### ISSUE TITLE
编译的过程中，报 'list' file not found

### ISSUE THREAD

**Issue by Ryan0520** [Tencent/wcdb#10]
编译的过程中，报 'list' file not found，这个怎么整？整个安装逻辑是按照guidelines来的

**Comment by RingoD** [comment]
WCDB是Objective-C++的库，需要修改你的文件名后缀为.mm

**Comment by lsqswl** [comment]
一样这个错误。只是编译wcdb的文件，没有我们自己的文件。不知道要改什么为.mm

**Comment by Juice007** [comment]
补充一句，`#import <WCDB/WCDB.h>`需要在.mm文件中导入，如果在.h文件中导入就可能会报这个错
