### ISSUE TITLE
iOS 分词

### ISSUE THREAD

**Issue by xt0612** [Tencent/wcdb#100]
再看代码时，看到createVirtualTableOfName:usingModule:withClass:方法，该方法是不是支持全文搜索建'VIRTUAL TABLE'，有没有文档说明WCDB对分词的支持

**Comment by RingoD** [comment]
@xt0612 
是的，这里留了个virtual table的接口。virtual table也可以用ORM创建。
但FTS暂时没有直接的支持。开发者可以通过WINQ自行组装。

FTS的挑战在于，如何提供一个好用、通用、高效的实现与接口。
我们会在近期的版本中实现该功能，敬请期待。
