### ISSUE TITLE
In version 2.0.1, the database was changed from encrypted to unencrypted

### ISSUE THREAD

**Issue by BaronWj** [Tencent/wcdb#1000]
### The language of WCDB

> e.g. Objective-C

### The version of WCDB

> e.g. v2.0.1

### The platform of WCDB

> e.g. iOS, 

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

Is there a direct way to use the encrypted database instead of the unencrypted one in version 2.0.1? Do you need data migration?

**Comment by BaronWj** [comment]
Is there a direct way to use the encrypted database instead of the unencrypted one in version 2.0.1? Do you need data migration?

**Comment by Qiuwen-chen** [comment]
Database migration is needed, but currently WCDB does not support migrating data from an encrypted database to an unencrypted database. It may be supported in the next version.

**Comment by BaronWj** [comment]
Thanks!

**Comment by BaronWj** [comment]
Whether the database supports changing from encrypted to unencrypted in version 2.0.4

**Comment by Qiuwen-chen** [comment]
Not yet. It will be supported in next version. Please wait.
