### ISSUE TITLE
Whether wcdb is listening to a db created by a module other than its own

### ISSUE THREAD

**Issue by BaronWj** [Tencent/wcdb#1002]
### The language of WCDB

> e.g. Objective-C

### The version of WCDB

> e.g. v1.0.7.5

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

Whether wcdb is listening to a db created by a module other than its own

**Comment by Qiuwen-chen** [comment]
You should build wcdb as a dynamic library.

**Comment by BaronWj** [comment]
target 'SQLDemo' do
 pod 'WCDB', '~> 1.0.7.5'
end

I can still listen to DB that is not created by wcdb using the dynamic library。

**Comment by Qiuwen-chen** [comment]
Upgrade to v2.0.4 and try again.

**Comment by BaronWj** [comment]
Has been tested in 2.0.1, he is no problem. Is there another way to fix this in 1.0.7.5?

**Comment by Qiuwen-chen** [comment]
NO
