### ISSUE TITLE
XCode15 ，carthage 报错

### ISSUE THREAD

**Issue by DrunkardSworder** [Tencent/wcdb#1007]
### The language of WCDB

> e.g. Swift 

### The version of WCDB

> e.g. v2.0.4

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g., Carthage

### What's the issue?

-> % carthage update --use-xcframeworks --platform iOS
*** Fetching WCDB
*** Checking out WCDB at "v2.0.4"
*** xcodebuild output can be found in /var/folders/x1/rv52g97d4xb4dkskgvkyv4wc0000gn/T/carthage-xcodebuild.SBj3gs.log
*** Downloading WCDB binary at "WCDB 2.0.4"
*** Building scheme "WCDBCpp" in WCDB.xcodeproj
*** Building scheme "WCDB" in WCDB.xcodeproj
*** Building scheme "WCDBObjc" in WCDB.xcodeproj
*** Building scheme "WCDBSwift" in WCDB.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/droog/Work/Project/Beth/Carthage/Checkouts/WCDB/src/WCDB.xcodeproj -scheme WCDBSwift -configuration Release -derivedDataPath /Users/droog/Library/Caches/org.carthage.CarthageKit/DerivedData/15.0_15A240d/WCDB/v2.0.4 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/x1/rv52g97d4xb4dkskgvkyv4wc0000gn/T/WCDB SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/droog/Work/Project/Beth/Carthage/Checkouts/WCDB)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/x1/rv52g97d4xb4dkskgvkyv4wc0000gn/T/carthage-xcodebuild.SBj3gs.log

**Comment by Qiuwen-chen** [comment]
get

**Comment by enefry** [comment]
+1

**Comment by huicongfu** [comment]
+1

**Comment by longjun-9** [comment]
+1

**Comment by Qiuwen-chen** [comment]
Fixed in v2.1.0
