### ISSUE TITLE
YYKit中的YYKVStorage，崩溃在sqlite3_exec调用上，请问如何解决？

### ISSUE THREAD

**Issue by jozdee** [Tencent/wcdb#1009]
YYKit中的YYKVStorage，崩溃在sqlite3_exec调用上，请问如何解决？

(BOOL)_dbExecute:(NSString *)sql {
if (sql.length == 0) return NO;
if (![self _dbCheck]) return NO;

char *error = NULL;
int result = sqlite3_exec(_db, sql.UTF8String, NULL, NULL, &error);
if (error) {
if (_errorLogsEnabled) NSLog(@"%s line:%d sqlite exec error (%d): %s", FUNCTION, LINE, result, error);
sqlite3_free(error);
}

return result == SQLITE_OK;
}

**Comment by jozdee** [comment]
其他还有一些第三方库也会使用 sqlite3_exec 系统方法

**Comment by jozdee** [comment]
![1697423693820](https://github.com/Tencent/wcdb/assets/10413288/13127749-7733-44a1-a045-155e13193224)
打包动态库，又出现这个错误

**Comment by Qiuwen-chen** [comment]
This is just a common library conflict and compilation problem, learn how to solve it yourself.
