### ISSUE TITLE
Potential memleak in android/jni/com_tencent_wcdb_database_SQLiteConnection.cpp

### ISSUE THREAD

**Issue by icy17** [Tencent/wcdb#1010]
### What's the issue?
in android/jni/com_tencent_wcdb_database_SQLiteConnection.cpp: 425
Calling [sqlite3_open_v2](https://github.com/Tencent/wcdb/blob/master/android/jni/com_tencent_wcdb_database_SQLiteConnection.cpp#L425C46-L425C48) without releasing it cause a memleak.

**Comment by Qiuwen-chen** [comment]
WCDB Android will be deprecated. WCDB Java is developing, please wait.
