### ISSUE TITLE
mac上编译Android的so库报找不到z-lib

### ISSUE THREAD

**Issue by ichenchen** [Tencent/wcdb#1011]
version> cmake ./ -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=21 -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=/Users/john/Documents/android-ndk/android-ndk-r20b && cmake
-- PLATFORM:
-- ---- BUILD FOR ANDROID ----
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
z-lib
    linked by target "WCDB" in directory /Users/john/Documents/iCollections/code/opensource/wcdb/tools/version

-- Configuring incomplete, errors occurred!
See also "/Users/john/Documents/iCollections/code/opensource/wcdb/tools/version/CMakeFiles/CMakeOutput.log".
See also "/Users/john/Documents/iCollections/code/opensource/wcdb/tools/version/CMakeFiles/CMakeError.log".

**Comment by YvesZHI** [comment]
我在Ubuntu 20.04.6 LTS上碰到了同样的问题，请问怎么解决？
