### ISSUE TITLE
编译Android的so库后要怎么在Android项目中使用，没有配套的java层的api

### ISSUE THREAD

**Issue by ichenchen** [Tencent/wcdb#1012]
参照C++ 安装与兼容性中的Android编译说明已成功编译了so文件，但是没有配套的java层调用的api
https://github.com/Tencent/wcdb/wiki/C++-%e5%ae%89%e8%a3%85%e4%b8%8e%e5%85%bc%e5%ae%b9%e6%80%a7

![image](https://github.com/Tencent/wcdb/assets/6995186/083bf2c6-287a-45cc-940b-3cd8d43339e6)
![image](https://github.com/Tencent/wcdb/assets/6995186/70638c43-8c82-4831-85e9-5417b733193c)

**Comment by ichenchen** [comment]
还有个问题，就是为啥编译后的so文件有52M，远程依赖引入的wcdb1.08版本的so文件只有1.9M

**Comment by 0x1306a94** [comment]
> 还有个问题，就是为啥编译后的so文件有52M，远程依赖引入的wcdb1.08版本的so文件只有1.9M

没有strip吧，你应该看最终apk 里面的大小吧

**Comment by Qiuwen-chen** [comment]
WCDB C++ is only for C++. WCDB Java is under developing, please wait. 

And we will also improve the build script in the next version to reduce the size of the product.
