### ISSUE TITLE
虚拟表中的数据如何更新

### ISSUE THREAD

**Issue by szweee** [Tencent/wcdb#1016]
### The language of WCDB

> Swift 

### The version of WCDB

> v2.0.4

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> 虚拟表中的数据如何更新呢？insertOrReplace和update接口都尝试了，都无法更新虚拟表中的数据，但是insert和delete都没问题

**Comment by Qiuwen-chen** [comment]
Please give an example.

**Comment by szweee** [comment]
> Please give an example.

Condition写错了，现在可以了。谢谢
