### ISSUE TITLE
我这边测试WCDB比FMDB慢了很多，请帮我看下是不是什么优化项没有设置

### ISSUE THREAD

**Issue by xfz211811** [Tencent/wcdb#1017]
### The language of WCDB

Objective-C

### The version of WCDB

最新的

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

//数据模型 Subtest 按照WCTColumnCoding转为jsondata

@interface Subtest : NSObject<WCTColumnCoding>
@property (nonatomic, strong) NSString *identifer;
@property (nonatomic, strong) NSString *content;
@property (nonatomic, strong) NSString *content1;
@property (nonatomic, strong) NSString *content2;
@property (nonatomic, assign) int number;
@end

@interface Test : NSObject<WCTTableCoding>
@property (nonatomic, strong) NSString *identifer;
@property (nonatomic, strong) NSString *content;
@property (nonatomic, strong) Subtest *sub;
WCDB_PROPERTY(identifer)
WCDB_PROPERTY(content)
WCDB_PROPERTY(sub)
@end

//建表语句
    NSString *wPath = [NSString stringWithFormat:@"%@/Documents/wcdb/wcdb.db",NSHomeDirectory()];
    WCTDatabase *database = [[WCTDatabase alloc] initWithPath:wPath];
    [database createTable:@"test" withClass:Test.class];
    
    NSString *fPath = [NSString stringWithFormat:@"%@/Documents/fmdb/fmdb.db",NSHomeDirectory()];
    FMDatabase *db = [FMDatabase databaseWithPath:fPath];
    db.shouldCacheStatements = YES;
    [db open];
    BOOL aaa = [db executeStatements:@"PRAGMA journal_mode = WAL"];
    aaa = [db executeStatements:@"PRAGMA page_size=4096"];
    aaa = [db executeUpdate:@"PRAGMA cache_size=-2000"];
    aaa = [db executeUpdate:@"create table if not exists test (identifer text primary key not null, content text, sub BLOB)"];

//执行测试

     fmdb插入10000条
        [db beginTransaction];
        for (int i = 0;i < 10000;i++)
        {
            NSString *key = [NSString stringWithFormat:@"%d",i];
            test.identifer = key;
            [db executeUpdate:@"INSERT OR REPLACE INTO test VALUES (?,?,?)",test2.identifer,test2.content,[test2.sub archivedWCTValue]];
        }
       [db commit];
        NSTimeInterval t2 = [[NSDate date] timeIntervalSinceDate:s2];

  wcdb插入10000条
        NSDate *s3 = [NSDate date];
        [database runTransaction:^BOOL(WCTHandle * _Nonnull) {
            for (int i = 0;i < 10000;i++)
            {
                NSString *key = [NSString stringWithFormat:@"%d",i];
                test.identifer = key;
                [database insertOrReplaceObject:test intoTable:@"test"];
            }
            return YES;
        }];
        NSTimeInterval t3 = [[NSDate date] timeIntervalSinceDate:s3]; 
wcdb 平均：0.77    fmdb平均：0.13

  fmdb查询10000条
        NSDate *s2 = [NSDate date];
        [db beginTransaction];
        for (int i = 0;i < 10000;i++)
        {
            NSString *key = [NSString stringWithFormat:@"%d",i];
            FMResultSet *ret = [db executeQuery:@"select * from test where identifer == ?",key];
            [ret next];
            Test *test = [Test toTest:ret];  //转对象包括Subtest
            [ret close];
            NSAssert(test, @"22222");
        }
        [db commit];
        NSTimeInterval t2 = [[NSDate date] timeIntervalSinceDate:s2];

wcdb查询10000条
        NSDate *s3 = [NSDate date];
        [database runTransaction:^BOOL(WCTHandle * _Nonnull) {
            for (int i = 0;i < 10000;i++)
            {
                NSString *key = [NSString stringWithFormat:@"%d",i];
                Test *test = [database getObjectOfClass:Test.class fromTable:@"test" where:Test.identifer == key];
            }
            return YES;
        }];
        
        NSTimeInterval t3 = [[NSDate date] timeIntervalSinceDate:s3];

fmdb:0.19 wcdb:1.146

同在事务内操作 wcdb就是慢很多 不知道哪里写的不对

**Comment by Qiuwen-chen** [comment]
For batch reads and writes, you can use getObjects and insertObjects interface. For scenarios requiring high performance, you can also use WCTPreparedStatement to cache SQL statements

**Comment by xfz211811** [comment]
> For some complex scenarios requiring high performance, you can also use WCTPreparedStatement to cache SQL statements

对于fmdb使用的是单条语句 wcdb使用批量语句是不是会不平等啊

**Comment by Qiuwen-chen** [comment]
There is automatic statement caching in FMDB. You can set shouldCacheStatements to NO to turn off this cache and compare again.
