### ISSUE TITLE
运行在 iOS 17 真机上，Core.cpp 库 Crash

### ISSUE THREAD

**Issue by ethanchiao2023** [Tencent/wcdb#1019]
### The language of WCDB
> Swift

### The version of WCDB
> v2.0.4

### The platform of WCDB
> iOS 17

### The installation of WCDB
> Cocoapods

### What's the issue?

![WCDB 错误](https://github.com/Tencent/wcdb/assets/28699255/b82fffa6-7fca-4343-adc4-080af3f826b8)
> 运行在 iOS 17 系统的真机上，刚启动起来就会 Crash 在图示位置。但是在 iOS 15.7.9 的系统上运行没问题。

**Comment by Qiuwen-chen** [comment]
Please give us a demo project to reproduce this problem

**Comment by LockeSwift** [comment]
> Please give us a demo project to reproduce this problem

我在 iOS 14.7.1  iPhone 11 上也遇到了此类问题，初始化数据库失败
![image](https://github.com/Tencent/wcdb/assets/26478789/e2b6d351-1975-4a14-9589-7b41e13a994a)

**Comment by LockeSwift** [comment]
> > Please give us a demo project to reproduce this problem
> 
> 我在 iOS 14.7.1 iPhone 11 上也遇到了此类问题，初始化数据库失败 ![image](https://user-images.githubusercontent.com/26478789/283307600-e2b6d351-1975-4a14-9589-7b41e13a994a.png)

Version：2.0.4

**Comment by Qiuwen-chen** [comment]
May be you can  try this: https://github.com/Tencent/wcdb/issues/1006
