### ISSUE TITLE
Compatible for iOS 11

### ISSUE THREAD

**Issue by RingoD** [Tencent/wcdb#102]

**Comment by RingoD** [comment]
The key of `userInfo` in `WCTError` must be `NSString` in iOS 11.

**Comment by dabing1022** [comment]
加一个：`NSError`类的userInfo的key必须是` NSString *`，涉及到类WCTError类里面使用的userInfo

**Comment by dabing1022** [comment]
`NSError`的`userInfo`的key在iOS11上只能是`NSString *`，涉及到了`WCTError`类

**Comment by RingoD** [comment]
fixed at https://github.com/Tencent/wcdb/commit/6455c9f57d314ee7e1901414aac5506b98c76394

**Comment by summerHearts** [comment]
Which branch of pod should I have?

**Comment by RingoD** [comment]
@summerHearts master

**Comment by summerHearts** [comment]
@RingoD  thanks

**Comment by tuluigi** [comment]
iOS11这个问题，在pod 版本什么时候更新？

**Comment by wangzzcloud** [comment]
同上

**Comment by RingoD** [comment]
@tuluigi  @wangzzcloud 预计本周内
