### ISSUE TITLE
为什么要设置SQLITE_MAX_VARIABLE_NUMBER为99

### ISSUE THREAD

**Issue by oqsh** [Tencent/wcdb#1020]
### The language of WCDB

Objective-C

### The version of WCDB

v2.0.1

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

看到WCDB2.0.1对应的WCDBOptimizedSQLCipher版本是1.4.0，然后1.4.0相比于之前的1.2.x（WCDB 1.x用的版本）新增了一个预编译宏SQLITE_MAX_VARIABLE_NUMBER=99（没设置的话，默认值是999）。

想了解一下为什么WCDB 2.0要特地把WCDB和WCDBOptimizedSQLCipher，这两个SDK中的SQLITE_MAX_VARIABLE_NUMBER都设置为99？

**Comment by Qiuwen-chen** [comment]
It's a long story. Has this affected you in any way?

**Comment by oqsh** [comment]
对的，因为我们这边计划有一个库用的是

**Comment by oqsh** [comment]
对的，因为我这边升级WCDBOptimizedSQLCipher后出了个问题: 因为SQL语句中的参数过多导致执行失败, 出错代码如下：
```
NSMutableArray<NSString *> *binds = @{}.mutableCopy;
NSUInteger count = nameIDs.count;// count数量为200
for (NSUInteger index = 0; index < count; index++ ) {
    [binds addObject:@"?"];
}
NSString *sql = [NSString stringWithFormat:@"DELETE FROM %@ WHERE name_id IN (%@);", tableName, [binds componentsJoinedByString:@","]];
FMDatabase *db = self.database;
NSError *error = nil;
[db executeUpdate:sql values:trackIDs error:&error];
```
然后我修复了这个参数过多导致SQL语句执行失败的问题（不使用 ? 代替in后面的内容），修复代码如下：
```
NSString *sql =[NSString stringWithFormat:@"DELETE FROM %@ WHERE track_id IN ( '%@' );", tableName, [nameIDs componentsJoinedByString:@"','"]];
```

但是因为我的项目中代码量很大，不确定其他地方是否会有类似问题 && 难以确保后面其他研发是否会这样裸用sql，
所以我这边计划把WCDBOptimizedSQLCipher的podspec中的SQLITE_MAX_VARIABLE_NUMBER=99这句干掉。

可我又不确定把这个宏干掉后，会不会导致WCDB、WCDBOptimizedSQLCipher这两个SDK出现其他问题，所以才会有本次提问的问题

**Comment by Qiuwen-chen** [comment]
If you don't use the data migration feature in WCDB, this will not have a negative impact.
