### ISSUE TITLE
  'WCDB.swift', '~> 2.0.3' 真机运行12.5.5创建database时崩溃

### ISSUE THREAD

**Issue by xuchaofei** [Tencent/wcdb#1022]
### The language of WCDB

swift

### The version of WCDB

> e.g. v2.0.3

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

崩溃
![Uploading 截屏2023-11-13 17.46.26.png…]()

```[tasklist]
### Tasks
```

**Comment by xuchaofei** [comment]
![Uploading 截屏2023-11-13 17.46.26.png…]()

**Comment by xuchaofei** [comment]
xcode 版本 Version 15.0.1 (15A507) 其他版本没问题。 这个版本13.0以上的手机也没问题

**Comment by Qiuwen-chen** [comment]
May be you can try this: https://github.com/Tencent/wcdb/issues/1022
