### ISSUE TITLE
iOS 扩展应用，在APP Group共享文件夹，无法创建数据库

### ISSUE THREAD

**Issue by ErvinSun** [Tencent/wcdb#1023]
在APP Group的共享文件夹中，使用NSFileManager 有权限创建文件夹，但是使用WCDB 自动创建数据库，首次提示创建成功，但是文件路径中是没有数据库文件的，再次创建提示空文件

**Comment by Qiuwen-chen** [comment]
Please give us more detail, or just give us a demo project to reproduce it.

**Comment by ErvinSun** [comment]
![Snipaste_2023-11-16_16-04-41](https://github.com/Tencent/wcdb/assets/11531668/dc2d1496-22ab-4beb-979e-a3115c91b88f)

app 启动 ->  正常创建数据库 然后返回错误，如果是使用WCDB创建到decuments下的话是正常的，然后在app group文件路径下的话就会失败
app是能正常访问app group 文件路径以及进行读写，使用fmdb进行创建也是ok，因为fmdb是用NSFilemanager创建的文件，所以怀疑是文件创建指令权限的问题

**Comment by Qiuwen-chen** [comment]
Create a WCTDatabase object will never cause any error. You only need to get error when its API returns NO.

**Comment by ErvinSun** [comment]
..... 没有error  但是对应路径下，数据库并没有创建成功，一切都正常，但是数据库并没有被创建，因为app group需要在开发者账号授权，所以我没法提供demo... 但是算了，有空我自己看源码吧

**Comment by Qiuwen-chen** [comment]
The database is not created until you read and write data.

**Comment by ErvinSun** [comment]
但是创建表的时候会提示失败，然后这时候拿到database，获取error会返回[ERROR:10 , empty directory]
![Snipaste_2023-11-17_14-44-25](https://github.com/Tencent/wcdb/assets/11531668/6ff8e482-db9c-470a-b41e-291e16e9a008)
然后创建到documents目录下的话是正常的，只有说创建到app group目录下会失败，并且如果是使用OC自己的文件管理类创建文件也是正常的，所以我怀疑说是文件创建权限指令的问题

**Comment by ErvinSun** [comment]
你好，我在项目里尝试使用mkdir进行文件目录的创建，然后mkdir在项目沙盒里面使用指定权限是可以进行文件操作的，但是对于app group目录下可能不太行，有可能是苹果对于这些文件夹的授权要求更高，所以通过oc自带文件管理器NSFileManager获取了权限可以进行文件操作，但是mkdir确实不太行，而WCDB应该是使用mkdir进行文件操作的

int result = mkdir(path, S_IRWXU | S_IRGRP | S_IXGRP | S_IROTH | S_IXOTH); 
返回的一直是-1，我也试过755，以及777

**Comment by Qiuwen-chen** [comment]
You can use NSFileManager to create that folder in advance.
