### ISSUE TITLE
WCDBSwift2.0.4无法创建虚拟表

### ISSUE THREAD

**Issue by xboy-im** [Tencent/wcdb#1024]
### The language of WCDB

> Swift

### The version of WCDB

> 2.0.4

### The platform of WCDB

>  iOS16，iPad

### The installation of WCDB

> Cocoapods

### What's the issue?

> 无法创建虚拟表，代码如下

模型定义：
<img width="661" alt="截屏2023-11-16 16 21 08" src="https://github.com/Tencent/wcdb/assets/5466295/db8b4f06-3f1d-4528-b939-b6925beb9233">

创建代码：
`try? database.create(virtualTable: boardFTSTable, of: BoardFTS.self)`

报错信息：

> [ERROR] Code:Error Source:SQLite,Path:/var/mobile/Containers/Data/Application/2E818245-2C88-4ED5-A555-CFE7399DE4A8/Documents/boards/db/boards.db,Message:no such tokenizer: wcdb_verbatim,SQL:CREATE VIRTUAL TABLE IF NOT EXISTS BoardFTS USING fts5(tokenize = 'wcdb_verbatim', id, name)

**Comment by xboy-im** [comment]
改成 `BindVirtualTable(withModule: .FTS3, and: BuiltinTokenizer.Simple)` 虚拟表能创建成功，使用文档里面的`BindVirtualTable(withModule: .FTS5, and: BuiltinTokenizer.Verbatim)`无法创建

**Comment by Qiuwen-chen** [comment]
You should call database.add(tokenizer: BuiltinTokenizer.Verbatim) to register this tokenizer to you database
