### ISSUE TITLE
Xcode 15 crash

### ISSUE THREAD

**Issue by 476793556** [Tencent/wcdb#1025]
### The language of WCDB
Objective-C

### The version of WCDB
1.1.0

### The platform of WCDB
 iOS

### The installation of WCDB
Cocoapods

### What's the issue?
<img width="1091" alt="截屏2023-11-18 18 05 12" src="https://github.com/Tencent/wcdb/assets/8399946/cefc314d-f346-4185-be4f-52a5e9e5428b">

Thank you for providing such a useful database framework, I have used it in many projects, and it has been fine before. After upgrading xcode15 for packaging, there was a crash, and iOS 11 and ios 12 apps crashed upon startup. After adding -ld64 to the other link flag, the compilation run will not crash, but the archive package will still crash, how to solve this? Looking forward to your reply

**Comment by Qiuwen-chen** [comment]
May be this issue might help you: https://github.com/Tencent/wcdb/issues/1006

**Comment by Qiuwen-chen** [comment]
In our opinion, xcode15 still has some bugs that prevent WeChat from using it to compile online packages, so I haven’t spent much energy looking at xcode15-related issues.

**Comment by 476793556** [comment]
Thank you for your reply. Just now, I removed the third-party libraries relied on in the project one by one for investigation. It has been found that the problem is not caused by wcdb, but by other third-party libraries. I will continue to use wcdb!

**Comment by song-jay** [comment]
> Thank you for your reply. Just now, I removed the third-party libraries relied on in the project one by one for investigation. It has been found that the problem is not caused by wcdb, but by other third-party libraries. I will continue to use wcdb!

请问怎么解决的，遇到一样的问题

**Comment by song-jay** [comment]
> Thank you for your reply. Just now, I removed the third-party libraries relied on in the project one by one for investigation. It has been found that the problem is not caused by wcdb, but by other third-party libraries. I will continue to use wcdb!

I had same problem. How to fix it ?
