### ISSUE TITLE
Cocoapods导入后 死活找不到头文件。

### ISSUE THREAD

**Issue by CrazyBWT** [Tencent/wcdb#1026]
### The language of WCDB
Objective-C

### The platform of WCDB
iOS

### What's the issue?
'WCDBObjc/WCDBObjc.h' file not found 
Pods/Headers/Public里面也没有WCDB文件夹
但是#import时，代码自动补全显示有WCDBObjc.h头文件，好奇怪。我该怎么办？

**Comment by Qiuwen-chen** [comment]
Google it
