### ISSUE TITLE
 WCDBOptimizedSQLCipher 无法下载

### ISSUE THREAD

**Issue by 937447974** [Tencent/wcdb#1030]
### The language of WCDB
> Swift

### The version of WCDB
> 2.0.3

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> pod 'WCDBOptimizedSQLCipher', '~> 1.4.2'
> 报错，在 https://github.com/Tencent/sqlcipher.git 项目中没有 1.4.2的tag

**Comment by Qiuwen-chen** [comment]
pod repo update
