### ISSUE TITLE
Database close

### ISSUE THREAD

**Issue by 0x1306a94** [Tencent/wcdb#1033]
### The language of WCDB

> C++

### The version of WCDB

> v2.0.4

### The platform of WCDB

> macOS

### The installation of WCDB

> Git clone

### What's the issue?

* Create Database and configure traceSQL callback.
Then after performing certain operations, manually call close to close the Database. and release the Database object.
After calling close for a period of time, it is observed that the callback of traceSQL is executed again, and the following SQL is output.
```sql
PRAGMA journal_mode
PRAGMA checkpoint_fullfsync = TRUE
PRAGMA temp_store = 1
PRAGMA journal_mode
PRAGMA checkpoint_fullfsync = TRUE
PRAGMA temp_store = 1
```
* Through breakpoint debugging, it was found that it was triggered by doCheckpoint in OperationQueue.
* Under normal circumstances, after calling close, you should no longer operate the corresponding database, right?

**Comment by Qiuwen-chen** [comment]
Indeed, it can be improved.
