### ISSUE TITLE
关键字查找

### ISSUE THREAD

**Issue by mxh-mo** [Tencent/wcdb#1035]
求教：我想通过用户输入的文字，查找包含该关键字的商品，类似 String.contains 这样的语句，用WCDB应该怎样实现？
<img width="1176" alt="image" src="https://github.com/Tencent/wcdb/assets/16602188/47cc46a3-88f6-4f22-9af7-a521df1151f5">

**Comment by Qiuwen-chen** [comment]
You can use fts: https://github.com/Tencent/wcdb/wiki/Swift-%e5%85%a8%e6%96%87%e6%90%9c%e7%b4%a2

**Comment by mxh-mo** [comment]
太复杂了，这个库为什么做这么复杂，做的简单易用点，star应该会更多。后悔选用这个库了

**Comment by Qiuwen-chen** [comment]
Or user can just use goodsname.like("%\(name)%"), it is must slower.

**Comment by mxh-mo** [comment]
早说嘛，这么简单的方法，非得藏着掖着 
<img width="1051" alt="image" src="https://github.com/Tencent/wcdb/assets/16602188/e22541de-40c3-41cf-a2d6-f417a22fa45c">
