### ISSUE TITLE
源码引入，release环境报错：umbrella header 'WCDBBridging.h' not found

### ISSUE THREAD

**Issue by Miles-Matheson** [Tencent/wcdb#1041]
### The language of WCDB

> WCDBSwift

### The version of WCDB

> e.g. master

### iOS

> e.g. iOS, macOS or Android

### The installation of WCDB

> e Git clone

wcdb 在swift环境，使用源码引入 打包时候报错（pod引入正常，项目需要 只能使用源码引入），非项目自身原因，尝试了新建空项目依然复现。 报错如下：

<img width="574" alt="image" src="https://github.com/Tencent/wcdb/assets/19796675/7c529376-03b8-4ef1-8a74-db65fa73b485">
<img width="1011" alt="image" src="https://github.com/Tencent/wcdb/assets/19796675/45e0aea0-0eb2-4d6d-a1f1-0970deeb3392">

**Comment by Qiuwen-chen** [comment]
Give us a demo project to reproduce it.

**Comment by Miles-Matheson** [comment]
Demo已添加到附件，请查收~。


















At 2024-01-18 11:05:04, "qiuwen" ***@***.***> wrote:

Give us a demo project to reproduce it.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从网易163邮箱发来的超大附件推荐客户端极速下载
WCDBSwift_Demo.zip (157.32M, 2024年2月2日 11:32 到期)
下载

**Comment by Qiuwen-chen** [comment]
Sorry, I've been too busy to deal with it. The file you sent has expired. Can you try the newly released version 2.1.0 again?
