### ISSUE TITLE
[ERROR] Code:IOError when exec(StatementVacuum().vacuum()) 

### ISSUE THREAD

**Issue by mxh-mo** [Tencent/wcdb#1043]
when restart app run db?.exec(StatementVacuum().vacuum()) throw a IOError:
<img width="1362" alt="image" src="https://github.com/Tencent/wcdb/assets/16602188/2cc83b94-b8ec-4fdc-b466-5790f8073548">

**Comment by Qiuwen-chen** [comment]
Get, it will be fixed in next version, please wait.

**Comment by mxh-mo** [comment]
> Get, it will be fixed in next version, please wait.

Thankyou ~

**Comment by Qiuwen-chen** [comment]
Please try the `Database.vacuum(with:)` method in version 2.1.0
