### ISSUE TITLE
ThreadLocal crash

### ISSUE THREAD

**Issue by JackMaal** [Tencent/wcdb#1048]
### The language of WCDB

Swift 

### The version of WCDB

v2.0.4

### The platform of WCDB

 iOS

### The installation of WCDB

 Cocoapods

### What's the issue?

c++ crashes. How to solve?

<img width="811" alt="screenshot_131" src="https://github.com/Tencent/wcdb/assets/160700551/d34e9b33-1d69-49fa-8b2b-8fa2253953ed">

**Comment by Qiuwen-chen** [comment]
What is the crash rate? 
We have also encountered this problem, but the crash rate is less than 0.01‰ per day. So we won’t deal with this issue for now.

**Comment by JackMaal** [comment]
This crash occurs when extensive database migration is required. The crash is high.

**Comment by Qiuwen-chen** [comment]
I don't know what extensive database migration means, can you give more details? It would be better if you could provide a demo project to reproduce this problem.
