### ISSUE TITLE
微信的Swift开发

### ISSUE THREAD

**Issue by tysun** [Tencent/wcdb#1049]
您好。抱歉打扰了。您知道微信何时首次开始在其代码库中使用Swift语言吗？微信开始使用Swift时，有哪些功能或模块是用Swift编写的？2017年或更早的微信工程博客中是否提到了这些信息？或者您能否介绍我去询问了解这方面信息的人？谢谢。

**Comment by Qiuwen-chen** [comment]
It's not public.
