### ISSUE TITLE
Pods/WCDB.objc/src/common/core/sqlite/HandleNotification.cpp:247:9: No matching function for call to 'sqlite3_wal_checkpoint_handler'

### ISSUE THREAD

**Issue by LisonFan** [Tencent/wcdb#1050]
### The language of WCDB

> Objective-C

### The version of WCDB

> 2.0.4

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

![image](https://github.com/Tencent/wcdb/assets/9424775/8baa5c5e-fb2b-432e-866d-716511cb8ed1)

- Xcode: `15.2.0`
- iOS SDK: `17.2`
- WCDB.objc: `2.0.4`
- WCDBOptimizedSQLCipher: `1.4.3`

![image](https://github.com/Tencent/wcdb/assets/9424775/04247cd1-df56-4b88-9f41-b504142276b9)

**Comment by Qiuwen-chen** [comment]
The version of WCDBOptimizedSQLCipher should be 1.4.2.

**Comment by fremaksim** [comment]
add `pod 'WCDBOptimizedSQLCipher', '1.4.2'` in your podfile
