### ISSUE TITLE
Roadmap for Java or Kotlin?

### ISSUE THREAD

**Issue by ysy950803** [Tencent/wcdb#1052]
When is WCDB planning to provide support for Java or Kotlin API on the Android platform? It seems like Kotlin might be a better option. Do we have a planned timeline for these developments?

**Comment by ysy950803** [comment]
It appears that the development of WCDB has been primarily driven by iOS developers starting from version 2.0.

**Comment by Qiuwen-chen** [comment]
WCDB for Java/Kotlin will be released in this week.

**Comment by ysy950803** [comment]
@Qiuwen-chen Thanks for your support to Kotlin/Java. Any plan for Jetpack Room API?

**Comment by Qiuwen-chen** [comment]
Not such plan for now.

**Comment by ysy950803** [comment]
> Not such plan for now.

Can I rely on "com.tencent.wcdb:compat" to implement the previous WCDB Room interface?

**Comment by Qiuwen-chen** [comment]
You can have a try. It may work.

**Comment by ysy950803** [comment]
[WCDBRoomX](https://github.com/ysy950803/WCDBRoomX)

I've made some minor modifications to the previous WCDB library, providing the following compatibilities. Hopefully, this can be of some assistance to you Android developers out there.

- Adapt [WCDB](https://github.com/Tencent/wcdb/tree/room) to work with the latest version of Room
- Include support for the `@Upsert` annotation
- Ensure compatibility with the latest version of [SQLCipher](https://github.com/sqlcipher/sqlcipher-android)
