### ISSUE TITLE
XCode15.2可编译，但是打包会报错未找到sqlcipher

### ISSUE THREAD

**Issue by CorbinLeeBest** [Tencent/wcdb#1053]
XCode没升级之前都正常，升级到15.2之后运行可以，打包会报错。
Build input file cannot be found: '***（路径）/BuildProductsPath/DailyBuild-iphoneos/WCDBOptimizedSQLCipher/sqlcipher.framework/sqlcipher'.

**Comment by Qiuwen-chen** [comment]
Please try 2.1.0

**Comment by Annabelle1024** [comment]
> Please try 2.1.0

do you mean to update sqlcipher to 2.1.0? if so, which version
should i use for WCDB

**Comment by Qiuwen-chen** [comment]
> > Please try 2.1.0
> 
> do you mean to update sqlcipher to 2.1.0? if so, which version should i use for WCDB

WCDB 2.1.4

**Comment by Annabelle1024** [comment]
> > > Please try 2.1.0
> > 
> > 
> > do you mean to update sqlcipher to 2.1.0? if so, which version should i use for WCDB
> 
> WCDB 2.1.4

is there any other method? I tried to update WCDB to 2.1.4, but it requires Swift5, our app now still supports swift4. It's a big change, I can't update the Swift to 5 directly. I tried to add this command $(BUILT_PRODUCTS_DIR)/WCDBOptimizedSQLCipher/sqlcipher.framework/sqlcipher to runscript output file, it works when archive, but when I excute the app, WCBD dose not work, it could't query or save
<img width="994" alt="image" src="https://github.com/Tencent/wcdb/assets/9578160/e8e0c34a-63df-4d94-9daf-cc0a8695f43e">

**Comment by CorbinLeeBest** [comment]
> /BuildProductsPath/DailyBuild-iphoneos/WCDBOptimizedSQLCipher/sqlcipher.framework/sqlcipher'.

我是在other linker flags里面把/BuildProductsPath/DailyBuild-iphoneos/WCDBOptimizedSQLCipher/sqlcipher.framework/sqlcipher'.直接删掉。
添加 -ld64 和 -all_load
<img width="902" alt="image" src="https://github.com/Tencent/wcdb/assets/20700375/3c0a4ad9-e734-49bb-af85-591e41e7398a">

**Comment by Annabelle1024** [comment]
感谢回答，我马上试试



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月09日 11:25 |
| 收件人 | ***@***.***> |
| 抄送至 | Jing ***@***.***>***@***.***> |
| 主题 | Re: [Tencent/wcdb] XCode15.2可编译，但是打包会报错未找到sqlcipher (Issue #1053) |

/BuildProductsPath/DailyBuild-iphoneos/WCDBOptimizedSQLCipher/sqlcipher.framework/sqlcipher'.

我是在other linker flags里面把/BuildProductsPath/DailyBuild-iphoneos/WCDBOptimizedSQLCipher/sqlcipher.framework/sqlcipher'.直接删掉。
添加 -ld64 和 -all_load
image.png (view on web)

**Comment by CorbinLeeBest** [comment]
不好意思，刚才书写有误，删除的是之前项目other linker flags中的
-framework "WCDBSwift" 
-force_load $(BUILT_PRODUCTS_DIR)/WCDBOptimizedSQLCipher/sqlcipher.framework/sqlcipher

**Comment by Annabelle1024** [comment]
嗯嗯，我能懂你的意思，太感谢了.



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月09日 11:35 |
| 收件人 | ***@***.***> |
| 抄送至 | Jing ***@***.***>***@***.***> |
| 主题 | Re: [Tencent/wcdb] XCode15.2可编译，但是打包会报错未找到sqlcipher (Issue #1053) |

不好意思，刚才书写有误，删除的是之前项目other linker flags中的
-framework "WCDBSwift"
-force_load $(BUILT_PRODUCTS_DIR)/WCDBOptimizedSQLCipher/sqlcipher.framework/sqlcipher

**Comment by Annabelle1024** [comment]
> 不好意思，刚才书写有误，删除的是之前项目other linker flags中的 -framework "WCDBSwift" -force_load $(BUILT_PRODUCTS_DIR)/WCDBOptimizedSQLCipher/sqlcipher.framework/sqlcipher

<img width="658" alt="image" src="https://github.com/Tencent/wcdb/assets/9578160/1a3329a2-ece1-45af-a376-733b92d37064">
报错说没有ld64, 这个是什么呢
