### ISSUE TITLE
Privacy Manifes

### ISSUE THREAD

**Issue by JuneLee61** [Tencent/wcdb#1055]
Need Privacy Manifest

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by Qiuwen-chen** [comment]
WCDB does not collect any private information.

**Comment by JuneLee61** [comment]
感谢你的回复，更新到最新版后，确实没有手机隐私相关信息，之前是使用旧版本1.0.8.2，有使用到mach_absolute_time这个API

**Comment by JuneLee61** [comment]
> WCDB does not collect any private information.

感谢你的回复，更新到最新版后，确实没有手机隐私相关信息，之前是使用旧版本1.0.8.2，有使用到mach_absolute_time这个API
