### ISSUE TITLE
XCode Swift Package Manager安装后，真机运行会崩溃

### ISSUE THREAD

**Issue by longjun-9** [Tencent/wcdb#1056]
### The language of WCDB

Swift

### The version of WCDB

v2.1.1

### The platform of WCDB

iOS,

### The installation of WCDB

通过Xcode Swift Package Manager安装

### What's the issue?
模拟器运行没有问题，但是真机编译后启动会崩溃。
dyld[524]: Library not loaded: @rpath/WCDBSwiftDynamic.framework/WCDBSwiftDynamic
  Referenced from: <606E6CD6-48E7-38D2-A833-D6C6B2FD3852>
![screenshot-20240313-185828](https://github.com/Tencent/wcdb/assets/4412991/5a1cdfc5-cf8e-451c-85f8-5085889454ab)

**Comment by Qiuwen-chen** [comment]
You need to copy the dynamic framework into you app package. Just google how to config.
