### ISSUE TITLE
如何获得修改 or 删除数据的受影响行数

### ISSUE THREAD

**Issue by qingiqng99** [Tencent/wcdb#1057]
### The language of WCDB

> Swift 5.0

### The version of WCDB

> v2.1.0

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> 通过
> try database?.update(table: tableName, on: propertyConvertibleList, with: entity, where: condition)
> 修改数据后，怎么获得受影响的行数。

**Comment by Qiuwen-chen** [comment]
let update = database.prepareUpdate(table: tableName, on: propertyConvertibleList).where(condition)
try update.execute(with: entity)
print(update.change)
