### ISSUE TITLE
查找表A的id在一个集合内的数据

### ISSUE THREAD

**Issue by qingiqng99** [Tencent/wcdb#1058]
### The language of WCDB

> Swift 5.0

### The version of WCDB

> v2.1.0

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> 通过
> select * from A where A.id in (1,2,3,4)
> 查找表A的id在一个集合内的数据
> 这样的in，怎么处理？

**Comment by Qiuwen-chen** [comment]
Use A.Properties.id.in(1,2,3,4)
