### ISSUE TITLE
'config.h' file not found

### ISSUE THREAD

**Issue by devhail** [Tencent/wcdb#1059]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

swift

### The version of WCDB

> e.g. v1.0.5

v2.1.0

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
![WechatIMG70](https://github.com/Tencent/wcdb/assets/19485110/201bbe5a-09eb-41ca-a833-be142c29a760)

> Explain what you want by example or code **in English**.

How to solve this error

**Comment by Qiuwen-chen** [comment]
You may need to execute ‘pod install’ again.

**Comment by devhail** [comment]
> You may need to execute ‘pod install’ again.
After doing what you said, the problem is still there

**Comment by Annabelle1024** [comment]
.ignore里面把config.h给忽略了, 导致pod install下来后, 没有这个类, 可以尝试自己私有化这个项目, 把.ignore修改掉

**Comment by gga122** [comment]
在集成时发现了同样的问题
经过排查发现是这样的

复现路径：
1. 工程使用Cocoapods集成WCDB.swift和Logan的日志库
2. 配置里面默认`Use Header Maps` 为`YES`

原因：
查看编译过程，发现hmap中存在`config.h`的两份映射, 第二份project的hmap包含了Logan库映射关系。自测手动调用clang编译命令，去掉project.hmap的参数后不会报错

解决方法：
修改WCDBOptimizedSQLCipher工程中`Use Header Maps` 为 `NO` 即可

@Qiuwen-chen 可以验证下

**Comment by qjnlz307** [comment]
如果 Podfile 中有多个库包含 config.h，编译时 WCDBOptimizedSQLCipher 中 sqliteInt.h 的 #include "config.h"  会提示找不到 config.h 。

可以改为绝对路径  #include "../config.h" 就可以了

@Qiuwen-chen 这种情况可以考虑兼容一下
