### ISSUE TITLE
ios连表查询

### ISSUE THREAD

**Issue by dengwant** [Tencent/wcdb#106]
/*
 SELECT contact.nickname, contact_ext.headImg
 FROM contact, contact_ext
 WHERE contact.name==contact_ext.name
 */
WCTMultiSelect *multiSelect = [[database prepareSelectMultiObjectsOnResults:{
    Contact.nickname.inTable(@"contact"), 需要获得两个表中的所有列，要把全部列列出来么，AllProperties不能用么
	ContactExt.nickname.inTable(@"contact_ext")
} fromTables:@[ @"contact", @"contact_ext" ]] where:Contact.name.inTable(@"contact") == ContactExt.name.inTable(@"contact_ext")];

while ((multiObject = [multiSelect nextMultiObject])) {
    Contact *contact = (Contact *) [multiObject objectForKey:@"contact"];
    ContactExt *contact = (ContactExt *) [multiObject objectForKey:@"contact_ext"];
    //...
}

**Comment by RingoD** [comment]
与SQLite不同，这里取出数据后还要组合成object，如果不指定的话，框架层是无法知道数据属于哪个表，并且应该组合成什么类。

你可以通过以下语句简化操作。
```
WCTPropertyList selection;
for (const WCTProperty& property : Contact.allProperties) {
    selection.push_back(property.inTable(@"contact"));
}
for (const WCTProperty& property : ContactExt.allProperties) {
    selection.push_back(property.inTable(@"contact_ext"));
}
//[database prepareSelectMultiObjectsOnResults: selection ....

**Comment by dengwant** [comment]
收到！
