### ISSUE TITLE
How to implement "public var rawCPPObj: UnsafeMutablePointer<CPPObject>" protocol method

### ISSUE THREAD

**Issue by devhail** [Tencent/wcdb#1060]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

swift

### The version of WCDB

> e.g. v1.0.5

2.1.0

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
<img width="961" alt="image" src="https://github.com/Tencent/wcdb/assets/19485110/02eca808-eb9d-4d0c-96dd-a70c22b63522">

> Explain what you want by example or code **in English**.

How to implement "public var rawCPPObj: UnsafeMutablePointer<CPPObject>" protocol method

**Comment by Qiuwen-chen** [comment]
You do not need to implement this protocol. You can use the classes that already implements it, such as StatementInsert, StatementUpdate, StatementSelect...
