### ISSUE TITLE
How to define "notindexed" for FTS Virtual Table with swift WCDB v1.0.8.2？

### ISSUE THREAD

**Issue by BAOU** [Tencent/wcdb#1063]
### The language of WCDB

Swift

### The version of WCDB

v1.0.8.2

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.

> Explain what you want by example or code **in English**.

class SampleFTSData: TableCodable {
    var name: String?
    var content: String?
    enum CodingKeys: String, CodingTableKey {
        typealias Root = SampleFTSData
        static let objectRelationalMapping = TableBinding(CodingKeys.self)
        case name
        case content
        static var virtualTableBinding: VirtualTableBinding? {
            return VirtualTableBinding(with: .fts3, and: ModuleArgument(with: .WCDB))
        }
    }
}

I do not want to create index for "name", how to define TableConstraint with v1.0.8.2 version?

**Comment by Qiuwen-chen** [comment]
Please use the latest version.
