### ISSUE TITLE
'WCTBridgeProperty+CPP.h' file not found in WCTTableCoding.h

### ISSUE THREAD

**Issue by BainJ** [Tencent/wcdb#1065]
### The language of WCDB

Objective

### The version of WCDB

v2.1.1

### The platform of WCDB

iOS

### The installation of WCDB

Carthage

### What's the issue?

![image](https://github.com/Tencent/wcdb/assets/5266081/6870d84c-6401-4e1b-9572-429a5af61b54)

When using WCDBObjc with Carthage, if you encounter the error message 'WCTBridgeProperty+CPP.h' file not found in WCTTableCoding.h

You need to check the following option for 'WCTBridgeProperty+CPP.h':
![image](https://github.com/Tencent/wcdb/assets/5266081/18e508c6-8cfb-4e78-9b94-bdd98efc3f86)

**Comment by Qiuwen-chen** [comment]
It seems OK. This header file has been marked as public and should be available.

**Comment by Qiuwen-chen** [comment]
Will be fix soon.

**Comment by Qiuwen-chen** [comment]
Fixed in v2.1.2
