### ISSUE TITLE
Failed to build wcdb as submodule in CMake

### ISSUE THREAD

**Issue by watergear** [Tencent/wcdb#1066]
### The language of WCDB
> C++
### The version of WCDB
> 2.1.0
### The platform of WCDB
> Ubuntu
### The installation of WCDB
> Git clone

### What's the issue?
I try to build **wcdb** as submodule in CMake project.
**CMakeLists.txt** like:
```
cmake_minimum_required(VERSION 3.13)

project(test_dep_wcdb)

add_subdirectory(wcdb/src)

add_executable(test_dep_wcdb wcdb_sample_test.cpp)
add_dependencies(test_dep_wcdb WCDB)

target_link_libraries(test_dep_wcdb WCDB)
```
Also there are the file **wcdb_sample_test.cpp** and folder **wcdb** in the same folder of **CMakeLists.txt**.
which **wcdb** is from [wcdb v2.1.0](https://github.com/Tencent/wcdb/commit/fb30db372ed253aff2ae8213c135fdfd98def803)
which **wcdb_sample_test.cpp** like:
```
#include <iostream>
#include "WCDBCpp.h"

class Sample {
public:
    Sample() {}
    Sample(int identifier, const std::string& content) : identifier(identifier), content(content) {}
    int identifier;
    std::string content;
    WCDB_CPP_ORM_DECLARATION(Sample)
};

WCDB_CPP_ORM_IMPLEMENTATION_BEGIN(Sample)
WCDB_CPP_SYNTHESIZE(identifier)
WCDB_CPP_SYNTHESIZE(content)
WCDB_CPP_ORM_IMPLEMENTATION_END

int main() {
	WCDB::Database database("./sample.db");
	bool ret = database.createTable<Sample>("sampleTable");
	if (ret) {
		std::cout<<"create wcdb database successful!"<<std::endl;
		return 0;
	}
	else {
		std::cout<<"create wcdb database failed!"<<std::endl;
		return -1;
	}
}
```

run command on the folder of **CMakeLists.txt**:
```
mkdir build && cd build
cmake ..
make
```

The project was failed to build and the error messages were output:
>/usr/bin/ld: CMakeFiles/test_dep_wcdb.dir/wcdb/src/cpp/Operation/BaseOperation.cpp.o: in function \`WCDB::BaseOperation::assignErrorToDatabase(WCDB::Error const&)\':
>BaseOperation.cpp:(.text+0xcc): undefined reference to `WCDB::ThreadedErrorProne::setThreadedError(WCDB::Error const&)'
>...
>make[2]: *** [CMakeFiles/test_dep_wcdb.dir/build.make:420: test_dep_wcdb] Error 1
>make[1]: *** [CMakeFiles/Makefile2:106: CMakeFiles/test_dep_wcdb.dir/all] Error 2
>make: *** [Makefile:91: all] Error 2

It seems all files on **wcdb/src/cpp** were built but can't link to the symbols on **wcdb/src/common**.
How to solve the problem?

**Comment by watergear** [comment]
Here is the testing cmake project file.
[test_wcdb.zip](https://github.com/Tencent/wcdb/files/14757163/test_wcdb.zip)

run command to test:
```
git submodule update --init --recursive
mkdir build && cd build
cmake ..
make
```

**Comment by Qiuwen-chen** [comment]
Can you catch the crash stack?

**Comment by watergear** [comment]
我想先解决CMake编译链接错误问题，基于官方版本2.1.0加入CMake子模块就会出现很奇怪的链接错误。我自己写的其它库作为子模块引入构建都是正常的，唯独这个wcdb不可以链接，丈二和尚摸不着头脑。

CMake项目中使用add_subdirectory导入其它子模块是很标准的做法，我随便写一个类库使用add_subdirectory导入都是正常的，为啥就是wcdb不行？我看了几遍wcdb/src/CMakeLists.txt，也没看出什么问题？

**Comment by watergear** [comment]
> Can you catch the crash stack?
我在linux下编译构建，默认是Makefile的，还不太熟怎么抓到它的错误堆栈，可能需要GDB工具之类的。
如果你熟悉GDB，可以用[test_wcdb](https://github.com/Tencent/wcdb/files/14757163/test_wcdb.zip)测试一下，不过需要先修改wcdb/src/CMakeLists.txt解决编译链接问题。

**Comment by Qiuwen-chen** [comment]
Will be fixed soon

**Comment by watergear** [comment]
I have already fixed the issue and it works fine now on my project.
PR #1071

**Comment by Qiuwen-chen** [comment]
> I have already fixed the issue and it works fine now on my project. PR #1071

Good. I find almost the same solution as yours just before. Since your pr does not cover all the things, it will be rejected. 

Anyway, thacks for your report and your solution.

**Comment by watergear** [comment]
> > I have already fixed the issue and it works fine now on my project. PR #1071
> 
> Good. I find almost the same solution as yours just before. Since your pr does not cover all the things, it will be rejected.
> 
> Anyway, thacks for your report and your solution.

I have signed the CLA and hope you can accept this PR. Even if I didn't cover all the things, of course you can base on this PR and go on to fix all later.
Because on my project I have make the git submodule refer to this PR, which commit hash from this PR, so everything will be easy if you accept this PR.

**Comment by Qiuwen-chen** [comment]
> > > I have already fixed the issue and it works fine now on my project. PR #1071
> > 
> > 
> > Good. I find almost the same solution as yours just before. Since your pr does not cover all the things, it will be rejected.
> > Anyway, thacks for your report and your solution.
> 
> I have signed the CLA and hope you can accept this PR. Even if I didn't cover all the things, of course you can base on this PR and go on to fix all later. Because on my project I have make the git submodule refer to this PR, which commit hash from this PR, so everything will be easy if you accept this PR.

Sory, I miss this message. v2.1.2 is published.
