### ISSUE TITLE
在swift项目中，使用Xcode自带的spm加载WCDB一直加载失败

### ISSUE THREAD

**Issue by superyang2019** [Tencent/wcdb#1068]
### The language of WCDB

>Swift

### The version of WCDB

> v2.1.1

### The platform of WCDB

> iOS

### The installation of WCDB

> Xcode自带的SPM包管理器

### What's the issue?

> Post the outputs or screenshots for errors.
> 每次使用spm下载WCDB 2.1.1版本的时候，下载到280多M的时候直接提示下载失败，提示Could not update repository submodules
> Explain what you want by example or code **in English**.

**Comment by superyang2019** [comment]
主要是wcdb中有三个子模块sqlcipher、openssl、zstd， 三个子模块加起来500多M，每次在构建的时候现在都无法正常拉取下来。

**Comment by Qiuwen-chen** [comment]
Can't help.
