### ISSUE TITLE
fatal error: 'config.h' file not found #include "config.h"

### ISSUE THREAD

**Issue by huicongfu** [Tencent/wcdb#1069]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
Swift

### The version of WCDB

> e.g. v1.0.5

V2.1.1

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

SPM

### What's the issue?

> Post the outputs or screenshots for errors.
> 

> Explain what you want by example or code **in English**.

My SPM Library depends on WCDB
The following error when I build the library using the SPM command:swift build --configuration release

<img width="1094" alt="image" src="https://github.com/Tencent/wcdb/assets/13210774/68b531a0-c512-4b3d-bb0b-62e817b9a9f5">

Are there any solutions or suggestions for this?

**Comment by Qiuwen-chen** [comment]
Can't reproduce. Can you try it in a empty project? If error still exist, you can  give us a demo project to reproduce it.
