### ISSUE TITLE
建议提供一个列名相同情况下,在表之间相互拷贝的方法

### ISSUE THREAD

**Issue by ztlyyznf001** [Tencent/wcdb#107]
现在需要先把所有的object取出来在insert进去

**Comment by lingol** [comment]
SQLite本身不支持表间复制，我看即使WCDB实现了这个方法，性能上也不会有多大提高，也不会方便多少。

**Comment by alexlee002** [comment]
貌似sqlite的 with语句可以支持这个？

类似于mysql的insert ... select ...语句。
