### ISSUE TITLE
crash on WCDBSwift WCDB::Value::clearValue() (atomic:)

### ISSUE THREAD

**Issue by mxh-mo** [Tencent/wcdb#1070]
### The language of WCDB

Swift 

### The version of WCDB

v2.0.4

### The platform of WCDB

iOS

### The installation of WCDB

Git clone

### What's the issue?

I have received such crashes on Bugly, and currently found that both insert and delete operations can trigger the same crash. Bugly shows that when the crash occurred, the users' phone storage spaces were all very limited, generally less than 0.5%.

![1](https://github.com/Tencent/wcdb/assets/23711680/d3e84e76-9b25-4472-a7a5-78c5e791506c)

I have tried to reproduce the issue myself using a phone with limited space, and the database also crashes occasionally. Here is the screenshot of the stack trace I obtained.

![2](https://github.com/Tencent/wcdb/assets/23711680/b75eb916-23e1-4227-a102-3b394beca6f9)

Could you please check what the problem is?

**Comment by Qiuwen-chen** [comment]
Fixed in the latest version
