### ISSUE TITLE
数据库关闭后，过一段时间后会自动打开

### ISSUE THREAD

**Issue by litsec1988** [Tencent/wcdb#1072]
### The language of WCDB

> C++

### The version of WCDB

> 2.0.0

### The platform of WCDB

> linux

### The installation of WCDB

> Maven

### What's the issue?

>当我打开一个数据库，并对数据库随便操作了一下，然后关闭数据库后（甚至把数据库删除），然后监听数据库的打开状态，发现数据库过一段时间后，会自动打开，这会导致文件夹中莫名其妙的多了一个空的数据库，请问这个是否有开关可以避免这种操作
> 
> int main()
{
    std::string time = ais::engine::tmpdb::getCurrentDate();
    WCDB::Database db1("/home/aoi/ais/projects/2.2/version/top/1226-1_test.db");
    ais::engine::tmpdb::Version versionItem;
    versionItem.side = static_cast<int>(ais::common::SideTop);
    versionItem.label = "1226-1";
    versionItem.software ="inspector";
    versionItem.modifyBy ="test";
    versionItem.createTime =time;
    versionItem.modifyTime = time;
    db1.insertObjects<ais::engine::tmpdb::Version>(versionItem,"Version");
    db1.close();
    db1.removeFiles();
    while(1){
        std::cout<<db1.isOpened()<<std::endl;;
        sleep(1);
    }
    return 0;
}

>打印信息：

0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1

**Comment by Qiuwen-chen** [comment]
Fixed in the latest version
