### ISSUE TITLE
Support build WCDB.framework from CMake on Apple platform

### ISSUE THREAD

**Issue by watergear** [Tencent/wcdb#1073]
### The language of WCDB
> C++
### The version of WCDB
> v2.12
### The platform of WCDB
> iOS, macOS
### The installation of WCDB
> Git clone
### What's the issue?

As we know, to submit iOS application to App Store, it requires all the dependent libraries must be in .framework format. Until now, it is unable to build WCDB.framework directly from the cmake configuration. So it is no easy to produce .framework packages for iOS App once it depend on wcdb on cmake configuration.
Because of that, if one cross-platform project decide to depend on wcdb, it will have to make a lot of extra configurations to produce .framework packages for only iOS platform. Which greatly increases the burden of wcdb denpendant as a cross-platform developer.
Modern cmake has provided many solutions, which can directly generate Xcode projects and build .framework libraries. Should we consider make wcdb, as a cross-platform project, be able to generate WCDB.framework directly from the cmake configuration?

#### Example
build wcdb sources and link to WCDB.framework
**CMakeLists.txt**
```
add_subdirectory(wcdb/src)
target_link_libraries(test_dep_wcdb_framework "-framework WCDB")
```

#### Testing cmake project
[test_wcdb_framework.zip](https://github.com/Tencent/wcdb/files/14831374/test_wcdb_framework.zip)

run command to build makefile:
```
cd test_wcdb_framework
git submodule update --init --recursive
mkdir build && cd build
cmake .. && cmake --build .
cd out && ./test_dep_wcdb_framework
```
output:
> create wcdb database successful!

run command to build xcode:
```
cd test_wcdb_framework
git submodule update --init --recursive
mkdir buildx && cd buildx
cmake .. -GXcode && cmake --build .
cd out/Debug && ./test_dep_wcdb_framework
```
output:
>/Users/sim/GitRepo/test_wcdb_framework/wcdb_sample_test.cpp:2:10: fatal error: 
>      'WCDBCpp.h' file not found
>#include "WCDBCpp.h"
>         ^~~~~~~~~~~
>1 error generated.

**Failed to compile wcdb_sample_test.cpp as WCDB.framework hasn't been built on Xcode.**

**Comment by Qiuwen-chen** [comment]
I understand what you need. I'm a little busy recently. Could you please submit your solution?

**Comment by watergear** [comment]
> I understand what you need. I'm a little busy recently. Could you please submit your solution?

OK, I will try to solve it, and submit PR when I finish.

**Comment by watergear** [comment]
Here is a very simple CMake configs to build .framework by Xcode.
[test_xcode_framework_header.zip](https://github.com/Tencent/wcdb/files/14902473/test_xcode_framework_header.zip)
Run:
```
mkdir buildx && cd buildx
cmake .. -GXcode && cmake --build .
./Debug/Bar 
```
Output
> foo

**Comment by Qiuwen-chen** [comment]
> > I understand what you need. I'm a little busy recently. Could you please submit your solution?
> 
> OK, I will try to solve it, and submit PR when I finish.

Thanks

**Comment by watergear** [comment]
I have got the solution.
See 
[test_xcode_framework.zip](https://github.com/Tencent/wcdb/files/14917108/test_xcode_framework.zip)

**Xcode works fine.**
Run
```
mkdir buildx && cd buildx
cmake .. -GXcode && cmake --build .
./Debug/Bar 
```
Output
> foo

**Of course makefile also works fine too.**
Run
```
mkdir build && cd build
cmake .. && make
./Bar 
```
Output
> foo

**The sample always build .framework whatever build system (Xcode or makefile) the cmake generated.**

use `otool -l ./Bar` to see dependent libraries.

**Comment by Qiuwen-chen** [comment]
> I have got the solution. See [test_xcode_framework.zip](https://github.com/Tencent/wcdb/files/14917108/test_xcode_framework.zip)
> 
> **Xcode works fine.** Run
> 
> ```
> mkdir buildx && cd buildx
> cmake .. -GXcode && cmake --build .
> ./Debug/Bar 
> ```
> 
> Output
> 
> > foo
> 
> **Of course makefile also works fine too.** Run
> 
> ```
> mkdir build && cd build
> cmake .. && make
> ./Bar 
> ```
> 
> Output
> 
> > foo
> 
> **The sample always build .framework whatever build system (Xcode or makefile) the cmake generated.**
> 
> use `otool -l ./Bar` to see dependent libraries.

I know that solution. I means that you can try to apply it to WCDB and raise a pr.

**Comment by Qiuwen-chen** [comment]
Your pr is merged.
