### ISSUE TITLE
Please provide a android proguard for the new version of WCDB!

### ISSUE THREAD

**Issue by CCint3** [Tencent/wcdb#1075]
### The language of WCDB

> Android, Java

### The version of WCDB

> com.tencent.wcdb:main:2.1.0
> com.tencent.wcdb:annotation:2.1.0
> com.tencent.wcdb:compiler:2.1.0
> com.tencent.wcdb:compat:2.1.0

### The platform of WCDB

> Android

### The installation of WCDB

> Maven, Gradle

### What's the issue?

> Please provide a android proguard for the new version of WCDB!

**Comment by Qiuwen-chen** [comment]
Get. Will be fixed soon.

**Comment by Qiuwen-chen** [comment]
Fixed in v2.1.4
