### ISSUE TITLE
与xutils3同时使用存在冲突

### ISSUE THREAD

**Issue by XiangliJiaxing** [Tencent/wcdb#108]
m.err: Caused by: java.lang.IllegalStateException: SQLiteConnection native handle not initialized.
07-25 16:25:21.470 8709-8900/com.vito.housekeepingdiretor W/System.err:     at com.tencent.wcdb.database.SQLiteConnection.getNativeHandle(SQLiteConnection.java:187)
07-25 16:25:21.470 8709-8709/com.vito.housekeepingdiretor D/CrashHandler: USER : jenkins
07-25 16:25:21.470 8709-8900/com.vito.housekeepingdiretor W/System.err:     at com.tencent.wcdb.database.SQLiteDebug.collectLastIOTraceStats(SQLiteDebug.java:180)
07-25 16:25:21.470 8709-8900/com.vito.housekeepingdiretor W/System.err:     at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:234)
07-25 16:25:21.470 8709-8900/com.vito.housekeepingdiretor W/System.err:     at com.tencent.wcdb.database.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:480)
07-25 16:25:21.470 8709-8900/com.vito.housekeepingdiretor W/System.err:     at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:208)
07-25 16:25:21.470 8709-8900/com.vito.housekeepingdiretor W/System.err:     at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:200)
07-25 16:25:21.470 8709-8900/com.vito.housekeepingdiretor W/System.err:     at com.tencent.wcdb.database.SQLiteDatabase.openInner(SQLiteDatabase.java:996)
07-25 16:25:21.470 8709-8900/com.vito.housekeepingdiretor W/System.err:     at com.tencent.wcdb.database.SQLiteDatabase.open(SQLiteDatabase.java:977)
07-25 16:25:21.470 8709-8900/com.vito.housekeepingdiretor W/System.err:     at com.tencent.wcdb.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:709)
07-25 16:25:21.470 8709-8900/com.vito.housekeepingdiretor W/System.err:     at com.tencent.wcdb.support.Context.openOrCreateDatabase(Context.java:144)
07-25 16:25:21.470 8709-8900/com.vito.housekeepingdiretor W/System.err:     at com.tencent.wcdb.database.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:288)
07-25 16:25:21.470 8709-8900/com.vito.housekeepingdiretor W/System.err:     at com.tencent.wcdb.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:225)

**Comment by John-He-928** [comment]
请提供具体代码，和WCDB版本。
你这个其实是open的时候失败了，进一步收集信息时出错了，收集信息出错的bug我改一下，但没法open是别的原因

**Comment by John-He-928** [comment]
dev分支现在正常处理打开异常，应该能收集到一些信息， @XiangliJiaxing 你试试

**Comment by gdutkyle** [comment]
你好，我也遇到这个问题了，请问有什么方法能够解决吗？

**Comment by gdutkyle** [comment]
com.tencent.wcdb.database.SQLiteConnection.long getNativeHandle(java.lang.String)(Unknown Source)
--
2 com.tencent.wcdb.database.SQLiteDebug.void collectLastIOTraceStats(com.tencent.wcdb.database.SQLiteConnection)(Unknown Source)
3 ##_parent_##1##_parent_##
4 ##_child_## void collectLastIOTraceStats(com.tencent.wcdb.database.SQLiteDatabase)##_child_##
5 com.tencent.wcdb.database.SQLiteConnection.com.tencent.wcdb.database.SQLiteConnection open(com.tencent.wcdb.database.SQLiteConnectionPool,com.tencent.wcdb.database.SQLiteDatabaseConfiguration,int,boolean,byte[],com.tencent.wcdb.database.SQLiteCipherSpec)(Unknown Source)
6 ##_parent_##1##_parent_##
7 ##_child_## void open()##_child_##
8 com.tencent.wcdb.database.SQLiteConnectionPool.com.tencent.wcdb.database.SQLiteConnection openConnectionLocked(com.tencent.wcdb.database.SQLiteDatabaseConfiguration,boolean)(Unknown Source)
9 com.tencent.wcdb.database.SQLiteConnectionPool.com.tencent.wcdb.database.SQLiteConnectionPool open(com.tencent.wcdb.database.SQLiteDatabase,com.tencent.wcdb.database.SQLiteDatabaseConfiguration,byte[],com.tencent.wcdb.database.SQLiteCipherSpec)(Unknown Source)
10 ##_parent_##2##_parent_##
11 ##_child_## com.tencent.wcdb.database.SQLiteConnectionPool open(com.tencent.wcdb.database.SQLiteDatabase,com.tencent.wcdb.database.SQLiteDatabaseConfiguration,byte[],com.tencent.wcdb.database.SQLiteCipherSpec,int)##_child_##
12 ##_child_## void open()##_child_##
13 com.tencent.wcdb.database.SQLiteConnectionPool.com.tencent.wcdb.database.SQLiteConnectionPool open(com.tencent.wcdb.database.SQLiteDatabase,com.tencent.wcdb.database.SQLiteDatabaseConfiguration,byte[],com.tencent.wcdb.database.SQLiteCipherSpec)(Unknown Source)
14 ##_parent_##2##_parent_##
15 ##_child_## com.tencent.wcdb.database.SQLiteConnectionPool open(com.tencent.wcdb.database.SQLiteDatabase,com.tencent.wcdb.database.SQLiteDatabaseConfiguration,byte[],com.tencent.wcdb.database.SQLiteCipherSpec,int)##_child_##
16 ##_child_## void open()##_child_##
17 com.tencent.wcdb.database.SQLiteDatabase.void openInner(byte[],com.tencent.wcdb.database.SQLiteCipherSpec,int)(Unknown Source)
18 com.tencent.wcdb.database.SQLiteDatabase.void open(byte[],com.tencent.wcdb.database.SQLiteCipherSpec,int)(Unknown Source)
19 com.tencent.wcdb.database.SQLiteDatabase.com.tencent.wcdb.database.SQLiteDatabase openDatabase(java.lang.String,com.tencent.wcdb.database.SQLiteDatabase$CursorFactory,int)(Unknown Source)
20 ##_parent_##4##_parent_##
21 ##_child_## com.tencent.wcdb.database.SQLiteDatabase openDatabase(java.lang.String,byte[],com.tencent.wcdb.database.SQLiteCipherSpec,com.tencent.wcdb.database.SQLiteDatabase$CursorFactory,int,com.tencent.wcdb.DatabaseErrorHandler,int)##_child_##
22 ##_child_## com.tencent.wcdb.database.SQLiteDatabase openDatabase(java.lang.String,byte[],com.tencent.wcdb.database.SQLiteCipherSpec,com.tencent.wcdb.database.SQLiteDatabase$CursorFactory,int,com.tencent.wcdb.DatabaseErrorHandler)##_child_##
23 ##_child_## com.tencent.wcdb.database.SQLiteDatabase openDatabase(java.lang.String,com.tencent.wcdb.database.SQLiteDatabase$CursorFactory,int,com.tencent.wcdb.DatabaseErrorHandler)##_child_##
24 ##_child_## com.tencent.wcdb.database.SQLiteDatabase openDatabase(java.lang.String,com.tencent.wcdb.database.SQLiteDatabase$CursorFactory,int,com.tencent.wcdb.DatabaseErrorHandler,int)##_child_##
25 com.tencent.wcdb.support.Context.com.tencent.wcdb.database.SQLiteDatabase openOrCreateDatabase(android.content.Context,java.lang.String,int,com.tencent.wcdb.database.SQLiteDatabase$CursorFactory)(Unknown Source)
26 ##_parent_##3##_parent_##
27 ##_child_## com.tencent.wcdb.database.SQLiteDatabase openOrCreateDatabase(android.content.Context,java.lang.String,int,com.tencent.wcdb.database.SQLiteDatabase$CursorFactory,com.tencent.wcdb.DatabaseErrorHandler)##_child_##
28 ##_child_## com.tencent.wcdb.database.SQLiteDatabase openOrCreateDatabase(android.content.Context,java.lang.String,byte[],com.tencent.wcdb.database.SQLiteCipherSpec,int,com.tencent.wcdb.database.SQLiteDatabase$CursorFactory)##_child_##
29 ##_child_## com.tencent.wcdb.database.SQLiteDatabase openOrCreateDatabase(android.content.Context,java.lang.String,byte[],com.tencent.wcdb.database.SQLiteCipherSpec,int,com.tencent.wcdb.database.SQLiteDatabase$CursorFactory,com.tencent.wcdb.DatabaseErrorHandler)##_child_##
30 com.tencent.wcdb.database.SQLiteOpenHelper.com.tencent.wcdb.database.SQLiteDatabase getDatabaseLocked(boolean)(Unknown Source)
31 com.tencent.wcdb.database.SQLiteOpenHelper.com.tencent.wcdb.database.SQLiteDatabase getWritableDatabase()(Unknown Source)
32 com.yunzhijia.data.db.PersonalDatabase.void <init>()(Unknown Source)
33 com.yunzhijia.data.db.PersonalDatabase.com.tencent.wcdb.database.SQLiteDatabase getEncryptedDB()(Unknown Source)
34 com.yunzhijia.utils.DatabaseMigrateUtils.void migratePrepareWithGlobalPersonTableD()(Unknown Source)
35 com.yunzhijia.account.login.impl.LoginVerifyCodeImpl$13.void onLoginSuccessInitFailed()(Unknown Source)
36 com.kdweibo.android.util.SchemeUtil$4$1.void onSuccess(int,java.lang.Object)(Unknown Source)
37 com.kdweibo.android.localTask.GJBaseTaskPacket.void onSuccess(int)(Unknown Source)
38 com.kdweibo.android.localTask.GJLocalTask.void onPostExecute(java.lang.Long)(Unknown Source)
39 com.kdweibo.android.localTask.GJLocalTask.void onPostExecute(java.lang.Object)(Unknown Source)
40 com.luciofm.asynctaskcompat.AsyncTaskCompat.void finish(java.lang.Object)(Unknown Source)
41 com.luciofm.asynctaskcompat.AsyncTaskCompat.void access$600(com.luciofm.asynctaskcompat.AsyncTaskCompat,java.lang.Object)(Unknown Source)
42 com.luciofm.asynctaskcompat.AsyncTaskCompat$InternalHandler.void handleMessage(android.os.Message)(Unknown Source)
43 android.os.Handler.dispatchMessage(Handler.java:102)
44 android.os.Looper.loop(Looper.java:135)
45 android.app.ActivityThread.main(ActivityThread.java:5595)
46 java.lang.reflect.Method.invoke(Native Method)
47 java.lang.reflect.Method.invoke(Method.java:372)
48 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
49 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
