### ISSUE TITLE
How to update or download database in wcdb version 2.1.0

### ISSUE THREAD

**Issue by liyaxun520** [Tencent/wcdb#1083]
### The language of WCDB

>  Java 

### The version of WCDB

> 2.1.0

### The platform of WCDB

> Android

### The installation of WCDB

> Maven

### What's the issue?

> How to update or download database in wcdb version 2.1.0
> 
> Provider an Android demo by kotlin or Java

**Comment by Qiuwen-chen** [comment]
https://github.com/Tencent/wcdb/wiki/Java%7CKotlin-%e5%ae%89%e8%a3%85%e4%b8%8e%e5%85%bc%e5%ae%b9%e6%80%a7
