### ISSUE TITLE
XCode无法运行APP到IOS15.4.1等手机上,打包.ipa也无法安装.其它iOS系统正常DEBUG 和安装

### ISSUE THREAD

**Issue by liuyingjieyeah** [Tencent/wcdb#1088]
Unable to install "enterpriseMessage"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620395
User Info: {
    DVTErrorCreationDateKey = "2024-04-27 13:18:43 +0000";
    IDERunOperationFailingWorker = IDEInstalliPhoneLauncher;
}
--
Unable to install "enterpriseMessage"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620395
User Info: {
    IDERunOperationFailingWorker = IDEInstalliPhoneLauncher;
}
--
A valid provisioning profile for this executable was not found.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620395
User Info: {
    DVTRadarComponentKey = 487925;
    MobileDeviceErrorCode = "(0xE8008015)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x0000000115ab5a8c DTDKCreateNSErrorFromAMDErrorCode + 229
	1   DTDeviceKitBase                     0x0000000115ae91e2 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 158
	2   DVTFoundation                       0x00000001093b7bdc DVTInvokeWithStrongOwnership + 70
	3   DTDeviceKitBase                     0x0000000115ae8f17 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1412
	4   IDEiOSSupportCore                   0x00000001159c098c __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.307 + 3568
	5   DVTFoundation                       0x00000001094f48e2 __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x00000001094f53ce __DVTDispatchAsync_block_invoke + 196
	7   libdispatch.dylib                   0x00007ff81295cac6 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007ff81295ddbc _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007ff812963eff _dispatch_lane_serial_drain + 800
	10  libdispatch.dylib                   0x00007ff812964997 _dispatch_lane_invoke + 377
	11  libdispatch.dylib                   0x00007ff81296e414 _dispatch_root_queue_drain_deferred_wlh + 271
	12  libdispatch.dylib                   0x00007ff81296dd2a _dispatch_workloop_worker_thread + 451
	13  libsystem_pthread.dylib             0x00007ff812afbb84 _pthread_wqthread + 327
	14  libsystem_pthread.dylib             0x00007ff812afaacf start_wqthread + 15
);
}
--

Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_model" = "iPhone10,1";
    "device_osBuild" = "15.4.1 (19E258)";
    "device_platform" = "com.apple.platform.iphoneos";
    "dvt_coredevice_version" = "355.24";
    "dvt_mobiledevice_version" = "1643.100.58";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 23940;
    "operation_errorCode" = "-402620395";
    "operation_errorDomain" = "com.apple.dt.MobileDeviceErrorDomain";
    "operation_errorWorker" = IDEInstalliPhoneLauncher;
    "operation_name" = IDEiPhoneRunOperationWorkerGroup;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 5;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 0;
    "param_launcher_substyle" = 0;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_structuredConsoleMode" = 1;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos17.4";
    "sdk_osVersion" = "17.4";
    "sdk_variant" = iphoneos;
}
--

System Information

macOS Version 14.4.1 (Build 23E224)
Xcode 15.3 (22618) (Build 15E204a)
Timestamp: 2024-04-27T21:18:43+08:00

**Comment by Qiuwen-chen** [comment]
This has nothing to do with WCDB
