### ISSUE TITLE
sqlcipher seekAndRead stuck

### ISSUE THREAD

**Issue by BAOU** [Tencent/wcdb#1090]
### The language of WCDB
Swift

### The version of WCDB
v1.0.8.2

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.

libsystem_kernel.dylib        _pread (in libsystem_kernel.dylib) +8
sqlcipher        seekAndRead (in sqlcipher) os_unix.c:3181
sqlcipher        unixRead (in sqlcipher) os_unix.c:3257
sqlcipher        readDbPage (in sqlcipher) pager.c:2932
sqlcipher        sqlite3PagerGet (in sqlcipher) pager.c:5472
sqlcipher        getAndInitPage (in sqlcipher) btree.c:2004
sqlcipher        sqlite3BtreeMovetoUnpacked (in sqlcipher) btree.c:5278
sqlcipher        handleDeferredMoveto (in sqlcipher) vdbeaux.c:3011
sqlcipher        sqlite3VdbeExec (in sqlcipher) vdbe.c:2461
sqlcipher        sqlite3Step (in sqlcipher) [inlined] vdbeapi.c:602
sqlcipher        sqlite3_step (in sqlcipher) vdbeapi.c:663
WCDBSwift    HandleStatement.step() (in WCDBSwift) [inlined] HandleStatement.swift:46
WCDBSwift    Selectable.next() (in WCDBSwift) [inlined] Selectable.swift:55
WCDBSwift    Select.allObjects<A>(of: A.Type) (in WCDBSwift) Select.swift:83
WCDBSwift    Table.getObjects(on: [PropertyConvertible], where: ExpressionConvertible?, orderBy: [OrderConvertible]?, limit: 
                        ExpressionConvertible?, offset: ExpressionConvertible?) (in WCDBSwift) Table.swift:298

> Explain what you want by example or code **in English**.
when I get objects from table，the app is stuck。How can I resolve this stuck without use the latest version？

**Comment by Qiuwen-chen** [comment]
Please try the latest version
