### ISSUE TITLE
 XCode升级到15.3以后打包时报错: WCDBOptimizedSQLCipher/sqlcipher.framework/sqlcipher

### ISSUE THREAD

**Issue by Annabelle1024** [Tencent/wcdb#1091]
### The language of WCDB

> Objective-C, Swift 

### The version of WCDB

 v1.0.8.2

### The platform of WCDB

 iOS

### The installation of WCDB

 Cocoapods

### What's the issue?

问题1: XCode升级到15.3以后, 使用force_load方式加载sqlcipher, 真机运行没问题, 打包时报错
Showing All Errors Only
Build input file cannot be found: '***（路径）/BuildProductsPath/DailyBuild-iphoneos/WCDBOptimizedSQLCipher/sqlcipher.framework/sqlcipher'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

问题2: 打包不成功后, 在runscript在output file中添加输出文件路径后, 打包成功, 可是数据库无法正常读取
<img width="1132" alt="image" src="https://github.com/Tencent/wcdb/assets/9578160/7579342f-ab71-44d5-a8bb-b76e89c8f1ad">

求问有没有人解决过这个问题?  升级WCDB的话, 需要swift升级到5, 目前项目还使用的是4, 暂时无法进行这么大的改动

**Comment by Qiuwen-chen** [comment]
Can you give us a demo project to reproduce this problem?
