### ISSUE TITLE
是否有支持HarmonyOS计划

### ISSUE THREAD

**Issue by cheng8482** [Tencent/wcdb#1092]
目前HarmonyOS正在推进中，之前Android/iOS应用使用了WCDB库，请问对HarmonyOS的支持是否有推进计划？

**Comment by Qiuwen-chen** [comment]
May be you can use WCDB C++

**Comment by Jadyli** [comment]
请问是否有发布 Kotlin Multiplatform 版本的计划？

**Comment by Qiuwen-chen** [comment]
WCDB C++ supports OpenHarmony OS since v2.1.7.

**Comment by Qiuwen-chen** [comment]
> 请问是否有发布 Kotlin Multiplatform 版本的计划？

That needs a lot of work, and I don't plan to do it in short term.
