### ISSUE TITLE
创建表失败，都已经注册了分词器，代码如下：        db.add(tokenizer: BuiltinTokenizer.Pinyin)         try db.create(virtualTable: FTSMessage.tableName, of: FTSMessage.self)

### ISSUE THREAD

**Issue by lihualin1688** [Tencent/wcdb#1093]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
https://github.com/Tencent/wcdb/wiki/Swift-%e7%9b%91%e6%8e%a7%e4%b8%8e%e9%94%99%e8%af%af%e5%a4%84%e7%90%86
