### ISSUE TITLE
android 使用wcdb 2.1.4  创建icu分词器报错

### ISSUE THREAD

**Issue by zl15074769846** [Tencent/wcdb#1094]
### The language of WCDB

> e.g Java 

  //注册本数据需要用到的分词器
        database.addTokenizer(BuiltinTokenizer.ICU);
        //创建虚表
        database.createVirtualTable("ddd",DBMgImSearch.INSTANCE);

使用上述代码创建虚表 报错：

com.tencent.wcdb.base.WCDBNormalException: Code: 1; Message: unknown tokenizer: icu; Path: /data/user/0/com.mgtv.dolphinjni/databases/test2222.db; SQL: CREATE VIRTUAL TABLE IF NOT EXISTS ddd USING fts4(tokenize = icu, nick_name TEXT, avatar TEXT); Source: SQLite

### The version of WCDB

> e.g. v2.1.4

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by zl15074769846** [comment]
Previously used [Android 1.0.8](android:1.0.8), which used the built-in MMICU of WCDB. Now using 2.1.4, is it compatible and will data loss occur？

**Comment by Qiuwen-chen** [comment]
MMICU is not supported in the new version yet. I will consider it in the next version, please wait.

**Comment by zl15074769846** [comment]
> MMICU is not supported in the new version yet. I will consider it in the next version, please wait.



> MMICU is not supported in the new version yet. I will consider it in the next version, please wait.

Urgently needed, I hope the next version can support it

**Comment by zl15074769846** [comment]
> MMICU is not supported in the new version yet. I will consider it in the next version, please wait.

Can I join the communication group？

**Comment by Qiuwen-chen** [comment]
> > MMICU is not supported in the new version yet. I will consider it in the next version, please wait.
> 
> > MMICU is not supported in the new version yet. I will consider it in the next version, please wait.
> 
> Urgently needed, I hope the next version can support it

OK

**Comment by Qiuwen-chen** [comment]
> > MMICU is not supported in the new version yet. I will consider it in the next version, please wait.
> 
> Can I join the communication group？

No such group

**Comment by Qiuwen-chen** [comment]
Supported in v2.1.5
