### ISSUE TITLE
Does Android 1.0.8 支持数据库损坏监测、备份、恢复功能吗

### ISSUE THREAD

**Issue by zl15074769846** [Tencent/wcdb#1095]
### The language of WCDB

> e.g  Java 

Does Android 1.0.8 support database damage monitoring, backup, and repair functions

### The version of WCDB

> e.g. v1.0.8

### The platform of WCDB

> e.g. Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
NO
