### ISSUE TITLE
Swift下使用UIActivityViewController分享的db文件中，是个空数据库

### ISSUE THREAD

**Issue by MichaelJackchuang** [Tencent/wcdb#1096]
我们想将db文件导出，就使用UIActivityViewController将db文件分享出来，但是数据库文件是可以导出的，但是没有数据，甚至没有表，这是什么原因呢？怎么解决呢？
另：用Data.init(contentOf:)方法读取db文件的时候，得到的data大小也只有4096字节，而沙盒中该db文件有57kb

**Comment by Qiuwen-chen** [comment]
It doesn't seem to be a WCDB problem.
