### ISSUE TITLE
iOS 使用SPM 失败 

### ISSUE THREAD

**Issue by Beiqi56** [Tencent/wcdb#1098]
### The language of WCDB

> Swift

### The version of WCDB

> 2.1.4

### The platform of WCDB

> iOS

### The installation of WCDB

> Swift Package Manager

### What's the issue?

> 
 无法选择2.1.x的版本 ：
<img width="844" alt="截屏2024-05-16 15 01 23" src="https://github.com/Tencent/wcdb/assets/33677462/ea760572-39b3-4794-90a8-491e6434876b">

选择branch时，也无法下载 
<img width="711" alt="image" src="https://github.com/Tencent/wcdb/assets/33677462/84d596f6-0e05-45b7-965c-692d9a55b8df">

**Comment by Qiuwen-chen** [comment]
https://github.com/Tencent/wcdb/wiki/Swift-%e5%ae%89%e8%a3%85%e4%b8%8e%e5%85%bc%e5%ae%b9%e6%80%a7#%E9%80%9A%E8%BF%87-swift-package-manager-%E5%AE%89%E8%A3%85

**Comment by Beiqi56** [comment]
> https://github.com/Tencent/wcdb/wiki/Swift-%e5%ae%89%e8%a3%85%e4%b8%8e%e5%85%bc%e5%ae%b9%e6%80%a7#%E9%80%9A%E8%BF%87-swift-package-manager-%E5%AE%89%E8%A3%85

使用 range of versions，或者exact version 均失败了，希望帮再确认一下：
<img width="1315" alt="image" src="https://github.com/Tencent/wcdb/assets/33677462/8ebb739f-e3c9-42c2-9c66-5be1f7f47aa2">

**Comment by Qiuwen-chen** [comment]
It looks like a network problem. I can not help.
