### ISSUE TITLE
使用 Carthage 安装，但是文件路径与文档不同

### ISSUE THREAD

**Issue by xdkhan** [Tencent/wcdb#11]
Carthage/Build/ 文件夹又分为 iOS 和 Mac两个文件夹，iOS文件夹下才是 framework。为什么会有这种区别呢？

**Comment by RingoD** [comment]
WCDB支持iOS和Mac版本，carthage会默认build两个版本。选择你需要的framework即可。
我稍后会将文档的描述改得更精确一些。
