### ISSUE TITLE
问下有 replace into 这样的接口么

### ISSUE THREAD

**Issue by Rannie** [Tencent/wcdb#110]
想扩展出一个简单的 key-value store ，看了下文档貌似没有 replace 这种 sql 的接口。

**Comment by RingoD** [comment]
https://github.com/Tencent/wcdb/wiki/基础类、CRUD与Transaction#插入

`insertOrReplaceObject:into`

希望你的key-value store的实现，也能开源出来

**Comment by Rannie** [comment]
十分感谢~

**Comment by Rannie** [comment]
key-value store 仓库已经搞好了 欢迎指导 https://github.com/Rannie/RHKeyValueStore

**Comment by RingoD** [comment]
@Rannie  Good，希望持续更新持续进化！
