### ISSUE TITLE
How can I use Wcdb repair Function

### ISSUE THREAD

**Issue by cangbing2003** [Tencent/wcdb#1102]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
Java

### The version of WCDB

> e.g. v1.0.5
I don't know

### The platform of WCDB

> e.g. iOS, macOS or Android
Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

I want to use wcdb's repare function,but when I use 1.0.8,the function  is not exist. but when i use 2.1.5 ,I can't import the aar, wcdb can not import to project.so which version can I use?

**Comment by Qiuwen-chen** [comment]
You can follow this wiki: https://github.com/Tencent/wcdb/wiki/Java%7CKotlin-%e5%ae%89%e8%a3%85%e4%b8%8e%e5%85%bc%e5%ae%b9%e6%80%a7
