### ISSUE TITLE
为什么初始化时select count(*) from message执行超过100ms

### ISSUE THREAD

**Issue by Yellowyzzz** [Tencent/wcdb#1103]
### The language of WCDB

Kotlin

### The version of WCDB

v1.0.8.2

### The platform of WCDB

Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?
目前使用room+wcdb 1.0.8.2版本，在SQLiteTrace.onSQLExecuted上报埋点，发现在执行时间>100ms的sql中，select count(*) from message占比超过30%
本地测试的时候打印log也可以看到这条sql执行时间与其他相比是较长的
<img width="722" alt="wcdb_init" src="https://github.com/Tencent/wcdb/assets/36409724/6f9c8f69-85a6-4d76-9cdd-ac6757328983">

顺便问一下为什么2.x版本不支持room了，升级有较大改动成本

**Comment by Qiuwen-chen** [comment]
You can use "explain query plan" to analyze your query process.

**Comment by Qiuwen-chen** [comment]
We don't use room, so there are no plans to support it now.

**Comment by Yellowyzzz** [comment]
@Qiuwen-chen sry我的提问出错了，想问的是“PRAGMA journal_mode”这条sql在初始化的时候耗时异常的高。SQLiteTrace.onSQLExecuted上报点位执行时间>100ms的sql中，PRAGMA journal_mode参与超过30%。本地测试非常少的数据量dump命令看它的耗时也是挺高的
<img width="955" alt="image" src="https://github.com/user-attachments/assets/306ca043-cb4e-4d6c-980b-9b2026619e5a">
