### ISSUE TITLE
下面的查询方式是否正确？union前的括号该怎么实现？

### ISSUE THREAD

**Issue by jiyang7** [Tencent/wcdb#1105]
### The language of WCDB

> Swift 

### The version of WCDB

> v2.0.4

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> 我在一个do catch内查询同一个表中两个不同条件的数据，发现结果1 result 和 结果2 otherResult 数据相同，理论上两个条件不同结果是不应该相同的，如果分开至两个do catch执行两次查询结果则不同。
       
        
        do {
            let condition = PCNotificationMessageInfo.Properties.notifyType.in([6, 7, 10])
            let select = try messageNoticeDB.prepareSelect(of: MessageNoticeTableType.messageInfo.tableType, fromTable: MessageNoticeTableType.messageInfo.rawValue).where(condition).limit(40)
            var result = try select.allObjects(of: PCNotificationMessageInfo.self)
            resultArray.append(contentsOf: result)
            
            let otherSelect = try messageNoticeDB.prepareSelect(of: MessageNoticeTableType.messageInfo.tableType, fromTable: MessageNoticeTableType.messageInfo.rawValue).where(!condition)
            let otherResult = try otherSelect.allObjects(of: PCNotificationMessageInfo.self)
            resultArray.append(contentsOf: otherResult)
        } catch {
            
        }

尝试使用union发现无法使用括号
let statementSelect = StatementSelect().select(properties).from(tableName).where(condition).limit(40).union().select(properties).from(tableName).where(!condition)

请问如下语句该如何实现
(SELECT * FROM tableName WHERE condition1 LIMIT 40) union (SELECT * FROM tableName WHERE condition2)

**Comment by Qiuwen-chen** [comment]
StatementSelect().select(Column.all()).from("tableName1").where(condition1).union().select(Column.all()).from("tableName2").where(condition2)

**Comment by jiyang7** [comment]
请问 LIMIT 40是否添加
如果按回复添加
StatementSelect().select(Column.all()).from("tableName1").where(condition1).limit(40).union().select(Column.all()).from("tableName2").where(condition2)

通过输出 description 发现语句是，总数限制40，并非单条语句限制40条
SELECT * FROM tableName1 WHERE condition1 union SELECT * FROM tableName2 WHERE condition2 LIMIT 40
并非
(SELECT * FROM tableName WHERE condition1 LIMIT 40) union (SELECT * FROM tableName WHERE condition2)

**Comment by jiyang7** [comment]
请问 LIMIT 40是否添加
如果按回复添加
StatementSelect().select(Column.all()).from("tableName1").where(condition1).limit(40).union().select(Column.all()).from("tableName2").where(condition2)

通过输出 description 发现语句是，总数限制40，并非单条语句限制40条
SELECT * FROM tableName1 WHERE condition1 union SELECT * FROM tableName2 WHERE condition2 LIMIT 40
并非
(SELECT * FROM tableName1 WHERE condition1 LIMIT 40) union (SELECT * FROM tableName2 WHERE condition2)

**Comment by Qiuwen-chen** [comment]
SQLite's select syntax can only put limit at the end of the statement: https://www.sqlite.org/lang_select.html

**Comment by Qiuwen-chen** [comment]
May be you should use two queries.

**Comment by jiyang7** [comment]
麻烦再问下最开始的问题
我在一个do catch内查询同一个表中两个不同条件的数据，发现结果1 result 和 结果2 otherResult 数据相同，理论上两个条件不同结果是不应该相同的，如果分开至两个do catch执行两次查询结果则不同。

do {
        let condition = PCNotificationMessageInfo.Properties.notifyType.in([6, 7, 10])
        let select = try messageNoticeDB.prepareSelect(of: MessageNoticeTableType.messageInfo.tableType, fromTable: MessageNoticeTableType.messageInfo.rawValue).where(condition).limit(40)
        var result = try select.allObjects(of: PCNotificationMessageInfo.self)
        resultArray.append(contentsOf: result)
        
        let otherSelect = try messageNoticeDB.prepareSelect(of: MessageNoticeTableType.messageInfo.tableType, fromTable: MessageNoticeTableType.messageInfo.rawValue).where(!condition)
        let otherResult = try otherSelect.allObjects(of: PCNotificationMessageInfo.self)
        resultArray.append(contentsOf: otherResult)
    } catch {
        
    }

这个问题有原因么？

**Comment by jiyang7** [comment]
麻烦看下第一个问题

我在一个do catch内查询同一个表中两个不同条件的数据，发现结果1 result 和 结果2 otherResult 数据相同，理论上两个条件不同结果是不应该相同的，如果分开至两个do catch执行两次查询结果则不同。

    do {
        let condition = PCNotificationMessageInfo.Properties.notifyType.in([6, 7, 10])
        let select = try messageNoticeDB.prepareSelect(of: MessageNoticeTableType.messageInfo.tableType, fromTable: MessageNoticeTableType.messageInfo.rawValue).where(condition).limit(40)
        var result = try select.allObjects(of: PCNotificationMessageInfo.self)
        resultArray.append(contentsOf: result)
        
        let otherSelect = try messageNoticeDB.prepareSelect(of: MessageNoticeTableType.messageInfo.tableType, fromTable: MessageNoticeTableType.messageInfo.rawValue).where(!condition)
        let otherResult = try otherSelect.allObjects(of: PCNotificationMessageInfo.self)
        resultArray.append(contentsOf: otherResult)
    } catch {
        
    }

请问这个问题有原因么?issues/wiki是否有相关内容？

**Comment by Qiuwen-chen** [comment]
You can give a demo project to reproduce it.

**Comment by jiyang7** [comment]
简单建了一个测试工程，麻烦看一下。
[https://github.com/jiyang7/WCDBTestSample.git](url)

**Comment by Qiuwen-chen** [comment]
Got it, it is indeed an obvious bug. I will fix it in the next version.

For now, you can use this interface to avoid this problem:
database.getObjects(on: Sample.Properties.all, fromTable: tableName, where: condition, orderBy: [orderBy])

**Comment by Qiuwen-chen** [comment]
Fixed in v2.1.6
