### ISSUE TITLE
Database.add(tokenizer:) memory leak

### ISSUE THREAD

**Issue by make1a** [Tencent/wcdb#1106]
memory leak:

![image](https://github.com/Tencent/wcdb/assets/17469549/df118b33-be36-4bf3-bd9b-948f8a0bb20e)
![image](https://github.com/Tencent/wcdb/assets/17469549/f1ce978b-d078-488d-8f68-1ba38d905c61)

**Comment by Qiuwen-chen** [comment]
Can't reproduce
