### ISSUE TITLE
in Objective-c language  pod " WCDB.swift"

### ISSUE THREAD

**Issue by BaronWj** [Tencent/wcdb#1109]
### The language of WCDB

> Objective-c and swift

### The version of WCDB

> 2.0.4

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `WCDB.swift` depends upon `WCDBOptimizedSQLCipher`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

**Comment by Qiuwen-chen** [comment]
I will consider it. For now, you can git clone source files and compile them as static lib.
