### ISSUE TITLE
grouy by 查询之后，如何返回实体类呢

### ISSUE THREAD

**Issue by jimdaxu** [Tencent/wcdb#1110]
### The language of WCDB

> e.g. swift 

### The version of WCDB

> e.g. v2.1.5

### The platform of WCDB

> e.g. Android

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
<img width="1147" alt="image" src="https://github.com/Tencent/wcdb/assets/14083020/694d3565-6c31-4306-ab4d-6229c0fa1b28">
grouy by 查询之后，如何返回实体类呢？现在返回的是[Any]。

**Comment by Qiuwen-chen** [comment]
The result of getRows is MultiRowsValue, you can use it to construct any type of object.

**Comment by jimdaxu** [comment]
请问下MultiRowsValue 怎么实例化成实体类呢？

**Comment by Qiuwen-chen** [comment]
MultiRowsValue is just a two-dimensional array. You read the data in it and assign it to your object.
