### ISSUE TITLE
Can't find column "xxx" in class orm config.

### ISSUE THREAD

**Issue by philipdroid** [Tencent/wcdb#1111]
### The language of WCDB

> Kotlin, ksp

### The version of WCDB

> 2.1.4

### The platform of WCDB

> Android

### The installation of WCDB

> Maven

### What's the issue?

Hi, i have a SDK project using RoomX. 
Resently i'm trying to switch to WCDB, but there's a problem confusing me.
There's an entity class named GroupMember, groupID and userID are two important attributes, and they will be treated as MultiPrimary columns.
For history reason, groupID and userID are attribute names of GroupMember entity, but the corresponding field name in the database table are group_id and user_id.
I have followed the wiki guide to config the build.gradle correctly, and some of DBxxx file are generated successfully. BTW, i'm using ksp. But DBGroupMember is not generated.
This is screenshots for errors:

![1718261857999](https://github.com/Tencent/wcdb/assets/5170304/73686814-e332-4098-afbe-98633ee8b871)

After checking wiki guides, i found this:

![1718264202008](https://github.com/Tencent/wcdb/assets/5170304/1a6f7e29-ca19-4b06-a207-791951b18f6a)

So i changed the MultiPrimary columns name to database table field name, like this:

![1718264792111](https://github.com/Tencent/wcdb/assets/5170304/7affebd3-4cf7-4c9c-bd27-a19e7eae5f0c)

After rebuild, new error occurs:

![1718264707209](https://github.com/Tencent/wcdb/assets/5170304/40e6047b-2b9a-419d-9c5c-bc679c396acf)

If i rename GroupMember attribute names groupID and userID to group_id and user_id directly, it works, but i think it's unacceptable, because theSDK has been accessed by the customer and is running online, This change will result in changes to the access party's business code.

This is a perplexing question for me, any help is welcome.

**Comment by Qiuwen-chen** [comment]
Got it, I will fix it soon, please wait.

**Comment by Qiuwen-chen** [comment]
Fixed in 2.1.6
