### ISSUE TITLE
请问为什么多线程触发创建同一张表，创建表的sql会拼接错误

### ISSUE THREAD

**Issue by 374714754** [Tencent/wcdb#1116]
struct TestUser: TableCodable {
    var userId: String?
    
    enum CodingKeys: String, CodingKey, CodingTableKey {
        public typealias Root = TestUser
        public static let objectRelationalMapping = TableBinding(CodingKeys.self) {
            BindColumnConstraint(.userId, isPrimary: true)
            BindIndex(userId, namedWith: "_uniqueIndex", isUnique: true)
        }
        case userId
    }
}

func testCreateTable() {
        let documentPath = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0]
        let dbPath = documentPath.appending("/test.db")
        let database = WCDBSwift.Database(at: dbPath)
        database.traceError { error in
            if error.code == .NotADatabase, let path = error.infos[.path]?.stringValue {
                try? FileManager.default.removeItem(at: URL(fileURLWithPath: path))
            }
            let ignoreError: [WCDBError.Level] = [.Ignore, .Debug]
            if !ignoreError.contains(error.level) {
                print("[WCDB]\(error)")
            } else {
                print("[WCDB]\(error)")
            }
        }
        let queue = DispatchQueue(label: "test creat table", attributes: .concurrent)
        
        for _ in 0 ... 1000 {
            queue.async {
                try? database.create(table: "user", of: TestUser.self)
            }
        }
        
    }

报错信息：
[ERROR] Code:Error Message:table "user" has more than one primary key,Source:SQLite,Path:/var/mobile/Containers/Data/Application/B28C2919-E1A1-45DF-8386-10A1C0E02211/Documents/test.db,SQL:CREATE TABLE IF NOT EXISTS user(userId TEXT PRIMARY KEY PRIMARY KEY)

**Comment by 374714754** [comment]
版本号： WCDB (2.1.2)

**Comment by Qiuwen-chen** [comment]
It is caused by sqlite.

**Comment by peiyangli** [comment]
> It is caused by sqlite.

根本不是sqlite的问题，就是并发的问题。这个问题存在很久了。
下面这个图中有两个“primary key”的constraint：

![Image](https://github.com/user-attachments/assets/e6b0042c-c483-412e-a13c-f0994fe8404f)

下面逻辑代码必现（ModelTest并发初始化其字段的constraint的问题）：
//try db?.create(table: test, of: ModelTest.self)   //取消注释临时处理
for i in 0..<500 {
    q1.async { //线程1
		try db?.create(table: test_i, of: ModelTest.self)
    }
    q2.async {//线程2
		try db?.create(table: test_(500+i), of: ModelTest.self)
    }
}
