### ISSUE TITLE
Wish to Upgrade WCDB From 1.0.75 To 2.1.6, It looks like WCDBOptimizedSQLCipher is required upgrade From 1.2.0 to 1.4.4，but has no changeLog

### ISSUE THREAD

**Issue by waitianlou** [Tencent/wcdb#1117]
### The language of WCDB
Objective-C

### The version of WCDB
1.0.75

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?
Wish to Upgrade WCDB From 1.0.75 To 2.1.6, It looks like WCDBOptimizedSQLCipher is required upgrade From 1.2.0 to 1.4.4，but has no changeLog；
This is a huge upgrade，but do not find Full change log at https://github.com/Tencent/sqlcipher/tree/wcdb；
The main goal is to know what optimizations are in place and whether configurations or switches are required

**Comment by Qiuwen-chen** [comment]
The change logs of WCDB has covered all the things.

**Comment by waitianlou** [comment]
thx,  by the way，Is there any plan to snapshot new version of to WCDBOptimizedSQLCipher ?  @Qiuwen-chen

**Comment by Qiuwen-chen** [comment]
No plans in the short term.
