### ISSUE TITLE
请问 SELECT * from `models` where `id` in (26612,26611,26610) order by field(id,26612,26611,26610); OderBy 部分怎么转化呢

### ISSUE THREAD

**Issue by LinglongKK** [Tencent/wcdb#1118]
### The language of WCDB

>  Swift 

### The version of WCDB

>  v2.1.2

### The platform of WCDB

>  iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> implement sql -> "SELECT * from `models` where `id` in (26612,26611,26610) order by field(id,26612,26611,26610)"
> 
> how to convert order by statement

**Comment by Qiuwen-chen** [comment]
Is it a valid sql for sqlite?

**Comment by LinglongKK** [comment]
Sorry , the field function is a syntax supported by MySQL.
