### ISSUE TITLE
'atomic' file not found

### ISSUE THREAD

**Issue by xindizhiyin2014** [Tencent/wcdb#1119]
### The language of WCDB

>  Objective-C, 

### The version of WCDB

> v2.1.6
pod 'WCDB.objc','~>2.1.6'

### The platform of WCDB

>  iOS

### The installation of WCDB

>  Cocoapods

### Xcode version
> Version 15.4

### What's the issue?

> 'atomic' file not found
> 
> when compile I meet this error ,but I check my C++ config
<img width="961" alt="image" src="https://github.com/Tencent/wcdb/assets/8096086/adad600e-62c5-49a2-8caf-9cc006b1f991">

<img width="1241" alt="image" src="https://github.com/Tencent/wcdb/assets/8096086/7566da40-b5aa-4310-abca-6c066ffeda65">

**Comment by Qiuwen-chen** [comment]
Just google how to solve.

**Comment by xindizhiyin2014** [comment]
hello ,I found the reason,when I use wcdb with ```pod 'WCDB.objc','~>2.1.6'``` ,in my project , it works well, but when I create my pod library in pod.spec file use   ``` s.dependency 'WCDB.objc' ```, the error occur, please help me, thanks

**Comment by Qiuwen-chen** [comment]
You can give me a demo project to reproduce this  problem.
