### ISSUE TITLE
swift中，请问查询条件中如果需要使用两列组合出的新的字段，应该如何拼装呢。 例如SELECT * from table where a||'_'||b in ('1_33'); 其中a和b是整形

### ISSUE THREAD

**Issue by zhangyanforever** [Tencent/wcdb#1121]
Swift, v2.1.2
如题，如何实现这个sql拼装呢
SELECT * from table where a||'_'||b in ('1_33'); 其中a和b是整形

**Comment by Qiuwen-chen** [comment]
a.concat("_").concat(b).in("1_33")
