### ISSUE TITLE
Xcode 16.0 beta,iOS 18， Expression类重名

### ISSUE THREAD

**Issue by zhangyanforever** [Tencent/wcdb#1122]
### The language of WCDB

Swift 

### The version of WCDB

v2.1.6

### The platform of WCDB

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

使用Xcode 16.0 beta ，WCDB的Expression类和系统Foundation库struct类型的 Expression重名了，后续会优化这个吗

**Comment by zhangyanforever** [comment]
![11](https://github.com/Tencent/wcdb/assets/36877096/885ce14d-8590-4da0-949a-b0d498f5a6a1)

**Comment by Qiuwen-chen** [comment]
Does it cause any problem?

**Comment by zbfksurjgliae** [comment]
我也遇到了同样的问题，Xcode16 build报错'Expression' is ambiguous for type lookup in this context

**Comment by Qiuwen-chen** [comment]
I can't come up with another name. Please change it to "WCDB.Expression" to avoid confliction.
