### ISSUE TITLE
全文搜索效果和微信的区别

### ISSUE THREAD

**Issue by zhengshengxi** [Tencent/wcdb#1123]
### The language of WCDB

Swift

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

库中有文本 “我是中国人” ，输入“我是”可以匹配，输入“中国”可以匹配，输入“我是人”却无法匹配。同样的内容在微信里是可以搜索到的，微信聪明多了
请问这个搜索效果的差异是什么原因？是否可以达到微信的搜索效果？

**Comment by Qiuwen-chen** [comment]
Here is our design:
https://mp.weixin.qq.com/s/Ph0jykLr5CMF-xFgoJw5UQ
https://github.com/Tencent/wcdb/wiki/Swift-%e5%85%a8%e6%96%87%e6%90%9c%e7%b4%a2
