### ISSUE TITLE
How to integrate into iOS project through source code？

### ISSUE THREAD

**Issue by 1704010901** [Tencent/wcdb#1129]
### The language of WCDB

> e.g. Objective-C

### The version of WCDB

> e.g. v2.1.6

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. AAR Package or Git clone

### What's the issue?

1. The source code is dragged to the shell project, which contains many unknown files. In addition, the shell project depends on the business project, and the business project cannot call the WCDB API.
2. Is there no existing .framework file or some script that can generate binary code?

**Comment by Qiuwen-chen** [comment]
We have provided the xcode project of WCDB. You should learn how to build a framework. It's not difficult.
