### ISSUE TITLE
'SQLite.h' file not found

### ISSUE THREAD

**Issue by Toj-dev** [Tencent/wcdb#1130]
pod 'WCDB.swift'

![image](https://github.com/Tencent/wcdb/assets/43204431/25c12b54-fc40-41a3-8b7f-df23156b469d)
![image](https://github.com/Tencent/wcdb/assets/43204431/863b8488-b0cc-497e-a748-34f676018113)

**Comment by Qiuwen-chen** [comment]
You should check your pod status

**Comment by Toj-dev** [comment]
![image](https://github.com/user-attachments/assets/aec96969-f324-43b4-afda-7d9cd0538068)

**Comment by Toj-dev** [comment]
有这个文件的

**Comment by Toj-dev** [comment]
![image](https://github.com/user-attachments/assets/d815834b-6780-42bd-9b35-3c08ac64db00)
2个库文件冲突?
