### ISSUE TITLE
iOS wcdb 2.0以上版本 firebase 数据库冲突问题 

### ISSUE THREAD

**Issue by l819183457** [Tencent/wcdb#1132]
### The language of WCDB

Swift 

### The version of WCDB
2.0 以上
### The platform of WCDB
iOS 
### The installation of WCDB
Cocoapods

### What's the issue?

iOS wcdb 2.0以上版本 firebase 数据库冲突问题

**Comment by Qiuwen-chen** [comment]
Can you explain it in detail?

**Comment by l819183457** [comment]
pod 'Google-Mobile-Ads-SDK'pod“FirebaseAnalytics”pod 'FirebaseAuth'pod“FirebaseFirestore”pod 'FirebaseCrashlytics'pod 'GoogleSignIn'pod 'FBSDKCoreKit'
都是最新的，然后使用wcdb 2.0以上会发生！[图片]（https://github.com/user-attachments/assets/08fa693b-de30-476d-b121-413fc7241938）
我现在只能先用1.0的做现在的开发

**Comment by Qiuwen-chen** [comment]
I can not open your picture

**Comment by l819183457** [comment]
![WeChat8d863a6f23929f93594fa9b42da32baf](https://github.com/user-attachments/assets/b2716839-c52d-44e7-a654-f5f2834288a0)

**Comment by Qiuwen-chen** [comment]
config.h is a header of sqlite. You should try to solve it, I can not help.
