### ISSUE TITLE
wcdb.objc在watchos上支持armv7k架构吗？

### ISSUE THREAD

**Issue by JuneLee61** [Tencent/wcdb#1133]
我遇到一个问题，就是我的项目有手表的Extension，手表项目中也使用wcdb，使用Xcode15构建上传AppStore时，报错缺少项目架构armv7k，如下图
![image](https://github.com/user-attachments/assets/46b3d35b-7199-4e6b-b0bc-13ab5c89c050)

然后在iWatch Extension的target中build setting中新增armv7k的架构，编译时就报错了，提示wcdb不支持armv7k的架构
![image](https://github.com/user-attachments/assets/c9e262e8-71bf-4e40-b56a-88be0417a848)

你能帮帮我吗？

**Comment by Qiuwen-chen** [comment]
You should google how to solve it.

**Comment by JuneLee61** [comment]
我尝试在Google寻找解决办法，但是都没有找到，我查看wcdb.podspec文件中，针对watchos的架构支持是这样的
"VALID_ARCHS[sdk=watchos*]" => "arm64_32 arm64 86_64",
根据报错信息，应该是wcdb没有支持armv7k的架构

**Comment by JuneLee61** [comment]
> You should google how to solve it.

我尝试在Google寻找解决办法，但是都没有找到，我查看wcdb.podspec文件中，针对watchos的架构支持是这样的
"VALID_ARCHS[sdk=watchos*]" => "arm64_32 arm64 86_64",
根据报错信息，应该是wcdb没有支持armv7k的架构

**Comment by Qiuwen-chen** [comment]
armv7k is too old, and I don't want to support it. You can build WCDB from source.
