### ISSUE TITLE
WCDBOptimizedSQLCipher，执行下面这个函数，报错no such function sqlcipher_export，用普通版本的sqlcipher是可以的

### ISSUE THREAD

**Issue by Ronnydalinseri** [Tencent/wcdb#1134]
### The language of WCDB

Objective-C

### The version of WCDB

2.1.6

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?
WCDB包含的sqlcipher，执行下面这个函数，报错no such function sqlcipher_export，用普通版本的sqlcipher是可以的

sqlite3_exec(unencrypted_DB, "SELECT sqlcipher_export('encrypted');", NULL, NULL, &errmsg);

**Comment by Ronnydalinseri** [comment]
Thank you. This is My Demo. 当在主页调用encrypt时，会报错no such function，需要把podfile改成 pod 'FMDB/SQLCipher'，才能解决问题，并且我发现分开写pod 'FMDB', pod 'SQLCipher'也会有WCDB同样的问题
[sqlcipherDemo-master 2.zip](https://github.com/user-attachments/files/16283185/sqlcipherDemo-master.2.zip)

**Comment by Qiuwen-chen** [comment]
You are actually using the sqlite provided by the system. Unlink it and use -[WCTDatabase execute:] instead.
