### ISSUE TITLE
how to set auto_vacuum to 1

### ISSUE THREAD

**Issue by NNlml** [Tencent/wcdb#1135]
### The language of WCDB

swift

### The version of WCDB

v2.1.1

### The platform of WCDB

iOS

### The installation of WCDB

Git clone

### What's the issue?

创建数据库时, 使用如下代码尝试设置auto_vacuum 为1 (full) 无效. 使用 DB Browser for Sqlite 软件打开创建的数据库, 看到auto_vacuum 还是0 (none) . 如何设置数据库的auto_vacuum 为1 ?

let db = Database(at: filePath)
let pragma = StatementPragma().pragma(.autoVacuum).to(1)
try? db.exec(pragma)
try? db.vacuum(with: nil)
return db

**Comment by Qiuwen-chen** [comment]
You can only set auto_vacuum for a  newly created db.

**Comment by NNlml** [comment]
上面代码就是新装app, 第一次创建数据库时, 文件4k, 并且没有创建任何表的时候执行的, 没有效果

**Comment by NNlml** [comment]
@Qiuwen-chen

**Comment by Qiuwen-chen** [comment]
First, you need to confirm how to set autovaccum when using SQLite directly.

Then, you can use the trace interface to watch all sql that WCDB excuted: https://github.com/Tencent/wcdb/wiki/Swift-%e7%9b%91%e6%8e%a7%e4%b8%8e%e9%94%99%e8%af%af%e5%a4%84%e7%90%86

This way you can compare the differences in raw sqlite and WCDB to find out what is wrong.
