### ISSUE TITLE
检查数据库是否崩溃的函数checkIfCorrupted一直返回true

### ISSUE THREAD

**Issue by 593607226** [Tencent/wcdb#1137]
### The language of WCDB

c++

### The version of WCDB

2.1.6

### The platform of WCDB

Windows10

### The installation of WCDB

Git clone

### What's the issue?

我希望在进程启动时检查数据库是否崩溃，如果崩溃就进行修复。手动删除数据库部分内容后，程序启动调用checkIfCorrupted查询是否崩溃返回true，然后调用retrieve进行修复。修复返回成功，调用checkIfCorrupted函数依然返回true。看代码确实是没有把奔溃结果清除的操作，我尝试在checkIfCorrupted返回true时调用removeFiles清空数据库，后面再次调用checkIfCorrupted还是返回true。对于已经恢复正常的数据库，checkIfCorrupted函数是否可以返回false
![image](https://github.com/user-attachments/assets/0ffe2df1-9040-4b32-811f-79cb2ec6913b)

**Comment by Qiuwen-chen** [comment]
Get

**Comment by Qiuwen-chen** [comment]
Fixed in v2.1.7
