### ISSUE TITLE
同一个项目Objective-C的WCDB能否和swift版本的WCDB一起使用？

### ISSUE THREAD

**Issue by superyang2019** [Tencent/wcdb#1138]
### The language of WCDB

> e.g. Objective-C, Swift 

### The version of WCDB

> e.g. v2.1(swift) OC版本1.1.0

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 我想咨询一下，目前我们是16年的老项目，早期是OC版本，目前正在用swift版本进行一部分模块的重构，早期OC使用了wcdb1.1.0版本，线上业务运行还算正常，现在重构的模块计划用swift2.1版本的WCDB，想问一下，如何让一个项目中继运行OC版本的WCDB，又运行swift版本的wcdb，如果不能同时运行，能不能给一些指导性建议，谢谢。
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
Yes, you can

**Comment by Qiuwen-chen** [comment]
You should use WCDB Swift 2.1 and WCDB Objc 2.1 together.

**Comment by superyang2019** [comment]
那 WCDB Swift 2.1 and WCDB Objc 2.1 一起使用，两个组件底层有很多相同的c++代码，而且有一些写了#pragma once
![image](https://github.com/user-attachments/assets/f7c76cd1-2560-4edd-b7db-781fe6aec59b)

**Comment by Qiuwen-chen** [comment]
You can WCDB directly, it contains Objc, Swift, C++ interfaces in one framework.

**Comment by tangxiaopingdev** [comment]
我也有同样的问题。好像不能一起使用。
