### ISSUE TITLE
Skip column problem[need help]

### ISSUE THREAD

**Issue by wdq123550** [Tencent/wcdb#1139]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
oc

### The version of WCDB

> e.g. v1.0.5
pod update newest

### The platform of WCDB

> e.g. iOS, macOS or Android

ios

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
Cocoapods

I have a property 'nickname' in my model.
when my app v1.0.0 'nickname' save to db
but whem my app v1.0.1. the 'nickname' delete from model.
and then. db will print error :wcdb error = [NOTICE: 20, Skip column], Column: nickname
how to fix this problem?
thanks!

**Comment by Qiuwen-chen** [comment]
It's just a notice, and you can ignore it.
