### ISSUE TITLE
WCDB_SYNTHESIZE 变量提示Duplicate declaration

### ISSUE THREAD

**Issue by pkjijie** [Tencent/wcdb#114]
我用Appcode开发iOS 时，WCDB类声明WCDB_SYNTHESIZE提示错误：

Error after macro subsituation: Duplicate declaration of global variable '_unused0'

代码：

WCDB_IMPLEMENTATION(WCTSampleORMIndex)
WCDB_SYNTHESIZE(WCTSampleORMIndex, indexProperty)
WCDB_SYNTHESIZE(WCTSampleORMIndex, multiIndexPart1)   //第一个属性没问题，从这里开始所有属性都提示上述错误
WCDB_SYNTHESIZE(WCTSampleORMIndex, multiIndexPart2)

**Comment by RingoD** [comment]
我使用Appcode能够正常运行WCDB的sample。你本地改了什么？

**Comment by pkjijie** [comment]
![image](https://user-images.githubusercontent.com/5966548/28853600-38b8d66e-7764-11e7-8c19-b5f835d3f0c4.png)

可以运行，就是在appcode里有红色错误提示，看着别扭

另外咨询2个问题，
1. 看了你们关于sqlite读写并发相关的优化，这部分优化是直接把sqlite的源码放到了WCDB库里了吗？
2. 在讲WCDB的特性时，看到Android提到了全文检索，iOS 有这个功能吗？

非常感谢百忙之余答疑解惑！

**Comment by RingoD** [comment]
1. 是的
2. iOS可以自行实现全文搜索，更加便捷的接口还在开发中

**Comment by pkjijie** [comment]
谢谢！请问现在WCDB库有全文检索的支持吗？ 有没有文档可以参考下？

**Comment by RingoD** [comment]
目前没有便捷的接口。
你可以使用WCDB调用SQLite实现。请参考：https://github.com/Tencent/wcdb/wiki/基础类、CRUD与Transaction#核心层接口

**Comment by ChasonTang** [comment]
这个问题确实存在，问题在于 `WCDB_SYNTHESIZE` 宏展开的时候会变成如下代码
```
+ (const WCTProperty &)propertyName {
    static const WCTProperty s_property(
            WCDB_STRINGIFY(intValue), WCTSampleAdvance.class,
            __WCDB_BINDING(WCTSampleAdvance)
                    .addColumnBinding<__WCDB_PROPERTY_TYPE(
                            WCTSampleAdvance, intValue)>(WCDB_STRINGIFY(propertyName),
                            WCDB_STRINGIFY(propertyName)));
    return s_property;
}

static const auto UNUSED_UNIQUE_ID = [](WCTPropertyList &propertyList) {
    propertyList.push_back(WCTSampleAdvance.propertyName);
    return nullptr;
}(__WCDB_PROPERTIES(WCTSampleAdvance));
```
这里做了两件事情
1. 创建了和属性同名的静态方法用于 properties: 等方法的使用
2. 声名 lambda 方法并执行。将这个静态方法加入到 propertyList 中

问题就在于创建的临时变量 `UNUSED_UNIQUE_ID` 重复了，也许可以通过
```
#define TEST_PROPERTIES(className, properties) _unused_##className##_##properties
```
这样的形式定义独一无二的变量名？

**Comment by RingoD** [comment]
@ChasonTang 看起来这是 AppCode 的问题。
`UNUSED_UNIQUE_ID` 使用的是 `__COUNTER__` 的内置宏实现的。
`__COUNTER__` 是 [GNU C extension](https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html) 的标准宏。这个宏会在每次调用的时候，自增 1，因此不会出现重名的情况。
而 AppCode 似乎无法解决这种问题，我并没有使用过 AppCode。有可能是其编译器的问题，也可能是他的某些优化将 `macro.hpp` 这个文件作为 `precompiled header` 了。

**Comment by ChasonTang** [comment]
@RingoD 看起来确实是 AppCode 的问题，我刚刚去 Jetbrains 网站看了一下，这个问题应该在 AppCode 2017.3 EAP 版本上修复了，谢谢
```
Full support for the __COUNTER__ macro and more.
```
https://blog.jetbrains.com/objc/
