### ISSUE TITLE
C++ support for 自定义字段映射类型

### ISSUE THREAD

**Issue by xyz1001** [Tencent/wcdb#1140]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

C++

### The version of WCDB

> e.g. v1.0.5

2.1.6

### The platform of WCDB

> e.g. iOS, macOS or Android

ubuntu

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Git clone

### What's the issue?

C++接口是否支持自定义字段映射类型？如果没有，有什么间接的实现途径么

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
It is not very useful to support custom field mapping for C++. 
You can write code to convert data between your type and supported types.
