### ISSUE TITLE
Help!.  How to code for excuting sql:  "ALERT TABLE table1 DROP PRIMARY KEY"

### ISSUE THREAD

**Issue by must126** [Tencent/wcdb#1141]
### The language of WCDB
swift

### The version of WCDB
最新

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?
As the title, I encountered a problem when updating table.
The table has a primary key, but now I want to remove it without deleting data.  
I known the sqlite syntax, 
 `ALERT TABLE table1 DROP PRIMARY KEY`,  
How it coding with WCDB, please?

**Comment by Qiuwen-chen** [comment]
SQLite do not support to drop primary key.
