### ISSUE TITLE
build error “error: 'numeric_limits' is not a member of 'std'”

### ISSUE THREAD

**Issue by JaneConan** [Tencent/wcdb#1143]
### The language of WCDB

> c

### The version of WCDB

>  v2.1.6

### The platform of WCDB

> linux

### The installation of WCDB

> Git clone

### What's the issue?

··· bash
cd src
mkdir build
cd build
cmake .. && cmake --build . -j8
···

When we compiled, we saw the following exception and couldn't continue.

![image](https://github.com/user-attachments/assets/77a2f5f8-165b-4c09-83c8-59c4e463c423)

**Comment by Qiuwen-chen** [comment]
You can add #include <limits> into StringView.hpp and try again. I will fix it in the next veriosn.

**Comment by Qiuwen-chen** [comment]
Fixed in the master branch.

**Comment by JaneConan** [comment]
> You can add #include <limits> into StringView.hpp and try again. I will fix it in the next version.

Maybe it will also give us the opportunity to write commit code 🤣
This problem was also discovered by our participation in your OpenCloudOS campaign!
