### ISSUE TITLE
c++如何将加密数据库数据导出

### ISSUE THREAD

**Issue by wang70937** [Tencent/wcdb#1144]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
Don't know what do you mean.

**Comment by wang70937** [comment]
> Don't know what do you mean.

知道加密数据库的密码，如何用wcdb将该数据库的数据全部导出为一个新数据库文件，不带密码。

**Comment by Qiuwen-chen** [comment]
You can execute:
WCDB::StatementSelect().select(WCDB::Expression::function("sqlcipher_export").argument("schemaOfEncypedDatabase"))
