### ISSUE TITLE
C++ 如何获取FieldName

### ISSUE THREAD

**Issue by Hin-D** [Tencent/wcdb#1145]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
C++

### The version of WCDB

> e.g. v1.0.5
2.1.6

### The platform of WCDB

> e.g. iOS, macOS or Android
macOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
CMake

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

我用 QT 开发，需要用到 WCDB，为了方便拓展，我希望做一个 table的基类实现 json 映射对象；
本来如果可以继承QObject是可以轻松实现对象遍历然后自己实现映射的，但继承QObject会报错，如下图；

WCDB 需要手动声明所有的 Field，应该是有记录到的，现在如何获取到这个 FiledName？
跪谢～

<img width="1449" alt="image" src="https://github.com/user-attachments/assets/afcb4868-90a2-45fd-a017-65cc47464594">

**Comment by Qiuwen-chen** [comment]
for(const auto &field : ObjectType::allFields()) {
   printf(field.syntax().name.data())
}
