### ISSUE TITLE
How to create a trigger?

### ISSUE THREAD

**Issue by AlexanderOliverAustin** [Tencent/wcdb#1146]
### The language of WCDB

> Swift

### The version of WCDB

>  v2.1.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Carthage

### What's the issue?

> I want to create a trigger for Table A so that when a set of data is inserted into Table A, it simultaneously triggers an operation to insert the current data into Table B. I have already read the WCDB project (StatementCreateTrigger) and related wikis, but I have no idea how to use WCDB’s API to handle NEW.ColumnName in the trigger. How can I express NEW.ColumnName using WCDB's API? Here is the SQL statement:
>
```
 CREATE TRIGGER IF NOT EXISTS  ATrigger
    AFTER INSERT ON ATable
    FOR EACH ROW
    BEGIN
    INSERT INTO BTable(id,title,content) VALUES(NEW.id,NEW.title,NEW.content);
    END;
```
>

**Comment by Qiuwen-chen** [comment]
Column(named: "NEW.id")
