### ISSUE TITLE
自定义数据库配置无效, 且wiki中默认配置无效

### ISSUE THREAD

**Issue by NNlml** [Tencent/wcdb#1147]
### The language of WCDB
 Swift
### The version of WCDB
v2.1.6
### The platform of WCDB
iOS
### The installation of WCDB
Cocoapods
### What's the issue?
跟前贴
[https://github.com/Tencent/wcdb/issues/1135](url)

我仔细研究了一下wcdb初始化创建数据库时候的配置设置, 创建数据库时, 会按照baseconfig进行一次配置设置, 我自定义的所有设置执行都会在baseconfig设置之后, 那么如何在baseconfig的设置执行之前, 插入我自己的设置呢?

        let wcdbPath = docPath.appending("/wcdb.sqlite")
        let wcdb = Database(at: wcdbPath)
        do {
            try wcdb.exec(StatementPragma().pragma(.autoVacuum).to(1))
        } catch let e {
            NSLog("wcdb %@", e as NSError)
        }
        
        if !wcdb.canOpen {
            NSLog("can not open wcdb")
        } else {
            wcdb.setConfig(named: "demo", withInvocation: { handle in
                try handle.exec(StatementPragma().pragma(.autoVacuum).to(1))
            }, withUninvocation: { handle in
                try handle.exec(StatementPragma().pragma(.autoVacuum).to(1))
            }, withPriority: .highest)
        }
        
这段代码, 无论是setconfig设置 auto_vacuum, 还是直接执行 都无法将 auto_vacuum改为1 

![QQ20240808-102729](https://github.com/user-attachments/assets/c579c274-7367-4db0-b306-dece126eb37d)

打印执行顺序看到auto_vacuum在最后执行了. 实际上是wcdb.exec这句执行的. setconfig里面handle.exec还没有执行.
我手动创建了一个数据库, 第一句就执行 pragma auto_vacuum = 1 是可以的. 
附上一个demo. 和FMDB的对比. FMDB创建没有执行任何配置, 直接执行设置 auto_vacuum就可以. 
麻烦看一下为什么wcdb无法设置成功.

另外, wcdb在wiki中, 默认配置写的 PRAGMA checkpoint_fullfsync=1 实际上也没有执行成功. 
附上使用wcdb创建数据库后, 使用 db browser for sqlite打开的空数据库, wcdb创建之后数据库的设置配置

![QQ20240808-103259](https://github.com/user-attachments/assets/2bdb454e-aecf-488d-8263-477112078ce4)

[test.zip](https://github.com/user-attachments/files/16536835/test.zip)

**Comment by Qiuwen-chen** [comment]
I will add a new interface to support this in next version, please wait.

**Comment by Qiuwen-chen** [comment]
Now, you can use enableAutoVacuum method to config in v2.1.7.
