### ISSUE TITLE
请问在KMM跨平台项目如何使用WCDB？

### ISSUE THREAD

**Issue by SamiuZhong** [Tencent/wcdb#1148]
### The language of WCDB

Kotlin

### The version of WCDB

v2.1.6

### The platform of WCDB

Android, iOS

### The installation of WCDB

Maven

### What's the issue?

我在使用Kotlin Multiplatform Mobile编写跨Android和iOS的项目，实现逻辑代码的双端共享，请问WCDB支持KMM跨平台编写吗？应该如何使用呢？

**Comment by Qiuwen-chen** [comment]
For now, you can try WCDB C++.
