### ISSUE TITLE
How can use the cmake_install.cmake?

### ISSUE THREAD

**Issue by JaneConan** [Tencent/wcdb#1149]
### The language of WCDB

> c

### The version of WCDB

> master

### The platform of WCDB

> Linux

### The installation of WCDB

> Git clone

### What's the issue?

How can use the cmake_install.cmake?

![image](https://github.com/user-attachments/assets/8c0718a2-8cee-4896-9a69-9dabf1556b95)

**Comment by JaneConan** [comment]
<img width="495" alt="image" src="https://github.com/user-attachments/assets/e13ea657-2f99-4a86-b8ef-ff9ee0a1c328">

**Comment by Qiuwen-chen** [comment]
I have no idea.
