### ISSUE TITLE
WCDB_PRIMARY_AUTO_INCREMENT 会出现编译错误 

### ISSUE THREAD

**Issue by leonylcatwork** [Tencent/wcdb#115]
使用中遇到两个问题:

1. WCDB_PRIMARY_AUTO_INCREMENT 会出现编译错误 (请看 DBTransaction.mm 注解, 通过 cocoapods 安装, wcdb 版本为 1.0.3)

2. 自定义  NSDate 转换时, 按照 sample 的代码写, 不知道如何引用 NSDate+WCTColumnCoding.mm 文件. 不引用的话没有效果. (我的转换是包含毫秒的). 不知道是否我理解错误?

谢谢

DBTransaction.h
```objc
#import <Foundation/Foundation.h>

@interface DBTransaction : NSObject

@property (nonatomic, assign) NSInteger id;
@property (nonatomic, assign) double amount;
@property (nonatomic, assign) NSInteger points;
@property (nonatomic, strong) NSDate *date;
@property (nonatomic, copy  ) NSString *code;

@end
```

DBTransaction.mm
```objc
@implementation DBTransaction

WCDB_IMPLEMENTATION(DBTransaction)

WCDB_SYNTHESIZE_COLUMN_DEFAULT(DBTransaction, id, "t_id", 1)
WCDB_SYNTHESIZE_COLUMN_DEFAULT(DBTransaction, amount, "t_amount", 0)
WCDB_SYNTHESIZE_COLUMN_DEFAULT(DBTransaction, points, "t_points", 0)
WCDB_SYNTHESIZE_COLUMN_DEFAULT(DBTransaction, date, "t_date", NULL)
WCDB_SYNTHESIZE_COLUMN_DEFAULT(DBTransaction, code, "t_code", NULL)

/// 此处报错: Property implementation must have its declaration in interface 'DBTransaction' or one of its extensions
/// 改为 WCDB_PRIMARY(DBTransaction, id) 可以编译, 但是就不能 auto increment 了
WCDB_PRIMARY_AUTO_INCREMENT(DBTransaction, id)

@end
```

NSDate+WCTColumnCoding.mm
```objc
#import <Foundation/Foundation.h>
#import <WCDB/WCDB.h>

@interface NSDate (WCTColumnCoding) <WCTColumnCoding>
@end

@implementation NSDate (WCTColumnCoding)

+ (instancetype)unarchiveWithWCTValue:(NSNumber *)value {
    return value ? [NSDate dateWithTimeIntervalSince1970:(value.doubleValue / 1000)] : nil;
}

- (NSNumber *)archivedWCTValue {
    return @((long long)(self.timeIntervalSince1970 * 1000));
}

+ (WCTColumnType)columnTypeForWCDB {
    return WCTColumnTypeInteger64;
}

@end
```

**Comment by RingoD** [comment]
id是OC的保留关键字，你改掉试试

**Comment by leonylcatwork** [comment]
@RingoD 
id 是可以用作变量名的, 应该不会存在问题. 尝试了改为 transactionId 不过没有什么区别, 依然是同一个错误 T_T

能麻烦你看一下吗? 我创建了一个 repo [https://github.com/leonylcatwork/wcdb_test](url), 包含了 wcdb 的 pod.

**Comment by RingoD** [comment]
访问你的repo 404了，sample内也有`WCDB_PRIMARY_AUTO_INCREMENT`的示例用法可供参考。

**Comment by leonylcatwork** [comment]
@RingoD 不好意思, url 给错了 

https://github.com/leonylcatwork/wcdb_test

我就是按照 sample 的示例写无法编译才不知道如何的. 麻烦了

**Comment by RingoD** [comment]
你的类没有遵循WCTTableCoding协议。

https://github.com/Tencent/wcdb/wiki/iOS-macOS使用教程#类字段绑定orm

**Comment by leonylcatwork** [comment]
@RingoD 可以了, 即使暴露的 category 遵循 WCTTableCoding, implement 里面还是需要遵循这个协议.

那关于第二个疑问的问题出在哪里呢?

2. 自定义 NSDate 转换时, 按照 sample 的代码写, 不知道如何引用 NSDate+WCTColumnCoding.mm 文件. 不引用的话没有效果. (我的转换是包含毫秒的). 不知道是否我理解错误?

**Comment by RingoD** [comment]
NSDate+WCTColumnCoding.mm包含在WCDB的代码里了。
如果是动态库，则不需要特别的设置。如果是静态库，则需要按教程里设置linker flag

**Comment by leonylcatwork** [comment]
@RingoD 那如果我希望改写这个转换呢 (比如我的转换需要包含毫秒, 即 time interval * 1000) ? 我是不是需要 subclass NSDate 然后在新的 class 遵循 WCTColumnCoding?

**Comment by RingoD** [comment]
如果要自定义内置类的column coding，则去掉`WCDB_BUILTIN_COLUMN_CODING`宏
