### ISSUE TITLE
通过Cocoapods同时引入WCDB.swift(最新的2.1.6)和OpenCV(4.3.0)时候，编译错误

### ISSUE THREAD

**Issue by Hpp6554** [Tencent/wcdb#1150]
### The language of WCDB
Swift

### The version of WCDB
v2.1.6

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?
在我自己的项目中同时引用了WCDB.swift和OpenCV，使用WCDB.swift(1.0.8.2)版本时候，可以正常使用，此时OpenCV版本是4.3.0，当我升级WCDB.swift到2.1.6版本时，编译报错，报错截图如下，当我在MigratingStatementDecorator.cpp中点击Core.hpp时候，会跳转到OpenCV的core.hpp文件中，这个有什么办法解决么？
![image](https://github.com/user-attachments/assets/6432ae69-a58d-4477-9b06-45ca3bfb87e3)

```[tasklist]
### Tasks
```

**Comment by Hpp6554** [comment]
截图代码是我新建的工程，只导入了这WCDB.swift和OpenCV库，然后编译报错的截图

**Comment by Qiuwen-chen** [comment]
I will rename this file in the next version.

**Comment by Qiuwen-chen** [comment]
Fixed in v2.1.7
