### ISSUE TITLE
IOS 源数据库如果是加密数据库 迁移成无加密数据库 现在是否已经支持？

### ISSUE THREAD

**Issue by BaronWj** [Tencent/wcdb#1154]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
Please see: https://github.com/Tencent/wcdb/wiki/Swift-%E6%95%B0%E6%8D%AE%E8%BF%81%E7%A7%BB
