### ISSUE TITLE
WCDB如何分组查询某字段值的求和 sum( XXField)

### ISSUE THREAD

**Issue by 243573077** [Tencent/wcdb#1155]
### The language of WCDB

> Java and kotlin

### The version of WCDB

>  v2.1.4

### The platform of WCDB

> Android

### The installation of WCDB

>  Maven,

### What's the issue?

> 请问下  这种sql 在java或者kotlin中 应该如何用WCDB写,假设表A有4个字段，分别是id, money,kind, time。前3个字段类型均是int类型，time字段是long类型。
> “select *, sum(money) from table A where time >100 and time < 200 group by kind order by time desc”
>我在使用WCDB的StatementSelect时，发现他的select()方法只能传入WCDB注解自动生成的field字段数组。

**Comment by Qiuwen-chen** [comment]
new StatementSelect().select(Column.all(), id.sum())
