### ISSUE TITLE
Could you give us WCDB C++ Demo?

### ISSUE THREAD

**Issue by JaneConan** [Tencent/wcdb#1156]
### The language of WCDB

> C++

### The version of WCDB

> v2.1.6

### The platform of WCDB

> Linux

### The installation of WCDB

> Git clone

### What's the issue?

We've looked at your wiki documentation, but we can't find a complete working C++ program, could you please provide us with a demo?

Thanks a lot!

**Comment by Qiuwen-chen** [comment]
I don't have time to do that
