### ISSUE TITLE
与FMDB链接的sqlite3共存问题

### ISSUE THREAD

**Issue by Ronnydalinseri** [Tencent/wcdb#1157]
### The language of WCDB

Objective-C, Swift 

### The version of WCDB

2.1.0

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

由于项目需要，通过cocoapods引入了FMDB，FMDB会自动链接系统提供的sqlite3，导致我自己的代码在调用sqlite3_exec的时候，总是会调用到系统提供的sqlite3而不是WCDBOptimizedSQLCipher提供的sqlite3_exec接口

**Comment by Qiuwen-chen** [comment]
You should build WCDB as a dynamic framework
