### ISSUE TITLE
我在调用OC的WCDB查询接口时，子线程卡住了，迟迟不给查询结果

### ISSUE THREAD

**Issue by superyang2019** [Tencent/wcdb#1158]
### The language of WCDB

> e.g. Objective-C

### The version of WCDB

> e.g. v1.1.0

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.

![image2024-8-14_18-21-9](https://github.com/user-attachments/assets/3070825a-fabe-4919-ac39-4cc81147f199)
![image2024-8-14_18-22-2](https://github.com/user-attachments/assets/5af006f4-f59d-431a-aa59-8ca175721a61)
![WX20240814-182936](https://github.com/user-attachments/assets/0846748f-ffba-4fde-809e-3b4edbc26f71)~

> Explain what you want by example or code **in English**.

我的业务方法图三在调用查询群信息的时候，一直没有返回，借助第三方平台监控，发现线程66自己在等待自己，而且他持有了锁，其他线程查询都要等待，我们业务有在主线程中查询数据库，所以主线程也被卡住了，想咨询一下，为啥查询DB没有得到数据结果。

**Comment by Qiuwen-chen** [comment]
Please upgrade to the latest version

**Comment by Qiuwen-chen** [comment]
Or you should downgrade wcdb to v1.0.x
