### ISSUE TITLE
In Windows environment, the project compiles incorrectly

### ISSUE THREAD

**Issue by JaneConan** [Tencent/wcdb#1159]
### The language of WCDB

> C++

### The version of WCDB

> v2.1.6

### The platform of WCDB

> windows

### The installation of WCDB

> Git clone

### What's the issue?

![image](https://github.com/user-attachments/assets/59931cc8-7ae8-4898-b099-c1fe324d8e66)

Names followed by ‘::’ must be class names or namespace names

```C#
        m_databaseHolder = Core::shared().getOrCreateDatabase(newPath);
```

Is it written here correctly to confirm that it's not CommonCore, but Core?

**Comment by Qiuwen-chen** [comment]
Yes, it should be CommonCore. It's fixed in the master branch.
