### ISSUE TITLE
有个疑问

### ISSUE THREAD

**Issue by zhangkehu** [Tencent/wcdb#116]
Android wcdb 1.0.0
我感觉app使用一段时间会丢失某些数据，我一个数据表里存的数据更新完新版本账号会丢失一部分或全部，没找到必现的场景，比较困惑。我是app运行期间不关闭数据库连接的。

**Comment by John-He-928** [comment]
更新新版本是更新app还是wcdb？

一般来说是不存在“丢失部分或全部数据”这种现象的，我估计是下面这几种情况

* 数据库损坏，这个会抛异常，而且概率不高，而且不会丢部分数据，不太像是这样
* SQLiteOpenHelper里面Schema升级处理不当

你可以设一下SQLiteTrace接口，将执行的所有SQL打印出来，排查一下具体执行过哪些SQL

**Comment by zhangkehu** [comment]
更新的是app的版本，我自己也觉得不太可能，我删除数据都有记录日志，日志文件没有任何删除记录，但是覆盖安装新版本里面的数据少了。在安装新版本之前数据是正常的。新版本没有数据库升级操作。

**Comment by zhangkehu** [comment]
乌龙了，其实是数据没有写进去，关闭这个问题
