### ISSUE TITLE
WCDB C++ usage

### ISSUE THREAD

**Issue by 0x1306a94** [Tencent/wcdb#1160]
### The language of WCDB

> C++

### The version of WCDB

> v2.1.6

### The platform of WCDB

> iOS, macOS or Android

### The installation of WCDB

> Git clone

### What's the issue?

I want to use WCDB to develop a unified multi-terminal data storage.
I plan to use git clone and cmake to integrate WCDB C++.
If I use this method, can I still enjoy the optimization for iOS and Android platforms?

**Comment by Qiuwen-chen** [comment]
Sure, WCDB C++ share the same core logic with WCDB for other language.
