### ISSUE TITLE
UIApplicationDidReceiveMemoryWarningNotification not found while build for TARGET_OS_MACCATALYST

### ISSUE THREAD

**Issue by enefry** [Tencent/wcdb#1161]
### The language of WCDB

> Objective-C, Swift 

### The version of WCDB

> 2.1.6

### The platform of WCDB

> MACCATALYST

### The installation of WCDB

> Cocoapods, Carthage 

### What's the issue?
<img width="843" alt="image" src="https://github.com/user-attachments/assets/4405dc4d-647d-4a48-ae54-07d329365d41">

Undefined symbols for architecture x86_64:
  "_UIApplicationDidReceiveMemoryWarningNotification", referenced from:
 link fail

**Comment by azureplus** [comment]
WCTOperationQueue
#if TARGET_OS_IPHONE && !TARGET_OS_MACCATALYST && !TARGET_OS_WATCH && !TARGET_OS_TV
