### ISSUE TITLE
windows 如何模拟破坏数据库

### ISSUE THREAD

**Issue by spraysmile** [Tencent/wcdb#1162]
The language of WCDB
c++

The version of WCDB
2.1.6

The platform of WCDB
windows10

The installation of WCDB
git clone

What's the issue?

我想去测试wcdb的数据恢复功能。由于数据库本身具有抗破坏能力，请问如何去模拟破坏数据库呢。

我试过简单的文本打开删除某些字符，这种能检测到破坏，但是无法修复；

**Comment by Qiuwen-chen** [comment]
wcdb can only repair the data that is not damaged.
