### ISSUE TITLE
遇到个死锁问题

### ISSUE THREAD

**Issue by yangfb522** [Tencent/wcdb#1163]
### The language of WCDB
Objective-C

### The version of WCDB
v1.1.0

### The platform of WCDB
iOS

### The installation of WCDB
 Git clone

### What's the issue?
堆栈如下

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: FRONTBOARD 2343432205 
<RBSTerminateContext| domain:10 code:0x8BADF00D explanation:scene-update watchdog transgression: application<>:2943 exhausted real (wall clock) time allowance of 10.00 seconds
ProcessVisibility: Foreground
ProcessState: Running
WatchdogEvent: scene-update
WatchdogVisibility: Background
WatchdogCPUStatistics: (
"Elapsed total CPU time (seconds): 7.110 (user 7.110, system 0.000), 12% CPU",
"Elapsed application CPU time (seconds): 0.020, 0% CPU"
) reportType:CrashLog maxTerminationResistance:Interactive>

Triggered by Thread:  0

Thread 0 name:   Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	       0x1c814887c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1d76d260c _pthread_cond_wait$VARIANT$armv81 + 1220
2   libc++.1.dylib                	       0x19a24a568 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>>) + 96
3   WCDB                          	       0x1148aabfc WCDB::Conditional::wait_for(std::__1::unique_lock<std::__1::mutex>&, double) + 212
4   WCDB                          	       0x1148a2f0c WCDB::BusyRetryConfig::onBusy(WCDB::UnsafeStringView const&, int) + 508
5   WCDB                          	       0x1147e26fc WCDB::HandleNotification::onBusy(void*, int) + 52
6   WCDB                          	       0x1147667c4 sqlite3InvokeBusyHandler + 80
7   WCDB                          	       0x1147bd1f8 sqlite3BtreeBeginTrans + 1136
8   WCDB                          	       0x1147a0ae0 sqlite3VdbeExec + 2888
9   WCDB                          	       0x11474ad04 sqlite3_step + 200
10  WCDB                          	       0x114842728 WCDB::HandleStatement::step() + 36
11  WCDB                          	       0x11483a660 -[WCTInsert realExecute] + 792
12  WCDB                          	       0x11483a30c -[WCTInsert execute] + 140
13  WCDB                          	       0x11485a2c4 -[WCTTable(Convenient) insertOrReplaceObject:] + 104

**Comment by Qiuwen-chen** [comment]
Please upgrade to the latest version, or downgrade wcdb to v1.0.x.
