### ISSUE TITLE
Database encryption problem

### ISSUE THREAD

**Issue by 0x1306a94** [Tencent/wcdb#1164]
### The language of WCDB

> Swift

### The version of WCDB

> 2.1.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

After I set the password via setCipher(key: password), I can read and write data on iOS.
Then I exported the written database file to macOS, and it failed to open using Navicat "Error: file is not a database"
Then I used the sqlite3 -key command to open it, and it also reported an error "Error: file is not a database"

**Comment by Qiuwen-chen** [comment]
wcdb has a set of encryption configurations for encrypted databases. When you use other applications to open this database, you need to set the same configuration to open it.
