### ISSUE TITLE
Open error

### ISSUE THREAD

**Issue by 0x1306a94** [Tencent/wcdb#1165]
### The language of WCDB

> Swift

### The version of WCDB

> 2.1.6

### The platform of WCDB

>  iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

I use WCDBSwift in my project and just open the database file and the error is as follows
```
API call with invalid database connection pointer
misuse at line 142103 of [1b37c146ee]
[*] traceSQL info:  sql: PRAGMA temp_store = 1
API call with invalid database connection pointer
misuse at line 142103 of [1b37c146ee]
[*] traceSQL info:  sql: PRAGMA temp_store = 1
[ERROR] Code:Misuse Source:SQLite,Path:/var/mobile/Containers/Data/Application/EFDC98F5-EE14-44FF-ABC2-19C3F3CFCFCC/Documents/ticketDatabase/6737926/dev-checking.sqlite,Message:bad parameter or other API misuse,SQL:PRAGMA journal_mode 
```
But I created a new, clean project and used the same code and it worked fine.
Then I thought it was because my current project integrated CoreData, so I added the CoreData link option to the new project, and it worked fine after running?
What could be the reason for this problem?

**Comment by 0x1306a94** [comment]
I tried to change the newly created project to CocoaPods integration, and it still ran without problems.
Then I changed the problematic project to SPM integration, and it ran without errors.
At present, it seems that there is a compilation option in the problematic project that caused the problem

**Comment by Qiuwen-chen** [comment]
Can you give me a demo project to reproduce it?

**Comment by 0x1306a94** [comment]
@Qiuwen-chen 
The problem is with the company project. I have tried to create a new project and integrate it with cocoapods, and it works fine. When I get to the company on Monday, I will add the pods that the company project depends on one by one to test whether it can be reproduced.

Found a new problem.
1. Currently I use `WCDB.xcodeproj` to compile into xcframework. Then after dragging xcframework directly into the project, it will prompt that WCDB_Private cannot be found when compiling the file of `import WCDBSwift`. Integration by creating a new spm package will not cause compilation failure

2. When compiling xcframework, I used the `xcodebuild -project` command to compile at first, but the compilation failed. I guess it may be the way `WCDB.xcodeproj` references `zstd.xcodeproj` and `sqlcipher.preprocessed.xcodeproj`. There are differences between command line and gui compilation. I will try to change to the `workspace` method to see if the command line can compile successfully

**Comment by 0x1306a94** [comment]
@Qiuwen-chen 
The following is a reproducible demo.

`TPNS-iOS` and `:linkage => :static` are the key conditions
[WCDBOpenError.zip](https://github.com/user-attachments/files/16653922/WCDBOpenError.zip)

**Comment by Qiuwen-chen** [comment]
> @Qiuwen-chen The following is a reproducible demo.
> 
> `TPNS-iOS` and `:linkage => :static` are the key conditions [WCDBOpenError.zip](https://github.com/user-attachments/files/16653922/WCDBOpenError.zip)

The XGMTACloud.framework in TPNS seems to have some sqlite configuration conflicted with wcdb. You should build wcdb as a dynamic framework.
