### ISSUE TITLE
swift 编译报错

### ISSUE THREAD

**Issue by zhongxing100** [Tencent/wcdb#1166]
<img width="385" alt="截屏2024-08-17 15 50 07" src="https://github.com/user-attachments/assets/13a68afe-71c4-4a89-acc0-413617686b5f">
<img width="1314" alt="截屏2024-08-17 15 52 34" src="https://github.com/user-attachments/assets/352acf32-a804-4961-8f65-343b9e8a3ecd">

Swift 5.0    Xcode 15.0.1.   编译报错,    请问怎么解决 ?    谢谢

**Comment by zhongxing100** [comment]
Swift 5.0     Xcode 15.0.1    wcdb 2.1.6      编译报错，请问怎么解决？ 谢谢

**Comment by Qiuwen-chen** [comment]
The library uploaded to cocoapods has been verified to have no compilation problems. Please check your local code.

**Comment by zhongxing100** [comment]
> 上传到cocoapods的库已经验证没有编译问题，请检查本地代码。

有其他第三方使用了FMDB会是冲突问题引起的吗?

**Comment by Qiuwen-chen** [comment]
It does not seems to be related to FMDB.

**Comment by zhongxing100** [comment]
> It does not seems to be related to FMDB.

问题找到了,  是另外一个第三方库 定义了自己的 LRUCache
且都   #import "LRUCache.hpp"   导致了冲突
WCDB是非常优秀的库, 一些文件能不能加上自己独有的前缀,  避免和其他库有冲突

**Comment by Qiuwen-chen** [comment]
I will consider it later.
