### ISSUE TITLE
Subquery usage

### ISSUE THREAD

**Issue by 0x1306a94** [Tencent/wcdb#1167]
### The language of WCDB

> Swift

### The version of WCDB

> 2.1.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Carthage

### What's the issue?

How to write the following subquery statement through winq?
```sql
SELECT 
	*
FROM
	ticket_detail
WHERE orderId = (SELECT orderId FROM ticket_detail WHERE ticketCode = '24b13227ca93da30')
```

**Comment by Qiuwen-chen** [comment]
Here is the wiki for the complex sql: https://github.com/Tencent/wcdb/wiki/Swift-%e8%af%ad%e8%a8%80%e9%9b%86%e6%88%90%e6%9f%a5%e8%af%a2
