### ISSUE TITLE
winq syntax

### ISSUE THREAD

**Issue by 0x1306a94** [Tencent/wcdb#1168]
### The language of WCDB

> Swift

### The version of WCDB

> 2.1.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Carthage

### What's the issue?

Is it possible to support writing similar to NSCompoundPredicate?
I used the following extension, and the generated sql should be illegal.
I checked the test code of the Swift part in the repository, but couldn't find how to write this.
```swift
extension Collection where Element: ExpressionConvertible {
    func and() -> ExpressionConvertible {
        if self.isEmpty {
            return Expression(nilLiteral: ())
        }
        
        let sql = self.map { $0.asExpression().description }
            .joined(separator: " AND ")
        
        return Expression(stringLiteral: "(\(sql))")
    }
    
    func or() -> ExpressionConvertible {
        if self.isEmpty {
            return Expression(nilLiteral: ())
        }
        
        let sql = self.map { $0.asExpression().description }
            .joined(separator: " OR ")
        
        return Expression(stringLiteral: "(\(sql))")
    }
}

func test() {
    let conditions = [
        Order.Properties.orderId.in(table: "order") == Ticket.Properties.orderId.in(table: "ticket"),
        Ticket.Properties.ticketCode.in(table: "ticket") == "xxxx",
        Ticket.Properties.orderId.in(table: "ticket") == BindParameter(1),
    ]
    
    print("and: \(conditions.and().asExpression().description)")
    // and: '(order.orderId == ticket.orderId AND ticket.ticketCode == ''xxxx'' AND ticket.orderId == ?1)'
    print("or: \(conditions.or().asExpression().description)")
    // or: '(order.orderId == ticket.orderId OR ticket.ticketCode == ''xxxx'' OR ticket.orderId == ?1)'
}
```
For example, some dynamic conditions are very cumbersome to write using the following method
```swift
func test(orderId: String, ticketCode: String?) {
    var condition = Ticket.Properties.orderId == orderId
    if let ticketCode, !ticketCode.isEmpty {
        condition = condition && Ticket.Properties.ticketCode == ticketCode
    }
    
    print("sql: \(condition.description)")
}
```

**Comment by Qiuwen-chen** [comment]
Winq does not support raw string expression

**Comment by 0x1306a94** [comment]
@Qiuwen-chen Can subsequent versions consider supporting NSCompoundPredicate?

**Comment by Qiuwen-chen** [comment]
> @Qiuwen-chen Can subsequent versions consider supporting NSCompoundPredicate?

NO

**Comment by 0x1306a94** [comment]
@Qiuwen-chen 
I mean support for NSCompoundPredicate-like syntax.
For example, you can convert a list into a set of AND or OR
```swift
func test(orderId: String, ticketCode: String?) {
    var condition = Ticket.Properties.orderId == orderId
    var dynamicConditions: [ExpressionConvertible] = []
    if let ticketCode, !ticketCode.isEmpty {
        dynamicConditions.append(Ticket.Properties.ticketCode == ticketCode)
        dynamicConditions.append(Ticket.Properties.telephone == "dddd")
    }
    
    let finalCondition = condition && dynamicConditions.and()
    // sql: (orderId = 'dd' AND (ticketCode = 'xx' AND telephone = 'ddd'))
    
    // let finalCondition = condition && dynamicConditions.or()
    // sql: (orderId = 'dd' AND (ticketCode = 'xx' OR telephone = 'ddd'))
    
    print("sql: \(condition.description)")
}

func testPlaceholder(orderId: String?, ticketCode: String?) {
    var condition = WCDBSwift.Condition.Placeholder // sql:
    if let orderId, let ticketCode {
        condition =  condition && Ticket.Properties.orderId == orderId &&
        Ticket.Properties.ticketCode == ticketCode
        // sql: (orderId = 'xx' AND ticketCode = 'xx')
    }
}
```

**Comment by Qiuwen-chen** [comment]
> @Qiuwen-chen I mean support for NSCompoundPredicate-like syntax. For example, you can convert a list into a set of AND or OR
> 
> ```swift
> func test(orderId: String, ticketCode: String?) {
>     var condition = Ticket.Properties.orderId == orderId
>     var dynamicConditions: [ExpressionConvertible] = []
>     if let ticketCode, !ticketCode.isEmpty {
>         dynamicConditions.append(Ticket.Properties.ticketCode == ticketCode)
>         dynamicConditions.append(Ticket.Properties.telephone == "dddd")
>     }
>     
>     let finalCondition = condition && dynamicConditions.and()
>     // sql: (orderId = 'dd' AND (ticketCode = 'xx' AND telephone = 'ddd'))
>     
>     // let finalCondition = condition && dynamicConditions.or()
>     // sql: (orderId = 'dd' AND (ticketCode = 'xx' OR telephone = 'ddd'))
>     
>     print("sql: \(condition.description)")
> }
> 
> func testPlaceholder(orderId: String?, ticketCode: String?) {
>     var condition = WCDBSwift.Condition.Placeholder // sql:
>     if let orderId, let ticketCode {
>         condition =  condition && Ticket.Properties.orderId == orderId &&
>         Ticket.Properties.ticketCode == ticketCode
>         // sql: (orderId = 'xx' AND ticketCode = 'xx')
>     }
> }
> ```

It seems that you can do it outside of wcdb

**Comment by 0x1306a94** [comment]
@Qiuwen-chen 
It just doesn't work?
That's why it needs support in wcdb!
Although this can be achieved through the following extension, `Expression(nilLiteral: ())` will output `NULL` and `Expression(stringLiteral: "")` will output `''`
```swift
extension Collection where Element: ExpressionConvertible {
    func and() -> ExpressionConvertible {
        if self.isEmpty {
            return Expression(nilLiteral: ())
        }
        
        let finalExpression = self.reduce(Expression(nilLiteral: ())) { $0 && $ 1 }        
        return finalExpression
    }
    
    func or() -> ExpressionConvertible {
        if self.isEmpty {
            return Expression(nilLiteral: ())
        }
        
        let finalExpression = self.reduce(Expression(nilLiteral: ())) { $0 || $ 1 }        
        return finalExpression
    }
}
```

**Comment by Qiuwen-chen** [comment]
You need a empty expression, may be you can try Expression(booleanLiteral: true)

**Comment by 0x1306a94** [comment]
@Qiuwen-chen 
* This can be achieved by the following expansion, but it will produce a lot of nested brackets
* It would be better if wcdb itself could support this
* In addition, I saw that the latest version 2.1.7 has support for the OHOS platform. Does it mean that version 2.1.7 is fully usable on the OHOS platform?
```swift
extension Collection where Element: ExpressionConvertible {
    func and() -> ExpressionConvertible? {
        guard let first = self.first else { return nil }
        guard count > 1 else { return first }

        let remainder = dropFirst()
        let finalExpression = remainder.reduce(first.asExpression()) { $0 && $1 }
        return finalExpression
    }

    func or() -> ExpressionConvertible? {
        guard let first = self.first else { return nil }
        guard count > 1 else { return first }

        let remainder = dropFirst()
        let finalExpression = remainder.reduce(first.asExpression()) { $0 || $1 }

        return finalExpression
    }
}
```

**Comment by Qiuwen-chen** [comment]
Yes, WCDB C++ can be fully used on the OHOS platform.
NSCompoundPredicate-like syntax is not a normal sql expression, I don't want to support this officially.
