### ISSUE TITLE
请问C++字段数值加 1 的更新如何实现

### ISSUE THREAD

**Issue by Hin-D** [Tencent/wcdb#1169]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

请问如何用 ORM 方法实现update 方法的数值加 1，类似这样
UPDATE table_name SET column_name = column_name + 1 WHERE [condition];

insertOrReplaceObjects时可以实现吗？

**Comment by Qiuwen-chen** [comment]
database.execute(WCDB::StatementUpdate().update(column_name).to(column_name + 1)...)
