### ISSUE TITLE
想咨询一下WCDB2.0以上OC版本是否职场复杂一点的多表联查功能

### ISSUE THREAD

**Issue by superyang2019** [Tencent/wcdb#1170]
### The language of WCDB

Objective-C

### The version of WCDB

2.1.6

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.

![1724376089802](https://github.com/user-attachments/assets/65201d33-fc74-4a6b-819d-70d580866de0)
![1724376280671](https://github.com/user-attachments/assets/c283aa62-b8e2-4924-b302-08f3474a9df3)

> Explain what you want by example or code **in English**.

我们目前正在从WCDB1.1.0升级到WCDB2.1.6，但是在老版本有一些特殊的语法WCDB::JoinClause他支持join操作，原业务确实用了left join这种左连接，而目前wcdb2.0以上的版本我们评估看支持内连接，没办法支持左连接或右连接，想问一下，是否有其他办法支持左连接多表查询，谢谢。

**Comment by Qiuwen-chen** [comment]
You can use WCDB::Join
