### ISSUE TITLE
Xcode16 新项目通过SPM安装，编译错误 'config.h' file not found

### ISSUE THREAD

**Issue by mrsunx** [Tencent/wcdb#1171]
### The language of WCDB

> Swift

### The version of WCDB

> v2.1.7

### The platform of WCDB

> iOS

### The installation of WCDB

> SPM

### What's the issue?

![WX20240825-153627@2x](https://github.com/user-attachments/assets/4aba80b0-e77f-4b47-a4a5-57f12df830fa)

**Comment by Qiuwen-chen** [comment]
Your can try to redownload WCDB.

**Comment by Qiuwen-chen** [comment]
> @Qiuwen-chen Xcode16 SPM 不再支持含有递归的 headerSearchPath, 比如 `.headerSearchPath("../../**")`,修复方法是一条条展开 headerSearchPath. 详情可参考[Parse Fix](https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1795)

get

**Comment by L1cardo** [comment]
所以什么时候可以修复一下？
谢谢

**Comment by NoahNyy** [comment]
等修复的+1，升级了一下结果跑不了项目了，或者有什么临时解决方案？

**Comment by mrsunx** [comment]
> 等修复的+1，升级了一下结果跑不了项目了，或者有什么临时解决方案？

master分支修复了

**Comment by Qiuwen-chen** [comment]
Fixed in the latest version.
