### ISSUE TITLE
2.1.7新版本报严重错误

### ISSUE THREAD

**Issue by CoderHJZhao** [Tencent/wcdb#1172]
<img width="537" alt="image" src="https://github.com/user-attachments/assets/72a18413-456d-4b41-9ae4-26b101f3dc60">
更新新版本后，不管是用swiftmanager还是pod还是carthage都会报错，换成[GRDB.swift](https://github.com/groue/GRDB.swift)正常，而且pod指定老版本无法回退，始终更新的是2.1.7最新版，还望尽快解决，感谢！

```[tasklist]
### Tasks
```

**Comment by CoderHJZhao** [comment]
XCODE版本15.1，手动集成退回到2.1.2后正常

**Comment by Qiuwen-chen** [comment]
please upgrade your xcode
