### ISSUE TITLE
内存优化

### ISSUE THREAD

**Issue by 2016-ios** [Tencent/wcdb#1173]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

swift

### The version of WCDB

> e.g. v1.0.5

2.1.7

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

WCDB.swift和WCDBOptimizedSQLCipher库包体占用过大，有优化的空间嘛？

**Comment by Qiuwen-chen** [comment]
may be your can try static framework
