### ISSUE TITLE
struct 可以继承 TableCodable 吗？

### ISSUE THREAD

**Issue by zxqqingchuan** [Tencent/wcdb#1175]
`
struct Message: Codable {

public var convID: String
    
public var uid: UInt64

}

extension Message: TableCodable {
    
    public enum CodingKeys: String, CodingTableKey {

        public typealias Root = Message
        public static let objectRelationalMapping = TableBinding(CodingKeys.self) {
            BindMultiPrimary(Properties.convID, Properties.uid)
        }
        case convID
        case uid

    }
    
}
`

**Comment by zxqqingchuan** [comment]
我现在遇到一个问题新增了一个字段：localID，但是 createTable 后表里没有这个字段。
struct Message: Codable {

public var convID: String

public var uid: UInt64

public var localID: UInt64

}

extension Message: TableCodable {

public enum CodingKeys: String, CodingTableKey {

    public typealias Root = Message
    public static let objectRelationalMapping = TableBinding(CodingKeys.self) {
        BindMultiPrimary(Properties.convID, Properties.uid)
    }
    case convID
    case uid
   case localID

}
}

**Comment by Qiuwen-chen** [comment]
You can give us a demo project to reproduct it
