### ISSUE TITLE
同时插入2条数据

### ISSUE THREAD

**Issue by 597579501** [Tencent/wcdb#1176]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
swift

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android
iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

let imageTable = DBMediaImageTable()
imageTable.fileId = fileId
imageTable.imageData = imageData
imageTable.imageWidth = imageWidth
imageTable.imageHeight = imageHeight

let message = DBMessageTable()
message.userId = userId
message.msgType = MsgType.image.rawValue
message.isSender = true
message.date = currDate
message.fileId = fileId

DBManager.share.inser(objects: [imageTable], intoTable: .mediaImageTable)
DBManager.share.inser(objects: [message], intoTable: .messageTable)

我用  DBMessageTable 的fileID 跟  DBMessageTable fileID 关联。
是否有类似事务操作可以保证2个一起成功才算

**Comment by Qiuwen-chen** [comment]
You can use transaction:

DBManager.share.run { handle in
    DBManager.share.inser(objects: [imageTable], intoTable: .mediaImageTable)
    DBManager.share.inser(objects: [message], intoTable: .messageTable)
}
