### ISSUE TITLE
请问下如何调用一些内置函数？比如 如何拼接 AND CAST(json_extract(jsonString, '$.subType') AS INTEGER) = 9  这个WINQ?

### ISSUE THREAD

**Issue by CharType** [Tencent/wcdb#1177]
### The language of WCDB
Objective-C

### The version of WCDB
v2.1.7

### The platform of WCDB
 iOS

### The installation of WCDB
Cocoapods, 

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
The "json_extract" is not supported yet.
