### ISSUE TITLE
微信是中国的 为什么文档还是英文

### ISSUE THREAD

**Issue by gb18030** [Tencent/wcdb#118]
我想用wcdb的原因 就是感觉这个文档应该是中文 结果还是英文的

**Comment by lingol** [comment]
https://github.com/Tencent/wcdb/wiki

**Comment by EvilGoose** [comment]
coding no national boundary

**Comment by jackytianhappy** [comment]
The best thing should be shared in the world

**Comment by gb18030** [comment]
@lingol 我说的是API文档全是英文的

**Comment by gb18030** [comment]
@jackytianhappy 你看看Issues有几个是用英文提问的  刚出来俩月 也就咱中国人用
