### ISSUE TITLE
[咨询贴] 请问根目录下的deprecated文件夹是干嘛的，为什么把原来Android相关代码迁移进来了

### ISSUE THREAD

**Issue by ggzmdc** [Tencent/wcdb#1181]
![image](https://github.com/user-attachments/assets/b510820d-7e7e-4258-b2ff-aaa1e00c9bc1)

**Comment by sooglejay** [comment]
借楼咨询一个问题：WCDB2.0对数据迁移（从一个数据库迁移到另外一个数据库），有提供实现么？

**Comment by Qiuwen-chen** [comment]
I re-implemented WCDB for Java/Kotlin since version 2.1. The code is completely different from WCDB for Android in version 1.x, so the previous code is deprecated.
