### ISSUE TITLE
【咨询贴】WCDB1.0升级到2.0，有哪些注意事项

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1182]
1. 从WCDB1.0升级到2.0，有哪些注意事项、有哪些测试case可供参考、是否存在版本向下兼容问题

2. WCDB2.0对数据迁移的性能有优化么（将数据从数据库A迁移到数据库B），关于数据迁移有提供功能接口么？

3. 微信Android消息数据库现在是多数据库方案么？

4. 多数据库下使用WCDB2.0 有什么注意事项呢，尤其是从一个旧数据库将数据迁移到多个数据库的场景

**Comment by Qiuwen-chen** [comment]
You have too many questions. You can try to use it first. There shouldn't be any unsolvable problems.
Here is the wiki of database migration: https://github.com/Tencent/wcdb/wiki/Java%7CKotlin-%E6%95%B0%E6%8D%AE%E8%BF%81%E7%A7%BB.
