### ISSUE TITLE
Disable WAL

### ISSUE THREAD

**Issue by 0x1306a94** [Tencent/wcdb#1184]
### The language of WCDB

> C++

### The version of WCDB

> v2.1.7

### The platform of WCDB

> macOS

### The installation of WCDB

> cmake submodule

### What's the issue?

* By default, WAL mode is enabled in BasicConfig, and now I want to turn off WAL default and restore it to default. So I use the following code
```c++
std::shared_ptr<WCDB::Database> m_db = std::make_shared<WCDB::Database>(*file);
m_db->setConfig(
    "closeWal", [](WCDB::Handle &handle) -> bool {
        auto journalMode = WCDB::StatementPragma()
                               .pragma(WCDB::Pragma::journalMode())
                               .to("DELETE");

        auto fullfSync = WCDB::StatementPragma()
                             .pragma(WCDB::Pragma::checkpointFullfsync())
                             .to(false);

        auto tempStore = WCDB::StatementPragma()
                             .pragma(WCDB::Pragma::tempStore())
                             .to(0);
        bool res = true;
        res &= handle.execute(journalMode);
        res &= handle.execute(fullfSync);
        res &= handle.execute(tempStore);
        return res;
    },
    nullptr, WCDB::Database::Priority::Low);
    
m_db->traceSQL([](long tag, const WCDB::UnsafeStringView &path, const void *handleIdentifier, const WCDB::UnsafeStringView &sql, const WCDB::UnsafeStringView &info) {
    std::cout << "path: " << path << "\n"
              << "info: " << info.data() << "\n"
              << "sql: " << sql.data() << "\n";
});

m_db->traceError([](const WCDB::Error &error) {
    std::cerr << "error: " << error.getDescription().data() << std::endl;
});
```
* The execution output information is as follows
```
path: /Users/king/Desktop/WCDBSample/test.sqlite
info: 
sql: PRAGMA journal_mode
path: /Users/king/Desktop/WCDBSample/test.sqlite
info: 
sql: PRAGMA checkpoint_fullfsync = TRUE
path: /Users/king/Desktop/WCDBSample/test.sqlite
info: 
sql: PRAGMA temp_store = 1
path: /Users/king/Desktop/WCDBSample/test.sqlite
info: 
sql: PRAGMA journal_mode = 'DELETE'
error: [ERROR: 10, disk I/O error], ExtCode:3850, Path:/Users/king/Desktop/WCDBSample/test.sqlite, SQL:PRAGMA journal_mode = 'DELETE', Source:SQLite, SystemErrMsg:Bad file descriptor, SystemErrno:9
path: /Users/king/Desktop/WCDBSample/test.sqlite
info: 
sql: PRAGMA checkpoint_fullfsync = FALSE
path: /Users/king/Desktop/WCDBSample/test.sqlite
info: 
sql: PRAGMA temp_store = 0
```

**Comment by Qiuwen-chen** [comment]
You can remove the flag SQLITE_OPEN_MAINDB_READONLY in the code of WCDB and try again.

**Comment by 0x1306a94** [comment]
@Qiuwen-chen 
After commenting out `SQLITE_OPEN_MAINDB_READONLY` in `AbstractHandle::open`, the execution does not report an error. But there is still a problem
* First, use `Navicat` to execute the following SQL to close WAL in a database file that has WAL enabled. After the statement is executed, the WAL file will be deleted immediately. Then use wcdb to open it and use the default configuration to execute canOpen. Then wait a while and call close to close the database. However, WAL-related files are not generated. Then create and call canOpen again, and WAL-related files are generated
```sql
PRAGMA journal_mode = 'DELETE'
PRAGMA checkpoint_fullfsync = FALSE
PRAGMA temp_store = 0
```
* After removing the `SQLITE_OPEN_MAINDB_READONLY` flag, the closeWal configuration in the previous code is used to close WAL. The execution is successful, but after the execution is successful, the WAL-related files are not automatically deleted like `Navicat`.
* At the same time,`setConfig` will retain the configuration. Specifically, I added an option to enable `WAL` on the interface. When the option is not checked, I configured the code to turn off `WAL` through setConfig, as shown in the previous code. Then I closed the database, and through the close callback, I can observe that the database is indeed closed. Then I checked the `WAL` option again. At this time, I will not set the custom configuration through`setConfig`, but after running, the `closeWal` configured last time is still executed.

**Comment by Qiuwen-chen** [comment]
> @Qiuwen-chen After commenting out `SQLITE_OPEN_MAINDB_READONLY` in `AbstractHandle::open`, the execution does not report an error. But there is still a problem
> 
> * First, use `Navicat` to execute the following SQL to close WAL in a database file that has WAL enabled. After the statement is executed, the WAL file will be deleted immediately. Then use wcdb to open it and use the default configuration to execute canOpen. Then wait a while and call close to close the database. However, WAL-related files are not generated. Then create and call canOpen again, and WAL-related files are generated
> 
> ```sql
> PRAGMA journal_mode = 'DELETE'
> PRAGMA checkpoint_fullfsync = FALSE
> PRAGMA temp_store = 0
> ```
> 
> * After removing the `SQLITE_OPEN_MAINDB_READONLY` flag, the closeWal configuration in the previous code is used to close WAL. The execution is successful, but after the execution is successful, the WAL-related files are not automatically deleted like `Navicat`.
> * At the same time,`setConfig` will retain the configuration. Specifically, I added an option to enable `WAL` on the interface. When the option is not checked, I configured the code to turn off `WAL` through setConfig, as shown in the previous code. Then I closed the database, and through the close callback, I can observe that the database is indeed closed. Then I checked the `WAL` option again. At this time, I will not set the custom configuration through`setConfig`, but after running, the `closeWal` configured last time is still executed.

I can not get your point.

**Comment by Qiuwen-chen** [comment]
I still can not get your point.
The logic in setConfig does not take effect immediately. It will only take effect after you perform some read and write operations on the database.

**Comment by 0x1306a94** [comment]
@Qiuwen-chen 
* I intentionally executed `insertObject` after `createTable`
* From `traceSQL`, we can observe that `custom.close.wal` is executed after the default configuration is executed, but before `createTable` and `insertObject`.

https://github.com/user-attachments/assets/a454d594-f414-462a-ad38-be9e4b21ebaa

**Comment by Qiuwen-chen** [comment]
OK, the custom config needs to be removed. It will not be disabled by closing the database.
