### ISSUE TITLE
After upgrading WCDB (v1.0.6 to v2.0.1), watchdog problems +30%

### ISSUE THREAD

**Issue by oqsh** [Tencent/wcdb#1185]
### The language of WCDB

Objective-C

### The version of WCDB

v1.0.6 to v2.0.1

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

After upgrading WCDB (v1.0.6 to v2.0.1), watchdog problems +30%.

Most probrlems stack have sqlite3BtreeBeginTrans, can you give any advice? 🙏🏻

One probrlem stack for example:

Thread 0 name: com.apple.main-threadthread_cpu_usage：28.5run_state：runningflags：swapped outpriority:45
0 libsystem_kernel.dylib___fcntl (in libsystem_kernel.dylib) +8
1 libsystem_kernel.dylib_fcntl (in libsystem_kernel.dylib) +80
2 XYMUSIC unixShmSystemLock (in XYMUSIC) os_unix.c:4427
3 XYMUSIC unixShmLock (in XYMUSIC) os_unix.c:4981
4 XYMUSIC walTryBeginRead (in XYMUSIC) wal.c:2698
5 XYMUSIC sqlite3WalBeginReadTransaction (in XYMUSIC) wal.c:2929
6 XYMUSIC pagerBeginReadTransaction (in XYMUSIC) [inlined] pager.c:3267
7 XYMUSIC sqlite3PagerSharedLock (in XYMUSIC) pager.c:5364
8 XYMUSIC lockBtree (in XYMUSIC) [inlined] btree.c:3016
9 XYMUSIC sqlite3BtreeBeginTrans (in XYMUSIC) btree.c:3391
10 XYMUSIC sqlite3VdbeExec (in XYMUSIC) vdbe.c:3267
11 XYMUSIC sqlite3Step (in XYMUSIC) [inlined] vdbeapi.c:630
12 XYMUSIC sqlite3_step (in XYMUSIC) vdbeapi.c:696
13 XYMUSIC XYWCDB::HandleStatement::step() (in XYMUSIC) HandleStatement.cpp:366
14 XYMUSIC XYWCDB::AbstractHandle::executeSQL(XYWCDB::UnsafeStringView const&) (in XYMUSIC) AbstractHandle.cpp:138
15 XYMUSIC XYWCDB::AbstractHandle::executeStatement(XYWCDB::Statement const&) (in XYMUSIC) AbstractHandle.cpp:146
16 XYMUSIC XYWCDB::AbstractHandle::beginTransaction() (in XYMUSIC) AbstractHandle.cpp:484
17 XYMUSIC XYWCDB::InnerHandle::beginTransaction() (in XYMUSIC) InnerHandle.cpp:338
18 XYMUSIC XYWCDB::InnerHandle::runTransaction(std::__1::function<bool (XYWCDB::InnerHandle*)> const&) (in XYMUSIC) InnerHandle.cpp:404
19 XYMUSIC XYWCDB::BaseBinding::createTable(XYWCDB::UnsafeStringView const&, XYWCDB::InnerHandle*) const (in XYMUSIC) BaseBinding.cpp:59
20 XYMUSIC -[XYWCTHandle(Table) remapTable:toClass:] (in XYMUSIC) XYWCTHandle+Table.mm:95
21 XYMUSIC -[XYWCTDatabase(Table) createTable:withClass:] (in XYMUSIC) XYWCTDatabase+Table.mm:46
22 libdispatch.dylib__dispatch_call_block_and_release (in libdispatch.dylib) +20
23 UIKitCore_UIApplicationMain (in UIKitCore) +332
24 XSFMmain (in XYMUSIC) main.m:50
25 dyldstart (in dyld) +440

**Comment by Qiuwen-chen** [comment]
You should give me more detail and I recommend you to upgrade to the latest version.
