### ISSUE TITLE
v1.0.6升级到v2.0.1，WCDB在”多线程往数据库进行写操作”的场景下会有什么变化吗？（直接返回错误变成忙等待之类的）

### ISSUE THREAD

**Issue by oqsh** [Tencent/wcdb#1186]
The language of WCDB
Objective-C

The version of WCDB
v1.0.6 to v2.0.1

The platform of WCDB
iOS

The installation of WCDB
Cocoapods

What's the issue?
您好，我从v1.0.6升级到v2.0.1后，卡死问题大幅上涨（+30%），发现卡死问题都是主线程在写数据库、然后子线程同时也在写入或删除数据，然后就导致主线程卡死了。

所以想确定下WCDB 2.0版本相较于1.0版本，在多线程操作数据库这块有做什么改动吗？比如说在多个线程同时对一个数据库进行写操作的场景下，在持有写锁的线程的写操作完成之前，1.0版本其余线程的写操作都会直接收到数据库忙碌的错误，但是2.0版本的其他线程就会一直等待写锁释放？

一个线上问题堆栈举例：
Thread 0 name: com.apple.main-threadthread_cpu_usage：85.1 run_state：running priority:46
0libsystem_kernel.dylib___psynch_mutexwait (in libsystem_kernel.dylib) +8
1libsystem_pthread.dylib__pthread_mutex_firstfit_lock_wait (in libsystem_pthread.dylib) +80
2libsystem_pthread.dylib__pthread_mutex_firstfit_lock_slow (in libsystem_pthread.dylib) +244
3 XYMUSIC unixShmLock (in  XYMUSIC ) os_unix.c:5023
4 XYMUSIC walTryBeginRead (in  XYMUSIC ) wal.c:2812
5 XYMUSIC sqlite3WalBeginReadTransaction (in  XYMUSIC ) wal.c:2929
6 XYMUSIC pagerBeginReadTransaction (in  XYMUSIC ) [inlined] pager.c:3267
7 XYMUSIC sqlite3PagerSharedLock (in  XYMUSIC ) pager.c:5364
8 XYMUSIC sqlite3BtreeBeginTrans (in  XYMUSIC ) btree.c:3410
9 XYMUSIC sqlite3VdbeExec (in  XYMUSIC ) vdbe.c:3267
10 XYMUSIC sqlite3Step (in  XYMUSIC ) [inlined] vdbeapi.c:630
11 XYMUSIC sqlite3_step (in  XYMUSIC ) vdbeapi.c:696
12 XYMUSIC SSWCDB::HandleStatement::step() (in  XYMUSIC ) HandleStatement.cpp:366
13 XYMUSIC -[WCTInsert realExecute] (in  XYMUSIC ) WCTInsert.mm:164
14 XYMUSIC -[WCTInsert execute] (in  XYMUSIC ) WCTInsert.mm:94
15 XYMUSIC -[WCTTable(Convenient) insertOrReplaceObjects:] (in  XYMUSIC ) WCTTable+Convenient.mm:321
16 XYMUSIC -[XYDBTable insertOrReplaceObjects:] (in  XYMUSIC ) XYDBTable.mm:65
17 XYMUSIC __57-[XYHistoryManager addHistoryDatasRemote:table:callback:]_block_invoke_2 (in  XYMUSIC ) XYHistoryManager.mm:608
18 XYMUSIC __61-[XYHistoryManager uploadHistoryProgress:isLogin:completion:]_block_invoke.692 (in  XYMUSIC ) XYHistoryManager.mm:2499
19 XYMUSIC __46-[XYRpcClient executeMethod:param:completion:]_block_invoke (in  XYMUSIC ) XYRpcClient.m:106
20 libdispatch.dylib __dispatch_call_block_and_release (in  libdispatch.dylib ) +28
21 libdispatch.dylib __dispatch_client_callout (in  libdispatch.dylib ) +16
22 libdispatch.dylib __dispatch_main_queue_drain (in  libdispatch.dylib ) +984
23 libdispatch.dylib __dispatch_main_queue_callback_4CF (in  libdispatch.dylib ) +40
24 CoreFoundation ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ (in CoreFoundation) +12
25 CoreFoundation ___CFRunLoopRun (in CoreFoundation) +1992
26 CoreFoundation _CFRunLoopRunSpecific (in CoreFoundation) +604
27 GraphicsServices _GSEventRunModal (in GraphicsServices) +160
28 UIKitCore -[UIApplication _run] (in UIKitCore) +884
29 UIKitCore _UIApplicationMain (in UIKitCore) +336
30 XYMUSIC main (in  XYMUSIC ) main.m:50
31 dyldstart (in dyld) +2352

Thread 7 name: XYHistoryManager.localthread_cpu_usage：74.7 run_state：running priority:37
0libsystem_kernel.dylib___psynch_mutexwait (in libsystem_kernel.dylib) +8
1libsystem_pthread.dylib__pthread_mutex_firstfit_lock_wait (in libsystem_pthread.dylib) +80
2libsystem_pthread.dylib__pthread_mutex_firstfit_lock_slow (in libsystem_pthread.dylib) +244
3 XYMUSIC unixShmLock (in  XYMUSIC ) os_unix.c:4935
4 XYMUSIC sqlite3WalBeginWriteTransaction (in  XYMUSIC ) wal.c:3174
5 XYMUSIC sqlite3PagerBegin (in  XYMUSIC ) pager.c:5852
6 XYMUSIC sqlite3BtreeBeginTrans (in  XYMUSIC ) btree.c:3397
7 XYMUSIC sqlite3VdbeExec (in  XYMUSIC ) vdbe.c:3267
8 XYMUSIC sqlite3Step (in  XYMUSIC ) [inlined] vdbeapi.c:630
9 XYMUSIC sqlite3_step (in  XYMUSIC ) vdbeapi.c:696
10 XYMUSIC SSWCDB::HandleStatement::step() (in  XYMUSIC ) HandleStatement.cpp:366
11 XYMUSIC -[WCTInsert realExecute] (in  XYMUSIC ) WCTInsert.mm:164
12 XYMUSIC -[WCTInsert execute] (in  XYMUSIC ) WCTInsert.mm:94
13 XYMUSIC -[WCTTable(Convenient) insertOrReplaceObject:] (in  XYMUSIC ) WCTTable+Convenient.mm:316
14 XYMUSIC -[XYDBTable insertOrReplaceObject:] (in  XYMUSIC ) XYDBTable.mm:55
15 XYMUSIC __55-[XYHistoryManager addHistoryDataLocal:table:callback:]_block_invoke (in  XYMUSIC ) XYHistoryManager.mm:549
16 libdispatch.dylib __dispatch_call_block_and_release (in  libdispatch.dylib ) +28
17 libdispatch.dylib __dispatch_client_callout (in  libdispatch.dylib ) +16
18 libdispatch.dylib __dispatch_lane_serial_drain (in  libdispatch.dylib ) +744
19 libdispatch.dylib __dispatch_lane_invoke (in  libdispatch.dylib ) +376
20 libdispatch.dylib __dispatch_root_queue_drain_deferred_wlh (in  libdispatch.dylib ) +284
21 libdispatch.dylib __dispatch_workloop_worker_thread (in  libdispatch.dylib ) +400
22 libsystem_pthread.dylib __pthread_wqthread (in libsystem_pthread.dylib) +284
23 libsystem_pthread.dylib _start_wqthread (in libsystem_pthread.dylib) +4

Thread 8 name: XYHistoryManager.dbioqueuethread_cpu_usage：10.2 run_state：uninterruptible priority:46
0libsystem_kernel.dylib_pread (in libsystem_kernel.dylib) +8
1 XYMUSIC seekAndRead (in  XYMUSIC ) os_unix.c:3397
2 XYMUSIC unixRead (in  XYMUSIC ) os_unix.c:3473
3 XYMUSIC readDbPage (in  XYMUSIC ) pager.c:3047
4 XYMUSIC getPageNormal (in  XYMUSIC ) pager.c:5536
5 XYMUSIC getAndInitPage (in  XYMUSIC ) btree.c:2125
6 XYMUSIC moveToLeftmost (in  XYMUSIC ) btree.c:5174
7 XYMUSIC sqlite3VdbeExec (in  XYMUSIC ) vdbe.c:5267
8 XYMUSIC sqlite3Step (in  XYMUSIC ) [inlined] vdbeapi.c:630
9 XYMUSIC sqlite3_step (in  XYMUSIC ) vdbeapi.c:696
10 XYMUSIC SSWCDB::HandleStatement::step() (in  XYMUSIC ) HandleStatement.cpp:366
11 XYMUSIC SSWCDB::InnerHandle::step() (in  XYMUSIC ) [inlined] InnerHandle.cpp:210
12 XYMUSIC SSWCDB::InnerHandle::execute(SSWCDB::Statement const&) (in  XYMUSIC ) InnerHandle.cpp:166
13 XYMUSIC -[WCTDelete execute] (in  XYMUSIC ) WCTDelete.mm:73
14 XYMUSIC -[WCTTable(Convenient) deleteObjectsWhere:] (in  XYMUSIC ) WCTTable+Convenient.mm:618
15 XYMUSIC __53-[XYHistoryManager getHistoryDatasWithType:callback:]_block_invoke_3 (in  XYMUSIC ) XYHistoryManager.mm:1081
16 libdispatch.dylib __dispatch_call_block_and_release (in  libdispatch.dylib ) +28
17 libdispatch.dylib __dispatch_client_callout (in  libdispatch.dylib ) +16
18 libdispatch.dylib __dispatch_lane_serial_drain (in  libdispatch.dylib ) +744
19 libdispatch.dylib __dispatch_lane_invoke (in  libdispatch.dylib ) +376
20 libdispatch.dylib __dispatch_root_queue_drain_deferred_wlh (in  libdispatch.dylib ) +284
21 libdispatch.dylib __dispatch_workloop_worker_thread (in  libdispatch.dylib ) +400
22 libsystem_pthread.dylib __pthread_wqthread (in libsystem_pthread.dylib) +284
23 libsystem_pthread.dylib _start_wqthread (in libsystem_pthread.dylib) +4

**Comment by superyang2019** [comment]
我们之前在1.0.8版本之前，也很少遇到数据库卡死的现象，在2.0没出来前，我升级到1.1，然后随着业务的升级，查询数据库读写越来越多，现在线上也有一些用户出现卡死的线程，这个os_unix.c:文件中有很多场景使用搜，虽然业务上层支持并发查询，但是如果过多的线程去查询，持有线程的锁的线程得不到系统的调度，越来越的多的读写，很容易导致卡死现象，不知道官方使用注意事项。

**Comment by Qiuwen-chen** [comment]
v1.1 is bugly, please try the latest version. And I'm not familiar with v1.0.6, so I don't know the difference of it.
