### ISSUE TITLE
[Android upgrade to 2.0] we have lots of sql statements since using wcdb 1.0.8, can wcdb2.0 execute pure sql statements? so that we can upgrade to 2.0 fast

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1188]

**Comment by Qiuwen-chen** [comment]
Check this: https://ilogs.woa.com/page/search?_qid=9dTHwQpJGHyNnAuPtqwcpa6hREFhL9KUY2VmMe84SDVS

**Comment by Qiuwen-chen** [comment]
Check this: https://github.com/Tencent/wcdb/wiki/Java%7CKotlin-%e5%ae%89%e8%a3%85%e4%b8%8e%e5%85%bc%e5%ae%b9%e6%80%a7#%E8%BF%81%E7%A7%BB%E5%88%B0-wcdb-%E6%96%B0%E7%89%88%E6%9C%AC

**Comment by sooglejay** [comment]
I checked the module named ":compat", WCDB 1.0 has class SQLiteOpenHelper、SQLiteException , which   not found  in WCDB 2.0,  neither as functions or parameters like setWriteAheadLoggingEnabled、isReadOnly、OPEN_READONLY、in SQLiteOpenHelper that is gone when I searched wcdb2.0

**Comment by sooglejay** [comment]
static {
        // Ensure libwcdb.so is loaded.
        SQLiteGlobal.loadLib();
    }

WCDB 2.0 Android developer no need to manually load the libwcdb.so， right？

**Comment by Qiuwen-chen** [comment]
> ```
> static {
>     // Ensure libwcdb.so is loaded.
>     SQLiteGlobal.loadLib();
> }
> ```
> 
> WCDB 2.0 Android developer no need to manually load the libwcdb.so， right？

yes
