### ISSUE TITLE
mmicu分词器MATCH内部使用AND好像不起作用

### ISSUE THREAD

**Issue by hanqi-bupt** [Tencent/wcdb#119]
使用mmicu创建了一个索引表，然后在某一个字段插入了"hello world你好"
- MATCH 'hello AND world AND 好' 匹配不到
- MATCH 'hello AND world' 匹配不到
- MATCH '*hello* AND *world* AND *好* ' 匹配不到
- MATCH 'hello world 好' 能匹配得到

**Comment by John-He-928** [comment]
并非分词器问题，是编译SQLCipher的时候没加上`SQLITE_ENABLE_FTS3_PARENTHESIS`选项，导致`AND`、`OR`、`NOT`等关键字没有启用，dev分支已修正
