### ISSUE TITLE
as for modification/add/remove for fields in db table, WCDB 2.0 let android developer no need to handle db-upgrade-version-logic right? since onUpgrade is gone as well as SQLiteOpenHelper

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1191]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
https://github.com/Tencent/wcdb/wiki/Java%7CKotlin-%e6%a8%a1%e5%9e%8b%e7%bb%91%e5%ae%9a#%E6%95%B0%E6%8D%AE%E5%BA%93%E5%8D%87%E7%BA%A7
