### ISSUE TITLE
Replacement for SQLiteTrace in WCDB 2.0

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1193]
Hi, I'm working with WCDB 2.0 and I noticed that the SQLiteTrace class is no longer present. Do you know what has replaced SQLiteTrace in WCDB 2.0 for tracing or monitoring SQLite operations?

**Comment by Qiuwen-chen** [comment]
You need to read all the wikis first.

**Comment by Qiuwen-chen** [comment]
https://github.com/Tencent/wcdb/wiki/Java%7CKotlin-%e7%9b%91%e6%8e%a7%e4%b8%8e%e9%94%99%e8%af%af%e5%a4%84%e7%90%86
