### ISSUE TITLE
setMaxSqlCacheSize replacement in WCDB2.0

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1195]

**Comment by sooglejay** [comment]
mDB.getValueFromSQL("PRAGMA page_size").getLong();

 mDB.execute("PRAGMA page_size = " + numBytes);

**Comment by Qiuwen-chen** [comment]
https://github.com/Tencent/wcdb/wiki/Java%7CKotlin-%e8%af%ad%e8%a8%80%e9%9b%86%e6%88%90%e6%9f%a5%e8%af%a2
