### ISSUE TITLE
unknown tokenizer: mmicu 

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1196]
wcdb2.0 android
SQL: CREATE VIRTUAL TABLE IF NOT EXISTS fts_msg_index_table_new USING fts4(tokenize=mmicu,search_content);

**Comment by Qiuwen-chen** [comment]
Use BuiltinTokenizer.MMICU https://github.com/Tencent/wcdb/wiki/Java%7CKotlin-%e5%85%a8%e6%96%87%e6%90%9c%e7%b4%a2

**Comment by sooglejay** [comment]
how to set tokenize in sql ?  my sql like below: 

`CREATE VIRTUAL TABLE IF NOT EXISTS fts_contact_index_table USING fts4(tokenize=simple)`

**Comment by sooglejay** [comment]
when I use tokenizer=wcdb_verbatim like: `CREATE VIRTUAL TABLE IF NOT EXISTS fts_contact_index_table USING fts5(tokenize='wcdb_verbatim')`

I got exception like:
 com.tencent.wcdb.base.WCDBNormalException: Code: 1; Message: no such tokenizer: wcdb_verbatim;

**Comment by sooglejay** [comment]
I’m encountering a lot of error messages in logcat with Code: 1; Message: unknown tokenizer: mmicu. What could be causing this issue, and how can I resolve it?
