### ISSUE TITLE
Feature: WCDB for Win32

### ISSUE THREAD

**Issue by skyline75489** [Tencent/wcdb#12]
Is it possible for wcdb to build on Win32?

**Comment by RingoD** [comment]
You can build android version on Win32.
But WCDB for C++ and C# is not supported yet.

**Comment by skyline75489** [comment]
Would love to see Win32 & C# support in the future. Thanks for your contribution to the community, anyway. Cheers.

**Comment by skyline75489** [comment]
There seems to be no easy way for sqlcipher to build on VC++. See https://github.com/sqlcipher/sqlcipher/issues/180 . So I don't think it would be possible for WCDB to support Win32. You can close this issue or leave it open. I'm OK with it. 🍻

**Comment by RingoD** [comment]
This can be an issue or not. We will discuss it and make a decision in the future.

**Comment by RingoD** [comment]
This can be a feature or not. We will discuss it and make a decision in the future.

**Comment by John-He-928** [comment]
WCDB currently doesn't have a platform specific binding for Win32,  but I think just building SQLCipher on VC is not so difficult (with prebuilt OpenSSL crypto library).

We may try fixing build problems for SQLCipher itself, but it has low priority.
C# bindings may be supported in the future.

**Comment by skyline75489** [comment]
Glad to hear. I happen to be working on Win32 & C# recently. I'll see if I can help.

**Comment by lingol** [comment]
Why not just use LINQ? It's way better than raw SQLite/FMDB/other wrappers.
https://stackoverflow.com/questions/250071/linq-with-sqlite-linqtosql
