### ISSUE TITLE
可否提供wcdb对sqlite修改的changelog?

### ISSUE THREAD

**Issue by alexlee002** [Tencent/wcdb#120]
wcdb的代码质量几乎秒杀同类产品(FMDB只是接口好用， 代码质量并不太好。)

但是wcdb自带了修改版的sqlite,  能否提供/维护一个对sqlite的change log?
因为如果要用在公司项目上， 还是需要谨慎评估。

**Comment by RingoD** [comment]
我们后续会提供sqlite的changelog，目前也可以通过sqlite的submodule中的commit了解到修改点。
