### ISSUE TITLE
Is There a Way to Optimize Carthage Build to Compile Only Specified xcframework?

### ISSUE THREAD

**Issue by EchoLunar** [Tencent/wcdb#1200]
I’m currently using GitHub Actions for CI to build my application, and I’ve noticed that the Carthage build process for WCDB takes a significantly long time. It compiles four different XCFrameworks, but I only need to compile a specified .xcframework, specifically WCDBSwift.xcframework.

Is there a way to optimize the build process to compile only the specified .xcframework instead of all? This would greatly reduce build times and improve overall CI efficiency.

**Comment by Qiuwen-chen** [comment]
I have no idea. May be you can use cocoapod or build wcdb from source.
