### ISSUE TITLE
Crash when create table

### ISSUE THREAD

**Issue by LimChihi** [Tencent/wcdb#1201]
### The language of WCDB

swift

### The version of WCDB

v2.1.8

### The platform of WCDB

iOS 18.0

### The installation of WCDB

Swift Package Manager

App crash in 
#0	0x0000000106b47c04 in WCDB::SQL::SQL wcdb/src/common/winq/SQL.cpp:34
when I try to create a table.

![螢幕截圖 2024-09-28 20 41 05](https://github.com/user-attachments/assets/701e7659-7ea2-4594-a673-d8ab68ae9d55)

Here is the code
```swift
// main

// define a Model
struct Persion: TableCodable {
    let name: String
    enum CodingKeys: String, CodingTableKey {
        typealias Root = Persion
        static var objectRelationalMapping: TableBinding<Persion.CodingKeys> {
            .init(CodingKeys.self)
        }
        case name
    }
}

// create a table
let doc = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
let db = Database(at: doc.appending(path: "Database/temp.db"))
do {
    try db.create(table: "Persion", of: Persion.self)
} catch let e {
    print(e)
}
```

This is a crash demo. Build and run can rebuild the crash.
[WCDBCrashDemo.zip](https://github.com/user-attachments/files/17174413/WCDBCrashDemo.zip)

**Comment by LimChihi** [comment]
More Info, This crash look like caused by `objectRelationalMapping`.

This crash can be fix if you change `objectRelationalMapping` init function from
```swift
static var objectRelationalMapping: TableBinding<CodingKeys> {
    .init(CodingKeys.self)
}
```
to 
```swift
static let objectRelationalMapping = TableBinding<CodingKeys>()
```

But this is also a problem, Swift 6 will disable the `static let` writing style because of concurrency-safe.

**Comment by Qiuwen-chen** [comment]
Get

**Comment by Qiuwen-chen** [comment]
You can use this is swift6: 
nonisolated(unsafe) static let objectRelationalMapping = TableBinding(CodingKeys.self)
