### ISSUE TITLE
The database query results do not match expectations

### ISSUE THREAD

**Issue by mumushuipi** [Tencent/wcdb#1202]
### The language of WCDB

Swift

### The version of WCDB

v2.1.8

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

After upgrading from V1.0.8.2 to V2.1.8, the following issues occurred：

- sql
(((deviceId = 'deviceid_0') AND (productId = 'productId_1')) AND (pairKey IN(SELECT pairKey FROM cloudVideoList GROUP BY pairKey HAVING (COUNT(pairKey) = 2))))

result:
Four results can be filtered out through SQL statements

![sql](https://github.com/user-attachments/assets/e7e69e54-fe47-4b4d-be03-d2824d5c5802)

- wcdbSwift:
Two results can be filtered out through SQL statements

![wcdbswift](https://github.com/user-attachments/assets/ce147ba4-1a65-4a56-86f6-4c29dcc6f70b)

**Comment by Qiuwen-chen** [comment]
I'm not sure if it is a bug of sqlite, may be you can give me a demo project to reproduce it.
