### ISSUE TITLE
是否支持 win   mingw 编译 我想在QT上使用这个库 但是QT需要用到mingw编译器

### ISSUE THREAD

**Issue by ma12155506** [Tencent/wcdb#1203]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
May be it is already supported, you can try to build WCDB C++ first.

**Comment by broadcast98** [comment]
@Qiuwen-chen  
WCDB C++ 不就是这个库吗？编译不过啊！！！

有另一个  WCDB C++ 库吗？

**Comment by broadcast98** [comment]
@ma12155506 请问你找到 qt mingw 编译的方法了吗？
