### ISSUE TITLE
Any plan to support Rust?

### ISSUE THREAD

**Issue by xuxiaocheng0201** [Tencent/wcdb#1204]
Is there a plan to support Rust?
What I mean is not to rewrite in Rust, but to generate Rust bindings.
I really hope to use WCDB in my Rust program.
Thank you very much.

**Comment by Qiuwen-chen** [comment]
No

**Comment by jrjrmiih** [comment]
https://github.com/jrjrmiih/wcdb_rust
This repo forked from here. Rust support has just started, welcome to join coding!
