### ISSUE TITLE
is there any doc or code for "Android room compat" when upgrade WCDB 1.x -> 2.x

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1205]

**Comment by Qiuwen-chen** [comment]
We don't support room in the new version

**Comment by sooglejay** [comment]
can we developers decide to implement room-compat like compat module in WCDB 2.0 by ourselves,  so that we use the old interfaces like before.

**Comment by Qiuwen-chen** [comment]
sure
