### ISSUE TITLE
no such tokenizer: wcdb_verbatim. how to set tokenize in sql?

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1208]
@Qiuwen-chen  how to set tokenize  using BuiltinTokenizer.MMICU  in sql ?  my sql like below: 

`CREATE VIRTUAL TABLE IF NOT EXISTS fts_contact_index_table USING fts4(tokenize=simple)`

The mmicu tokenizer has been marked as deprecated in WCDB 2.0. What is the recommended replacement for it?

    /**
     * Deprecated tokenizer for fts3/4.
     */
    public final static String MMICU = "mmicu";

when I use tokenizer=wcdb_verbatim as below:  
`
CREATE VIRTUAL TABLE IF NOT EXISTS fts_xxx_index_table USING `fts5(tokenize='wcdb_verbatim')

I got exception as below:
``
com.tencent.wcdb.base.WCDBNormalException: Code: 1; Message: no such tokenizer: wcdb_verbatim; Path: xxx.db; SQL: CREATE VIRTUAL TABLE IF NOT EXISTS fts_xxx_index_table USING fts5(tokenize='wcdb_verbatim skip_stemming chinese_traditional_to_simplified',fts_name);; at com.tencent.wcdb.core.PreparedStatement.createException(PreparedStatement.java:48) at com.tencent.wcdb.core.PreparedStatement.step(PreparedStatement.java:88) at com.tencent.wcdb.compat.SQLiteStatement.execute(SQLiteStatement.java:37) at com.tencent.wcdb.compat.SQLiteStatement.execute(SQLiteStatement.java:72) at com.tencent.wcdb.compat.SQLiteDatabase.execSQL(SQLiteDatabase.java:1000) at com.tencent.wcdb.compat.SQLiteDatabase.execSQL(SQLiteDatabase.java:995) at com.tencent.wcdb.compat.SQLiteDatabase.execSQL(SQLiteDatabase.java:942)
``

_Originally posted by @sooglejay in https://github.com/Tencent/wcdb/issues/1196#issuecomment-2406415506_

**Comment by Qiuwen-chen** [comment]
https://github.com/Tencent/wcdb/wiki/Java%7CKotlin-%e5%85%a8%e6%96%87%e6%90%9c%e7%b4%a2

**Comment by sooglejay** [comment]
OMG... I forgot to add tokenizer... 
![image](https://github.com/user-attachments/assets/692c94ea-3178-4819-8567-6b736f898bbd)

**Comment by sooglejay** [comment]
**I encountered an error when using the** mmicu **tokenizer as per the WCDB 2.0 documentation**: sqlException=[WCDB] [IGNORE] Code: 1; Message: unknown tokenizer: mmicu; Path: xx.db; SQL: SELECT fts3_tokenizer('mmicu'); Source: SQLite. **What could be the issue, and what is the recommended replacement for** mmicu?
