### ISSUE TITLE
WCDB.swift Version 2.1.8 Build Failed

### ISSUE THREAD

**Issue by HelloHchen** [Tencent/wcdb#1209]
Language：Swift 
Version：'WCDB.swift', '2.1.8'
Xcode：Version 15.2 (15C500b)

But when I changed to version 2.1.2, can build success.

Errors on 2.1.8 Screenshots 👇
![image](https://github.com/user-attachments/assets/97e7308b-683c-4465-8ec0-9aee200fa8cd)
![image](https://github.com/user-attachments/assets/4847c0ce-0ed6-4627-ae93-a832cf0457d1)

![image](https://github.com/user-attachments/assets/2b44e3ae-ecab-4daa-add8-a3535623865c)
![image](https://github.com/user-attachments/assets/c14ce2cf-dba6-4eef-b220-4eda60aaedad)

**Comment by Qiuwen-chen** [comment]
upgrade your xcode

**Comment by HelloHchen** [comment]
OK, I got it, thank you. (I'd rather use the lower version, I don't want to upgrade Xcode at the moment
