### ISSUE TITLE
Code: 21; Message: Statement is not finalized

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1215]
### The language of WCDB

>  Java

### The version of WCDB

>  v2.1.8

### The platform of WCDB

>  Android

### The installation of WCDB

>  Git clone

### What's the issue?

>  com.tencent.wcdb.base.WCDBNormalException: Code: 21; Message: Statement is not finalized.; Build: Custom Build; Source: Assertion; Version: Custom build
![image](https://github.com/user-attachments/assets/87f802a2-c873-4e34-afc5-0328bd1f7286)

**Comment by Qiuwen-chen** [comment]
Your pull repuests can solve this problem, thanks.

**Comment by sooglejay** [comment]
still exist, please take a look https://github.com/Tencent/wcdb/issues/1217
