### ISSUE TITLE
Transaction Rollback Suspected After Upgrading to WCDB 2.0

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1217]
### The language of WCDB

> e.g. Java 

### The version of WCDB

> e.g. v2.1.8

### The platform of WCDB

> e.g. Android

### The installation of WCDB

> e.g. git clone 

### What's the issue?

I recently upgraded from WCDB 1.0 to WCDB 2.0, but I retained the same transaction handling logic that I used in WCDB 1.0. I am now facing an issue where performance metrics such as costInNanoseconds and indexPageReadCount are always zero, and I suspect that my transactions might be rolling back without being committed properly. 

I encountered the issue while inserting data using WCDB 2.0. The function responsible for inserting records returns the correct row ID, indicating that the insertion was successful. However, when I query the database file, the corresponding data is missing, and I can’t find the record that was supposed to be inserted.

> ![image](https://github.com/user-attachments/assets/2f49f821-cced-4ee6-8b9e-59df1abb1f8a)

> ![image](https://github.com/user-attachments/assets/73768934-00e5-4d12-95f8-22bdc8b99e9c)

Could it be that some changes in transaction handling between WCDB 1.0 and 2.0 are causing the rollback? What are the key differences in transaction management between these versions, and how should I modify my transaction logic to ensure proper commit behavior in WCDB 2.0?

Additionally, what would be the best way to debug this issue, possibly by setting breakpoints or logging transaction rollbacks in WCDB 2.0?

**Comment by sooglejay** [comment]
Previously, I encountered the exception:
`com.tencent.wcdb.base.WCDBNormalException: Code: 21; Message: Statement is not finalized.; Build: Custom Build; Source: Assertion; Version: Custom build`

I attempted to fix it by implementing a try-finally block around the database operations, ensuring that the statement is finalized in the finally clause. Specifically, I submitted a [pull request](https://github.com/Tencent/wcdb/pull/1214/files), where I wrapped the code in a try block and called stmt.finalizeStatement() in the finally block to ensure the resources are cleaned up properly.

However, despite this fix, the problem still persists. The function responsible for inserting data returns the correct row ID, but I cannot find the corresponding data in the database file. I am now wondering if this might be related to transaction rollbacks or some other issue.

Do you have any further insights into what might be going wrong or additional steps I should take to troubleshoot this?

**Comment by sooglejay** [comment]
fixed by https://github.com/Tencent/wcdb/wiki/Java%7CKotlin-%e6%95%b0%e6%8d%ae%e5%ba%93%e3%80%81%e8%a1%a8%e3%80%81%e4%ba%8b%e5%8a%a1

**Comment by Qiuwen-chen** [comment]
I found your pull request is wrong, because the statement created from preparedWithMainStatement will automatically execute finalize when the step operation fails, so there is no need to put it into the finally block. 
When executing finalization in the finally block, the handle obtained in the try block may have been reused by other threads, so it is possible to finalize the statement being used by other threads.

**Comment by Qiuwen-chen** [comment]
May be you can give me a demo project to reproduce your problem. Or you can use some monitors for further analization: https://github.com/Tencent/wcdb/wiki/Java%7CKotlin-%e7%9b%91%e6%8e%a7%e4%b8%8e%e9%94%99%e8%af%af%e5%a4%84%e7%90%86

**Comment by sooglejay** [comment]
> May be you can give me a demo project to reproduce your problem. Or you can use some monitors for further analization: https://github.com/Tencent/wcdb/wiki/Java%7CKotlin-%e7%9b%91%e6%8e%a7%e4%b8%8e%e9%94%99%e8%af%af%e5%a4%84%e7%90%86

ok, I'll try and reproduce the issue if not fixed

**Comment by sooglejay** [comment]
![image](https://github.com/user-attachments/assets/b66cb334-714f-4909-94a2-f66c7fc9d98d)

![image](https://github.com/user-attachments/assets/7418397d-b60d-4633-8749-966e5723ab9b)

there are many code that manually call preparedStatement.finalizeStatement() ,  You should remove all the calls to finalizeStatement(). right?
