### ISSUE TITLE
Can we use backup manually if we enableAutoBackup, or the answer is DONOT

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1218]
### The language of WCDB

Java

### The version of WCDB

2.1.8

### The platform of WCDB

Android

### The installation of WCDB

Git clone

### What's the issue?

Is it recommended to manually call the backUp method after enabling the automatic backup capability in WCDB, or the answer is DONOT?

![image](https://github.com/user-attachments/assets/6492a608-5617-4fc0-a3d8-4ba7287c4cb8)

**Comment by Qiuwen-chen** [comment]
It is not recommended
