### ISSUE TITLE
Possible Bug in Nested Transaction Handling Logic in endTransaction()

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1219]
### The language of WCDB

Java 

### The version of WCDB

2.1.8

### The platform of WCDB

Android

### The installation of WCDB

Git clone

### What's the issue?

I’ve noticed a potential issue in the endTransaction() method within the transaction management code. Specifically, the line that sets parent.childFailed = true; may not accurately reflect the state of the child transaction.

Currently, parent.childFailed is set to true whenever the parent is not null, regardless of whether the child transaction was successful or not. This could lead to incorrect states being assigned to parent transactions when nested transactions are involved.

To improve the accuracy of the transaction management, I suggest modifying the logic to only set parent.childFailed = true; when the current transaction was unsuccessful. Here’s a proposed adjustment:

```
if (parent != null) {
    parent.childFailed = !successful;
}
```

This change would ensure that the parent transaction’s state correctly reflects the success or failure of its child transactions.

![image](https://github.com/user-attachments/assets/619d0e99-6765-463d-af8f-f1fe5394ecba)

**Comment by Qiuwen-chen** [comment]
Yes, it is truly a big bug. Fixed in the master branch. Thanks.

**Comment by sooglejay** [comment]
Could you please check if there are any other similar code errors throughout the project? I’m particularly concerned about potential issues related to transaction handling or other critical operations.
