### ISSUE TITLE
有没有Windows上查看Android上的加密数据库的GUI工具

### ISSUE THREAD

**Issue by zhangkehu** [Tencent/wcdb#122]
没找到交流群之类的，只好在这里问啦。

**Comment by zhangkehu** [comment]
额，这里找到了一个，试试看怎么用。http://www.sqlabs.com/sqlitemanager4_encryption.php

**Comment by zhangkehu** [comment]
@RingoD 大佬，下载了三个工具输入密码转为byte数组的字符串都打不开数据库，请教一下应该用什么姿势打开？

**Comment by RingoD** [comment]
交流群在Wiki上有写

**Comment by zhangkehu** [comment]
终于可以查看加密数据库了，查看[工具](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.9.1)，打开加密数据库会提示输入密码，这里wcdb输入的密码应该是产生byte数组的那个String原型，然后page_size填4096即可，记录一下，方便后面的同志少走弯路。

**Comment by tigerZhang86** [comment]
@zhangkehu 谢谢,让我少走弯路了！

**Comment by aolphn** [comment]
哎呀，又让今天的我少走弯路😄😄😄

**Comment by aolphn** [comment]
我又来了
