### ISSUE TITLE
finalizeStatement manually or not

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1220]
1. I believe it is necessary to release resources for PreparedStatement in the finally block, and the HandleOperation class also releases resources in the finally block.

2. Could you explain why the PreparedStatement class does not implement the AutoCloseable interface? What are the design considerations or implications behind this decision?

3. Why is the call to handle.invalidate() wrapped in the autoInvalidateHandle() condition? What is the rationale behind this design choice
```

     if(autoInvalidateHandle()) {
            handle.invalidate();
     }

```

![image](https://github.com/user-attachments/assets/d7d0183f-db15-4ea1-9fe1-f84688e173e8)

_Originally posted by @Qiuwen-chen in https://github.com/Tencent/wcdb/issues/1217#issuecomment-2410620961_

**Comment by Qiuwen-chen** [comment]
Both Database and Handle extend HandleOperation. Auto-invalidate is unsuitable for Handle.

AutoCloseable will be considered in the future, PreparedStatement is not supposed to be used frequently, since there are a lot of convinient methods.
