### ISSUE TITLE
use a keyword as a name

### ISSUE THREAD

**Issue by zhenian** [Tencent/wcdb#1221]
### The language of WCDB

Java

### The version of WCDB

2.1.4

### The platform of WCDB

Android

### The installation of WCDB

Maven

#### Background

I used the [GreenDAO](https://github.com/greenrobot/greenDAO) AS app database framework. 

Now I want to use WCDB java to replace GreenDAO.

#### Question 1

Code snippet with GreenDAO

```java

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

@Entity
public class TestEntity {
    @Id
    private long id;
    private String name;
    private Date readingTime;
    private int index;
    private int select;
}

```

GreenDAO generate the scheme :

```SQL

CREATE TABLE "TEST_ENTITY" (
    "_id" INTEGER PRIMARY KEY NOT NULL ,
    "NAME" TEXT, 
    "READING_TIME" INTEGER,
    "INDEX" INTEGER NOT NULL,
    "SELECT" INTEGER NOT NULL
)

```

Implementation using wcdb

```java

import com.tencent.wcdb.WCDBField;
import com.tencent.wcdb.WCDBTableCoding;

@WCDBTableCoding
public class TestEntity {
    @WCDBField(columnName = "_id", isPrimary = true) public long id;
    @WCDBField(columnName = "NAME") public String name;
    @WCDBField(columnName = "READING_TIME") public Date readingTime;
    @WCDBField(columnName = "INDEX") public int index;
    @WCDBField(columnName = "SELECT") public int select;
}

```

It got an error:

Message: near "INDEX": syntax error;

com.tencent.wcdb.base.WCDBNormalException: Code: 1; Message: near "INDEX": syntax error; Path: /xxxx/xxxx/xx.green.orm.db; SQL: CREATE TABLE IF NOT EXISTS TEST_ENTITY(_id INTEGER PRIMARY KEY, NAME TEXT, READING_TIME INTEGER,  INDEX INTEGER, SELECT INTEGER); Source: SQLite

#### Feature Request

In the document [SQLite Keywords](https://www.sqlite.org/lang_keywords.html) , it is mentioned that we can use keyword as a name.

So,  can add this feature in WCDB java ?

**Comment by Qiuwen-chen** [comment]
You can try the follow config:
public class TestEntity {
    @WCDBField(columnName = "_id", isPrimary = true) public long id;
    @WCDBField(columnName = "NAME") public String name;
    @WCDBField(columnName = "READING_TIME") public Date readingTime;
    @WCDBField(columnName = "'INDEX'") public int index;
    @WCDBField(columnName = "'SELECT'") public int select;
}

**Comment by zhenian** [comment]
> You can try the follow config: public class TestEntity { @WCDBField(columnName = "_id", isPrimary = true) public long id; @WCDBField(columnName = "NAME") public String name; @WCDBField(columnName = "READING_TIME") public Date readingTime; @WCDBField(columnName = "'INDEX'") public int index; @WCDBField(columnName = "'SELECT'") public int select; }



com.tencent.wcdb.base.WCDBNormalException: Code: 1; Message: duplicate column name: INDEX; Path: /xxxx/xxxx/xx.green.orm.db; SQL: ALTER TABLE main.TEST_ENITY ADD COLUMN 'INDEX' INTEGER; Source: SQLite

com.tencent.wcdb.base.WCDBNormalException: Code: 1; Message: duplicate column name: SELECT; Path: /xxxx/xxxx/xx.green.orm.db; SQL: ALTER TABLE main.TEST_ENITY ADD COLUMN 'SELECT' INTEGER; Source: SQLite


IT RUN. BUT it NOT work right.

it can write in db, but can't read value out for 'INDEX'  and 'SELECT' 

Maybe this issues should be reopen @Qiuwen-chen

**Comment by zhenian** [comment]
Instead of add support for keyword as column name.  changing the column name:


```java

    private boolean checkTableExistColumn(String table, String column){
        boolean exist = false;
        List<Value[]> list = this.db.getAllRowsFromStatement(new StatementPragma().pragma(Pragma.tableInfo).withValue(table));
        for(Value[] values : list){
            if(values.length < 2){
                continue;
            }
            Value name = values[1];
            if(name != null && !TextUtils.isEmpty(name.getText()) && column.equalsIgnoreCase(name.getText())){
                exist = true;
                break;
            }
        }
        return exist;
    }

    private void renameColumnIfExist(String table, String column, String newColumn){
        boolean exist = checkTableExistColumn(table, column);
        if(exist){
            Statement statement = new StatementAlterTable().alterTable(table).renameColumn("\"" + column + "\"").toColumn("\"" + newColumn + "\"");
            this.db.execute(statement);
        }
    }

```

usage: 

```java
renameColumnIfExist("TestEntity", "SELECT", "SELECT2");

```
