### ISSUE TITLE
Equivalent SQL statement to create the virtual table with fts4 mmicu

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1223]
### The language of WCDB

Java 

### The version of WCDB

2.1.8

### The platform of WCDB

Android

### The installation of WCDB

Git clone

### What's the issue?

error caused **(Code: 1; Message: unknown tokenizer: mmicu)** when I use sql statement to using fts4 with mmicu, https://github.com/Tencent/wcdb/issues/1222

Is there an equivalent SQL statement that corresponds to this code for creating the virtual table with specific FTS (Full Text Search)  and BuiltinTokenizer.MMICU?

```


@WCDBTableCoding(ftsModule =
 @FTSModule(version = FTSVersion.FTS5,             
            tokenizer = BuiltinTokenizer.MMICU)
)
public class FTSSample {
 @WCDBField(isNotIndexed = true) 
 public int id;
 @WCDBField
 public String summary;
 @WCDBField
 public String description;
}

// Register the tokenizer
database.addTokenizer(BuiltinTokenizer.MMICU)

// Create the virtual table
database.createVirtualTable('sampleVirtualTable', DBFTSSample)

**Comment by sooglejay** [comment]
error caused when I use sql statement to using fts4 with mmicu

**Comment by Qiuwen-chen** [comment]
If createVirtualTable does not throw any exception, just ignore this error(The error level of it is also Ignore).

**Comment by sooglejay** [comment]
![image](https://github.com/user-attachments/assets/fac13757-de36-4691-bd1d-7051e28f0593)

does WCDB not support fts4?

**Comment by sooglejay** [comment]
![image](https://github.com/user-attachments/assets/9d4fad71-8889-4d13-81d2-c517c64a1fa8)

what's the reason for this error?

**Comment by Qiuwen-chen** [comment]
I don't time to explain every thing. Read the code if you need.
