### ISSUE TITLE
如何通过自定义SQL语句初始化Select

### ISSUE THREAD

**Issue by zhangyanforever** [Tencent/wcdb#1225]
### The language of WCDB
Swift 
### The version of WCDB
v2.1.8
### The platform of WCDB
iOS
### The installation of WCDB
Git clone
### What's the issue?
我想执行一些特殊的自定义的Select SQL语句。对Select进行扩展的时候，增加了一个新的初始化方法如下图。其中StatementSelectSQL是一个继承自StatementSelect的自定义类，它的description变量重写成了固定返回初始化的传的sql字符串。
但是执行的时候查询不出内容，麻烦看下如何修改呢

重写init
![1](https://github.com/user-attachments/assets/125370ce-02bb-4340-95d6-0645528148c3)

初始化select
![2](https://github.com/user-attachments/assets/814a19a3-a64e-4515-b29a-517e2403f6bd)

查询
![3](https://github.com/user-attachments/assets/e9e9dd9e-bb4a-4af6-b5a7-87805c253b92)

**Comment by Qiuwen-chen** [comment]
StatementSelect can not be inherited. WCDB Swift does not support to execute custom sql string.
