### ISSUE TITLE
React Native iOS 引入WCDB.objc编译报错

### ISSUE THREAD

**Issue by huiqun922** [Tencent/wcdb#1226]
### The language of WCDB

> Objective-C

### The version of WCDB

> 2.1.8

### The platform of WCDB

>  iOS/React Native

### The installation of WCDB

>  Cocoapods

### What's the issue?

新建React Native(v0.75.4)工程
iOS Podfile 添加   use_frameworks! 和 pod 'WCDB.objc'
编译报错

![image](https://github.com/user-attachments/assets/4ea6d1fb-78a7-4031-9e3d-719ddfffb403)

Podfile 如下：

[Podfile.txt](https://github.com/user-attachments/files/17429372/Podfile.txt)

**Comment by Qiuwen-chen** [comment]
No idea, wcdb don't have this file.

**Comment by huiqun922** [comment]
bitset 是系统的C++库，这个报错会定位到React Native的Yoga库，应该是影响了Xcode对应c++的编译配置文件，但是具体不知道哪里的配置。

**Comment by ShawnShi2016** [comment]
> bitset 是系统的C++库，这个报错会定位到React Native的Yoga库，应该是影响了Xcode对应c++的编译配置文件，但是具体不知道哪里的配置。

有找到解决方法吗

**Comment by kaifuZzz** [comment]
> bitset 是系统的C++库，这个报错会定位到React Native的Yoga库，应该是影响了Xcode对应c++的编译配置文件，但是具体不知道哪里的配置。

请问有解决方案吗，遇到同样问题了

**Comment by zongren** [comment]
> > bitset 是系统的C++库，这个报错会定位到React Native的Yoga库，应该是影响了Xcode对应c++的编译配置文件，但是具体不知道哪里的配置。
> 
> 请问有解决方案吗，遇到同样问题了

把wcdb打包成xcframework，测试可行
