### ISSUE TITLE
如何在一个实例中加载多个库？

### ISSUE THREAD

**Issue by broadcast98** [Tencent/wcdb#1227]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

```
https://github.com/Tencent/wcdb/issues/614
想请教一下，如果想实现同一个app能够进行多个用户的切换，每个用户的数据单独保存到一个独立到数据库，比如用户a登陆后的数据库采用a.db 保存，a退出后，b在同一个手机上进行登陆，建立b.db用于存放b的相关数据。

这种场景，可以通过什么方式进行database的切换吗？ 目前database采用的单例，是需要重新走一次databse初始化操作么？

谢谢指教。有这方面经验的朋友也欢迎分享。再次谢过了
```

以上为一个旧ISSUE的问题，因为开发者回答很模糊，没解决问题，所以在这里重新提一下。我补充以下：
1. 原ISSUE问题是如何用一个实例，在多个库间切换。我的问题是如何在一个实例中加载多个库。应该是同一功能的二个面。
2. sqlite 自带有 ATTACH 数据库功能，可能在同一实例中加载多个库。但使用wcdb之后 ，这个功能好像是不能用了。如果能用请告之。

sqlite ATTACH 功能使用代码如下：
std::string attachSQL = "ATTACH  'D:/test.db' AS testdb;";
sqlite3_exec(m_db, attachSQL.c_str(), nullptr, nullptr, &errmsg);

**Comment by Qiuwen-chen** [comment]
database.execute(StatementAttach().attach(xxx).as(xxx))

**Comment by broadcast98** [comment]
有密码的库也是这样写么？

**Comment by Qiuwen-chen** [comment]
database.execute(StatementAttach().attach(xxx).as(xxx).key(xxx)). You should learn to use winq.
