### ISSUE TITLE
Class 'BindParameter' has no initializers 

### ISSUE THREAD

**Issue by WDDGitHubiOS** [Tencent/wcdb#1229]
### The language of WCDB

>Swift

### The version of WCDB

> v2.1.8

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods, pod 'WCDB.swift', '~> 2.1.8'

### What's the issue?

> When pod install  Project Build error
> the error is  -Class 'BindParameter' has no initializers
> No exact matches in call to initializer 
>have 400 bugs for buid error

**Comment by WDDGitHubiOS** [comment]
<img width="2017" alt="image" src="https://github.com/user-attachments/assets/fd501d39-1a0f-47cc-837e-8df6e83bbec1">

**Comment by Qiuwen-chen** [comment]
may be you should upgrade your xcode

**Comment by mikefan1998** [comment]
my xcode version is 15.2， whate latest version can i use ？

**Comment by Qiuwen-chen** [comment]
15.4 may be ok
