### ISSUE TITLE
核心层调用对不会c++的不太友好>_<,能否给个直接写SQL的api，或者有更好的解决方案推出

### ISSUE THREAD

**Issue by OYForever** [Tencent/wcdb#123]

**Comment by RingoD** [comment]
核心层接口并不需要C++的基础。
结合原本的SQL语句和文档、示例中的代码，依样画瓢即可写出对应的核心层接口。

关于如何简化核心层的代码，这个还在讨论中，可以关注repo中后续的提交。

**Comment by alexlee002** [comment]
非c++类型， 如何做到隐式类型转换？ 
如果没有这个， 那么winq的简洁性就不存在了。

**Comment by RingoD** [comment]
@alexlee002 请举例说明
