### ISSUE TITLE
Frequent openDatabase Calls Cause Tokenizer Unavailability and Re-registration

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1232]
### The language of WCDB

> Java 

### The version of WCDB

> 2.1.8

### The platform of WCDB

> Android

### The installation of WCDB

>  Git clone

### What's the issue?

I’m encountering an issue where mmicu appears to become unregistered during runtime, leading to an unknown tokenizer error. I suspect this is due to frequent calls to openDatabase, which seems to create new database instances, requiring the tokenizer to be re-registered each time.

1. Register a custom tokenizer using registerTokenizer.
2. Open the database and observe successful tokenizer usage initially.
3. During subsequent operations, frequent openDatabase calls appear to create new instances, leading to unregistered tokenizer issues and requiring re-registration.

```

/*
** This routine does the work of opening a database on behalf of
** sqlite3_open() and sqlite3_open16(). The database filename "zFilename"  
** is UTF-8 encoded.
*/
static int openDatabase(
  const char *zFilename, /* Database filename UTF-8 encoded */
  sqlite3 **ppDb,        /* OUT: Returned database handle */
  unsigned int flags,    /* Operational flags */
  const char *zVfs       /* Name of the VFS to use */
){
  sqlite3 *db;                    /* Store allocated handle here */
  int rc;                         /* Return code */
  int isThreadsafe;               /* True for threadsafe connections */
  char *zOpen = 0;                /* Filename argument to pass to BtreeOpen() */
  char *zErrMsg = 0;              /* Error message from sqlite3ParseUri() */
/* Allocate the sqlite data structure */
  db = sqlite3MallocZero( sizeof(sqlite3) );
  char dbAddress[30];
  sprintf(dbAddress, "%p", (void *) db);
  FTS3_LOGI("openDatabase for path=%s, dbAddress=%s",zFilename, dbAddress);
}


```

![image](https://github.com/user-attachments/assets/a4637e0e-c01f-4f72-b0cf-3d545cd66c5d)

![image](https://github.com/user-attachments/assets/5d660a22-70a6-406e-804a-51e89e643abe)

**Comment by Qiuwen-chen** [comment]
When multiple threads use the database in parallel, wcdb will open different DB handles for each thread.

**Comment by sooglejay** [comment]
could you show me any code snippets where does WCDB open different DB handles for each different thread?

**Comment by Qiuwen-chen** [comment]
> @Qiuwen-chen could you please show me any code snippets where does WCDB open different DB handles for each different thread?

You can check the code in HandlePool
