### ISSUE TITLE
'nonisolated' can not be applied to stored properties

### ISSUE THREAD

**Issue by cqcool** [Tencent/wcdb#1233]
在Apple M3 笔记本上运行出现WCDB-swfit（最新版本）出现该问题 'nonisolated' can not be applied to stored properties。同一项目跑MAC mini（Intel）上不会有问题。
 
笔记本上是XCode Version 15.0.1 (15A507)

```[tasklist]
### Tasks
```

**Comment by Qiuwen-chen** [comment]
Upgrade your xcode
