### ISSUE TITLE
Question on Auto-Commit Mode and Write Operation Timing without Explicit Transaction Control

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1236]
### The language of WCDB

> Java 

### The version of WCDB

> v2.1.8

### The platform of WCDB

> Android

### The installation of WCDB

> Git clone

### What's the issue?

I have a question regarding WCDB’s behavior in handling write or read operations without explicit transaction control. Specifically, if we don’t call functions like runInTransaction, beginTransaction or endTransaction for operations, what is the exact timing when the data is written/read or committed to the database? I understand that, generally, in SQLite’s auto-commit mode, each write operation would be committed immediately. However, I’m curious if WCDB has any specific optimizations or differences in this regard.

When using WCDB without explicit transactions, does each write operation immediately commit to the database, or is there some internal batching mechanism to commit the sql?

Any guidance、**code snippets** or insights would be greatly appreciated!

**Comment by Qiuwen-chen** [comment]
All write operations not in a transaction will be committed immediately.
