### ISSUE TITLE
如何获得 insert / update 后的 [db changes]

### ISSUE THREAD

**Issue by leonylcatwork** [Tencent/wcdb#124]
你好, 再提两个问题:

1. 在完成一个写入操作后, 如何获得改变的行数, 类似 FMDB 的 [db changes]?

2. 在 convenient 的方法里面, 貌似没有办法直接获取当前操作的 error? 是必须创建 WCTSelect / WCTInsert / WCTUpdate 等对象么?

谢谢

**Comment by RingoD** [comment]
1. 可以通过WCTInsert、WCTUpdate、WCTDelete、WCTTransaction的changes接口获取，该接口目前还在dev分支，发布后会合入master分支。
2. 既然叫做convenient接口，目的就是直接、易用，其设计原则就是一行代码完成操作。因此肯定是不包含error等信息的，更多信息应该用chaincall的接口获取。

**Comment by leonylcatwork** [comment]
明白了~ 谢谢

**Comment by RingoD** [comment]
代码已经合到master分支
