### ISSUE TITLE
iOS平台Objective-C语言 开启自动备份遇到的问题

### ISSUE THREAD

**Issue by CharType** [Tencent/wcdb#1240]
### The language of WCDB

> Objective-C,

### The version of WCDB

> v2.1.8

### The platform of WCDB

> iOS

### The installation of WCDB

> Dynamic Framework

### What's the issue?

> 使用了 enableAutoBackup 函数 自动备份数据库 但是在出错的回调(globalTraceError)中一直有提示开始备份 和 结束备份
> code = 27  error.message = Backup Begin. level = 3
>  code = 27  error.message = Backup End. level = 3

**Comment by Qiuwen-chen** [comment]
globalTraceError is also a log output interface, just ignore the error with level lower then warning.
