### ISSUE TITLE
Potential Deadlock in tryIncreaseHandleCount due to Infinite Waiting

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1241]
### The language of WCDB

>  Java 

### The version of WCDB

>  218

### The platform of WCDB

> Android

### The installation of WCDB

> Git clone

### What's the issue?
In the original implementation of `tryIncreaseHandleCount` in `HandleCounter`, there seems to be a potential deadlock scenario due to the way threads are managed when the handle pool is full. Specifically, the code enters infinite waiting states when resources are exhausted, and no thread is able to make progress. 

The current logic in the `tryIncreaseHandleCount` function checks whether the handle pool is full and waits for available resources using condition variables:

```cpp
while (m_totalCount >= HandlePoolMaxAllowedNumberOfHandles
       || (writeHint && m_writerCount >= HandlePoolMaxAllowedNumberOfWriters)) {
    while (m_totalCount >= HandlePoolMaxAllowedNumberOfHandles) {
        if (!handleShouldWaitWhenFull(type)) {
            return false;
        }
        m_pendingNormals.emplace(Thread::current());
        m_conditionalNormals.wait(lockGuard);
        m_pendingNormals.pop();
    }
    while (writeHint && m_writerCount >= HandlePoolMaxAllowedNumberOfWriters) {
        if (!handleShouldWaitWhenFull(type)) {
            return false;
        }
        m_pendingWriters.emplace(Thread::current());
        m_conditionalWriters.wait(lockGuard);
        m_pendingWriters.pop();
    }
}

```

This logic can lead to deadlock situations:
1. Threads that are waiting for resources might get stuck forever if no other threads free up handles.
2. There is no timeout or retry limit on waiting, so the threads can be indefinitely blocked.

#### Expected Behavior

The function should:
1. Allow for a timeout or a maximum retry limit when waiting for resources.
2. Avoid deadlock situations where no resources are freed, and threads are blocked indefinitely.
3. Provide a more robust way to handle conditions where the handle pool is full.

#### Suggested Fix
Consider adding a timeout mechanism to the wait calls and possibly a retry limit for acquiring handles. This way, threads are not indefinitely blocked, and the system remains responsive even under heavy load.

#### Steps to Reproduce
1. Set the HandlePoolMaxAllowedNumberOfHandles to a small value, e.g., 1.
2. Set the HandlePoolMaxAllowedNumberOfWriters to a small value, e.g., 1.
3. Create a scenario where many threads attempt to acquire handles simultaneously (both normal and writer handles).
4. Observe the system’s behavior—threads may get stuck waiting indefinitely, causing a deadlock.

---

#### Test Case
为了测试 `tryIncreaseHandleCount` 函数是否会陷入死循环，我们可以构造一个用例，其中：
- 设置较小的资源池和写入者限制。
- 多个线程同时请求获取句柄。
- 在没有线程释放资源的情况下，观察线程是否进入死循环。

以下是构造测试用例的思路：

```cpp
#include <iostream>
#include <thread>
#include <vector>
#include <atomic>

class MockHandleCounter : public WCDB::HandleCounter {
public:
    MockHandleCounter() : HandleCounter() {}

    bool tryIncreaseHandleCount(WCDB::HandleType type, bool writeHint) override {
        return HandleCounter::tryIncreaseHandleCount(type, writeHint);
    }
};

void testDeadlockScenario() {
    // 设置最大允许的句柄数量和写入句柄数目为1
    WCDB::HandlePoolMaxAllowedNumberOfHandles = 1;
    WCDB::HandlePoolMaxAllowedNumberOfWriters = 1;
    
    MockHandleCounter handleCounter;
    
    std::atomic<int> failedAttempts{0};
    auto task = [&]() {
        // 每个线程尝试获取句柄
        if (!handleCounter.tryIncreaseHandleCount(WCDB::HandleType::Normal, false)) {
            failedAttempts++;
        }
    };

    // 启动多个线程，超过资源池的容量
    std::vector<std::thread> threads;
    for (int i = 0; i < 10; ++i) {
        threads.push_back(std::thread(task));
    }

    // 等待线程结束
    for (auto& t : threads) {
        t.join();
    }

    // 打印失败的尝试次数，理想情况下，应该有失败的尝试，但不应有死循环
    std::cout << "Failed attempts: " << failedAttempts.load() << std::endl;
}

int main() {
    testDeadlockScenario();
    return 0;
}

**Comment by Qiuwen-chen** [comment]
You should avoid to hold the handles for a long time.

**Comment by sooglejay** [comment]
how to check whether some handles being hold too long?

**Comment by Qiuwen-chen** [comment]
> Thank you for your prompt response. I understand that holding handles for an extended time should be avoided, but I have a specific concern regarding the autoInvalidateHandle() method. I suspect that it may be returning false, which could lead to handles not being invalidated as expected.
> 
> ```java
> if (this.autoInvalidateHandle()) {
>     handle.invalidate();
> }
> ```
> 
> In my scenario, if autoInvalidateHandle() returns false, the handle.invalidate() method will not be called, potentially causing handles to accumulate in the pool. Once the number of active handles reaches the HandlePoolMaxAllowedNumberOfHandles limit, any additional requests for handles might enter a waiting loop indefinitely.

Don't worry, it works well here

**Comment by sooglejay** [comment]
I noticed something unusual in the log output:

`2024-11-07 17:33:22.210 26186-26877 WCDB2 com.ss.android.wcdb.demo  I leave decreaseHandleCount without notify since hasNotified=false and empty m_pendingNormals writersCount=4 totalCount=4, writeHint=0, threadId=26877, m_pendingWriters=10, m_pendingNormals=0`

In this case, decreaseHandleCount exited without sending a notification, even though there are 10 pending writers (m_pendingWriters=10). This might indicate an issue with the writeHint parameter, as it is set to 0 in this instance.

Could you check if writeHint is being passed correctly throughout the code, especially in scenarios where there are pending writers? If writeHint is inadvertently set to false, it might prevent necessary notifications and lead to blocked writer threads.

I am debugging with the code below to see if my issue would be fixed
```
if (!hasNotified && m_writerCount > 0 && m_pendingWriters.size() > 0) {
    LOGI("Extra notify for pending writers");
#ifdef __APPLE__
    m_conditionalWriters.notify(m_pendingWriters.front());
#else
    m_conditionalWriters.notify_all();
#endif
}
```

**Comment by sooglejay** [comment]
![image](https://github.com/user-attachments/assets/810f26f0-23c5-4922-9fb1-64c9ebe74beb)

when I increate the number of handles, the issue when I use transaction is fixed. but this is not a best solution, I need found out why the decreaseHandleCount does not notify the writers

**Comment by Qiuwen-chen** [comment]
You can give me a demo to reproduce you problem.

**Comment by sooglejay** [comment]
> You can give me a demo to reproduce you problem.

![image](https://github.com/user-attachments/assets/e429fdfc-ab3e-44a2-b7b5-614495ac7c45)

ok, I would also like to know if WeChat uses the same configuration of 32 and 4 for these values in its production environment.

**Comment by Qiuwen-chen** [comment]
> > You can give me a demo to reproduce you problem.
> 
> ![image](https://private-user-images.githubusercontent.com/6687300/384252682-e429fdfc-ab3e-44a2-b7b5-614495ac7c45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTU1NzEsIm5iZiI6MTczMTA1NTI3MSwicGF0aCI6Ii82Njg3MzAwLzM4NDI1MjY4Mi1lNDI5ZmRmYy1hYjNlLTQ0YTItYjdiNS02MTQ0OTVhYzdjNDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMDg0MTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGZkMDRhNTgxZTE5ZWM4Y2ExZWNiNjc5OTgwMDNhN2U3YTg3YTVlNjIwMTdhMGEzY2QxMWI0M2VmY2ViMjc3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wWygsqgnBbb_AGE6WBcxAhcTrfPEmgPlaxNcMCgSHsQ)
> 
> ok, I would also like to know if WeChat uses the same configuration of 32 and 4 for these values in its production environment.

sure
