### ISSUE TITLE
Database.getHandle

### ISSUE THREAD

**Issue by kuas** [Tencent/wcdb#1242]
### The language of WCDB
swift
### The version of WCDB
> 2.1.2

### The platform of WCDB
> ios

### The installation of WCDB
> Cocoapods

### What's the issue?
启动时初始化数据库，创建表，低概率（0.02%）出现崩溃, 是我哪里用错了吗

 EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000020
 Crashed: com.apple.main-thread
0  WCDBSwift                      0x106bf0 Database.getHandle(writeHint:) + 28 (Database.swift:28)
1  WCDBSwift                      0x10be8c protocol witness for HandleRepresentable.getHandle(writeHint:) in conformance Database + 20 (<compiler-generated>:20)
2  WCDBSwift                      0x10be8c protocol witness for HandleRepresentable.getHandle(writeHint:) in conformance Database + 20 (<compiler-generated>:20)
3  WCDBSwift                      0x145a74 TableInterface<>.create<A>(table:of:) + 72
4  WCDBSwift                      0x1459cc TableInterface<>.create<A>(table:of:) + 28
5  BloomchicStore                 0x441720 specialized BCSQLiteManager.createTable<A>(for:of:) + 4345042720
6  BloomchicStore                 0xca2b0 @objc BCGlobalConfigManager.application(_:didFinishLaunchingWithOptions:) + 30 (BCRemoteToggleType.swift:30)
7  BloomchicStore                 0x4ded20 AppDelegate.application(_:didFinishLaunchingWithOptions:) + 115 (BCModuleCenter.swift:115)
8  BloomchicStore                 0x4df010 @objc AppDelegate.application(_:willFinishLaunchingWithOptions:) + 4345688080
9  ???                            0x1956d9bac (缺少)

**Comment by Qiuwen-chen** [comment]
This seems to be caused by your code.
