### ISSUE TITLE
Abount WCDBSwift

### ISSUE THREAD

**Issue by wdq123550** [Tencent/wcdb#1243]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
swift

### The version of WCDB

> e.g. v1.0.5

v2.9.1

### The platform of WCDB

> e.g. iOS, macOS or Android

ios

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

swift package manager

### What's the issue?

Hello, I added an extra property to the model, and then after I started the App again, the model disappeared.

**Comment by wdq123550** [comment]
version - 2.1.9

**Comment by Qiuwen-chen** [comment]
Don't know what do you mean.

**Comment by wdq123550** [comment]
意思就是比如我有一个userModel，然后里面原本只有userName，然后在某个版本增加了个userID，然后就getObject就返回nil了

**Comment by Qiuwen-chen** [comment]
It is not related to the new column. Check your code.

**Comment by wdq123550** [comment]
我刚刚自测了一遍，发现如果在旧模型中(当然这个模型已经遵守了wcdb的相关协议)。然后新增一个新的属性，然后这个新增的属性是string类型等foundation支持的类型，那么这个属性哪怕是写String都没问题，但是如果这个新增的属性，是一个新的Struct，就是自定义的结构体，假设说这个新的属性是Struct UserInfoModel { var avatar: string }，此时，在旧模型中添加这个属性要写成可选项，就是在UserModel中的var userInfoModel: UserInfoModel?，要写成可选项，如果不写可选项，直接是var userInfoModel: UserInfoModel，查出来的是个nil。所以这是不是model和DB的 ORM需要考虑可选项的特性。如果在版本v1.0.0中userModel还没有userInfoModel，但是如果在后面的版本需要加上自定义的这种结构体，需要加userInfoModel?，但是我有个疑问，就是，既然加String这种foundation的基本数据类型可以不用写成可选项的话，因为string没值默认给了空字符串，假设嵌套的userInfoModel里面其实也是一些foundation的数据类型，那好像也可以构建一个空的userInfoModel？然后就不用写成可选项了？因为db的ORM，导致需要写成可选项的话，可能会对业务端有掣肘，比如userInfoModel加了之后就必定有值之类的。

**Comment by Qiuwen-chen** [comment]
It's too complicated to implement.

**Comment by wdq123550** [comment]
如果使用swift自带的codable协议的话，应该可以自动完成序列化与反序列化的，哪怕嵌套了很多层，只要相关类或结构体都遵守了这个协议，那反序列化也可以使用deaodable，那自定义的结构体应该不难从db中构建出来。
当然只是一个个人想法，可能很不成熟，可能我想得太简单了。
