### ISSUE TITLE
Whether FTS3 or FTS4 is enabled？

### ISSUE THREAD

**Issue by BaronWj** [Tencent/wcdb#1246]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> 2.0.4

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue ?

WCDB using 2.0.4 ， Whether FTS3 or FTS4 is enabled？

**Comment by Qiuwen-chen** [comment]
Sure
