### ISSUE TITLE
Regarding Anti-injection: For this article, I would like to consult what security methods wcdb has adopted. Thank you very much!

### ISSUE THREAD

**Issue by BaronWj** [Tencent/wcdb#1249]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

Regarding Anti-injection: For this article, I would like to consult what security methods wcdb has adopted. Thank you very much!

**Comment by Qiuwen-chen** [comment]
This feature is provided by winq: https://github.com/Tencent/wcdb/wiki
