### ISSUE TITLE
Error:Execution failed for task ':LogicComponent:transformNativeLibsWithStripDebugSymbolForDebug'.

### ISSUE THREAD

**Issue by king1988** [Tencent/wcdb#125]
为什么我的工程里gradle文件里添加了
compile 'com.tencent.wcdb:wcdb-android:1.0.0'后就报错，日志如下：
Error:Execution failed for task ':LogicComponent:transformNativeLibsWithStripDebugSymbolForDebug'.
> java.lang.NullPointerException (no error message)
请问我该怎么做？

**Comment by John-He-928** [comment]
请用1.0.3版本，并升级到Android Studio 2.3以上试试

**Comment by king1988** [comment]
我使用的就是1.0.3，AS版本2.3.3
