### ISSUE TITLE
调用retrieve 修复损坏的数据库，进度回调不及时的问题

### ISSUE THREAD

**Issue by CharType** [Tencent/wcdb#1251]
### The language of WCDB

> Objective-C

### The version of WCDB

> 2.1.6

### The platform of WCDB

>  iOS

### The installation of WCDB

>Cocoapods

### What's the issue?

> 调用retrieve 修复损坏的数据库，进度回调
只有2次回调
2024-11-26 14:34:30:895 ✅I | WCDB: Reparing progress: 0.999000
2024-11-26 14:34:33:925 ✅I | WCDB: Reparing progress: 1.000000

一个1.7G文件大小的数据库 修复需要大概一分40秒，前面1分39秒进度一直没有回调，最后一秒回调了2次 这个是正常的吗？

**Comment by Qiuwen-chen** [comment]
You should check the retrieve score. The progress callback is not so accurate.

**Comment by CharType** [comment]
因为我看wiki上写的

修复过程根据数据库的大小不同，需要一定的时间。建议在界面上提示等待，并在子线程进行修复。retrieve:方法的回调会不断更新数据库的修复进度，可以用来做界面展示。

也就是说 现在最新版本的代码 修复数据库是拿不到进度回调,wiki没有更新对吗？

**Comment by CharType** [comment]
> You should check the retrieve score. The progress callback is not so accurate.

因为我看wiki上写的

修复过程根据数据库的大小不同，需要一定的时间。建议在界面上提示等待，并在子线程进行修复。retrieve:方法的回调会不断更新数据库的修复进度，可以用来做界面展示。

也就是说 现在最新版本的代码 修复数据库是拿不到进度回调,wiki没有更新对吗？
