### ISSUE TITLE
WCDB 2.1.9 - How to disable the busyRetry Function?

### ISSUE THREAD

**Issue by oqsh** [Tencent/wcdb#1252]
### The language of WCDB

Objective-C

### The version of WCDB

v2.1.9

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

How to disable the busyRetry Function?

In WCDB 2.0, when open a new databse (generate new handle), it will enable busyRetry in default: 

<img width="1019" alt="image" src="https://github.com/user-attachments/assets/cde297db-1b83-47a4-8199-e1fa5964b645">

<img width="1064" alt="image" src="https://github.com/user-attachments/assets/099585d1-bc54-4a64-90d3-c69ae8eca9cf">

It will be great for me if there is a switch to choose open busyRetry or not.😃 Thanks.

**Comment by Qiuwen-chen** [comment]
This is not recommended. If you really need it, you can directly modify the source code to compile
