### ISSUE TITLE
How to change the sqlcipher encrypted version to the non-encrypted version?

### ISSUE THREAD

**Issue by BaronWj** [Tencent/wcdb#1253]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Swift

### The version of WCDB

> e.g. 2.0.4

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapod

### What's the issue?
How to change the sqlcipher encrypted version to the non-encrypted version?
At present, the online version encrypts the database. How to change the encrypted version to the non-encrypted version?
Can you only migrate to new tables through data？Thanks!

**Comment by Qiuwen-chen** [comment]
You can try data migration: https://github.com/Tencent/wcdb/wiki/Swift-%E6%95%B0%E6%8D%AE%E8%BF%81%E7%A7%BB
