### ISSUE TITLE
Difference in the description of WAL Mode between WCDB Android and sqlite 

### ISSUE THREAD

**Issue by Chiichen** [Tencent/wcdb#1254]
[WCDB Android enableWriteAheadLogging](https://tencent.github.io/wcdb/references/android/reference/com/tencent/wcdb/database/SQLiteDatabase.html#enableWriteAheadLogging()) mentioned 

> Writers should use [beginTransactionNonExclusive()](https://tencent.github.io/wcdb/references/android/reference/com/tencent/wcdb/database/SQLiteDatabase.html#beginTransactionNonExclusive()) or [beginTransactionWithListenerNonExclusive(SQLiteTransactionListener)](https://tencent.github.io/wcdb/references/android/reference/com/tencent/wcdb/database/SQLiteDatabase.html#beginTransactionWithListenerNonExclusive(com.tencent.wcdb.database.SQLiteTransactionListener)) to start a transaction. Non-exclusive mode allows database file to be in readable by other threads executing queries.

However in [Sqlite Transaction](https://sqlite.org/lang_transaction.html) 

> EXCLUSIVE is similar to IMMEDIATE in that a write transaction is started immediately. EXCLUSIVE and IMMEDIATE are the same in [WAL mode](https://sqlite.org/wal.html), but in other journaling modes, EXCLUSIVE prevents other database connections from reading the database while the transaction is underway.

In my actual test, when WCDB is in WAL mode, there is actually a difference between invoking `beginTransactionNonExclusive` and `beginTransaction`. Is there any difference between the sqlite in WCDB and the sqlite in upstream?

**Comment by Qiuwen-chen** [comment]
We use sqlite 3.27.2 in WCDB.
