### ISSUE TITLE
请问swift怎么使用matchinfo方法

### ISSUE THREAD

**Issue by sonull-2019** [Tencent/wcdb#1255]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by sonull-2019** [comment]
再请问下，这个结合match 要怎么使用？

**Comment by Qiuwen-chen** [comment]
You can use winq to express this query: https://github.com/Tencent/wcdb/wiki/Swift-%e8%af%ad%e8%a8%80%e9%9b%86%e6%88%90%e6%9f%a5%e8%af%a2
