### ISSUE TITLE
如何为OC的数据model定义外键？

### ISSUE THREAD

**Issue by CityLeaf1993** [Tencent/wcdb#1256]
### The language of WCDB

> Objective-C

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

如何为Model定义外键?
> Explain what you want by example or code **in English**.
How to define one or more ForeignKeys for one data Model?

**Comment by Qiuwen-chen** [comment]
It is not supported in OC ORM. You can create table manually using WCDB::StatementCreateTable
