### ISSUE TITLE
swift使用压缩功能，如何链接zstd呢？

### ISSUE THREAD

**Issue by ondev** [Tencent/wcdb#1259]
参照教程中使用压缩功能， insert的时候异常了，提示需要WCDB_ZSTD=1，然后我在WCDB的target里面加上了宏WCDB_ZSTD=1，编译有报错，提示无法找到#include <zstd/zstd.h>

我自己编译了一个zstd.framework，然后在wcdb的target中link这个framework，结果还是失败。

**Comment by Qiuwen-chen** [comment]
You can build the WCDBSwift target in Xcode project from source.

**Comment by ondev** [comment]
@Qiuwen-chen Podfile中加入pod 'WCDB'来使用WCDB，是不是没有包含zstd?

**Comment by Qiuwen-chen** [comment]
> @Qiuwen-chen Podfile中加入pod 'WCDB'来使用WCDB，是不是没有包含zstd?

yes
