### ISSUE TITLE
如何集成 model是嵌套类型的的数据结构

### ISSUE THREAD

**Issue by anker-eric** [Tencent/wcdb#126]
如何集成 [model是嵌套类型的的数据结构
![333](https://user-images.githubusercontent.com/26217917/29759215-4942e64a-8bec-11e7-98cc-6838fab577b5.png)

**Comment by RingoD** [comment]
请参考column coding - https://github.com/Tencent/wcdb/wiki/ORM使用教程#自定义类型

**Comment by xiaoweiFive** [comment]
求demo一份看下
