### ISSUE TITLE
Not work with 'kapt' annotation processor in kotlin adroid project

### ISSUE THREAD

**Issue by wuseal** [Tencent/wcdb#1262]
### The language of WCDB
Kotlin

### The version of WCDB

2.1.9

### The platform of WCDB
Android

### The installation of WCDB
Maven

### What's the issue?

When compile project, it will throw this error:
```
AndroidStudioProjects/TestWCDB/app/build/tmp/kapt3/stubs/debug/com/example/testwcdb/Demo.java:7: error: The field with annotation @WCDBField can not be private or protected
    private long databaseId = 0L;
```

My demo class is very simple:

```kotlin
package com.example.testwcdb

import com.tencent.wcdb.WCDBField
import com.tencent.wcdb.WCDBTableCoding

@WCDBTableCoding
class Demo {
    @WCDBField(isPrimary = true, isAutoIncrement = true)
    var databaseId:Long = 0L
}
```

Here is the problem reproduce project link: https://github.com/wuseal/TestWCDB

**Comment by Qiuwen-chen** [comment]
WCDB use ksp, not kapt

**Comment by wuseal** [comment]
For any guys who has the same problem, use java model class files instead of kotlin model class files in kotlin androd project, then the 'kapt' can work well for WCDB
