### ISSUE TITLE
如何设置主键自增开始的基数数值？比如用户ID，想从200000开始自增

### ISSUE THREAD

**Issue by CityLeaf1993** [Tencent/wcdb#1263]
### The language of WCDB

> Objective-C

### The version of WCDB

>  v2.1.9

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> 如何设置主键自增开始的基数数值？比如用户ID，想从200000开始自增。
> 
> > How to set the base value of the primary key to start auto-incrementing? For example, the user ID should start auto-incrementing from 200000.

**Comment by Qiuwen-chen** [comment]
You can insert a data with id 200000 and then delete it. Or you can directly modify sqlite_sequence table.

**Comment by CityLeaf1993** [comment]
> You can insert a data with id 200000 and then delete it. Or you can directly modify sqlite_sequence table.

你好，我希望采取您给出的第二种方案：修改sqlite_sequence表，有sql语句，但是不知道使用什么API可以执行sql，或者其他方式如何修改sqlite_sequence。

**Comment by CityLeaf1993** [comment]
<img width="1345" alt="image" src="https://github.com/user-attachments/assets/a7150e16-6b6a-4e1e-a033-56d4d7c271f2">
@Qiuwen-chen 感谢， 已经通过学习“语言集成”的使用教程，了解了修改sqlite_sequence的方式，如上图。

> You can insert a data with id 200000 and then delete it. Or you can directly modify sqlite_sequence table.
