### ISSUE TITLE
unknown tokenizer: wcdb_one_or_binary

### ISSUE THREAD

**Issue by JvanChow** [Tencent/wcdb#1265]
### The language of WCDB

Objective-C

### The version of WCDB

2.1.8

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
<img width="996" alt="image" src="https://github.com/user-attachments/assets/82a14fb4-2893-4a4f-9880-c61cc3ac284f" />

> Explain what you want by example or code **in English**.
[TestWCDBFTS.zip](https://github.com/user-attachments/files/18097490/TestWCDBFTS.zip)

**Comment by Qiuwen-chen** [comment]
The level of this error is ignore, just ignore it
