### ISSUE TITLE
使用wcdb进行全文搜索，如何把"-"当做一个普通字符搜索,而不是作为一个分隔符

### ISSUE THREAD

**Issue by 810152690** [Tencent/wcdb#1266]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
You can config a parameter for tokenizer to treat symbols as token. In OC, this parameter is WCTTokenizerParameter_NeedSymbol.

**Comment by 810152690** [comment]
support WCTTokenizerVerbatim and WCTTokenizerParameter_NeedSymbol at same time？ like this WCDB_VIRTUAL_TABLE_TOKENIZE_WITH_PARAMETERS(WCTTokenizerVerbatim, WCTTokenizerParameter_NeedSymbol)

**Comment by 810152690** [comment]
thanks, it's helpful.
