### ISSUE TITLE
 Support for Individual Busy Tracers for Each Database Instance

### ISSUE THREAD

**Issue by sooglejay** [Tencent/wcdb#1267]
### The language of WCDB

> Java 

### The version of WCDB

> latest

### The platform of WCDB

> Android

### The installation of WCDB

> Git clone

### What's the issue?

Currently, the Database.globalTraceBusy method allows setting a global busy tracer to monitor database connection pool busy events. However, when Database.globalTraceBusy is called multiple times, the previous tracer is replaced. This makes it impossible to set different busy tracers for individual database instances. For example:

```
Database.globalTraceBusy(busyTracerA, 30.0); // Sets busyTracerA
Database.globalTraceBusy(busyTracerB, 30.0); // busyTracerA is replaced
```

Could you consider adding support for database-specific busy tracers? This would allow developers to set a unique busy tracer for each database instance?

**Comment by Qiuwen-chen** [comment]
No, it will reduce the performance.
