### ISSUE TITLE
WCDB版本为2.0.4，WCDBOptimizedSQLCipher版本为1.4.4时，无法正常运行

### ISSUE THREAD

**Issue by linnoIt** [Tencent/wcdb#1268]
### The language of WCDB

Swift 

### The version of WCDB

 v2.0.4

### The platform of WCDB

 iOS

### The installation of WCDB

 Cocoapods

### What's the issue?

WCDB版本为2.0.4，pod install 自动拉取的 WCDBOptimizedSQLCipher 版本为1.4.4。
具体报错信息：WCBD 库 HandleNotification.c文件 247行，无法调用 WCDBOptimizedSQLCipher 中 sqlite3_wal_checkpoint_handler方法

当前解决方式：podfile.lock中锁定WCDBOptimizedSQLCipher版本为1.4.2可解决。

希望寻求直接更新可解决的方式，谢谢

**Comment by Qiuwen-chen** [comment]
Please use the latest version
