### ISSUE TITLE
不同类对NSArray的支持

### ISSUE THREAD

**Issue by he15his** [Tencent/wcdb#127]
如果类A有一个property数组，数组里放的是NSString,类B有一个property数组，数组里放的是自定义对象C,这种情况下好像实现不了哦，使用WCTColumnCoding协议只能单独指定NSArray对应一种类型，不支持对不同的类设置不同coding方法。

**Comment by RingoD** [comment]
这个取决于你的序列化方式。
以系统的NSCoding为例，他在序列化时保存了反序列化对应的类信息，所以不会出现你提到的问题。
但如果你的序列化方式是pb之类不保存类信息的方式，则需要自己处理。

解决方法可以是，新建一个类A，继承自NSArray<NSString*>，并实现WCTColumnCoding。在类定义里使用A来定义

**Comment by he15his** [comment]
嗯对，继承后用自己的类来实现就能解决了

**Comment by ericoda** [comment]
能举例说明吗？

**Comment by GirlCunt** [comment]
对数组对象 存储比较疑惑 有demo 或者代码么
