### ISSUE TITLE
Receiver type 'std::remove_pointer_t<WCDB::remove_ownership_t<__strong id>>' (aka 'id') is not an Objective-C class

### ISSUE THREAD

**Issue by TieriaDM** [Tencent/wcdb#1270]
### The language of WCDB

> Objective-C

### The version of WCDB

> v2.1.8、2.1.9

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

I just make my message model to follow `WCTTableCoding` protocol, the code just like below 

``````objc
#import <Foundation/Foundation.h>
#import <WCDBObjc/WCDBObjc.h>

@interface MyMsgModel : NSObject

@property (nonatomic, copy) NSString *msgId;
@property (nonatomic, copy) NSString *content;
@property (nonatomic, strong) id extraData;

@end

@interface MyMsgModel (WCTTableCoding) <WCTTableCoding>

WCDB_PROPERTY(msgId);
WCDB_PROPERTY(content);
WCDB_PROPERTY(extraData);

@end
  
#import "MyMsgModel.h"
  
@implementation MyMsgModel

WCDB_IMPLEMENTATION(MyMsgModel)

WCDB_SYNTHESIZE(msgId);
WCDB_SYNTHESIZE(content);
WCDB_SYNTHESIZE(extraData);

@end
``````

When I build my code, the error below comes:

>  Receiver type 'std::remove_pointer_t<WCDB::remove_ownership_t<__strong id>>' (aka 'id') is not an Objective-C class
>
> in file included from xxxxxxxx/models/MyMsgModel.mm:8:
>
> in file included from xxxxxxx/models/MyMsgModel.h:11:
>
> in file included from xxxxxxxx-dkdoxxyekfcfffcezwcsuyobvnde/Build/Products/Debug-iphoneos/WCDB.objc/WCDBObjc.framework/Headers/WCDBObjc.h:38:
>
> in file included from xxxxxxxxx-dkdoxxyekfcfffcezwcsuyobvnde/Build/Products/Debug-iphoneos/WCDB.objc/WCDBObjc.framework/Headers/Interface.h:49:
>
> in file included from xxxxxxxxx-dkdoxxyekfcfffcezwcsuyobvnde/Build/Products/Debug-iphoneos/WCDB.objc/WCDBObjc.framework/Headers/WCTORM.h:28:
>
> in file included from xxxxxxxx-dkdoxxyekfcfffcezwcsuyobvnde/Build/Products/Debug-iphoneos/WCDB.objc/WCDBObjc.framework/Headers/WCTBinding.h:30:
>
> in file included from xxxxxxxxx-dkdoxxyekfcfffcezwcsuyobvnde/Build/Products/Debug-iphoneos/WCDB.objc/WCDBObjc.framework/Headers/WCTProperty.h:25:
>
> In instantiation of function template specialization 'WCTColumnBinding::WCTColumnBinding<id>' requested here
>
> In instantiation of function template specialization 'WCTColumnBinding::generate<id>' requested here

<img width="708" alt="iShot_2024-12-20_16 09 24" src="https://github.com/user-attachments/assets/d10ad6d8-1f90-41b6-9ed1-4dbecd6f5c09" />

**Comment by Qiuwen-chen** [comment]
You must specify the type of extraData
