### ISSUE TITLE
Android [Kotlin/Jaava] 在使用 getAllRowsFromStatement() 这种方式无法对数据模型直接解析吗？

### ISSUE THREAD

**Issue by Edison0716** [Tencent/wcdb#1272]
![image](https://github.com/user-attachments/assets/198b7d61-5e1b-4a11-9698-3ef4016b60a3)

必须使用 二维数组遍历吗？

**Comment by Qiuwen-chen** [comment]
yes

**Comment by Edison0716** [comment]
please help:

![image](https://github.com/user-attachments/assets/d2096cd9-689b-474d-834b-608967d7b4cd)

how to use winq to implement image's sql ?

![image](https://github.com/user-attachments/assets/5956a6d1-6341-4314-9d0f-5b75e1890aa1)


it is not correct.

@Qiuwen-chen

**Comment by Qiuwen-chen** [comment]
You can directly use DBxxx.name.table(xxx).

And you can use statement.getDiscription() to check the real sql of winq.

**Comment by Edison0716** [comment]
Just less info about `Join` on the document, hard to learn about how to use it.
