### ISSUE TITLE
The words is "这是数字123456 hi"，what should I do to get this word by search ""45"*"。I use "WCDB_VIRTUAL_TABLE_TOKENIZE_WITH_PARAMETERS(WCTTokenizerVerbatim, WCTTokenizerParameter_NeedSymbol)" code , but it's not work

### ISSUE THREAD

**Issue by 810152690** [Tencent/wcdb#1273]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
You can use custom tokenizer. WCTTokenizerVerbatim does not support searching for content in the middle of numbers
