### ISSUE TITLE
怎么样在模型绑定时定义某个字段为 COLLATE NOCASE

### ISSUE THREAD

**Issue by ddd0819** [Tencent/wcdb#1275]
Language: c++

version 2.1.7

怎么样在模型绑定时定义某个字段为 COLLATE NOCASE ,而不是在执行时使用Expression collate(const UnsafeStringView &collation)

**Comment by Qiuwen-chen** [comment]
It's not supported yet. You can use WCDB::StatementCreateTable to create table manually.

**Comment by ddd0819** [comment]
Thank you for your reply
