### ISSUE TITLE
咨询关于创建表的问题

### ISSUE THREAD

**Issue by dakexuan** [Tencent/wcdb#1276]
### The language of WCDB

> e.g. kotlin

### The version of WCDB

> e.g. v2.1.9

### The platform of WCDB

> e.g. Android

### The installation of WCDB

> e.g. Maven

### What's the issue?

有两个问题想问下，
1、我拿到数据库对象之后调用tableExist查询是否有某张表，会闪退，且必现，只要不调这个方法就没问题，异常如下：
com.tencent.wcdb.base.WCDBNormalException: Code: -1; Message: invalid error obj
2、我需要使用表名动态生成表，但是生成表似乎是异步，我调完createTable方法之后，再调用其他方法去操作这个表的内容，比如插入数据，会报没有这个表的异常。我想问下如何能让我可以同步实现创建表后可以立即使用。
以上，谢谢解答

**Comment by Qiuwen-chen** [comment]
give me a demo to reproduce it
