### ISSUE TITLE
demo build error on macOS

### ISSUE THREAD

**Issue by lsqlebai** [Tencent/wcdb#1277]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
c++

### The version of WCDB

> e.g. v1.0.5
master

### The platform of WCDB

> e.g. iOS, macOS or Android
macOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
build error 
include/WCDB/HandleORMOperation.hpp:127:23: error: implicit instantiation of undefined template 'WCDB::Insert<Sample>'
        auto insert = prepareInsert<ObjectType>().intoTable(table).value(obj);
demo.cpp:16:14: note: in instantiation of function template specialization 'WCDB::HandleORMOperation::insertObject<Sample>' requested here
    database.insertObject<Sample>(object, "sampleTable");

> Explain what you want by example or code **in English**.

#include "sample.h"
#include "WCDB/Database.hpp"

int main(int argc, char *argv[]) {
    WCDB::Database database("sample.db");
    bool ret = database.createTable<Sample>("sampleTable");
    printf("ret = %d\n", ret);
    //Prepare data
    Sample object(1, "sample_insert");
    //Insert
    // 以下代码等效于 SQL：INSERT INTO sampleTable(identifier, content) VALUES(1, sample_insert)
    ret &= database.insertObjects<Sample>(Sample(1, "sample_insert"), "sampleTable");
    WCDB::OptionalValueArray<Sample> objects = database.getAllObjects<Sample>("sampleTable");
}

#pragma once
====sample.hpp====
#include "WCDB/CPPORM.h"
#include "WCDB/CPPORMMacro.h"
#include "WCDB/Database.hpp"
#include <string>
class Sample {
public:
    Sample();//必须要有默认构造函数
    Sample(int identifier, const std::string& content);//非必须实现的构造函数，只是为了演示方便
    int identifier;
    std::string content;
    WCDB_CPP_ORM_DECLARATION(Sample)
};
WCDB_CPP_ORM_IMPLEMENTATION_BEGIN(Sample)
WCDB_CPP_SYNTHESIZE(identifier)
WCDB_CPP_SYNTHESIZE(content)
WCDB_CPP_ORM_IMPLEMENTATION_END

**Comment by Qiuwen-chen** [comment]
#include "WCDB/WCDBCpp.h"

**Comment by lsqlebai** [comment]
希望demo能把include代码也加上，或者有官方demo，这样更加nive
