### ISSUE TITLE
In Objective-C, How to select datas where same date. "where:Message.timeDate == msg.timeDate"?

### ISSUE THREAD

**Issue by 810152690** [Tencent/wcdb#1278]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
Just query with condition Message.timeDate == msg.timeDate

**Comment by Qiuwen-chen** [comment]
You can convert NSDate to double
