### ISSUE TITLE
影响的行数

### ISSUE THREAD

**Issue by huangsf89757** [Tencent/wcdb#1280]
在Swift版本的WCDB中，如何获取某个操作（如insert、update）后，影响的行数?

**Comment by Qiuwen-chen** [comment]
You can execute sql through Handle: 
https://github.com/Tencent/wcdb/wiki/Swift-%e9%ab%98%e7%ba%a7%e6%8e%a5%e5%8f%a3#handle

and then use Handle.changes to get the number of rows that were changed.
