### ISSUE TITLE
通过pod安装时  同时加入 pod 'sqlite3' 无法编译 最新的sqlite版本有兼容问题

### ISSUE THREAD

**Issue by applejian** [Tencent/wcdb#130]
如
pod 'WCDB'
pod 'sqlite3'

无法编译

**Comment by RingoD** [comment]
WCDB已经包含了sqlite3的源码，无须再pod 'sqlite3'

**Comment by applejian** [comment]
那如何更新 sqlite3 的版本呢

**Comment by RingoD** [comment]
wcdb内置了sqlite3 3.15.2，已经是较新的版本了

**Comment by applejian** [comment]
可不可以把这个单独提出来 因为我的一些其他框架也要用到
而且据pod search 显示 sqlite3 最新的到 3.20.1 了 一两个月会出来个版本

**Comment by RingoD** [comment]
WCDB内的sqlite3是经过优化的，性能上更优。
官方sqlite3虽然经常更新，但升级内容并不一定适合你的需求。这里并不推荐持续跟着官方的sqlite3更新。
如果你需要，可以根据wcdb的pod.podspec，将sqlite3部分删去

**Comment by applejian** [comment]
好的 谢谢
