### ISSUE TITLE
表联动删除

### ISSUE THREAD

**Issue by zidonJ** [Tencent/wcdb#133]
表联动删除 是不是很麻烦啊 API。deleteObjectsFromTable:NSStringFromClass(Student.class)
                                              where:Student.studentID == [_number.text intValue]  这样设计 联动删除比较难操作

**Comment by RingoD** [comment]
你的代码没有问题，这里也只有一行代码，不存在难操作的问题。
请更详细地举例说明你的问题

**Comment by zidonJ** [comment]
就是A表有一个字段是另一个表的主键，当A表删除一条数据的时候，要求所有以这个字段为主键的表也同时删除这一条数据。（感谢回复）

**Comment by RingoD** [comment]
麻烦提供你的两个表结构，以及你期望执行的sql

**Comment by zidonJ** [comment]
@interface Student : NSObject

@property int studentID;
@property(retain) NSString *name;
@property(retain) NSString *electiveName;
@property(retain) NSDate *modifiedTime;
@property(assign) BOOL isHaveSelectCls;

@end

@interface Student (WCTTableCoding) <WCTTableCoding>

WCDB_PROPERTY(studentID)
WCDB_PROPERTY(name)
WCDB_PROPERTY(electiveName)
WCDB_PROPERTY(modifiedTime)
WCDB_PROPERTY(isHaveSelectCls)

@end



选课表
@interface ElectiveClass : NSObject

@property (nonatomic,copy) NSString *className;
@property (nonatomic,copy) NSString *stuName;

@end

//每个学生只能选修一门课程 stuName是主键
@interface ElectiveClass (WCTTableCoding) <WCTTableCoding>

WCDB_PROPERTY(stuName)
WCDB_PROPERTY(className)

@end



当删除某条学生记录的时候 要求自动匹配删除掉某一个可能包含这个学生的记录

**Comment by RingoD** [comment]
依然没有明白什么是“可能包含这个学生的记录”
如果你需要删除ElectiveClass表内指定stuName的行，只需要用
```
NSString* name = @"sample";
[database deleteObjectsFromTable:tableName where: ElectiveClass.stuName==name];
```

**Comment by zidonJ** [comment]
学生表内的学生名字字段stuName可能是很多张表的外键,当学生表删除一条记录(stuName = @"Andrew")的时候,需要所以以stuName作为主键的表删除(stuName = @"Andrew")那一条记录。

**Comment by zidonJ** [comment]
学生表内的学生名字字段stuName可能是很多张表的主键,当学生表删除一条记录(stuName = @"Andrew")的时候,需要所以以stuName作为主键的表删除(stuName = @"Andrew")那一条记录。

**Comment by RingoD** [comment]
建议你直接用**SQL**去表达你的需求。
写明你的需求在没有WCDB时，
1. 各个表结构是怎样的。
2. 表之间的关系是如何。
3. 你执行了什么SQL，达到了什么效果。

**Comment by zidonJ** [comment]
delete from student where studentId = @"100" 当执行这个sql的时候(之前会记录A1，A2，A3的表名字,他们的主键是学生表的学生名字字段)，也同时会执行下面的sql语句
delete from A1 where name = @"Andrew"
delete from A2 where name = @"Andrew"
delete from A3 where name = @"Andrew"

**Comment by RingoD** [comment]
你这里是4句SQL，那就需要写4句代码执行，没有什么问题。为什么你会期望WCDB自动帮你删呢？

**Comment by ztlyyznf001** [comment]
你写 sql 也要写四句啊,你也不可能在一句里面完成..
