### ISSUE TITLE
多表联查

### ISSUE THREAD

**Issue by colaicode** [Tencent/wcdb#134]
使用prepareSelectMultiObjectsOnResults进行多表联查，得到的结果为空。但是运行通过WCTStatistics打印的sql，却可以得到正确的结果

**Comment by RingoD** [comment]
尝试更新到最新的master分支后再试试，可能是之前的一个bug

**Comment by colaicode** [comment]
我是通过cocoapods安装，最新版本是1.0.2。但是我发现cocoapods安装的SDK与clone编译后的SDK不一样，是不是cocoapods没有更新呢

**Comment by RingoD** [comment]
cocoapods是同步更新的，请清理你的缓存后再试。
参考常见问题：https://github.com/Tencent/wcdb/wiki/常见问题#cocoapods无法搜到wcdb或搜到的版本不是最新的

**Comment by colaicode** [comment]
已经将SDK更新到1.0.3，还是有一样的问题

**Comment by RingoD** [comment]
RingoD commented 17 hours ago
尝试更新到最新的master分支后再试试，可能是之前的一个bug

**Comment by colaicode** [comment]
经过测试，使用cocoapods引进的SDK会有此问题，但是使用静态库的方式引进的SDK则不会有这个问题

**Comment by RingoD** [comment]
该问题在master分支修复后还未打tag，因此cocoapods要指定分支或指定commit后再试

**Comment by colaicode** [comment]
好的，解决问题的速度点赞
