### ISSUE TITLE
iOS WCDB在网络请求库中做缓存 .mm问题

### ISSUE THREAD

**Issue by Wuou** [Tencent/wcdb#135]
场景：ios版的wxdb 如果在网络请求库中使用wcdb做数据持久化，那其他用到这个网络库的地方都要变成.mm，这样感觉好变扭啊。有什么解决方法么？

**Comment by RingoD** [comment]
请参考wiki和sample 
https://github.com/Tencent/wcdb/wiki/ORM使用教程#隔离cpp代码

**Comment by Wuou** [comment]
这个是解决了model中引用WCDB的隔离，但是在其他文件中还要使用数据库呀，WCTDatabase *database = [[WCTDatabase alloc] initWithPath:path];等等，甚至再在WCDB基础上加一层封装，在.h中暴露接口还是会要引用WCDB呀，比如：- (BOOL)updateRowsInTable:(NSString *)table onProperty:(const WCTProperty &)property withObject:(id)obj;，这些有办法隔离么？

**Comment by RingoD** [comment]
WCDB是属于Model，应该只在该层使用，并且修改文件名后缀为.mm
一个封装完善的Model，不应该对外暴露里边的细节，包括是否使用WCDB，对外也是需要不可知的，因此也不存在隔离的问题。

**Comment by Wuou** [comment]
那我有多个不同的数据模型model，我就要对应这多个模型在.m中 个个重新写一套增删查改方法么？

**Comment by RingoD** [comment]
没有明白你表达的意思，可以尝试举例说明。
model内可以透明使用WCDB，但对外的view、controller等，不应该能获知WCDB这个细节

**Comment by Wuou** [comment]
#import "WONetworkHelper.h"

@implementation WONetworkHelper

+ (NSURLSessionTask *)POSTWithBaseUrl:(NSString *)baseUrl
			model:(id)model
			tableName：tableName
                           suffixUrl:(NSString *)suffixUrl
                          parameters:(id)parameter
                             success:(WOHttpRquestSuccess)success
                             failure:(WOHttpRequestFailed)failure {

//    有缓存就取缓存数据
[_basedb getAllObjectsOfClass:model.class fromTable:tableName];
    
    NSURLSessionTask *sessionTask = [_sessionManager POST:baseUrl parameters:parameter progress:^(NSProgress * _Nonnull uploadProgress) {
        
    } success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        
   // 刷新后有更新就更新本地数据库，或者全部覆盖之的数据
	[_basedb updateAllRowsInTable:table onProperty:property withObject:obj] 
        
        success ? success(responseObject) : nil;
        
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        
        failure ? failure(error) : nil;
    }];
    
    return sessionTask;
}   

我之前意思就是这样的，网络请求需要引用WCDB

**Comment by Wuou** [comment]
想重新封装下WCDB，以便在项目中各个地方使用，所以问题是用到WOWCDBManager就需要.m改.mm

@interface WOWCDBManager : NSObject

+ (instancetype)defaultManager;

#pragma mark - create db
/**
 创建数据库
 
 @param path 数据库创建路径
 @param table 表名
 @param cls ORM对应的类
 @return 创建成功与否
 */
- (BOOL)createDBWithPath:(NSString *)path table:(NSString *)table elementClass:(Class)cls;


#pragma mark - Insert
/**
 插入数据
 
 @param obj ORM对应的模型类
 @param table 插入的表名
 @return 插入成功与否
 */
- (BOOL)insertObject:(id)obj table:(NSString *)table;

#pragma mark - Update Property With Object
/**
 修改某个字段的值
 
 @param table 表名
 @param property 被修改的字段
 @param obj ORM对应的模型类
 @return 修改成功与否
 */
- (BOOL)updateRowsInTable:(NSString *)table onProperty:(const WCTProperty &)property withObject:(id)obj;

#pragma mark - Delete

@end

**Comment by RingoD** [comment]
WOWCDBManager如果是提供给Model层的其他类使用的，那没有问题。但如果是提供给controller使用的，那么这里封装就不够完善了。
WOWCDBManager的抽象度应该更低一些，提供一些更业务相关的接口。
以删除过期数据为例，model对外的接口应该提供`- (BOOL)deleteExpiredModelSince:(NSDate*)date;`，而不是`- (BOOL)deteleModelWhere:(WCTCondition)condition;`

**Comment by Wuou** [comment]
😯，大概知道该怎么用了。谢谢您的答疑，如果遇到其它问题我再提问🤝
