### ISSUE TITLE
iOS 内存泄漏

### ISSUE THREAD

**Issue by isunimp** [Tencent/wcdb#138]
用leaks检测出有内存泄漏

<img width="753" alt="wx20170907-113501 2x" src="https://user-images.githubusercontent.com/7866141/30144899-a6461e6c-93c0-11e7-9433-ba19ffd64862.png">
<img width="262" alt="wx20170907-113246 2x" src="https://user-images.githubusercontent.com/7866141/30144870-7c35aa52-93c0-11e7-8f10-683b5359e1be.png">
<img width="266" alt="wx20170907-113223 2x" src="https://user-images.githubusercontent.com/7866141/30144871-7c66a9ea-93c0-11e7-9066-6060790ec0ff.png">

**Comment by RingoD** [comment]
你使用的WCDB版本是多少

**Comment by isunimp** [comment]
1.0.3 😊

**Comment by RingoD** [comment]
这个并非是内存泄漏。
WCDB的ORM有一个全局变量，且有循环的指针引用，导致Instrument误认为这个无法释放。事实上这个内存的生命周期是整个app的生命周期，不存在释放的问题，也就不存在泄漏的问题了。
我们在master分支上已经fix了这个问题，instrument不会误报了，你可以用master分支的代码重试。
相关commit：https://github.com/Tencent/wcdb/commit/0755f7f9cbbc1a5851ee54c8038c1785b5bf80f8

**Comment by isunimp** [comment]
好的  谢谢！👍👍👍
