### ISSUE TITLE
wcdb 的开发路线

### ISSUE THREAD

**Issue by fantasticfears** [Tencent/wcdb#139]
这个问题和 #96 类似。wcdb 现在是一个开源项目，主要的代码贡献来自于腾讯微信。那它的 roadmap 是怎么样的呢？

比如它在一段时间会只为了满足微信团队的需要来添加功能和 bugfix。还或是会继续拓展使用范围，去帮助其他人使用？

我拿 C++ API 的需求作例子？按照我刚扫了下代码的理解，现在 C++ 这是没法用到 ORM、CRUD、Transaction、WINQ 这些方便的写法的。不过大部分对 sqlite 的封装是 C++ 写的。所以把逻辑提取至 C++ 用 JNI 或者 OC，甚至自动生成接口都是可能的。不过做这些都需要不少工作。所以如果你们能分享一下你们的目标会对我们很有帮助。

**Comment by RingoD** [comment]
WCDB-iOS/macOS目前主要是完善iOS/macOS开发中数据库使用的性能、功能的问题，因此肯定是以OC为优先。
即，这里的因果关系是，WCDB-iOS/macOS版本提供了C++层以留作扩展，而不是WCDB实现了C++的逻辑而只维护iOS/macOS版本。

据我了解，有部分开发者正在利用核心层，尝试去做Windows C++或C#的版本，还在开发中。也有一些直接使用WCDB去做key-value的数据库，如https://github.com/Rannie/RHKeyValueStore

正如你所说，WCDB现在是一个开源项目，因此更多的人参与进来开发维护才更符合开源精神。
对于你的C++ API或导到JNI等的需求，我们可能与你场景不一致，无法完全理解你的需求，因此由我们来做也不是最适合的。因此希望你也将你的需求和代码贡献出来共同完善。

**Comment by RingoD** [comment]
关于Roadmap，WCDB-iOS/macOS有一些需求是在开源之前就有开发的计划了，因此这部分会是近期开发的重点。
在Issue列表里应该也可窥一斑，包括Swift版本、FTS的支持以及类似Notification的通知机制等等。

开发者在Issue和QQ群里的提的需求我们也很关注，如果是重要或共性的需求，也会优先去处理。其实在代码和文档的commit里，有很大一部分是开发者提的，由于当前WCDB开源时间并不长，开发者们提的需求并不复杂，基本都是立刻就fix掉的。

Android近期应该是以ORM为主， @John-He-928 也可以说下。

**Comment by fantasticfears** [comment]
感谢微信团队愿意去花时间帮助这个项目成长，也谢谢你的解答和鼓励。

我的需求跟 Dropbox 的架构（https://github.com/dropbox/djinni）比较一样。用 C++ 来完成主要的核心逻辑部分，这部分包括对 sqlite 的封装和 event loop。然后应用使用 C++ 这里暴露的 view model 来构建视图和处理交互。对于 iOS，OC++ 能直接接受大部分数据类型。Java 的话使用 JNI 来和 C++ 代码互相交换数据。目的是用性能换重用代码。

所以 WCDB 对 sqlite 的封装、优化和 sqlcipher、fts 这些对我来说很有价值。当然我理解 WCDB 优化了很多东西，而且 WCDB 希望在两个平台提供最好的性能，所以 Android、iOS 都是独立写出来的。不过这个开发成本对我来说就相当高了。这也是我提到利用 C++ 接口的意思。

**Comment by RingoD** [comment]
WCDB-iOS/macOS的架构分四层，
1. 底层的sqlcipher和损坏修复工具
2. 抽象层，即WINQ
3. 核心层，最主要的逻辑，包括多线程并发、性能优化等
4. 接口层，包含ORM、便捷的接口和平台特性的优化

这里只有4. 接口层是Objective-C的代码。因此一个C++的实现也主要需要完成便捷接口和ORM这两个方面的能力。前者只需满足大部分开发习惯，并不复杂，而后者则是重点。

如果你觉得这个开发成本过高，也可等待社区贡献第一个demo版本，然后再在其上去完善你的需求。

**Comment by fantasticfears** [comment]
是的，如果我能重用到核心层我就很满意了。不过要做到一个独立的实现，构建倒是很复杂的工程之一。我想请教一下你觉得怎么做会好一些。

我觉得大概有三种可能的做法。第一是用 CMake 构建核心层，然后让 apple 里的工程直接来处理核心层编译好的结果。第二种是 gyp 之类。还有一种是最简单的直接另一个目录然后用相对链接去控制编译。

**Comment by RingoD** [comment]
你建一个VS工程都可以呀，apple目录下的代码如果有共享需要，完全是可以提取到根目录的。主要还是看Windows C++的共同开发习惯

**Comment by fantasticfears** [comment]
啊，我问这个是因为核心库要变动的话意味着额外的工作。不过你完全支持这么做，我是蛮惊讶的...我现在很敬佩微信团队在开源上的态度。谢谢你的回答。

> 据我了解，有部分开发者正在利用核心层，尝试去做Windows C++或C#的版本，还在开发中。

我搜了一下还没有看到相关的目录，也没看到有相关的 issues。我能怎么联系他们呢？

**Comment by RingoD** [comment]
关于变动，这里的逻辑是，接口层不会轻易改接口。即便改了，也会将接口标为deprecated，多个版本后才删除。即确保近期的旧版本升到新版本不会出现error。

而核心层的维护上没有这个逻辑，因此变动可能是会有的。但从近期来看，基本都是简单的接口名称修改，没有大的功能架构变更。因此你可以以某个版本为基准进行开发，待完成后只需做简单的修改即可升级到最新版本。

关于Windows C++或C#版本，是开发者在我们的QQ交流群里直接联系我的。

**Comment by fantasticfears** [comment]
QQ 群里私聊问那位做 Windows C++ 的先生没收到回应。之后我花了点时间把 Apple 里的东西抽出来用 CMake 打包好了。

https://github.com/fantasticfears/wcdb/commit/a7e0664b5023ed5760824e2f87d6c4919155d11c

这里我没有修 XCode 的依赖库和 include 路径。有一些不太一致的头文件名我有修改。这个核心层 wcdb_core 已经足够我用了。

**Comment by happyjiahan** [comment]
@fantasticfears 我在调研在你的 core 上面封装一层C#的Wrapper，给Unity3D用，请问，wcdb_core你使用有什么Bug吗？谢谢。

**Comment by fantasticfears** [comment]
@happyjiahan 我现在精力不在上面，所以我不推荐你在生产上用。不过这个变动只涉及目录结构的变化。我只是在用 WCDB 底层的一些优化。你要注意 1）这个不是官方的关注点。WCDB 有 ORM 层，这个是重点。2）代码质量应该不会有问题。这完完全全就和用 WCDB 一样。3) 把 CMake 调好再合回主线大概是几小时的活。

**Comment by happyjiahan** [comment]
@fantasticfears  明白了，多谢。

**Comment by forconz** [comment]
C# 版本在哪里可以下载？
