### ISSUE TITLE
iOS 主键问题

### ISSUE THREAD

**Issue by colaicode** [Tencent/wcdb#140]
当使用**WCDB_PRIMARY_AUTO_INCREMENT**(Message, id)来定义主键时，报以下错误：

**[WCDB]Code:1555, Type:SQLiteGlobal, Msg:abort at 12 in [INSERT INTO message(mes_id,title,time,id) VALUES(?,?,?,?)]: UNIQUE constraint failed: message.id
[WCDB]Code:19, Type:SQLite, Tag:0, Op:5, ExtCode:1555, Msg:UNIQUE constraint failed: message.id, SQL:INSERT INTO message(mes_id,title,time,id) VALUES(?,?,?,?), Path:XXX**

打开数据库后发现id为0。

**Comment by colaicode** [comment]
经过测试，下面的代码可以实现主键自增长。
`
Message *message = [[Message alloc] init];
    **message.isAutoIncrement = YES;**
    message.title = @"Hello, WCDB!";
    message.time = [NSDate date];
    for (NSInteger i = 0; i<5; i++) {
        **BOOL result1 = [database insertObject:message
                                         into:@"message"];**
    }
`
但是为什么 **insertOrReplaceObject**就不行，必须要用**insertObject**

**Comment by colaicode** [comment]
经过测试，下面的代码可以实现主键自增长。
Message *message = [[Message alloc] init]; 
**message.isAutoIncrement = YES;** 
message.title = @"Hello, WCDB!"; 
message.time = [NSDate date]; 
for (NSInteger i = 0; i<5; i++) { 
      **BOOL result1 = [database insertObject:message into:@"message"];**
 }
但是为什么 insertOrReplaceObject就不行，必须要用insertObject

**Comment by RingoD** [comment]
自增是当前最大的主键+1，replace是用覆盖当前的主键，这两者是矛盾的。
