### ISSUE TITLE
Xcode9上使用CocoaPods做依赖，编译不通过！

### ISSUE THREAD

**Issue by daiweilai** [Tencent/wcdb#149]
'sqlcipher/sqlite3.h' file not found
应该是Podspec中的prepare_command没有正确执行

Xcode9.0 9A235
CocoaPods 1.3.1

**Comment by RingoD** [comment]
更新pod repo，然后清理一下pod缓存试试

**Comment by LiGuanWen** [comment]
直接自己在Podfile 里面添加这个
pod 'SQLCipher', '~> 3.4.1'

**Comment by RingoD** [comment]
@LiGuanWen  WCDB里已经包含了SQLCipher，而且是优化后的版本，不需要手动添加

**Comment by LiGuanWen** [comment]
@RingoD  但是我pod 1.0.4 就是会出现'sqlcipher/sqlite3.h' file not found 所以我添加了pod 'SQLCipher', '~> 3.4.1' 就可以解决。  我之前有按照你说的“更新pod repo，然后清理一下pod缓存试试” 试过了没用 
反正WCDB里已经包含了SQLCipher 我再pod SQLCipher 也没什么影响

**Comment by RingoD** [comment]
WCDB的SQLCipher是优化后的版本，你通过pod去拉的SQLCipher并不适合WCDB，无法得到好的性能和并发性。
可通过以下命令解决你的问题：
```
pod cache clean
pod repo update
```
