### ISSUE TITLE
表创建失败

### ISSUE THREAD

**Issue by pkjijie** [Tencent/wcdb#15]
声明类：
@interface TestWCDBObject : NSObject<WCTTableCoding>
@property int localID;
@property(retain) NSString *content;
@property(retain) NSDate *createTime;
@property(retain) NSDate *modifiedTime;
@property(assign) int unused; //You can just define the properties you need

WCDB_PROPERTY(localID)
WCDB_PROPERTY(content)
WCDB_PROPERTY(createTime)
WCDB_PROPERTY(modifiedTime)
@end

实现类：
@implementation TestWCDBObject
WCDB_IMPLEMENTATION(TestWCDBObject)
WCDB_SYNTHESIZE(TestWCDBObject, localID)
WCDB_SYNTHESIZE(TestWCDBObject, content)
WCDB_SYNTHESIZE(TestWCDBObject, createTime)
WCDB_SYNTHESIZE(TestWCDBObject, modifiedTime)

WCDB_PRIMARY(TestWCDBObject, localID)

WCDB_INDEX(TestWCDBObject, "_index", createTime)

@end

创建表：
 NSArray *cachPath = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory,NSUserDomainMask, YES);
    NSString *path = [cachPath objectAtIndex:0];
    WCTDatabase *database = [[WCTDatabase alloc] initWithPath:path];
    /*
     CREATE TABLE messsage (localID INTEGER PRIMARY KEY,
     content TEXT,
     createTime BLOB,
     modifiedTime BLOB)
     */
    BOOL result = [database createTableAndIndexesOfName:@"TestWCDBObject"
                                              withClass:TestWCDBObject.class];
    
    result 是NO

**Comment by RingoD** [comment]
按你的代码，你的path应该是一个已经存在的目录。
修改下path再试？

**Comment by pkjijie** [comment]
新建的空项目，在document根目录下，我看了模拟器的目录，是空的

**Comment by pkjijie** [comment]
**# 找到原因了， 我传入的path是Document根目录，**
/Users/Hi/Library/Developer/CoreSimulator/Devices/2C4E5FC7-362D-4103-8A87-22B0A54ADD25/data/Containers/Data/Application/877B0CD4-B930-4B53-9C60-F55B670C0777/Documents/
# **而创建WCTDatabase时使用 的path需要拼接上数据库名字：**
/Users/Hi/Library/Developer/CoreSimulator/Devices/2C4E5FC7-362D-4103-8A87-22B0A54ADD25/data/Containers/Data/Application/877B0CD4-B930-4B53-9C60-F55B670C0777/Documents/wcdb

**Comment by JohnnyB0Y** [comment]
发现了另一个原因，字段里使用了 ‘update’ ，也会创表失败。🤣🤣🤣

**Comment by RingoD** [comment]
@JohnnyB0Y  You should not use a SQLite reserved word.
