### ISSUE TITLE
更新后 报错

### ISSUE THREAD

**Issue by xiaoheiai4719** [Tencent/wcdb#150]
#include "parse.h" 提示这个文件找不到 不知道 有没有小哥哥 遇见过这样的错误。之前都是好好的能够使用。

**Comment by RingoD** [comment]
什么平台？使用什么方式接入的？WCDB版本多少？

**Comment by xiaoheiai4719** [comment]
通过cocopod 接入 ，更新到1.0.4版本.

**Comment by RingoD** [comment]
建议清理下pod cache后重试

**Comment by xiaoheiai4719** [comment]
清理完成 pod cache 后 还是会爆这个错误。

**Comment by RingoD** [comment]
pod cache clean WCDB --all
pod repo update

**Comment by xiaoheiai4719** [comment]
嗯 好了。谢谢您。
