### ISSUE TITLE
WCTError.h 报的错

### ISSUE THREAD

**Issue by loss99** [Tencent/wcdb#152]
Cannot initialize a parameter of type 'NSErrorUserInfoKey _Nonnull' (aka 'NSString *') with an rvalue of type 'NSNumber *'
Cannot initialize a parameter of type 'void (^ _Nonnull)(NSErrorUserInfoKey  _Nonnull __strong, id  _Nonnull __strong, BOOL * _Nonnull)' with an rvalue of type 'void (^)(NSNumber *__strong, __strong id, BOOL * _Nonnull)'

**Comment by loss99** [comment]
xcod 9

**Comment by loss99** [comment]
@RingoD

**Comment by RingoD** [comment]
更新到v1.0.4
