### ISSUE TITLE
WCDB头文件引入问题

### ISSUE THREAD

**Issue by gx2015** [Tencent/wcdb#153]
您好：我在对WCDB做二次封装的时候出现一个问题，OC的.h文件无法直接import WCDB.h文件，一旦引入就会出现编译错误（Xcode9）：说是WCDB模块无法编译，如果在.mm文件中引入的话就可以。但是这样的话，我就没法在.h文件中暴露一些接口了，因为有些接口的参数所表示的类型无法识别。本身是不想在太多的.mm文件中直接使用framework，所以想做一个简单的二次封装，提供一些常用的接口，把数据库操作都放在这个类里面。请问：有什么解决办法吗？

**Comment by RingoD** [comment]
https://github.com/Tencent/wcdb/wiki/ORM使用教程#隔离cpp代码

**Comment by gx2015** [comment]
这种是在model层隔离，我说的是在工具类层，我想再对常用CRUD操作 简单封装一下 但是不想在所有控制器中直接调用WCDB接口 所以想单独搞一个类 直接调用这个？

**Comment by RingoD** [comment]
两者有什么区别？工具类层也应该是只调用model层，而不是调用model层内部的WCDB

**Comment by gx2015** [comment]
比如说：我写了一个DbHelper的工具类，里面就是简单的封装了WCDB中常用的数据库操作，如表创建、插入、删除 ...差不多就是原封不动的搬过去了，这样做可以在其他controller中只用这个工具类调用数据库操作了而不用把相关controller文件改为.mm文件，在写工具类.h文件的时候接口就跟WCDB接口差不多，但是因为WCDB api接口中有的参数的类型需要引用相关头文件，那么我在工具类的.h文件定义的接口也要用到这个类型，但是WCDB在工具类.h文件中无法直接被import（只能在.mm文件中被引用） 所以这个类型就没法识别，出现编译错误，如果我在.h文件中直接#import <WCDB/WCDB.h> 编译器会报错：WCDB模块无法编译，或者是WCDB框架中的子头文件也没法直接import。
所以我想问一下：有没有办法直接在.h文件中直接#import <WCDB/WCDB.h>而不报错，或者说是我框架引入错误导致.h文件无法#import <WCDB/WCDB.h> ？虽然也可以用@class 或者 @protocol 关键字引入，但是这样的话，还不得直接#import <WCDB/WCDB.h>。
![1](https://user-images.githubusercontent.com/10735111/30956273-5ac29e20-a469-11e7-9fe3-2d7dde6a9af0.png)

**Comment by RingoD** [comment]
明白你的问题。你这里的封装不对，如果只是将WCDB的接口，如`insertObjects`等重写一遍到`ZQDbHelper`，那这个封装毫无意义。
正确的model应该是只对外提供需要的接口，而不是做一层桥接。
你可以看一下这个issue的讨论：https://github.com/Tencent/wcdb/issues/135

**Comment by gx2015** [comment]
嗯 我明白意思了。 多谢！！！

**Comment by gx2015** [comment]
还有一个问题请教：你说的这个model层具体指什么？是定义的数据模型类还是操作数据模型的类？

**Comment by RingoD** [comment]
Model View Controller

**Comment by gx2015** [comment]
。。。
