### ISSUE TITLE
Android版本1.0.3，关闭DB后再开，偶现崩溃

### ISSUE THREAD

**Issue by edongyu** [Tencent/wcdb#155]
Android版本1.0.3， 先用wcdb的SQLiteOpenHelper .close() 方法关闭数据库，再通过下面代码获取Database，setTraceCallback方法偶现崩溃

代码如下：

`
if (mDB == null || !mDB.isOpen()) {

    mDB = getWritableDatabase();
    mDB.setTraceCallback(...);

}
`

崩溃日志：
`java.lang.IllegalStateException: The database '/data/data/**/databases/eacc8e6f7e0d.db' is not open.
	at com.tencent.wcdb.database.SQLiteDatabase.I(SourceFile:2421)
	at com.tencent.wcdb.database.SQLiteDatabase.a(SourceFile:2219)
	...
`

按说，getWritableDatabase() 已经open db了，为什么还会有这种异常呢？请帮忙看看！

**Comment by John-He-928** [comment]
这边没有办法复现，偶现的话像是多线程同步问题？
请问有没有具体复现方法？

`setTraceCallback` 检查的是 db 对象里的 `mConnectionPoolLocked` 成员，能调试跟踪一下？

**Comment by edongyu** [comment]
我这边也无法复现，从崩溃日中看到的，应该跟多线程有关，我这边用法是每个表对应一个DBHelper，里面用getWritableDatabase() 获取一个mDB， 可能是在某一个表close时，其他表去使用了产生的异常，目前是加了try catch
