### ISSUE TITLE
xcode9编译失败

### ISSUE THREAD

**Issue by wzboy049** [Tencent/wcdb#156]
旧项目是xcode8写的, 用xcode9编译失败,提示 sqlite3_rekey 方法找不到

**Comment by RingoD** [comment]
`sqlite3_rekey`是sqlcipher的代码，是不是你接入的时候没有按照教程联入sqlcipher？

麻烦贴一下完整的错误信息，以及你的接入方式（源码、cocoapods还是carthage）

**Comment by RingoD** [comment]
贴一下完整的错误信息

**Comment by wzboy049** [comment]
sorry, 又看了一下代码,不是你们的锅,出错不在你们, 我不好意思贴图了, 耽误您时间了,抱歉

**Comment by will0321** [comment]
我也是，有两个错误信息。一个错误如信如下：WCTError.mm:84:40: error: cannot initialize a parameter of type 'NSErrorUserInfoKey _Nonnull' (aka 'NSString *') with an rvalue of type 'NSNumber *'
第二个错误信息如下：WCTError.mm:71:54: error: cannot initialize a parameter of type 'void (^ _Nonnull)(NSErrorUserInfoKey  _Nonnull __strong, id  _Nonnull __strong, BOOL * _Nonnull)' with an rvalue of type 'void (^)(NSNumber *__strong, __strong id, BOOL * _Nonnull)'
    [self.userInfo enumerateKeysAndObjectsUsingBlock:^(NSNumber *key, id obj, BOOL *_Nonnull unused) {

**Comment by RingoD** [comment]
@will0321 更新到WCDB v1.0.4
