### ISSUE TITLE
iOS 版本使用sql语句等问题

### ISSUE THREAD

**Issue by huchpi0226** [Tencent/wcdb#158]
研究了iOS和android的版本，想问问
1.为什么iOS版本不能直接运行sql语句，而android版本可以？我们iOS客户端数据库很多都没有建model，如果都要先建model，iOS客户端改造会很大。有类似android那样接口或者fmdb直接用sql语句吗？
2.android版本引入wcdb改造小也很方便，但是iOS有orm,winq,.m改成.mm等等，实际上iOS引入的改造量不小，成本大。有考虑过吗？

**Comment by RingoD** [comment]
iOS和Android版本的WCDB是不同的设计。由于Google提供的SQLite还算好用，并且大家都比较习惯，因此Android版的WCDB基本与其保持一致。而iOS侧并没有现成的足够好用、易用的数据库组件，因此其是全新的设计。

iOS端大部分主流的数据库组件都是以更为先进的ORM进行数据绑定，如CoreData、Realm等等，WCDB也不例外。

WCDB的ORM、WINQ等中包含了大量的易用性、性能等的优化。如果直接使用字符串的SQL进行操作，在架构上会有不少功能需要对其进行兼容（如Transaction的判断等）。更重要的是，这将无法得到我们的许多特性和性能优化。因此，如果只是通过字符串的SQL操作WCDB，这并不值当。

为类和表进行建模，可以很大程度上优化代码结构、提高可维护性、减少出错的风险，即便不接入WCDB，这也是很值得去做的代码重构。

**Comment by huchpi0226** [comment]
不过很多第三发库，两个版本接口一般都会类似，但wcdb差别好大。
那是不是iOS版本就只能使用ORM,WINQ来处理数据？
iOS和Android版本的WCDB，benchmark性能数据也差别大，以后会统一吗？

**Comment by RingoD** [comment]
1. 一般来说，iOS开发者不会去考虑Android侧的接口和实现，Android也是同样。因此我们更关注易用、符合平台习惯，而不是强行统一。
2. 是的，iOS必须使用ORM、WINQ等。建议你先进行一些尝试，上手后会发现性能和易用上有质的提升，业务层的代码量也可以大幅度减少
3. 和1.一样

**Comment by huchpi0226** [comment]
好的，谢谢
