### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by alexlee002** [Tencent/wcdb#16]
如果可能， 希望能在readme中增加官方的性能测试数据， 主要是以下三点：
* 多并发数据库操作。 WCDB是支持多并发读写， 文档上说是线程安全的。 希望增加一下WCDB模式下频繁的多并发读写和传统的1写N读模式的性能对比(包括漏读和脏读的几率)？
* WINQ性能。我去年也开源了一个小工具(无耻的蹭热点做个广告🙈:[patchwork](https://github.com/alexlee002/patchwork)),  里边ActiveRecord模块也实现了类似WINQ的操作,   但没有用c++运算符重载方式实现(考虑过， 但是c++技能已经生疏了， 特别是c++11之后的)， 不得不说， 运算符重载的实现方式对于使用者来说很简洁。 但是用函数拼装sql, 有一定的性能损耗(winq的运算符重载是const的，也就是说， 在这过程中会产生大量临时对象)。 不知道有没有一些稍微复杂sql操作的性能测试数据？
* SQLCipher。 我们之前做过测试， sqlcipher会带来比较大的性能影响(表的行数越多，两者区别越小， 但是也几乎有40%左右的损耗 -- 但是我们没有把sqlcipher和sqlite编译在一起)，不知道WCDB有没有这方面的官方测试？

**Comment by RingoD** [comment]
* 线程安全是指WCTDatabase、WCTTable、WCTransaction的接口调用时，不需要考虑不同线程时序造成的问题。但在具体实现上，依然是1写N读并行，多写串行。
* SQL的字符串都不长，这些性能损耗和SQL的编译以及I/O读写比起来微不足道。当然，临时对象确实是一个浪费，我后续有计划优化（类似字符串池）。
* 理论上不加密的SQLCipher和SQLite没有明显差别。现在的CPU也都对大多数加密算法有专门的指令集处理。这部分性能比较我建议直接去看SQLCipher的benchmark。

当然，理论分析不如数据直观。project里有benchmark的target，但非常粗糙。我们也在benchmark里打了TODO warning，后续会优先完善这部分，也欢迎你来pr。

**Comment by alexlee002** [comment]
哦， 对于sqlcipher的差别， 我指的是加密之后的性能损耗。

**Comment by John-He-928** [comment]
SQLCipher加解密性能主要取决于加密库（OpenSSL Crypto / CommonCipher）的实现和编译选项，损耗比较大的是打开DB后首次执行SQL语句，需要做密钥生成，比较耗时，后续损耗应该不会有40%这么夸张。

SQLCipher Benchmark会补上的，也欢迎贡献benchmark相关代码

**Comment by alexlee002** [comment]
@John-He-928 @RingoD : 测试代码已经找不到了， 貌似应该是参照[这篇文章](http://blog.devzeng.com/blog/encrypt-sqlite-with-sqlcipher.html)来搭建的环境， Mac系统下测试。

当时的测试结果， 在数据量少的时候， 不加密insert一条大概2 ~ 3ms， 加密大概10 ~ 15ms， 随着数据量增多， 耗时越来越长， 但是两者差距逐渐减少。 大概在20万条数据左右， 不加密insert一条大概25+ms左右， 加密大概30+ms (大概数字是这个范围， 准确的记不住了)。 数据库文件大概在1个多G到2G的样子， 两者大小大概相差100M左右？(这个记不住了， 只是文件大小的差距没有时间差距那么大)。

**Comment by lianchengjiang** [comment]
据https://github.com/ibireme/YYCache里面提到，SQLite 官网最新的sqlite会比iOS自带的libsqlite3.dylib性能提升最高 1.5～3 倍，有没有考虑使用最新的sqlite呢？ @RingoD

**Comment by RingoD** [comment]
@lianchengjiang  我还没有细看YYCache的benchmark。但WCDB没有使用系统SQLite。
目前WCDB使用的SQLCipher基于的SQLite版本是3.15.2，比YYCache提到的3.9.2高。后续我们也会不定期地升级SQLCipher和SQLite的版本。

性能是一方面的考虑，另一方面是，不同系统会对应不同的SQLite版本，他们的功能和性能各不相同，会给开发带来麻烦。

**Comment by alexlee002** [comment]
@RingoD 建议提供一个对sqlcipher和sqlite修改的changelog.

**Comment by RingoD** [comment]
iOS benchmark请参考：https://github.com/Tencent/wcdb/wiki/性能数据与Benchmark
