### ISSUE TITLE
iOS无法打开存在bundle里的数据库

### ISSUE THREAD

**Issue by flyico** [Tencent/wcdb#160]
对数据库只有读的操作，把数据库预先准备好打入bundle里，却发现真机上无法打开，是不支持bundle里的数据库吗？

**Comment by RingoD** [comment]
麻烦提供一下错误日志

**Comment by flyico** [comment]
[WCDB][DEBUG]Code:14, Type:SQLiteGlobal, Msg:cannot open file at line 4384 of [bbd85d235f]
[WCDB][DEBUG]Code:14, Type:SQLiteGlobal, Msg:os_unix.c:4384: (1) open(/var/containers/Bundle/Application/97A66197-1365-4970-A3BA-4FA17BAEA263/TDCheckin.app/core-shm) - 
[WCDB][DEBUG]Code:14, Type:SQLiteGlobal, Msg:unable to open database file
[WCDB][ERROR]Code:14, Type:SQLite, Tag:0, Op:3, ExtCode:14, Msg:unable to open database file, SQL:SELECT id,name FROM song_info, Path:/var/containers/Bundle/Application/97A66197-1365-4970-A3BA-4FA17BAEA263/TDCheckin.app/core

我检查了下  数据库相关代3个文件core  core-shm  core-wal都已经打到bundle里了

**Comment by RingoD** [comment]
感谢反馈，WCDB 设计之初没有考虑 Readonly database 的支持，现在看来还是有这个需求的。

已经将代码加到 master 分支了，更新后可用。如有其他问题可进一步反馈。

如果是使用 cocoapods 或者 carthage 的话，需要指定 commit 或 branch 进行更新，具体方法可用自行 google。

**Comment by flyico** [comment]
@RingoD 你好，我试了修改过的版本，Podfile里指定了commit，查看了代码确实已更新，但是真机上仍然打不开数据库。

[WCDB][DEBUG]Code:14, Type:SQLiteGlobal, Msg:cannot open file at line 4384 of [bbd85d235f]
[WCDB][DEBUG]Code:14, Type:SQLiteGlobal, Msg:os_unix.c:4384: (1) open(/var/containers/Bundle/Application/9460FBC1-0BB3-46C0-B02D-1514613030D7/TDCheckin.app/core-shm) - 
[WCDB][DEBUG]Code:14, Type:SQLiteGlobal, Msg:unable to open database file
[WCDB][ERROR]Code:14, Type:SQLite, Tag:0, Op:3, ExtCode:14, Msg:unable to open database file, SQL:SELECT id,name FROM song_info, Path:/var/containers/Bundle/Application/9460FBC1-0BB3-46C0-B02D-1514613030D7/TDCheckin.app/core

**Comment by RingoD** [comment]
看日志是文件不存在，路径错了，或者文件没有打包进bundle里

**Comment by zzcshao** [comment]
[1.0.5] 真机无法打开存在bundle里的数据库 , 在模拟器上可以正常打开

**Comment by zzcshao** [comment]
错误日志如下:
2017-11-09 12:27:52.579851+0800 QianTuanShe[72863:9000210] +[WCDBManager shareDatabaseWithUserid:]_block_invoke 第46行 ------->[WCDB]Code:14, Type:SQLiteGlobal, Msg:cannot open file at line 4384 of [bbd85d235f]
2017-11-09 12:27:52.580043+0800 QianTuanShe[72863:9000210] +[WCDBManager shareDatabaseWithUserid:]_block_invoke 第46行 ------->[WCDB]Code:14, Type:SQLiteGlobal, Msg:os_unix.c:4384: (0) open(/var/containers/Bundle/Application/C3F31B06-2A25-4299-8F3E-CECC9A3E237C/QianTuanShe.app/SCHOOL.sqlite-shm) - 
2017-11-09 12:27:52.580242+0800 QianTuanShe[72863:9000210] +[WCDBManager shareDatabaseWithUserid:]_block_invoke 第46行 ------->[WCDB]Code:14, Type:SQLiteGlobal, Msg:unable to open database file
2017-11-09 12:27:52.580608+0800 QianTuanShe[72863:9000210] +[WCDBManager shareDatabaseWithUserid:]_block_invoke 第46行 ------->[WCDB]Code:14, Type:SQLite, Msg:unable to open database file, Tag:0, ExtCode:14, SQL:SELECT school_name,school_pro_id,school_schooltype_id,school_id,province_name,province_id FROM SCHOOLLISTTABLE WHERE (province_name LIKE '%湖南%'), Path:/var/containers/Bundle/Application/C3F31B06-2A25-4299-8F3E-CECC9A3E237C/QianTuanShe.app/SCHOOL.sqlite, Op:3

**Comment by RingoD** [comment]
@zzcshao  你的db是 wal 的。wal 数据库不能用于只读。需要配置 journal_mode 为 normal

**Comment by Archer353** [comment]
> @zzcshao 你的db是 wal 的。wal 数据库不能用于只读。需要配置 journal_mode 为 normal

guard let bundleDBPath = Bundle.main.path(forResource: "DPBundleDB", ofType: "db") else {return}
bundleDatabase_p_DP = Database(withPath: bundleDBPath)
        bundleDatabase_p_DP?.setConfig(named: "journal_mode", with: { (handle) in
            try handle.exec(StatementPragma().pragma(.journalMode, to: "NORMAL"))
        })
您好，我这样设置了journal_mode，还是不能查询bundle的数据库，请问我该如何修改？

**Comment by Archer353** [comment]
> [1.0.5] 真机无法打开存在bundle里的数据库 , 在模拟器上可以正常打开

您好，请问你后来如何修改的，我也遇到了相同的问题

**Comment by leonylcatwork** [comment]
所以有人有解决方法吗？

**Comment by MorningStarJ** [comment]
> > [1.0.5] 真机无法打开存在bundle里的数据库 , 在模拟器上可以正常打开
> 
> 您好，请问你后来如何修改的，我也遇到了相同的问题
请问您最后解决了吗？

**Comment by zzcshao** [comment]
> > > [1.0.5] 真机无法打开存在bundle里的数据库 , 在模拟器上可以正常打开
> > 
> > 
> > 您好，请问你后来如何修改的，我也遇到了相同的问题
> 
> 请问您最后解决了吗？

不太记得当初是怎么解决的了，我已经转行了。

**Comment by leonylcatwork** [comment]
> > > > [1.0.5] 真机无法打开存在bundle里的数据库 , 在模拟器上可以正常打开
> > > 
> > > 
> > > 您好，请问你后来如何修改的，我也遇到了相同的问题
> > 
> > 
> > 请问您最后解决了吗？
> 
> 不太记得当初是怎么解决的了，我已经转行了。

在打包进 bundle 之前就必须把 Journal Mode 改为 NORMAL。因为打包进bundle后就是只读了，不能改 Journal Mode。

**Comment by MorningStarJ** [comment]
> > > > > [1.0.5] 真机无法打开存在bundle里的数据库 , 在模拟器上可以正常打开
> > > > 
> > > > 
> > > > 您好，请问你后来如何修改的，我也遇到了相同的问题
> > > 
> > > 
> > > 请问您最后解决了吗？
> > 
> > 
> > 不太记得当初是怎么解决的了，我已经转行了。
> 
> 在打包进 bundle 之前就必须把 Journal Mode 改为 NORMAL。因为打包进bundle后就是只读了，不能改 Journal Mode。

感谢

**Comment by shiyj** [comment]
如果无法修改db，或者需要对比db的md5来和服务器同步，也可以通过替换默认的basic config的模式来达到只读模式：

```
            _wcdb = [[WCTDatabase alloc] initWithPath:[self dbPath]];
            if ([self isReadonlyDB]) {
                NSString *name = [WCTDatabase DefaultBasicConfigName];
                
                WCDB::Config config = [](std::shared_ptr<WCDB::Handle> &handle, WCDB::Error &error) -> bool {
                    return true;
                };
                [_wcdb setConfig:config forName:name];
            }
```

**Comment by tanxiuguang** [comment]
swift 版本真机还是不可以，模拟器上能正常运行
[WCDB][ERROR] Code:systemCall(513), Type:SystemCall, Path:/var/containers/Bundle/Application/17CFC729-A8E8-45D9-A71B-0D0B0201168A/rare.app/rare.db,Message:您没有将文件“rare.db”存储到文件夹“xx”中的权限。,Operation:262
Unexpected error: Code:systemCall(513), Type:SystemCall, Path:/var/containers/Bundle/Application/17CFC729-A8E8-45D9-A71B-0D0B0201168A/rare.app/rare.db,Message:您没有将文件“rare.db”存储到文件夹“xx”中的权限。,Operation:262.

262的错误代码 应该是这行代码产生的
```
do {
            try fileManager.setAttributes(attributes, ofItemAtPath: path)
        } catch let error as NSError {
            throw Error.reportSystemCall(operation: .setAttributes,
                                         path: path,
                                         errno: error.code,
                                         message: error.localizedDescription)
        }
```
把这段代码注释掉会运行到下面
```
guard !handle.isReadonly else {
                let handleStatement = try handle.prepare(CommonStatement.getJournalMode)
                try handleStatement.step()
                let journalMode: String = handleStatement.columnValue(atIndex: 0)
                try handleStatement.finalize()
                assert(journalMode.caseInsensitiveCompare("WAL") == ComparisonResult.orderedSame,
                       "It is not possible to open read-only WAL databases.")
                return
            }
```
但是我查看我的db file的JournalMode已经设置成delete，为什么这里还是WAL？
handle.isReadonly 这个判断是判断db文件的什么属性？看代码没看明白

**Comment by MorningStarJ** [comment]
> swift 版本真机还是不可以，模拟器上能正常运行
> [WCDB][ERROR] Code:systemCall(513), Type:SystemCall, Path:/var/containers/Bundle/Application/17CFC729-A8E8-45D9-A71B-0D0B0201168A/rare.app/rare.db,Message:您没有将文件“rare.db”存储到文件夹“xx”中的权限。,Operation:262
> Unexpected error: Code:systemCall(513), Type:SystemCall, Path:/var/containers/Bundle/Application/17CFC729-A8E8-45D9-A71B-0D0B0201168A/rare.app/rare.db,Message:您没有将文件“rare.db”存储到文件夹“xx”中的权限。,Operation:262.
> 
> 262的错误代码 应该是这行代码产生的
> 
> ```
> do {
>             try fileManager.setAttributes(attributes, ofItemAtPath: path)
>         } catch let error as NSError {
>             throw Error.reportSystemCall(operation: .setAttributes,
>                                          path: path,
>                                          errno: error.code,
>                                          message: error.localizedDescription)
>         }
> ```
> 
> 把这段代码注释掉会运行到下面
> 
> ```
> guard !handle.isReadonly else {
>                 let handleStatement = try handle.prepare(CommonStatement.getJournalMode)
>                 try handleStatement.step()
>                 let journalMode: String = handleStatement.columnValue(atIndex: 0)
>                 try handleStatement.finalize()
>                 assert(journalMode.caseInsensitiveCompare("WAL") == ComparisonResult.orderedSame,
>                        "It is not possible to open read-only WAL databases.")
>                 return
>             }
> ```
> 
> 但是我查看我的db file的JournalMode已经设置成delete，为什么这里还是WAL？
> handle.isReadonly 这个判断是判断db文件的什么属性？看代码没看明白

如果是存在于Bundle 的数据库，移动到沙盒，对 Bundle 只有只读权限

**Comment by tanxiuguang** [comment]
> > swift 版本真机还是不可以，模拟器上能正常运行
> > [WCDB][ERROR] Code:systemCall(513), Type:SystemCall, Path:/var/containers/Bundle/Application/17CFC729-A8E8-45D9-A71B-0D0B0201168A/rare.app/rare.db,Message:您没有将文件“rare.db”存储到文件夹“xx”中的权限。,Operation:262
> > Unexpected error: Code:systemCall(513), Type:SystemCall, Path:/var/containers/Bundle/Application/17CFC729-A8E8-45D9-A71B-0D0B0201168A/rare.app/rare.db,Message:您没有将文件“rare.db”存储到文件夹“xx”中的权限。,Operation:262.
> > 262的错误代码 应该是这行代码产生的
> > ```
> > do {
> >             try fileManager.setAttributes(attributes, ofItemAtPath: path)
> >         } catch let error as NSError {
> >             throw Error.reportSystemCall(operation: .setAttributes,
> >                                          path: path,
> >                                          errno: error.code,
> >                                          message: error.localizedDescription)
> >         }
> > ```
> > 
> > 
> > 把这段代码注释掉会运行到下面
> > ```
> > guard !handle.isReadonly else {
> >                 let handleStatement = try handle.prepare(CommonStatement.getJournalMode)
> >                 try handleStatement.step()
> >                 let journalMode: String = handleStatement.columnValue(atIndex: 0)
> >                 try handleStatement.finalize()
> >                 assert(journalMode.caseInsensitiveCompare("WAL") == ComparisonResult.orderedSame,
> >                        "It is not possible to open read-only WAL databases.")
> >                 return
> >             }
> > ```
> > 
> > 
> > 但是我查看我的db file的JournalMode已经设置成delete，为什么这里还是WAL？
> > handle.isReadonly 这个判断是判断db文件的什么属性？看代码没看明白
> 
> 如果是存在于Bundle 的数据库，移动到沙盒，对 Bundle 只有只读权限

移动到沙盒要做很多处理，数据库文件有点大还有可能更新，每次启动都要拷贝一次太浪费，加上版本号等控制机制有点太麻烦

**Comment by MorningStarJ** [comment]
> > > swift 版本真机还是不可以，模拟器上能正常运行
> > > [WCDB][ERROR] Code:systemCall(513), Type:SystemCall, Path:/var/containers/Bundle/Application/17CFC729-A8E8-45D9-A71B-0D0B0201168A/rare.app/rare.db,Message:您没有将文件“rare.db”存储到文件夹“xx”中的权限。,Operation:262
> > > Unexpected error: Code:systemCall(513), Type:SystemCall, Path:/var/containers/Bundle/Application/17CFC729-A8E8-45D9-A71B-0D0B0201168A/rare.app/rare.db,Message:您没有将文件“rare.db”存储到文件夹“xx”中的权限。,Operation:262.
> > > 262的错误代码 应该是这行代码产生的
> > > ```
> > > do {
> > >             try fileManager.setAttributes(attributes, ofItemAtPath: path)
> > >         } catch let error as NSError {
> > >             throw Error.reportSystemCall(operation: .setAttributes,
> > >                                          path: path,
> > >                                          errno: error.code,
> > >                                          message: error.localizedDescription)
> > >         }
> > > ```
> > > 
> > > 
> > > 把这段代码注释掉会运行到下面
> > > ```
> > > guard !handle.isReadonly else {
> > >                 let handleStatement = try handle.prepare(CommonStatement.getJournalMode)
> > >                 try handleStatement.step()
> > >                 let journalMode: String = handleStatement.columnValue(atIndex: 0)
> > >                 try handleStatement.finalize()
> > >                 assert(journalMode.caseInsensitiveCompare("WAL") == ComparisonResult.orderedSame,
> > >                        "It is not possible to open read-only WAL databases.")
> > >                 return
> > >             }
> > > ```
> > > 
> > > 
> > > 但是我查看我的db file的JournalMode已经设置成delete，为什么这里还是WAL？
> > > handle.isReadonly 这个判断是判断db文件的什么属性？看代码没看明白
> > 
> > 
> > 如果是存在于Bundle 的数据库，移动到沙盒，对 Bundle 只有只读权限
> 
> 移动到沙盒要做很多处理，数据库文件有点大还有可能更新，每次启动都要拷贝一次太浪费，加上版本号等控制机制有点太麻烦

那似乎你只能换个库了

**Comment by MorningStarJ** [comment]
> > > swift 版本真机还是不可以，模拟器上能正常运行
> > > [WCDB][ERROR] Code:systemCall(513), Type:SystemCall, Path:/var/containers/Bundle/Application/17CFC729-A8E8-45D9-A71B-0D0B0201168A/rare.app/rare.db,Message:您没有将文件“rare.db”存储到文件夹“xx”中的权限。,Operation:262
> > > Unexpected error: Code:systemCall(513), Type:SystemCall, Path:/var/containers/Bundle/Application/17CFC729-A8E8-45D9-A71B-0D0B0201168A/rare.app/rare.db,Message:您没有将文件“rare.db”存储到文件夹“xx”中的权限。,Operation:262.
> > > 262的错误代码 应该是这行代码产生的
> > > ```
> > > do {
> > >             try fileManager.setAttributes(attributes, ofItemAtPath: path)
> > >         } catch let error as NSError {
> > >             throw Error.reportSystemCall(operation: .setAttributes,
> > >                                          path: path,
> > >                                          errno: error.code,
> > >                                          message: error.localizedDescription)
> > >         }
> > > ```
> > > 
> > > 
> > > 把这段代码注释掉会运行到下面
> > > ```
> > > guard !handle.isReadonly else {
> > >                 let handleStatement = try handle.prepare(CommonStatement.getJournalMode)
> > >                 try handleStatement.step()
> > >                 let journalMode: String = handleStatement.columnValue(atIndex: 0)
> > >                 try handleStatement.finalize()
> > >                 assert(journalMode.caseInsensitiveCompare("WAL") == ComparisonResult.orderedSame,
> > >                        "It is not possible to open read-only WAL databases.")
> > >                 return
> > >             }
> > > ```
> > > 
> > > 
> > > 但是我查看我的db file的JournalMode已经设置成delete，为什么这里还是WAL？
> > > handle.isReadonly 这个判断是判断db文件的什么属性？看代码没看明白
> > 
> > 
> > 如果是存在于Bundle 的数据库，移动到沙盒，对 Bundle 只有只读权限
> 
> 移动到沙盒要做很多处理，数据库文件有点大还有可能更新，每次启动都要拷贝一次太浪费，加上版本号等控制机制有点太麻烦

那似乎你只能换其他框架了，我曾尝试配置Bundle中的配置 journal_mode 为 normal，不知道是不是使用姿势的问题，无法修改也无法解决，感觉可能还是Bundle 写入权限的问题，移动到沙盒即可解决问题。

**Comment by GodLiek** [comment]
> > > > swift 版本真机还是不可以，模拟器上能正常运行
> > > > [WCDB][ERROR] Code:systemCall(513), Type:SystemCall, Path:/var/containers/Bundle/Application/17CFC729-A8E8-45D9-A71B-0D0B0201168A/rare.app/rare.db,Message:您没有将文件“rare.db”存储到文件夹“xx”中的权限。,Operation:262
> > > > Unexpected error: Code:systemCall(513), Type:SystemCall, Path:/var/containers/Bundle/Application/17CFC729-A8E8-45D9-A71B-0D0B0201168A/rare.app/rare.db,Message:您没有将文件“rare.db”存储到文件夹“xx”中的权限。,Operation:262.
> > > > 262的错误代码 应该是这行代码产生的
> > > > ```
> > > > do {
> > > >             try fileManager.setAttributes(attributes, ofItemAtPath: path)
> > > >         } catch let error as NSError {
> > > >             throw Error.reportSystemCall(operation: .setAttributes,
> > > >                                          path: path,
> > > >                                          errno: error.code,
> > > >                                          message: error.localizedDescription)
> > > >         }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 把这段代码注释掉会运行到下面
> > > > ```
> > > > guard !handle.isReadonly else {
> > > >                 let handleStatement = try handle.prepare(CommonStatement.getJournalMode)
> > > >                 try handleStatement.step()
> > > >                 let journalMode: String = handleStatement.columnValue(atIndex: 0)
> > > >                 try handleStatement.finalize()
> > > >                 assert(journalMode.caseInsensitiveCompare("WAL") == ComparisonResult.orderedSame,
> > > >                        "It is not possible to open read-only WAL databases.")
> > > >                 return
> > > >             }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 但是我查看我的db file的JournalMode已经设置成delete，为什么这里还是WAL？
> > > > handle.isReadonly 这个判断是判断db文件的什么属性？看代码没看明白
> > > 
> > > 
> > > 如果是存在于Bundle 的数据库，移动到沙盒，对 Bundle 只有只读权限
> > 
> > 
> > 移动到沙盒要做很多处理，数据库文件有点大还有可能更新，每次启动都要拷贝一次太浪费，加上版本号等控制机制有点太麻烦
> 
> 那似乎你只能换其他框架了，我曾尝试配置Bundle中的配置 journal_mode 为 normal，不知道是不是使用姿势的问题，无法修改也无法解决，感觉可能还是Bundle 写入权限或是数据库配置的问题，移动到沙盒即可解决问题。

我这也是遇到了相同的问题，"[WCDB][ERROR] Code:systemCall(513), Type:SystemCall, Path:/var/containers/Bundle/Application/5677E003-4E1E-4F1B-AEB2-89C2708597F1/xxx.app/country.db,Operation:262,Message:You don’t have permission to save the file “xxx.db” in the folder “xxx”."，但是只有WCDB.swift会有这样的错误，OC版的WCDB可以正常打开
