### ISSUE TITLE
Could not build module 'WCDB'

### ISSUE THREAD

**Issue by koreadragon** [Tencent/wcdb#161]
用cocoapods安装完，导入报这个错

**Comment by koreadragon** [comment]
我是直接导入到pch文件中的，所以导致报错，直接在新建类中导入就好了

**Comment by RingoD** [comment]
WCDB是Objective-C++代码，不能直接在pch里导入

**Comment by koreadragon** [comment]
@RingoD 那么我在其他地方引入使用时，每次引入新文件都需要把`.m`文件改成`.mm`文件？感觉这样好麻烦啊，有没有其他解决办法，谢谢！

**Comment by RingoD** [comment]
https://github.com/Tencent/wcdb/wiki/ORM使用教程#隔离cpp代码
