### ISSUE TITLE
WCDB/WCDB.h' file not found

### ISSUE THREAD

**Issue by BoYuanZjq** [Tencent/wcdb#164]
我在最新的xcode Version 9.0.1 (9A1004)中运行demo ,报错，是怎么回事

**Comment by RingoD** [comment]
请严格按照教程安装：https://github.com/Tencent/wcdb/wiki#安装
如有进一步问题，请描述你的安装方式，并贴出完整的错误日志

**Comment by RingoD** [comment]
no reply
