### ISSUE TITLE
一次性读取大量数据，每次都出现警告信息：Window is full: requested allocation 409 bytes, free space 216 bytes, window size 2097152 bytes

### ISSUE THREAD

**Issue by lihywh** [Tencent/wcdb#165]
原因：由于业务需要必须一次性读入数万条数据，每次都有此警告信息。
问题：
1.是否能够通过配置避免此警告？
2.此警告是否影响读取结果？

10-25 18:34:27.706: W/WCDB.CursorWindow(12799): Window is full: requested allocation 409 bytes, free space 216 bytes, window size 2097152 bytes
10-25 18:34:27.706: W/WCDB.SQLiteConnection(12799): Failed allocating 409 bytes for blob at 15733,6, error=-12
10-25 18:34:28.129: W/WCDB.CursorWindow(12799): Window is full: requested allocation 661 bytes, free space 164 bytes, window size 2097152 bytes
10-25 18:34:28.129: W/WCDB.SQLiteConnection(12799): Failed allocating 661 bytes for blob at 17491,6, error=-12
10-25 18:34:28.565: W/WCDB.CursorWindow(12799): Window is full: requested allocation 661 bytes, free space 428 bytes, window size 2097152 bytes
10-25 18:34:28.565: W/WCDB.SQLiteConnection(12799): Failed allocating 661 bytes for blob at 19000,6, error=-12
10-25 18:34:28.948: W/WCDB.CursorWindow(12799): Window is full: requested allocation 2005 bytes, free space 1424 bytes, window size 2097152 bytes
10-25 18:34:28.948: W/WCDB.SQLiteConnection(12799): Failed allocating 2005 bytes for blob at 20359,6, error=-12
10-25 18:34:29.408: W/WCDB.CursorWindow(12799): Window is full: requested allocation 144 bytes, free space 11 bytes, window size 2097152 bytes
10-25 18:34:29.989: W/WCDB.CursorWindow(12799): Window is full: requested allocation 1165 bytes, free space 200 bytes, window size 2097152 bytes
10-25 18:34:29.989: W/WCDB.SQLiteConnection(12799): Failed allocating 1165 bytes for blob at 23116,6, error=-12
10-25 18:34:30.369: W/WCDB.CursorWindow(12799): Window is full: requested allocation 144 bytes, free space 87 bytes, window size 2097152 bytes
10-25 18:34:30.788: W/WCDB.CursorWindow(12799): Window is full: requested allocation 745 bytes, free space 332 bytes, window size 2097152 bytes
10-25 18:34:30.788: W/WCDB.SQLiteConnection(12799): Failed allocating 745 bytes for blob at 25319,6, error=-12
10-25 18:34:31.152: W/WCDB.CursorWindow(12799): Window is full: requested allocation 913 bytes, free space 272 bytes, window size 2097152 bytes
10-25 18:34:31.152: W/WCDB.SQLiteConnection(12799): Failed allocating 913 bytes for blob at 26894,6, error=-12
10-25 18:34:31.587: W/WCDB.CursorWindow(12799): Window is full: requested allocation 1165 bytes, free space 912 bytes, window size 2097152 bytes
10-25 18:34:31.587: W/WCDB.SQLiteConnection(12799): Failed allocating 1165 bytes for blob at 28300,6, error=-12
10-25 18:34:32.090: W/WCDB.CursorWindow(12799): Window is full: requested allocation 493 bytes, free space 56 bytes, window size 2097152 bytes
10-25 18:34:32.090: W/WCDB.SQLiteConnection(12799): Failed allocating 493 bytes for blob at 29758,6, error=-12
10-25 18:34:32.602: W/WCDB.CursorWindow(12799): Window is full: requested allocation 1333 bytes, free space 1308 bytes, window size 2097152 bytes
10-25 18:34:32.602: W/WCDB.SQLiteConnection(12799): Failed allocating 1333 bytes for blob at 31221,6, error=-12
10-25 18:34:33.005: W/WCDB.CursorWindow(12799): Window is full: requested allocation 144 bytes, free space 55 bytes, window size 2097152 bytes
10-25 18:34:33.393: W/WCDB.CursorWindow(12799): Window is full: requested allocation 661 bytes, free space 480 bytes, window size 2097152 bytes
10-25 18:34:33.393: W/WCDB.SQLiteConnection(12799): Failed allocating 661 bytes for blob at 33778,6, error=-12
10-25 18:34:33.779: W/WCDB.CursorWindow(12799): Window is full: requested allocation 745 bytes, free space 232 bytes, window size 2097152 bytes
10-25 18:34:33.779: W/WCDB.SQLiteConnection(12799): Failed allocating 745 bytes for blob at 35055,6, error=-12
10-25 18:34:34.183: W/WCDB.CursorWindow(12799): Window is full: requested allocation 493 bytes, free space 320 bytes, window size 2097152 bytes
10-25 18:34:34.183: W/WCDB.SQLiteConnection(12799): Failed allocating 493 bytes for blob at 36199,6, error=-12
10-25 18:34:34.568: W/WCDB.CursorWindow(12799): Window is full: requested allocation 829 bytes, free space 104 bytes, window size 2097152 bytes
10-25 18:34:34.569: W/WCDB.SQLiteConnection(12799): Failed allocating 829 bytes for blob at 37268,6, error=-12
10-25 18:34:34.935: W/WCDB.CursorWindow(12799): Window is full: requested allocation 913 bytes, free space 400 bytes, window size 2097152 bytes
10-25 18:34:34.935: W/WCDB.SQLiteConnection(12799): Failed allocating 913 bytes for blob at 38278,6, error=-12
10-25 18:34:35.307: W/WCDB.CursorWindow(12799): Window is full: requested allocation 1081 bytes, free space 808 bytes, window size 2097152 bytes
10-25 18:34:35.307: W/WCDB.SQLiteConnection(12799): Failed allocating 1081 bytes for blob at 39180,6, error=-12
10-25 18:34:35.666: W/WCDB.CursorWindow(12799): Window is full: requested allocation 913 bytes, free space 824 bytes, window size 2097152 bytes
10-25 18:34:35.666: W/WCDB.SQLiteConnection(12799): Failed allocating 913 bytes for blob at 40030,6, error=-12
10-25 18:34:36.012: W/WCDB.CursorWindow(12799): Window is full: requested allocation 997 bytes, free space 532 bytes, window size 2097152 bytes
10-25 18:34:36.012: W/WCDB.SQLiteConnection(12799): Failed allocating 997 bytes for blob at 40800,6, error=-12
10-25 18:34:36.355: W/WCDB.CursorWindow(12799): Window is full: requested allocation 2593 bytes, free space 952 bytes, window size 2097152 bytes
10-25 18:34:36.355: W/WCDB.SQLiteConnection(12799): Failed allocating 2593 bytes for blob at 41549,6, error=-12

**Comment by John-He-928** [comment]
这个警告是由于`CursorWindow`一次分配2MB内存，如果一次结果集超了2MB，会自动分页，当你cursor滚动到后面再次查询。

这个会对速度有比较明显的影响，特别是当你的查询比较复杂的时候。

解决方法有：
* 使用`CursorWindow.windowSize(int)`方法设置CursorWindow大小，单位是字节，你可以设置成一个较大的值来包含尽量多的行，副作用是每次查询时会占用对应的内存（Cursor关闭后会释放）
* 查询的时候通过传进Cursor Factory使用别的Cursor实现，比如`SQLiteDirectCursor.FACTORY`，这个实现不使用Cursor Window而是直接调用底层遍历结果集，副作用是不能getCount和向后遍历（方法可以调但会非常慢并且打警告），所以不能用于赋予Adapter用于展示数据。而且Cursor关闭之前会一直占用一个连接，导致别的查询卡死，使用的时候建议配合WAL模式。

**Comment by ukyo6** [comment]
@John-He-928 Hi, 修改cursorWindow的大小为更大, 出现内存不足的概率是不是更大呢.如果查询存在并发的话

java.util.concurrent.ExecutionException: com.tencent.wcdb.CursorWindowAllocationException: Cursor window allocation of 10240 kb failed.
