### ISSUE TITLE
iOS客户端使用WCDB1.0.1，且数据库加密，升级到WCDB1.0.4后，数据库无法读取

### ISSUE THREAD

**Issue by xpacificsoda** [Tencent/wcdb#166]
如题，数据库加密。升级到WCDB1.0.4后，无法读取数据。报错：
[WCDB][DEBUG]Code:26, Type:SQLiteGlobal, Msg:file is encrypted or is not a database

业务代码如下，从未做过更改：
`NSString* path = [self databasePath];
WCTDatabase* db = [[WCTDatabase alloc] initWithPath:path];
[db setCipherKey:[cipher dataUsingEncoding:NSUTF8StringEncoding]];
[db createTableAndIndexesOfName:DB_NAME withClass:ABC.class];`

**Comment by RingoD** [comment]
尝试替换`- setCipherKey:`为`- setCipherKey:andCipherPageSize:`，并分别尝试 1024 和 4096 的`page size`，看哪种是否能正常打开。

**Comment by xpacificsoda** [comment]
`[db setCipherKey:[cipher dataUsingEncoding:NSUTF8StringEncoding] andCipherPageSize:1024];`

这样可以正常读取数据👍
