### ISSUE TITLE
下面这个SQL语句如何执行？目前很多第三方orm数据库不支持直接查询

### ISSUE THREAD

**Issue by myz1104** [Tencent/wcdb#167]
SELECT (minutes/30) AS timeIndex, sum(stepCount), sum(calorie), sum(distance), year, month, day FROM Exercise WHERE year = ? AND month = ? AND day = ? GROUP BY timeIndex

（1）minutes是按照从当日0点开始的分钟数，每五分钟一个记录往上叠加，比如 5 10 15 20 25 30
（2）现在要对数据记录做统计，每30分钟一段数据求和

另外的一个问题就是是否支持触发器？如果我需要把表TA当日的详细记录在有数据更新时自定统计到表TB，如果监控TB的变化？

**Comment by RingoD** [comment]
这个SQL在sample里有类似的例子，可以参考使用。

目前不直接支持 trigger。实际上，WCDB 只要实现 [trigger 的 syntax](http://www.sqlite.org/lang_createtrigger.html)，立刻就能支持。这个很简单。
但 trigger 在性能上不够好，而且 trigger 在多 handle 并发下，会出现某些 handle 无法触发 trigger 的情况。
因此，在 iOS 的场景下，单个 db 的代码都是你自己写的，建议直接在业务的逻辑代码层面去实现检测数据，并分发 notification，从而达到类似 trigger 的功能。

**Comment by myz1104** [comment]
你好，感谢回复。我已经仔细阅读了一遍wcdb的文档和OC层代码，并做了一遍测试，操作起来简单方便，不过操作自定义列数据的时候有点绕，比如User有属性userId,name,sex,ico 等等二十多个属性，那么为了方便我想存储 （UserId TEXT, JSONData BLOB），JSONData就是User的二进制数据，按照你们的做法，我大概要建立一个 WCDBUserTable （@p userId, @p User）对象用于构建表, 然后再建一个WCDBUser用于columnCoding, 为了简化我直接在WCDBUser上配置属性 WCDBUser *userCoding,然后绑定 userId和userCoding，存储是成功的，但是读取回来的userCoding是空的,不知道什么原因。目前我们用到的很多对象属性，都有一部分关键属性存储到字段，其余全部存储为JSONData BLOB 。如果columnCoding类型能够直接在自身对象模型上配置，就会很方便的。

**Comment by RingoD** [comment]
没有明白你的需求，麻烦用代码举例说明

**Comment by RingoD** [comment]
no reply

**Comment by duyulong12** [comment]
请问相同字段的联合查询用在WCDB应该怎么写？ 
比如这种SQL:  select * from t1 union all select * from t1

**Comment by RingoD** [comment]
@duyulong12  Do not reply on a closed issue. For any question, you can submit your own issue.
