### ISSUE TITLE
`WCDB_PROPERTY`,  `WCDB_SYNTHESIZE` 修改建议

### ISSUE THREAD

**Issue by alexlee002** [Tencent/wcdb#17]
* `WCDB_PROPERTY` 希望改成 WCDB_PROPERTY(className, propertyName),   在imp 中像WCDB_SYNTHESIZE增加`WCDB_PROPERTY_HINT`,  这样可以在指定WCDB_PROPERTY的时候有自动补全， 否则model中property多的时候写起来比较麻烦。

* `WCDB_SYNTHESIZE `希望增加到数据表字段的mapping,  比如可以自定义字段名称， 这么做是为了在老项目中使用WCDB的时候能做到兼容。比如可以改成 `WCDB_SYNTHESIZE_CUSTOM(className, propertyName, customColumnName)`。 另外希望默认columnName能把propertyName的驼峰命名方式映射为下划线分割， e.g.: propertyName => property_name.

**Comment by RingoD** [comment]
* 自动补全方面，因为宏内涉及到转字符串，所以编译器没法提示。
* `WCDB_SYNTHESIZE_COLUMN`可以自定义名称，满足你的需求。其他宏可以参考`WCTCodingMacro.h`内的定义。
关于宏的深入用法，我也会在最近写到教程里。
