### ISSUE TITLE
更新到1.0.4 创建表出现问题

### ISSUE THREAD

**Issue by haotiankeji** [Tencent/wcdb#170]
[WCDB][DEBUG]Code:1, Type:SQLiteGlobal, Msg:near ",": syntax error
[WCDB][ERROR]Code:1, Type:SQLite, Tag:0, Op:4, ExtCode:1, Msg:near ",": syntax error, SQL:CREATE TABLE IF NOT EXISTS session_079d57d99ff73af2b97ede36af33af9c_1041(,, PRIMARY KEY,,,,,,,,,,,,,,,,,,,), Path:/Users/haotian/Library/Developer/CoreSimulator/Devices/4FDD3E90-9577-4378-B70A-2578FC6E4778/data/Containers/Data/Application/8643A364-B8CB-46B6-B376-36C69F186E98/Documents/DB1041

**Comment by haotiankeji** [comment]
哥救济啊

**Comment by RingoD** [comment]
从日志来看你没有正确定义ORM。请参考 wiki 的教程和 sample 的例子

**Comment by RingoD** [comment]
no reply
