### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by gdutkyle** [Tencent/wcdb#171]
dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.kd.kd-1/base.apk"],nativeLibraryDirectories=[/data/app/com.kd.kd-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libwcdb.so"
com.tencent.wcdb.database.SQLiteDatabase.<clinit>(Unknown Source)

大神，这个是怎么回事啊

**Comment by John-He-928** [comment]
你检查一下你的APK里面有没有编进去libwcdb.so，这个应该是编译时的问题

**Comment by gdutkyle** [comment]
这个应用发版后，后台错误日志收集的，并不是必现的哦，请问能怎么解决这个问题？

**Comment by John-He-928** [comment]
可能是应用安装时的问题，老版本android会出现，建议遇到这样的问题时，从APK中提取相应的libwcdb.so，放到应用目录里，然后先加载该so，再调用WCDB

**Comment by moncat** [comment]
腾讯1.0.5的bug,已经修改   https://github.com/Tencent/wcdb/blob/master/CHANGELOG.md
