### ISSUE TITLE
更新数据库忽然 - 不能创建表 

### ISSUE THREAD

**Issue by haotiankeji** [Tencent/wcdb#173]
检查对应关系没错
 Type:SQLiteGlobal, Msg:near "PRIMARY": syntax error

**Comment by haotiankeji** [comment]
没做任何操作,隔10分种,可以创建表格了,这个算什么bug

**Comment by RingoD** [comment]
麻烦提供能出现问题的代码

**Comment by RingoD** [comment]
no reply
