### ISSUE TITLE
建议Pod源码可以分group

### ISSUE THREAD

**Issue by littlewu0** [Tencent/wcdb#174]
你好，最近在研究WCDB的源码，真是大神作品，有很多可以学习的地方。
但是就是看的比较费劲，其中一个原因就是工程里面的源码组织没有分group，希望后面能够加上哦，谢谢！

**Comment by RingoD** [comment]
【分group】具体指的是什么？求教下，好用的话马上加上。

**Comment by Rey-superlrp** [comment]
pod WCDB 之后必须要移除工程中的FMDB模块吗？pod之后FMDB的open()直接会Crash。

**Comment by RingoD** [comment]
@Rey-superlrp  FMDB 和 WCDB 没有冲突的地方。但 WCDB 嵌入了 SQLite 源码，你可以尝试去掉原来的 SQLite 系统库试试。

**Comment by c344081** [comment]
@RingoD 就是在podsepc里建立多个subspec来组织源文件:)
例如这个[AFNetworking.podspec](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking.podspec)

**Comment by RingoD** [comment]
可以考虑，后续加一下。
不过如果是为了阅读代码方便，那建议还是阅读源码。Cocoapods即便组织后也不利于阅读代码。

**Comment by RingoD** [comment]
It's done under v1.0.7.5.
