### ISSUE TITLE
1.0.5 FTS  WCDB_VIRTUAL_TABLE_TOKENIZE 

### ISSUE THREAD

**Issue by Fanccc** [Tencent/wcdb#175]
WCDB_VIRTUAL_TABLE_TOKENIZE(WCTSampleFTSData, WCTTokenizerNameWCDB)
crash.. 这里的WCTTokenizerNameWCDB 是个nil...

**Comment by RingoD** [comment]
我这边运行没有问题，你有对工程做什么修改吗？

**Comment by fc852130** [comment]
pod了一个新工程,把example里的这两个文件拖过来build就出了问题.
<img width="273" alt="2017-11-10 4 23 22" src="https://user-images.githubusercontent.com/14356369/32649052-25b773a6-c5be-11e7-9cb1-6c1fb4023b54.png">

**Comment by RingoD** [comment]
看下你的 pod 的版本是不是 v1.0.5，可能没有更新到

**Comment by fc852130** [comment]
<img width="575" alt="2017-11-10 4 55 08" src="https://user-images.githubusercontent.com/14356369/32651175-f2174046-c5c5-11e7-9967-019422283e9a.png">
<img width="633" alt="2017-11-10 4 55 18" src="https://user-images.githubusercontent.com/14356369/32651179-f4ca6a8e-c5c5-11e7-8fa5-0dd95b17d03e.png">
pod 导入的是1.0.5,会有这个问题,我尝试使用Carthage导入好像没问题......

**Comment by RingoD** [comment]
我用cocoapods没有出现问题。
麻烦贴一下crash日志，最好能给个能重现的工程。

**Comment by Fanccc** [comment]
[WCDB_Pod_test.zip](https://github.com/Tencent/wcdb/files/1465333/WCDB_Pod_test.zip)
就这个.

**Comment by RingoD** [comment]
你没有使用 `use_frameworks!`，请参考 cocoapods 官方的教程：https://cocoapods.org
