### ISSUE TITLE
WCDB for Swift - Beta 测试中！

### ISSUE THREAD

**Issue by RingoD** [Tencent/wcdb#176]
WCDB 发布以来，Swift 版的呼声一直比较高。由于 ObjC 版参杂了 C++ 代码，无法直接移植到 Swift 。因此，这里对 Swift 做了全新的开发，目前正在 [swift-alpha](https://github.com/Tencent/wcdb/tree/swift-alpha) 分支测试中。接下来会快速迭代，推动至 beta 版，直至正式 release。

## 关于 WCDB for Swift
Swift 版本的计划是
1. 与 ObjC 版具有相同的功能。支持 ORM、WINQ 语句、便捷的接口等。
2. 根据 Swift 的语言特性，以更好的方式实现 WINQ 和 Convenient、ChainCall 接口。
3. 具有与 Swift 语言匹配的性能。

## 关于 WCDB for Swift - Alpha
alpha 版在功能、性能、易用性、稳定性等方面都可能存在问题，且我们还会不断地根据 Swift 特性优化接口，因此我们**不建议将 alpha 版用于正式项目中**。

初始的 alpha 版与 ObjC 版相比，还有以下欠缺：
1. FTS全文搜索
2. 文件操作接口（db文件移动、删除等）
3. 数据库修复
4. 监控接口（SQL监控、性能监控）
5. Benchmark
6. 文档教程
7. 其他零散的接口

我们会快速迭代，在 beta 版发布之前解决以上问题。并将 Swift 的文档合并进现在的 ObjC 文档中。

## 关于 WCDB for Swift 的教程
同上，目前还没完成与 Swift 版对应的教程文档。
但 Swift 版的接口和设计与 ObjC 版并无太大差别，熟悉 ObjC 版的开发者可以参考 Swift 版的 sample 进行开发。不熟悉的也可以对照 ObjC 版的文档尝试操作。

## 关于 PR 和社区
WCDB 的 ObjC 版包含了许多 C++ 的高级特性，对于 大多数 iOS 开发者来说比较难去修改源码，因此 PR 也很不活跃。
而 Swift 版 WCDB 基本都是纯 Swift 代码，且其社区文化一直很活跃。我们很欢迎大家多多来提 PR ，不管是一个 typo、一个 bug fixed 还是一个新的 feature。
**希望 WCDB 不仅是 Tencent / WeChat 的，更是社区的。**

任何关于 Swift 版的问题都欢迎在这个 issue 下提出，或者来我们的 [QQ 群讨论](http://qm.qq.com/cgi-bin/qm/qr?k=hgCZCOfTLZcSblvl_zgiFa20iCol7Gr8)。后续的进度也会在这里更新。

**Comment by RingoD** [comment]
WCDB for Swift beta 版已发布，代码已经合到 dev 分支。
包含与 ObjC 版相同的功能，并有相对完善的测试用例，以确保正确性。
目前可以通过 git clone, carthage, cocoapods 的方式体验 beta 版。流程与 ObjC 版基本一致，其中
cocoapods: 需指定分支为： pod 'WCDB.swift', :git => 'https://github.com/Tencent/wcdb.git', :branch => 'dev'
carthage: 需指定分支为： github "Tencent/wcdb" "dev"

**Comment by zhengrusong** [comment]
大神您好！我通过 pod 'WCDB.swift', :git => 'https://github.com/Tencent/wcdb.git', :branch => 'dev' 集成到项目里 报了76个错误，类的访问权限问题。 例如Datebase.swift文件53行报错：‘defaultConfigs’ is inaccessible due to 'private' protection level @RingoD

**Comment by RingoD** [comment]
@zhengrusong  我刚才试了下，没有类似问题。检查下：
1. podfile 里要加有 `use_framework!`
2. 支持的 Swift 版本是 4.0
3. 清理 cocoapods 的缓存后再试
```
pod cache clean WCDB --all
rm -rf ~/Library/Caches/CocoaPods
pod repo update
```
如果还不行，可以发下你的工程

**Comment by zhengrusong** [comment]
可以了。。THX。 @RingoD

**Comment by wanhmr** [comment]
> 希望 WCDB 不仅是 Tencent / WeChat 的，更是社区的。

我相信这话太鼓舞人心了。

**Comment by RingoD** [comment]
WCDB Swift is already released
