### ISSUE TITLE
大神求教实体对象嵌套如何使用

### ISSUE THREAD

**Issue by cqb9005** [Tencent/wcdb#178]
object嵌套object时如何存储？

**Comment by RingoD** [comment]
iOS还是Android？
请举例说明问题

**Comment by cqb9005** [comment]
ios，比如数据结构是{"cateid":"id","name":"名字","param":[{"paramid":"id","paramname":"名字"}]}  
#import <WCDB/WCDB.h>
@interface ZZCateModel : NSObject<WCTTableCoding>
@property (nonatomic, strong) NSString *cateid;
@property (nonatomic, strong) NSString *name;
WCDB_PROPERTY(cateid)
WCDB_PROPERTY(name)
@end

**Comment by RingoD** [comment]
https://github.com/Tencent/wcdb/wiki/ORM使用教程#自定义类型

**Comment by cqb9005** [comment]
param的对象如何创建？如何和cate对象关联？

**Comment by RingoD** [comment]
认真看下 column coding 的链接和 sample

**Comment by RingoD** [comment]
no reply
