### ISSUE TITLE
iOS 调用 - (instancetype)initWithPath:(NSString *)path 时有时会崩溃

### ISSUE THREAD

**Issue by coder4LYK** [Tencent/wcdb#180]
## 对应的 WCDB 语言 ( The language of WCDB )

Objective

## WCDB 的版本号 ( The version of WCDB )

v1.0.4

## WCDB 的平台 ( The platform of WCDB )

iOS

## WCDB 的安装方式 ( The installation of WCDB )

Cocoapods

## 遇到的问题 ( What's the issue? )
感谢各位分享这么强大的数据库框架，在使用过程中，有时候会在调用 - (instancetype)initWithPath:(NSString *)path 时崩溃，下面是我的崩溃截图，这个崩溃时有时无，崩溃的时候数据库路径也是没问题的，崩在string.h文件里，无从下手解决，麻烦帮忙看下是由于什么原因导致的，应该怎么解决？
<img width="823" alt="2017-11-15 3 56 08" src="https://user-images.githubusercontent.com/12741142/32825592-787b20ea-ca20-11e7-9be8-15b93459fd34.png">

- [x] 我已阅读 [wiki的文档](https://github.com/Tencent/wcdb/wiki) 和 [常见问题](https://github.com/Tencent/wcdb/wiki/常见问题)。

- [x]  I've read and understood the [wiki](https://github.com/Tencent/wcdb/wiki/iOS-macOS-Tutorial).

**Comment by RingoD** [comment]
能否提供一个能重现问题的工程代码？

**Comment by coder4LYK** [comment]
抱歉工程可能提供不了，而且崩溃是有时发生的，暂时找不到崩溃原因，初始化方法会在主线程和子线程都会调的，有可能会同时调，请问这个会影响吗？

**Comment by RingoD** [comment]
不影响。
能否将所有线程的堆栈完整截图一下。

**Comment by coder4LYK** [comment]
<img width="945" alt="2018-03-29 4 41 04" src="https://user-images.githubusercontent.com/12741142/38078832-16f4fd6e-3370-11e8-8237-69d570d589d7.png">
<img width="935" alt="2018-03-29 4 40 27" src="https://user-images.githubusercontent.com/12741142/38078855-287654ac-3370-11e8-8d03-406b4ac4ca80.png">
你好，这样截图你看看行不行

**Comment by RingoD** [comment]
你提供的截图上并没有显示 crash 了

**Comment by coder4LYK** [comment]
不是的，这个就是我在crash的时候截图的

**Comment by RingoD** [comment]
那请提供与crash相关的堆栈。

**Comment by coder4LYK** [comment]
CSMBP-AppStore-Package    0x101108008    WCDB::Configs::setConfig(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<bool (std::__1::shared_ptr<WCDB::Handle>&, WCDB::Error&)> const&) (string:1247)
CSMBP-AppStore-Package    0x101107fd0    WCDB::Configs::setConfig(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<bool (std::__1::shared_ptr<WCDB::Handle>&, WCDB::Error&)> const&) (memory:0)
CSMBP-AppStore-Package    0x10110c844    WCDB::Database::setConfig(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<bool (std::__1::shared_ptr<WCDB::Handle>&, WCDB::Error&)> const&) (memory:4625)
CSMBP-AppStore-Package    0x10118b1ec    -[WCTDatabase(Database) initWithPath:] (functional:1860)
CSMBP-AppStore-Package    0x100631248    +[CSMessageDBHelper(CSMsgCenterMessageModel) addMessages:] (CSMessageDBHelper+CSMsgCenterMessageModel.mm:26)
CSMBP-AppStore-Package    0x1006370bc    ___101+[CSMessageDBHelper(CSMsgCenterMessageModel) getMessagesWithType:language:successBlock:failureBlock:]_block_invoke (CSMessageDBHelper+CSMsgCenterMessageModel.mm:506)
CSMBP-AppStore-Package    0x100db33e0    ___49-[CSApiRequest startLoadDataWithSuccess:failure:]_block_invoke_2 (CSApiRequest.m:536)
CSMBP-AppStore-Package    0x100db2654    _ExceBlockInMain (CSApiRequest.m:53)
CSMBP-AppStore-Package    0x100db335c    ___49-[CSApiRequest startLoadDataWithSuccess:failure:]_block_invoke (CSApiRequest.m:539)
CSMBP-AppStore-Package    0x100db61f0    -[CSNetBaseRequest callSuccess] (CSNetBaseRequest.m:281)
CSMBP-AppStore-Package    0x1009e347c    -[CSApiRequest(CSRequestInfoLocalization) callSuccessMine] (CSNetBaseRequest+CSRequestInfoLocalization.m:31)
CSMBP-AppStore-Package    0x100db60c8    -[CSNetBaseRequest dealSuccess:] (CSNetBaseRequest.m:259)
CSMBP-AppStore-Package    0x100db5de8    ___28-[CSNetBaseRequest loadData]_block_invoke (CSNetBaseRequest.m:209)
CSMBP-AppStore-Package    0x100db9a64    -[CSNetProxy dealCompletionCallback:request:success:fail:response:responseObject:error:] (CSNetProxy.m:412)
CSMBP-AppStore-Package    0x100db9544    ___46-[CSNetProxy callNetWithRequest:success:fail:]_block_invoke.267 (CSNetProxy.m:334)
CSMBP-AppStore-Package    0x100d59880    ___72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_2.150 (AFURLSessionManager.m:308)
libdispatch.dylib    0x1807e6a54    __dispatch_call_block_and_release + 24
libdispatch.dylib    0x1807e6a14    __dispatch_client_callout + 16
libdispatch.dylib    0x180827acc    __dispatch_main_queue_callback_4CF$VARIANT$armv81 + 532
CoreFoundation    0x180e12544    ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
CoreFoundation    0x180e10120    ___CFRunLoopRun + 2012
CoreFoundation    0x180d2fe58    _CFRunLoopRunSpecific + 436
GraphicsServices    0x182bdcf84    _GSEventRunModal + 100
UIKit    0x18a48467c    _UIApplicationMain + 236
CSMBP-AppStore-Package    0x10001eccc    _main (main.m:24)
libdyld.dylib    0x18084c56c    _start + 4

**Comment by RingoD** [comment]
呃，如上面所说，你需要提供完整的线程堆栈，才能进行定位问题。
完整的线程堆栈包括
1. 各个线程的调用栈
2. 系统诊断
3. 中断错误码等
你可以参考一下苹果的crash文件里包含哪些信息。
