### ISSUE TITLE
您好，求教一下，在iOS中怎么将包含数组或者字典（数组/字典中也包含有实体）的实体与另外的实体嵌套进行相关CRUD？

### ISSUE THREAD

**Issue by xtxh** [Tencent/wcdb#181]
> 请按照模版填写你在使用 WCDB 时的基本信息。
> 请在**编辑完成后删除所有灰色的提示信息**。
### 对应的 WCDB 语言 ( The language of WCDB )
Objective

### WCDB 的版本号 ( The version of WCDB )
v1.0.5

### WCDB 的平台 ( The platform of WCDB )
iOS

### WCDB 的安装方式 ( The installation of WCDB )
Cocoapods

### 遇到的问题 ( What's the issue? )

> 如果是错误信息，请**贴上相关的报错信息或截图**。
项目一运行就出现了，这种情况是我清理了一次DriveData后出现的，在模拟器iPhone 8 Plus和iPhone X上运行的，
![2017-11-20 10 21 14](https://user-images.githubusercontent.com/15848988/32999397-e2c97cd4-cddc-11e7-8052-1ad2306de059.png)

- [x] 我已阅读 [wiki的文档](https://github.com/Tencent/wcdb/wiki) 和 [常见问题](https://github.com/Tencent/wcdb/wiki/常见问题)。

- [x]  I've read and understood the [wiki](https://github.com/Tencent/wcdb/wiki/iOS-macOS-Tutorial).

**Comment by RingoD** [comment]
请按照模版填写基本信息

**Comment by xtxh** [comment]
按照RingoD大神指示，在Podfile文件中加上use_framework就好了
