### ISSUE TITLE
Android run build-depends-android.sh fail....

### ISSUE THREAD

**Issue by Guang1234567** [Tencent/wcdb#182]
Hello  weChatDev:

Run build-depends-android.sh on  ubuntu  fail.

Help me please.

**NDK version**
ndk-r11c

**The error output:**

![20171116190153](https://user-images.githubusercontent.com/8240718/32887962-ab5dfb3c-cb00-11e7-8e4d-75c6657a9684.png)

**WCDB version**

![20171116190445](https://user-images.githubusercontent.com/8240718/32888090-1d9b7710-cb01-11e7-85ce-6f4625dc5738.png)

**Comment by John-He-928** [comment]
The issue you showed is patching failure to OpenSSL code. This is probably caused by using different version or modified OpenSSL. You can manually edit the failed file an ignore that error.

Also, NDK r15 is recommended for building WCDB and its dependencies. r16 support will be added soon.
