### ISSUE TITLE
怎样安装文件模版

### ISSUE THREAD

**Issue by tanghaiyang1992** [Tencent/wcdb#183]
「1、首先需要安装文件模版。该模版的安装脚本集成在WCDB的编译脚本中，只需编译一次WCDB，就会自动安装文件模版。安装完成后重启Xcode，新建文件，即可看到对应的文件模版」

**Comment by RingoD** [comment]
请按照issue的模版提供基本信息

**Comment by RingoD** [comment]
no reply
