### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by Heycz** [Tencent/wcdb#185]
### 对应的 WCDB 语言 ( The language of WCDB )

Java

### WCDB 的版本号 ( The version of WCDB )

v1.0.5

### WCDB 的平台 ( The platform of WCDB )

Android 

### WCDB 的安装方式 ( The installation of WCDB )

Gradle

### 遇到的问题 ( What's the issue? )
db能读不能写,报 database is locked,坚果1 android5.0
> Open: true
  Max connections: 4
  Available primary connection:
    Connection #1:
      connectionPtr: 0xffffffffb8793e70
      isPrimaryConnection: true
      onlyAllowReadOnlyOperations: false
      Most recently executed operations:
        0: [2017-11-27 14:43:08.331] prepare took 0ms - succeeded, sql="PRAGMA main.integrity_check(1);", tid=16655
        1: [2017-11-27 14:40:38.974] execute took 10753ms - failed, sql="BEGIN EXCLUSIVE;", tid=16655, exception="database is locked (code 5, errno 0): "
        2: [2017-11-27 14:37:00.035] execute took 10020ms - failed, sql="BEGIN EXCLUSIVE;", tid=16655, exception="database is locked (code 5, errno 0): "
        3: [2017-11-27 14:34:27.680] execute took 10022ms - failed, sql="BEGIN EXCLUSIVE;", tid=14797, exception="database is locked (code 5, errno 0): "
        4: [2017-11-27 14:33:45.581] execute took 10021ms - failed, sql="BEGIN EXCLUSIVE;", tid=15398, exception="database is locked (code 5, errno 0): "
        5: [2017-11-27 14:29:48.538] execute took 10015ms - failed, sql="BEGIN EXCLUSIVE;", tid=5342, exception="database is locked (code 5, errno 0): "
        6: [2017-11-27 14:28:49.178] execute took 10016ms - failed, sql="BEGIN EXCLUSIVE;", tid=5152, exception="database is locked (code 5, errno 0): "
        7: [2017-11-27 14:19:54.015] prepare took 0ms - succeeded, sql="PRAGMA user_version;", tid=5344
        8: [2017-11-27 14:19:54.015] execute took 0ms - succeeded, sql="PRAGMA synchronous=1"
        9: [2017-11-27 14:19:54.014] executeForLong took 0ms - succeeded, sql="PRAGMA wal_autocheckpoint=100"
        10: [2017-11-27 14:19:54.014] executeForLong took 0ms - succeeded, sql="PRAGMA wal_autocheckpoint"
        11: [2017-11-27 14:19:54.014] executeForLong took 0ms - succeeded, sql="PRAGMA journal_size_limit=524288"
        12: [2017-11-27 14:19:54.014] executeForLong took 0ms - succeeded, sql="PRAGMA journal_size_limit"
        13: [2017-11-27 14:19:54.014] execute took 0ms - succeeded, sql="PRAGMA synchronous=2"
        14: [2017-11-27 14:19:54.005] executeForString took 9ms - succeeded, sql="PRAGMA journal_mode=WAL"
        15: [2017-11-27 14:19:54.002] executeForString took 3ms - succeeded, sql="PRAGMA journal_mode"
        16: [2017-11-27 14:19:54.002] executeForLong took 0ms - succeeded, sql="PRAGMA foreign_keys"
        17: [2017-11-27 14:19:54.002] executeForLong took 0ms - succeeded, sql="PRAGMA page_size"
      Prepared statement cache:
        <none>
  Available non-primary connections:
    Connection #3:
      connectionPtr: 0xffffffffb87a5310
      isPrimaryConnection: false
      onlyAllowReadOnlyOperations: true
      Most recently executed operations:
        0: [2017-11-27 14:19:54.041] prepare took 1ms - succeeded, sql="SELECT * FROM `OrganizationUserTable` WHERE `uid` = 'ex_zhangsan1'  LIMIT 1", tid=5344
        1: [2017-11-27 14:19:54.041] executeForLong took 0ms - succeeded, sql="PRAGMA journal_size_limit=524288"
        2: [2017-11-27 14:19:54.041] executeForLong took 0ms - succeeded, sql="PRAGMA journal_size_limit"
        3: [2017-11-27 14:19:54.041] execute took 0ms - succeeded, sql="PRAGMA synchronous=1"
        4: [2017-11-27 14:19:54.034] executeForString took 7ms - succeeded, sql="PRAGMA journal_mode"
        5: [2017-11-27 14:19:54.034] executeForLong took 0ms - succeeded, sql="PRAGMA foreign_keys"
        6: [2017-11-27 14:19:54.033] executeForLong took 1ms - succeeded, sql="PRAGMA page_size"
      Prepared statement cache:
        0: statementPtr=0xffffffffb889c2d0, numParameters=0, type=1, readOnly=true, sql="SELECT * FROM `OrganizationUserTable` WHERE `uid` = 'ex_zhangsan1'  LIMIT 1"
    Connection #2:
      connectionPtr: 0xffffffffb8853f58
      isPrimaryConnection: false
      onlyAllowReadOnlyOperations: true
      Most recently executed operations:
        0: [2017-11-27 14:43:08.331] executeForString took 21ms - succeeded, sql="PRAGMA main.integrity_check(1);", tid=16655
        1: [2017-11-27 14:39:59.401] executeForCursorWindow took 29ms - succeeded, sql="select * from OrganizationUserTable", tid=16655
        2: [2017-11-27 14:39:59.395] prepare took 1ms - succeeded, sql="select * from OrganizationUserTable", tid=16655
        3: [2017-11-27 14:39:49.424] prepare took 0ms - succeeded, sql="select * from OrganizationUserTable", tid=16655
        4: [2017-11-27 14:39:32.270] prepare took 1ms - succeeded, sql="select * from OrganizationUserTable", tid=16655
        5: [2017-11-27 14:38:36.954] prepare took 1ms - failed, sql="select * from organizationuser", tid=16655, exception="no such table: organizationuser (code 1, errno 0): , while compiling: select * from organizationuser"
        6: [2017-11-27 14:29:48.460] executeForCursorWindow took 0ms - succeeded, sql="SELECT * FROM `OrganizationDepartTable` WHERE `departmentNumber` = '182098839302'  LIMIT 1", tid=5342
        7: [2017-11-27 14:29:48.459] prepare took 0ms - succeeded, sql="SELECT * FROM `OrganizationDepartTable` WHERE `departmentNumber` = '182098839302'  LIMIT 1", tid=5342
        8: [2017-11-27 14:29:48.408] executeForCursorWindow took 0ms - succeeded, sql="SELECT * FROM `OrganizationDepartTable` WHERE `departmentNumber` = '00017661'  LIMIT 1", tid=5152
        9: [2017-11-27 14:29:48.407] prepare took 1ms - succeeded, sql="SELECT * FROM `OrganizationDepartTable` WHERE `departmentNumber` = '00017661'  LIMIT 1", tid=5152
        10: [2017-11-27 14:29:48.407] executeForCursorWindow took 0ms - succeeded, sql="SELECT * FROM `OrganizationDepartTable` WHERE `departmentNumber` = '100000'  LIMIT 1", tid=5152
        11: [2017-11-27 14:29:48.406] prepare took 0ms - succeeded, sql="SELECT * FROM `OrganizationDepartTable` WHERE `departmentNumber` = '100000'  LIMIT 1", tid=5152
        12: [2017-11-27 14:29:48.405] executeForCursorWindow took 0ms - succeeded, sql="SELECT * FROM `OrganizationDepartTable` WHERE `departmentNumber` = '160508542462'  LIMIT 1", tid=5152
        13: [2017-11-27 14:29:48.405] prepare took 0ms - succeeded, sql="SELECT * FROM `OrganizationDepartTable` WHERE `departmentNumber` = '160508542462'  LIMIT 1", tid=5152
        14: [2017-11-27 14:29:48.404] executeForCursorWindow took 0ms - succeeded, sql="SELECT * FROM `OrganizationDepartTable` WHERE `departmentNumber` = '182098833436'  LIMIT 1", tid=5152
        15: [2017-11-27 14:29:48.403] prepare took 1ms - succeeded, sql="SELECT * FROM `OrganizationDepartTable` WHERE `departmentNumber` = '182098833436'  LIMIT 1", tid=5152
        16: [2017-11-27 14:29:48.402] executeForCursorWindow took 0ms - succeeded, sql="SELECT * FROM `OrganizationDepartTable` WHERE `departmentNumber` = '182098839302'  LIMIT 1", tid=5152
        17: [2017-11-27 14:29:48.401] prepare took 0ms - succeeded, sql="SELECT * FROM `OrganizationDepartTable` WHERE `departmentNumber` = '182098839302'  LIMIT 1", tid=5152
        18: [2017-11-27 14:29:48.374] executeForCursorWindow took 5ms - succeeded, sql="SELECT * FROM `OrganizationUserTable` WHERE (`uid` = 'caizx2' AND `appkey` = 'e21c13e0-b57a-49f1-985b-01af30232e1a' )  LIMIT 1", tid=5342
        19: [2017-11-27 14:29:48.368] prepare took 6ms - succeeded, sql="SELECT * FROM `OrganizationUserTable` WHERE (`uid` = 'caizx2' AND `appkey` = 'e21c13e0-b57a-49f1-985b-01af30232e1a' )  LIMIT 1", tid=5342
      Prepared statement cache:
        0: statementPtr=0xffffffffb83a00b0, numParameters=0, type=1, readOnly=true, sql="SELECT * FROM `OrganizationUserTable` WHERE `uid` = 'ex_zhangsan1'  LIMIT 1"
        1: statementPtr=0xffffffffb8566060, numParameters=0, type=1, readOnly=true, sql="SELECT * FROM `OrganizationUserTable` WHERE `uid` = 'xubx1'  LIMIT 1"
        2: statementPtr=0xffffffffb84cd560, numParameters=0, type=1, readOnly=true, sql="SELECT * FROM `OrganizationUserTable` WHERE `uid` = 'fanyl5'  LIMIT 1"
        3: statementPtr=0xffffffffb8fd9c78, numParameters=0, type=1, readOnly=true, sql="SELECT * FROM `OrganizationUserTable` WHERE (`uid` = 'caizx2' AND `appkey` = 'e21c13e0-b57a-49f1-985b-01af30232e1a' )  LIMIT 1"
        4: statementPtr=0xffffffffb89ec938, numParameters=0, type=1, readOnly=true, sql="SELECT * FROM `OrganizationDepartTable` WHERE `departmentNumber` = '182098833436'  LIMIT 1"
        5: statementPtr=0xffffffffb895ab10, numParameters=0, type=1, readOnly=true, sql="SELECT * FROM `OrganizationDepartTable` WHERE `departmentNumber` = '160508542462'  LIMIT 1"
        6: statementPtr=0xffffffffb8bb6a38, numParameters=0, type=1, readOnly=true, sql="SELECT * FROM `OrganizationDepartTable` WHERE `departmentNumber` = '100000'  LIMIT 1"
        7: statementPtr=0xffffffffb898bab8, numParameters=0, type=1, readOnly=true, sql="SELECT * FROM `OrganizationDepartTable` WHERE `departmentNumber` = '00017661'  LIMIT 1"
        8: statementPtr=0xffffffffb82cc730, numParameters=0, type=1, readOnly=true, sql="SELECT * FROM `OrganizationDepartTable` WHERE `departmentNumber` = '182098839302'  LIMIT 1"
        9: statementPtr=0xffffffffb8898990, numParameters=0, type=1, readOnly=true, sql="select * from OrganizationUserTable"
  Acquired connections:
    <none>
  Connection waiters:
    <none>

**Comment by John-He-928** [comment]
SQLITE_BUSY一般是由于文件锁被别的链接持有

是否打开了同一个DB的多个对象，另一个对象打开了事务？（别的进程打开的DB对象也会影响）

**Comment by Heycz** [comment]
SqliteHeler已经用了单例模式来处理,应该没有多开,而且获取当前这个单例close掉再开就能正常读取,当时debug db是没有开事务,不过这个还是第一次发现,我加到日志了,之后再出现再跟踪,不知道咋重现了

**Comment by lightai** [comment]
wcdb ios版本单进程情况下通过pthread同步避免SQLITE_BUSY问题，请问Android下是什么情况，也可以参考ios的那种方式么？

**Comment by John-He-928** [comment]
Android在Java层有连接池负责管理多个连接，单进程单个SQLiteDatabase对象下不会出现SQLITE_BUSY，多进程或多个实例则可能出现SQLITE_BUSY。

正常使用场景应该是一个进程内一个数据库文件只持有一个SQLiteDatabase对象，多个线程共用一个对象

**Comment by lightai** [comment]
https://zhuanlan.zhihu.com/p/22285202
这个是你们写的单进程并发访问sqlite情况下，通过pthread的mutex代替file lock解决SQLITE_BUSY的问题。
Android平台下单进程开启多个连接，也是存在SQLITE_BUSY的问题啊。
