### ISSUE TITLE
iOS版本使用Extension时，共享WCDB，不能创建地址

### ISSUE THREAD

**Issue by WcZhaoWei** [Tencent/wcdb#187]
> e.g. Objective
> e.g. v1.0.5
> e.g. iOS
> e.g. Cocoapods

[WCDB][ERROR]Code:13, Type:SystemCall, Op:6, Msg:Permission denied, Path:file:
[WCDB][DEBUG]Code:14, Type:SQLiteGlobal, Msg:cannot open file at line 5891 of [bbd85d235f]
[WCDB][DEBUG]Code:14, Type:SQLiteGlobal, Msg:os_unix.c:5891: (2) open(//file:/Users/zhaowei/Library/Developer/CoreSimulator/Devices/C5ED35F9-A3BD-487A-A80C-8612A5902654/data/Containers/Shared/AppGroup/6D404237-F6D5-48CF-A07A-8EE8EAAF1964/test.db) - 
[WCDB][ERROR]Code:14, Type:SQLite, Tag:0, Op:1, Msg:unable to open database file, Path:file:/Users/zhaowei/Library/Developer/CoreSimulator/Devices/C5ED35F9-A3BD-487A-A80C-8612A5902654/data/Containers/Shared/AppGroup/6D404237-F6D5-48CF-A07A-8EE8EAAF1964/test.db
[WCDB][ERROR]Code:13, Type:SystemCall, Op:6, Msg:Permission denied, Path:file:
[WCDB][DEBUG]Code:14, Type:SQLiteGlobal, Msg:cannot open file at line 5891 of [bbd85d235f]
[WCDB][DEBUG]Code:14, Type:SQLiteGlobal, Msg:os_unix.c:5891: (2) open(//file:/Users/zhaowei/Library/Developer/CoreSimulator/Devices/C5ED35F9-A3BD-487A-A80C-8612A5902654/data/Containers/Shared/AppGroup/6D404237-F6D5-48CF-A07A-8EE8EAAF1964/test.db) - 
[WCDB][ERROR]Code:14, Type:SQLite, Tag:0, Op:1, Msg:unable to open database file, Path:file:/Users/zhaowei/Library/Developer/CoreSimulator/Devices/C5ED35F9-A3BD-487A-A80C-8612A5902654/data/Containers/Shared/AppGroup/6D404237-F6D5-48CF-A07A-8EE8EAAF1964/test.db

**Comment by RingoD** [comment]
看日志是你这个目录没有写权限

**Comment by yayakjoss** [comment]
wcdb /.gitignore
