### ISSUE TITLE
编译后未出现对应的文件模版（已重启多次Xcode）,Xcode版本 Version 9.1 (9B55)

### ISSUE THREAD

**Issue by xiaogao233** [Tencent/wcdb#189]
### 对应的 WCDB 语言 ( The language of WCDB )

> Objective

### WCDB 的版本号 ( The version of WCDB )

> v1.0.5

### WCDB 的平台 ( The platform of WCDB )

> iOS

### WCDB 的安装方式 ( The installation of WCDB )

> Cocoapods

### 遇到的问题 ( What's the issue? )

>编译后未出现对应的文件模版（已重启多次Xcode）,Xcode版本 Version 9.1 (9B55)

**Comment by RingoD** [comment]
可以清理cocoapods缓存后再试，参考：https://github.com/Tencent/wcdb/wiki/常见问题#cocoapods无法搜到wcdb或搜到的版本不是最新的

**Comment by xiaogao233** [comment]
清理缓存后依然无效

**Comment by xiaogao233** [comment]
已解决：
需要在pod中指定该库的地址，并且指定分支master.
pod 'WCDB',git: 'https://github.com/Tencent/wcdb.git' , branch: 'master'

解决方案来源：
http://www.jianshu.com/p/7395f778c020
