### ISSUE TITLE
iOS 建议添加打包脚本

### ISSUE THREAD

**Issue by patgdut** [Tencent/wcdb#19]
现在编译需要把真机跟模拟器的库用 lipo 合并, 有一点麻烦, 希望可以添加打包脚本, 以后升级可以方便一点。

**Comment by RingoD** [comment]
你可以用carthage。它会生成真机和模拟器合并的的库。

“合并真机和模拟器”，这个是否是一个普遍需求，其他iOS framework有这么做吗？

**Comment by patgdut** [comment]
模拟器调试比较快，特别是项目比较大的时候。目前项目是用 cocoapods 管理第三方库，要是支持 cocoapods 也可以，不过看评论貌似比较麻烦，所以你们不够时间做，我自己写一个脚本也是可以的：）

**Comment by RingoD** [comment]
可以pr你的打包脚本，应该也不复杂的。
cocoapods正在支持中。

**Comment by RingoD** [comment]
cocoapods已经支持了，请参考 #3
