### ISSUE TITLE
查询或排序时忽略大小写

### ISSUE THREAD

**Issue by CoderXL** [Tencent/wcdb#190]
请问如果查询时需要忽略大小写 或者 排序时需要忽略大小写应该怎么写sql语句呢
比如 ORDER BY pinYin COLLATE NOCASE ASC

**Comment by RingoD** [comment]
感谢反馈，这个语法之前没有支持到，我刚加上了：https://github.com/Tencent/wcdb/commit/7b30fe5d7b0aa19fdb9545c7abe880294a9895ce

可以通过在普通的 CRUD 方法的 orderBy 参数中，填入: `orderBy: Order(className.pinYin, "NOCASE", OrderTerm::ASC)`

**Comment by nalanrola** [comment]
swift版本中sdk中好像没有这样的api呀

**Comment by RingoD** [comment]
@nalanrola  Do not reply in a closed issue. If you have any question, just submit a new issue.
