### ISSUE TITLE
iOS - 启动APP，控制台打印提示信息 [WCDB][DEBUG]Code:283

### ISSUE THREAD

**Issue by lzg8899** [Tencent/wcdb#191]
> v1.0.4  Xcode 9.1 开发模式，OC

启动APP弹出提示，[WCDB][DEBUG]Code:283, Type:SQLiteGlobal, Msg:recovered 53 frames from WAL file

请问是我漏了操作数据库的哪一步么？

**Comment by RingoD** [comment]
不是错误，请参考wiki中错误处理的文档

**Comment by lzg8899** [comment]
看了一下WiKi,  确认一下：这个打印信息不用处理的，对吧？

**Comment by RingoD** [comment]
是的

**Comment by lzg8899** [comment]
感谢您的回复，简直秒回啊！

**Comment by RingoD** [comment]
no reply

**Comment by gee1k** [comment]
请问这个信息可以关闭吗？我的一个 macos app 。需要提供命令行方式使用，每次终端都会打印，很影响体验。
