### ISSUE TITLE
不能在+(void)load 函数中调用[[WCTDatabase alloc] initWithPath:]吗

### ISSUE THREAD

**Issue by CoderXL** [Tencent/wcdb#194]
如果在+(void)load函数中调用initWithPath会crash

https://github.com/CoderXL/WCDB.git

**Comment by RingoD** [comment]
为什么要在 `load` 函数调用 WCDB 的代码？
推荐看下 Apple 文档中 load 函数的作用

**Comment by SeanChense** [comment]
load 函数中做这个操作不妥。
崩溃不说，还拖慢加载速度。
