### ISSUE TITLE
出现默认支持类型 NSString ,NSDate需要实现WCTColumnCoding 协议的问题

### ISSUE THREAD

**Issue by wz5891** [Tencent/wcdb#196]
### 对应的 WCDB 语言 ( The language of WCDB )
Objective

### WCDB 的版本号 ( The version of WCDB )
v1.0.5

### WCDB 的平台 ( The platform of WCDB )
iOS

### WCDB 的安装方式 ( The installation of WCDB )
Git clone

### 遇到的问题 ( What's the issue? )
![image](https://user-images.githubusercontent.com/1487838/33696218-c741cfec-dac6-11e7-8811-48d032d471f1.png)
[WCDB][ERROR]Code:2, Type:Abort, Msg:[NSString] should conform to WCTColumnCoding protocol, which is the class of [User name]
(lldb) 

-[] 我已阅读 [wiki的文档](https://github.com/Tencent/wcdb/wiki) 和 [常见问题](https://github.com/Tencent/wcdb/wiki/常见问题)。

**Comment by RingoD** [comment]
见文档：在你的项目工程配置的Build Settings->Other Linker Flags中添加-all_load和-ObjC。

**Comment by wz5891** [comment]
我之前加了这个报我linker error 我以为是版本不同了呢 能帮我看看吗 
![image](https://user-images.githubusercontent.com/1487838/33745602-65dbc20a-db7d-11e7-94ac-1b5f98f04aa7.png)
![image](https://user-images.githubusercontent.com/1487838/33745635-a47bbe20-db7d-11e7-81a6-14ba83b6d219.png)

**Comment by RingoD** [comment]
没有加 `libz`，这些都在教程里写了。麻烦严格按照教程接入。

**Comment by wz5891** [comment]
谢谢 ok了
