### ISSUE TITLE
iOS 编译时报错  

### ISSUE THREAD

**Issue by caodong1991** [Tencent/wcdb#200]
cocoapods 集成的1.0.5版本。
错误如下图。
![wx20171214-190159](https://user-images.githubusercontent.com/18346636/33989288-e89f2310-e101-11e7-8810-2e54af6364a1.png)
![wx20171214-190211](https://user-images.githubusercontent.com/18346636/33989289-e8d2456a-e101-11e7-9147-8d1b211aeb61.png)

**Comment by RingoD** [comment]
这边没有重现类似问题，可以检查下 cocoapods 是否有加 `use_framework!`。
并严格按照 wiki 的教程进行接入，如果不行则清理缓存后再试。
相关链接：
1. https://github.com/Tencent/wcdb/wiki
2. https://github.com/Tencent/wcdb/wiki/常见问题

**Comment by BulletTrain** [comment]
正好遇到了，感谢楼上
