### ISSUE TITLE
getObjectsOfClass:fromTable:where: 字符串如何比较

### ISSUE THREAD

**Issue by summertian4** [Tencent/wcdb#201]
### 对应的 WCDB 语言 ( The language of WCDB )
Objective

### WCDB 的版本号 ( The version of WCDB )
v1.0.5

### WCDB 的平台 ( The platform of WCDB )
iOS

### WCDB 的安装方式 ( The installation of WCDB )
Cocoapods

### 遇到的问题 ( What's the issue? )

我的代码中 logId 是 NSString 类型，请问应该如何写 where 语句。

另，目前木有找到非常详尽的代码解说 where 语句的各种表达方式，以后还会更新吗。

```objc
[self.wcdb getObjectsOfClass:UploadLog.class
                                        fromTable:kUploadLogTableName
                                        where:uploadModel.logId == uploadModel.logId];
```

**Comment by RingoD** [comment]
应该通过 `className.propertyName` 的方式调用 WINQ，文档和 sample 的代码中都有详细介绍及类似的例子。

**Comment by summertian4** [comment]
👌，大感谢，一开始没找到 Sample 的位置，可以更新到 README 里
