### ISSUE TITLE
加密后getWritableDatabase()打开数据库性能问题

### ISSUE THREAD

**Issue by zhangxi28** [Tencent/wcdb#202]
e.g. java
e.g. v1.0.2
e.g. android
e.g. maven

_**android 应用中使用了数据库加密后，发现性能很慢
断点log分析后，发现每次getWritableDatabase()方法耗时较长，一般在300ms左右。
而不加密的情况下，这个方法只需要3ms，请问这个怎么优化

**Comment by John-He-928** [comment]
duplicated with #203
