### ISSUE TITLE
加密后数据库的频繁打开和关闭

### ISSUE THREAD

**Issue by zhangxi28** [Tencent/wcdb#203]
加密后数据库的频繁打开和关闭，对性能影响很大，这个有没有好的处理方案？谢谢！

**Comment by lingol** [comment]
别频繁打开关闭DB？

**Comment by zhangxi28** [comment]
因为是聊天消息相关的业务，需要频繁的数据读写，但是每次的操作都是一个事务，数据库的严格写法每次都要打开关闭，这样才能保证数据的准确性。

**Comment by lingol** [comment]
哥们，“数据库的严格写法每次都要打开关闭，这样才能保证数据的准确性”，这个说法哪来的。。。微信都没有这么频繁的打开关闭。

**Comment by zhangxi28** [comment]
BroadcastReceiver receiver = new BroadcastReceiver() {
        @Override
        public void onReceive(Context context, Intent intent) {
            //获取写数据库
            SQLiteDatabase db = dbHelper.getWritableDatabase();
            //insert 操作省略
            //关闭数据库
            db.close();
        }
    };

如上比如一个广播频繁的收到数据，而getWritableDatabase()这个方法是比较耗时的操作，这样就会存在效率问题

**Comment by John-He-928** [comment]
加密DB打开时需要对密钥进行KDF操作，会比较耗时，建议不关闭数据库。

如果非要关闭，可以通过设置`SQLiteCipherSpec.setKDFIteration(...)`，设置一个比较小的KDF迭代次数，比如256（默认是64000），可以改善一点性能，但仍然会比非加密DB慢不少的。
