### ISSUE TITLE
NSNumber值为nil的处理问题

### ISSUE THREAD

**Issue by littlewu0** [Tencent/wcdb#208]
### The language of WCDB

> Objective-C

### The version of WCDB
>  v1.0.3

### The platform of WCDB
>  iOS

### The installation of WCDB
>  Cocoapods

### What's the issue?
场景如下：
在我们的app中，一个NSNumber字段，值为nil和值为0是两种不同的含义，
但是在使用WCDB的过程中，发现，如果一个NSNumber对象的值为nil，存储到数据库会使用数值0来存储，这样对于我们的业务而言，相当于存储了一个错误的值。
(所以我们不得不在给对象初始化一个默认的值，比如-1)

后来我个人针对wcdb的源码做了一点修改来处理NSNumber值为nil的情况。
但是我觉得本质上来说，应该存储成NULL值会更合理一些。
所以我个人希望你们可以考虑下。

感谢各位大神！

- []  I've read and understood the [wiki](https://github.com/Tencent/wcdb/wiki).

**Comment by RingoD** [comment]
感谢反馈，可能会有这个问题，我们后续尝试重现先，看看怎么改

**Comment by SeanChense** [comment]
@RingoD 总觉得拿 NSNumber 的 nil 和 0 当做不同状态是设计不当吧


    NSNumber *number = nil;
    NSInteger integer = [number integerValue];
    printf("integer is %d", integer);

output

   `integer is 0`

**Comment by littlewu0** [comment]
I think "nil" and "0" is different thing. 
"nil" means the field has no value,   but "0" means exact value.

**Comment by RingoD** [comment]
It's fixed and tested in `v1.1.0`, which will be the next version.
