### ISSUE TITLE
escribable.hpp:24:10: 'list' file not found

### ISSUE THREAD

**Issue by Crazyang** [Tencent/wcdb#209]
> Please fill out this template when filing an issue.
>
> Please **remove all grey hint text before submitting**.
>

### The language of WCDB

Objective-C

### The version of WCDB

WCDB, 1.0.6

### The platform of WCDB

IOS

### The installation of WCDB

Cocoapods

### What's the issue?

clone from git compile error  list not found 

。。。。Pods/Headers/Public/WCDB/describable.hpp:24:10: 'list' file not found

- [ ]  I've read and understood the [wiki](https://github.com/Tencent/wcdb/wiki).

**Comment by RingoD** [comment]
这边没有出现类似问题。是否你没有按教程，将文件名后缀改为 `.mm`
