### ISSUE TITLE
当我尝试加密数据库的时候遇到这个bug

### ISSUE THREAD

**Issue by liner02** [Tencent/wcdb#21]
buglog:attempt to re-open an already-closed object
并且导致应用崩溃。
是否是我在不同的线程中打开了相同的数据库引起的。

**Comment by John-He-928** [comment]
看你这个提示似乎是Android的，请说明平台，并将错误堆栈、相关代码贴一下，否则无法帮你排查

**Comment by John-He-928** [comment]
看提示似乎是Android的，请说明平台，并提供错误堆栈和相关代码，否则无法帮你排查

**Comment by unknownx** [comment]
机型：魅族MX4
Android版本：5.1
系统版本：Flyme 6.0.2.0A

`FATAL EXCEPTION: AsyncTask #1
                                                                                   Process: com.tencent.wcdb.sample.encryptdb, PID: 15970
                                                                                   java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                       at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                                    Caused by: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/com.tencent.wcdb.sample.encryptdb/databases/encrypted.db
                                                                                       at com.tencent.wcdb.database.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
                                                                                       at com.tencent.wcdb.database.SQLiteDatabase.endTransaction(SQLiteDatabase.java:530)
                                                                                       at com.tencent.wcdb.database.SQLiteOpenHelper.getDatabaseLockedLast(SQLiteOpenHelper.java:337)
                                                                                       at com.tencent.wcdb.database.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:303)
                                                                                       at com.tencent.wcdb.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:225)
                                                                                       at com.tencent.wcdb.sample.encryptdb.MainActivity$2$1.doInBackground(MainActivity.java:127)
                                                                                       at com.tencent.wcdb.sample.encryptdb.MainActivity$2$1.doInBackground(MainActivity.java:110)
                                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                       at java.lang.Thread.run(Thread.java:818) `

**Comment by John-He-928** [comment]
Crash内容为重复打开已关闭的DB，sample里应该没有关闭DB的操作，可能是`EncryptedDBHelper`中间遇到错误导致的。我这边找一下有没有魅族MX4来复现这个问题。

方便的话，可否提供一下完整logcat日志？

**Comment by unknownx** [comment]
Crash之前的log是这样的：
```
06-14 13:55:45.073 26937-27044/com.tencent.wcdb.sample.encryptdb W/linker: libwcdb.so: unused DT entry: type 0x6ffffffe arg 0x5378
06-14 13:55:45.073 26937-27044/com.tencent.wcdb.sample.encryptdb W/linker: libwcdb.so: unused DT entry: type 0x6fffffff arg 0x3
06-14 13:55:45.076 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB: Initialize JNI module (1/11) CursorWindow...
06-14 13:55:45.076 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB: Initialize JNI module (2/11) FileUtils...
06-14 13:55:45.077 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB: Initialize JNI module (3/11) ChunkedCursorWindow...
06-14 13:55:45.078 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB: Initialize JNI module (4/11) SQLiteConnection...
06-14 13:55:45.079 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB: Initialize JNI module (5/11) SQLiteDebug...
06-14 13:55:45.079 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB: Initialize JNI module (6/11) SQLiteDirectCursor...
06-14 13:55:45.079 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB: Initialize JNI module (7/11) SQLiteGlobal...
06-14 13:55:45.080 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB: Initialize JNI module (8/11) DBBackup...
06-14 13:55:45.081 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB: Initialize JNI module (9/11) DBDumpUtil...
06-14 13:55:45.081 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB: Initialize JNI module (10/11) DBRepair...
06-14 13:55:45.081 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB: Initialize JNI module (11/11) Log...
06-14 13:55:45.089 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB.SQLiteConnectionPool: Max connection pool size is 4.
06-14 13:55:45.091 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB: Initialize SQLite connection module 'MMFTS'...
06-14 13:55:45.092 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB.SQLiteConnection: Opened connection 0xae840808 with label '/data/data/com.tencent.wcdb.sample.encryptdb/databases/encrypted.db'
06-14 13:55:45.093 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB.SQLiteConnection: sqlite3_key verification passed.
06-14 13:55:45.822 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB.SQLiteConnection: executeForString took 723ms - succeeded, sql="PRAGMA journal_mode=WAL"
06-14 13:55:45.826 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB: Initialize SQLite connection module 'MMFTS'...
06-14 13:55:45.826 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB.SQLiteConnection: Opened connection 0xae840c08 with label '/data/data/com.tencent.wcdb.sample.encryptdb/databases/encrypted.db'
06-14 13:55:45.826 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB.SQLiteConnection: sqlite3_key verification passed.
06-14 13:55:46.413 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB.SQLiteConnection: executeForString took 586ms - succeeded, sql="PRAGMA journal_mode"
06-14 13:55:46.415 26937-27044/com.tencent.wcdb.sample.encryptdb I/EncryptedDBHelper: Migrating plain-text database to encrypted one.
06-14 13:55:46.417 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB: Initialize SQLite connection module 'MMFTS'...
06-14 13:55:46.417 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB.SQLiteConnection: Opened connection 0xae840808 with label '/data/data/com.tencent.wcdb.sample.encryptdb/databases/encrypted.db'
06-14 13:55:46.417 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB.SQLiteConnection: sqlite3_key verification passed.
06-14 13:55:47.003 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB.SQLiteConnection: executeForString took 585ms - succeeded, sql="PRAGMA journal_mode"
06-14 13:55:47.017 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB.SQLiteConnectionPool: Max connection pool size is 1.
06-14 13:55:47.018 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB.SQLite: [SQLite ErrCode: 283] recovered 2 frames from WAL file /data/data/com.tencent.wcdb.sample.encryptdb/databases/plain-text.db-wal
06-14 13:55:47.019 26937-27044/com.tencent.wcdb.sample.encryptdb E/WCDB.SQLite: [SQLite ErrCode: 11] database corruption at line 61542 of [bbd85d235f]
06-14 13:55:47.019 26937-27044/com.tencent.wcdb.sample.encryptdb W/WCDB.SQLite: [SQLite ErrCode: 26] statement aborts at 4: [ATTACH DATABASE '/data/data/com.tencent.wcdb.sample.encryptdb/databases/plain-text.db' AS old;] file is encrypted or is not a database
06-14 13:55:47.020 26937-27044/com.tencent.wcdb.sample.encryptdb I/WCDB.SQLiteConnection: executeForChangedRowCount took 2ms - failed, sql="ATTACH DATABASE '/data/data/com.tencent.wcdb.sample.encryptdb/databases/plain-text.db' AS old;", exception="file is encrypted or is not a database (code 26, errno 0): ", changedRows=0
06-14 13:55:47.021 26937-27044/com.tencent.wcdb.sample.encryptdb E/WCDB.DefaultDatabaseErrorHandler: Corruption reported by sqlite on database: /data/data/com.tencent.wcdb.sample.encryptdb/databases/encrypted.db
06-14 13:55:47.025 26937-27044/com.tencent.wcdb.sample.encryptdb E/WCDB.DefaultDatabaseErrorHandler: Remove database file: /data/data/com.tencent.wcdb.sample.encryptdb/databases/encrypted.db
06-14 13:55:47.026 26937-27044/com.tencent.wcdb.sample.encryptdb E/WCDB.DefaultDatabaseErrorHandler: Could not create directory for corrupted database. Corruption backup may be unavailable.
06-14 13:55:47.027 26937-27044/com.tencent.wcdb.sample.encryptdb W/WCDB.SQLite: [SQLite ErrCode: 28] file renamed while open: /data/data/com.tencent.wcdb.sample.encryptdb/databases/encrypted.db

```

**Comment by yaya2212** [comment]
请问这个问题修复了吗？我在小米4上也是一直crash,相同的错误

**Comment by John-He-928** [comment]
@unknownx 你这是数据库损坏了，encryptdb示例是先init plain-text DB，然后演示从plain-text迁移到encrypted，不是演示修复功能的，因此没处理DB损坏的情况，使用常规损坏处理逻辑，遇到损坏则关闭DB并重命名（等待以后修复）。

DB是存在 /data 目录的，卸载重装或清除数据可以恢复。

@liner02 @yaya2212 你们也可以试试是不是同样问题

**Comment by yaya2212** [comment]
@John-He-928  谢谢回复  嗯，，就是数据库损坏了。。应该先init一下的

**Comment by zhangkehu** [comment]
我做升级的时候一直这个错误，是哪里操作不对吗？

06-15 18:31:18.374 22379-22575/com.view.asim.gov I/WCDB: Initialize JNI module (1/11) CursorWindow...
06-15 18:31:18.374 22379-22575/com.view.asim.gov V/WCDB.JNIHelp: Registering com/tencent/wcdb/CursorWindow natives
06-15 18:31:18.374 22379-22575/com.view.asim.gov I/WCDB: Initialize JNI module (2/11) FileUtils...
06-15 18:31:18.374 22379-22575/com.view.asim.gov V/WCDB.JNIHelp: Registering com/tencent/wcdb/FileUtils natives
06-15 18:31:18.374 22379-22575/com.view.asim.gov I/WCDB: Initialize JNI module (3/11) ChunkedCursorWindow...
06-15 18:31:18.374 22379-22575/com.view.asim.gov V/WCDB.JNIHelp: Registering com/tencent/wcdb/database/ChunkedCursorWindow natives
06-15 18:31:18.375 22379-22575/com.view.asim.gov V/WCDB.JNIHelp: Registering com/tencent/wcdb/database/SQLiteAsyncQuery natives
06-15 18:31:18.375 22379-22575/com.view.asim.gov I/WCDB: Initialize JNI module (4/11) SQLiteConnection...
06-15 18:31:18.375 22379-22575/com.view.asim.gov V/WCDB.JNIHelp: Registering com/tencent/wcdb/database/SQLiteConnection natives
06-15 18:31:18.376 22379-22575/com.view.asim.gov I/WCDB: Initialize JNI module (5/11) SQLiteDebug...
06-15 18:31:18.376 22379-22575/com.view.asim.gov V/WCDB.JNIHelp: Registering com/tencent/wcdb/database/SQLiteDebug natives
06-15 18:31:18.376 22379-22575/com.view.asim.gov I/WCDB: Initialize JNI module (6/11) SQLiteDirectCursor...
06-15 18:31:18.376 22379-22575/com.view.asim.gov V/WCDB.JNIHelp: Registering com/tencent/wcdb/database/SQLiteDirectQuery natives
06-15 18:31:18.377 22379-22575/com.view.asim.gov I/WCDB: Initialize JNI module (7/11) SQLiteGlobal...
06-15 18:31:18.377 22379-22575/com.view.asim.gov V/WCDB.JNIHelp: Registering com/tencent/wcdb/database/SQLiteGlobal natives
06-15 18:31:18.377 22379-22575/com.view.asim.gov I/WCDB: Initialize JNI module (8/11) DBBackup...
06-15 18:31:18.377 22379-22575/com.view.asim.gov V/WCDB.JNIHelp: Registering com/tencent/wcdb/repair/BackupKit natives
06-15 18:31:18.377 22379-22575/com.view.asim.gov V/WCDB.JNIHelp: Registering com/tencent/wcdb/repair/RecoverKit natives
06-15 18:31:18.378 22379-22575/com.view.asim.gov I/WCDB: Initialize JNI module (9/11) DBDumpUtil...
06-15 18:31:18.378 22379-22575/com.view.asim.gov V/WCDB.JNIHelp: Registering com/tencent/wcdb/repair/DBDumpUtil natives
06-15 18:31:18.378 22379-22575/com.view.asim.gov I/WCDB: Initialize JNI module (10/11) DBRepair...
06-15 18:31:18.378 22379-22575/com.view.asim.gov V/WCDB.JNIHelp: Registering com/tencent/wcdb/repair/RepairKit natives
06-15 18:31:18.378 22379-22575/com.view.asim.gov I/WCDB: Initialize JNI module (11/11) Log...
06-15 18:31:18.378 22379-22575/com.view.asim.gov V/WCDB.JNIHelp: Registering com/tencent/wcdb/support/Log natives
06-15 18:31:18.462 22379-22661/com.view.asim.gov I/WCDB.SQLiteConnectionPool: Max connection pool size is 5.
06-15 18:31:18.468 22379-22661/com.view.asim.gov I/WCDB: Initialize SQLite connection module 'MMFTS'...
06-15 18:31:18.477 22379-22661/com.view.asim.gov I/WCDB.SQLiteConnection: Opened connection 0xba173e50 with label '/storage/emulated/0/Android/data/com.view.asim.gov/.asim/data/enterprise-f59fd8bc10ea073c10817339c0709c2e/dc2069c4b88506f9dc23b3553bba1126/database/dc2069c4b88506f9dc23b3553bba1126-encrypted.db'
06-15 18:31:18.479 22379-22661/com.view.asim.gov I/WCDB.SQLiteConnection: sqlite3_key verification passed.
06-15 18:31:18.491 22379-22661/com.view.asim.gov I/WCDB: Initialize SQLite connection module 'MMFTS'...
06-15 18:31:18.491 22379-22661/com.view.asim.gov I/WCDB.SQLiteConnection: Opened connection 0xba185fe0 with label '/storage/emulated/0/Android/data/com.view.asim.gov/.asim/data/enterprise-f59fd8bc10ea073c10817339c0709c2e/dc2069c4b88506f9dc23b3553bba1126/database/dc2069c4b88506f9dc23b3553bba1126-encrypted.db'
06-15 18:31:18.492 22379-22661/com.view.asim.gov I/WCDB.SQLiteConnection: sqlite3_key verification passed.
06-15 18:31:18.556 22379-22661/com.view.asim.gov W/WCDB.SQLite: [SQLite ErrCode: 1] no such table: old.sqlite_master
06-15 18:31:18.556 22379-22661/com.view.asim.gov W/WCDB.SQLite: [SQLite ErrCode: 1] statement aborts at 1: [SELECT sqlcipher_export('main', 'old');] SQL logic error or missing database
06-15 18:31:18.559 22379-22661/com.view.asim.gov I/WCDB.SQLiteConnection: executeForString took 1ms - failed, sql="SELECT sqlcipher_export('main', 'old');", exception="SQL logic error or missing database (code 1, errno 0): "
06-15 18:31:18.598 22379-22661/com.view.asim.gov W/System.err: com.tencent.wcdb.database.SQLiteException: SQL logic error or missing database (code 1, errno 0): 
06-15 18:31:18.601 22379-22661/com.view.asim.gov W/System.err:     at com.tencent.wcdb.database.SQLiteConnection.nativeExecuteForString(Native Method)
06-15 18:31:18.601 22379-22661/com.view.asim.gov W/System.err:     at com.tencent.wcdb.database.SQLiteConnection.executeForString(SQLiteConnection.java:729)
06-15 18:31:18.601 22379-22661/com.view.asim.gov W/System.err:     at com.tencent.wcdb.database.SQLiteSession.executeForString(SQLiteSession.java:674)
06-15 18:31:18.601 22379-22661/com.view.asim.gov W/System.err:     at com.tencent.wcdb.database.SQLiteStatement.simpleQueryForString(SQLiteStatement.java:126)
06-15 18:31:18.601 22379-22661/com.view.asim.gov W/System.err:     at com.tencent.wcdb.DatabaseUtils.stringForQuery(DatabaseUtils.java:886)
06-15 18:31:18.601 22379-22661/com.view.asim.gov W/System.err:     at com.tencent.wcdb.DatabaseUtils.stringForQuery(DatabaseUtils.java:874)
06-15 18:31:18.602 22379-22661/com.view.asim.gov V/WCDB.SQLiteConnection: Closing connection 0xba185fe0
06-15 18:31:18.604 22379-22661/com.view.asim.gov V/WCDB.SQLiteConnection: Closing connection 0xba173e50
06-15 18:31:18.606 22379-22661/com.view.asim.gov W/System.err:     at com.tencent.wcdb.database.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
06-15 18:31:18.606 22379-22661/com.view.asim.gov W/System.err:     at com.tencent.wcdb.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1501)
06-15 18:31:18.606 22379-22661/com.view.asim.gov W/System.err:     at com.tencent.wcdb.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1444)

**Comment by John-He-928** [comment]
@zhangkehu 请贴代码。

看你的Log，似乎 "old" 数据库是空的

**Comment by zhangkehu** [comment]
不是的，数据不是空的，我特意在老版本上产生数据之后才升级的

**Comment by zhangkehu** [comment]
@John-He-928 db文件180kb，里面有一些数据

**Comment by John-He-928** [comment]
麻烦你贴一下代码，报错是找不到'old'数据库的sqlite_master表

**Comment by zhangkehu** [comment]
@John-He-928 

public void onCreate(SQLiteDatabase db) {
        // Check whether old plain-text database exists, if so, export it
        // to the new, encrypted one.
        File oldDbFile = getNormalDatabasePath(mName);
        if (oldDbFile.exists()) {

            Log.i(TAG, "Migrating plain-text database to encrypted one:."+oldDbFile.getAbsolutePath());

            // SQLiteOpenHelper begins a transaction before calling onCreate().
            // We have to end the transaction before we can attach a new database.
            db.endTransaction();

            // Attach old database to the newly created, encrypted database.
            String sql = String.format("ATTACH DATABASE %s AS old;",
                    DatabaseUtils.sqlEscapeString(oldDbFile.getPath()));
            db.execSQL(sql);

            // Export old database.
            db.beginTransaction();
            DatabaseUtils.stringForQuery(db, "SELECT sqlcipher_export('main', 'old');", null);
            db.setTransactionSuccessful();
            db.endTransaction();

            // Get old database version for later upgrading.
            int oldVersion = (int) DatabaseUtils.longForQuery(db, "PRAGMA old.user_version;", null);

            // Detach old database and enter a new transaction.
            db.execSQL("DETACH DATABASE old;");

            // Old database can be deleted now.
            oldDbFile.delete();

            // Before further actions, restore the transaction.
            db.beginTransaction();

            // Check if we need to upgrade the schema.
            if (oldVersion > mVersion) {
                onDowngrade(db, oldVersion, mVersion);
            } else if (oldVersion < mVersion) {
                onUpgrade(db, oldVersion, mVersion);
            }
        } else {
            Log.i(TAG, "Creating new encrypted database.");
        }

        // OPTIONAL: backup master info for corruption recovery.
//        RepairKit.MasterInfo.save(db, db.getPath() + "-mbak", mPassphrase.getBytes());
    }

PS：数据库文件在那个目录的，数据库文件路径是自定义的路径，在sd卡里

**Comment by John-He-928** [comment]
应该是ATTACH了不存在的路径作为old DB，试试将 `oldDbFile.getPath()` 换成 `oldDbFile.getAbsolutePath()`，还有看看
```java
        String sql = String.format("ATTACH DATABASE %s AS old;",
                DatabaseUtils.sqlEscapeString(oldDbFile.getPath()));
```
的值是多少。

**Comment by zhangkehu** [comment]
@John-He-928 
我只加了打印：check sql,日志如下：
06-16 23:57:02.950 1811-2040/com.view.asim.gov I/EncryptedDBHelper: Migrating plain-text database to encrypted one:/storage/emulated/0/Android/data/com.view.asim.gov/.asim/data/enterprise-f59fd8bc10ea073c10817339c0709c2e/4273d364fa444305225cc9882ba984b/database/4273d364fa444305225cc9882ba984b
06-16 23:57:02.959 1811-2040/com.view.asim.gov I/EncryptedDBHelper: check sql:ATTACH DATABASE '/storage/emulated/0/Android/data/com.view.asim.gov/.asim/data/enterprise-f59fd8bc10ea073c10817339c0709c2e/4273d364fa444305225cc9882ba984b/database/4273d364fa444305225cc9882ba984b' AS old;

Migrating...那里的路径是absolutePath，check sql...那里是path，代码片段：


```
 Log.i(TAG, "Migrating plain-text database to encrypted one:"+oldDbFile.getAbsolutePath());

            // SQLiteOpenHelper begins a transaction before calling onCreate().
            // We have to end the transaction before we can attach a new database.
            db.endTransaction();

            // Attach old database to the newly created, encrypted database.
            String sql = String.format("ATTACH DATABASE %s AS old;",
                    DatabaseUtils.sqlEscapeString(oldDbFile.getPath()));
            Log.i(TAG,"check sql:"+sql);
```

**Comment by John-He-928** [comment]
我注意到了，你的加密DB名字有`.db`后缀，而明文的没有，是否是这样原因？

```
06-15 18:31:18.477 22379-22661/com.view.asim.gov I/WCDB.SQLiteConnection: Opened connection 0xba173e50 with label '/storage/emulated/0/Android/data/com.view.asim.gov/.asim/data/enterprise-f59fd8bc10ea073c10817339c0709c2e/dc2069c4b88506f9dc23b3553bba1126/database/dc2069c4b88506f9dc23b3553bba1126-encrypted.db'
```

```
06-16 23:57:02.959 1811-2040/com.view.asim.gov I/EncryptedDBHelper: check sql:ATTACH DATABASE '/storage/emulated/0/Android/data/com.view.asim.gov/.asim/data/enterprise-f59fd8bc10ea073c10817339c0709c2e/4273d364fa444305225cc9882ba984b/database/4273d364fa444305225cc9882ba984b' AS old;
```

你的非加密DB名称是“4273d364fa444305225cc9882ba984b”还是“4273d364fa444305225cc9882ba984b**.db**”？

因为不知道`getNormalDatabasePath(mName);`的实现，你也许可以试试打开'/storage/emulated/0/Android/data/com.view.asim.gov/.asim/data/enterprise-f59fd8bc10ea073c10817339c0709c2e/4273d364fa444305225cc9882ba984b/database/4273d364fa444305225cc9882ba984b'这个文件，看看是不是空的。

另外，old数据库是否本身就是加密数据库？如果本身是加密并且你不打算换密钥，那不需要使用`sqlite_export`来迁移

**Comment by zhangkehu** [comment]
@John-He-928 非加密的文件名没有.db的后缀，那个文件目录我看过没问题的，我在那个目录可以直接用sqliteEditor查看的。

**Comment by John-He-928** [comment]
@zhangkehu 试试
```sql
ATTACH DATABASE 'filename.db' AS old KEY '';
```
指定ATTACH的数据库使用空密钥（不加密）

**Comment by zhangkehu** [comment]
@John-He-928 虽然我知道这样不一定起作用，所以拖到今天又尝试了你上面说的，加个 KEY '',还是那个错误。
```
check sql:ATTACH DATABASE '/storage/emulated/0/Android/data/com.view.asim.jct/.asim/data/enterprise-f59fd8bc10ea073c10817339c0709c2e/9e112428295852d8f7556290ccc139f7/database/9e112428295852d8f7556290ccc139f7' AS old KEY '';
com.view.asim.jct W/WCDB.SQLite: [SQLite ErrCode: 1] no such table: old.sqlite_master
com.view.asim.jct W/WCDB.SQLite: [SQLite ErrCode: 1] statement aborts at 1: [SELECT sqlcipher_export('main', 'old');] SQL logic error or missing database
```

是不是attach那一步出问题了？ no_such table:old.sqlite_master

**Comment by zhangkehu** [comment]
@John-He-928 
![image](https://user-images.githubusercontent.com/9359883/27379091-815eee9a-56ac-11e7-945b-f278c82056c0.png)我那里的db对象是将要加密的数据库对象，这里对吗？

**Comment by zhangkehu** [comment]
额，我想了一下应该是要加密的对象

**Comment by John-He-928** [comment]
@zhangkehu 是ATTACH的问题，SELECT的时候用的连接没有挂载old数据库。我这边复现不了，看你的描述，可能是连接池导致，ATTACH执行和SELECT执行不在同一个连接（也没有同步过去），你可以先不打开连接池试试。
```java
SQLiteOpenHelper dbHelper = new YourDBHelper();
// 不使用WAL和连接池
dbHelper.setWriteAheadLoggingEnabled(false);
// 打开DB
db = dbHelper.getWritableDatabase();
```
如果这个跑得通，则应该是连接池的问题。

**Comment by zhangkehu** [comment]
@John-He-928 刚才又试了一下，setWriteAheadLoggingEnabled(false);之后
，还是no such table: old.sqlite_master。

**Comment by zhangkehu** [comment]
@John-He-928在前面的基础上 改成`SQLiteDatabase.openOrCreateDatabase(file,password.getBytes(), mFactory,null);`这个方法打开ok了，之前是`SQLiteDatabase.openOrCreateDatabase(file,password.getBytes(), mFactory,null,cupCount)`.
