### ISSUE TITLE
Wrong GitHub repo 

### ISSUE THREAD

**Issue by CodeEagle** [Tencent/wcdb#210]
- [x]  I've read and understood the [wiki](https://github.com/Tencent/wcdb/wiki).

> 在工程目录下创建 cartfile 文件，并添加 github "Tencent/WCDBSwift"。
[Ref](https://github.com/Tencent/wcdb/wiki/Swift-安装与兼容性)

`并添加 github "Tencent/WCDBSwift"` -> `并添加 github "Tencent/WCDB"`

**Comment by RingoD** [comment]
It's fixed. Thx.
