### ISSUE TITLE
Error happens when creating a table

### ISSUE THREAD

**Issue by vulgur** [Tencent/wcdb#211]
### The language of WCDB
Swift

### The version of WCDB

Integrated by Cocoapods, so assume it as the latest

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?

> Please post the outputs or screenshots for an error.

![screen shot 2018-01-03 at 12 45 09](https://user-images.githubusercontent.com/3339536/34509910-7182efb2-f08a-11e7-94a0-b165a28fcf7e.png)

![screen shot 2018-01-03 at 13 41 23](https://user-images.githubusercontent.com/3339536/34510105-ef966aa4-f08b-11e7-8217-058cdb440ce0.png)

> Please explain what you want by example or code.

Creating database was fine, but some error happened when creating the table. Here's the relevant code:
```swift
let home = NSHomeDirectory()
        let path = URL.init(string: home)!.appendingPathComponent("Documents").appendingPathComponent("demo.db")
        let database = Database(withPath: path.absoluteString)
        print("db path:", database.path) // this line is output 
        do {
            try database.create(table: "food", of: Food.self) // the program hangs up here
            print("food exists: ", try database.isTableExists("food"))
        } catch let error as NSError {
            print(error)
        }
```

The only model file was created by template and I only changed class name.

```swift
import Foundation
import WCDBSwift

class Food: TableCodable {
    //Your own properties
    let variable1: Int = 0
    var variable2: String? // Optional if it would be nil in some WCDB selection
    var variable3: Double? // Optional if it would be nil in some WCDB selection
    let unbound: Date? = nil

    enum CodingKeys: String, CodingTableKey {
        typealias Root = Food

        //List the properties which should be bound to table
        case variable1 = "custom_name"
        case variable2
        case variable3

        static let objectRelationalMapping = TableBinding(CodingKeys.self)
       ...

```
I've also tried reduce the properties to only one with the type of Int, but it still didn't work.

According the assertion of screenshot above, this is a bug or something wrong in my code?

- [x]  I've read and understood the [wiki](https://github.com/Tencent/wcdb/wiki).

**Comment by RingoD** [comment]
Try to use var for variable1

**Comment by vulgur** [comment]
It worked.
Thanks a lot! @RingoD

**Comment by RingoD** [comment]
In Swift, constant can only be init once. So an inited `variable1` can't be exposed from database.
I will add more tips in later version.

**Comment by RingoD** [comment]
Developers will receive a new hint: `The following keys: \(keys) can't be decoded.  Try to change their definition from let to var or report an issue to us.` in next version.
8536cbee74993e58384f062e5e1f55f9eea2ad70

**Comment by vulgur** [comment]
Cool @RingoD
