### ISSUE TITLE
How to use `getObject` in swift?

### ISSUE THREAD

**Issue by zhongdom** [Tencent/wcdb#213]
- Swift
- 1.0.6
- iOS
- Cocoapods

This is my model:

```
struct ArticleModel: TableCodable {
    
    var articleId: Int
    var response: Data
    
    enum CodingKeys: String, CodingTableKey {
        typealias Root = ArticleModel
        static let objectRelationalMapping = TableBinding(CodingKeys.self)
        
        case articleId = "id"
        case response
        
        static var columnConstraintBindings: [CodingKeys: ColumnConstraintBinding]? {
            return [
                articleId: ColumnConstraintBinding(isPrimary: true, isAutoIncrement: true, isUnique: true)
            ]
        }
    }
}
```

when I execute 

```
let temp = try DBHelper.share.database.getObject(on: ArticleModel.Properties.articleId, fromTable: String(describing: ArticleModel.self), where: ArticleModel.Properties.articleId == self.articleId!)
``` 

 I got the error

```
Cannot convert value of type 'ArticleModel.CodingKeys' to expected argument type '[PropertyConvertible]'
```

What's wrong with my code? 

- [x]  I've read and understood the [wiki](https://github.com/Tencent/wcdb/wiki). It seems not help.

**Comment by RingoD** [comment]
The type of `temp` should be specific to trigger the generic.
```swift
let temp: ArticleModel = try DBHelper.share.database.getObject(on: ArticleModel.Properties.articleId, fromTable: String(describing: ArticleModel.self), where: ArticleModel.Properties.articleId == self.articleId!)
```

Check the tutorial or sample code for further information.

**Comment by zhongdom** [comment]
@RingoD  It seems not help.

### Fisrt modify and error
```
let temp: ArticleModel = try DBHelper.share.database.getObject(on: ArticleModel.Properties.articleId, fromTable: String(describing: ArticleModel.self), where: ArticleModel.Properties.articleId == self.articleId!)
```
```
'getObject' produces 'Object?', not the expected contextual result type 'ArticleModel'
```

### Second modify and error

```
let temp: ArticleModel? = try DBHelper.share.database.getObject(on: ArticleModel.Properties.articleId, fromTable: String(describing: ArticleModel.self), where: ArticleModel.Properties.articleId == self.articleId!)
```
```
Cannot convert value of type 'ArticleModel.CodingKeys' to expected argument type '[PropertyConvertible]'
```

**Comment by RingoD** [comment]
I try to use the same code and no compiler error occurs.

Try to remove some code to debug it. For example, remove the `where` condition.

By the way, it will still failed after compiled. Since the partial selection can't init the `response` variable, it would be better to make it optional.

**Comment by zhongdom** [comment]
@RingoD 

Finally I change my code in this way, It works
```
let temp: ArticleModel? = try DBHelper.share.database.getObject(fromTable: String(describing: ArticleModel.self), where: ArticleModel.Properties.articleId.in(self.articleId!))
```

But I still don't know why I can't write the condition like `SampleConvenient.Properties.intValue > 0`  in the sample code. why?

**Comment by RingoD** [comment]
I can't find the wrong code here. Or maybe you can post a sample project which can reproduce it.

**Comment by zhongdom** [comment]
@RingoD 
[This is error demo](https://github.com/zhongdom/ErrorRepetion)

**Comment by RingoD** [comment]
It will be fixed by adding `import WCDBSwift` at the top of `DBHelper.swift`, which is a strange behavior of Swift.

**Comment by zhongdom** [comment]
wow，adding `import WCDBSwift` at the top of  `ViewController.swift` , It works.
Thanks for you patiently help!
