### ISSUE TITLE
1.0.6 OC版本 安装报错

### ISSUE THREAD

**Issue by applejian** [Tencent/wcdb#215]
### The version of WCDB

> e.g. v1.0.6

错误情况 1
pod 安装成功 xcode 编译报 parse.h not found

错误情况 2
pod 安装不成功

控制台：

> Running prepare command
   $ /bin/bash -c  set -e git submodule update --init sqlcipher;                           cd tools/templates; sh install.sh; cd ../..;                           cd sqlcipher; make
   -f Makefile.preprocessed; cd ..;                           cp sqlcipher/ext/fts3/fts3_tokenizer.h sqlcipher/
   Submodule 'sqlcipher' (https://github.com/Tencent/sqlcipher.git) registered for path 'sqlcipher'
   Cloning into '/Users/yans/Library/Caches/CocoaPods/Pods/Release/WCDB/1.0.6-4d292/sqlcipher'...
   Submodule path 'sqlcipher': checked out 'd4726337010f60408a9c99633b35f01a8a7ae2de'
   usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
          cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
[!] /bin/bash -c 
set -e
git submodule update --init sqlcipher;                           cd tools/templates; sh install.sh; cd ../..;                           cd sqlcipher; make -f Makefile.preprocessed; cd ..;                           cp sqlcipher/ext/fts3/fts3_tokenizer.h sqlcipher/

Submodule path 'sqlcipher': checked out 'd4726337010f60408a9c99633b35f01a8a7ae2de'
Submodule 'sqlcipher' (https://github.com/Tencent/sqlcipher.git) registered for path 'sqlcipher'
Cloning into '/Users/yans/Library/Caches/CocoaPods/Pods/Release/WCDB/1.0.6-4d292/sqlcipher'...
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory

/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:69:in `execute_command'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:27:in `block in executable'

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Please post the outputs or screenshots for an error.
>
> Please explain what you want by example or code.

**Comment by RingoD** [comment]
应该是你的本地文件夹的状态导致的错误，我稍后加个容错。
然后，麻烦协助定位下问题，看这边能否处理下这种错误：

先找到你用 `pod install` 拉下来的代码，然后到 `tools/templates` 目录 `cat install.sh`，然后贴下输出

**Comment by applejian** [comment]
经过排查是软件导致的路径不通问题 问题已解决 
整理如下 

~/Library/Developer/Xcode/Templates/File Templates/
有WCDB 相关的 先删除

~/Library/Developer/Xcode/UserData/
有CodeSnippets相关的删除
