### ISSUE TITLE
Bad food crash

### ISSUE THREAD

**Issue by CrashRain** [Tencent/wcdb#217]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.5

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> 发生一次Bad food闪退，下面是crash报告相关的截图
<img width="1016" alt="1" src="https://user-images.githubusercontent.com/5134517/34639828-70cef8b4-f322-11e7-867b-eb2f97aa5ab7.png">
<img width="721" alt="2" src="https://user-images.githubusercontent.com/5134517/34639831-776a0e7a-f322-11e7-9457-1e67b5ab61db.png">
<img width="1003" alt="3" src="https://user-images.githubusercontent.com/5134517/34639832-7b3aa0d2-f322-11e7-8531-0b844cf7a67e.png">

**Comment by RingoD** [comment]
从 crash 中的 SIGKILL、SPRINGBOARD 来看，这个应该是被系统 kill 了。你可以根据 iOS 的机制自查下，如启动超时、主线程卡顿时间过长等

**Comment by CrashRain** [comment]
做了分批处理和子线程优化，这段时间没有再出现了，谢谢！
另外请问为何日志中会连续出现两次sqlite3MemRealloc + 398376的调用？

**Comment by RingoD** [comment]
Crash Report 截取堆栈的机制。两个地址相同，没有什么问题。
