### ISSUE TITLE
Objc 下全文查找 snippet() 返回的内容重叠

### ISSUE THREAD

**Issue by xmkevin** [Tencent/wcdb#218]
### The language of WCDB
 Objective-C

### The version of WCDB
v1.0.5

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?

数据库字段内容是 "我今天很高兴",  使用 snippet() 返回的内容为  @"我今天很高兴我今天很高兴今天很高兴天很高兴很<b>高兴</b>高兴"

**Comment by zhanghesheng** [comment]
我也遇到了同样的问题 @xmkevin  请问@RingoD 这个bug有解决的吗？或者解决的思路是怎样的？

**Comment by RingoD** [comment]
Yes, it's already fixed and it will be released in next version. 
The test is here: https://github.com/Tencent/wcdb/blob/feature/repair_2.0/objc/testcase/test/fts/DatabaseTests%2BFTS.mm

**Comment by zhanghesheng** [comment]
![2018-08-03 11 26 06](https://user-images.githubusercontent.com/7437146/43622725-4f37c3ba-9710-11e8-9ef5-55ba9f228afe.png)
![2018-08-03 11 26 14](https://user-images.githubusercontent.com/7437146/43622742-5ace1e36-9710-11e8-84cf-a764703a19b8.png)

the test results is still  repeated @RingoD

**Comment by RingoD** [comment]
@zhanghesheng  Got it. I think it can be fixed using FTS5. We will upgrade the FTS recently.

**Comment by include11** [comment]
> @zhanghesheng Got it. I think it can be fixed using FTS5. We will upgrade the FTS recently.

the newest version, upgrade the FTS5?

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
