### ISSUE TITLE
Exception 'Library not loaded' after installing with Carthage

### ISSUE THREAD

**Issue by jojoting** [Tencent/wcdb#219]
### The language of WCDB

> Swift

### The version of WCDB

> v1.0.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Carthage

### What's the issue?

> Console log:
> ![Log](https://user-images.githubusercontent.com/9513847/34706054-aeac9d52-f53f-11e7-902d-9a26573e689f.jpg)
>
> Project General:
> ![General](https://user-images.githubusercontent.com/9513847/34706091-085ad3c8-f540-11e7-892b-23573b0a2f12.png)
>
> Project Build Phases:
> ![Build-Phases](https://user-images.githubusercontent.com/9513847/34706092-089455c6-f540-11e7-82fb-f7b16b227673.png)

**Comment by RingoD** [comment]
It's fixed at v1.0.6.1, which is a new tag for this issue.
You can clean the cache and execute `carthage update` again. Then add `WCDBSwift.framework`, `sqlcipher.swift.framework` and `sqliterk.swift.framework` into your project.

Check the installation tutorial for further information.

**Comment by jojoting** [comment]
Works on v1.0.6.1
