### ISSUE TITLE
SQLCipher 依赖

### ISSUE THREAD

**Issue by heistings** [Tencent/wcdb#222]
### The language of WCDB

Objective-C

### The version of WCDB

1.0.6

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

既然依赖 SQLCipher，为什么不通过 pod 依赖？

**Comment by RingoD** [comment]
SQLCipher is already linked by pod of WCDB. What's your issue?

**Comment by RingoD** [comment]
no reply.
