### ISSUE TITLE
It should not be failed. If you think it's a bug, please report an issue to us.

### ISSUE THREAD

**Issue by al1020119** [Tencent/wcdb#225]
### The language of WCDB

> Swift 

### The version of WCDB

> v1.0.5

### The platform of WCDB

>  iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> It should not be failed. If you think it's a bug, please report an issue to us.

    func generateColumnDef(with key: CodingTableKeyBase) -> ColumnDef {
        let codingTableKey = key as? CodingTableKeyType
        assert(codingTableKey != nil, "[\(key)] must conform to CodingTableKey protocol.")
        let columnType = columnTypes[codingTableKey!.stringValue]
        assert(columnType != nil, "It should not be failed. If you think it's a bug, please report an issue to us.")
        var columnDef = ColumnDef(with: codingTableKey!, and: columnType!)
        if let index = columnConstraintBindings?.index(forKey: codingTableKey!) {
            columnDef = columnConstraintBindings![index].value.generateColumnDef(with: columnDef)
        }
        return columnDef
    }

**Comment by RingoD** [comment]
Check the correctness of your posted information please, since the first Swift version is v1.0.6.

Maybe you can post your ORM definition or check this issue: #211
