### ISSUE TITLE
sqlite 加密之后无法压缩

### ISSUE THREAD

**Issue by xxx50236** [Tencent/wcdb#226]
### The language of WCDB

>  Swift

### The platform of WCDB

>  iOS

### What's the issue?

> 现在应用里在使用 WCDB 的加密功能，发现加密之后无法压缩数据包，原本的数据包是比较大，不知有没有什么好的建议，感谢
>
>

**Comment by RingoD** [comment]
Compression and encryption is irrelevant. If you think it's an issue, please provide more information.

**Comment by RingoD** [comment]
no reply.
