### ISSUE TITLE
如何检测表是否包含某个字段

### ISSUE THREAD

**Issue by haotiankeji** [Tencent/wcdb#228]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Please post the outputs or screenshots for an error.
>
> Please explain what you want by example or code.

**Comment by RingoD** [comment]
Please provide basic information as the issue template suggested.

**Comment by RingoD** [comment]
no reply.
