### ISSUE TITLE
导入头文件报错

### ISSUE THREAD

**Issue by losedMemory** [Tencent/wcdb#229]
在已有项目中导入WCDB头文件报错
![image](https://user-images.githubusercontent.com/18753243/35034563-8df99e5a-fba9-11e7-8c66-69931233fae2.png)

**Comment by losedMemory** [comment]
@RingoD 我用pod集成WCDB,在项目文件中引用#import <WCDB/WCDB.h>,并且将.m改成.mm会报这个错,但是如果新建一个空白的项目再集成WCDB,引用就不会报错,WCDB是和别的框架有冲突吗

**Comment by RingoD** [comment]
You should rename the extension from `.m` to `.mm` for all files included `WCDB.h`.

**Comment by RingoD** [comment]
no reply.

**Comment by kb824824** [comment]
@losedMemory 老哥，这问题最终怎么解决的？我也遇到了...
