### ISSUE TITLE
iOS文件编译设置

### ISSUE THREAD

**Issue by 312362115** [Tencent/wcdb#23]
`由于WCDB是基于Objective-C++，因此需要将源文件对应的后缀.m改为.mm`

所以如果`Message`在头文件引入`WCDB.h`, 所有用到`Message`的地方都必须将源文件后缀改成.mm, 否则提示`'list' file not found` ??

**Comment by 312362115** [comment]
并且没办法在类似`pch`文件的地方引入 `WCDB.h`

**Comment by 312362115** [comment]
如果一个class引入了`WCDB.h`, 并且这个class在所有地方都有用到, 会导致几乎整个app的`.m`文件都要改成`.mm` ??

**Comment by 312362115** [comment]
xcode对于`.mm`文件的自动补全, 语法高亮太差了.
所以改成`.mm`之后, `WCDB`使用起来特别费劲

**Comment by RingoD** [comment]
* `.mm`是对应Objective-C++代码文件后缀
    * 如果你在源文件里引用WCDB，则只需要将对应源文件的`.m`改为`.mm`。
    * 如果你在头文件里引用WCDB，则需要将所有引用该头文件的源文件的`.m`改为`.mm`。
    * 为了最小化你的修改，建议可以在头文件使用`@WCTDatabase`的语法，然后在源文件里再import WCDB。
    * 如果你必须在头文件里引用WCDB，建议用脚本批量修改文件名后缀。
* Xcode对`.mm`的自动补全和语法高亮也是很好的。但你在刚修改完文件名后缀，可能xcode的索引还没有建完。可以等待其完成后再重启Xcode。如果依然没有高亮，可以删除`~/Library/Developer/Xcode/DerivedData`下对应project的数据后再试。

**Comment by 312362115** [comment]
`WCTTableCoding.h`  `WCTCodingMacro.h` 这两个文件呢, 不是必须在model的头文件引入的嘛, 其他需要引入改model的, 也都必须改成`.mm`呀

**Comment by RingoD** [comment]
这个看你代码结构怎么设计，Objective-C++的机制是需要改后缀的的。
