### ISSUE TITLE
Change Column::Any to Column::All

### ISSUE THREAD

**Issue by zhongwuzw** [Tencent/wcdb#230]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.5

### The platform of WCDB

> iOS, macOS

### The installation of WCDB

> Git clone

### What's the issue?

> We use `Column::Any` to represent `*`. I think `Any` would misleading, `Any` and `All` have different way of looking at a collection of objects. `Any` referring to a single object and not several or more.

`const Column Column::Any("*");`

**Comment by RingoD** [comment]
True. 

But `All` is conflict with `AllProperties`, which is the array of all defined `WCTProperty`. 

e.g.
`WCTMaster.AnyProperty` means the star `*` while `WCTMaster.AllProperties` means `{WCTMaster.type, WCTMaster.name, WCTMaster.tableName, WCTMaster.rootPage, WCTMaster.sql}`.

Do you have any good idea?

**Comment by zhongwuzw** [comment]
I prefer `AllColumns`, it's not conflict with `AllProperties`, and express the semantic more correctly.

Excerpt from `SQLite` document.
> If a result expression is the special expression "*" then all columns in the input data are substituted for that one expression.

**Comment by RingoD** [comment]
Actually, the `*` belongs to `ColumnResult`, not `Column`. It will be fixed in later version.

**Comment by RingoD** [comment]
It is renamed to `AllResults`. #eaa05e0c8dcc8abb0f809c3a57bd00ff22f5b64f
