### ISSUE TITLE
pod集成，报错C++ requires a type specifier for all declarations

### ISSUE THREAD

**Issue by xiaogao233** [Tencent/wcdb#231]
statement_delete
statement_select
statement_update
三个文件不能正常编译

报错在
StatementUpdate &offset(const Expr &offset); 
这行
C++ requires a type specifier for all declarations
Expected parameter declarator
Expected ')'

**Comment by RingoD** [comment]
You can check FAQ in wiki

**Comment by xiaogao233** [comment]
pod是按步骤走的，新建项目使用都没问题，但是主项目一编译就出问题了

**Comment by RingoD** [comment]
Your issue is already described in wiki.

**Comment by xiaogao233** [comment]
非常感谢，问题已解决。
跟第三方库Masonry宏定义冲突，Masonry有一个去除mas_前缀的宏，其中mas_offset(...)如果使用去除前缀就会导致冲突，而我之前尝试同样的类库并没有报错就在于没有使用去除Masonry前缀的宏。

**Comment by RingoD** [comment]
no reply.
