### ISSUE TITLE
WCDBSwift crashed on canopen after calling setCipher

### ISSUE THREAD

**Issue by ShmilyLin** [Tencent/wcdb#235]
### The language of WCDB

Swift

### The version of WCDB

1.0.6

### The platform of WCDB

iOS

### The installation of WCDB

> Cocoapods

### What's the issue?
sql setCipher

```swift
self.database = WCDBSwift.Database(withPath: self.databaseFilePath)
let passwordData = "\(Int(Date().timeIntervalSince1970))".data(using: String.Encoding.utf8)
self.database!.setCipher(key: passwordData!)
self.database!.tag = 1
if self.database!.canOpen { // crash

}
```

crash information：
![image](https://user-images.githubusercontent.com/14346033/35329704-c752e0fc-013b-11e8-80d0-5f09444a5c86.png)

![image](https://user-images.githubusercontent.com/14346033/35329723-d6a65070-013b-11e8-8ff4-168b07983960.png)

I can find the .db file has been created in the corresponding path.

**Comment by RingoD** [comment]
As the issue template said, please describe your issue in English, which is also the consensus of the open source community.

**Comment by RingoD** [comment]
As for your question, this fatal error is triggered while `WCDB_HAS_CODEC` compiler flag is not defined.
But the code is already coloring, which means that `WCDB_HAS_CODEC` is defined.

Have you ever modified the source code of WCDB or your project setting ?

**Comment by ShmilyLin** [comment]
I never modified the source code after pod the sdk. 

I only add a build configuration named "Mockup".

**Comment by RingoD** [comment]
That's exactly where the issue is. You should create a scheme by duplicating, which will inherit the existing scheme.

**Comment by RingoD** [comment]
By the way, could you please translate the title and the issue description into English?

**Comment by ShmilyLin** [comment]
I have already set up this build configuration long before pod `WCDBSwift`.

could give a solution？

**Comment by RingoD** [comment]
You can either re-add the `Mockup` scheme or add the Swift flags manually.

**Comment by ShmilyLin** [comment]
It is recommended to add features that can be added automatically following cocoapods

**Comment by RingoD** [comment]
This issue has nothing to do with WCDB. The build setting is added by Cocoapods.

**Comment by ShmilyLin** [comment]
I will
