### ISSUE TITLE
A compilation error occurred while integrating the WCDB dynamic library

### ISSUE THREAD

**Issue by vincentgemini** [Tencent/wcdb#236]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Framework

### What's the issue?

![screen shot 2018-01-26 at 00 14 53](https://user-images.githubusercontent.com/12698004/35398907-ff0b7d68-022d-11e8-98c1-4c44063e0bb9.png)

When add the file of wcdb.h to the project and appear with the compiler error above.

The project introduced some other libraries and PCH are as follows:

![screen shot 2018-01-26 at 00 19 40](https://user-images.githubusercontent.com/12698004/35399181-a776e38e-022e-11e8-9b9c-44db7e6afb2f.png)

![screen shot 2018-01-26 at 00 20 33](https://user-images.githubusercontent.com/12698004/35399237-c2db4ea8-022e-11e8-9168-9e8088e6aa4a.png)

**Comment by RingoD** [comment]
As the issue template said, please describe your issue in English, which is also the consensus of the open source community.

**Comment by RingoD** [comment]
Since WCDB is a OC++ framework, it may not be included in the pch file.
Try to move it to the file used WCDB.

**Comment by vincentgemini** [comment]
i don't include WCDB in the pct file. is it mean that i need to remove the pch file?

**Comment by RingoD** [comment]
You can only include it where it is used.

**Comment by vincentgemini** [comment]
I am not clearly what you said. I want to know that whether it can use PCH file (not included any WCDB header ). I think that it should be used PCH file in the project and when need WCDB include the file.mm.

**Comment by RingoD** [comment]
YES. Using pch for other ObjC framework and not using it for ObjC++ framework.
By the way, maybe you can learn more about pch and compiling progress to get a deep look.
