### ISSUE TITLE
 Use cocoapods to create data persistence module and reference WCDB.swfit (by cocoapods), and in other projects to introduce data persistence module will report 'sqlcipher / fts3_tokenizer.h' file not found

### ISSUE THREAD

**Issue by bluajack** [Tencent/wcdb#237]
### The language of WCDB

Swift

### The version of WCDB

v1.0.6

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

I use cocoapods to create data persistence module and reference WCDB.swfit (by cocoapods), and in other projects to introduce data persistence module will report ```'sqlcipher / fts3_tokenizer.h' file not found```，When compiling a project, the following error is reported:

### Error
```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/WCDB.swift-umbrella.h"
        ^
/Users/tinghuiyuan/Desktop/TSTradingSystemiOS/TSOptionalModule/Pods/Target Support Files/WCDB.swift/WCDB.swift-umbrella.h:13:9: note: in file included from /Users/tinghuiyuan/Desktop/TSTradingSystemiOS/TSOptionalModule/Pods/Target Support Files/WCDB.swift/WCDB.swift-umbrella.h:13:
#import "SQLite-Bridging.h"
        ^
/Users/tinghuiyuan/Desktop/TSTradingSystemiOS/TSOptionalModule/Pods/WCDB.swift/swift/source/util/SQLite-Bridging.h:28:9: error: 'sqlcipher/fts3_tokenizer.h' file not found
#import <sqlcipher/fts3_tokenizer.h>
        ^
<unknown>:0: error: could not build Objective-C module 'WCDBSwift'
```

I tried many times the following operation, still can not solve the problem

```swift
pod cache clean WCDB --all
rm -rf ~/Library/Caches/CocoaPods
pod repo update
```

### Project dependencies are as follows
<img width="770" alt="2018-01-26 6 53 15" src="https://user-images.githubusercontent.com/29746653/35436704-7803652c-02ca-11e8-8593-a2e2616310c0.png">

<img width="279" alt="2018-01-26 6 53 52" src="https://user-images.githubusercontent.com/29746653/35436716-81721b12-02ca-11e8-8bbc-53f48cf8985e.png">

<img width="280" alt="2018-01-26 6 54 09" src="https://user-images.githubusercontent.com/29746653/35436722-89002f7c-02ca-11e8-844c-edcf04d2715a.png">

**Comment by RingoD** [comment]
Are intergrating WCDB into your app by pod or into your framework by podspec?

**Comment by bluajack** [comment]
### My component is as follows

<img width="955" alt="2018-01-27 10 31 28" src="https://user-images.githubusercontent.com/29746653/35467818-91b25562-034e-11e8-96d8-e71b47829ca9.png">

<img width="743" alt="2018-01-27 10 31 57" src="https://user-images.githubusercontent.com/29746653/35467829-c5f24d28-034e-11e8-8d9e-84702353c141.png">

<img width="1087" alt="2018-01-27 10 32 19" src="https://user-images.githubusercontent.com/29746653/35467870-477537ac-034f-11e8-9be2-3d71e2640995.png">


### I think I know what is the reason
<img width="1168" alt="2018-01-27 10 33 07" src="https://user-images.githubusercontent.com/29746653/35467871-56d9cee2-034f-11e8-94f9-7b4e631a220d.png">

### When I did the following operation on the project compiled successfully
<img width="1156" alt="2018-01-27 10 33 44" src="https://user-images.githubusercontent.com/29746653/35467884-802d661e-034f-11e8-846d-45f90c4448f2.png">

### But every time after the project pod install again Preprocessor Macros will be reset, what is your solution?

**Comment by RingoD** [comment]
I know what your problem is now. 
Could you please give me a sample project which can reproduct this?

**Comment by bluajack** [comment]
https://github.com/ExamplesWCDB

**Comment by RingoD** [comment]
Which version of cocoapods is ?

**Comment by bluajack** [comment]
COCOAPODS: 1.3.1

**Comment by RingoD** [comment]
It seems that it will be fixed by upgrading to Cocoapods 1.4.0. 
Maybe you can have a try.

**Comment by bluajack** [comment]
It still does not work

**Comment by niyaoyao** [comment]
@bluajack Have you solved your problem? I have the same issue and I don't know how to solve it. @RingoD

**Comment by RingoD** [comment]
@niyaoyao  I had received many of the same issues about it and most of them solved this problem by cleaning the pod cache.
```
pod cache clean WCDB --all
rm -rf ~/Library/Caches/CocoaPods
pod repo update
```
So I think it could be the problem of Cocoapods.

**Comment by bluajack** [comment]
@niyaoyao 
```
s.xcconfig = {
      "GCC_PREPROCESSOR_DEFINITIONS" => "$(inherited) WCDB_BUILTIN_SQLCIPHER WCDB_COCOAPODS",
  }
```

24/5000
Nǐ kěyǐ zài bào cuòwù de gōngchéng de podspec wénjiàn jiārù zhège
You can add this in the podspec file that reports the wrong project,But it is only a temporary solution!

**Comment by niyaoyao** [comment]
@RingoD I have tried, however it didn't work. So I try to use carthage to install~ It works~~ 
@bluajack I would have a try later. Thank you~

**Comment by hcxyzlm** [comment]
我目前也遇到这个问题。用pod私有库数据持久化模块并引用WCDB.swfit(cocoapods方式)，会报
![image](https://user-images.githubusercontent.com/8855839/43496605-cfab60f2-9570-11e8-9431-331fd11a18dc.png)。
![image](https://user-images.githubusercontent.com/8855839/43496736-8ba7b0c6-9571-11e8-9e52-7472291a50f2.png)
我的demo地址为https://github.com/hcxyzlm/PrivatePod_WCDB

**Comment by Jonzzs** [comment]
@bluajack it works for me, thank you!
