### ISSUE TITLE
OC 1.0.6 sqlcipher/fts3_tokenizer.h' file not found

### ISSUE THREAD

**Issue by JunyiXie** [Tencent/wcdb#238]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
Please fill the issue template with basic information.

**Comment by JunyiXie** [comment]
update cocoapod to 1.4.0 fix problem.
