### ISSUE TITLE
Android创建数据库表失败

### ISSUE THREAD

**Issue by weilixin** [Tencent/wcdb#24]
你好，我的应用启动会创建common_new的数据库，数据库中有2个表user、logo。目前切换到WCDB后创建表失败，请问是为什么？日志如下，多谢！

06-13 17:35:02.153 16576-16712/com.wlx.debug I/WCDB: Initialize JNI module (1/11) CursorWindow...
06-13 17:35:02.153 16576-16712/com.wlx.debug V/WCDB.JNIHelp: Registering com/tencent/wcdb/CursorWindow natives
06-13 17:35:02.154 16576-16712/ccom.wlx.debug I/WCDB: Initialize JNI module (2/11) FileUtils...
06-13 17:35:02.154 16576-16712/com.wlx.debug V/WCDB.JNIHelp: Registering com/tencent/wcdb/FileUtils natives
06-13 17:35:02.154 16576-16712/com.wlx.debug I/WCDB: Initialize JNI module (3/11) ChunkedCursorWindow...
06-13 17:35:02.154 16576-16712/com.wlx.debug V/WCDB.JNIHelp: Registering com/tencent/wcdb/database/ChunkedCursorWindow natives
06-13 17:35:02.154 16576-16712/com.wlx.debug V/WCDB.JNIHelp: Registering com/tencent/wcdb/database/SQLiteAsyncQuery natives
06-13 17:35:02.154 16576-16712/com.wlx.debug I/WCDB: Initialize JNI module (4/11) SQLiteConnection...
06-13 17:35:02.154 16576-16712/com.wlx.debug V/WCDB.JNIHelp: Registering com/tencent/wcdb/database/SQLiteConnection natives
06-13 17:35:02.154 16576-16712/com.wlx.debug I/WCDB: Initialize JNI module (5/11) SQLiteDebug...
06-13 17:35:02.154 16576-16712/com.wlx.debug V/WCDB.JNIHelp: Registering com/tencent/wcdb/database/SQLiteDebug natives
06-13 17:35:02.155 16576-16712/com.wlx.debug I/WCDB: Initialize JNI module (6/11) SQLiteDirectCursor...
06-13 17:35:02.155 16576-16712/com.wlx.debug V/WCDB.JNIHelp: Registering com/tencent/wcdb/database/SQLiteDirectQuery natives
06-13 17:35:02.155 16576-16712/com.wlx.debug I/WCDB: Initialize JNI module (7/11) SQLiteGlobal...
06-13 17:35:02.155 16576-16712/com.wlx.debug V/WCDB.JNIHelp: Registering com/tencent/wcdb/database/SQLiteGlobal natives
06-13 17:35:02.155 16576-16712/com.wlx.debug I/WCDB: Initialize JNI module (8/11) DBBackup...
06-13 17:35:02.155 16576-16712/com.wlx.debug V/WCDB.JNIHelp: Registering com/tencent/wcdb/repair/BackupKit natives
06-13 17:35:02.155 16576-16712/com.wlx.debug V/WCDB.JNIHelp: Registering com/tencent/wcdb/repair/RecoverKit natives
06-13 17:35:02.155 16576-16712/com.wlx.debug I/WCDB: Initialize JNI module (9/11) DBDumpUtil...
06-13 17:35:02.157 16576-16712/com.wlx.debug V/WCDB.JNIHelp: Registering com/tencent/wcdb/repair/DBDumpUtil natives
06-13 17:35:02.157 16576-16712/com.wlx.debug I/WCDB: Initialize JNI module (10/11) DBRepair...
06-13 17:35:02.157 16576-16712/com.wlx.debug V/WCDB.JNIHelp: Registering com/tencent/wcdb/repair/RepairKit natives
06-13 17:35:02.157 16576-16712/com.wlx.debug I/WCDB: Initialize JNI module (11/11) Log...
06-13 17:35:02.157 16576-16712/com.wlx.debug V/WCDB.JNIHelp: Registering com/tencent/wcdb/support/Log natives
06-13 17:35:02.163 16576-16712/com.wlx.debug I/WCDB.SQLiteConnectionPool: Max connection pool size is 1.
06-13 17:35:02.164 16576-16712/com.wlx.debug I/WCDB: Initialize SQLite connection module 'MMFTS'...
06-13 17:35:02.180 16576-16712/com.wlx.debug I/WCDB.SQLiteConnection: Opened connection 0xaed22608 with label '/data/data/com.wlx.debug/databases/common_new'
06-13 17:35:02.185 16576-16712/com.wlx.debug W/WCDB.SQLite: [SQLite ErrCode: 1] no such table: logo
06-13 17:35:02.188 16576-16712/com.wlx.debug I/WCDB.SQLiteConnection: prepare took 2ms - failed, sql="SELECT _id, from_time, to_time, add_time, image_url, image_md5, file_size FROM logo WHERE  from_time<? and to_time>?", exception="no such table: logo (code 1, errno 0): , while compiling: SELECT _id, from_time, to_time, add_time, image_url, image_md5, file_size FROM logo WHERE  from_time<? and to_time>?"
06-13 17:35:02.540 16576-16576/com.wlx.debug W/WCDB.SQLite: [SQLite ErrCode: 1] no such table: users
06-13 17:35:02.541 16576-16576/com.wlx.debug I/WCDB.SQLiteConnection: prepare took 1ms - failed, sql="select * from users where (is_login <> 2 and is_login <> 100)  order by last_login_time desc", exception="no such table: users (code 1, errno 0): , while compiling: select * from users where (is_login <> 2 and is_login <> 100)  order by last_login_time desc"
06-13 17:35:03.562 16576-16783/com.wlx.debug W/WCDB.SQLite: [SQLite ErrCode: 1] no such table: users
06-13 17:35:03.563 16576-16783/com.wlx.debug I/WCDB.SQLiteConnection: prepare took 1ms - failed, sql="select * from users where (is_login <> 2 and is_login <> 100)  order by last_login_time desc", exception="no such table: users (code 1, errno 0): , while compiling: select * from users where (is_login <> 2 and is_login <> 100)  order by last_login_time desc"

**Comment by John-He-928** [comment]
从日志看，你没有执行过创建表的操作，而直接执行了

```sql
SELECT _id, from_time, to_time, add_time, image_url, image_md5, file_size FROM logo WHERE from_time<? and to_time>?
```

如果是创建表操作失败，日志里会打印失败的语句。

请单步调试一下，看看创建表的语句是否真的执行了，或者将相关代码贴出来看一下？

**Comment by weilixin** [comment]
已解决，多谢。。。原因是没有创建表
