### ISSUE TITLE
/Users/apple/Downloads/wcdb-master/objc/WCDB/abstract/fts_module.hpp:25:10: fatal error: 'sqlcipher/fts3_tokenizer.h' file not found

### ISSUE THREAD

**Issue by Hanchunlin** [Tencent/wcdb#240]
/Users/apple/Downloads/wcdb-master/objc/WCDB/abstract/fts_module.hpp:25:10: fatal error: 'sqlcipher/fts3_tokenizer.h' file not found .

**Comment by RingoD** [comment]
Please provide basic information as the issue template said.

**Comment by stoneForRock** [comment]
I also encountered this problem
I create an new project , pod init ,pod 'WCDB'    then run the project ,it will appear this problem.
Need I  to configure the project other information？

**Comment by RingoD** [comment]
@stoneForRock 
You can clean Cocoapods cache and re-pod it.

**Comment by stoneForRock** [comment]
@RingoD 
Thanks,let me try

**Comment by stoneForRock** [comment]
I pod repo update and re-create a new project, It is done.

**Comment by niyaoyao** [comment]
@RingoD It didn't work for me 😭

**Comment by niyaoyao** [comment]
@RingoD @stoneForRock I solved this problem with carthage to install WCDB finally ...

**Comment by stoneForRock** [comment]
...

**Comment by lsqswl** [comment]
It works for me😄
