### ISSUE TITLE
如何使用WCDB保存复杂的多层模型？  

### ISSUE THREAD

**Issue by Hanchunlin** [Tencent/wcdb#241]
用YYModle解析json字符串获取到的数据模型中属性里存在数组，数组中是存储的其他数据模型对象。这个时候再存储YYModle的对象到数据库，要崩溃啊？？？请问这个时候有什么好的存储方法或者示列？？？？

**Comment by RingoD** [comment]
As the issue template said, please describe your issue in English, which is also the consensus of the open source community, and provide the basic information.

**Comment by wxlpp** [comment]
so [QMUI](https://github.com/QMUI/QMUI_iOS/issues) is stupid?

**Comment by RingoD** [comment]
@wxlpp I don't understand what you mean.

**Comment by wxlpp** [comment]
It's just a joke,you don't have to care.i think what he want is just like realm

**Comment by RingoD** [comment]
no reply.

**Comment by SarahCarrie** [comment]
> As the issue template said, please describe your issue in English, which is also the consensus of the open source community, and provide the basic information.

你不是中国人呀！！！不懂，就学！
