### ISSUE TITLE
How to query whether an array type field contains a value?

### ISSUE THREAD

**Issue by Jinkeycode** [Tencent/wcdb#242]
### The language of WCDB

> Swift 

### The version of WCDB

> v1.0.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

I have an field：`var names: Array<String> = []`, when I want to get rows where names contains "J", how can I write the query condition?

**Comment by RingoD** [comment]
Use `where: className.Properties.myProperty.like("J*")`.
Check the sqlite syntax doc for further info.
By the way, please translate this issue title into English.

**Comment by Jinkeycode** [comment]
@RingoD I had tried to code this：
```
(
    MyObject.Properties.sourcePlatformId.in(table: table1)
        == FavoriteSource.Properties.id.in(table: table2)
)
&& (
    MyObject.Properties.tags.in(table: table1).like("\(currentCondition)*")
)
```
while `var tags: Array<String> = []`, it didn't match any result.

**Comment by RingoD** [comment]
You can register a tracer to check whether your SQL is correct.
If so, you can run it in command line to check the result.

**Comment by hydyy** [comment]
how to search Array<Int> ?
