### ISSUE TITLE
Binary operator '==' cannot be applied to operands of type '***.CodingKeys' and ***

### ISSUE THREAD

**Issue by tanpengsccd** [Tencent/wcdb#244]
>  Swift 4

>  v1.0.6

>  iOS

>  Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
``` 
Binary operator '==' cannot be applied to operands of type 'TP_Model_Employees.Res.Data.Record.CodingKeys' and 'Int?'
```
> Explain what you want by example or code **in English**.

![image](https://user-images.githubusercontent.com/13959880/35896898-853c84e8-0bf9-11e8-81b7-ed6d19740763.png)

I want select records whether TP_Model_Employees.Res.Data.Record.Properties.deptid is nil or not 

departmentId is optional,so error will appear.
if  ```where: TP_Model_Employees.Res.Data.Record.Properties.deptid == departmentId! ``` ,it is ok.
if  ``` where: TP_Model_Employees.Res.Data.Record.Properties.deptid == nil ``` ,it is ok.

**Comment by tanpengsccd** [comment]
还是中文吧 😳

**Comment by RingoD** [comment]
It makes no sense to compare a database column to a `Int?`.
To do so, you should write `where: column == departmentId! || column.isNull()`

**Comment by tanpengsccd** [comment]
if force to unwarp departmentId ,will it crash if  departmentId is nil?

**Comment by RingoD** [comment]
Of course.
It's the basic feature of Swift.

**Comment by tanpengsccd** [comment]
thanks! done
my code 
```
            let records:[TP_Model_Employees.Res.Data.Record] = try db().getObjects(on: TP_Model_Employees.Res.Data.Record.Properties.all, fromTable: TableType.contacts.rawValue ,
                                                                                   where: (departmentId == nil ? TP_Model_Employees.Res.Data.Record.Properties.deptid.isNull() : TP_Model_Employees.Res.Data.Record.Properties.deptid == departmentId!) )
            
            return records
```
ok !
