### ISSUE TITLE
Can't use WCDB in Unit Tests For iOS(Swift, CocoaPods), Compile Error!

### ISSUE THREAD

**Issue by BBHNation** [Tencent/wcdb#246]
### The language of WCDB

> Swift

### The version of WCDB

> v1.0.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> It's OK for me To run my project with WCDB, but when I want to write a Unit Test, The Problem Shows.
> <img width="447" alt="2018-02-07 4 18 45" src="https://user-images.githubusercontent.com/9971257/35905715-1cbf8fda-0c23-11e8-9f6e-19158646d60b.png">
> I write 
```
import XCTest
import WCDBSwift
@testable import MyProjectsName
```
> in my test file, and click test button to run test, but Xcode show error of this:
<img width="329" alt="2018-02-07 4 20 24" src="https://user-images.githubusercontent.com/9971257/35905784-62b26666-0c23-11e8-8da4-56a683ca7c4a.png">

> please help, thanks.
> the Podfile just like this:

```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'Project' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'WCDB.swift', '1.0.6'

  target 'ProjectTests' do
      inherit! :search_paths
  end
end
```

**Comment by RingoD** [comment]
There's nothing different between project or testcase while using Cocoapods.
Did you create a new target or project manually, which means that it's not created by Cocoapods?

**Comment by BBHNation** [comment]
@RingoD The tests target is created by default when I created the iOS project, I have selected the 'unitTests'.

**Comment by RingoD** [comment]
You can compare the build setting of project target and test target. It must be different.

**Comment by BBHNation** [comment]
thanks, I'll try later..

**Comment by wongzigii** [comment]
@BBHNation You should config your Podfile likes this:

````ruby
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!
target 'Test' do

    target 'TestTests' do
        inherit! :search_paths
        pod 'WCDB.swift', '1.0.6'
    end
end
````

This will do the trick.

**Comment by BBHNation** [comment]
@wongzigii It works for me, Thank you so much.
