### ISSUE TITLE
Value of type 'DataBase' has no member 'delete'

### ISSUE THREAD

**Issue by JasonSparrow** [Tencent/wcdb#247]
### The language of WCDB

>  Swift4

### The version of WCDB

>  v1.0.6

### The platform of WCDB

> iOS

### The installation of WCDB

>  Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
>  // 删除 sampleTable 中所有 identifier 大于 1 的行的数据
try database.delete(fromTable: "sampleTable", 
                    where: Sample.Properties.identifier > 1)
找不到删除的方法

![2018-02-07 6 12 27](https://user-images.githubusercontent.com/15692322/35910747-9a593a72-0c32-11e8-8fc6-a9980de8a0f2.png)

**Comment by RingoD** [comment]
You can check the sample code in testcase.
By the way, you are calling a `try` function without any `catch`.

**Comment by JasonSparrow** [comment]
Thank you for your answer
