### ISSUE TITLE
iOS WCDB WAL processing strategy

### ISSUE THREAD

**Issue by JunyiXie** [Tencent/wcdb#248]
### The language of WCDB

Objective-C

### The version of WCDB

1.0.6

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

what is the wcdb wal file processing mechanism?
In the case of continuous write ，wal file has reached 2gb +.

**Comment by JunyiXie** [comment]
in ios simulator iPhone 8.

**Comment by RingoD** [comment]
It will be checkpointed into main db when it is idle.

**Comment by JunyiXie** [comment]
In app life time , continue write...

[？？？](https://cloud.tencent.com/developer/article/1031030
)然而这个策略很快就发现问题了：如果一直有读写请求，频繁尝试 Checkpoint 会一直失败，以至 -wal 文件不断增大最终严重影响性能。现实中 APP 可能没有 Demo 中的情况极端，但也不能排除这种情况存在。为了解决这个问题，我们多引入了一个阻塞阈值，如果 Checkpoint 一直没有完成导致 -wal 堆积的 page 数达到阻塞阈值，则会阻塞其他读写操作让 Checkpoint 优先完成。

引入了阻塞阈值之后，经过线下测试，阻塞阈值设置在 100 ~ 300 左右在高压极端情况下性能损失较少，也不至于一直阻塞做 Checkpoint，最后我们选择普通阈值 0，阻塞阈值 100 的配置，记作 ACP(0/100)【ACP = Asynchronous Checkpoint】。

**Comment by RingoD** [comment]
It's the way WCDB-Android used, which will be used in iOS in later version.
As for v1.0.6, it will only do a checkpoint when db is idle.

**Comment by RingoD** [comment]
By the way, please translate the title of this issue into English.

**Comment by JunyiXie** [comment]
please fix.
If you do not fix this bug in three days, I will be unemployed
wuuu....

**Comment by RingoD** [comment]
While database closed, it will be checkpointed too.
So, only a database write continuously, have not rest and abnormally shut down(e.g. crash), it will result in this badcase.
Maybe you should find out why your database shut down.

**Comment by JunyiXie** [comment]
I think WCDB should control the WAL checkpoint  strategy, rather than users.

**Comment by RingoD** [comment]
It does. But when your app crash or keep busy, there is not rest for WCDB to control the WAL.

**Comment by RingoD** [comment]
We design the subthread checkpoint feature. Maybe you can check again in `v1.1.0`, which will be the next version.

**Comment by tigerzhang08** [comment]
我们应用在一段时间内会持续写入数据库，而且非常频繁，导致 wal 无限增长到 6，7 G，一直没有触发 checkpoint
