### ISSUE TITLE
How can I implement sql join ( cascade Model  for example model which has model as property ) ?

### ISSUE THREAD

**Issue by tangyumeng** [Tencent/wcdb#250]
### The language of WCDB

>  Objective-C

### The version of WCDB

> 1.0.6

### The platform of WCDB

>  iOS

### The installation of WCDB

>  Cocoapods

### What's the issue?

>  I want to implement the sql join.
> 
<pre><code>
@interface Person : NSObject
@property (nonatomic,strong) NSString *userID;
@property (nonatomic,strong) NSString *userName;
@property (nonatomic,strong) NSString *stageName;
@property (nonatomic,strong) NSString *phone;
@property (nonatomic,strong) Company *company;
@property (nonatomic,strong) NSArray /* array of Address model*/ *addresses;
@end

@interface Address : NSObject
@property (nonatomic,strong) NSString *addressID;
@property (nonatomic,strong) NSString *addressName;
@property (nonatomic,assign) NSInteger addressCode;
@end

@interface Company : NSObject
@property (nonatomic,strong) NSString *companyName;
@property (nonatomic,strong) Address *companyAddress;
@end

-(void)createPersonTable
{
    NSString *path = [self dbPath];
    WCTDatabase *database = [[WCTDatabase alloc] initWithPath:path];
    [database close:^{
    
    }];
    
    
    NSString *tableName = [self personTableName];
    BOOL ret = [database createTableAndIndexesOfName:tableName withClass:[Person class]];
    NSArray *schemas = [database getAllObjectsOnResults:{WCTMaster.name, WCTMaster.sql} fromTable:WCTMaster.TableName];
    for (WCTMaster *table : schemas) {
        NSLog(@"SQL Of %@: %@", table.name, table.sql);
    }
}

-(void)insertPersonToDB
{
    WCTDatabase *database = [[WCTDatabase alloc] initWithPath:[self dbPath]];
    [database close:^{
    }];
    BOOL result = [database insertObject:self.person
                      into:[self personTableName]];
    
    NSLog(@"insert person result :%@",@(result));
}

#pragma mark - Address
-(void)createAddress
{
    
    NSString *path =  [self dbPath];
    WCTDatabase *database = [[WCTDatabase alloc] initWithPath:path];
    [database close:^{
    }];
    
    NSString *tableName = [self addressTableName];
    BOOL ret = [database createTableAndIndexesOfName:tableName withClass:[Address class]];
    assert(ret);
    
    //Add column
    {
        ret = [database addColumn:Person.userID.def(WCTColumnTypeString)
                         forTable:[self addressTableName]];
        
        NSLog(@"xxxx  ret is:%@",@(ret));
    }
    
    NSArray *schemas = [database getAllObjectsOnResults:{WCTMaster.name, WCTMaster.sql} fromTable:WCTMaster.TableName];
    for (WCTMaster *table : schemas) {
        NSLog(@"SQL Of %@: %@", table.name, table.sql);
    }
}

-(void)insertAddressIntoDB
{
    WCTDatabase *database = [[WCTDatabase alloc] initWithPath:[self dbPath]];
    [database close:^{
    }];
    for (Address *address in self.person.addresses) {
        BOOL result = [database insertObject:address
                                        into:[self addressTableName]];
        NSLog(@"insert address into DB result :%@",@(result));
    }
}

</code></pre>

in the  `-(void)insertAddressIntoDB ` , I want to insert Address to the DB , and  retrieve the data and assign to person model . So I must put the Person model 's userID to Address Model , so the question is when insert address model to db ,how can I put the userID to address table ?

**Comment by RingoD** [comment]
You can check `Core Interface` doc in wiki to learn how to call SQLite interface using WINQ.

**Comment by tangyumeng** [comment]
https://github.com/Tencent/wcdb/wiki/WINQ%E5%8E%9F%E7%90%86 only tells how to retrieve  data . But I am still confused about how to insert Address for the model only has three property but the db table has four column(include userID) ? should I define the Address Model like this: `@interface Address : NSObject
@property (nonatomic,strong) NSString *addressID;
@property (nonatomic,strong) NSString *addressName;
@property (nonatomic,assign) NSInteger addressCode;

/*
 * used as foreign key ?
 */ 
@property (nonatomic,strong) NSString *userID;
@end`

**Comment by ruoyi** [comment]
The language of WCDB
Swift

The version of WCDB
1.0.6

The platform of WCDB
iOS

The installation of WCDB
Cocoapods

 Is also a confused for me, 
I would like to find a solution to the problem through the official demo,
But the official demo can not run.
And if you are comfortable? Wish you write an example.
Is useful for me very  much.👻
Thanks😘, Thanks😘, Thanks😘, 

![wechatimg268](https://user-images.githubusercontent.com/6287152/36090463-6a3195c8-101b-11e8-8e6c-e99a350cd1bf.jpeg)

**Comment by RingoD** [comment]
@ruoyi Do not post a different problem in one issue. You should submit your own one.
