### ISSUE TITLE
swift 为什么会自动联想到WCDB语句

### ISSUE THREAD

**Issue by RQ0588** [Tencent/wcdb#251]
![1518505095776](https://user-images.githubusercontent.com/20916477/36137114-a42c1a24-10ce-11e8-8d28-ae8132c54654.jpg)

**Comment by RQ0588** [comment]
这个项目没有使用WCDB

**Comment by RingoD** [comment]
As the issue template said, please describe your issue in English, which is also the consensus of the open source community, and provide the basic information.

**Comment by RingoD** [comment]
no reply.

**Comment by RingoD** [comment]
no reply.

**Comment by yuyedaidao** [comment]
![image](https://user-images.githubusercontent.com/6354958/37389452-6e0a8150-279f-11e8-8ebe-b32f4137e632.png)
@RQ0588 这些删掉就好了，不用英文会不会被打
