### ISSUE TITLE
benchmark疑问

### ISSUE THREAD

**Issue by lsqswl** [Tencent/wcdb#252]
测试发现，baseline_write写的时候。fmdb比wcdb更快，并非文档所述的wcdb块。

iphoneX测试：
wcdb  19603.46 ops/sec
fmdb  23395.09 ops/sec

**Comment by RingoD** [comment]
As the issue template said, please describe your issue in English, which is also the consensus of the open source community, and provide the basic information.

**Comment by RingoD** [comment]
As for your question, you can check the wiki about benchmark. 
Importantly, you must keep your device in same situation(without any other non-system background processes), run muliple times, and get the avenge value for the final conclusion.

**Comment by RingoD** [comment]
no reply.

**Comment by lsqswl** [comment]
[归档.zip](https://github.com/Tencent/wcdb/files/1774177/default.zip)
