### ISSUE TITLE
insertOrReplace doesnt't update the field whose type is Array<String>

### ISSUE THREAD

**Issue by Jinkeycode** [Tencent/wcdb#253]
### The language of WCDB

> Swift

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

>  iOS

### The installation of WCDB

> Cocoapods

### What's the issue?
insertOrReplace doesnt't update the field whose type is `Array<String>`

**Comment by RingoD** [comment]
Since you provide too little information to figure out what happen, please describable the issue by sample or code.
