### ISSUE TITLE
How to vacuum a database?

### ISSUE THREAD

**Issue by highlystuff** [Tencent/wcdb#254]
### The language of WCDB

Objective-C

### The version of WCDB

v1.0.6

### The platform of WCDB

iOS

## The installation of WCDB

Cocoapods

### What's the issue?
How to vacuum a database? since I found the database file's size did not decrease after executing delete commands.

**Comment by RingoD** [comment]
Since you provide too little information to figure out what happen, please describable the issue by sample or code.

**Comment by RingoD** [comment]
Use `Core Interface` to exec a vacuum statement. You can check the tutorial in the wiki.

**Comment by highlystuff** [comment]
you mean https://github.com/Tencent/wcdb/wiki/iOS+macOS%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B ?
what key word should I search,"Core Interface"or"vacuum" turned out to nothing.

**Comment by RingoD** [comment]
https://github.com/Tencent/wcdb/wiki/%e5%9f%ba%e7%a1%80%e7%b1%bb%e3%80%81CRUD%e4%b8%8eTransaction#%e6%a0%b8%e5%bf%83%e5%b1%82%e6%8e%a5%e5%8f%a3

**Comment by highlystuff** [comment]
code like this:
[database exec:WCDB::StatementPragma().pragma(WCDB::Pragma::AutoVacuum, true)];
        WCTStatement *statement = [self.store.database prepare:WCDB::StatementPragma().pragma(WCDB::Pragma::AutoVacuum)];
        if (statement && statement.step) {
            NSLog(@"AutoVacuum %@", [statement getValueAtIndex:0]);
        }
it expected to log 1 but turned out 0,can you reproduce it?

**Comment by RingoD** [comment]
I can't reproduce this by your code.

Since WCDB is a multithread database framework, `Pragma` may be set in one handle and be got in another handle. The correct way to run it is to set it as a config. You can check `setConfig:` interface in source code and sample for further info.

**Comment by highlystuff** [comment]
[database setConfig:^BOOL(std::shared_ptr<WCDB::Handle> handle, WCDB::Error &error) {
            BOOL success = handle->exec(WCDB::StatementPragma().pragma(WCDB::Pragma::AutoVacuum, true));
            WCTStatement *statement = [self.store.database prepare:WCDB::StatementPragma().pragma(WCDB::Pragma::AutoVacuum)];
            if (statement && statement.step) {
                NSLog(@"AutoVacuum %@", [statement getValueAtIndex:0]);
            }
            return success;
        } forName:@"AutoVacuum"];
Am I using this interface correctly?the result is always 0...what is worse，it is printed too many times in my example, more than 20 times.Please check my code.Thanks!

**Comment by RingoD** [comment]
You could setup the `auto_vacuum` config in the sample of WCDB to check whether it succeeds or not, or provide a sample project which can reproduce this issue.

**Comment by CoderXXLee** [comment]
[database exec:WCDB::StatementVacuum().vacuum()];
