### ISSUE TITLE
How to build the table on foreign keys

### ISSUE THREAD

**Issue by ruoyi** [Tencent/wcdb#255]
### The language of WCDB

> e.g. Swift

### The version of WCDB

> e.g. v1.0.6

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### How to build the table on foreign keys
I would like to find a solution to the problem through the official demo,
But the official demo can not run.
And if you are comfortable? Wish you write an example.
Is useful for me very much.👻

```swift
struct Classes {
    var id: Int? = nil
    var description: String? = nil
    var students: [Student] = [Student]()
}

struct Student {
    var id: Int? = nil
    var name: String? = nil
    var age: Int? = nil
}
```

**Comment by RingoD** [comment]
I don't understand what your want. Could you please give more information and sample to explain it.

**Comment by ruoyi** [comment]
Thanks you for your reply.

```swift
    var students: [Student] = [Student]() // students Is an array type.
```
'Student' and 'Classes' is Many-to-one relationship.

I want save the 'Classes' object, save the 'Student' at the same time.
Query 'Classes' object at the same time query 'Student'.

How to build 'Students' and 'Classes' these two tables.

**Comment by RingoD** [comment]
Can you please give me the foreign key SQLs?

**Comment by kingstarwmx** [comment]
CREATE TABLE artist(
artistid INTEGER PRIMARY KEY,
artistname TEXT
);
CREATE TABLE track(
trackid     INTEGER,
trackname   TEXT,
trackartist INTEGER,
FOREIGN KEY(trackartist) REFERENCES artist(artistid)
);
How to implement this code using WCDB ORM？

**Comment by ihewro** [comment]
Do not support foreign keys? It seems that this macro has not been completed

![image](https://user-images.githubusercontent.com/20165605/144228029-f467106b-0f78-4321-bf56-44d4908260a8.png)
