### ISSUE TITLE
`Date` type properties cannot store with `ms`

### ISSUE THREAD

**Issue by jojotov** [Tencent/wcdb#257]
### The language of WCDB

> Swift

### The version of WCDB

> v1.0.6.1

### The platform of WCDB

> iOS

### The installation of WCDB

> Carthage

### What's the issue?

If I have a `Date` property in my table's model. 
```swift
var modifiedTime: Date = Date()
```

When I insert it into database, it stores with seconds but not milliseconds by default. How can I change the default storing type to milliseconds for `Date`.

**Comment by RingoD** [comment]
It's already fixed in the lastest WCDB Swift.
