### ISSUE TITLE
How to fetch N objects  with random sort by a property from a table ?

### ISSUE THREAD

**Issue by tigerandy163com** [Tencent/wcdb#258]
### The language of WCDB

>  Objective-C

### The version of WCDB

> 1.0.6

### The platform of WCDB

>  iOS

### The installation of WCDB

>  Cocoapods

### What's the issue?
How to fetch N objects  with random sort by a property from a table ?

**Comment by RingoD** [comment]
As the issue template said, please describe your issue in English, which is also the consensus of the open source community, and provide the basic information.

**Comment by RingoD** [comment]
It's a question how we use SQLite.
There is no standard answer about this.

Here is a way I used. To use SQL: `SELECT * FROM myTable ORDER BY random()`.
In WCDB, You can call it like this:
```
NSArray *objects = [[database prepareSelectObjectsOfClass:MyClass.class fromTable:myTable] orderBy:WCTExpr::Function(@"random", {})];
```

**Comment by tigerandy163com** [comment]
Maybe  you could provide a WCTOrderTerm enmu type, for example WCTOrderedRandom like other values(WCTOrderedAscending,WCTOrderedDescending..), and as a order param (WCTOrderBy WCTProperty::order(WCTOrderTerm term) const) ?

**Comment by tigerandy163com** [comment]
NSArray *objects = [[database prepareSelectObjectsOfClass:MyClass.class fromTable:myTable] orderBy:WCTExpr::Function(@"random", {})];

orderBy... cann't compiled!
<img width="862" alt="493dabb9-bf02-4c98-8ba4-798d74ff144e" src="https://user-images.githubusercontent.com/3240001/36956781-33476f5a-206b-11e8-888b-22012e6032a2.png">
