### ISSUE TITLE
How to open a DB with read-only mode ?

### ISSUE THREAD

**Issue by tigerandy163com** [Tencent/wcdb#259]
### The language of WCDB

>  Objective-C

### The version of WCDB

> 1.0.6

### The platform of WCDB

>  iOS

### The installation of WCDB

>  Cocoapods

### What's the issue?
 How to open a DB with read-only mode ? the DB file itself can be read and write.

**Comment by RingoD** [comment]
As the issue template said, please describe your issue in English, which is also the consensus of the open source community, and provide the basic information.

**Comment by RingoD** [comment]
Since WAL journal mode is used by default in WCDB, which do not support read-only, we don't provide a builtin interface to setup a database to readonly.
But, for a readonly file, which can't be written or have not permission to be written, it will be readonly automatically.

**Comment by tigerandy163com** [comment]
Thanks
