### ISSUE TITLE
Android集成WCDB后性能问题

### ISSUE THREAD

**Issue by weilixin** [Tencent/wcdb#26]
你好，我们的应用会在启动后内存维护唯一的SQLiteOpenHelper对象，SQLiteOpenHelper对象中有个全局成员是SQLiteDatabase，当多线程调用增删改查时候都使用唯一的SQLiteDatabase操作。

SQLiteOpenHelper对象内部维护SQLiteDatabase全局成员，如下：
    public SQLiteDatabase open() throws SQLException {
        if (null == db || !db.isOpen()) {
            db = getWritableDatabase();
        }
        return db;
    }

创建数据库cipher配置，如下：
    private static final SQLiteCipherSpec cipher = new SQLiteCipherSpec().setPageSize(1024).setSQLCipherVersion(1);

【问题】切换WCDB后性能并没有提高，反而还有下降，原来我们业务完成操作数据库耗时17s左右，目前WCDB耗时接近33s左右，请问是哪里没有配置对？还是其他原因呢？感谢！！！

另，个人理解原生数据库读写是单队列的，WCDB读写支持并发，所有想知道如何使用才能实现读写并发呢？

**Comment by John-He-928** [comment]
要支持并发读写，需要**在打开DB前设置WAL**，不打开WAL创建DB目前实现连接池大小只有1（不支持并发），后续解决`SQLITE_BUSY`问题后会改为4，但也只支持读读并发，不设置WAL从SQLite层面就不支持读写并发。

```java
SQLiteOpenHelper dbHelper = new SQLiteOpenHelper(...);
// 设置WAL
dbHelper.setWriteAheadLoggingEnabled(true);
// 打开DB
SQLiteDatabase db = dbHelper.getWritableDatabase();
```

性能问题，不知你原来使用的是什么，是Android原生SQLiteDatabase还是SQLCipher Android？
最好能提供一下相关代码、Log和profile数据以便分析。

**Comment by weilixin** [comment]
感谢反馈！我们原来使用的是SQLCipher Android，相关配置如下：   
 private static SQLiteDatabaseHook hook = new SQLiteDatabaseHook() {

        @Override
        public void postKey(SQLiteDatabase db) {
            LogUtil.d(TAG, "CipherDB::postKey");
            if (Build.VERSION.SDK_INT > 10) {
                db.rawExecSQL("PRAGMA journal_mode = WAL;");
                LogUtil.d(TAG, "CipherDB::journal_mode_WAL");
            }
            if (Constant.DEBUG && Build.VERSION.SDK_INT > 19) {
                db.rawExecSQL("PRAGMA mmap_size=268435456;");
                LogUtil.d(TAG, "CipherDB::mmap_size");
            }
        }

        @Override
        public void preKey(SQLiteDatabase db) {
            LogUtil.d(TAG, "CipherDB::preKey");
            db.rawExecSQL("PRAGMA cipher_default_kdf_iter = 4000;");
        }
    };

按照您的方法开启WAL后性能和原来基本一致了，请问还有提升空间吗？如何提升呢？感谢

**Comment by John-He-928** [comment]
一起用理论上是没有影响的，性能提升需要看具体场景和代码，你可以贴一部分业务代码来分析一下。如果是**同一个`SQLiteDatabase`对象在不同线程同时调用query或exec**，WCDB的连接池会处理这种情况，自动分配和管理多个数据库连接。

SQLCipher Android用的框架，一个`SQLiteDatabase`只对应一个连接，如果要并发，需要使用多个`SQLiteDatabase`对象。这种使用多个对象达到并发的用法，在WCDB中不会有明显的优化。

Android SDK 自身的接口，和WCDB一样也是单个 `SQLiteDatabase` 自动管理多个连接。

WCDB提供[trace接口](https://tencent.github.io/wcdb/references/android/reference/com/tencent/wcdb/database/SQLiteTrace.html)，可以用于监控单条SQL执行和连接池互锁的消耗，可用于排查SQL性能问题，后续应该会增加更多接口

**Comment by weilixin** [comment]
你好，通过实现trace接口后并没有发现有pool busy和corrupted回调。。。onSQLExecuted中回调执行SQL的时间大多是0和1，极少数出现2位数的。
    @Override
    public void onSQLExecuted(SQLiteDatabase db, String sql, int type, long time) {
        LogUtil.d(TAG, "onSQLExecuted:sql: " + sql);
        LogUtil.d(TAG, "onSQLExecuted:type: " + type);
        LogUtil.d(TAG, "onSQLExecuted:time: " + time);
    }

    @Override
    public void onConnectionPoolBusy(SQLiteDatabase db, String sql, List<String> requests, String message) {
        LogUtil.e(TAG, "onConnectionPoolBusy:sql: " + sql);
        LogUtil.e(TAG, "onConnectionPoolBusy:message: " + message);
    }

    @Override
    public void onDatabaseCorrupted(SQLiteDatabase db) {
        LogUtil.e(TAG, "onDatabaseCorrupted: " + db);
    }
