### ISSUE TITLE
[Proposal] Replacing force unwrap with if let 

### ISSUE THREAD

**Issue by CodeEagle** [Tencent/wcdb#263]
```swift
if term != nil {
    description.append(" \(term!.description)")
 }
```

Like codes above, it's totally fine for compiling and reading

But if we optimize it to 

```swift
if let value = term {
    description.append(" \(value.description)")
 }
```

erase the **`!`** will make it looks more  _**safety**_

**Comment by RingoD** [comment]
Yeah, I totally agree with you.
The latest code optimize I did is to use `let`. Maybe I missed some of the code. It will be done in the next version. 
Thanks.
