### ISSUE TITLE
What type of property does iOS support, nsdictionary, Nsarray support?

### ISSUE THREAD

**Issue by bluesky0109** [Tencent/wcdb#264]
What type of property does iOS support, nsdictionary, Nsarray support？

**Comment by RingoD** [comment]
As the issue template said, please describe your issue in English, which is also the consensus of the open source community, and provide the basic information.

**Comment by RingoD** [comment]
Yes.
All builtin supported `NS-type` is already listed in wiki.

**Comment by RingoD** [comment]
No reply.
