### ISSUE TITLE
[WCDB.swift]Fatal error: Index out of range

### ISSUE THREAD

**Issue by over140** [Tencent/wcdb#266]
### The language of WCDB

> Swift 

### The version of WCDB

> v1.0.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

<img width="1180" alt="qq20180312-1 2x" src="https://user-images.githubusercontent.com/1852993/37273777-c2e24644-2615-11e8-8f39-895651cb3d1d.png">

**Comment by LZYongcn** [comment]
Meeting the same issue when I insert into table

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
