### ISSUE TITLE
setConfig Pragma Error 

### ISSUE THREAD

**Issue by lsqswl** [Tencent/wcdb#268]
[wcdb setConfig:^BOOL(std::shared_ptr<WCDB::Handle> handle, WCDB::Error &error) {
    return handle->exec(WCDB::StatementPragma().pragma(WCDB::Pragma::CacheSize=-2000));
} forName:@"CacheSizeConfig"]

the error is:    No viable overloaded '='

if remove "=-2000", it will be right. What's the problem？Help!

**Comment by lsqswl** [comment]
pod 'WCDB', '1.0.4'

**Comment by RingoD** [comment]
There is a same code in the Sample. You can check it out.

**Comment by lsqswl** [comment]
[wcdb setConfig:^BOOL(std::shared_ptr<WCDB::Handle> handle, WCDB::Error &error) {
    return handle->exec(WCDB::StatementPragma().pragma(WCDB::Pragma::CacheSize, -2000));
} forName:@"CacheSizeConfig"]

This is right answer!
