### ISSUE TITLE
how to use 'getObjects' 

### ISSUE THREAD

**Issue by yuyedaidao** [Tencent/wcdb#269]
this is my code:

```
DBManager.shared.db.getObjects(on: [DownloadTask.Properties.status], fromTable: "\(DownloadTask.self)", where: DownloadTask.Properties.status != DownloadTaskStatus.finish.rawValue, orderBy: [DownloadTask.Properties.date.asOrder(by: .ascending)], limit: nil, offset: nil)
```

then compiler  tell me:

Type '[OrderBy]?' (aka 'Optional<Array<OrderConvertible>>') does not conform to protocol 'ExpressibleByArrayLiteral'

**Comment by RingoD** [comment]
It is the mistake of Swift compiler. 
Try to specify the objects type for its returned value and you will know it.

Actually, there is exactly same sample and testcase shown in the source code. Copy and paste will effective.

**Comment by yuyedaidao** [comment]
thx
