### ISSUE TITLE
Command failed due to signal: Abort trap: 6

### ISSUE THREAD

**Issue by onekyle** [Tencent/wcdb#276]
### The language of WCDB
Swift

### The version of WCDB
V1.0.6

### The platform of WCDB
iOS

### The installation of WCDB
CocoaPods

### What's the issue?

> Post the outputs or screenshots for errors.
![image](https://user-images.githubusercontent.com/16211378/37882078-80f2c5fc-30d2-11e8-9e77-3ee1964aab38.png)

> Explain what you want by example or code **in English**.
Complier Error
Command failed due to signal: Abort trap: 6

**Comment by onekyle** [comment]
When I change the toolchain to the Xcode rather than Swift 4.0 RELEASE which downloaded from the Swift Open Source, the error is disappear. 

![image](https://user-images.githubusercontent.com/16211378/37882134-12393c8a-30d3-11e8-89e8-b9c6d3affc11.png)

But the others frameworks are always fine.

**Comment by RingoD** [comment]
It seems a compiler bug of Swift. Maybe you can post an issue to Swift.

**Comment by RingoD** [comment]
No reply.
