### ISSUE TITLE
插入数据失败

### ISSUE THREAD

**Issue by bianzhifeng** [Tencent/wcdb#278]
### The language of WCDB

> e.g. Swift

### The version of WCDB

> e.g. v1.0.6

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 您好, 请问哪里有问题?.
[WCDB][ERROR] Code:sqlite(1), Type:SQLite, Path:/var/mobile/Containers/Data/Application/3F3A78D2-253E-4147-A57F-A67F6557E23D/Documents/airtalk.db,ExtendedCode:1,Message:unrecognized token: "300012contacts",Operation:3,SQL:SELECT nickname, tels, tel, colorIndex, phone, id FROM 300012contacts

> Explain what you want by example or code **in English**.

**Comment by bianzhifeng** [comment]
![image](https://user-images.githubusercontent.com/12978315/38006625-70e85454-3278-11e8-90e0-b111d8894536.png)

**Comment by lingol** [comment]
表名 “300012contacts”是数字开头，不合法吧？
