### ISSUE TITLE
Failed to register native method com.tencent.wcdb.CursorWindow.nativeSetNumColumns(JI)Z in /data/app/...

### ISSUE THREAD

**Issue by afayp** [Tencent/wcdb#28]
how can I solve this problem?

**Comment by John-He-928** [comment]
It looks like WCDB's Java methods were obfuscated by ProGuard.
Try adding the following lines to your `proguard-rules.pro` or other ProGuard settings file:

```proguard
-keep class com.tencent.wcdb.** {
    *;
}
```

**Comment by afayp** [comment]
Thanks for your reply so fast. it works for me! 👍
