### ISSUE TITLE
crash at [WCTCore initWithCore:]

### ISSUE THREAD

**Issue by tigerandy163com** [Tencent/wcdb#280]
### The language of WCDB

> Objective-C 

### The version of WCDB

> v1.0.6

### The platform of WCDB

> iOS 

### The installation of WCDB

> Cocoapods

### What's the issue?
Below is a screenshot of the crash stack  in bugly 

<img width="1021" alt="3a5f2bab-2c2c-4c24-8ec8-70586f72bd83" src="https://user-images.githubusercontent.com/3240001/38013880-598e5dfa-3299-11e8-8eb7-e3b9a833f47a.png">

**Comment by RingoD** [comment]
Please provide the entire crash stack, including the all threaded crash stack and analysis.
