### ISSUE TITLE
sample code links 404 not found

### ISSUE THREAD

**Issue by bluesky0109** [Tencent/wcdb#281]
### The language of WCDB

Objective-C

### The version of WCDB

v1.0.6

### The platform of WCDB

 iOS, macOS 

### The installation of WCDB

 Cocoapods

### What's the issue?

sample code links 404 not found，please update tks

**Comment by RingoD** [comment]
Which link? Please provide the tutorial page. Thanks.

**Comment by bluesky0109** [comment]
https://github.com/Tencent/wcdb/wiki/%E5%9F%BA%E7%A1%80%E7%B1%BB%E3%80%81CRUD%E4%B8%8ETransaction

https://github.com/Tencent/wcdb/blob/master/apple/sample/table/sample_table_main.mm ；
all sample links 404

**Comment by RingoD** [comment]
Thanks. It's already fixed.
We are in the mid of refactor now. So some of the samples or wikis may be not good enough.
Sorry for this.
