### ISSUE TITLE
How to observe the data in the database in real time when debugging? 

### ISSUE THREAD

**Issue by czh0318** [Tencent/wcdb#282]
### The language of WCDB
> Objective-C

### The version of WCDB
>  v1.0.6

### The platform of WCDB
>  iOS 9.0+

### The installation of WCDB
> Cocoapods

### What's the issue?

Hi @RingoD ：
    I switched from fmdb to wcdb. I specified my original database via ```[[WCTDatabase alloc] initWithPath:path]```. When I  inserted object into table, it was successful, but I didn't see the data being inserted into my original database. Only two files, [mydbname].db-shm and [mydbname].db-wal was generated. I can't open them, it requires a password, what is the default password? But, actually, when I read from database, data is inserted, how to observe the data in the database in real time when debugging? 

Thank you very much.

**Comment by RingoD** [comment]
WCDB will not encrypt  your database by default. The password is same as your origin. If it's not encrypted before, you do not need to set up its password.

Were you moving the database file to another directory? If so, you should copy the db file and its `-shm` and `-wal`. If it is moved by code, you should use the interface of WCDB to make sure the integrity.

**Comment by czh0318** [comment]
@RingoD 
Glad to  receive your reply!
The db file and its -shm and -wal are always in the same directory, I store my db file in the iOS Document directory. Actually data is correct when read and written, but I am just confused that I can't see the data in real time  to verify that my code is correct.
Thanks again.

**Comment by RingoD** [comment]
What do you mean "real time"?

**Comment by czh0318** [comment]
I mean when I insert one object, I export db file, I can see that object in table.

**Comment by czh0318** [comment]
I know .db-shm and .db-wal are cache files, have any apis to rollback cache to db manually.

**Comment by RingoD** [comment]
As I said before, when you export the db file, you should copy both db file, `-shm` and `-wal`.

**Comment by czh0318** [comment]
OK, I see ,thanks a lot.

**Comment by RingoD** [comment]
No reply.
