### ISSUE TITLE
compile error in source code after pod install complete

### ISSUE THREAD

**Issue by jyhg** [Tencent/wcdb#284]
### The language of WCDB

>  Swift

### The version of WCDB
> v1.0.6

### The platform of WCDB
>  iOS  
XCode 9.3 edition

### The installation of WCDB
 Cocoapods,

### What's the issue?
18 compile error in total
like following
> 'ColumnDecodableBase' requires that 'Key' 
> ColumnDecodableBase' requires that 'Element' conform to 'Decodable'

**Comment by RingoD** [comment]
https://github.com/Tencent/wcdb/issues/283
