### ISSUE TITLE
wcdb init TableCoding nonsupport “gender, address”keywords，will crash bind cloumn 

### ISSUE THREAD

**Issue by hcxyzlm** [Tencent/wcdb#285]
### The language of WCDB

> e.g. Objective-C

### The version of WCDB

> e.g. v1.0.6

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 数据模型有gender, address等字段，程序启动时，绑定到数据库时，会发生崩溃
> Explain what you want by example or code **in English**.

@interface LMUser : LMBaseModel

@property (nonatomic,assign)  NSInteger userId;       //用户id

@property (nonatomic,assign ) NSInteger      userState;//用户状态
@property (nonatomic,strong ) NSString       *account;//用户账户名
@property (nonatomic,strong ) NSString       *token;//授权的token
@property (nonatomic,assign)  NSInteger       gender;//1-男，2-女
@property (nonatomic,assign)  NSInteger       gender1;//1-男，2-女
@property (nonatomic,strong ) NSString       *nickname;//昵称
@property (nonatomic,strong ) NSString       *cover;//用户头像
@property (nonatomic,strong ) NSString       *backCover;//用户主页背景
@property (nonatomic,strong ) NSString       *areaIds;//地区id
@property (nonatomic,strong ) NSString       *address;//用户地区
@property (nonatomic,strong ) NSString       *desrc;//用户描述
@end 
@implementation LMUser

WCDB_IMPLEMENTATION(LMUser)

WCDB_SYNTHESIZE(LMUser,userId)
WCDB_SYNTHESIZE(LMUser,userState)
WCDB_SYNTHESIZE(LMUser,account)
WCDB_SYNTHESIZE(LMUser,token)
WCDB_SYNTHESIZE(LMUser,gender1)
WCDB_SYNTHESIZE(LMUser,nickname)
WCDB_SYNTHESIZE(LMUser,cover)
WCDB_SYNTHESIZE(LMUser,backCover)
WCDB_SYNTHESIZE(LMUser,areaIds)
WCDB_SYNTHESIZE(LMUser,address)
WCDB_SYNTHESIZE(LMUser,desrc)
@tencent-adm 
![wx20180409-181635](https://user-images.githubusercontent.com/8855839/38492639-2edcd964-3c22-11e8-833b-025f2935c5a9.png)

**Comment by RingoD** [comment]
As the issue template said, please describe your issue in English.

**Comment by RingoD** [comment]
As for your question, I found everything works fine with your definition.
 If you think it should be a bug, please provide a sample project with reproducible crash.

**Comment by RingoD** [comment]
No reply.
