### ISSUE TITLE
Unit test error

### ISSUE THREAD

**Issue by Ginxx** [Tencent/wcdb#286]
### The language of WCDB

> swift

### The version of WCDB

> v1.0.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> ![Image](https://user-images.githubusercontent.com/15857442/38538257-7898b39a-3cc5-11e8-9856-0d32ad8df669.png)

![Image](https://user-images.githubusercontent.com/15857442/38538279-9d8a1bb2-3cc5-11e8-8ca6-5b1e91f6b872.png)

> Some build error when unit test

**Comment by RingoD** [comment]
You can simply clear the cocoapods cache and re-pod.
