### ISSUE TITLE
Carthage 集成出错

### ISSUE THREAD

**Issue by selfmaking** [Tencent/wcdb#29]
describable.hpp 中报错
<img width="870" alt="2017-06-14 4 57 04" src="https://user-images.githubusercontent.com/21097577/27124118-93d63c70-5122-11e7-8e75-2f1c6275eab7.png">
引入报错
<img width="883" alt="2017-06-14 4 56 54" src="https://user-images.githubusercontent.com/21097577/27124129-9ea99804-5122-11e7-9a1b-4493bad39dcc.png">

**Comment by RingoD** [comment]
请查看 #10
