### ISSUE TITLE
Remove 

### ISSUE THREAD

**Issue by chulito1** [Tencent/wcdb#291]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

X project and swift please 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
This issue does not make sense.
