### ISSUE TITLE
Could fix  a crash bug ? 

### ISSUE THREAD

**Issue by tigerandy163com** [Tencent/wcdb#292]
### The language of WCDB

> Objective-C 

### The version of WCDB

> v1.0.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?
crash stack from Bugly, how to resolve it ? thanks!
 
![2018-04-27 11 28 17](https://user-images.githubusercontent.com/3240001/39343221-2ffb59ca-4a0e-11e8-851f-3e616afe6521.png)

**Comment by RingoD** [comment]
It seems like sqlite hit a rogue memory, which means that the pointer becomes rogue by others illegal use, but not sqlite itself.

**Comment by tigerandy163com** [comment]
Well, before i used WCDB,  i used FMDB, there was not this kind of crashes reported at that time, and now，there are still some FMDB code  in my code, but this kind of crash happened  also at place of FMDB called. Can i think that the biggest difference between WCDB and FMDB except ORM is SQLCipher?  these crashes  are caused by SQLCipher?

**Comment by RingoD** [comment]
Did you embed the SQLite source code before?

**Comment by tigerandy163com** [comment]
i used the libsqlite3 framework supported by xcode, not source code

**Comment by RingoD** [comment]
How much crash do you monitor there?

**Comment by tigerandy163com** [comment]
In the most recent version reached up to 800 times

**Comment by tigerandy163com** [comment]
here is another crash 

#221826 SIGSEGV
SEGV_ACCERR
jiakaobaodianPromise __ZNKSt3__18functionIFvRKN4WCDB5ErrorEEEclES4_ (functional:)

![518ef230-0f44-4739-b81b-62cc6736aa57](https://user-images.githubusercontent.com/3240001/39683170-a91df8f0-51e6-11e8-8773-59cce87eef4f.png)

**Comment by RingoD** [comment]
Actually, even WeChat does not crash so many times. Here are two more questions:
1. Are you using both FMDB and WCDB for a database with same path ?
2. What about the main thread stack of first crash ?

**Comment by tigerandy163com** [comment]
1. In order to avoid unnecessary mistakes I did not mix FMDB and WCDB at a same database 
2. Bugly shows the reason thread stack in the first place, is it not credible?

**Comment by tigerandy163com** [comment]
yes ,i linked it

**Comment by RingoD** [comment]
Since sqlcipher is embedded in WCDB, you can remove the sqlite3 system library.

**Comment by xmkevin** [comment]
Is this issue resolved ?

**Comment by RingoD** [comment]
@xmkevin  Please provide the full crash report.

**Comment by xmkevin** [comment]
I have mixed wcdb and fmdb together to reproduce this crash, but it doesn't happen. It seems no because of linking the system sqlite library.

**Comment by tigerandy163com** [comment]
yes，i removed system sqlite，but the same crash still happen。
