### ISSUE TITLE
Does it support swift 4.1 now?

### ISSUE THREAD

**Issue by BeckWang0912** [Tencent/wcdb#295]
### The version of Xcode

> 9.3

### The language of WCDB

> Swift4.1

### The version of WCDB

> v1.0.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

error:

'ColumnDecodableBase' requires that 'Element' conform to 'Decodable'
Type 'Element' does not conform to protocol 'Decodable'

**Comment by RingoD** [comment]
https://github.com/Tencent/wcdb/issues/283
