### ISSUE TITLE
数据库后置加密错误

### ISSUE THREAD

**Issue by Marcusias** [Tencent/wcdb#296]
### The language of WCDB

>  Objective-C

### The version of WCDB

> new

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?
最初版本未进行数据加密，迭代时进行加密，然后提示如下错误：
Code:26, Type:SQLiteGlobal, Msg:file is encrypted or is not a database
必须要将旧的未加密的库表，迁移到额外创建的新的加密库表里吗？

**Comment by RingoD** [comment]
As the issue template said, please describe your issue in English.

**Comment by RingoD** [comment]
No reply
