### ISSUE TITLE
InsertOrReplaceObject cannot modify data, "OFFSET": syntax error

### ISSUE THREAD

**Issue by mxmhao** [Tencent/wcdb#297]
### The language of WCDB

Objective-C

### The version of WCDB

v1.0.5, v1.0.6

### The platform of WCDB

iOS, macOS

### The installation of WCDB

Cocoapods

### What's the issue?

[WCTDatabase insertOrReplaceObject:onProperties:into:] can't change the data, 
so can [WCTTable insertOrReplaceObject:onProperties].

[WCTDatabase updateRowsOnProperties:withObject:where] can modify the data.

You can test it

[WCTTable getObjectsWhere:orderBy:offset:] will prompt
[WCDB][ERROR]Code:1, Type:SQLite, Tag:0, Op:3, ExtCode:1, Msg:near "OFFSET": syntax error,

**Comment by RingoD** [comment]
Note that `[WCTTable insertOrReplaceObject:onProperties]` is simply call the `[WCTDatabase insertOrReplaceObject:onProperties:into:] `. So they should be the same. Or
1. you can upgrade to v1.0.6 and retry it.
2. provide a reproducible sample here.

**Comment by mxmhao** [comment]
The v1.0.6 problem remains.

A new issue:
[WCTTable getObjectsWhere:orderBy:offset:] will prompt
[WCDB][ERROR]Code:1, Type:SQLite, Tag:0, Op:3, ExtCode:1, Msg:near "OFFSET": syntax error,

**Comment by RingoD** [comment]
OFFSET is the reserved keyword in SQLite, which can not be used.

**Comment by RingoD** [comment]
No reply.
