### ISSUE TITLE
install using source code failed

### ISSUE THREAD

**Issue by witchnana** [Tencent/wcdb#299]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Swift

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> dyld: Library not loaded: @rpath/sqlcipher.swift.framework/sqlcipher.swift
  Referenced from: /private/var/containers/Bundle/Application/BD2D73F6-D79F-49AA-84A4-B995C0D172B8/SavePoint.app/Frameworks/WCDBSwift.framework/WCDBSwift
  Reason: image not found
> Explain what you want by example or code **in English**.

I create a new project, following instructions to embed binararies. App crashed when I run in devices.
I want it to run correctly.

XCode 9.2

**Comment by RingoD** [comment]
Please use English for the issue title.

**Comment by RingoD** [comment]
As the console said, you have not embedded the `sqlcipher.framework` into your bundle.

**Comment by RingoD** [comment]
No reply.
