### ISSUE TITLE
iOS 不支持cocoapods引入吗

### ISSUE THREAD

**Issue by GodL** [Tencent/wcdb#3]

**Comment by xdkhan** [comment]
同问

**Comment by Yincongxiao** [comment]
Mark 同问~

**Comment by KIVET** [comment]
不支持就太low了

**Comment by RingoD** [comment]
近期会加上支持。这个是有原因的
因为WCDB依赖sqlcipher，并且是逐文件的链入，而不是整一个超大的sqlite3.c。这样在调试过程会更方便，但是在接入cocoapods的配置就比较复杂，遇到了一些问题。
有兴趣的同学也可以一起来配。

**Comment by zingwin** [comment]
看完文档就发现这个问题，原来已经在解决了，加油！

**Comment by XiaoChenYung** [comment]
希望支持

**Comment by icofans** [comment]
加油！

**Comment by alexlee002** [comment]
@RingoD : 我觉得对Cocoapods的支持，可以先通过提供二进制framework的方式。之后解决了sqlcipher依赖再增加源码支持。

**Comment by leewaycn** [comment]
that is my question too. thx.

**Comment by RingoD** [comment]
WCDB已经支持Cocoapods了，请参考 https://github.com/Tencent/wcdb/wiki 的安装教程。

Cocoapods is supported now. Check https://github.com/Tencent/wcdb for installation tutorial.

**Comment by RingoD** [comment]
no reply
