### ISSUE TITLE
SQLiteDirectCursor性能提升问题

### ISSUE THREAD

**Issue by ChenGuanshu** [Tencent/wcdb#30]
我们项目也有几个查询，会重复触发 windowcursor refill .
10000条数据，耗时在 14秒左右，使用 SQLiteDirectCursor 在11秒左右。

我们业务之前的做法是先查询一遍某个索引的范围，然后多线程查询再合并结果，耗时在 6秒左右，但写起来很复杂，而且不通用。

SQLiteDirectCursor 还有优化空间么。

**Comment by John-He-928** [comment]
不是很明白“先查询一遍某个索引的范围”，是通过估算将WHERE子句范围划分成不同区域，用不同线程去查询？比如
```sql
SELECT * FROM table1 WHERE id < 3000;
SELECT * FROM table1 WHERE id BETWEEN 3000 AND 6000;
SELECT * FROM table1 WHERE id > 6000;
```
拆分到三个线程去做？

从目前DirectCursor实现来说，我们暂时没想到更好的方法，优化空间肯定还有，但可能不会是颠覆性的。关键点是 `Cursor` 是个迭代器，而且没有类型信息，这和SQLite底层的`sqlite3_stmt`是吻合的，所以DirectCursor实际上是很薄的胶水层。

多线程填充的思想的确很好，如果不考虑“WHERE子句范围划分”的业务相关性，可以试试用我们的 `ChunkedCursorWindow` 来实现通用的多线程查询。ChunkedCursorWindow可以看作分块变长的CursorWindow，本身考虑了多线程读写，你可以实现自己的CursorFactory来使用多线程填充ChunkedCursorWindow。实现方法可以参考`SQLiteDirectCursor`和`SQLiteAsyncCursor`（Async Cursor未完成），我们对`CursorFactory`、`SQLiteProgram`和`SQLiteDatabase`做了扩展，支持实现自己的Cursor来对特定业务做优化。这个过程可能需要使用JNI实现，也可以将`SQLiteDirectQuery`视为底层SQLite Statement的封装来通过纯Java实现。（SQLiteDirectCursor / SQLiteDirectQuery 接口本身有设想自身成为别的Cursor实现的一部分）

`ChunkedCursorWindow` 的接口多在native层，Java只暴露了读接口，所以如果使用它就要写native代码。如果使用SQLiteDirectCursor / SQLiteDirectQuery实现，可以直接用他们填充一个List，再封装一个Cursor接口返回List的内容。

如果能发展出一套业务无关的高性能Cursor，欢迎发Pull Request给我们 :)
