### ISSUE TITLE
问个问题，wcdb读写数据是直接操作DB表文件，还是有内存缓存呢？

### ISSUE THREAD

**Issue by hxming2919** [Tencent/wcdb#301]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
读写数据是直接操作DB文件，还是有内存缓存呢？

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
As it said, please describe your issue in English.

**Comment by RingoD** [comment]
As for your question, I think it's a common behavior that all databases do.
Write to memory, and flush to disk when it's needed(commit or other cases).
