### ISSUE TITLE
Mapping another model

### ISSUE THREAD

**Issue by summertian4** [Tencent/wcdb#302]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

Can I map the select result as another model?

E.g:

```
select path,type,count(*) as r_count,avg(length) avg_length,sum(length) sum_length from HttpRecord group by path,type
```

**Comment by RingoD** [comment]
As it said, please describe your issue in English.

**Comment by RingoD** [comment]
I think `as` redirection feature is what you want.
You can use `A.property.count().as(B.property)` in object selection.
Check wiki for further information.

**Comment by summertian4** [comment]
I met a problem.

![qq20180601-120112](https://user-images.githubusercontent.com/7870394/40820540-bdc526be-6593-11e8-9a26-ea468626844e.png)

But these two ways are OK

![qq20180601-120328](https://user-images.githubusercontent.com/7870394/40820571-dc492eaa-6593-11e8-8f33-7661053702b5.png)

![qq20180601-120419](https://user-images.githubusercontent.com/7870394/40820579-ee33c5bc-6593-11e8-9bbe-bfd227d143cf.png)

**Comment by RingoD** [comment]
The return type of `as` expression is `WCTProperty`. So the combination of two `as` expression should be `WCTPropertyList` and compiler fails to find the best way to convert them into `WCTResultList`.

It will be fixed in the next release. For now, you can write them separately using `WCTResultList`.
