### ISSUE TITLE
.mm file use enum get a error

### ISSUE THREAD

**Issue by Rico358097990** [Tencent/wcdb#304]
### The language of WCDB

> Objective-C 

### The version of WCDB

> 'WCDB', '~> 1.0.6'

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> Cannot initialize return object of type 'UITableViewCellEditingStyle' with an rvalue of type 'long'
> when i change the file .m to .mm ，xcode give me the error
![image](https://user-images.githubusercontent.com/16099174/40787866-37deb686-6521-11e8-9507-3f30d3decb72.png)
![image](https://user-images.githubusercontent.com/16099174/40787899-485cfaa4-6521-11e8-94b4-be8558dc12c2.png)

**Comment by RingoD** [comment]
In cpp, converting from a `enum` value to a raw integer is not allowed. You can do a force conversion or change the compiler setting.
