### ISSUE TITLE
wcdb-android:1.0.6.2提示错误

### ISSUE THREAD

**Issue by onexuan** [Tencent/wcdb#307]
无法同步到最新1.0.6.2
implementation 'com.tencent.wcdb:wcdb-android:1.0.6.2' 提示错误

Error:(117, 20) Failed to resolve: com.tencent.wcdb:wcdb-android:1.0.6.2

但implementation 'com.tencent.wcdb:wcdb-android:1.0.6' 成功

**Comment by John-He-928** [comment]
Bintray出了点问题，现在已经恢复，可以同步1.0.6.2
