### ISSUE TITLE
Android 性能问题

### ISSUE THREAD

**Issue by zichengzhang** [Tencent/wcdb#308]
<img width="660" alt="wcdb" src="https://user-images.githubusercontent.com/24287835/42486848-abe5bae2-8430-11e8-8186-8ad06e7a9aa1.png">

麻烦帮看一下这个可能是什么原因导致的？有时操作数据库完成需要等几十秒，偶发的不是必现得

**Comment by lightai** [comment]
db访问是用的一个线程池么？wal模式下write是串行的，如果不做读写分离，很有可能db线程都卡在write上

**Comment by lightai** [comment]
flag0x2意思是需要更新db，需要主connection，但是主connection被另外更新db的线程持有了，所以这里只有等主connection了。

**Comment by zichengzhang** [comment]
Open: true
      Max connections: 4
      Available primary connection:
        <none>
      Available non-primary connections:
        Connection #1:
          connectionPtr: 0xffffffffb751fe68
          isPrimaryConnection: false
          onlyAllowReadOnlyOperations: true
          Most recently executed operations:
            0: [2018-06-22 19:53:48.073] executeForCursorWindow took 1ms - succeeded, sql="SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?", tid=10111, bindArgs=["data_index_1"]
            1: [2018-06-22 19:53:48.073] prepare took 0ms - succeeded, sql="SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?", tid=10111
            2: [2018-06-22 19:53:48.073] executeForCursorWindow took 0ms - succeeded, sql="SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?", tid=10111, bindArgs=["data_index_7"]
            3: [2018-06-22 19:53:48.073] prepare took 0ms - succeeded, sql="SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?", tid=10111
            4: [2018-06-22 19:53:48.023] executeForCursorWindow took 0ms - succeeded, sql="SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?", tid=10109, bindArgs=["data_index_1"]
            5: [2018-06-22 19:53:48.023] prepare took 0ms - succeeded, sql="SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?", tid=10109
06-22 19:53:52.182 9998-10111/SQLiteDatabase onConnectionPoolBusy::         6: [2018-06-22 19:53:48.023] executeForCursorWindow took 0ms - succeeded, sql="SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?", tid=10109, bindArgs=["data_index_7"]
            7: [2018-06-22 19:53:48.023] prepare took 0ms - succeeded, sql="SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?", tid=10109
            8: [2018-06-22 19:53:48.022] executeForLong took 0ms - succeeded, sql="PRAGMA user_version;", tid=10109
            9: [2018-06-22 19:53:48.022] executeForLong took 0ms - succeeded, sql="PRAGMA wal_autocheckpoint=100", tid=10109
            10: [2018-06-22 19:53:48.022] executeForLong took 0ms - succeeded, sql="PRAGMA wal_autocheckpoint", tid=10109
            11: [2018-06-22 19:53:48.022] executeForLong took 0ms - succeeded, sql="PRAGMA journal_size_limit=524288", tid=10109
            12: [2018-06-22 19:53:4a8.022] executeForLong took 0ms - succeeded, sql="PRAGMA journal_size_limit", tid=10109
            13: [2018-06-22 19:53:48.021] executeForString took 1ms - succeeded, sql="PRAGMA synchronous", tid=10109
            14: [2018-06-22 19:53:47.529] executeForString took 492ms - succeeded, sql="PRAGMA journal_mode", tid=10109
            15: [2018-06-22 19:53:47.529] executeForLong took 0ms - succeeded, sql="PRAGMA foreign_keys", tid=10109
            16: [2018-06-22 19:53:47.529] execute took 0ms - succeeded, sql="PRAGMA cipher_page_size=4096", tid=10109
            17: [2018-06-22 19:53:47.529] executeForLong took 0ms - succeeded, sql="PRAGMA cipher_page_size", tid=10109
          Prepared statement cache:
            0: statementPtr=0xffffffffb7a36158, numParameters=1, type=1, readOnly=true, sql="SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?"
      Acquired connections:
        Connection #0:
06-22 19:53:52.192 9998-10111/SQLiteDatabase onConnectionPoolBusy::       connectionPtr: 0xffffffffb7ef05f8
          isPrimaryConnection: true
          onlyAllowReadOnlyOperations: false
          Most recently executed operations:
            0: [2018-06-22 19:53:49.176] executeForChangedRowCount started 3019ms ago - running, sql="VACUUM", tid=10109
            1: [2018-06-22 19:53:49.176] execute took 0ms - succeeded, sql="COMMIT;", tid=10111
            2: [2018-06-22 19:53:49.176] executeForCursorWindow took 0ms - succeeded, sql="SELECT changes() AS affected_row_count", tid=10111
            3: [2018-06-22 19:53:49.175] prepare took 1ms - succeeded, sql="SELECT changes() AS affected_row_count", tid=10111
            4: [2018-06-22 19:53:49.175] executeForChangedRowCount took 0ms - succeeded, sql="delete from data_index_1 where orderDate < ? and orderStatus not in (1,2) and payStatus != 1 ;", tid=10111, bindArgs=["1528977228073"]
            5: [2018-06-22 19:53:49.175] prepare took 0ms - succeeded, sql="delete from data_index_1 where orderDate < ? and orderStatus not in (1,2) and payStatus != 1 ;", tid=10111
            6: [2018-06-22 19:53:49.175] execute took 0ms - succeeded, sql="BEGIN IMMEDIATE;", tid=10111
            7: [2018-06-22 19:53:49.175] prepare took 0ms - succeeded, sql="VACUUM", tid=10109
            8: [2018-06-22 19:53:49.174] execute took 0ms - succeeded, sql="COMMIT;", tid=10111
            9: [2018-06-22 19:53:49.174] executeForCursorWindow took 0ms - succeeded, sql="SELECT changes() AS affected_row_count", tid=10111
            10: [2018-06-22 19:53:49.174] prepare took 0ms - succeeded, sql="SELECT changes() AS affected_row_count", tid=10111
            11: [2018-06-22 19:53:49.173] executeForChangedRowCount took 1ms - succeeded, sql="delete from data_core where uuid in (select t.uuid from data_core t inner join data_index_1 o on t.uuid=o.data_core_id where o.orderDate<? and o.orderStatus not in (1,2) and o.payStatus != 1);", tid=10111, bindArgs=["1528977228073"]
06-22 19:53:52.202 9998-10111/SQLiteDatabase onConnectionPoolBusy::         12: [2018-06-22 19:53:49.173] prepare took 0ms - succeeded, sql="delete from data_core where uuid in (select t.uuid from data_core t inner join data_index_1 o on t.uuid=o.data_core_id where o.orderDate<? and o.orderStatus not in (1,2) and o.payStatus != 1);", tid=10111
            13: [2018-06-22 19:53:49.173] execute took 0ms - succeeded, sql="BEGIN IMMEDIATE;", tid=10111
            14: [2018-06-22 19:53:49.173] execute took 0ms - succeeded, sql="COMMIT;", tid=10109
            15: [2018-06-22 19:53:49.173] executeForCursorWindow took 0ms - succeeded, sql="SELECT changes() AS affected_row_count", tid=10109
            16: [2018-06-22 19:53:49.173] prepare took 0ms - succeeded, sql="SELECT changes() AS affected_row_count", tid=10109
            17: [2018-06-22 19:53:49.173] executeForChangedRowCount took 0ms - succeeded, sql="delete from data_index_1 where orderDate < ? and orderStatus not in (1,2) and payStatus != 1 ;", tid=10109, bindArgs=["1528977227012"]
            18: [2018-06-22 19:53:49.173] prepare took 0ms - succeeded, sql="delete from data_index_1 where orderDate < ? and orderStatus not in (1,2) and payStatus != 1 ;", tid=10109
            19: [2018-06-22 19:53:49.171] execute took 2ms - succeeded, sql="BEGIN IMMEDIATE;", tid=10109
          Prepared statement cache:
            0: statementPtr=0xffffffffb7ae1e58, numParameters=1, type=2, readOnly=false, sql="delete from data_core where uuid in (select t.uuid from data_core t inner join data_index_7 o on t.uuid=o.data_core_id where o.operateTime < ? ) ;"
            1: statementPtr=0xffffffffb7a35b00, numParameters=1, type=2, readOnly=false, sql="delete from data_upload_task where upload_status=2 and update_time < ? ;"
            2: statementPtr=0xffffffffb791ec50, numParameters=1, type=2, readOnly=false, sql="delete from data_core where uuid in (select t.uuid from data_core t inner join data_index_1 o on t.uuid=o.data_core_id where o.orderDate<? and o.orderStatus not in (1,2) and o.payStatus != 1);"
            3: statementPtr=0xffffffffb7b39e18, numParameters=1, type=2, readOnly=false, sql="delete from data_index_1 where orderDate < ? and orderStatus not in (1,2) and payStatus != 1 ;"
            4: statementPtr=0xffffffffb7ef6950, numParameters=0, type=1, readOnly=true, sql="SELECT changes() AS affected_row_count"
          Status: NORMAL
      Connection waiters:
        0: waited for 3035 ms - thread=Thread[pool-14-thread-2,5,main], priority=0, sql='VACUUM'
06-22 19:53:52.202 9998-10020/ dogTime: 1529668432210 \ !: SQLiteDatabase onConnectionPoolBusy: db=SQLiteDatabase: /mnt/internal_sd/database/shop_data_1, sql=VACUUM, requests=[executeForChangedRowCount started 3001ms ago - running, sql="VACUUM", tid=10109], message=The connection pool for database '/mnt/internal_sd/database/shop_data_1' has been unable to grant a connection to thread 4397 (pool-14-thread-2) with flags 0x2 for 3.0010002 seconds.
    Connections: 1 active, 0 idle, 1 available.
    
    Requests in progress:

@lightai @John-He-928 我本地模拟了一下，但也只等了3s，dump出来我也没发现什么。这种问题一般是什么原因导致的，为什么要等主connection，其他的connection为啥不能用，你们有遇到过吗？应该怎么处理，我们项目目前用的版本是1.0.2
