### ISSUE TITLE
SQLITE_OPEN_FILEPROTECTION_COMPLETE can't be used in WCDB?

### ISSUE THREAD

**Issue by zedzhao** [Tencent/wcdb#309]
> Objective-C, Swift
>  iOS, macOS 

### What's the issue?

The sqlite3 in iOS Library contains the following MACROS which is not included in official SQLite:
#define SQLITE_OPEN_FILEPROTECTION_COMPLETE                             0x00100000
#define SQLITE_OPEN_FILEPROTECTION_COMPLETEUNLESSOPEN                   0x00200000
#define SQLITE_OPEN_FILEPROTECTION_COMPLETEUNTILFIRSTUSERAUTHENTICATION 0x00300000
#define SQLITE_OPEN_FILEPROTECTION_NONE                                 0x00400000
#define SQLITE_OPEN_FILEPROTECTION_MASK                                 0x00700000

And I see the WCDB depends on SQLCipher, so if I use WCDB in my project, is there any way may let these file protection features work?

**Comment by RingoD** [comment]
Basically, there macros are used for file protection to avoid crash when using `mmap` in `shm` file. Since WCDB already handle the file protection mode, developers have no need to concern about these.

**Comment by zedzhao** [comment]
OK ,I check the code found that WCDB use NSFIlemanager to implement the file protection feature, is it right?

**Comment by RingoD** [comment]
Right.

**Comment by zedzhao** [comment]
If sqlite use WAL mode,  do the shm and wal file need be set the file protection?
If so, what time is it?  Because the shm and wal file are created at the first I/O operation.

**Comment by RingoD** [comment]
Yes.
The file protection of those files will be set up by WCDB when they created.
