### ISSUE TITLE
how can I open the wal file?

### ISSUE THREAD

**Issue by hxming2919** [Tencent/wcdb#310]
### The language of WCDB

> Objective-C

### The version of WCDB

> e.g. v1.0.4

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> how can I open the wal file?

I try to open the wal file, but I faild.
I see the below info, then I input the pwd to open wal, also the result is failed. 
can you give me some help?thanks.

========
命令行无法打开WCDB创建的加密数据库

除了password，还需要设置cipher的page size，默认为4096

PRAGMA key="your_password";
PRAGMA cipher_page_size=4096;

> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
WAL is automatically opened when ones open the db file. Check the sqlite tutorial for further info.

**Comment by RingoD** [comment]
No reply.
