### ISSUE TITLE
android可以添加SQLITE_WCDB_SIGNAL_RETRY=1编译选项么？

### ISSUE THREAD

**Issue by lightai** [Tencent/wcdb#311]
### The language of WCDB

> Java 

### The version of WCDB

> v1.0.6

### The platform of WCDB

> Android

### What's the issue?
ios平台下开启了SQLITE_WCDB_SIGNAL_RETRY=1编译选项，
应该是sqlite单进程模式下使用线程锁代替sqlite默认的文件锁，
请问android也能开启SQLITE_WCDB_SIGNAL_RETRY么，不然android wal
并发模式下有可能会出现sqlite_busy问题。

**Comment by John-He-928** [comment]
Android进程内使用Java实现的连接池实现并发，不依赖SQLite底层的文件锁，只要相同进程使用同一个SQLiteDatabase对象即不会存在并发访问的问题
