### ISSUE TITLE
在桥接头文件中@import Charts; 会报错

### ISSUE THREAD

**Issue by Wuou** [Tencent/wcdb#312]
### The language of WCDB

> Objective-C

### The version of WCDB

>  v1.0.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

>  请问下这个是什么问题？   在桥接头文件中@import Charts; 会报错
Use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules
![image](https://user-images.githubusercontent.com/14285500/41270708-5a13c2ec-6e3f-11e8-931c-bbcaeda855be.png)

**Comment by RingoD** [comment]
As the issue template said, please describable your question in English.

**Comment by RingoD** [comment]
As for your question, the answer is already in your screenshot: `Use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules`

**Comment by hatjs880328s** [comment]
enable module  设置为 yes
auto link 设置为 yes

other c++ flags 中添加  -fcxx-modules 即可。
