### ISSUE TITLE
android wal模式下，读线程数超过两个之后select性能并没有提高的问题

### ISSUE THREAD

**Issue by lightai** [Tencent/wcdb#313]
### The language of WCDB

java

### The version of WCDB

v1.0.6

### The platform of WCDB

 Android

### The installation of WCDB

源码

### What's the issue?

[`wiki`](https://github.com/Tencent/wcdb/wiki/%E6%80%A7%E8%83%BD%E6%95%B0%E6%8D%AE%E4%B8%8EBenchmark)上Multithread Read-Read开启了两个线程。
我这边跑的Multithread Read-Read benchmark，两个线程的ops/sec是单线程的两倍，是正常的，
但是超过两个线程之后ops/sec并没有提升，还是跟两个线程是一样的，理论上ops/sec应该是线程数正相关的。
这个是正常现象么？

**Comment by RingoD** [comment]
no reply.
