### ISSUE TITLE
ORM 一个 model 对应多个表结构

### ISSUE THREAD

**Issue by leonylcatwork** [Tencent/wcdb#315]
例如 有一个 model Message，其中有 id, sender, receiver, created_time, read_time, content 等 property。正常建表把这些 property 都映射到 sqlite 表字段里。同时，我还需要另一张表，储存字段比较少，例如只有 id, sender, read_time。有什么办法让 Message 这个 model 同时能在两个表做 ORM 呢？当然第二个表缺少的字段映射后可以是 nil。

我暂时能想到的办法是创建 Message2 继承 Message， 在 implementation 里面只映射需要的字段， 例如
WCDB_SYNTHESIZE_COLUMN_DEFAULT(Message2, id, "id", NULL)
WCDB_SYNTHESIZE_COLUMN_DEFAULT(Message2, sender, "sender",  NULL)
WCDB_SYNTHESIZE_COLUMN_DEFAULT(Message2, read_time, "read_time", NULL)

这样表2 ORM 后的 Message2 也可以直接传给接受 Message 为参数的方法。

除此之外有没有更好的不用写新类的办法？

**Comment by RingoD** [comment]
As the issue template said, please describable your question in English and provide the basic information.

**Comment by leonylcatwork** [comment]
Alright, this is not an issue but a question. I try to rephrase it as simple as possible.

Say, I have a model called 'Message' containing properties: 'id', 'sender', 'created_time', 'read_time', and 'content'. 

Now I want two tables: table1, with columns of all 5 properties; and table2 with only 'id', 'sender' and 'read_time'. Creating table1 is easy and ORM will work straight away. The question is what is the best way to create and maintain table2, without having to create a new class of model?

**Comment by RingoD** [comment]
I'm Sorry but I need all other informations mentioned in issue template. e.g. Version? The way of installation? Language(seems like ObjC)?
Or I don't know how to reply you.

**Comment by RingoD** [comment]
no reply.
