### ISSUE TITLE
WCTPropertyList does not support remove(), find() etc. because of '==' operator overloading

### ISSUE THREAD

**Issue by leonylcatwork** [Tencent/wcdb#316]
### The language of WCDB
Objective-C

### The version of WCDB
v1.0.5

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?
WCTPropertyList is a list of WCTProperty. But WCTProperty overloads '==' operator (returns 'WCTExpr') and the native implementation of a list performs element comparison using '==' operator. For example, remove(). This raise a compile error: No viable conversion from 'WCTExpr' to 'bool'.

Sample code:

// suppose this SomeClass has a property 'id'
WCTPropertyList list = SomeClass.AllProperties;
// remove
list.remove(SomeClass.id);
// find
std::list<const WCTProperty>::iterator it = std::find(list.begin(), list.end(), SomeClass.id);

// will get compile error: No viable conversion from 'WCTExpr' to 'bool'.

### What I expect 
Suppose I have a class with 100 properties and I want to get a property list of all of them, I use +AllProperties. Now I want to remove a particular property from the list such that the list contains only 99 properties. How do we do that?

**Comment by RingoD** [comment]
Yes. Currently, `WCTPropertyList` can only be assembled, but not `remove` of `find`.
It's already re-design in the new feature branch, which will release in next version.

**Comment by RingoD** [comment]
`WCTPropertyList` inherits from `std::list`, so developers can operate it freely.
