### ISSUE TITLE
database can not open after create

### ISSUE THREAD

**Issue by intspt** [Tencent/wcdb#317]
### The language of WCDB

Objective-C

### The version of WCDB

1.0.6

### The platform of WCDB

iOS

### The installation of WCDB

Git clone

### What's the issue?

WCTDatabase *database = [[WCTDatabase alloc] initWithPath:path];
if ([database canOpen]) {

then output

2018-06-17 13:01:00.304410+0800 test[13996:142189] [logging] API call with invalid database connection pointer
2018-06-17 13:01:00.304548+0800 test[13996:142189] [logging] misuse at line 117984 of [2b0954060f]
[WCDB][ERROR]Code:21, Type:SQLite, Tag:0, Op:4, ExtCode:0, Msg:not an error, SQL:PRAGMA synchronous='NORMAL', Path:/Users/spt/Library/Developer/CoreSimulator/Devices/90332C48-ECEC-405D-AA7A-0CDED3E67773/data/Containers/Data/Application/83450C02-A6BC-4895-B673-5FF7D0FB0E39/Documents/test.db

**Comment by RingoD** [comment]
What about changing the path of database?

**Comment by intspt** [comment]
@RingoD I'm sorry;
Everything is OK after I add all_load to the Other Linker Flags
