### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException Couldn't read row 1461, col 0 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.

### ISSUE THREAD

**Issue by lightai** [Tencent/wcdb#319]
### The language of WCDB

> Java 

### The version of WCDB

> wcdb-room (2017 year)

### The platform of WCDB

> Android

### The installation of WCDB

> Git clone

### What's the issue?
query sql is: "select * from TB_XX where deleteTime = 0 and duplicated = ? and categoryId > -1".

Fatal Exception: java.lang.IllegalStateException Couldn't read row 1461, col 0 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it. Raw Text
--
  | com.tencent.wcdb.CursorWindow.nativeGetLong (CursorWindow.java)
  | com.tencent.wcdb.CursorWindow.getLong (CursorWindow.java:502)
  | com.tencent.wcdb.AbstractWindowedCursor.getLong (AbstractWindowedCursor.java:77)
  | com.tencent.wcdb.AbstractCursor.moveToPosition (AbstractCursor.java:223)
  | com.tencent.wcdb.AbstractCursor.moveToNext (AbstractCursor.java:248)

**Comment by lightai** [comment]
Devices
Xiaomi44%
Letv14%
HUAWEI14%
vivo14%
Other…14%
Operating Systems
5 43%
6 43%
7 14%

**Comment by John-He-928** [comment]
由于你没有提供代码和其他错误log，我只能说这个是个典型的访问越界，你moveToNext或者类似的调用后没有判断返回值，导致访问了结果集里面不存在的行，比如你这个结果集很可能只有1461行
