### ISSUE TITLE
无法通过pod 获取wcdb 

### ISSUE THREAD

**Issue by sunjames** [Tencent/wcdb#32]
无法通过pod search wcdb 搜索到 结果 提示 ：[!] Unable to find a pod with name, author, summary, or description matching `wcdb`

**Comment by RingoD** [comment]
我能搜到，是否是你的索引没有更新。
尝试执行`pod repo update `，如果还不行，则删掉cocoapods的索引缓存`rm ~/Library/Caches/CocoaPods/search_index.json`后再试

**Comment by RingoD** [comment]
no reply

**Comment by d553296416** [comment]
确实无法搜索到
