### ISSUE TITLE
Pod compiler errors.

### ISSUE THREAD

**Issue by fpfengpan** [Tencent/wcdb#320]
### The language of WCDB

Swift 4.1

### The version of WCDB

v1.0.6

### The platform of WCDB

macOS

### The installation of WCDB

Cocoapods

### What's the issue?
> After installed WCDB, I got compiler errors 
![screen shot 2018-06-22 at 4 16 02 pm](https://user-images.githubusercontent.com/9455505/41765851-e28c6282-7637-11e8-9cdc-e077cc455de7.png)

**Comment by fpfengpan** [comment]
@RingoD Does WCDB support for Swift 4.1?

**Comment by RingoD** [comment]
No.
It's already mentioned in the release note: https://github.com/Tencent/wcdb/releases/tag/v1.0.6.2

**Comment by fpfengpan** [comment]
Well... ok
