### ISSUE TITLE
rename table API is not found

### ISSUE THREAD

**Issue by lishuailibertine** [Tencent/wcdb#322]

**Comment by RingoD** [comment]
You can check the document in SQLite official website to learn about how to altering a table: https://sqlite.com/lang_altertable.html

**Comment by lishuailibertine** [comment]
- (BOOL)alterTableWithDBType:(HBDBType)withDBType
               withTableName:(NSString *)tableName
            withNewTableName:(NSString *)newtableName{
    
    WCTDatabase * withDB =[self getDBWithDBType:withDBType];
    WCDB::Error innerError;
    return _core->exec(WCDB::StatementAlterTable()
                       .alter(tableName.UTF8String)
                       .rename(newtableName.UTF8String),
                       innerError);
    
}

do I want to change it like this?

**Comment by RingoD** [comment]
Just try it.
You can register the sql trace to make sure whether your sql correct.

**Comment by lishuailibertine** [comment]
During compilation,xcode  prompt  `Use of undeclared identifier '_core' `

**Comment by lishuailibertine** [comment]
@RingoD During compilation,xcode prompt Use of undeclared identifier '_core'

**Comment by RingoD** [comment]
Why do you modify the source code of WCDB ?
Please check core interface tutorial in wiki.

**Comment by lishuailibertine** [comment]
@RingoD I didn't want to modify the source code. I was dull. The existing interface in the SDK didn't find what I wanted. 囧

**Comment by RingoD** [comment]
Both `_core` and `WCDB::Error` are the underlying implementation components of WCDB. I don't why should you use them.
All the common used interfaces are mentioned in wiki. Please read.

**Comment by RingoD** [comment]
I think I am already answered.
> You can check the document in SQLite official website to learn about how to altering a table in SQL: https://sqlite.com/lang_altertable.html

You should use core interface to implement it. About `Core Interface`, it can be checked in the wiki.

**Comment by lishuailibertine** [comment]
@RingoD Wow, thanks a lot. I found it for a long time. ` [withDB exec:WCDB::StatementAlterTable().alter(tableName.UTF8String).rename(newtableName.UTF8String)];`.

**Comment by RingoD** [comment]
The fastest way to learn a new skill is to read its document slowly.

**Comment by kfq0072** [comment]
dropIndexOfName怎么用啊，[database dropIndexOfName:@"state"];没效果
