### ISSUE TITLE
How can I use Array in my model with WCDBSwift?

### ISSUE THREAD

**Issue by LabanL** [Tencent/wcdb#323]
### The language of WCDB

> Swift

### The version of WCDB

> v1.0.6.2

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

I have a 'tag' field  with Array<String> type in my model,  like **var tag: Array<String>?**.    
<img width="312" alt="a7609f092a1f0c86db03957447290b79" src="https://user-images.githubusercontent.com/3862082/42204217-a1c0fc14-7ed3-11e8-9cc5-9f574173e277.png">

And it build success, but in the runtime, the app is broken. And console has a warning, as follow:

**warning: Swift runtime does not yet support dynamically querying conditional conformance ('Swift.Array<Swift.String>': 'WCDBSwift.ColumnDecodable')**
<img width="536" alt="42bb5590-31ba-4b76-b4a3-95cad684ba80" src="https://user-images.githubusercontent.com/3862082/42204258-c4f8acc2-7ed3-11e8-9d76-90bc35fb29ce.png">

**Comment by RingoD** [comment]
As the release note said, you should use Xcode 10(Beta) for v1.0.6.2

**Comment by RingoD** [comment]
No reply.
