### ISSUE TITLE
wcdb.swift compiler error

### ISSUE THREAD

**Issue by luojianzhen** [Tencent/wcdb#324]
### The language of WCDB

> Swift 4.0

### The version of WCDB

> v1.0.6.2

### The platform of WCDB

> iOS

### The installation of WCDB

>  Cocoapods

### What's the issue?

![err1](https://user-images.githubusercontent.com/1590679/42211910-418f758c-7ee7-11e8-90cb-041d21e3f338.jpg)
![err2](https://user-images.githubusercontent.com/1590679/42211922-49ec2bbc-7ee7-11e8-8430-020929ca5471.jpg)
![err3](https://user-images.githubusercontent.com/1590679/42211935-4f610324-7ee7-11e8-8fe7-0f2dcc6822cd.jpg)

**Comment by RingoD** [comment]
As the release note said, you should use Xcode 10(Beta) for v1.0.6.2

**Comment by RingoD** [comment]
No reply.
