### ISSUE TITLE
WCDB.swift dependency in podspec build error

### ISSUE THREAD

**Issue by Jonzzs** [Tencent/wcdb#325]
### The language of WCDB

> Swift

### The version of WCDB

> v1.0.6.2

### The version of Xcode

> v9.4.1

### The version of Swift

> v4.1.2

### What's the issue?

> add `s.dependency 'WCDB.swift', '1.0.6.2'` in my podspec, validate error, but build success in Xcode, how can i fix this question, this is errors and warnings:

![](https://ws3.sinaimg.cn/large/006tNc79gy1fswttpbwm6j313c27ahdl.jpg)

**Comment by RingoD** [comment]
As the release note said, you should use Xcode 10(Beta) for v1.0.6.2

**Comment by Jonzzs** [comment]
@RingoD There are other libraries that are not adapted for Xcode 10(Beta), but I used Xcode 9.2(Swift 4.0) for WCDB.swift v1.0.6, the same problem exists:

![](https://ws2.sinaimg.cn/large/006tNc79gy1fsxol93tpkj30l615ob29.jpg)

**Comment by Jonzzs** [comment]
@RingoD But there is no problem with Xcode compilation, just error with podspec validate.

**Comment by RingoD** [comment]
Are you embedding WCDBSwift into your Podspec ? 
I believe that should be problem of the podspec, maybe the lack of header path.

**Comment by Jonzzs** [comment]
@RingoD I tried to install using carthage, but why I can't install v1.0.6 with carthage, I input `github "Tencent/WCDB" == 1.0.6` in Cartfile, but the actual installation is v1.0.6.2, does the v1.0.6 version not support carthage?

![](https://ws1.sinaimg.cn/large/006tNc79gy1fsxyiilv0hj30ia062dg4.jpg)

![](https://ws4.sinaimg.cn/large/006tNc79gy1fsxyiog7abj30ir0dc0tk.jpg)

**Comment by RingoD** [comment]
Since Carthage will clone the git repo and build, there is no relationship between how Carthage works and what WCDB is. In other word, there is not such thing as "Support Carthage".
I think it would be the bug of Carthage. Maybe you should submit an issue to them.

By the way, it works with `github "Tencent/WCDB" "v1.0.6"`.

**Comment by SeraZheng** [comment]
I got the same issue. I install v1.0.6 with carthage, after "carthage update", only WCDBSwift.framework file, no sqlcipher.swift.framework and sqliterk.swift.framework file.But WCDB.swift is not dependency by podspec, which is only import WCDBSwift by main project. My project contains Cocoapods for static library, Carthage for WCDB.

**Comment by SeraZheng** [comment]
And I have tested project with WCDBSwift dependency of Carthage only, nothing works.
Enveriment:
Xcode 9.2
Swift 4.0
github WCDB v1.0.6

**Comment by RingoD** [comment]
@SeraZheng Didn't I already answer? 

As the release note said, you should use Xcode 10(Beta) for v1.0.6.2

**Comment by Jonzzs** [comment]
@SeraZheng I tried to add the following code to the podspec, it works, it can be temporarily solved the podspec build error issue.

```
s.xcconfig = { "GCC_PREPROCESSOR_DEFINITIONS" => "$(inherited) WCDB_BUILTIN_SQLCIPHER WCDB_COCOAPODS" }
```
