### ISSUE TITLE
wcdb存在情况会自动drop表或者db吗？

### ISSUE THREAD

**Issue by 669754618** [Tencent/wcdb#326]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Objective-C

### The version of WCDB

> e.g. v1.0.5
v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

ios

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
As the issue template said, please describe your issue in English.

**Comment by RingoD** [comment]
no reply.
