### ISSUE TITLE
Is there a tool for WCDB analysis in PC for encrypted WCDB file?

### ISSUE THREAD

**Issue by ysuliu** [Tencent/wcdb#327]
### The language of WCDB

Java

### The version of WCDB

 v1.0.5

### The platform of WCDB

Android

### The installation of WCDB

Maven

### What's the issue?

Originally, we use 'SQLite Expert' for non-encrypted database file analysis in PC. 

We migrated to WCDB in recent days with the option encrypt. Now my question is that we can not open the .db file by 'SQLite Expert' any more.

Is there a tools for this case? Once I provide the password, I can see the data in PC.

Thanks a lot.

**Comment by RingoD** [comment]
I don't known what "SQLite Expert" is. 
BUT since WCDB is a SQLite-based framework without any changed on the database file, any tools that can open SQLite will work.

**Comment by ysuliu** [comment]
The point is 'encrypted'. The common tools does NOT support this kind of database files. The way or tool to  open the database file in PC is important for debug/analysis during development.
Hope you guys could have an investigation about that, thanks.

**Comment by RingoD** [comment]
Actually, there is not difference. 
I have no idea about SQLite tools on PC.
But as I said, the database created by WCDB is the same as SQLite(SQLCipher).
Any tools that can open an encrypted SQLite database will work( by setting the correct password and `cipher_page_size` to 4096 ).

**Comment by ysuliu** [comment]
1, I got your answer is "Any tools that can open an encrypted SQLite database will work( by setting the correct password and cipher_page_size to 4096 )." But I still do not know which tool could do that. Seems you guys have no idea about it. That's OK, I'll try to solve this by myself later.
2, This issue is for Android obviously, please label it to the correct category.

**Comment by RingoD** [comment]
There's a huge number of SQLite tools. Maybe you can google it.

**Comment by liu12151407** [comment]
sqlcipher 客户端（PC版本）
