### ISSUE TITLE
Msg:no such column:

### ISSUE THREAD

**Issue by wdq123550** [Tencent/wcdb#333]
why i add new property to class .and running agian, and wcdb not found my table ,xcode said no much column

complete xcode said that "[WCDB][DEBUG]Code:1, Type:SQLiteGlobal, Msg:no such column: lastTime"

i add lastTime property to my class ,and runging agin ,it's that,why?
my english is poor sorry!

**Comment by RingoD** [comment]
As the template said, please provide the basic information for your issue.
