### ISSUE TITLE
有一个自定义对象数组，如何存储进数据库中？

### ISSUE THREAD

**Issue by GirlCunt** [Tencent/wcdb#335]
### The language of WCDB

>  Objective-C,

### The version of WCDB

> e.g. v1.0.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

**Comment by RingoD** [comment]
As the issue template said, please describe your issue in English.

**Comment by RingoD** [comment]
As for your question, it's already mentioned in the tutorial.
