### ISSUE TITLE
spec 文件中的 sqlcipher.xcconfig 是否必要？

### ISSUE THREAD

**Issue by Whirlwind** [Tencent/wcdb#336]
在 WCDB.podspec 中，有设置 `sqlcipher.xcconfig`，这些配置影响了主项目的相关配置。这些配置一定要加到主项目吗？如果只是自己target使用，可以改成 `sqlcipher.pod_target_xcconfig`。
```
            "CLANG_WARN_CONSTANT_CONVERSION": "YES",
            "GCC_WARN_64_TO_32_BIT_CONVERSION": "NO",
            "CLANG_WARN_UNREACHABLE_CODE": "NO",
            "GCC_WARN_UNUSED_FUNCTION": "NO",
            "GCC_WARN_UNUSED_VARIABLE": "NO"
```

**Comment by RingoD** [comment]
As the issue template said, please describe your issue in English.

**Comment by RingoD** [comment]
I think you are right. It would be better to add them as a private config. 
It will be done in the next version.

**Comment by RingoD** [comment]
https://github.com/Tencent/sqlcipher/commit/827b250f7b75ef8d1c4a4b662c58acad9ece85ef

**Comment by Whirlwind** [comment]
@RingoD Should you update the https://github.com/Tencent/wcdb/blob/master/WCDB.podspec ?

**Comment by RingoD** [comment]
On going. Don't worry.
