### ISSUE TITLE
分词器搜索不够智能

### ISSUE THREAD

**Issue by wangduanqing5945** [Tencent/wcdb#339]
在demo中尝试了分词器的效果，入库一个文本 “中华人民共和国”，然后进行搜索，输入“中”，可以匹配到，输入"中华"可以匹配到，输入"中华国"也可以匹配到；非常的傻。而在微信中的体验就不是如此，输入"中"不能匹配，输入"中华"可以匹配，体验非常棒。望给下原因

**Comment by wangduanqing5945** [comment]
没人回答吗，如果有词库的话，词库是否可以开源？

**Comment by iamcxl369** [comment]
你是android还是ios?

**Comment by RingoD** [comment]
As the issue template said, please describe your question is English and provide the basic information.

**Comment by wangduanqing5945** [comment]
@iamcxl369 android

**Comment by wangduanqing5945** [comment]
微信的安卓端是有中文词库的支持吗？能解释下上面的问题吗

**Comment by RingoD** [comment]
@John-He-928

**Comment by iamcxl369** [comment]
微信自己自定义了FTS5的分词器好像
