### ISSUE TITLE
关于复合主键

### ISSUE THREAD

**Issue by mdjwanghong** [Tencent/wcdb#34]
我看文档使用：
WCDB_PRIMARY(Message, localID)
设置主键，我如果想用复合主键，可以用如下的方法吗？
WCDB_PRIMARY(Message, localID)
WCDB_PRIMARY(Message, content)

**Comment by RingoD** [comment]
复合主键用WCDB_MULTI_PRIMARY的宏，确保constraintName相同，就会组合起来了。这部分文档我明天就放上去了

**Comment by mdjwanghong** [comment]
回复的太快了，我的应用马上要上线了，看到这个开源的组件，打算全部改造一下，但我发现下载的demo，里面不是很全面，再者能不能弄一个详细的全中文说明的文档，这样学习起来会更快此，毕竟每个类看下来，挺累的！

**Comment by RingoD** [comment]
sample里有绝大部分的例子，wiki上也有全中文的文档。不知道你对哪方面有疑问

**Comment by RingoD** [comment]
@mdjwanghong  ORM的教程已经上传，请参考 https://github.com/Tencent/wcdb/wiki/ORM使用教程 ， 如有疑问请进一步提出

**Comment by RingoD** [comment]
no reply
