### ISSUE TITLE
podspec 推送的时候，报 'list' file not found

### ISSUE THREAD

**Issue by lsqswl** [Tencent/wcdb#340]
只是编译wcdb的文件，没有我们自己的文件。已经全是.mm了。

使用wcdb的podspec，想自己发一个pod版本。

NOTE | [WCDB/sqlcipher] xcodebuild: WCDB/sqlcipher/src/util.c:408:7: note: cast expression to void to silence warning
ERROR | xcodebuild: Headers/Public/WCDB/WCDB.h:25:2: error: Since WCDB is an Objective-C++ framework, for those files in your project that includes WCDB, you should rename their extension .m to .mm.
NOTE | xcodebuild: Headers/Public/WCDB/describable.hpp:24:10: fatal error: 'list' file not found

**Comment by RingoD** [comment]
As the issue template said, please desirable your question in English and provide the basic information for us.

**Comment by lsqswl** [comment]
chinese library......

**Comment by lsqswl** [comment]
[WCDB.podspec.zip](https://github.com/Tencent/wcdb/files/2234853/WCDB.podspec.zip)

the file is our podspec, and all other files or dir are wcdb's. 

when run "pod repo push", the problem take place.

**Comment by RingoD** [comment]
Please provide the basic information in issue template for us.

**Comment by lsqswl** [comment]
https://github.com/Tencent/wcdb/issues/341
