### ISSUE TITLE
'list' file not found

### ISSUE THREAD

**Issue by lsqswl** [Tencent/wcdb#341]
### The language of WCDB

> Objective-C

### The version of WCDB

> e.g. v1.0.6

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?
[WCDB.podspec.zip](https://github.com/Tencent/wcdb/files/2234873/WCDB.podspec.zip)

the file is our podspec, and all other files or dir are wcdb's.

we want to fix some problem. But,
when run "pod repo push", the "'list' file not found" take place.

part:

NOTE | [WCDB/sqlcipher] xcodebuild: WCDB/sqlcipher/src/util.c:408:7: note: cast expression to void to silence warning
ERROR | xcodebuild: Headers/Public/WCDB/WCDB.h:25:2: error: Since WCDB is an Objective-C++ framework, for those files in your project that includes WCDB, you should rename their extension .m to .mm.
NOTE | xcodebuild: Headers/Public/WCDB/describable.hpp:24:10: fatal error: 'list' file not found

**Comment by RingoD** [comment]
Maybe you can try to use the command at the wcdb.podspec to lint and push you own podspec.
https://github.com/Tencent/wcdb/blob/master/WCDB.podspec

**Comment by RingoD** [comment]
Try google it.
https://github.com/CocoaPods/CocoaPods/releases/tag/1.2.1

**Comment by lsqswl** [comment]
use --skip-import-validation,
and the problem is solved. 3Q.
