### ISSUE TITLE
【报错】项目中同时添加WCDB 和 WCDB.swift ，编辑报错

### ISSUE THREAD

**Issue by limeidong** [Tencent/wcdb#343]
### The language of WCDB

Objective-C, Swift

### The version of WCDB

 v1.0.6

### The platform of WCDB

 iOS

### The installation of WCDB

 Cocoapods

### What's the issue?

因为我的项目之前是 混编，大部分是swift代码，还有一小部分是 objective-c，我想用WCDB 数据库，就在 Podfile 文件中 添加了 ‘pod 'WCDB.swift' 和 pod 'WCDB' ’，安装什么的都没问题。但是编辑的时候 报错 ‘'sqlite3.h' file not found’，请问这个怎么解决，下边是截图。
*podfile文件*
<img width="508" alt="image" src="https://user-images.githubusercontent.com/18624413/43364670-5eb9281e-9351-11e8-9f09-e0fe22bff172.png">

*安装后 项目*
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/18624413/43364695-d34f28c2-9351-11e8-9460-8be647fe1ecf.png">

*报错*
![Uploading image.png…]()

**备注：如果项目中 只安装 WCDB.swift，项目可以正常运行，没有任何问题，再安装WCDB 之后，编辑就开始报错**

**Comment by RingoD** [comment]
As the issue template said, please describe your question in English.

**Comment by RingoD** [comment]
As for your question, it's not supported for installing both WCDB and WCDB.swift due to sqlite3.
This will be optimized in future releases.

**Comment by limeidong** [comment]
ok, thank you，i understand. Please solve this problem as soon as possible.

**Comment by RingoD** [comment]
Note that it's NOT a bug or an issue. Linking same library multiple time is wrong typically.

**Comment by RingoD** [comment]
@limeidong  Maybe you can try using their dynamic library at the same time with v1.0.7+.

**Comment by limeidong** [comment]
ok. I will have a try. @RingoD

**Comment by aelam** [comment]
sqlite shouldn't be included in SQLCipher directly please check the latest SQLCipher. 
sqlite3 could be a standalone pod. 
WCDBOptimizedSQLCipher forked from an old version of SQLCipher, it should be updated

**Comment by RingoD** [comment]
@aelam  I don't understand what your issue is. If you have any problem other than this issue, you can open your own one.
Currently, this issue is talking about integrate both WCDB and WCDBSwift.

**Comment by RingoD** [comment]
It's safe to link multiple sqlite library in v1.1.0, which will be the next version.
