### ISSUE TITLE
Cannot load underlying module for 'WCDBSwift'

### ISSUE THREAD

**Issue by kkkelicheng** [Tencent/wcdb#345]
### The language of WCDB

Swift

### The version of WCDB

WCDB 1.0.6.2

### The platform of WCDB

  iOS

### The installation of WCDB

 Cocoapods

### What's the issue?

when I `import WCDBSwift`

Cannot load underlying module for 'WCDBSwift'

xcode version is 9.4.1

here is my podfile

```
 platform :ios, '9.0'

target 'WCDBDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for WCDBDemo
  pod 'WCDB.swift'

end
```

**Comment by RingoD** [comment]
Typically, it is an issue of Cocopods. It seems like the spec source is missing. Maybe you should google it.

**Comment by limeidong** [comment]
i had try your method ,but i failed. I clean the Xcode and rebuild. it still show this error.
