### ISSUE TITLE
How to disable logs?

### ISSUE THREAD

**Issue by ysuliu** [Tencent/wcdb#346]
### The language of WCDB
Java

### The version of WCDB
1.0.6

### The platform of WCDB
Android

### The installation of WCDB
Maven

### What's the issue?

A lot of Logs like below in logcat:

`
D/WCDB.SQLiteQueryBuilder: Performing query: SELECT * FROM table_alluser WHERE (uid=?)
D/WCDB.SQLiteQueryBuilder: Performing query: SELECT * FROM table_alluser WHERE (uid=?)
D/WCDB.SQLiteQueryBuilder: Performing query: SELECT * FROM table_alluser WHERE (uid=?)
D/WCDB.SQLiteQueryBuilder: Performing query: SELECT * FROM table_alluser WHERE (uid=?)
`

Any config/options could disable the logs?

**Comment by yuxiaofei93** [comment]
Just comment this line
``` java
Log.d(TAG, "Performing query: " + sql);
```
in file 
`android/wcdb/src/com/tencent/wcdb/database/SQLiteQueryBuilder.java`

**Comment by cnting** [comment]
`com.tencent.wcdb.support.Log.setLogger(Log.LOGGER_NONE);`
