### ISSUE TITLE
c++库

### ISSUE THREAD

**Issue by lefex** [Tencent/wcdb#347]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Objective-C

### The version of WCDB

> e.g. v1.0.5

v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
>  [!] Can't merge user_target_xcconfig for pod targets: ["WCDB", "LayoutEngine"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.

[!] Can't merge user_target_xcconfig for pod targets: ["WCDB", "LayoutEngine"]. Singular build setting CLANG_CXX_LIBRARY has different values.

[!] Can't merge user_target_xcconfig for pod targets: ["WCDB", "LayoutEngine"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.

[!] Can't merge user_target_xcconfig for pod targets: ["WCDB", "LayoutEngine"]. Singular build setting CLANG_CXX_LIBRARY has different values.

> Explain what you want by example or code **in English**.

I am use c++ in my project.

'CLANG_CXX_LANGUAGE_STANDARD' => 'gnu++98',
'CLANG_CXX_LIBRARY' => 'libstdc++',

When I am `pod install`，the error display. Hope you can replay. Thanks.

**Comment by RingoD** [comment]
`libstdc++` is already deprecated long times ago and removed in Xcode 10.
It's time to upgrade your C++ version.
