### ISSUE TITLE
WCTTokenizerNameWCDB is nil 

### ISSUE THREAD

**Issue by Graphicooooone** [Tencent/wcdb#349]
### The language of WCDB

Objective-C

### The version of WCDB

v1.0.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

There are many TFS Class similar to WCTSampleFTSData in my project. I tried to do the same thing with demo, but the project crashed at startup. The information is as follows.
Could it be that WCTTokenizerNameWCDB is nil causing?

![wechatimg512](https://user-images.githubusercontent.com/14357641/43986718-5593a98e-9d48-11e8-8fa5-cc7b47d2f35a.jpeg)

**Comment by Graphicooooone** [comment]
@RingoD thx

**Comment by RingoD** [comment]
As the tutorial said, you should add `-objc_load` or `-all_load` to add the extern variable for static lib.

**Comment by Graphicooooone** [comment]
But I installed WCDB through Cocoapods, and there already exists "-all_load" and "-objc" in the project.

**Comment by Graphicooooone** [comment]
Cocoapods automatically added "-objc" for me and I manually added "-all_load" still have the same problem.

**Comment by Graphicooooone** [comment]
Ok, after receiving the reply of issue, I tried cocoapod again and updated it to v1.0.6, but the same problem still exists. This is the demo I pulled from the project model, and when I run it, I get the same error message.[
[WCDB_FTS.zip](https://github.com/Tencent/wcdb/files/2288952/WCDB_FTS.zip)
](url)

**Comment by Graphicooooone** [comment]
@RingoD

**Comment by Graphicooooone** [comment]
@RingoD thanks

**Comment by Graphicooooone** [comment]
@RingoD 
I am using version v.1.0.7.5 of WCDB and the problem has not been solved

**Comment by RingoD** [comment]
What does your podfile look like? And what's the console output of `pod install`?

**Comment by Graphicooooone** [comment]
...
Installing WCDB (1.0.7.5)
...

Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `Memento.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 19 dependencies from the Podfile and 22 total pods installed.

**Comment by Graphicooooone** [comment]
@RingoD 
This is information about my podfile and the command line after executing 'pod install'
I'm sorry for not replying to you in time
thanks.

**Comment by RingoD** [comment]
Did you add `-ObjC` in your linker flag?

**Comment by RingoD** [comment]
Then I think it should be the construct order problem of static lib. There are three ways to fix.
1. Use raw string instead `WCTTokenizerNameWCDB`. The value of `WCTTokenizerNameWCDB` should be `@"WCDB"`;
2. Add `use_frameworks!` into your podfile to port WCDB to dynamic framework;
3. Wait for the next major version of WCDB with new implementation;

**Comment by Graphicooooone** [comment]
I think I will use the first method to solve the problem for the time being, but there is a problem if there are multiple FTS files in the project, is it allowed to use the same "WCDB" as WCTTokenizerNameWCDB

**Comment by Graphicooooone** [comment]
source code
NSString *const WCTTokenizerNameWCDB = @(WCDB::FTS::WCTModule::Name);

**Comment by RingoD** [comment]
Yes, there will not be any problem.

**Comment by RingoD** [comment]
It's fixed by redesigning the ORM feature to avoid global constructor. It will be released in next version.

**Comment by JHCarpediem** [comment]
> It's fixed by redesigning the ORM feature to avoid global constructor. It will be released in next version.

1.Use raw string instead WCTTokenizerNameWCDB. The value of WCTTokenizerNameWCDB should be @"WCDB";
make bug:
[WCDB][ERROR]Code:2, Type:Abort, Msg:Tokenize name is not registered

**Comment by JHCarpediem** [comment]
> I think I will use the first method to solve the problem for the time being, but there is a problem if there are multiple FTS files in the project, is it allowed to use the same "WCDB" as WCTTokenizerNameWCDB

The first method make that :[WCDB][ERROR]Code:2, Type:Abort, Msg:Tokenize name is not registered
