### ISSUE TITLE
请教个加密的问题

### ISSUE THREAD

**Issue by zhangkehu** [Tencent/wcdb#35]
将密码的byte数组传进去加密了，如果我拿到数据库文件想在其他地方查看的话怎么看（如果工具让输入密码，我怎么根据设置的密码 **生成** 数据库实际使用的密码？），wcdb在底层是否对byte进一步运算生成了新密码？。

**Comment by RingoD** [comment]
SQLCipher会根据key生成真正的密钥。
安装一个命令行的sqlcipher或者用绝大部分软件都能打开，密钥只需要输入你传入的那个。

**Comment by zhangkehu** [comment]
@RingoD 实际传入wcdb的参数是byte数组，但我输入密码应该输入的是字符串？

**Comment by RingoD** [comment]
如果密钥是字符串，然后转成二进制的，则直接输入字符串即可

**Comment by zhangkehu** [comment]
@RingoD 好的，多谢！

**Comment by zhangkehu** [comment]
@RingoD 大佬，我用下载的一个[软件](http://www.sqlabs.com/sqlitemanager4_encryption.php)貌似打不开加密数据库。我是按你说的把密码转成二进制的字符串复制进去的

**Comment by RingoD** [comment]
设置正确的密码 以及 cipher_page_size = 4096
