### ISSUE TITLE
数据库升级问题

### ISSUE THREAD

**Issue by zgf19910122** [Tencent/wcdb#358]
### The language of WCDB
Objective-C

### The version of WCDB
v1.0.6

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?
数据库升级问题：
1.添加新的属性(newProperty)并绑定
2.启动程序时调用createTableAndIndexesOfName:withClass方法
3.进入页面调用[db getObjectsOfClass:GFPerson.class fromTable:NSStringFromClass(self.class) where:GFPerson.newProperty == newProperty]方法后，返回的数据不包含升级之前添加的老数据，只有升级后插入的数据，update和delete方法使用where子句且条件为newProperty时，亦无法操作老数据
4.然而使用getAllObjectsOfClass:fromTable方法可以获取所有数据，表示数据存在，符合预期
请问是升级方式不对还是框架存在bug？

**Comment by RingoD** [comment]
It must be the problem of your condition since it can be extract by `getAllObjectsOfClass:fromTable `.

**Comment by zgf19910122** [comment]
查询条件没问题，因为可以查出升级后插入的数据，只是无法查出升级前的旧数据
经过分析和尝试，我发现了一种解决方案：
将需要添加的新属性使用WCDB_SYNTHESIZE_DEFAULT(className, propertyName, defaultValue)方法绑定数据，可以解决上述问题
可以解释下原理吗？
