### ISSUE TITLE
getOneObjectWhere:orderBy生成的SQL语句,limit应放在order by之后

### ISSUE THREAD

**Issue by pozi119** [Tencent/wcdb#359]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> 使用 - (id )getOneObjectWhere:(const WCTCondition &)condition
                                 orderBy:(const WCDB::OrderList &)order
> 出现如下错误:
>  [WCDB][ERROR]Code:1, Type:SQLite, Tag:0, Op:3, ExtCode:1, Msg:near "ORDER": syntax error, SQL:SELECT xxx,xxx,xxx,xxx FROM xxx WHERE (ixxx=0) LIMIT 1 ORDER BY xxx DESC,xx DESC
>  limit应该放在order by之后

**Comment by RingoD** [comment]
Thanks for your issue. It will be fixed later.
