### ISSUE TITLE
如何不使用 createTableAndIndexesOfName:withClass: 不新建实现<WCTTableCoding>的ORM文件，创建表？？

### ISSUE THREAD

**Issue by QSKOBE24** [Tencent/wcdb#360]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Objective-C
### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

WCDB 中 都是通过createTableAndIndexesOfName:withClass:创建表或索引。但是该接口需要提前创建好
@interface XXXX : NSObject <WCTTableCoding>的文件。如果我希望在代码运行过程中动态创建表，在WCDB中应该如何操作，在FMDB中可以通过直接执行sql语句,那么在WCDB中，是否也可以？

**Comment by RingoD** [comment]
You can use `exec:`.

**Comment by RingoD** [comment]
WINQ let you free from assemble SQL by strings. It brings the builtin anti-injection and avoids spelling mistakes.

Actually, with ORM of WCDB, you don't have to assemble SQL at most of time.
Why not create an ORM object ?

**Comment by QSKOBE24** [comment]
也不是不创建ORM对象，只是很多时候，代码里面需要动态创建表，这种时候并没有提前创建好
@interface XXXX : NSObject 这种文件，因此也就只能通过exec：的方法去创建表了。使用这个接口创建表，感觉比之前执行一条SQL建表 还更复杂了。

**Comment by RingoD** [comment]
I don't understand "dynamic creating table". Even if it's created dynamically, the table structure should be determined in your mind while developing, which can also build an ORM object for them.
Could you please give us an example about your case?

**Comment by cxm19881208** [comment]
> I don't understand "dynamic creating table". Even if it's created dynamically, the table structure should be determined in your mind while developing, which can also build an ORM object for them.
> Could you please give us an example about your case?

app init, maybe create tabes fail, so we want to create table if the table is not exists, before do just like INSERT SELECT ......

**Comment by RingoD** [comment]
@cxm19881208 I think it's a different issue that you should submit your own one.
As for what you asked, why `createTableAndIndexesOfName:withClass:` does not work?

**Comment by cxm19881208** [comment]
> @cxm19881208 I think it's a different issue that you should submit your own one.
> As for what you asked, why doesn't `createTableAndIndexesOfName:withClass:` work?

Of course, could use `createTableAndIndexesOfName:withClass:` before CRUD. but we hope WCDB can ‘Delayed creation of a table’, so the users don`t care creating table brefore CRUD

**Comment by RingoD** [comment]
@cxm19881208 
The concept of table is very important in a relational database. It should not be skipped, comparing with key-value database.
In addition, what `createTableAndIndexesOfName:withClass:` does is not only creating table, but also other indexes, constraints and others that developers should concern about.

**Comment by cxm19881208** [comment]
> @cxm19881208
> The concept of table is very important in a relational database. It should not be skipped, comparing with key-value database.
> In addition, what `createTableAndIndexesOfName:withClass:` does is not only creating table, but also other indexes, constraints and others that developers should concern about.

YES, you are right, I am not thinking about it. indexes, sonstraints........ thx
