### ISSUE TITLE
'sqlcipher/sqlite3.h' file not found 错误

### ISSUE THREAD

**Issue by tuyongjiang** [Tencent/wcdb#369]
最新版的 pod集成  'sqlcipher/sqlite3.h' file not found 错误

**Comment by RingoD** [comment]
Please provide the basic information as the issue template said.

**Comment by RingoD** [comment]
https://github.com/Tencent/wcdb/issues/370

**Comment by Yuzeyang** [comment]
it still not work.

run pod update
`Installing WCDB 1.0.7.4 (was 1.0.6)`

build error:
`sqlcipher/sqlite3.h' file not found`
