### ISSUE TITLE
'sqlcipher/sqlite3.h' file not found 错误

### ISSUE THREAD

**Issue by tuyongjiang** [Tencent/wcdb#370]
### The language of WCDB

Objective-C

### The version of WCDB

> e.g. v1.0.7

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

创建一个新项目,通过Cocoapods集成,编译发生'sqlcipher/sqlite3.h' file not found 错误

**Comment by RingoD** [comment]
Upgrade to v1.0.7.4 and retry.

**Comment by Yuzeyang** [comment]
it still not work.

run pod update
Installing WCDB 1.0.7.4 (was 1.0.6)

build error:
sqlcipher/sqlite3.h' file not found

@RingoD

**Comment by tuyongjiang** [comment]
在 podfile  加上 use_frameworks!

**Comment by tuyongjiang** [comment]
@Yuzeyang
