### ISSUE TITLE
database tag

### ISSUE THREAD

**Issue by bianzhifeng** [Tencent/wcdb#372]
### The language of WCDB

> e.g. Swift

### The version of WCDB

> e.g. v1.0.6.2

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

When I created the database, I specified that the database tag is 1, and then I changed the database tag to 2, then I performed the table creation again under the database is to recreate the table?

**Comment by RingoD** [comment]
No.
