### ISSUE TITLE
statement_delete.hpp 报错

### ISSUE THREAD

**Issue by hrscy** [Tencent/wcdb#373]
### The language of WCDB
> Objective-C
### The version of WCDB
> v1.0.6
### The platform of WCDB
> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?
在文件中 #import <WCDB/WCDB.h> 之后，也把文件 改为了 .mm，但是编译之后报错
C++ requires a type specifier for all declarations

![image](https://user-images.githubusercontent.com/16634163/45035353-5d2de900-b08c-11e8-967f-951924691dfe.png)

**Comment by hrscy** [comment]
这个不是我定义的，我没有修改 wcdb 里的代码，我只是将 .m 文件 改为了 .mm 文件，然后运行报的错。

**Comment by RingoD** [comment]
So why not find out where to define this macro?

**Comment by hrscy** [comment]
![image](https://user-images.githubusercontent.com/16634163/45270563-5a3e5880-b4d1-11e8-8e54-856321b9e555.png)
![image](https://user-images.githubusercontent.com/16634163/45270575-6f1aec00-b4d1-11e8-8582-c494e389b5d2.png)
