### ISSUE TITLE
Swift sample crashes at WCDBTokenize.swift line 165

### ISSUE THREAD

**Issue by LiLejia** [Tencent/wcdb#374]
### The language of WCDB

> Swift

### The version of WCDB

> e.g. v1.0.7

### The platform of WCDB

>  iOS

### The installation of WCDB

> Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
![image](https://user-images.githubusercontent.com/1023819/45215486-247e5180-b2d0-11e8-81f2-b0d339734973.png)

> Swift sample crashes at WCDBTokenize.swift line 165, it's a known [Swift 4.1 framework issue](https://bugs.swift.org/browse/SR-7330).

Easy recurrence:

`var string = "1"
let orthography = NSOrthography(dominantScript: "Latin", languageMap: [ "Latn": ["en"]])
string.enumerateLinguisticTags(in: string.startIndex..<string.endIndex,
                               scheme: NSLinguisticTagScheme.lemma.rawValue,
                               options: NSLinguisticTagger.Options.omitWhitespace,
                               orthography: orthography,
                               invoking: { (tag, _, _, stop) in
                                stop = true
})`

FYI

**Comment by RingoD** [comment]
The referenced issue was posted by me. 
It's mentioned in the release note that ones should use Swift 4.2.
And what do you expect to get?

**Comment by over140** [comment]
Swift 5.0 also has this problem

**Comment by eyuxin** [comment]
This bug still exists today( Swift5.0+ Xcode 14.3.1) , is there a plan to fix it?
