### ISSUE TITLE
createTableAndIndexesOfName.  return NO

### ISSUE THREAD

**Issue by TianBaoLi** [Tencent/wcdb#376]
[WCTStatistics SetGlobalPerformanceTrace:^(WCTTag tag, NSDictionary<NSString *,NSNumber *> *sqls, NSInteger cost) {
//        EBLog(@"Tag: %d", tag);
        [sqls enumerateKeysAndObjectsUsingBlock:^(NSString *sql, NSNumber *count, BOOL *) {
//            EBLog(@"SQL: %@ Count: %d", sql, count.intValue);
        }];
//        EBLog(@"Total cost %ld nanoseconds", (long) cost);
    }];
    
    //error
    [WCTStatistics SetGlobalErrorReport:^(WCTError *error) {
//        EBLog(@"[Error] %@", error);
    }];
    
    NSString *baseDirectory = [self getDatabaseDirectory];
    
//    EBLog(@"Sample-ORM Begin");
    NSArray *clses = @[
        CourseQuestionDB.class,
    ];
    
    for (Class cls in clses) {
        NSString *classString = NSStringFromClass(cls);
        NSString *filename = classString;
        NSString *tableName = classString;
        
        NSString *path = [baseDirectory stringByAppendingPathComponent:filename];
        WCTDatabase *database = [[WCTDatabase alloc] initWithPath:path];
//        [database close:^{
//            [database removeFilesWithError:nil];
//        }];
        
        BOOL ret = [database createTableAndIndexesOfName:tableName withClass:cls];
        assert(ret);----这里停止了

**Comment by TianBaoLi** [comment]
database正常 但是不能打开

**Comment by RingoD** [comment]
What did the console say?

**Comment by TianBaoLi** [comment]
库升级后 createTableAndIndexesOfName 这个函数返回NO，[database canOpen] 也是返回NO，找不到具体原因。

**Comment by RingoD** [comment]
So what did the console say?

**Comment by TianBaoLi** [comment]
createTableAndIndexesOfName  这个正常情况 下是返回NO  还是返回Yes呢 ？ 可能是我对这个库不是很理解。

**Comment by RingoD** [comment]
Maybe you should have a deep reading for the tutorials in the wiki before asking.

**Comment by TianBaoLi** [comment]
谢谢

**Comment by bluesky0109** [comment]
遇到同样问题：
1.0.6版本时 createTableAndIndexesOfName 执行 返回 YES；
代码逻辑未做任何修改 只是wcdb更新到 1.0.7.4  createTableAndIndexesOfName 执行 返回 NO；
报错信息如下：
`[logging] API call with invalid database connection pointer
 [logging] misuse at line 122222 of [95fbac39ba]
[WCDB][ERROR]Code:21, Type:SQLite, Tag:0, Op:4, ExtCode:0, Msg:not an error, SQL:PRAGMA synchronous='NORMAL', Path:/var/mobile/Containers/Data/Application/3E3B4550-0DD5-412A-AEB1-483DEE3F4627/Documents/CommonDB`

**Comment by limeidong** [comment]
我也是和你遇到一样的问题，从1.0.6升级到1.0.7+，运行代码就出现了上述问题[WCDB][ERROR]Code:21, Type:SQLite, Tag:0, Op:4, ExtCode:0, Msg:not an error, SQL:PRAGMA synchronous='NORMAL'，请问你解决了么？

**Comment by limeidong** [comment]
@bluesky0109

**Comment by TianBaoLi** [comment]
没解决，作者不理睬我。我把版本退回1.0.6使用了




| |
13143337451
邮箱：13143337451@163.com
|

Signature is customized by Netease Mail Master

On 09/19/2018 21:57, 李美东 wrote:

@bluesky0109

**Comment by TianBaoLi** [comment]
等其他大佬有方案再升级吧




| |
13143337451
邮箱：13143337451@163.com
|

Signature is customized by Netease Mail Master

On 09/19/2018 22:01, TianBaoLi wrote:
没解决，作者不理睬我。我把版本退回1.0.6使用了




| |
13143337451
邮箱：13143337451@163.com
|

Signature is customized by Netease Mail Master

On 09/19/2018 21:57, 李美东 wrote:

@bluesky0109

**Comment by RingoD** [comment]
@TianBaoLi  Actually, you didn't answer my question by posting the console output.

**Comment by RingoD** [comment]
@limeidong  @bluesky0109  Do not post anything on a closed issue. If you have any question, you can submit your own issue.
