### ISSUE TITLE
Crash in ColumnTypeDecoder

### ISSUE THREAD

**Issue by Pircate** [Tencent/wcdb#379]
### The language of WCDB

> Swift

### The version of WCDB

> v1.0.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
<img width="1071" alt="default" src="https://user-images.githubusercontent.com/15857442/45497563-b8598d00-b7aa-11e8-95d7-de85ad9041fb.png">

> Explain what you want by example or code **in English**.

I just write a KeyedDecodingContainer extension and called superDecoder(forKey key: Key).

**Comment by RingoD** [comment]
Maybe there is some conflict between the `Codable` in WCDB and others. I think we should fix it in the future version.
Could you please give a demo project that can reproduce this issue to us?

**Comment by Pircate** [comment]
[WCDB-Demo.zip](https://github.com/Tencent/wcdb/files/2386337/WCDB-Demo.zip)

**Comment by RingoD** [comment]
Thanks.
