### ISSUE TITLE
order question

### ISSUE THREAD

**Issue by bianzhifeng** [Tencent/wcdb#382]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Swift

### The version of WCDB

> e.g. v1.0.5

 1.0.6.2

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

I want to set the storage order of the table data sorted by time, but the result is not as good as I intended.
//example: 
sendTime: ColumnConstraintBinding(isPrimary: true, orderBy: .descending,
                                                  isNotNull: true, defaultTo: 0),
sendTime is TimeInterval .

When I output the results of the table, Still arranged in the order I saved.

Output Result:
Optional(1536897116.559)
Optional(1536897103.277)
Optional(1536897129.602)

**Comment by RingoD** [comment]
How did you get the results? Show the code.

**Comment by bianzhifeng** [comment]
I also found in the documentation that the sorting parameters are also needed when getting the results. thanks.

**Comment by RingoD** [comment]
Of course it's needed.
