### ISSUE TITLE
product demand

### ISSUE THREAD

**Issue by johanntony** [Tencent/wcdb#383]
### The language of WCDB

> Objective-C 

### The version of WCDB

> - WCDB (1.0.6):
    - WCDB/sqlcipher (= 1.0.6)
  - WCDB/sqlcipher (1.0.6)

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

i found the DB without db version like UserVersion this

**Comment by RingoD** [comment]
You should use `Core interface` to run a `StatementPragma` to get the `user_version`. Check the tutorial in the wiki.
