### ISSUE TITLE
unexpected Mach-O header

### ISSUE THREAD

**Issue by RyukieSama** [Tencent/wcdb#384]
### The language of WCDB
Swift 4.2
Xcode10 GM

### The version of WCDB
v1.0.7

### The platform of WCDB
iOS

### The installation of WCDB
Carthage

### What's the issue?

![image](https://user-images.githubusercontent.com/17486479/45617370-bcd0bf00-baa4-11e8-9b76-172fcc063ac3.png)
![image](https://user-images.githubusercontent.com/17486479/45617382-c2c6a000-baa4-11e8-830b-b9c9f07ff2d5.png)

"Found an unexpected Mach-O header code: 0x72613c21"

 Install frameworks by Carthage.
When I want to get IPA. 
Get that error.

Remove 
`
"$(SRCROOT)/../Carthage/Build/iOS/WCDBSwift.framework",
"$(SRCROOT)/../Carthage/Build/iOS/Static/sqlcipher.framework",
"$(SRCROOT)/../Carthage/Build/iOS/Static/sqliterk.framework",
`
everything is ok. 

In a empty project install by Carthage this error will happen.

**Comment by RingoD** [comment]
I don't think that should be the problem of WCDB. 
Since developers work with code and compiler handles the others, I can't imagine how mach-o header could be corrupted in a project. So this must be the problem of the compiler tool chain.
