### ISSUE TITLE
Dead link in Wiki

### ISSUE THREAD

**Issue by yuxiaofei93** [Tencent/wcdb#386]
### What's the issue?

This is an issue about Wiki.

The page url: https://github.com/Tencent/wcdb/wiki/Android%E6%95%B0%E6%8D%AE%E5%BA%93%E4%BF%AE%E5%A4%8D

In this line, "关于不同修复方法的详细介绍，请参照 《公众号文章》", "《公众号文章》" is a dead link.

**Comment by RingoD** [comment]
@John-He-928
