### ISSUE TITLE
集成wcdb.swift 最新版 启动崩溃，项目暂时只能用1.0.6.2版本

### ISSUE THREAD

**Issue by srn214** [Tencent/wcdb#387]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
Swift

### The version of WCDB

> e.g. v1.0.7.3
v1.0.7.3

### The platform of WCDB

> e.g. iOS, macOS or Android
iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
Cocoapods

### What's the issue?

![image](https://user-images.githubusercontent.com/14295747/45672136-fd3e4480-bb59-11e8-9c1e-d8493e5f4cb4.png)

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
Show your `podfile`.

**Comment by srn214** [comment]
# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

platform :ios, '9.0'

# 去掉由pod引入的第三方库的警告，需要更新命令才生效
inhibit_all_warnings!

def common_Pods
    
    use_frameworks!
    
    # 下载图片
    pod 'Kingfisher'
    
    pod 'IBAnimatable'
    
    # Moya
    pod 'Moya/RxSwift'
    # 响应式框架
    pod 'RxSwift'
    # Tableview 和 CollectionView 的Rx封装
    pod 'RxCocoa'
    
    pod 'Then'
    
    pod 'DefaultsKit'
    
    # JSON 转 Model
    pod 'HandyJSON', '~> 4.2.0-beta1'
    # 布局
    pod 'SnapKit'
    # 颜色框架
    pod 'ChameleonFramework'
    # 键盘处理
    pod 'IQKeyboardManagerSwift'
    
    # 菊花
    pod 'SVProgressHUD'
    
    # 为我们提供 rx_disposeBag
    pod 'NSObject+Rx'
    
    # 加密库
    pod 'CryptoSwift'
    
    #上下拉刷新控件
    pod 'MJRefresh'
    
    #日期处理库
    pod 'SwiftDate'
    pod 'Tiercel'
    
    # 空数据列表占位图
    pod 'DZNEmptyDataSet'
    
    # 右滑返回
    pod 'FDFullscreenPopGesture'
    
    pod 'RxDataSources'
    
    # 移动端数据库
    pod 'WCDB.swift', '1.0.6.2'

    # 异步渲染UI框架
    pod 'YYKit'
    
    #图片选择控件
    pod 'CLImagePickerTool'
    
    pod 'FCUUID'
    
    pod 'JXPhotoBrowser'
    
    pod 'Starscream'
    
    # U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMCShare/UI'
    # 集成微信(精简版0.2M)
    pod 'UMCShare/Social/ReducedWeChat'
    # 集成QQ/QZone/TIM(精简版0.5M)
    pod 'UMCShare/Social/ReducedQQ'
    
    pod 'Charts'
    
    # 阿里云OSS
    pod 'AliyunOSSiOS'
    pod 'AlicloudPush'
    
    pod 'MagicWindowSDKBitcode'
    
    pod 'Zhugeio'

end

target 'JianZhongBang' do
    
    common_Pods

  target 'JianZhongBangTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JianZhongBangUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
      
      # 需要指定编译版本的第三方的名称
      myTargets = ['WCDBOptimizedSQLCipher', 'SQLiteRepairKit']

      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              if target.name == 'Charts'
                  config.build_settings['SWIFT_VERSION'] = '4.2'
                  else
                  config.build_settings['SWIFT_VERSION'] = '4.1'
              end
          end
          if myTargets.include? target.name
              target.build_configurations.each do |config|
                  config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
              end
          end
      end
  end

end

**Comment by RingoD** [comment]
Why would you specific the `WCDBOptimizedSQLCipher` and `'SQLiteRepairKit`?
