### ISSUE TITLE
WCDB.swift doesn't work with Firebase

### ISSUE THREAD

**Issue by wuyuehyang** [Tencent/wcdb#388]
### The language of WCDB

> Swift

### The version of WCDB

> v1.0.7.3 (newest)

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### Environment

> Xcode 10, iPhone Simulator / iPhone 5s with iOS 10.3.3

### What's the issue?

<img width="920" alt="screen shot 2018-09-18 at 15 56 56" src="https://user-images.githubusercontent.com/12228763/45672898-e4cf2980-bb5b-11e8-8e70-fadb767b769e.png">

Firebase and WCDB were installed through Cocoapods. Once database object is created, any pragma statement executed by `Handle.exec(_ statement: Statement)` returns error code 21. I set a symbolic breakpoint as the attachment above, which reveals that the sqlite3_exec is not linked to WCDBOptimizedSQLCipher but libsqlite3.dylib. If Firebase were removed, everything works fine.

Any idea to fix this?

Demo project:
[WCDBFirebase.zip](https://github.com/Tencent/wcdb/files/2391702/WCDBFirebase.zip)

**Comment by RingoD** [comment]
Make WCDBSwift as a separate dynamic framework, but not within Cocoapods.

**Comment by wuyuehyang** [comment]
Sure a pre-compiled framework will solve the linking problem. I've also tried renaming the `sqlite3_exec` to `sqlite3_exec_wcdb` in legacy.c of WCDBOptimizedSQLCipher, which works that around too, but both of them appear to be invasive. I was wondering if `sqlite3_exec` in WCDBOptimizedSQLCipher will be renamed in future release, or just integrate the whole project into WCDB, just like it was before.

**Comment by RingoD** [comment]
Of course NOT. Why should WCDB rename the name of SQLCipher? This is unreasonable.

**Comment by wuyuehyang** [comment]
Well resolving a symbolic conflict like this beyonds my current level, renaming is the only idea I came up with.
At last we turn back to WCDB version 1.0.6.x, since there's no source code changes in releases after. A pre-compiled framework is also unacceptable, swift runtime libs will take more than 20MB of space which is a totally waste.

For any reference: https://github.com/wuyuehyang/wcdb

**Comment by RingoD** [comment]
@wuyuehyang Actually, I met nothing error with your demo project.
Here are the outputs:

Console output:
```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing Firebase (5.7.0)
Installing FirebaseAnalytics (5.1.1)
Installing FirebaseCore (5.1.2)
Installing FirebaseInstanceID (3.2.1)
Installing GoogleAppMeasurement (5.1.1)
Installing GoogleUtilities (5.2.2)
Installing SQLiteRepairKit (1.1.6)
Installing WCDB.swift (1.0.7.3)
Installing WCDBOptimizedSQLCipher (1.1.6)
Installing nanopb (0.3.8)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `WCDBTest.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 10 total pods installed.
```

Xcode Build Output:
[Build WCDBTest_2018-09-19T22-36-53.txt](https://github.com/Tencent/wcdb/files/2397501/Build.WCDBTest_2018-09-19T22-36-53.txt)

**Comment by RingoD** [comment]
The reason why it failed should be some of the frameworks inside Firebase linking system library.
Since WCDBSwift never import or link SQLite explicitly, linker should link the WCDBOptimizedSQLCipher. BUT it not.
I don't if it's a bug of linker or not.
Maybe I will fix it or try to avoid it sooner or later.

**Comment by RingoD** [comment]
Note that Swift runtime libs may not be necessary.

**Comment by wuyuehyang** [comment]
Thanks, It’s glad to hear that you will be working on it.
I don’t think it’s a good idea to get rid of those libs. I will have to recompile WCDB every time swift upgrade its ABI, and there will be no compiler errors reminding me if I don’t.

**Comment by RingoD** [comment]
Upgrade to v1.0.7.5 and try again.

**Comment by wuyuehyang** [comment]
Thank you for your great work, I tested it in the demo project and now it works like a charm.
Anyway it could be perfect if these two warnings could be eliminated 😝
<img width="876" alt="screen shot 2018-09-25 at 11 44 35" src="https://user-images.githubusercontent.com/12228763/45991676-91f3f580-c0b8-11e8-8d25-c83d21413c0e.png">

**Comment by RingoD** [comment]
It did not happen on my machine. I'll check it later.

**Comment by RingoD** [comment]
It's fixed. Run `pod update` for your project to get the latest version. 
Note that `WCDBSwift` should be v1.0.7.5 and both `SQLiteRepairKit` and `WCDBOptimizedSQLCipher` should be v1.2.1.

**Comment by wuyuehyang** [comment]
Thanks, it works perfect for me.

**Comment by weiguangmeng** [comment]
WCDB also have this problem if you enbale generate_multiple_pod_projects in Podfie. could you solve this problem? @RingoD

**Comment by CJaeson** [comment]
I still encounter this problem. Is there any new solution now?  @RingoD
version:
WCDB.swift (2.0.4)
WCDBOptimizedSQLCipher (1.4.2)
