### ISSUE TITLE
update primary key errors

### ISSUE THREAD

**Issue by bianzhifeng** [Tencent/wcdb#389]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Swift

### The version of WCDB

> e.g. v1.0.5

1.0.6.2

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

I want to change the primary key of a table, but the database keeps reporting errors. Is there any way to update the primary key of a table senselessly? And when I change the path of the database to recreate a table with the same name, the way my glob matches a field all fails.

**Comment by RingoD** [comment]
I don't understand what your issue and its background is. 
You should express it more clearly with code, console output, error and others.
