### ISSUE TITLE
项目编译时.hpp里有报错

### ISSUE THREAD

**Issue by lb930430** [Tencent/wcdb#39]
![Uploading WX20170616-170637.png…]()

statement_update.hpp
statement_select.hpp
statement_delete.hpp
三个文件都是同样的错误。

奇怪的是我新建项目测试时是正常的，还有改动了offset这个方法名之后也能编译通过

**Comment by lb930430** [comment]
![wx20170616-170637](https://user-images.githubusercontent.com/16176682/27220160-c682f98e-52b6-11e7-8c85-9a4277b6114a.png)

**Comment by RingoD** [comment]
1. 是否有修改依赖文件的后缀`.m`为`.mm`。
2. 新建项目和你现有项目的`Build Settings`下的`Apple LLVM 8.1 - Language - C++`是否一致？如果不一致，麻烦发一下两边的区别。
3. 麻烦发一下Build过程出错的那条命令。

**Comment by lb930430** [comment]
1.依赖文件的后缀已经改了的。
2.Apple LLVM 8.1 - Language - C++下的设置也检查过，两边一样，如下
![wx20170616-180014](https://user-images.githubusercontent.com/16176682/27222189-eb7e7a36-52bd-11e7-81f2-2c89c42b640e.png)
3.
![wx20170616-180246](https://user-images.githubusercontent.com/16176682/27222217-07681590-52be-11e7-8602-11648715e71b.png)

**Comment by lb930430** [comment]
![wx20170616-180418](https://user-images.githubusercontent.com/16176682/27222281-3e11e904-52be-11e7-95cc-1897cb614306.png)

**Comment by lb930430** [comment]
好像是和Masonry有关...

**Comment by RingoD** [comment]
我怀疑是某个代码定义一个`offset`的宏，导致WCDB的接口被宏替换了。
你可以全局搜索一下，如果还不行，麻烦给一个能够重现问题的project。

**Comment by lb930430** [comment]
确实是被替换了，我查到是Masonry框架里定义过offset(...)。

**Comment by ChenChuanzhen** [comment]
> 确实是被替换了，我查到是Masonry框架里定义过offset(...)。
我现在也遇到这个问题，请问该怎么解决
