### ISSUE TITLE
Failed allocating 899 bytes for text at 1844,6, error=-12

### ISSUE THREAD

**Issue by zichengzhang** [Tencent/wcdb#390]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

java

### The version of WCDB

> e.g. v1.0.5

v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 09-16 15:58:39.569 2466 2466 W WCDB.SQLiteConnection: Failed allocating 899 bytes for text at 1844,6, error=-12
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
@John-He-928
