### ISSUE TITLE
 include static frameworks

### ISSUE THREAD

**Issue by Ycong** [Tencent/wcdb#391]
### The language of WCDB

> Swift

### The version of WCDB

> WCDB.swift v1.0.7.3

### The platform of WCDB

> Xcode10, iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

>  ERROR | [iOS] unknown: Encountered an unknown error (The 'Pods-App' target has transitive dependencies that include static frameworks: (WCDB.swift, WCDBOptimizedSQLCipher, and SQLiteRepairKit)
> 
> Create Private Pods

**Comment by RingoD** [comment]
Post the whole console output.

**Comment by Ycong** [comment]
- ERROR | [iOS] unknown: Encountered an unknown error (The 'Pods-App' target has transitive dependencies that include static frameworks: (WCDB.swift, WCDBOptimizedSQLCipher, and SQLiteRepairKit)
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:87:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in `block in verify_no_static_framework_transitive_dependencies'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:70:in `each'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:70:in `verify_no_static_framework_transitive_dependencies'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:36:in `validate!'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:415:in `validate_targets'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:501:in `block in install_pod'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:501:in `each'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:501:in `install_pod'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:320:in `block in perform_extensive_analysis'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:312:in `each'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:312:in `perform_extensive_analysis'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:87:in `validate'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/command/repo/push.rb:139:in `block in validate_podspec_files'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/command/repo/push.rb:130:in `each'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/command/repo/push.rb:130:in `validate_podspec_files'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/command/repo/push.rb:75:in `run'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Users/yc/.rvm/gems/ruby-2.3.4/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/Users/yc/.rvm/gems/ruby-2.3.4/bin/pod:23:in `load'
/Users/yc/.rvm/gems/ruby-2.3.4/bin/pod:23:in `<main>'
/Users/yc/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
/Users/yc/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
) during validation.

**Comment by RingoD** [comment]
You should define `static_framework` in your podspec. Or wait for our new pod version.
