### ISSUE TITLE
xcode升级到10，wcdb报错

### ISSUE THREAD

**Issue by honbolau** [Tencent/wcdb#392]
### The language of WCDB

swift

### The version of WCDB
1.0.6.2

### The platform of WCDB

 iOS

### The installation of WCDB

Cocoapods

报错内容具体如下：
[WCDB][ERROR] Code:sqlite(14), Type:SQLite, Operation:1,Path:/Users/liuhongbao/Library/Developer/CoreSimulator/Devices/0A39F8E5-09F4-400D-88A3-010FE6CDD117/data/Containers/Data/Application/570592A8-75B0-4A3F-A1C9-83D58BA8B3F5/Documents/hicent.db,Message:unable to open database file

```swift
do {
            
            let database = Database(withPath: dbPath);
            if database.canOpen{
                try database.create(table: "tokenkey", of: TokenKey.self)//  TokenKey 缓存服务端接口的token key
                try database.create(table: "userinfo", of: UserInfoModel.self)// UserInfo
            }
            
            database.close()
        } catch {
            fatalError()
        }
```

**Comment by RingoD** [comment]
Is there any other errors?

**Comment by honbolau** [comment]
```swift
func open() throws {
        let directory = URL(fileURLWithPath: path).deletingLastPathComponent().path
        try File.createDirectoryWithIntermediateDirectories(atPath: directory)
        let rc = sqlite3_open(path, &handle)
        guard rc == SQLITE_OK else {
            throw Error.reportSQLite(tag: tag,
                                     path: path,
                                     operation: .open,
                                     code: rc,
                                     message: String(cString: sqlite3_errmsg(handle))
            )
        }
```


"[WCDB][DEBUG] Code:sqliteGlobal(14), Type:SQLiteGlobal, Message:cannot open file at line 5891 of [bbd85d235f]"
"[WCDB][DEBUG] Code:sqliteGlobal(14), Type:SQLiteGlobal, Message:os_unix.c:5891: (2) open(/Users/liuhongbao/Library/Developer/CoreSimulator/Devices/0A39F8E5-09F4-400D-88A3-010FE6CDD117/data/Containers/Data/Application/8CB75B94-C733-48E3-9FEB-63CF31D3C165/Documents/hicent.db"
[WCDB][ERROR] Code:sqlite(14), Type:SQLite, Message:unable to open database file,Path:/Users/liuhongbao/Library/Developer/CoreSimulator/Devices/0A39F8E5-09F4-400D-88A3-010FE6CDD117/data/Containers/Data/Application/8CB75B94-C733-48E3-9FEB-63CF31D3C165/Documents/hicent.db,Operation:1

**Comment by RingoD** [comment]
I have no idea how it happen. Maybe you should post a demo for us.

**Comment by honbolau** [comment]
```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        #if DEBUG
            QorumLogs.enabled = true //log开关
        #endif
        /// WCDB
        do {
            
            let database = Database(withPath: dbPath);
            if database.canOpen{ ///过完这行就报错了。
                try database.create(table: "tokenkey", of: TokenKey.self)//  TokenKey 缓存服务端接口的token key
                try database.create(table: "userinfo", of: UserInfoModel.self)// UserInfo
            }
            
            database.close()
        } catch {
            fatalError()
        }
}
```

**Comment by honbolau** [comment]
I'm sorting videos, uploading YouTube.

**Comment by honbolau** [comment]
https://www.youtube.com/watch?v=6zI6DPQo6ys

**Comment by RingoD** [comment]
Get the latest version and retry by running `pod update`.
Note that `WCDBSwift` should be **v1.0.7.5** and both `SQLiteRepairKit` and `WCDBOptimizedSQLCipher` should be **v1.2.1**.

**Comment by RingoD** [comment]
No reply.
