### ISSUE TITLE
 createTableAndIndexesOfName return NO v1.0.7.4

### ISSUE THREAD

**Issue by bluesky0109** [Tencent/wcdb#393]
### The language of WCDB

Objective-C

### The version of WCDB

 v1.0.7

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

1.0.6版本时 createTableAndIndexesOfName 执行 返回 YES；
代码逻辑未做任何修改 只是wcdb更新到 1.0.7.4 createTableAndIndexesOfName 执行 返回 NO；
报错信息如下：
createTableAndIndexesOfName return NO
[logging] API call with invalid database connection pointer [logging] misuse at line 122222 of [95fbac39ba] [WCDB][ERROR]Code:21, Type:SQLite, Tag:0, Op:4, ExtCode:0, Msg:not an error, SQL:PRAGMA synchronous='NORMAL', Path:/var/mobile/Containers/Data/Application/3E3B4550-0DD5-412A-AEB1-483DEE3F4627/Documents/CommonDB

**Comment by RingoD** [comment]
Try v1.0.7.5.
Note that if you are linking an additional SQLite lib, you should add `use_frameworks!` into your podfile.
