### ISSUE TITLE
WCDB for Android  没有GreenDao 用着方便，尝试将greenDao 和 WCDB，奈何能力不够，哎

### ISSUE THREAD

**Issue by sjdlfajdlfe** [Tencent/wcdb#394]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
@John-He-928
