### ISSUE TITLE
mm_tokenizer 的 mmtok_open 实现为什么是先 U8_NEXT 然后 U16_APPEND

### ISSUE THREAD

**Issue by qiulang** [Tencent/wcdb#395]
关于 FTS的实现 `mm_tokenizer `的 `mmtok_open` 方法

```
typedef struct mm_cursor_t {
    ...
    UChar *in_buffer;       // whole input text buffer, in UTF-16, 
    char *out_buffer;       // output token buffer, int UTF-8, 
} mm_cursor_t;

static int mmtok_open {
   ...
   U8_NEXT(zInput, i_input, nInput, c);
   ...
   U16_APPEND(cur->in_buffer, i_output, dst_len, c, is_error);
}

```
为什么in_buffer 要UTF-16，不能都用UFT-8来处理呢？ 而且既然要 UTF-16 为什么 `mmtok_open` 找token时候先 `U8_NEXT` 再 `U16_APPEND` ？ 不能用 `U16_NEXT` 和 `U16_APPEND` 吗？

**Comment by qiulang** [comment]
@RingoD 其实我是想把这个分词器移植的pc上，所以不一定是 android标签 😄

**Comment by qiulang** [comment]
又仔细查了sqlite文档， https://www.sqlite.org/c3ref/open.html

> The default encoding will be UTF-8 for databases created using sqlite3_open() or sqlite3_open_v2(). The default encoding for databases created using sqlite3_open16() will be UTF-16 in the native byte order.

很多时候我们都是用（至少我自己是）  sqlite3_open打开，也就是用 UTF-8编码，所以  UChar *in_buffer;   用 UTF-16是基于什么考虑？

**Comment by RingoD** [comment]
@John-He-928
