### ISSUE TITLE
IOS pod 失败

### ISSUE THREAD

**Issue by haotiankeji** [Tencent/wcdb#40]
$ /usr/bin/git clone https://github.com/Tencent/wcdb.git
     /var/folders/j4/zzxbx4sx7071b3p5grljnqlc0000gn/T/d20170616-31076-qljeg5
     --template= --single-branch --depth 1 --branch v1.0.0
     Cloning into '/var/folders/j4/zzxbx4sx7071b3p5grljnqlc0000gn/T/d20170616-31076-qljeg5'...
     Note: checking out 'f97a55c08d6313af8f5e6afb3e83aab523ffad8d'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     
     $ /usr/bin/git submodule update --init --recursive
     Submodule 'openssl' (https://github.com/openssl/openssl.git) registered for path 'openssl'
     Submodule 'sqlcipher' (https://github.com/Tencent/sqlcipher.git) registered for path 'sqlcipher'
     Cloning into '/private/var/folders/j4/zzxbx4sx7071b3p5grljnqlc0000gn/T/d20170616-31076-qljeg5/openssl'...

     error: RPC failed; curl 56 SSLRead() return error -9806
     fatal: The remote end hung up unexpectedly
     fatal: early EOF
     fatal: index-pack failed
     fatal: clone of 'https://github.com/openssl/openssl.git' into submodule path '/private/var/folders/j4/zzxbx4sx7071b3p5grljnqlc0000gn/T/d20170616-31076-qljeg5/openssl' failed
     Failed to clone 'openssl'. Retry scheduled
     Cloning into '/private/var/folders/j4/zzxbx4sx7071b3p5grljnqlc0000gn/T/d20170616-31076-qljeg5/sqlcipher'...
     error: RPC failed; curl 18 transfer closed with outstanding read data remaining
     fatal: The remote end hung up unexpectedly
     fatal: early EOF
     fatal: index-pack failed
     fatal: clone of 'https://github.com/Tencent/sqlcipher.git' into submodule path '/private/var/folders/j4/zzxbx4sx7071b3p5grljnqlc0000gn/T/d20170616-31076-qljeg5/sqlcipher' failed
     Failed to clone 'sqlcipher'. Retry scheduled
     Cloning into '/private/var/folders/j4/zzxbx4sx7071b3p5grljnqlc0000gn/T/d20170616-31076-qljeg5/openssl'...

**Comment by RingoD** [comment]
看日志像是网络或pod的出错。

pod安装其他库会出现同样的问题吗？

**Comment by hzx157** [comment]
我的也会出现这问题，开4G依然不行，其他库没有问题

**Comment by RingoD** [comment]
尝试搜索 RPC failed; curl 56 SSLRead() return error -9806 这个错误，找下解决办法

**Comment by RingoD** [comment]
我没能重现这个问题，麻烦搜索RPC failed; curl 56 SSLRead() return error -9806这个错误尝试解决

**Comment by RingoD** [comment]
或者尝试用carthage或源码进行接入

**Comment by RingoD** [comment]
no reply

**Comment by limeidong** [comment]
RPC failed; curl 56 SSLRead() return error -9806这个错误，好像是什么SSL 配置问题，我也没能解决，最后我把cocoapods 卸载重新安装的；
至于这个问题：“ You are in 'detached HEAD' state. You can look around, make experimental
 changes and commit them, and you can discard any commits you make in this
 state without impacting any branches by performing another checkout.”
应该是你当前不在任何分支，请先选择一个分支去添加。
