### ISSUE TITLE
Question of 'sqlite3CodecAttach()'

### ISSUE THREAD

**Issue by ws00801526** [Tencent/wcdb#401]
### The language of WCDB
> Objective-C
### The version of WCDB
> WCDB:v1.0.7.5 ,SQLiteRepairKit: v1.2.1, WCDBOptimizedSQLCipher: v1.2.1
### The platform of WCDB
> iOS
### The installation of WCDB
> Cocoapods

### What's the issue?
while execute 'createTableAndIndexesOfName:withClass:' after `setClipherKey `,  the method `sqlite3CodecAttach` did not execute correctly，the result of `sqlite3CodecAttach` will be SQLITE_OK.
then the app will crash while executing `void sqlcipher_free(void *ptr, int sz)` 

##### error snapshots
![snip20181008_3](https://user-images.githubusercontent.com/3012567/46603544-eae67380-cb25-11e8-91ee-1e33e0ef7e97.png)
![snip20181008_4](https://user-images.githubusercontent.com/3012567/46603562-fc2f8000-cb25-11e8-99e2-fa08ab9d59fe.png)
![snip20181008_6](https://user-images.githubusercontent.com/3012567/46603979-54b34d00-cb27-11e8-9573-d5b87ba7a749.png)

##### correct snapshots
![snip20181008_7](https://user-images.githubusercontent.com/3012567/46604115-bc699800-cb27-11e8-9786-222228e7d93e.png)

**Comment by RingoD** [comment]
What's the matter of this issue? I did not see any error log or crash stack.

**Comment by ws00801526** [comment]
Here is the crash stack, this crash will happened while using WCDB and AMap together.

[crash-demo](https://github.com/ws00801526/WCDBDemo)

![snip20181009_1](https://user-images.githubusercontent.com/3012567/46641859-7acc0200-cba6-11e8-8685-f83e8a0a4ca8.png)

**Comment by RingoD** [comment]
Since there must be some symbols conflict between WCDB and AMap, you should not use static lib for them.
As a solution, you can simply uncomment `use_framework!` and rerun `pod install`.
