### ISSUE TITLE
WCTError 错误信息中的路径被截断

### ISSUE THREAD

**Issue by xiangwangfeng** [Tencent/wcdb#403]
### The language of WCDB

Objective-C

### The version of WCDB

1.0.7.5

### The platform of WCDB

iOS,

### The installation of WCDB

Cocoapods, Carthage

### What's the issue?

WCTError 输出错误信息会有被截断的情况发生。

![wechatimg615](https://user-images.githubusercontent.com/5561963/46786158-9f6ed800-cd66-11e8-831d-9d0461b1b51e.png)

如图，db 初始化从 wal 文件中恢复 frame 时会有相应的 log，并最终通过
[WCTStatistics SetGlobalErrorReport:^(WCTError *error) {}]; 输出。

从 walIndexRecover 方法中获得的 pWal->zWalName 是完整的，但最终 format 时预设的 buffer 仅有 SQLITE_PRINT_BUF_SIZE * 3，也就是 210，导致文件路径很容易被截断，而得不到完整的出错信息。（iOS 下文件最大路径长度为 1024）

PS  sqlite 的原定义中  SQLITE_PRINT_BUF_SIZE 会根据当前系统/设备堆栈较小来设定，小堆栈系统为 50，大堆栈为 350，所以理论上 350 * 3 > 1024 是超过 iOS 文件最大长度的。

**Comment by RingoD** [comment]
Note that WCDB never change the default value of `SQLITE_PRINT_BUF_SIZE`.
What's the meaning of the **original definition in SQLite**? Where did you find it?

**Comment by RingoD** [comment]
Actually, it's kind of problem. I'll redefine `SQLITE_PRINT_BUF_SIZE` to an acceptable value for Apple platform in the next release.

**Comment by xiangwangfeng** [comment]
赞~~~

**Comment by RingoD** [comment]
Or... why not find out the right value yourself and submit a PR for us? :)

**Comment by RingoD** [comment]
`SQLITE_PRINT_BUF_SIZE=256` is defined is next version.
