### ISSUE TITLE
WCDB保存复杂的多层模型怎么使用?

### ISSUE THREAD

**Issue by xuyulon** [Tencent/wcdb#404]
比如: 现在有个Message类, 里面包含了 另外一个 Person类

Message.h? Message.mm

#import <Foundation/Foundation.h>
#import <WCDB/WCDB.h>

@class Person;
@interface Message : NSObject <WCTTableCoding>
@property (nonatomic, assign) int localID;
@property (nonatomic, copy) NSString *content;
@property (nonatomic, strong) NSDate *createTime;
@property (nonatomic, strong) NSDate *modifiedTime;
@property (nonatomic, assign) int unused;
@property (nonatomic, strong) Person *person;
WCDB_PROPERTY(localID)
WCDB_PROPERTY(content)
WCDB_PROPERTY(createTime)
WCDB_PROPERTY(modifiedTime)
WCDB_PROPERTY(person)
@end

#import "Message.h"

@implementation Message
WCDB_IMPLEMENTATION(Message)
WCDB_SYNTHESIZE(Message, localID)
WCDB_SYNTHESIZE(Message, content)
WCDB_SYNTHESIZE(Message, createTime)
WCDB_SYNTHESIZE(Message, modifiedTime)
WCDB_SYNTHESIZE(Message, person)
WCDB_PRIMARY(Message, localID)
// WCDB_INDEX 定义索引
WCDB_INDEX(Message, "_index", createTime)

@end

Person.h??和 Person.mm

#import <Foundation/Foundation.h>
#import <WCDB/WCDB.h>

@interface Person : NSObject <WCTTableCoding>
@property (nonatomic, assign) int personID;
@property (nonatomic, assign) int age;
@property (nonatomic, copy) NSString *name;
WCDB_PROPERTY(personID)
WCDB_PROPERTY(age)
WCDB_PROPERTY(name)
@end

#import "Person.h"

@implementation Person
WCDB_IMPLEMENTATION(Person)
WCDB_SYNTHESIZE(Person, personID)
WCDB_SYNTHESIZE(Person, age)
WCDB_SYNTHESIZE(Person, name)

WCDB_PRIMARY(Person, personID)
WCDB_INDEX(Person, "_index", name)

@end

在ViewController中的操作, 初始化Message类, 然后写入数据库

Message *message = [[Message alloc] init];
message.localID = 1;
message.content = @"Hello, WCDB!";
message.createTime = [NSDate date];
message.modifiedTime = [NSDate date];

Person *person = [[Person alloc] init];

person.personID = 1;
person.age = 20;
person.name = @"James";
message.person = person;

BOOL inserResult = [database insertObject:message into:@"message"];

最后写入失败, 直接崩溃了
崩在wcdb的这个函数里面
- (NSData *)archivedWCTValue
{
    //Class should conform to either [WCTColumnCoding] or [NSCoding] protocol or it may crash here.
    return [NSKeyedArchiver archivedDataWithRootObject:self];
}

**Comment by RingoD** [comment]
Check the wiki about `WCTColumnCoding`. 
Or didn't you see the comment in the posted content ?
> //Class should conform to either [WCTColumnCoding] or [NSCoding] protocol or it may crash here.
