### ISSUE TITLE
建库就奔溃到这internal func superDecoder(forKey key: Key) throws -> Decoder 

### ISSUE THREAD

**Issue by FANGXIDONG** [Tencent/wcdb#406]
![image](https://user-images.githubusercontent.com/15224533/47090004-909b9000-d254-11e8-899a-fe7338d52f57.png)
建库就出现报错

**Comment by FANGXIDONG** [comment]
这是我的Podfile

platform:ios,'9.3'
inhibit_all_warnings!
use_frameworks!

target 'InestingProject' do

pod 'iCarousel'
pod 'JPFPSStatus'
pod 'CHKLineChartKit'
pod 'SnapKit'
pod 'Moya'
pod 'SwiftyJSON'
pod 'Kingfisher'
pod 'IBAnimatable'
pod 'SwiftTheme'
pod 'RxSwift'
pod 'RxCocoa'
#tencent开源 性能比userdefult高80倍
pod 'MMKV'
#tencent开源数据库
pod 'WCDB.swift'
pod 'MBProgressHUD'
pod 'NVActivityIndicatorView'
pod 'MJRefresh'
pod 'KafkaRefresh'
pod 'SGPagingView'
pod 'FDFullscreenPopGesture'
pod 'IQKeyboardManager' 
pod 'CLImagePickerTool'
pod 'SocketRocket', '~> 0.5.1'
pod 'Then'
pod 'DZNEmptyDataSet'
pod 'YYText'
# UMeng 依赖库
pod 'UMCCommon'
pod 'UMCSecurityPlugins'
# 统计
pod 'UMCAnalytics'
# 推送
pod 'UMCPush'
# 分享
# 分享面板ui
#pod 'UMCShare/UI'
# 集成facebook\twitter\kakao\whatsapp
pod 'UMCShare/Social/Facebook'
pod 'UMCShare/Social/Twitter'
pod 'UMCShare/Social/Kakao'
pod 'UMCShare/Social/WhatsApp'
pod 'UMCShare/Social/WeChat'
# 调试打印 上线前删除
pod 'UMCCommonLog'
pod 'UMCErrorCatch'

end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end

**Comment by RingoD** [comment]
Please post the code for your ORM binding
Note that you'd better to use Swift 4.2.
