### ISSUE TITLE
咨询一下可不可以直接拼写Sql语句啊？聊天消息建表的主键用发送的消息时间作为主键？还是消息id作为主键好些啊？麻烦给些建议谢谢？

### ISSUE THREAD

**Issue by MeterSunlight** [Tencent/wcdb#407]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by MeterSunlight** [comment]
咨询一下可不可以直接拼写Sql语句啊？聊天消息建表的主键用发送的消息时间作为主键？还是消息id作为主键好些啊？麻烦给些建议谢谢？

**Comment by RingoD** [comment]
I don't understand your question. You can check the WINQ tutorial in the wiki.

**Comment by RingoD** [comment]
As for the primary key problem, I think you should solve it by yourself.
