### ISSUE TITLE
How can I remove the database model in a simpler way by PRIMARY

### ISSUE THREAD

**Issue by WSFeng** [Tencent/wcdb#411]
### The language of WCDB
> e.g. Objective-C

### The version of WCDB
> e.g. all version

### The platform of WCDB
> e.g. iOS

### The installation of WCDB
> e.g. Cocoapods

### What's the issue?

>>How can I remove the database model in a much simpler way?<<

just like this: WCTDatabase
-(BOOL)deleteObject:(WCDBModel *)model;

--->just use Model's PRIMARY to remove Object from DBFile
this way like realm style, but more easy...

**Comment by RingoD** [comment]
Use `where` condition to do this. There are differences from relational database and key-value database, which you should consider them.
