### ISSUE TITLE
WCDBSwift error: Ambiguous reference to member 'getObjects(on:fromTable:where:orderBy:limit:offset:)'

### ISSUE THREAD

**Issue by summer9011** [Tencent/wcdb#412]
### The language of WCDB
Swift4.2

### The version of WCDB
1.0.7.5

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?
When I call `getObjects` method, Xcode show the error `Ambiguous reference to member 'getObjects(on:fromTable:where:orderBy:limit:offset:)'`, but I found that the document tell me the right way is `let allObjects: [Sample] = try database.getObjects(fromTable: "sampleTable")`, it still doesn't work.

Here is the code I written.
`
import Foundation
import WCDBSwift

class DBManager: NSObject {
    static let shared = DBManager()
    
    lazy var db: Database = {
        let database = Database.init(withPath: DBPath)
        return database
    }()
    
    override init() {
        super.init()
        try? self.db.create(table: DBLoggedUser.tableName, of: DBLoggedUser.self)
    }
}

extension DBManager {
    func getCurrentLoggedUser() -> DBLoggedUser? {
        do {
            let user = try self.db.getObjects(on: DBLoggedUser.Properties.all, fromTable: DBLoggedUser.tableName, where: DBLoggedUser.Properties.currentLogged == true)
        } catch {
            print("get logged user error: \(error)")
        }
    }
}
`

**Comment by RingoD** [comment]
I can't figure out the problem from the provided info. Maybe you can check the testcase in the repo. There is an exactly same case.

**Comment by summer9011** [comment]
Ooh, my bad!!! 😊, it should define var's type when call `database.getObjects` or any `database.getXXX` methods, thanks.
