### ISSUE TITLE
How can I change the table constraint

### ISSUE THREAD

**Issue by IceCreamWu** [Tencent/wcdb#413]
### The language of WCDB

Objective-C

### The version of WCDB

 v1.0.7.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

If a table is already existent，and it has no table constraint when it is created. In a new version, I want to add a unique constraint on a property, such as username. But I found it is not work and I can insert a object with the same username. How can I do for this?Should I drop the table and recreate it?

**Comment by RingoD** [comment]
SQLite does not support to changed the table constraints for an existed table. All you can do is dropping and re-create it.

**Comment by IceCreamWu** [comment]
OK!Thank you!
