### ISSUE TITLE
Can I create FTS5 table

### ISSUE THREAD

**Issue by hippocwh** [Tencent/wcdb#414]
### The language of WCDB

Objective-C

### The version of WCDB

v1.0.6

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

How can I use FTS5 to create a virtual table

it said no such module: FTS5
`WCDB_VIRTUAL_TABLE_MODULE(BaseData, @"FTS5")`

**Comment by RingoD** [comment]
fts5 is supported in v1.0.7.5. You can upgrade the pod and retry.
