### ISSUE TITLE
How Can I add a tokenizer in FTS5 table

### ISSUE THREAD

**Issue by hippocwh** [Tencent/wcdb#415]
### The language of WCDB

Objective-C

### The version of WCDB

v1.0.7.5

### The platform of WCDB

 iOS

### The installation of WCDB

Cocoapods

### What's the issue?

> When I use WCDB tokenizer to create a virtual table, it said "no such tokenizer: WCDB"
> 
> `WCDB_VIRTUAL_TABLE_MODULE(RCYSearchBaseNameStone, @"FTS5")
WCDB_VIRTUAL_TABLE_TOKENIZE(RCYSearchBaseNameStone, WCTTokenizerNameWCDB)
`

**Comment by RingoD** [comment]
You should use FTS3 for WCDB tokenizer, which is described in the tutorial.

**Comment by hippocwh** [comment]
Are there any other tokenizers support FTS5? Should I write another one?

**Comment by RingoD** [comment]
You should use the SQLite builtin FTS5 tokenizer at current WCDB version. Check the FTS doc in sqlite.org for further information.
