### ISSUE TITLE
a = 5; b = ++a; b = ?这个答案应该是6,怎么进qq群提示错误？

### ISSUE THREAD

**Issue by shatian114** [Tencent/wcdb#416]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
The answer is 6. And there are many developers joining into the group everyday. So maybe you should think about whether it is your own problem.
