### ISSUE TITLE
Create Table Error in FTS5 

### ISSUE THREAD

**Issue by zimo888** [Tencent/wcdb#418]
### The language of WCDB

> e.g. Objective-C

### The version of WCDB

> e.g. v1.0.7.5

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

```
Code:1, Type:SQLiteGlobal, Msg:statement aborts at 29: [CREATE VIRTUAL TABLE IF NOT EXISTS colleague_fts_model USING FTS5(name TEXT,pinyin TEXT,tokenize=WCDB)] unrecognized column option: TEXT
```

I found the sql from "https://www.sqlite.org/fts5.html" ,It hasn't the 'Text' 

```
CREATE VIRTUAL TABLE email USING fts5(sender, title, body);
```

I think this is an error when ORM convert to FTS5.

**Comment by RingoD** [comment]
As the tutorial said, WCDB tokenize only support FTS3.
