### ISSUE TITLE
怎么让model层，不要太多代码入侵下，能使用wcdb

### ISSUE THREAD

**Issue by biancheng347** [Tencent/wcdb#419]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
I don't understand your question. Please describe it more detailed.

**Comment by biancheng347** [comment]
比如 我要用 wcdb的话，我的数据结构 需要继承和实现一些 配置，那天项目不用wcdb，这样数据结构上面有很多当初写的配置实现代码。就太麻烦了，




| |
sir wang
邮箱：biancheng347@163.com
|

Signature is customized by Netease Mail Master

在2018年11月08日 20:00，Ringo_D 写道：

I don't understand your question. Please describe it more detailed.

**Comment by biancheng347** [comment]
比如  你需要 继承 某个协议，这个我是可以接受的，这个我可以能分装下解决，如果还有其他的 硬编码在 数据结构上，就非常麻烦，我也研究过了，wcdb,的确比 比其他的三方数据库框架，性能,线程安全和方便的等优点，但是项目和数据库耦合性太强，不利于项目扩展和维护。

**Comment by RingoD** [comment]
It will not affect the upper layer. I don't understand what you means. Could you please give us an example?

**Comment by biancheng347** [comment]
比如 简单的说，我的项目已经用了wcdb for swift,  项目都已经很多版本了，，突然有一天，我不想用wcdb，我只要修改我的数据库层，其他的地方都不需要改动，就完成数据库的替换。

**Comment by RingoD** [comment]
You should wrap your own model layer, which is a common design in development.

**Comment by biancheng347** [comment]
如果能包装的话，那就不是问题了。。关键是包装不起来....

**Comment by RingoD** [comment]
Why?

**Comment by biancheng347** [comment]
enum CodingKeys: String, CodingTableKey {
        typealias Root = Sample
        static let objectRelationalMapping = TableBinding(CodingKeys.self)
        case identifier = "id"
        case description
        case offset = "db_offset"
    }


这个在模型 怎么包装

**Comment by RingoD** [comment]
I think you misunderstand what MODEL layer is.
You only need to show your business related interfaces to the views and the controllers, which means that the objects with object relational mapping should be hidden through MODEL layer.

**Comment by biancheng347** [comment]
我明白你的意思，，但是如果一旦我不用wcdb，会导致很多无用的代码在 数据结构 上面
