### ISSUE TITLE
是否可以提供android orm 操作

### ISSUE THREAD

**Issue by chenyunecjtu** [Tencent/wcdb#42]

**Comment by John-He-928** [comment]
后续版本有Android ORM计划

**Comment by chenyunecjtu** [comment]
请问：android 的 orm 什么时候能加上呀？

**Comment by John-He-928** [comment]
@chenyunecjtu 估计还有一段时间

**Comment by John-He-928** [comment]
@chenyunecjtu room分支接入了Google的[Room][https://developer.android.com/topic/libraries/architecture/room.html]，可以试用一下，暂时还没正式发布。分支下面的README有接入方法，如有问题欢迎来QQ群交流
