### ISSUE TITLE
Swift 联表查询

### ISSUE THREAD

**Issue by pandaApe** [Tencent/wcdb#421]
### The language of WCDB

Swift

### The version of WCDB

1.0.8

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

I want to contvert

`SELECT f.* FROM TrackerItem as t, Food as f WHERE t.trackedId == f.id  GROUP BY trackedId ORDER BY trackerDate DESC;`

via swift,
How to handle it?

**Comment by RingoD** [comment]
It's already described in the tutorial.

**Comment by pandaApe** [comment]
Got it, thanks.
