### ISSUE TITLE
android room无法使用repairdb

### ISSUE THREAD

**Issue by dongzhixuanyuan** [Tencent/wcdb#423]
如果现有项目使用了Room框架，那么引入WCDB时，无法使用WCDB的repair功能。
RepairKit.MasterInfo.save(SqlliteDatabase, db.getPath() + "-mbak", PASSPHRASE);
但是room的oncreate()或者onUpgrade（）中的回调的是SupportSQLiteDatabase，无法兼容。

**Comment by John-He-928** [comment]
这个我们后面版本兼容一下

**Comment by John-He-928** [comment]
现在的接口可以解决

```java
public void onCreate(SupportSQLiteDatabase db) {
    SQLiteDatabase realDB = ((WCDBDatabase) db).getInnerDatabase();
    // do more stuff......
}
```

**Comment by dongzhixuanyuan** [comment]
好的 谢谢  我这边来尝试适配到项目中
