### ISSUE TITLE
iOS  Failed to verify bitcode in WCDB.framework/WCDB:

### ISSUE THREAD

**Issue by ZRD1112** [Tencent/wcdb#425]
iOS打包失败
Failed to verify bitcode in WCDB.framework/WCDB:
error: Bundle only contains bitcode-marker /var/folders/47/f03sf8ys6175fhg_rfzh6x3w0000gn/T/IDEDistributionOptionThinning.EqR/Payload/APPFormwork.app/Frameworks/WCDB.framework/WCDB (armv7)

**Comment by RingoD** [comment]
Where did you get the framework? Downloaded or builded by yourself via source code?
