### ISSUE TITLE
WCDB.swift pod update error

### ISSUE THREAD

**Issue by stackJolin** [Tencent/wcdb#426]
![image](https://user-images.githubusercontent.com/14361098/48603009-090a8380-e9b0-11e8-9bc3-c6730e43d9ff.png)

**Comment by stackJolin** [comment]
如果我设置了pod 'SQLiteRepairKit', :modular_headers => true
  pod 'WCDBOptimizedSQLCipher', :modular_headers => true，会导致WCDB.swift中的很多方法找不到

**Comment by RingoD** [comment]
You missed `use_frameworks!` inside your podfile, which is mentioned in the tutorial.
