### ISSUE TITLE
关于sqlite的时间处理函数

### ISSUE THREAD

**Issue by cocoawork** [Tencent/wcdb#428]
SQLite的关于时间处理的一些函数在WCDB中应该如何操作?
例如SQL :
SELECT datetime(timestampCloumn, 'unixepoch', 'localtime') FROM table;
通过WCDB应该如何实现呢?
谢谢!

**Comment by RingoD** [comment]
Currently, you can use WINQ interface `WCDB::Expr::Function` to implement this since `datetime` is kind of SQL function.

**Comment by cocoawork** [comment]
好的, 明白了 ,谢谢回复!
