### ISSUE TITLE
数据求和

### ISSUE THREAD

**Issue by lanyannoren** [Tencent/wcdb#431]
### The language of WCDB

> Objective-C

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> select sum(column) from table;

How to implement?

**Comment by cocoawork** [comment]
`WCTSelect *select = [[[[database prepareSelectObjectsOnResults:WCTSampleChainCall.intValue.max() fromTable:tableName] where:WCTSampleChainCall.intValue == 1] groupBy:{WCTSampleChainCall.intValue}] limit:3];
NSArray *objects = select.allObjects;
 if (!objects) {
 NSLog(@"Select objects Error %@", select.error);
}
`
This is copy&paste from the sample of WCDB

**Comment by lanyannoren** [comment]
OK! Thank you!!
