### ISSUE TITLE
WCDB 是否对模糊查询（like）的支持，非全文模糊查询？

### ISSUE THREAD

**Issue by Jonwei** [Tencent/wcdb#435]
### The language of WCDB
 Objective-C

### The version of WCDB
v1.0.7

### The platform of WCDB
 iOS

### The installation of WCDB

Cocoapods

### What's the issue?
是否支持sqlite Like 模糊查询 ？

**Comment by qxuewei** [comment]
支持模糊查询，查询语法： ‘Model.Properties.name.like(）’
