### ISSUE TITLE
About compile

### ISSUE THREAD

**Issue by wdq123550** [Tencent/wcdb#439]
### The language of WCDB
Objective-C

### The version of WCDB

v1.0.5

### The platform of WCDB
iOS

### The installation of WCDB

Cocoapods

### What's the issue?
我是用Cocoapods的方式导入WCDB的，然后发现每次编译都很慢，具体说就是大部分编译的时间都是在编译WCDB的源文件，有什么办法提高编译速度吗？

**Comment by RingoD** [comment]
Since we didn't feel slow, there is not enough information for us to solve.
1. What's the definition of slow? How long did it cost?
2. What's your compiler option? Debug or release? Is there any additional compiler flag?
3. What's the hardware you used?
4. ...

**Comment by RingoD** [comment]
I would like to have two recommended ways for you to debug:
1. Upgrade to newest version - v1.0.7.5 or v1.0.8. The latest is always the best.
2. Learn how to build your app faster in WWDC, such as disabling DSYM... 
2.1 Due to WCDB a shared framework, it has no need to be compiled every time.

**Comment by wdq123550** [comment]
具体说是我pod高德地图的框架，然后发现Xcode好像都不编译它，但是会花好长时间编译WCDB，WCDB怎么弄成像高德地图那样

**Comment by RingoD** [comment]
I think the other pods should be a binary only. 

In Cocoapods, I think there is no way to build once. But Xcode will cache them in derived data after first build.

**Comment by wdq123550** [comment]
我知道了，高德地图是只有几个头文件在外面而已，其他文件都装子一个framework中，所以编译才那么快。WCDB有什么办法装成framework吗？pod下来了之后WCDB是很多Cpp和C文件在WCDB的文件夹里的

**Comment by RingoD** [comment]
Pre-build, and embed as a binary framework.
