### ISSUE TITLE
版本支持问题

### ISSUE THREAD

**Issue by Zhouztashin** [Tencent/wcdb#44]
ios 系统不支持 ios 7吗？后续会否支持？
我看文档没有说明android支持的版本，请问android支持的最低版本是多少？

**Comment by John-He-928** [comment]
**Android 目前支持最低是API 12（Android 3.1），最高支持 Android O。**

支持到 API 10 （2.3.3）乃至 API 7 （2.1）理论上是没有问题的，但对应的平台的 C 标准库支持有些问题，我们对 SQLite 做的一些优化要做一些适配。新版的 NDK 也逐渐去掉对老平台的支持了，最新的 r15 已经想要将 14 以下的去掉。

目前一个情况是 WCDB Android 已经接入的大型 APP，最低支持 API 是 14，所以没有一个可靠的持续测试平台来测试 14 以下的可靠性，14 以下支持也很少使用，因此不想这个小部分掣肘优化进程。

如果确实有老版本支持的需要，可以修改源码实现：

 1. 修改 wcdb 的 `build.gradle`，将 `minSdkVersion` 改低；
 2. 修改 `Application.mk` 的 `TARGET_PLATFORM`；
 3. 运行 `build-depends-android.sh`，用 `--api=` 参数指定目标 API Level，编译对应的 libcrypto.a 依赖项；
 4. 修正编译错误，测试运行。

**Comment by RingoD** [comment]
carthage需要使用动态库，因此最低版本为iOS 8。
虽然代码层面应该可以支持iOS 7，但是不建议继续支持iOS 7，这个版本已经很低了。

如果你有需要，可以自己修改。
修改方法为
1. 将`WCDB.xcodeproj`中WCDB的target中的`Build Settings`->`Mach-O Type`改为`Static Library`
2. 分别将`WCDB.xcodeproj`和`sqlcipher-preprocessed.xcodeproj`中的`iOS Deployment Target`改为iOS 7.0。（如果你在使用Xcode 8以上版本，应该已经不支持直接设置`iOS Deployment Target`为iOS 8以下。具体修改方法建议自行搜索。

**Comment by RingoD** [comment]
@Zhouztashin  WCDB 1.0.1 添加了iOS 7 和 macOS 10.9的支持，请参考 通过静态库安装 或 通过cocoapods安装： https://github.com/Tencent/wcdb/wiki#安装

**Comment by RingoD** [comment]
no reply
