### ISSUE TITLE
isTableExists 语法错误

### ISSUE THREAD

**Issue by aelam** [Tencent/wcdb#441]
### The language of WCDB

>  Swift

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
Yes, it should be `tableExists:`, which is already be fixed in `v1.1.0` branch for ObjC.
Thanks for your issue.
