### ISSUE TITLE
Error installing WCDB

### ISSUE THREAD

**Issue by haipengchen** [Tencent/wcdb#443]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

[!] Error installing WCDB
[!] /usr/bin/git clone https://github.com/Tencent/wcdb.git /var/folders/cw/k7sd_vln2ds8g55vkkmf1wjr0000gn/T/d20181224-903-1tkcg3k --template= --single-branch --depth 1 --branch v1.0.4

Cloning into '/var/folders/cw/k7sd_vln2ds8g55vkkmf1wjr0000gn/T/d20181224-903-1tkcg3k'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

### The version of WCDB

> e.g. v1.0.4

### The platform of WCDB

> e.g. iOS, macO

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by elilien** [comment]
It seems like your network is not stable when pulling data from GitHub.
