### ISSUE TITLE
pod install  ERROR

### ISSUE THREAD

**Issue by haipengchen** [Tencent/wcdb#444]
### The language of WCDB

> e.g. Objective-C

### The version of WCDB

> e.g. v1.0.4

### The platform of WCDB

> e.g. iOS

尝试了多种网络环境pod stall 均失败报错信息如下。其他pod能正常下载
[!] Error installing WCDB
[!] /usr/bin/git clone https://github.com/Tencent/wcdb.git /var/folders/cw/k7sd_vln2ds8g55vkkmf1wjr0000gn/T/d20181224-1022-em1rv --template= --single-branch --depth 1 --branch v1.0.7.5

Cloning into '/var/folders/cw/k7sd_vln2ds8g55vkkmf1wjr0000gn/T/d20181224-1022-em1rv'...
fatal: unable to access 'https://github.com/Tencent/wcdb.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443

**Comment by haipengchen** [comment]
尝试了多种网络环境pod stall 均失败报错信息如下。其他pod能正常下载
[!] Error installing WCDB
[!] /usr/bin/git clone https://github.com/Tencent/wcdb.git /var/folders/cw/k7sd_vln2ds8g55vkkmf1wjr0000gn/T/d20181224-1022-em1rv --template= --single-branch --depth 1 --branch v1.0.7.5

Cloning into '/var/folders/cw/k7sd_vln2ds8g55vkkmf1wjr0000gn/T/d20181224-1022-em1rv'...
fatal: unable to access 'https://github.com/Tencent/wcdb.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443

**Comment by haipengchen** [comment]
尝试N天后，终于在今天早上成功了。

**Comment by RingoD** [comment]
Search SSL_ERROR_SYSCALL and you will find the answer.
