### ISSUE TITLE
Does WCDB.swift support carthage?

### ISSUE THREAD

**Issue by aelam** [Tencent/wcdb#446]
### The language of WCDB

> Swift 

### The version of WCDB

> Any

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
Yes
