### ISSUE TITLE
ClientThread SIGSEGV(SEGV_MAPERR) Crash

### ISSUE THREAD

**Issue by emile2013** [Tencent/wcdb#447]
### The language of WCDB

> Java 

### The version of WCDB

>  v1.0.2

### The platform of WCDB

> Android

### The installation of WCDB

> Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 

1 #00 lr 0001e06b /data/data/**/lib/libwcdb.so (sqlite3_register_mm_cipher+58) [armeabi-v7a]
--
2 java:
3 java.lang.Thread.parkFor$(Thread.java:1220)
4 sun.misc.Unsafe.park(Unsafe.java:299)
5 java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
6 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
7 java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
8 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
9 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
10 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)

### Devices

Crash in 8.1.0 and 6.0.1 and 5.1 ,like 小米 MI 8

**Comment by John-He-928** [comment]
The probable reason is failure to load system ICU library used by the FTS feature. The next release will make FTS feature optional and fix this issue.
