### ISSUE TITLE
WCDB.SQLite: [SQLite ErrCode: 28] file unlinked while open

### ISSUE THREAD

**Issue by zichengzhang** [Tencent/wcdb#448]
### The language of WCDB

Java

### The version of WCDB

v1.0.6.2

### The platform of WCDB

Android

### The installation of WCDB

Maven

### What's the issue?

12-27 15:01:53.834 27687 27708 I pkg: com.b.o.c dogTime: 1545894113834 \ !: 恢复损坏数据库 --> 开始：dbName=shop_data_2
12-27 15:01:53.860 27687 24822 I RetryWithRangeTime: 请求商品全量接口完成
12-27 15:01:53.860 27687 24822 I RecoverSQLiteDatabase: 恢复损坏数据库 --> 完成：shop_data_2, 耗时 26 ms
12-27 15:01:53.861 27830 11852 I MicroService: PosService   content:nullPosService  EventNamerecover_database_complete
12-27 15:01:53.863 27687 24822 I WCDB.SQLiteConnection: Closing connection 0xb834cfe0
12-27 15:01:53.863 27687 24822 W WCDB.SQLite: [SQLite ErrCode: 28] file unlinked while open: /mnt/internal_sd/com.b.o.c/database/shop_data_2
12-27 15:01:53.864 27687 24822 I WCDB.SQLiteConnection: Closing connection 0xb77bea50
12-27 15:01:53.864 27687 24822 W WCDB.SQLite: [SQLite ErrCode: 28] file unlinked while open: /mnt/internal_sd/com.b.o.cB.SQLiteConnectionPool: The connection pool for /mnt/internal_sd/com.b.o.c/database/shop_data_2 has been closed but there are still 1 connections in use.  They will be closed as they are released back to the pool.

这是什么原因导致的呢？我们现在的逻辑是发现数据库损坏之后删掉数据库文件，然后重新创建后, 再操作数据库就导致了上面的异常，下面是代码片段

<img width="493" alt="wx20181227-171719 2x" src="https://user-images.githubusercontent.com/24287835/50474362-a0c1af80-09fb-11e9-8351-03fee1d83b46.png">

**Comment by John-He-928** [comment]
在打开时候发现损坏会自动删除DB文件重建，这个逻辑是继承自 Android SDK 的行为。你可以直接依赖这个行为，或者自定义一个 `DatabaseErrorHandler` 控制这个行为，并在创建DB的时候传进去

**Comment by zichengzhang** [comment]
> 在打开时候发现损坏会自动删除DB文件重建，这个逻辑是继承自 Android SDK 的行为。你执行数据库删除的时候，实际上它已经重建并且重新打开了，你可以不用自己做这个操作。
> 
> 你可以直接依赖这个行为，或者自定义一个 `DatabaseErrorHandler` 控制这个行为，并在创建DB的时候传进去

我们现在是这样操作的，通过DatabaseErrorHandler监听到异常的时候，就去删除数据库并重建，这样也会有问题吗？
<img width="1082" alt="databaseerrorhandler" src="https://user-images.githubusercontent.com/24287835/50535378-38eaa080-0b84-11e9-843d-8185516fd91e.png">
<img width="799" alt="recoversqlitedatabase" src="https://user-images.githubusercontent.com/24287835/50535379-38eaa080-0b84-11e9-97d4-413f1f839212.png">

**Comment by John-He-928** [comment]
调用`DatabaseErrorHandler.onCorruption`的时候，传进来的`db`对象是 **未关闭** 的，删除前要先关闭，建议参考一下 `DefaultDatabaseErrorHandler`。
