### ISSUE TITLE
The file “wcdb.db-shm” couldn’t be opened because there is no such file in swift

### ISSUE THREAD

**Issue by xiaohuochai** [Tencent/wcdb#449]
Code:systemCall(260), Type:SystemCall, Operation:261,Message:The file “wcdb.db-shm” couldn’t be opened because there is no such file.,Path:/var/mobile/Containers/Data/Application/95F956BA-E567-418F-9129-EEBFF95A558F/Documents/wcdb.db-shm  (in swift)

**Comment by RingoD** [comment]
It should be developer's own code that deleted those file.
