### ISSUE TITLE
describable.hpp 文件出错

### ISSUE THREAD

**Issue by mdjwanghong** [Tencent/wcdb#45]
通过cocoapods安装完成后，编译工程，describable.hpp 的#incloude <list>中提示：
‘list’ file not found!出错！

**Comment by mdjwanghong** [comment]
只要 在代码文件头引入头文件#import <WCDB/WCDB.h>，就出现 ‘list’ file not found 错误提示！

**Comment by RingoD** [comment]
#10 

5. 由于WCDB是基于Objective-C++，因此需要将引用WCDB的源文件后缀.m改为.mm。
