### ISSUE TITLE
Apple LLVM -language C++编译项为Default时编译不通过，C++低版本兼容问题

### ISSUE THREAD

**Issue by xiaoliuTX** [Tencent/wcdb#454]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
Objective-C

### The version of WCDB

> e.g. v1.0.5
V1.0.7

### The platform of WCDB

> e.g. iOS, macOS or Android
iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
动态库framwork导入

### What's the issue?
工程代码中已有大量的C++类使用，buid Settings中C++ launguage Dialect 及C++ standard Library均为Complier Default。引用WCDB后编译报下面的错误
Non-type template argument of type 'WCDB::Columtype' is not an integral constant expresion
Xcode版本号为9.0。模板类型是C++11以后的特性会考虑C++低版本的兼容么？
> Post the outputs or screenshots for errors.
> 
![img_4589](https://user-images.githubusercontent.com/17293350/51010123-e0f16800-158d-11e9-8e84-6f65241408f4.JPEG)

> Explain what you want by example or code **in English**.

Nothing

**Comment by RingoD** [comment]
No, we will not consider the compatible for some version of C++/Xcode. 
But your version is too old while Xcode 9 was released in 2016 and C++11 was released in 2011.
