### ISSUE TITLE
Multiple thread select doesn't run faster than single thread?

### ISSUE THREAD

**Issue by SelmerZhang** [Tencent/wcdb#455]
### The language of WCDB

Objective-C 

### The version of WCDB

v1.0.5

### The platform of WCDB

iOS

### The installation of WCDB

Git clone

### What's the issue?

I use single thread to select 1000000 rows, it spends about 2700 ms.
Then I use 2 threads to select 500000 rows respectively, it spends 2600ms.
It seems that multiple threads doesn't read much faster than single thread in WCDB?

Here's the code:

`    NSString *docmentPath = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES)[0];
    NSString *sqlitePath = [docmentPath stringByAppendingPathComponent:@"database.sqlite"];
    
    dispatch_group_t group = dispatch_group_create();
    dispatch_queue_t queue = dispatch_get_global_queue(0, 0);
    
    dispatch_group_async(group, queue, ^{
        WCTDatabase *database = [[WCTDatabase alloc] initWithPath:sqlitePath];
        __block NSArray<Person *> *objects;
        
        BOOL commited = [database runTransaction:^BOOL {
            objects = [database getObjectsOfClass:Person.class fromTable:@"Person" where:Person.name>=0&&Person.name<500000];
            return YES; //return YES to commit transaction and return NO to rollback transaction.
        }];
        NSLog(@"thread 1 finished.");
    });
    
    dispatch_group_async(group, queue, ^{
        WCTDatabase *database = [[WCTDatabase alloc] initWithPath:sqlitePath];
        __block NSArray<Person *> *objects;
        
        BOOL commited = [database runTransaction:^BOOL {
            objects = [database getObjectsOfClass:Person.class fromTable:@"Person" where:Person.name>=500000&&Person.name<1000000];
            return YES; //return YES to commit transaction and return NO to rollback transaction.
        }];
        NSLog(@"thread 2 finished.");
    });`

**Comment by RingoD** [comment]
The dispatch queue in your code is serial.

**Comment by RingoD** [comment]
About multi-threading performance, it's described in the wiki.
The baseline read speed is 1160000 ops/sec while multi-threading read speed is 1830000 ops/sec in iPhone 6s.
You can check the same test at https://github.com/Tencent/wcdb/blob/master/objc/benchmark/benchmark/WCDB/WBMMultithreadReadRead.mm and get your own result.

About your own test, I didn't see the full code and project, so I have no judge.

**Comment by SelmerZhang** [comment]
I got the answer. It's because I run 2 transactions, and that can't be concurrent.
Thank you so much.
