### ISSUE TITLE
Is subclass ORM class possible?

### ISSUE THREAD

**Issue by elilien** [Tencent/wcdb#457]
### The language of WCDB

Swift. 

### The version of WCDB

v1.0.7.5.

### The platform of WCDB

iOS.

### The installation of WCDB

Cocoapods.

### What's the issue?

I have a class 'AORM' is a subclass of TableCodable:

```
class AORM: TableCodable {
    
    let test: String
    
    required init(withTest test: String) {
        self.test = test
    }

    enum CodingKeys: String, CodingTableKey {
        typealias Root = AORM

        case test

        static let objectRelationalMapping = TableBinding(CodingKeys.self)
    }
}
```

Now I want to add a class 'BORM' which is a subclass of 'AORM':

```
class BORM: AORM {

    let foo: String
    
    required init(withTest test: String, foo: String)
    	super.init(withTest: test)
        self.foo = foo
    }
    
    enum CodingKeys: String, CodingTableKey {
        typealias Root = BORM
        
        case foo
        
        static let objectRelationalMapping = TableBinding(CodingKeys.self)
    }
}
```

My question is how to write the BORM's `enum CodingKeys` part and is it possible to do like this?

Thank you.

**Comment by RingoD** [comment]
ORM inheritance is not supported by design.

**Comment by elilien** [comment]
@RingoD Got it, thank you!
