### ISSUE TITLE
If you use both isAutoIncrement and orderBy you will get "AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY"

### ISSUE THREAD

**Issue by damozhang** [Tencent/wcdb#458]
### The language of WCDB

> Swift

### The version of WCDB

> v1.0.7.5

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> Code:sqlite(1), Type:SQLite, Message:**AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY**, Path:/log.db,SQL:
```
CREATE TABLE IF NOT EXISTS log(
id INTEGER PRIMARY KEY DESC AUTOINCREMENT NOT NULL,
bid INTEGER NOT NULL DEFAULT 0, 
category TEXT NOT NULL, 
start_at REAL, 
end_at REAL, 
created_at REAL,
updated_at REAL, 
context BLOB, 
notes TEXT)
```

```
let id: Int
...
id: ColumnConstraintBinding(
    isPrimary: true,
    orderBy: OrderTerm.descending,
    isAutoIncrement: true,
    isNotNull: true
)
```

I got this error message if I use both orderBy and isAutoIncrement in ColumnConstraintBinding.

```
id: ColumnConstraintBinding(
    isPrimary: true,
    isAutoIncrement: true,
    isNotNull: true
)
```

If I remove orderBy it will work .

**Comment by RingoD** [comment]
Yes, it's a constraint from SQLite that primary key should be integer and ascending.
