### ISSUE TITLE
dynamic table name

### ISSUE THREAD

**Issue by seedotlee** [Tencent/wcdb#460]
### The language of WCDB

 Objective-C

### The version of WCDB

v1.0.4

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

How can I implementation like this?

```
NSString *clzName = obj;
Class clz = NSClassFromString(clzName);

 [[database getOneObjectOfClass:clz fromTable:clzName] where:clz.bid == @"xxx"];

```

This property(clzName) is dynamically passed when it is executed.

**Comment by RingoD** [comment]
What's the meaning of 'dynamic'? I don't really understand this.

**Comment by seedotlee** [comment]
Like this function, how can I write the `???` (clz.bid == bid)

```
+ (id<BookItem>)getBookItemWithBid:(NSString *)bid type:(BookItemType)type
{
    NSString *bookItemClz = [self getBookItemClzWith:type];
    Class clz = NSClassFromString(bookItemClz);
    id<bookItem> = [[self.database getOneObjectOfClass:clz fromTable: bookItemClz] where: ??? ];
    return bookItem;
}
```

**Comment by RingoD** [comment]
Then write `clz.bid == @"xxx"`.

**Comment by seedotlee** [comment]
write `clz.bid == @"xxx"` then has a compiler error

```
No member named 'bid' in 'objc_class'
```

**Comment by RingoD** [comment]
Maybe `[clz bid]` will help.
By the way, it's an ObjC language question, but not WCDB.

**Comment by seedotlee** [comment]
That's OK. I thought it was a mapping of WCDB.
Thanks!
