### ISSUE TITLE
Swift命令行应用

### ISSUE THREAD

**Issue by jinaiyuanbaojie** [Tencent/wcdb#461]
请问支持Swift命令行程序么？
coocapods安装后，报错
yld: Library not loaded: @rpath/WCDBSwift.framework/Versions/A/WCDBSwift
  Referenced from: /*****/****
  Reason: image not found

**Comment by RingoD** [comment]
What's the meaning of 'Swift命令行程序'?

Please provide the basic message as the issue template suggested.

**Comment by jinaiyuanbaojie** [comment]
### The language of WCDB

>  Swift



### The version of WCDB

> PODS:
  - SQLiteRepairKit (1.2.1):
    - WCDBOptimizedSQLCipher (~> 1.2.0)
  - WCDB.swift (1.0.7.5):
    - SQLiteRepairKit (~> 1.2.0)
    - WCDBOptimizedSQLCipher (~> 1.2.0)
  - WCDBOptimizedSQLCipher (1.2.1)



### The platform of WCDB

>  macOS: Command Line Tool Program



### The installation of WCDB

>  Cocoapods version 1.6.0.beta.1



### What's the issue?

> After installing the WCDB via cocoapods, the project build successfully. But when running the project, there is a crash shows that:
> yld: Library not loaded: @rpath/WCDBSwift.framework/Versions/A/WCDBSwift
Referenced from: /*****/****
Reason: image not found
> I know this is maybe not a issue form your code. The root cause is that my program can not load the framework at run-time. Can I fixed it by configure Xcode build setting?

**Comment by RingoD** [comment]
I think it should be an issue caused by Cocoapods. The library search path is not filled.

"Can I fixed it by configure Xcode build setting?"
Of course yes.

**Comment by jinaiyuanbaojie** [comment]
So, How to solve it by config build setting? :)

**Comment by RingoD** [comment]
Sorry, we won't talk about non-WCDB issues.

**Comment by jinaiyuanbaojie** [comment]
Thanks, close this issue.
