### ISSUE TITLE
can not build with Swift 5

### ISSUE THREAD

**Issue by miku1958** [Tencent/wcdb#462]
### The language of WCDB

Swift

### The version of WCDB

1.0.7.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?
<img width="379" alt="image" src="https://user-images.githubusercontent.com/24806909/53460819-65824200-3a79-11e9-8a62-3029d4d01e96.png">

**Comment by RingoD** [comment]
It says that:
> As with Swift 4.2, the vast majority of sources that built with the Swift 4.2 compiler should compile with the Swift 5.0 compiler.

But, you know, it's Swift, who always redefine the word 'Compatibility'.

Well, we will work for the compatibility later, before the Release of Swift 5.0.

**Comment by RingoD** [comment]
It's fixed.
