### ISSUE TITLE
将wcdb和model尝试组件化提交podspec报错

### ISSUE THREAD

**Issue by Vickeywei** [Tencent/wcdb#464]
- ERROR | [iOS] xcodebuild:  /Users/vicky/Library/Developer/Xcode/DerivedData/App-dfexbdestovkpbagxzgvdpkbxdjl/Build/Products/Release-iphonesimulator/WCDB/WCDB.framework/Headers/WCDB.h:25:2: error: Since WCDB is an Objective-C++ framework, for those files in your project that includes WCDB, you should rename their extension .m to .mm.

<img width="273" alt="2019-03-01 22 48 51" src="https://user-images.githubusercontent.com/18063693/53645641-43084880-3c74-11e9-952d-1f09896b15a2.png">

**Comment by hatjs880328s** [comment]
请问怎么解决的、 我就俩6个文件.m全部更改为.mm了。

**Comment by peppapedar** [comment]
请问怎么解决的？我也遇到这个问题了，百思不得其解

**Comment by kusalrajapaksha** [comment]
I am facing this problem too..along with there errors
'list' file not found in decribable.hpp
Since WCDB is an Objective-C++ framework, for those files in your project that includes WCDB, you should rename their extension .m to .mm. in WCDB.h
