### ISSUE TITLE
1、当我用 Database.init(withPath:"path") 初始化了一个DB的时候，我能不能用属性去持有所创建的Database 对象？会不会影响多线程的问题呢？

### ISSUE THREAD

**Issue by daveleenew** [Tencent/wcdb#466]
1、当我用 Database.init(withPath:"path") 初始化了一个DB的时候，我能不能用属性去持有所创建的Database 对象？会不会影响多线程的问题呢？

**Comment by RingoD** [comment]
Yes, you can. WCDB will keep the thread safety for operating sql by `Database`.

**Comment by daveleenew** [comment]
thanks.
