### ISSUE TITLE
how to query `Array<Int>` contains ?

### ISSUE THREAD

**Issue by hydyy** [Tencent/wcdb#467]
The language of WCDB
Swift

The version of WCDB
v1.0.6

The platform of WCDB
iOS

The installation of WCDB
Cocoapods

What's the issue?
I have an field：`var tagIds: Array<Int> = []`, when I want to get rows where tagIds contains 10, how can I write the query condition?  

`where ..tags.like("%\(tagId)%")` no result

_Originally posted by @hydyy in https://github.com/Tencent/wcdb/issues/242#issuecomment-470368415_

**Comment by RingoD** [comment]
Sorry, but I don't really understand what you mean.
Could you please provide the basic information and a sample for us.

**Comment by hydyy** [comment]
@RingoD

**Comment by RingoD** [comment]
Since array is binary data type, it's hard to search it from database. 
A BLOB is not designed for searching, but storing. So I think you should re-consider about it when determining the table structure and column types.

**Comment by hydyy** [comment]
change `Array<Int>` to `Array<String>` ?

**Comment by hydyy** [comment]
Ok
I will create a relationship table， thx
