### ISSUE TITLE
更通用的获得 changes

### ISSUE THREAD

**Issue by leonylcatwork** [Tencent/wcdb#468]
### The language of WCDB

Objective-C

### The version of WCDB

v1.0.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

问题：
需要获得 update 之后的 changes，目前能找到的接口只有在 WCTUpdate 才有。（WCTTransaction 也能获取，但是必须在 commit 之后。有时候一系列的 update 需要知道分别都改变了多少行数据）
但是 WCTUpdate 封装无法覆盖所有 SQL 语句，StatementUpdate 可以更灵活，但却无法获得 changes。

比如这个SQL ："UPDATE table set field1=field2 WHERE field3=1"
用 WCTUpdate 貌似无法实现，而 StatementUpdate 则可以。

WCTStatement+Private.h 有私有的 iVar _statementHandle 可以通过 getChanges() 获得，但是私有变量无法在外部调用。尝试写 WCTStatement 的 Category 给 _statementHandle 提供接口，编译出错 
```
Undefined symbols for architecture arm64:
  "_OBJC_IVAR_$_WCTStatement._statementHandle"
```
请问是如何可以更通用的获得 changes？谢谢

**Comment by RingoD** [comment]
Yes, it's my fault that didn't make more interfaces for `changes`. In next version, we will have a better solution for this.
Currently, I think you can use `core function` of SQLite to get it, which is `WCDB::Expr::function("changes", {})` as a alias of `changes()`. You can check this core function at [official page](https://sqlite.org/lang_corefunc.html) of SQLite too.

**Comment by leonylcatwork** [comment]
谢谢
