### ISSUE TITLE
Can I use TableCodable ORM as a variable in another TableCodable ORM?

### ISSUE THREAD

**Issue by elilien** [Tencent/wcdb#469]
### The language of WCDB

Swift 4.2

### The version of WCDB

1.0.7.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

I have a TableCodable ORM named "DemoAORM":

```swift
class DemoAORM: NSObject, TableCodable {
    
    let var1: String
    let var2: String
    let var3: Double

...
}
```

And now I have create "DemoBORM":

```swift
class DemoBORM: NSObject, TableCodable {
    
    let var1: String
    let var2: DemoAORM?

...
}
```

And seems wcdb may crash at: wcdb `type` must conform to ColumnDecodableBase protocol.
When I changed `let var2: DemoAORM?` to `let var2: [DemoAORM]?`, everything work fine.

My question is:
1. Should I use a TableCodable ORM as a variable in another TableCodable ORM?
2. My custom class may have different type of variables(e.g. var1 is String, var2 is Double, etc.), when I follow your guide implement the ColumnCodable protocol with my custom class, Xcode may have errors as below:

```swift
 func archivedValue() -> FundamentalValue {
        guard let data = try? JSONEncoder().encode([
            "var1": var1,
            "var2": var2]) else {
                return FundamentalValue(data)
        }
        return FundamentalValue(nil)
    }
```
Line 2 occurred an error on `encode`: Generic parameter 'T' could not be inferred.

**Comment by RingoD** [comment]
Yes, you can. 
As the hint said, `DemoAORM` should conforms to `ColumnDecodable`(actually conforms to `ColumnCodable` would be better.).

As for your question 2, I think it's simple syntax error issue. The testcase code may inspire you.

**Comment by elilien** [comment]
Thank you very much RingoD. I've changed my code as below:

```
class DemoAORM: ColumnCodable, LiteralValueConvertible, ExpressionCanBeOperated {
    
    var name: String?
    var age: Double
    
    static var columnType: ColumnType {
        return .BLOB
    }
    
    required init?(with value: FundamentalValue) {
        let data = value.dataValue
        guard data.count > 0 else {
            return nil
        }
        guard let dictionary = try? JSONDecoder().decode(DemoAORM.self, from: data) else {
            return nil
        }
        self.name = dictionary.name
        self.age = dictionary.age
    }
    
    init(with name: String?, age: Double) {
        self.name = name
        self.age = age
    }
    
    func archivedValue() -> FundamentalValue {
        let obj = DemoAORM(with: name, age: age)
        guard let data = try? JSONEncoder().encode(obj) else {
            return FundamentalValue(nil)
        }
        return FundamentalValue(data)
    }
}
```
I wrote a custom initializer to init the DemoAORM object for `func archivedValue() -> FundamentalValue` use, and now everything seems work fine. Am I doing it right?

**Comment by RingoD** [comment]
Awesome.

**Comment by elilien** [comment]
Thank you very much again!:stuck_out_tongue_winking_eye:
