### ISSUE TITLE
支持数据库合并吗？

### ISSUE THREAD

**Issue by lihywh** [Tencent/wcdb#47]
类似微信的数据备份和数据导入功能，将两个数据库合成一个。

**Comment by RingoD** [comment]
将一个数据库的查询结果插入到另一个数据，无法实现吗？

**Comment by lihywh** [comment]
可能问得不太好；
repairKit里面的备份和恢复功能不会进行合并操作是吧？
自己查询再导入当然是可行。

**Comment by RingoD** [comment]
恢复也是将旧数据插入到另一个db，因此也是支持合并

**Comment by RingoD** [comment]
no reply
