### ISSUE TITLE
是否版本更新接入代码示例没有更新？

### ISSUE THREAD

**Issue by Will-ZJ** [Tencent/wcdb#471]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
Platform? Language? Which line of code?

**Comment by Will-ZJ** [comment]
Xcode,oc,[transaction getError] ,can not find the api

**Comment by Will-ZJ** [comment]
code from "iOS macOS使用教程"

**Comment by RingoD** [comment]
It's `[transaction error]` now. The doc is updated. Thanks for your issue.
