### ISSUE TITLE
通过事务批量插入无效

### ISSUE THREAD

**Issue by Will-ZJ** [Tencent/wcdb#472]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

   [transaction begin];
    [transaction insertObjects:mArr.copy into:@"new_usr"];
    [transaction commit];
    事务批量使用这种形式貌似没成功，使用block是ok的，why

**Comment by RingoD** [comment]
Please provide the error log or a project that can reproduce your issue.

**Comment by Will-ZJ** [comment]
no error log, no response, as if the method was not implemented.就是随意写的一个小测试，用database 去调用runTransaction: 是可行的，换成上面那种形式没有一点反应

**Comment by RingoD** [comment]
So provide a project that can reproduce your issue.

**Comment by Will-ZJ** [comment]
NSString *docPath=[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) lastObject];
    NSString *dbPath=[docPath stringByAppendingPathComponent:@"test_wc.db"];
    WCTDatabase *dataBase = [[WCTDatabase alloc] initWithPath:dbPath];
    BOOL result = [dataBase createTableAndIndexesOfName:@"Tst_user" withClass:Tst_user.class];
    if (result) {
        NSMutableArray *temp = [NSMutableArray array];
        for (int i = 0; i <10; i ++) {
            Tst_user *usr = [Tst_user new];
            usr.name = [NSString stringWithFormat:@"小明%d",i];
            usr.sex = [NSString stringWithFormat:@"%d",i];
            [temp addObject:usr];
        }
        WCTTransaction *transation = [dataBase getTransaction];
        BOOL result = [transation begin];
        [transation insertObjects:temp.copy into:@"Tst_user"];
        result = [transation commit];
        if (!result) {
            [transation rollback];
            NSLog(@"error:%@",[transation error]);
        }else{
            NSArray *arr = [dataBase getAllObjectsOfClass:Tst_user.class fromTable:@"Tst_user"];
            NSLog(@"arr:%lu",(unsigned long)arr.count);
        }

**Comment by RingoD** [comment]
Provide the whole project please. Or I have no idea about other problems except code.

**Comment by Will-ZJ** [comment]
how to upload the whole project?

**Comment by RingoD** [comment]
Zip, then simply drop and drug it here.

**Comment by Will-ZJ** [comment]
[TestWCDB.zip](https://github.com/Tencent/wcdb/files/2990734/TestWCDB.zip)

**Comment by RingoD** [comment]
It's OK here...

**Comment by Will-ZJ** [comment]
……Really？？It doesn't work for me `，[transation insertObjects:temp.copy into:@"Tst_user"]`This method has no response，and the program does not go down

**Comment by Will-ZJ** [comment]
only `[transation insertObject:temp.firstObject into:@"Tst_user"]`this method works,can not find the efficient batch insertion method , Can you reconfirm the validity of the method mentioned above ?

**Comment by RingoD** [comment]
To do a batch insertion, you may use `insertObjects:into:`.
Note that there is a "s" following the `insertObject`.

**Comment by Will-ZJ** [comment]
I did use the batch insertion ,but it did not work for me, the code like `[transation insertObjects:temp.copy into:@"Tst_user"]`,the Zip code that uploaded also used the batch insertion method and it did not work for me ,you message said it is ok after you test , I really do not know why？is there any problem wiht my code ,I would like to ask you to reconfirm the validity of the zip program that uploaded 4 days ago on your side,Thk you

**Comment by Will-ZJ** [comment]
I test  the insertion methods that  only the single insertion  is works well

**Comment by Will-ZJ** [comment]
the batch insertion method that use the block style also works well,but It can not output exceptions or errors.

**Comment by RingoD** [comment]
While using `insertObjects:into:`, you have no need to run a transaction since it's already within transaction.
All errors will be shown in your console.

**Comment by Will-ZJ** [comment]
Aah,i used the method like ` WCTTransaction *transation = [dataBase getTransaction];
        BOOL result = [transation begin];

        [dataBase insertObjects:temp.copy into:@"Tst_user"];
        result = [transation commit];`
 it also does not work for me ,so I confused  about that how to use the transaction in the framwork

**Comment by RingoD** [comment]
As I said, 
> While using insertObjects:into:, you have no need to run a transaction since it's already within transaction.

**Comment by Will-ZJ** [comment]
No matter which object the calling method is, it is useless.

**Comment by RingoD** [comment]
I don't understand what you mean.

**Comment by Will-ZJ** [comment]
Do you mean that I do not need to write code to invoke transaction,it works inside the method like `[dataBase insertObjects:temp.copy into:@"Tst_user"]`?

**Comment by RingoD** [comment]
> As I said,
> 
> > While using insertObjects:into:, you have no need to run a transaction since it's already within transaction.

Again.

**Comment by Will-ZJ** [comment]
Aah ,I see . the code from  the guid 'iOS macOS使用教程' and the sample of example project both use the transcaction  ，the code like 
`
WCTTransaction *transaction = [database getTransaction];
BOOL result = [transaction begin];
[transaction insertObject:message into:@"message"];
result = [transaction commit];
if (!result) {
    [transaction rollback];
    NSLog(@"%@", [transaction error]);
}
`
come from  the guid 'iOS macOS使用教程'
Thk you for your help!

**Comment by RingoD** [comment]
It's `insertObject:into:` but not `insertObjects:into:`.

**Comment by Will-ZJ** [comment]
may be I got it wrong,thk you again ,I have another question about how to get the exceptions or errors,if I use the method`insertObjects:into:`,then how to get the exceptions or errors but the console of the Xcode ,is there such a way like `transaction error]` ,I means I can get the error from the code not the console

**Comment by RingoD** [comment]
Use `WCTInsert`.
Actually, you have no need to know what the error exactly. Since you are not familiar to SQLite, you may not know what the error means. So what you need is a boolean that indicate the action did or did not run as your expected.

**Comment by Will-ZJ** [comment]
thk you very much !!!

**Comment by Will-ZJ** [comment]
it works well now ,thk you ,but I have another question ,if it exec failure ,do I need to roll back transaction by write code ? or the roll back transaction within the method ,I  do not  need to handle it ?

**Comment by RingoD** [comment]
Within.

**Comment by Will-ZJ** [comment]
Thank you for your patience！！！Excellent ！！！
