### ISSUE TITLE
Android 混淆后，运行错误

### ISSUE THREAD

**Issue by XiangliJiaxing** [Tencent/wcdb#473]
No pending exception expected: java.lang.NoSuchMethodError: no non-static method "Lcom/tencent/wcdb/database/SQLiteConnection;.notifyChange(Ljava/lang/String;Ljava/lang/String;[J[J[J)V"

**Comment by XiangliJiaxing** [comment]
此方法在com_tencent_wcdb_database_SQLiteConnection.cpp 中反射调用；

**Comment by XiangliJiaxing** [comment]
notifyCheckpoint

**Comment by XiangliJiaxing** [comment]
notifyCheckpoint

**Comment by XiangliJiaxing** [comment]
替换原有的混淆规则：
#-keep class com.tencent.wcdb.**.*Exception
-keep class com.tencent.wcdb.**.*Exception {
    public void ***(...);
}
-keep class com.tencent.wcdb.database.SQLiteConnection {
    void notifyCheckpoint(java.lang.String, int);
    void notifyChange(...);
}

**Comment by John-He-928** [comment]
Fixed in master branch
