### ISSUE TITLE
The concurrency of database exceeds the max concurrency with -[WCTStatement step]

### ISSUE THREAD

**Issue by leonylcatwork** [Tencent/wcdb#474]
### The language of WCDB

Objective-C

### The version of WCDB

1.0.7.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

Following code produce error:

[WCDB][WARNING]Code:1, Type:Warning, Msg:The concurrency of database:0 with 64 exceeds the concurrency of hardware:8
[WCDB][ERROR]Code:2, Type:Core, Tag:0, Op:7, Msg:The concurrency of database exceeds the max concurrency ......

```
WCTDatabase *db = [[WCTDatabase alloc] initWithPath:[NSTemporaryDirectory() stringByAppendingPathComponent:@"wcdb"]];
NSInteger count = 100;
while (count--) {
    WCTStatement *stm = [db prepare:StatementSelect().select({ColumnResult(Expr::Function("changes", {}))})];
    int changes = 0;
    while (stm.step) {
        id value = [stm getValueAtIndex:0];
        if ([value respondsToSelector:@selector(intValue)]) {
             changes = [value intValue];
        }
    }
    [stm finalize];
    NSLog(@"changes = %d", changes);
}
```

**Comment by RingoD** [comment]
So what's your question?

**Comment by leonylcatwork** [comment]
It is in the code above. It hits max concurrency allowed and not able to print 100x "changes = 0" as it should. It should not have any concurrency at all since there is no threading in the code.

**Comment by RingoD** [comment]
`@autoreleasepool` may help.

**Comment by leonylcatwork** [comment]
Yes it does. Thanks.
Thought it could be a bit more explicit by saying "ok I am done with that WCTStatement instance" rather than having to wrap every single one of them in @autoreleasepool, in case one does need to use many custom SQLs in a method.

**Comment by RingoD** [comment]
Yes, you are right. So we already redesigned it in sub-branch, which will be released next version.
Thanks for your advice.

**Comment by leonylcatwork** [comment]
Great stuff!
