### ISSUE TITLE
Check if already in transaction?

### ISSUE THREAD

**Issue by leonylcatwork** [Tencent/wcdb#475]
### The language of WCDB

Objective-C

### The version of WCDB

v1.0.7.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

Is there a way to check if code is currently in a transaction? Something like -isInTransaction as below such that -someMethod1 can be called with a transaction without failure:

```
- (BOOL)someMethod1 {
    if (self.db.isInTransaction) {
            // do something ...
    } else {
        return [self.db runTransaction:^BOOL{
            // do something ...
         }
    }
}

- (BOOL)someMethod2 {
    return [self.db runTransaction:^BOOL{
        return [self someMethod1];
     }
}

```

**Comment by RingoD** [comment]
Currently, no by default. We added it next version.
