### ISSUE TITLE
Implicit import of bridging header 'WCDB-Bridging.h' via module 'WCDBSwift' is deprecated and will be removed in a later version of Swift

### ISSUE THREAD

**Issue by onelcat** [Tencent/wcdb#478]
### The language of WCDB

> Swift4.2

### The version of WCDB

> v1.0.8

### The platform of WCDB

> iOS

### The installation of WCDB

> Carthage

### What's the issue?
> Implicit import of bridging header 'WCDB-Bridging.h' via module 'WCDBSwift' is deprecated and will be removed in a later version of Swift

**Comment by RingoD** [comment]
Swift 4.2 is tested. Maybe you can try a new empty project with WCDBSwift to see whether if it's reproducible. Or provide a sample project for us.

**Comment by onelcat** [comment]
Swift 4.2 WCDBSwift new empty projec is OK。It may be a farmwork file conflict
