### ISSUE TITLE
ORM Update 为什么update整个table？

### ISSUE THREAD

**Issue by daveleenew** [Tencent/wcdb#479]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Swift

### The version of WCDB

> e.g. v1.0.5
v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

ios

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

    static func update(_ model: LanguageConfigModel) {
        
        /// 获取数据库操作对象
        guard let database =XXXXX.database else {
            return
        }
        /// 更新
        try? database.update(table: kLanguageConfigTableName, on: [LanguageConfigModel.Properties.currentCompanyCode, LanguageConfigModel.Properties.currentLanguageCode],with: model)
    }

调用: LanguageConfigModel.update(config)

为什么他帮我整个table都更新了？

**Comment by RingoD** [comment]
It's the basic behavior of SQLite. For updating specific column, you may use `where:`, `limit:` or other constraints.
