### ISSUE TITLE
The performance trace about specified database, can't output the latest sqls execute

### ISSUE THREAD

**Issue by LonlyCat** [Tencent/wcdb#480]
### The language of WCDB

> Objective-C

### The version of WCDB

> WCDB 1.0.8

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

#### The performance trace about specified database, can't log the latest sqls and always log the previous sqls.

my setup code:

```
- (void)setup {

    NSString *path = [NSTemporaryDirectory() stringByAppendingPathComponent: @"test.db"];
    _db = [[WCTDatabase alloc] initWithPath: path];

    NSAssert([_db canOpen], @"database can not opened!");

    __weak WCTDatabase *db = _db;
    [_db close:^{
        [db removeFilesWithError: nil];
    }];

    [_db setPerformanceTrace:^(WCTTag tag, NSDictionary<NSString *,NSNumber *> *sqls, NSInteger cost) {
        NSLog(@"Tag: %d", tag);
        [sqls enumerateKeysAndObjectsUsingBlock:^(NSString *sql, NSNumber *count, BOOL *) {
            NSLog(@"SQL: %@ Count: %d", sql, count.intValue);
        }];
        NSLog(@"Total cost %ld nanoseconds", (long) cost);
    }];

    [_db createTableAndIndexesOfName: [Student wcdb_tableName]
                           withClass: Student.class];
    [_db createTableAndIndexesOfName: [School wcdb_tableName]
                           withClass: School.class];
}
```

Outputs about trace:

```
2019-03-25 10:42:53.403528+0800 WCDBTest[5528:37966] SQL: PRAGMA locking_mode Count: 1
2019-03-25 10:42:53.403861+0800 WCDBTest[5528:37966] SQL: PRAGMA synchronous='NORMAL' Count: 1
2019-03-25 10:42:53.404914+0800 WCDBTest[5528:37966] SQL: PRAGMA journal_mode Count: 1
2019-03-25 10:42:53.405163+0800 WCDBTest[5528:37966] SQL: PRAGMA journal_mode='WAL' Count: 1
2019-03-25 10:42:53.405990+0800 WCDBTest[5528:37966] SQL: PRAGMA fullfsync=1 Count: 1
2019-03-25 10:42:53.436539+0800 WCDBTest[5528:37966] SQL: CREATE TABLE IF NOT EXISTS student(localID INTEGER PRIMARY KEY ASC AUTOINCREMENT,age INTEGER,name TEXT UNIQUE,number INTEGER UNIQUE,school_num INTEGER,createTime REAL,modifiedTime REAL) Count: 1
2019-03-25 10:42:53.436635+0800 WCDBTest[5528:37966] SQL: BEGIN IMMEDIATE Count: 1
2019-03-25 10:42:53.436757+0800 WCDBTest[5528:37966] SQL: COMMIT Count: 1
``` 

The latest sqls about 'CREATE TABLE school' has no output.

**Comment by RingoD** [comment]
Could you please provide your sample project here?

**Comment by LonlyCat** [comment]
[WCDBTest.zip](https://github.com/Tencent/wcdb/files/3002469/WCDBTest.zip)

I write some test-case about 'create table', 'insert object' and 'fetch object'. In all case, performance trace never output the latest sqls.

**Comment by RingoD** [comment]
```
    [self.db close:^{
        [db removeFilesWithError: nil];
    }];
```
In `createTestTables`, why would you remove the database you just set?

**Comment by LonlyCat** [comment]
i just want to get a clear database when start the project. It will affect the trace result ?

**Comment by RingoD** [comment]
Then you should clear the database before you setup it.

**Comment by LonlyCat** [comment]
Thanks for remind this, but even I don't execute `[db removeFilesWithError: nil];`. Trace output will also ignore the latest sqls. 

If my problem, could you provide an example which the performance trace can output the latest sqls ? Many thanks for it.

**Comment by RingoD** [comment]
Register everything after the database created and before you call any other interface(e.g.: `canOpen`).

**Comment by RingoD** [comment]
In addition, `createDirectoryAtPath:withIntermediateDirectories:attributes:error:` is not necessary as the tutorial described.
