### ISSUE TITLE
Xcode 10.2 Swift 5 需要更新了

### ISSUE THREAD

**Issue by ziruozimi** [Tencent/wcdb#481]

**Comment by RingoD** [comment]
Try v1.0.8.2 which released just now.

**Comment by alexiscn** [comment]
> Try v1.0.8.2 which released just now.

CocoaPods not Updated yet

**Comment by RingoD** [comment]
@alexiscn  try again

**Comment by alexiscn** [comment]
> @alexiscn try again

Xcode 10.1 can not build with v1.0.8.2 .....

**Comment by RingoD** [comment]
@alexiscn  of course.

**Comment by alexiscn** [comment]
> @alexiscn of course.

I think add following code will much better for developers.

```swift
#if swift(>=5.0) {

}
```

**Comment by RingoD** [comment]
> > @alexiscn of course.
> 
> I think add following code will much better for developers.
> 
> ```swift
> #if swift(>=5.0) {
> 
> }
> ```

It's updated for Swift 4.2 only.

**Comment by RingoD** [comment]
I think it's fixed.
