### ISSUE TITLE
android 查询 中文加数字 崩溃

### ISSUE THREAD

**Issue by FengShao123** [Tencent/wcdb#484]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

java

### The version of WCDB

> e.g. v1.0.5

WCDB  v1.0.0  arr包试过1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
Maven 

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
我使用rawQuery(SELECT * FROM 表 WHERE 表 MATCH '上1') 导致final long result = nativeExecuteForCursorWindow(
                                mConnectionPtr, statement.getPtr(), window.mWindowPtr,
                                startPos, requiredPos, countAllRows);崩溃

同样rawQuery(SELECT * FROM 表 WHERE 表 MATCH '上')没问题

[error_info.txt](https://github.com/Tencent/wcdb/files/3007019/error_info.txt)

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
