### ISSUE TITLE
swift最新版本的CodableType.swift编译报错

### ISSUE THREAD

**Issue by marycctv** [Tencent/wcdb#486]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

swift

### The version of WCDB

> e.g. v1.0.5

1.0.8.2

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

xcode版本为10.1，编译时

extension Array: ColumnCodable where Element: Codable {
    public static var columnType: ColumnType {
        return .BLOB
    }
    public init?(with value: FundamentalValue) {
        guard let decodable = try? JSONDecoder().decode(Array.self, from: value.dataValue) else {
            return nil
        }
        self = decodable
    }
    public func archivedValue() -> FundamentalValue {
        guard let encoded = try? JSONEncoder().encode(self) else {
            return FundamentalValue(nil)
        }
        return FundamentalValue(encoded)
    }
}

extension Dictionary: ColumnCodable where Key: Codable, Value: Codable {
    public static var columnType: ColumnType {
        return .BLOB
    }
    public init?(with value: FundamentalValue) {
        guard let decodable = try? JSONDecoder().decode(Dictionary.self, from: value.dataValue) else {
            return nil
        }
        self = decodable
    }
    public func archivedValue() -> FundamentalValue {
        guard let encoded = try? JSONEncoder().encode(self) else {
            return FundamentalValue(nil)
        }
        return FundamentalValue(encoded)
    }
}

extension Set: ColumnCodable where Element: Codable {
    public static var columnType: ColumnType {
        return .BLOB
    }
    public init?(with value: FundamentalValue) {
        guard let decodable = try? JSONDecoder().decode(Set.self, from: value.dataValue) else {
            return nil
        }
        self = decodable
    }
    public func archivedValue() -> FundamentalValue {
        guard let encoded = try? JSONEncoder().encode(self) else {
            return FundamentalValue(nil)
        }
        return FundamentalValue(encoded)
    }
}

均报类似的错：

Conditional conformance of type 'Array<Element>' to protocol 'ColumnDecodable' does not imply conformance to inherited protocol 'ColumnCodableBase'

**Comment by RingoD** [comment]
Use Xcode 10.2

**Comment by fisland** [comment]
我也是一样问题

**Comment by RingoD** [comment]
@fisland  It's a replied issue. I will close it.
