### ISSUE TITLE
I follow the wiki “Via Static Framework”，but still has error blow,some body help??

### ISSUE THREAD

**Issue by dolway** [Tencent/wcdb#489]
### The language of WCDB

> Objective-C

### The platform of WCDB

> iOS  （Xcoed 10.1）

### The installation of WCDB

> Via Static Framework

### What's the issue?

Undefined symbols for architecture x86_64:
  "_sqlcipher_codec_ctx_get_data", referenced from:
      _sqliterkCryptoDecode in WCDB(sqliterk_crypto.o)
  "_sqlcipher_codec_key_derive", referenced from:
      _sqliterkCryptoDecode in WCDB(sqliterk_crypto.o)
  "_sqlcipher_codec_ctx_set_pagesize", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
  "_sqlcipher_codec_ctx_init", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
  "_sqlcipher_page_cipher", referenced from:
      _sqliterkCryptoDecode in WCDB(sqliterk_crypto.o)
  "_sqlcipher_codec_ctx_get_reservesize", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
  "_sqlcipher_activate", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
  "_sqlcipher_codec_ctx_set_cipher", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
  "_sqlcipher_codec_ctx_set_use_hmac", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
  "_sqlcipher_codec_ctx_set_kdf_iter", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
  "_sqlcipher_deactivate", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
      _sqliterkCryptoFreeCodec in WCDB(sqliterk_crypto.o)
  "_sqlcipher_codec_ctx_get_pagesize", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
      _sqliterkCryptoDecode in WCDB(sqliterk_crypto.o)
  "_sqlcipher_codec_ctx_free", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
      _sqliterkCryptoFreeCodec in WCDB(sqliterk_crypto.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by RingoD** [comment]
How did you install the static framework? What is the procedure?

**Comment by dolway** [comment]
# i just follow the document in readme,like blow。 than i got that error message。
## Via Static Framework:
Getting source code from git repository and update the submodule of sqlcipher.
git clone https://github.com/Tencent/wcdb.git
cd wcdb
git submodule update --init sqlcipher
Drag WCDB.xcodeproj in wcdb/apple/ into your project.
Add WCDB iOS Static to the Target Dependencies section of your Xcode project's Build Phases settings.
Add WCDB.framework， libz.tbd to the Linked Binary and Libraries section of your Xcode project's Build Phases settings. Note that there are two WCDB.framework, you should choose the one from WCDB iOS Static target.
Add -all_load and -ObjC to the Other Linker Flags section of your Xcode project's Build Settings.
Add #import <WCDB/WCDB.h> at the top of your Objective-C++ source files and start your WCDB journey.
Since WCDB is an Objective-C++ framework, for those files in your project that includes WCDB, you should rename their extension .m to .mm.

**Comment by RingoD** [comment]
Could you please provide your project for us?

**Comment by dolway** [comment]
this is a .zip platform file about WCDB Domo。it has a too big size ，so i uploaded to baiduyun.If there is any inconvenience, I can try other ways.
[https://pan.baidu.com/s/1VlpXbW27wZ1YrOiApaYtxw](url)

**Comment by RingoD** [comment]
You can upload your zip here directly.

**Comment by dolway** [comment]
sorry，idon't know how to upload directly. 
the size so big ,when iupload the .zip ,i got this
![image](https://user-images.githubusercontent.com/13316461/55367522-1ae46180-5520-11e9-9e95-e26bc8b815b9.png).
In fact, my project does not have any logic, just integrated WCDB. So I think it makes sense to package the whole project into. zip files (including WCDB and sqlcipher), so that. zip files have more than 100 M.

Is there any other convenient way for you?
Thanks very much !

**Comment by RingoD** [comment]
Actually, integrating via static framework is a tested feature. So the problem would be your own project. So we need your project to debug.

**Comment by RingoD** [comment]
As your error shown, it contains sqlcipher but not sqlite. The problem should be
1. You integrate a sqlite library, which is different from WCDB's.
2. The sqlcipher within WCDB is not integrated.

By the way, it would be better to clone tag `v1.0.7.5` for ObjC version.

**Comment by dolway** [comment]
Thank you very much for your patience. These pictures are the structure and part configuration of my project.

From the project , I think sqlcipher has been integrated, and there is no other library for integration.

If it's convenient, you can click on this link to download my project. [WCDBTest] (https://pan.baidu.com/s/1VlpXbW27wZ1YrOiApaYtxw).

Because I need to compile a project under a cross-platform IDE (kony), limited by the platform, I have to use Xcode to manually integrate wcdb . 

Look forward to your reply。Thank you very much!
I will also try tag v1.0.7.5。

<img width="1423" alt="WX20190402-101650@2x" src="https://user-images.githubusercontent.com/13316461/55371954-964f0e80-5532-11e9-882d-b0d8bf83718b.png">
<img width="1421" alt="WX20190402-101727@2x" src="https://user-images.githubusercontent.com/13316461/55371960-99e29580-5532-11e9-983c-835857b9f284.png">

**Comment by RingoD** [comment]
I think it's different between `Target Dependencies` and `Link Binary With Libraries`.
Try remove `WCDB` target for dynamic framework, then clean and build again.

**Comment by dolway** [comment]
I've tried .
if `Target Dependencies` chooses `WCDB iOS Static`, `Link Binary With Libraries` chooses any `WCDB. framework` that can't be compiled.
 However, 
if `Target Dependencies` chooses `WCDB`, `Link Binary With Libraries`chooses any `WCDB. framework` or not, it can be compiled. (But I haven't tested whether it works.)

**Comment by RingoD** [comment]
Try to remove the `WCDB` target for dynamic framework. Then clean and build again. It would make this issue easy to solve.

**Comment by dolway** [comment]
I do not sure what's your mean   "remove the WCDB target for dynamic framework" .is like the picture ?
<img width="1011" alt="WX20190402-220041@2x" src="https://user-images.githubusercontent.com/13316461/55408572-dba32880-5592-11e9-94ad-44566953c9fe.png">
I removed it, and build successed . But ,I add this code in UIViewController ,then i got a new error 
```Objctive-c
- (void)viewDidLoad {
    [super viewDidLoad];
    //获取沙盒根目录
    NSString *documentsPath = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) lastObject];
    NSString *filePath = [documentsPath stringByAppendingPathComponent:@"messageCenter.sqlite"];
// 创建数据库    
WCTDatabase *database = [[WCTDatabase alloc] initWithPath:filePath];
}
```

 new error
```Objective-c
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_WCTDatabase", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by RingoD** [comment]
I said **target**, in WCDB project.

**Comment by dolway** [comment]
sorry!Thanks your patience again.
I removed `WCDB`target in WCDB project,but it doesn't seem to work.
![image](https://user-images.githubusercontent.com/13316461/55448150-366f6b00-55f9-11e9-9f24-e7e7118f0319.png)

**Comment by RingoD** [comment]
I think you can create a repo on github, so that I can clone your code to debug.

**Comment by dolway** [comment]
[https://github.com/dolway/WCDBTest.git](https://github.com/dolway/WCDBTest.git)   thanks!

**Comment by RingoD** [comment]
Hey, you didn't upload your `WCDB` project.
I do know that it's just clone from here, but I still it to reproduce your issue.

**Comment by dolway** [comment]
It has been uploaded. Thank you.

**Comment by RingoD** [comment]
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/2156166/55723514-d4b96180-5a3b-11e9-895c-e876ff2f1bec.png">

No error.

**Comment by dolway** [comment]
## But I did get a error here.  Is it because the environment is different?
my environment:
![pic](https://i.loli.net/2019/04/08/5cab4fdbe073b.png) 
![pic](https://i.loli.net/2019/04/08/5cab4f179eff5.png)
![pic](https://i.loli.net/2019/04/08/5cab4f1bdad1e.png)

**Comment by RingoD** [comment]
No special environment

**Comment by dolway** [comment]
Anyway, thank you very much. Today, I upgraded Xcode to 10.2, and it worked.
