### ISSUE TITLE
解密WCDB加密数据库失败

### ISSUE THREAD

**Issue by weilixin** [Tencent/wcdb#49]
之前问答的issues:
https://github.com/Tencent/wcdb/issues/36

你好，我尝试解密数据库还是失败，烦请帮忙看一下原因，多谢！

打开wcdb加密数据库代码如下：
                        db = com.tencent.wcdb.database.SQLiteDatabase.openDatabase(originalFile.getAbsolutePath(),
                                (isDecode ? password.getBytes() : null/* 无密 */), cipher, null,
                                SQLiteDatabase.OPEN_READWRITE, new DatabaseErrorHandler() {
                                    @Override
                                    public void onCorruption(com.tencent.wcdb.database.SQLiteDatabase dbObj) {
                                        LogUtil.e(TAG, "CipherDB::startDataBaseMigration2::onCorruption1");
                                    }
                                });

创建临时文件暂存代码：
                          newFile = File.createTempFile(ENCRYPTED_DATABASE_PREFIX, TEMP_ENCRYPTED_DATABASE_PREFIX,
                                    context.getCacheDir());

数据迁移代码：
                            try {
                                // db.rawExecSQL("PRAGMA cipher_default_kdf_iter = 4000;");
                                db.execSQL(String.format("ATTACH DATABASE '%s' AS encrypted KEY '%s';",
                                        newFile.getAbsolutePath(), (isDecode ? ""/* 无密 */ : password)));
                                db.execSQL("SELECT sqlcipher_export('encrypted')");
                                db.execSQL("DETACH DATABASE encrypted;");
                                db.close();
                            } catch (Exception e) {
                                LogUtil.e(TAG, "CipherDB::startDataBaseMigration OMG ...DataMigration has exception. "
                                        + e.getMessage());
                                throw new StopRequestException(DATA_TRANSFER_DATA_MIGRATION_ERROR, e);
                            }

异常日志，如下：

06-19 16:17:22.214 7185-7185/com.wlx.debug W/wlx: main:SqliteCipherLogic [LOGIN_READLY]: CipherDB::onItemClick: common_new
06-19 16:17:22.215 7185-7185/com.wlx.debug D/wlx: main:SqliteCipherLogic [LOGIN_READLY]: CipherDB::startDataBaseMigration starting... databaseName: common_new
06-19 16:17:22.215 7185-7185/com.wlx.debug D/wlx: main:SqliteCipherLogic [LOGIN_READLY]: CipherDB::startDataBaseMigration originalFile path: /data/user/0/com.wlx.debug/databases/common_new

06-19 16:17:22.215 7185-7185/com.wlx.debug I/WCDB.SQLiteConnectionPool: Max connection pool size is 1.
06-19 16:17:22.216 7185-7185/com.wlx.debug I/WCDB: Initialize SQLite connection module 'MMFTS'...
06-19 16:17:22.216 7185-7185/com.wlx.debug I/WCDB.SQLiteConnection: Opened connection 0x9b8f6808 with label '/data/user/0/com.wlx.debug/databases/common_new'
06-19 16:17:22.216 7185-7185/com.wlx.debug I/WCDB.SQLiteConnection: sqlite3_key verification passed.

06-19 16:17:22.254 7185-7185/com.wlx.debug W/WCDB.SQLite: [SQLite ErrCode: 5] statement aborts at 1: [PRAGMA journal_mode=PERSIST] database is locked
06-19 16:17:22.255 7185-7185/com.wlx.debug W/WCDB.SQLiteConnectionPool: Connections: 0 active, 0 idle, 0 available.
06-19 16:17:22.257 7185-7185/com.wlx.debug I/WCDB.SQLiteConnection: executeForString took 1ms - failed, sql="PRAGMA journal_mode=PERSIST", exception="database is locked (code 5, errno 0): "
06-19 16:17:22.257 7185-7185/com.wlx.debug W/WCDB.SQLiteConnection: Could not change the database journal mode of '/data/user/0/com.wlx.debug/databases/common_new' from 'wal' to 'PERSIST' because the database is locked.  This usually means that there are other open connections to the database which prevents the database from enabling or disabling write-ahead logging mode.  Proceeding without changing the journal mode.
06-19 16:17:22.258 7185-7185/com.wlx.debug D/wlx: main:SqliteCipherLogic [LOGIN_READLY]: CipherDB::startDataBaseMigration originalFile version: 65
06-19 16:17:22.266 7185-7185/com.wlx.debug D/wlx: main:SqliteCipherLogic [LOGIN_READLY]: CipherDB::startDataBaseMigration newFile path: /data/user/0/com.wlx.debug/cache/tmp_common

06-19 16:17:23.852 7185-7185/com.wlx.debug I/WCDB.SQLiteConnection: executeForChangedRowCount took 1584ms - failed, sql="SELECT sqlcipher_export('encrypted')", exception="unknown error (code 0, errno -1): Queries can be performed using SQLiteDatabase query or rawQuery methods only.", changedRows=0

06-19 16:17:23.852 7185-7185/com.wlx.debug E/wlx: main:SqliteCipherLogic [LOGIN_READLY]: CipherDB::startDataBaseMigration OMG ...DataMigration has exception. unknown error (code 0, errno -1): Queries can be performed using SQLiteDatabase query or rawQuery methods only.
06-19 16:17:23.852 7185-7185/com.wlx.debug E/wlx: main:SqliteCipherLogic [LOGIN_READLY]: CipherDB::startDataBaseMigration --- > Aborting request for database migration common_new: com.tencent.wcdb.database.SQLiteException: unknown error (code 0, errno -1): Queries can be performed using SQLiteDatabase query or rawQuery methods only.
06-19 16:17:23.853 7185-7185/com.wlx.debug D/wlx: main:SqliteCipherLogic [LOGIN_READLY]: CipherDB::startDataBaseMigration finally --- > 103

**Comment by John-He-928** [comment]
discussed in #36
