### ISSUE TITLE
多线程（主线程和子线程）使用WCDB，子线程操作会有一定概率崩溃。

### ISSUE THREAD

**Issue by MrLittleWhite** [Tencent/wcdb#492]
### The language of WCDB

> Objective-C

### The version of WCDB

> 1.0.7.5

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> 多线程（主线程和子线程）使用WCDB，子线程操作会有一定概率崩溃。如图：
![image](https://user-images.githubusercontent.com/9458702/55550803-c8679880-570b-11e9-9b68-88db340c2a16.png)

![image](https://user-images.githubusercontent.com/9458702/55550814-d0bfd380-570b-11e9-8ed1-72a5cd1e4a59.png)

![image](https://user-images.githubusercontent.com/9458702/55550831-dd442c00-570b-11e9-96b5-d79dfc75e363.png)

![image](https://user-images.githubusercontent.com/9458702/55550840-e46b3a00-570b-11e9-9984-eccf6c5f4578.png)

![image](https://user-images.githubusercontent.com/9458702/55550868-f947cd80-570b-11e9-8dc2-91c2cbf12b8a.png)

![image](https://user-images.githubusercontent.com/9458702/55550880-01a00880-570c-11e9-86c0-d5fd8647dc5c.png)

![image](https://user-images.githubusercontent.com/9458702/55550888-0795e980-570c-11e9-87bb-24270eaa93ad.png)

**Comment by RingoD** [comment]
What about the call stack of main thread?

**Comment by AAAma** [comment]
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/15354033/55699474-9f8e1e80-59fd-11e9-9542-b7dfb1b831ec.png">

<img width="1574" alt="image" src="https://user-images.githubusercontent.com/15354033/55699537-cc423600-59fd-11e9-9676-f16c15e7cf1d.png">

<img width="1608" alt="image" src="https://user-images.githubusercontent.com/15354033/55699620-2e02a000-59fe-11e9-969b-7792e662a128.png">

**Comment by RingoD** [comment]
I didn't see any WCDB operation in the main thread.

**Comment by MrLittleWhite** [comment]
It didn’t mean run wcdb operations in main thread and other threads simultaneously. It had run wcdb operations in main thread,  and also other threads. It had chances get crashed in “other threads” according to our crash logs.

**Comment by RingoD** [comment]
So why did you think this crash is related with main thread operation?

**Comment by RingoD** [comment]
Is it reproducible? Could you give us a project to reproduce it ?

**Comment by MrLittleWhite** [comment]
I don't know if this crash is related with main thread operation. I just try to tell how I use wcdb.Maybe it will not crash if I use it only in main thread. it happens sometimes, so I can not reproduce. I try to figure 
it out.

**Comment by RingoD** [comment]
I am waiting for your results.

**Comment by MrLittleWhite** [comment]
I didn't find a way to reproduce. But I found that we use another WCTDatabase object in the other thread, not same WCTDatabase object in main thread. These two WCTDatabase objects access the same database. May it cause a crash like above?
