### ISSUE TITLE
swift 项目 pod install成功后 编译报错

### ISSUE THREAD

**Issue by MQL9011** [Tencent/wcdb#494]
### The language of WCDB

> Swift 

### The version of WCDB

> 1.0.8.2

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

![image](https://user-images.githubusercontent.com/11871158/55704112-01ef1b00-5a0e-11e9-8b9a-e680e8a6b7f0.png)

**Comment by RingoD** [comment]
Clean the pod cache and your project, then re-install.

**Comment by MQL9011** [comment]
首次pod install 提示 use_modules_header
其实已经不需要 use_modules_header了
但是需要 use_frameworks!
