### ISSUE TITLE
The Crash on iOS associated with 'WCDB::RecyclableHandle'

### ISSUE THREAD

**Issue by caiwb** [Tencent/wcdb#495]
### The language of WCDB

Objective-C

### The version of WCDB

1.0.7.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

The following is crash stack.

Exception Type:  SIGTRAP
Exception Codes: #0 at 0x222f16e3c
Crashed Thread:  9

Thread 9 Crashed:
0   libsystem_c.dylib                   __abort  +184
1   libsystem_c.dylib                   __abort  +0
2   libc++abi.dylib                     __cxa_bad_cast  +0
3   libc++abi.dylib                     default_terminate_handler()  +280
4   libobjc.A.dylib                     _objc_terminate()  +140
5   libc++abi.dylib                     std::__terminate(void (*)())  +16
6   libc++abi.dylib                     std::terminate()  +84
7   MyApp                           std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle> > >::__deallocate_node(std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle>, void*>*>*) recyclable.hpp:71 +3
8   MyApp                           std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle> > >::~__hash_table() __hash_table:1503 +3
9   MyApp                          WCDB::ThreadLocal<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, WCDB::RecyclableHandle> > > >::ThreadLocal()::{lambda(void*)#1}::__invoke(void*) __hash_table:1495 +3
10  libsystem_pthread.dylib             _pthread_tsd_cleanup  +508
11  libsystem_pthread.dylib             _pthread_exit  +80
12  libsystem_pthread.dylib             pthread_workqueue_setdispatchoffset_np  +0
13  libsystem_pthread.dylib             _pthread_wqthread  +368
14  libsystem_pthread.dylib             start_wqthread  +4

This crash was happen randomly, and cannot reproduce. Wanna get some help to find out what's happened?

**Comment by RingoD** [comment]
Please provide the whole crash file.

**Comment by caiwb** [comment]
Incident Identifier: B23B1AC9-2D3F-4526-A893-9C9914D31F0B
CrashReporter Key:   TODO
Hardware Model:      iPhone8,1
Process:         MyApp [848]
Path:            
Identifier:      
Version:         
Code Type:       ARM-64
Parent Process:  ??? [1]

Date/Time:       2019-04-09 12:53:51 +0000
OS Version:      iPhone OS 12.1.2 (16C104)
Report Version:  104

Exception Type:  SIGTRAP
Exception Codes: #0 at 0x222f16e3c
Crashed Thread:  9

Thread 9 Crashed:
0   libsystem_c.dylib                   __abort  +184
1   libsystem_c.dylib                   __abort  +0
2   libc++abi.dylib                     __cxa_bad_cast  +0
3   libc++abi.dylib                     default_terminate_handler()  +280
4   libobjc.A.dylib                     _objc_terminate()  +140
5   libc++abi.dylib                     std::__terminate(void (*)())  +16
6   libc++abi.dylib                     std::terminate()  +84
7   MyApp                           std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle> > >::__deallocate_node(std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle>, void*>*>*) recyclable.hpp:71 +3
8   MyApp                           std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle> > >::~__hash_table() __hash_table:1503 +3
9   MyApp                           WCDB::ThreadLocal<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, WCDB::RecyclableHandle, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, WCDB::RecyclableHandle> > > >::ThreadLocal()::{lambda(void*)#1}::__invoke(void*) __hash_table:1495 +3
10  libsystem_pthread.dylib             _pthread_tsd_cleanup  +508
11  libsystem_pthread.dylib             _pthread_exit  +80
12  libsystem_pthread.dylib             pthread_workqueue_setdispatchoffset_np  +0
13  libsystem_pthread.dylib             _pthread_wqthread  +368
14  libsystem_pthread.dylib             start_wqthread  +4

Thread 0:
0   libsystem_kernel.dylib              mach_msg_trap  +8
1   CoreFoundation                      __CFRunLoopServiceMachPort  +236
2   CoreFoundation                      __CFRunLoopRun  +1396
3   CoreFoundation                      CFRunLoopRunSpecific  +436
4   GraphicsServices                    GSEventRunModal  +100
5   UIKitCore                           UIApplicationMain  +212
6   MyApp                           _main main.m:32 +19
7   libdyld.dylib                       start  +4

Thread 1:
0   libsystem_kernel.dylib              mach_msg_trap  +8
1   CoreFoundation                      __CFRunLoopServiceMachPort  +236
2   CoreFoundation                      __CFRunLoopRun  +1396
3   CoreFoundation                      CFRunLoopRunSpecific  +436
4   Foundation                          -[NSRunLoop(NSRunLoop) runMode:beforeDate:]  +300
5   Foundation                          -[NSRunLoop(NSRunLoop) runUntilDate:]  +148
6   UIKitCore                           -[UIEventFetcher threadMain]  +136
7   Foundation                          __NSThread__start__  +1040
8   libsystem_pthread.dylib             _pthread_body  +128
9   libsystem_pthread.dylib             _pthread_start  +48
10  libsystem_pthread.dylib             thread_start  +4

Thread 2:
0   libsystem_kernel.dylib              mach_msg_trap  +8
1   CoreFoundation                      __CFRunLoopServiceMachPort  +236
2   CoreFoundation                      __CFRunLoopRun  +1396
3   CoreFoundation                      CFRunLoopRunSpecific  +436
4   CFNetwork                           -[__CoreSchedulingSetRunnable runForever]  +212
5   Foundation                          __NSThread__start__  +1040
6   libsystem_pthread.dylib             _pthread_body  +128
7   libsystem_pthread.dylib             _pthread_start  +48
8   libsystem_pthread.dylib             thread_start  +4

Thread 3:
0   libsystem_kernel.dylib              __psynch_cvwait  +8
1   libc++.1.dylib                      std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)  +24
2   JavaScriptCore                      void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&)  +104
3   JavaScriptCore                      bmalloc::Scavenger::threadRunLoop()  +176
4   JavaScriptCore                      bmalloc::Scavenger::Scavenger(std::__1::lock_guard<bmalloc::Mutex>&)  +0
5   JavaScriptCore                      std::__1::__thread_specific_ptr<std::__1::__thread_struct>::set_pointer(std::__1::__thread_struct*)  +0
6   libsystem_pthread.dylib             _pthread_body  +128
7   libsystem_pthread.dylib             _pthread_start  +48
8   libsystem_pthread.dylib             thread_start  +4

Thread 4:
0   libsystem_kernel.dylib              mach_msg_trap  +8
1   CoreFoundation                      __CFRunLoopServiceMachPort  +236
2   CoreFoundation                      __CFRunLoopRun  +1396
3   CoreFoundation                      CFRunLoopRunSpecific  +436
4   WebCore                             RunWebThread(void*)  +592
5   libsystem_pthread.dylib             _pthread_body  +128
6   libsystem_pthread.dylib             _pthread_start  +48
7   libsystem_pthread.dylib             thread_start  +4

Thread 5:
0   libsystem_kernel.dylib              mach_msg_trap  +8
1   CoreFoundation                      __CFRunLoopServiceMachPort  +236
2   CoreFoundation                      __CFRunLoopRun  +1396
3   CoreFoundation                      CFRunLoopRunSpecific  +436
4   Foundation                          -[NSRunLoop(NSRunLoop) runMode:beforeDate:]  +300
5   MyApp                           +[GCDAsyncSocket cfstreamThread] GCDAsyncSocket.m:7601 +19
6   Foundation                          __NSThread__start__  +1040
7   libsystem_pthread.dylib             _pthread_body  +128
8   libsystem_pthread.dylib             _pthread_start  +48
9   libsystem_pthread.dylib             thread_start  +4

Thread 6:
0   libsystem_kernel.dylib              __select  +8
1   libsystem_pthread.dylib             _pthread_body  +128
2   libsystem_pthread.dylib             _pthread_start  +48
3   libsystem_pthread.dylib             thread_start  +4

Thread 7:
0   libsystem_kernel.dylib              mach_msg_trap  +8
1   CoreFoundation                      __CFRunLoopServiceMachPort  +236
2   CoreFoundation                      __CFRunLoopRun  +1396
3   CoreFoundation                      CFRunLoopRunSpecific  +436
4   AVFAudio                            GenericRunLoopThread::Entry(void*)  +164
5   AVFAudio                            CAPThread::Entry(CAPThread*)  +88
6   libsystem_pthread.dylib             _pthread_body  +128
7   libsystem_pthread.dylib             _pthread_start  +48
8   libsystem_pthread.dylib             thread_start  +4

Thread 8:
0   libsystem_kernel.dylib              __workq_kernreturn  +8
1   libsystem_pthread.dylib             start_wqthread  +4

Thread 10:
0   libsystem_kernel.dylib              __workq_kernreturn  +8
1   libsystem_pthread.dylib             start_wqthread  +4

Thread 11:
0   libsystem_kernel.dylib              __workq_kernreturn  +8
1   libsystem_pthread.dylib             start_wqthread  +4

Thread 9 crashed with ARM-64 Thread State:
    pc: 0x0000000222f16e3c     fp: 0x000000016cece940     sp: 0x000000016cece910     x0: 0x0000000000000000 
    x1: 0x0000000000000000     x2: 0x0000000000000000     x3: 0x0000000000000001     x4: 0x0000000000000000 
    x5: 0x0000000000989680     x6: 0x0000000000000074     x7: 0x000000016ceced38     x8: 0x00000000ffffffe7 
    x9: 0x000000025c7ddb10    x10: 0x00000000000003e8    x11: 0x0000000000000004    x12: 0x0000000000000075 
   x13: 0x0000000000000000    x14: 0x0000000000000010    x15: 0x0000000000000002    x16: 0x0000000000000030 
   x17: 0x0000000000000000    x18: 0x0000000000000000    x19: 0x000000016cece928    x20: 0x000000025a6492d8 
   x21: 0x000000016cece9e0    x22: 0x000000016cecf130    x23: 0x000000025c7de000    x24: 0x000000025c7de838 
   x25: 0x0000000000000013    x26: 0x0000000000000000    x27: 0x0000000000000000    x28: 0x0000000000000000 
    lr: 0x0000000222f16e3c   cpsr: 0x0000000040000000 

Here is the whole crash file, thanks.

**Comment by RingoD** [comment]
Can this crash be perceived? It seems that it happens when the app is exiting.

**Comment by caiwb** [comment]
It doesn't seem to happen when the app is exiting.
I found the following reports on the end of command line logs:

...
[SQLITERK_OK] Saved master info with 18 entries.
[SQLITERK_OK] Saved master info with 18 entries.
[SQLITERK_OK] Saved master info with 18 entries.
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument

**Comment by caiwb** [comment]
And it happens more frequently with very few users.

**Comment by RingoD** [comment]
> It doesn't seem to happen when the app is exiting.
> I found the following reports on the end of command line logs:
> 
> ...
> [SQLITERK_OK] Saved master info with 18 entries.
> [SQLITERK_OK] Saved master info with 18 entries.
> [SQLITERK_OK] Saved master info with 18 entries.
> libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument

It doesn't seem to indicate that it's not exiting.

**Comment by RingoD** [comment]
As I see, most of the threads are not executing for meaningful things and thread 9 is exiting. So I come to the conclusion that it's exiting.

**Comment by RingoD** [comment]
Maybe a project that can producible this crash will help.

**Comment by caiwb** [comment]
Thanks for the answer, I'll keep looking at this crash.
