### ISSUE TITLE
[Android] DB version is gone after BackupKit / RecoverKit ?

### ISSUE THREAD

**Issue by JacksonHuangTW1229** [Tencent/wcdb#496]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
Java

### The version of WCDB

> e.g. v1.0.5
local build by self
wcdb-20190125-master

### The platform of WCDB

> e.g. iOS, macOS or Android
Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

AAR

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

I use BackupKit to get a backup db file, the db has a schema version 9 
Then I increase my db schema version to 10. (Add a column to a table)
Then when I want to restore the backup db file, the restore db file seems doesn't have the origin schema version 9 ? It directly use schema version 10 to open it . Cause crash because it can't find the new column in the table.
```

db = SQLiteDatabase.openOrCreateDatabase(
                source,
                getDefaultPassphrase(),
                getDefaultCipherSpec(),
                null,
                getDefaultDatabaseErrorHandler());   ///  source db file, the version is 9
            
backup = new BackupKit(
                db,
                tmpBackupDbFile.getPath(),
                getDefaultPassphrase(),
                0,
                null
            );   /////   get backup db file

int result = backup.run();
backup.release();
backup = null;

```
```
tmpRestoreDb = SQLiteDatabase.openOrCreateDatabase(
                tmpRestoreDbFile,
                getDefaultPassphrase(),
                getDefaultCipherSpec(),
                null,
                getDefaultDatabaseErrorHandler());  /// ->  create a new tmp db file
 
recoverKit = new RecoverKit(
                tmpRestoreDb,
                tmpBackupDbFile.getPath(),
                getDefaultPassphrase()
            );    ///  restore the backup db file to tmp db file

 int result2 = recoverKit.run(true); 

```
After restore, tmpRestoreDb.getVersion() is 0 , not 9
Are there something wrong about how I use the BackupKit / RecoverKit  ??

**Comment by JacksonHuangTW1229** [comment]
Hi, is there any information ?

**Comment by John-He-928** [comment]
User version backup is not currently implemented in Backup/Recover operation right now. You can back it up to another file and reset it after recovery for a workaround.

User version backup will be implemented in the future versions.
