### ISSUE TITLE
怎样灵活实现只更新值改变的列？

### ISSUE THREAD

**Issue by halocq** [Tencent/wcdb#497]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

swift

### The version of WCDB

> e.g. v1.0.5

1.0.8

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Carthage

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

还有个问题，prepareSelect跟getObject有什么区别？

**Comment by RingoD** [comment]
Check the tutorial first.

**Comment by RingoD** [comment]
Actually, I don't understand what the title means. Could you show an example?

**Comment by halocq** [comment]
Like A(a, b, c), sometimes update A.a / A.b, A.c / A.a, A.b, A.c, I should use update(... on: [A.Properties .a] / [A.Properties.b, A.Properties.c] /[ A.Properties.a, A.Properties.b, A.Properties.c]), this will be difficult to use. And ask a low-level question, is there a difference between 'update whole line' and 'update some columns'?

**Comment by RingoD** [comment]
Then, what does the easy way look like to update the columns in your mind?

**Comment by RingoD** [comment]
What do your mean about differences? Performance? I/O? Memory? Or others?

**Comment by halocq** [comment]
> Then, what does the easy way look like to update the columns in your mind?

I don't know, it seems replace whole line is the easy way, so make the question below

> What do your mean about differences? Performance? I/O? Memory? Or others?

Performance and Memory

**Comment by RingoD** [comment]
For the first question, isn't there a `Properties.all` property?

For the second question, you should write/run your own test case. There is a lot of related factors.

**Comment by halocq** [comment]
Got it, thanks~
