### ISSUE TITLE
Android compile error

### ISSUE THREAD

**Issue by nightlight9** [Tencent/wcdb#498]
### The language of WCDB

> Java 

### The version of WCDB

> v1.0.8

### The platform of WCDB

> Android

### The installation of WCDB

> Maven

### What's the issue?

When I compile my project, I got a error.

Here is the error message:

ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1

**Comment by John-He-928** [comment]
Please post your gradle build scripts
