### ISSUE TITLE
Feature: WCDB for Swift

### ISSUE THREAD

**Issue by Anomymouse** [Tencent/wcdb#5]

**Comment by RingoD** [comment]
有考虑。
WCDB架构上，只有接口层是ObjC，其他都是C/C++。接口层主要完成ORM和接口的易用性，需结合Swift的特性来做。

**Comment by tylerlong** [comment]
是否 Objective-C 的例子直接翻译成 Swift 就能用？ 能否写一个 Swift 版本的教程？ 类似这里的 Objective-C 的教程： https://github.com/Tencent/wcdb/wiki/iOS+macOS%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B

**Comment by qq20539350** [comment]
这个.mm 虽然没什么影响，但是看起来很尴尬

**Comment by cwwise** [comment]
realm底层 好像也是用c++写的吧。。

**Comment by raymondCaptain** [comment]
对 swift 的支持是否有排期？

**Comment by RingoD** [comment]
@raymondCaptain  下半年

**Comment by RingoD** [comment]
@Anomymouse  @tylerlong  @qq20539350  @cwwise  @raymondCaptain 
Swift 版 alpha 测试中： #176
