### ISSUE TITLE
The version in podspec didn't match tag

### ISSUE THREAD

**Issue by xilin** [Tencent/wcdb#501]
Even when the tag reach [v1.0.8.2](https://github.com/Tencent/wcdb/blob/v1.0.8.2/WCDB.podspec), the version in podspec is still 1.0.7.5.
```
wcdb.version      = "1.0.7.5"
```

Could you update the version in next release? Thanks.

**Comment by RingoD** [comment]
For ObjC version, the newest tag is v1.0.7.5. There is no difference between v1.0.7.5 and v1.0.8.2 for Objective-C code.

We are ongoing to integrate Swift version and ObjC version to avoid this kind of situation.

**Comment by xilin** [comment]
Got it, thanks.
