### ISSUE TITLE
Error when trying to update an element in table. 

### ISSUE THREAD

**Issue by Co2333** [Tencent/wcdb#502]
Swift WCDB, newest version installed from cocoa pods.

In my case, I fetched the string data from server and trying to write it back. Check the photo for details. 
![6E5D42D0-137F-42CF-913E-633DC2BD265F](https://user-images.githubusercontent.com/25259084/57019910-5aef4f00-6c5a-11e9-925c-af6e8f6c816e.jpeg)

I had also tried to add [ ] to parameter but there comes new issue. 
![71094DCF-B459-4895-897E-4A3864ED9076](https://user-images.githubusercontent.com/25259084/57019936-70647900-6c5a-11e9-91ab-61ebc7151f0a.jpeg)

I’m new to data base, and I think I was doing things just like the documents said. 

Please help me out. Best wishes.

**Comment by RingoD** [comment]
Unwrap some of the code so that Swift compiler can deduce syntax.

**Comment by Co2333** [comment]
I have tried to unwrap each variable with both ?? and ! but none of it works.
Both with [] and without [].
![屏幕快照 2019-05-05 下午5 16 51](https://user-images.githubusercontent.com/25259084/57191566-b0c53f00-6f59-11e9-8f5f-8b9956a42f27.png)
![屏幕快照 2019-05-05 下午5 16 35](https://user-images.githubusercontent.com/25259084/57191567-b15dd580-6f59-11e9-9bbc-d283aee30004.png)

I'm using insertOrReplace temporally while continue having the same problem.

**Comment by Co2333** [comment]
Fixed..... My fault.
![屏幕快照 2019-05-05 下午5 21 38](https://user-images.githubusercontent.com/25259084/57191619-42cd4780-6f5a-11e9-92b5-fad70e7348d6.png)
