### ISSUE TITLE
Delete condition did not work

### ISSUE THREAD

**Issue by MQL9011** [Tencent/wcdb#503]
### The language of WCDB
Swift
### The version of WCDB
1.0.8.2
### The platform of WCDB
iOS
### The installation of WCDB
Cocoapods
### What's the issue?

I want delete row data from table where  "albumId =  1 ",  but it did not work ...  row data is still exist

Please help.

Here is my code

![image](https://user-images.githubusercontent.com/11871158/57191427-1c0e1180-6f58-11e9-9193-b52b1062fa10.png)

**Comment by RingoD** [comment]
Remove `.rawValue`

**Comment by MQL9011** [comment]
> Remove `.rawValue`

![image](https://user-images.githubusercontent.com/11871158/57203742-35a96a80-6fe5-11e9-923b-d51409eddfca.png)

Here is my Model

**Comment by RingoD** [comment]
I think it's an error of Swift compiler. In your code, a `==`(compare/equal)  is expected. But the error said `convert`.
I think checking and following the test case code in repo may help.

**Comment by MQL9011** [comment]
> I think it's an error of Swift compiler. In your code, a `==`(compare/equal) is expected. But the error said `convert`.
> I think checking and following the test case code in repo may help.

I solved this by `like`

![image](https://user-images.githubusercontent.com/11871158/57208005-c68f3e80-7003-11e9-822b-26b0517b00cf.png)


but It is not the best  code.

Just so on....

**Comment by EdgarDegas** [comment]
Make sure you have imported WCDBSwift before any CRUD operation:
```swift
import WCDBSwift
```

Then write your code like this:
```swift
yourDatabase.delete(
    from: tableName,
    where: Entity.Properties.column == 1
)
```

Replace `==` with `like` is definitely wrong. They are completely different in a predicate.
