### ISSUE TITLE
how to group by date

### ISSUE THREAD

**Issue by iOkay** [Tencent/wcdb#505]
### The language of WCDB

> Objective-C

### The version of WCDB

> 1.0.7.5

### The platform of WCDB

> iOS

### The installation of WCDB

>  Cocoapods

### What's the issue?

 ```
@interface PlanWord : NSObject

@property(nonatomic, assign) NSInteger aid;
@property(nonatomic, retain) NSDate *addDate;
@property(nonatomic, retain) NSDate *modifyDate;

@end
```
I want to group PlanWord by modifyDate. How to implement it by code?

> sqlite: SELECT count(*) from mytable  GROUP BY strftime('%Y-%m-%d',  modifyDate)
> How to write it by wcdb?
I tried like this:
```
    WCTSelect *select = [[[self database] prepareSelectObjectsOfClass:[PlanWord class]
                                                            fromTable:tableName]
                         where:PlanWord.unlearned.is(0)];
    
    WCTExprList exprList = { @"%Y-%m-%d", PlanWord.modifyDate};
    NSArray *array = [[select groupBy:{WCTExpr::Function(@"strftime", exprList)}] allObjects];
```
but not work.

**Comment by RingoD** [comment]
You can register a SQL tracer to check whether it's correct.

**Comment by iOkay** [comment]
Thanks for reply. It's helpful.
