### ISSUE TITLE
可以在用AllProperties更新模型的所有字段时忽略掉(不更新)模型中某些是空值的属性(字段)吗？

### ISSUE THREAD

**Issue by zyvv** [Tencent/wcdb#506]
`updateRowsInTable:AccountTable onProperties:Account.AllProperties withObject:account where:Account.userID == account.userID]`

account中的空属性把更新之前的非空字段全部覆盖掉了。

**Comment by wenjinfu321** [comment]
问题咋解决的  怎么就关了？
