### ISSUE TITLE
如果清空列表后, 如何主键id如何从1开始再自增

### ISSUE THREAD

**Issue by bugaio** [Tencent/wcdb#507]
### The language of WCDB

>  Objective-C

### The version of WCDB

> 1.0.7.5

### The platform of WCDB

> iOS

### The installation of WCDB

>  Cocoapods

### What's the issue?
如果清空列表后, 如何主键id如何从1开始再自增?

**Comment by RingoD** [comment]
Learn [auto increment](https://www.sqlite.org/autoinc.html) and [sqlite_sequence](https://www.sqlite.org/fileformat2.html#seqtab).
