### ISSUE TITLE
in IOS，why is the WAL file size so large?

### ISSUE THREAD

**Issue by mustlogin** [Tencent/wcdb#508]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
Please provide the basic information as the issue template.

**Comment by mustlogin** [comment]
I use transaction to update/insert/replace data into DB normally, but the WAL file size will be larger and  larger. 
I tried to derive class of WCDB and expose sqlite API:sqlite3_wal_checkpoint() , and execute this API manually, but it doesn't work!
What's wrong with this?

**Comment by RingoD** [comment]
@mustlogin  Didn't you see what issue template say?

**Comment by mustlogin** [comment]
It is not relevant to issue template. I seem to fix it now. 
I try to commit data with transaction, it doesn't work. But when I close the DB connection before the app process will be terminated,  the WAL file contents merge to DB. The WAL is gone! 
I will test more in this way.

**Comment by RingoD** [comment]
Without language, version, and more other info, I have no idea to solve this issue.
