### ISSUE TITLE
const WCTCondition &  传值到block后, 有问题

### ISSUE THREAD

**Issue by bugaio** [Tencent/wcdb#509]
### The language of WCDB

> Objective-C

### The version of WCDB

> 1.0.7.5

### The platform of WCDB

>iOS

### The installation of WCDB

> Cocoapods

### What's the issue?
我还是个菜鸟,  写了一个方法如下, 但是condition 传值到异步 block中后, 就会变的很奇怪, 请问有什么办法 解决么? 

**报错信息:**
 [WCDB]出错了啊啊啊 Code:1, Type:SQLite, Msg:unrecognized token: "", Tag:0, ExtCode:1, SQL:DELETE FROM MESSAGE WHERE yÔ,

**异步方法:**
```Object-C
/**
 异步  删除

 @param tabName 表名
 @param condition 条件
 @param complete 结果
 */
- (void)asyncDeleteWithTableName:(NSString *)tabName
                           Where:(const WCTCondition &)condition
                        Complete:(void(^)(BOOL result))complete
{
    [self.dataBaseQueue async:^{
        BOOL result = [self deleteWithTableName:tabName Where:condition];
        complete(result);
    }];
}
```

**Comment by bugaio** [comment]
不懂  c++,  不过自己 做测试, 把  `Where:(const WCTCondition &)condition` 改成`Where:(const WCTCondition)condition` 去掉了`&` , 好像就可以了.
 有没有大神 稍微给我扫个盲就好,  谢谢~

**Comment by RingoD** [comment]
`condition` is already deconstructed when `async` run.

**Comment by RingoD** [comment]
Actually, I can't understand why it's needed to be wrapped. `asyncDeleteWithTableName` just passes through the parameters and does nothing.

**Comment by bugaio** [comment]
@RingoD 是这样的,  我把维护了一个 队列,  把对 数据库的操作  抽象成一个 task, 类似 insertTask,  deleteTask 之类的 ,  有个dataManager 就是把 这些操作  组装为task,  扔进 队列里,   然后对每个任务 可以 取消, 可以挂起 之类的,   不过 我还没有 写完...
