### ISSUE TITLE
iOS平台是否支持ARC

### ISSUE THREAD

**Issue by czj1127292580** [Tencent/wcdb#51]
我看用模板生成的代码里面有retain

**Comment by RingoD** [comment]
支持。
你是说哪里的代码，麻烦贴一下

**Comment by czj1127292580** [comment]
/*
@property(nonatomic, assign) int primary;
@property(nonatomic, retain) NSString* valueWithIndex;
@property(nonatomic, assign) int valueWithSpecifiedColumnName;
@property(nonatomic, retain) NSString* valueWithDefaultValue;
@property(nonatomic, assign) unsigned int value1WithMultiIndex;
@property(nonatomic, retain) NSString* value2WithMultiIndex;

**Comment by czj1127292580** [comment]
另外我用cocoapods导入的，这里报错了'list' file not found
![image](https://user-images.githubusercontent.com/10876312/27282337-169d1f2c-5522-11e7-8963-769ad88148eb.png)

**Comment by RingoD** [comment]
那个retain和ARC没关系

**Comment by RingoD** [comment]
5. 由于WCDB是基于Objective-C++，因此需要将引用WCDB的源文件后缀.m改为.mm。

**Comment by czj1127292580** [comment]
已经改了啊，就是在导入那个文件的时候报的错，不引入模型文件就不会报错！！！

发自我的 iPhone

**Comment by czj1127292580** [comment]
已经OK了，模型里引入了WCDB，别的文件引入模型的时候，也需要将该文件改为.mm的，谢啦
