### ISSUE TITLE
about composite indexes

### ISSUE THREAD

**Issue by mustlogin** [Tencent/wcdb#510]
Help!  Please tell me, which macro ( WCDB_INDEX,  WCDB_UNIQUE_INDEX, ...)  can be used to create composite indexes, such as: 
CREATE UNIQUE INDEX "idx_1" ON "table"(field1, field2)

**Comment by RingoD** [comment]
It's already introduced in the wiki.

**Comment by mustlogin** [comment]
Just because there is not introduction about this, I ask for help in here. There is only introduce about common index, not composite index!!!
I read you iOS sample code and didn't find too. 
And I think that you should not close the issue until give us some right answer.

**Comment by RingoD** [comment]
https://github.com/Tencent/wcdb/wiki/ORM使用教程#多字段索引

**Comment by mustlogin** [comment]
Thanks!  You really did me a favor.
