### ISSUE TITLE
20W+ 数据量 增删改用时过长

### ISSUE THREAD

**Issue by SoloFriend** [Tencent/wcdb#511]
### The language of WCDB

> Java 

### The version of WCDB

> v1.0.8

### The platform of WCDB

> Android

### The installation of WCDB

> Git clone

### What's the issue?

> 我原本看了微信的全文检索优化的帖子，用了全文检索后查询速度可以接受，但是增删改速度还是达不到要求，
>尝试了一下WCDB，查询速度跟自实现的全文检索相当，但是增删改还是要2-3s（终端用的HI3798mv200芯片 性能堪忧）
>请问有没有可能优化的点？
>我目前的操作方式是直接使用WCDB中的SQLiteDatabase，获取到数据库后直接写的sql语句做的测试，有其他提高增删改效率的写法么？

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
