### ISSUE TITLE
请教一下,我想监听某张表的数据变化,主要是数据条数的变化,有什么比较好的办法吗

### ISSUE THREAD

**Issue by MQL9011** [Tencent/wcdb#512]
### The language of WCDB
Swift
### The version of WCDB
WCDB.swift  1.0.8.2
### The platform of WCDB
iOS
### The installation of WCDB
Cocoapods
### What's the issue?
 请教一下,我想监听某张表的数据变化,主要是数据条数的变化,有什么比较好的办法吗

**Comment by RingoD** [comment]
In short, no.

SQLite itself provides some `sqlite_XXX_hook` or other interfaces to do the reflection work. The ability is so limited that we can't go too far., especially comparing other modern database frameworks.

In our roadmap, we will do this hard work. By modifying the source code of SQLite, using our "unique" `WINQ` ability or other implementation, we may find a better solution.

**Comment by MQL9011** [comment]
@RingoD  Thanks. Looking forward to early support !

**Comment by auxten** [comment]
@MQL9011  SQLite has built-in TRIGGER, try it.
