### ISSUE TITLE
swift 5.0 pod install之后编译报错

### ISSUE THREAD

**Issue by baozhoua** [Tencent/wcdb#513]
### The language of WCDB

Swift 5.0

### The version of WCDB

1.0.7.5

### The platform of WCDB

iOS

### The installation of WCDB

 Cocoapods

### What's the issue?
#

pod install 之后编译报错：
1：
"extension Array: ColumnCodable, ColumnCodableBase where Element: Codable {
    public static var columnType: ColumnType {
        return .BLOB
    }
    public init?(with value: FundamentalValue) {
        guard let decodable = try? JSONDecoder().decode(Array.self, from: value.dataValue) else {
            return nil
        }
        self = decodable
    }
    public func archivedValue() -> FundamentalValue {
        guard let encoded = try? JSONEncoder().encode(self) else {
            return FundamentalValue(nil)
        }
        return FundamentalValue(encoded)
    }
}"扩展中
Redundant conformance of 'Array<Element>' to protocol 'ColumnCodableBase'

2：
`extension Dictionary: ColumnCodable, ColumnCodableBase where Key: Codable, Value: Codable {
    public static var columnType: ColumnType {
        return .BLOB
    }
    public init?(with value: FundamentalValue) {
        guard let decodable = try? JSONDecoder().decode(Dictionary.self, from: value.dataValue) else {
            return nil
        }
        self = decodable
    }
    public func archivedValue() -> FundamentalValue {
        guard let encoded = try? JSONEncoder().encode(self) else {
            return FundamentalValue(nil)
        }
        return FundamentalValue(encoded)
    }
}`报：
Redundant conformance of 'Dictionary<Key, Value>' to protocol 'ColumnCodableBase'错误

3：
`extension Set: ColumnCodable, ColumnCodableBase where Element: Codable {
    public static var columnType: ColumnType {
        return .BLOB
    }
    public init?(with value: FundamentalValue) {
        guard let decodable = try? JSONDecoder().decode(Set.self, from: value.dataValue) else {
            return nil
        }
        self = decodable
    }
    public func archivedValue() -> FundamentalValue {
        guard let encoded = try? JSONEncoder().encode(self) else {
            return FundamentalValue(nil)
        }
        return FundamentalValue(encoded)
    }
}`报
Redundant conformance of 'Set<Element>' to protocol `'ColumnCodableBase'` 错误

4：
    public static func open(pTokenizer: UnsafeMutablePointer<sqlite3_tokenizer>?,
                            pInput: UnsafePointer<Int8>?,
                            nBytes: Int32,
                            ppCursor: UnsafeMutablePointer<UnsafeMutablePointer<sqlite3_tokenizer_cursor>?>?) -> Int32 {
        var bytes: Int32 = nBytes
        if pInput == nil {
            bytes = 0
        }
        if bytes < 0 {
            bytes = Int32(strlen(pInput))
        }

        let cursorSize = MemoryLayout<Cursor>.size
        let optionalCursorRawPointer = sqlite3_malloc(Int32(cursorSize))
        guard let cursorRawPointer = optionalCursorRawPointer else {
            return SQLITE_NOMEM
        }
        memset(cursorRawPointer, 0, cursorSize)

        let tokenizerPointer = UnsafeMutableRawPointer(pTokenizer!).assumingMemoryBound(to: Tokenizer.self)
        let cursorPointer = cursorRawPointer.assumingMemoryBound(to: Cursor.self)
        let tokenizerInfo = Unmanaged<TokenizerInfo>.fromOpaque(tokenizerPointer.pointee.info).takeUnretainedValue()
        let cursorInfo = CursorInfo(withInput: pInput, count: bytes, tokenizerInfo: tokenizerInfo)
        cursorPointer.pointee.info = Unmanaged.passRetained(cursorInfo).toOpaque()

        ppCursor!.pointee = cursorRawPointer.assumingMemoryBound(to: sqlite3_tokenizer_cursor.self)

        return SQLITE_OK
    }
中报：Value of optional type 'UnsafePointer<Int8>?' must be unwrapped to a value of type 'UnsafePointer<Int8>'。

**Comment by RingoD** [comment]
Update to the newest version.
