### ISSUE TITLE
failed to open existing encrypted database encrypted use SQLCipher 4 defaults configuration

### ISSUE THREAD

**Issue by zhouzhongguang** [Tencent/wcdb#514]
### The language of WCDB
Objective-C

### The version of WCDB
V 1.0.7.5

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?
As the title says, I have a existing encrypted database file use SQLCipher 4 default configurations.
`    sqlite3_key(_database, [key UTF8String], (int)key.length);`
I can open it use DB Browser App by input the encryption key string and select SQLCipher 4 default configurations, as follows:
![屏幕快照 2019-05-17 上午11 18 42](https://user-images.githubusercontent.com/10241716/57900968-906c7d00-7895-11e9-9567-490422467c45.png)

But when set the same key use WCDB and run create table code it logs error:
![屏幕快照 2019-05-17 上午11 35 33](https://user-images.githubusercontent.com/10241716/57901472-ecd09c00-7897-11e9-8af6-592c03d65d2e.png)

error:
`[WCDB][DEBUG]Code:26, Type:SQLiteGlobal, Msg:file is encrypted or is not a database
[WCDB][ERROR]Code:26, Type:SQLite, Tag:0, Op:4, ExtCode:26, Msg:file is encrypted or is not a database, SQL:PRAGMA synchronous='NORMAL', Path:/var/mobile/Containers/Data/Application/DAEECA1F-09DD-40BD-88FC-F87AE72DF416/Library/hikMoaDataBase_zhouzhongguang.sqlite`

Is there some APIs to configure the three options : "KDF iterations" 
、"HMAC algorithm" and "KDF algorithm"

**Comment by RingoD** [comment]
Try sqlcipher 3.

**Comment by zhouzhongguang** [comment]
But the problem is the existing encrypted database file is already on user's device by old version APP. And next version i want migrate the DB code library to WCDB library.  What should i do?

If migrate the data in the existing database file, it should open database use SQLCipher 4. But the SQLCipher4 and WCDBOptimizedSQLCipher cant appear in the same project.😢

**Comment by RingoD** [comment]
Unfortunately, I think there is hard work to be done.

At the moment WCDB released, the newest sqlcipher version was v3. And v4 was released 2018.12.1, which is not too long ago.

We have no plan for upgrading sqlcipher to v4 recently, especially considering this compatible issue.

**Comment by zhouzhongguang** [comment]
Thank you, i know.
