### ISSUE TITLE
xcode 10.1 编译失败

### ISSUE THREAD

**Issue by lizhaojie001** [Tencent/wcdb#515]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
 Swift4.2

### The version of WCDB

> e.g. v1.0.5
1.8.0.2

### The platform of WCDB

> e.g. iOS, macOS or Android
macOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

https://zhuanlan.zhihu.com/p/60453657
不同版本的xcode,语法变异不通过 xocde10.2可以编译通过
具体的可以看下知乎这里面
都是典型了

**Comment by lizhaojie001** [comment]
不知道咋解决

**Comment by RingoD** [comment]
Use the newest Xcode version.

**Comment by lizhaojie001** [comment]
我不想升级系统

**Comment by RingoD** [comment]
Then nobody can help you.

**Comment by RingoD** [comment]
No reply.
