### ISSUE TITLE
Swift 5 support ?

### ISSUE THREAD

**Issue by jienice** [Tencent/wcdb#516]

**Comment by RingoD** [comment]
What's the question?

**Comment by jienice** [comment]
just like warnings:

'withUnsafeBytes' is deprecated: use `withUnsafeBytes<R>(_: (UnsafeRawBufferPointer) throws -> R) rethrows -> R` instead

**Comment by RingoD** [comment]
Please provide the basic information as the issue template said.

**Comment by jienice** [comment]
### The language of WCDB

> Swift


### The version of WCDB

> v1.0.8.2


### The platform of WCDB

>  iOS


### The installation of WCDB

>  Cocoapods



### What's the issue?

> i just update swift version to 5.0.  convert wcdbswift
> 
![20190604145040](https://user-images.githubusercontent.com/24646304/58857557-2b5bb880-86d8-11e9-84da-760c0e54a539.jpg)

**Comment by RingoD** [comment]
Does warning still exist with Swift 5.x and WCDB v1.0.8.2?

**Comment by ClaudeLi** [comment]
let rc = key.withUnsafeBytes ({ (bytes) -> Int32 in
            let bytes = bytes.load(as: UnsafePointer<Int8>.self)
            return sqlite3_key(handle, bytes, Int32(key.count))
        })

这样是否可行？

**Comment by bluedaquiri** [comment]
> Does warning still exist with Swift 5.x and WCDB v1.0.8.2?

Waring still exist  with Swift 5.x and WCDB v1.0.8.2

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
