### ISSUE TITLE
查询失败，提示no such table，实际上是存在的

### ISSUE THREAD

**Issue by markingdom** [Tencent/wcdb#517]
### The language of WCDB

Java

### The version of WCDB

1.0.4

### The platform of WCDB

 Android

### The installation of WCDB

Maven

### What's the issue?

![image](https://user-images.githubusercontent.com/27982416/58154665-b84c4e00-7ca4-11e9-8ed9-55a8f7c514aa.png)

**Comment by markingdom** [comment]
密码是正确的，用sqlcipher图形化工具打开没有问题

**Comment by John-He-928** [comment]
加密配置不对，会被视为密码不对，触发默认`DatabaseErrorHandler`，删掉原来的DB重新创建一个

**Comment by markingdom** [comment]
好的 多谢
