### ISSUE TITLE
Install WCDB Via Dynamic Framework, but build failed

### ISSUE THREAD

**Issue by zacdaryl** [Tencent/wcdb#519]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.5

### The platform of WCDB

> iOS

### The installation of WCDB

> Git clone

### What's the issue?
Install Via Dynamic Framework
> Compile rtree.c
> **/wcdb/sqlcipher/ext/rtree/rtree.c:980:44: No member named 'bCorrupt' in 'struct Rtree'
> **/wcdb/sqlcipher/ext/rtree/rtree.c:3442:43: Use of undeclared identifier 'SQLITE_PREPARE_NO_VTAB'

**Comment by RingoD** [comment]
I think you should upgrade to the newest version since you are using v1.0.5.

**Comment by zacdaryl** [comment]
I checkout a new branch from tag v1.0.8.2, and checkout out sqlcipher branch to wcdb, then build, but there is a new error occur:

> Undefined symbols for architecture armv7:
  "_sqlcipher_codec_ctx_set_cipher", referenced from:
      _sqliterkCryptoSetCipher in sqliterk_crypto.o
ld: symbol(s) not found for architecture armv7

Finally, I installed via CocoaPods

**Comment by RingoD** [comment]
I think you may not update the sqlcipher submodule.

**Comment by zacdaryl** [comment]
Thanks，after ‘git submodule --init sqlcipher’，sqlcipher‘s error is gone.
But,  in my *.h file, 
 `#import <WCDB/WCDB.h>`
'WCDB/WCDB.h'  file not found

**Comment by RingoD** [comment]
Check the wiki first.

**Comment by Yzc-jason** [comment]
Check out the master,and run Benchmark-WCDB-macOS have a error.
"Use of undeclared identifier 'SQLITE_PREPARE_NO_VTAB'"

**Comment by RingoD** [comment]
`master` is in preparation. Use the specified tag instead.

**Comment by moyu011** [comment]
I am using Xcode 16.0 + MacOS 15.0.1 + WDCB 2.1.8 development environment, and I have reproduced this issue. How can I resolve it?
