### ISSUE TITLE
Refactor: 优化updateTable:onProperty接口名

### ISSUE THREAD

**Issue by mayu0418** [Tencent/wcdb#52]
updateTable:@"my_wcdb" onProperty:MYModel.name withObject:model 不是 调用这个么 还是说需要加where的？

**Comment by RingoD** [comment]
要加where语句，SQLite的语法规则如此。
不过这里的接口名确实存在一些不严谨，我后面改一下

**Comment by RingoD** [comment]
https://github.com/Tencent/wcdb/commit/3757fb4143a46a74a9188a11cb58540f7b6ee924
