### ISSUE TITLE
How to clean cipher key ?

### ISSUE THREAD

**Issue by mustlogin** [Tencent/wcdb#521]
### The language of WCDB

Objective-C

### The version of WCDB

v1.0.5

### The platform of WCDB

iOS

### The installation of WCDB

 Cocoapods

### What's the issue?

As the issue #520 described, I had known the way to change cipher key:
_WCDB::StatementPragma stp = WCDB::StatementPragma().pragma(WCDB::Pragma::Rekey, "newkey");
BOOL rc = [database exec:stp];_

According to the description of sqlite3_rekey() in sqlite3.h, line 5028~5093,
_/*
** Change the key on an open database.  If the current database is not
** encrypted, this routine will encrypt it.  If pNew==0 or nNew==0, the
** database is decrypted.
**
** The code to implement this API is not available in the public release
** of SQLite.
*/
SQLITE_API int sqlite3_rekey(
  sqlite3 *db,                   /* Database to be rekeyed */
  const void *pKey, int nKey     /* The new key */
);_

In order to clean the encryption key, I set the parameter is **empty** as following,
_WCDB::StatementPragma stp = WCDB::StatementPragma().pragma(WCDB::Pragma::Rekey, **""**);
BOOL rc = [database exec:stp];_

In debug model, I can see it compose a SQL : _**PRAGMA rekey=''**_
But while the code step into sqlite3_rekey_v2(),  this following code: 

_int sqlite3_rekey_v2(sqlite3 *db, const char *zDb, const void *pKey, int nKey) {
  CODEC_TRACE(("sqlite3_rekey_v2: entered db=%p zDb=%s pKey=%s, nKey=%d\n", db, zDb, (char *)pKey, nKey));
  **if(db && pKey && nKey) {**    //<-- it jumps over here !!
    ......
  }
  return SQLITE_ERROR;
}_

It do nothing at all, because the variable **nKey** is 0.
This is, it doesn't clear encryption key!!   How shall I do ? Pls help me!

**Comment by RingoD** [comment]
I think the doc will help: https://www.zetetic.net/sqlcipher/sqlcipher-api/#rekey

**Comment by mustlogin** [comment]
> I think the doc will help: https://www.zetetic.net/sqlcipher/sqlcipher-api/#rekey

Thanks! I will try again later.

**Comment by mustlogin** [comment]
I can't solve this problem. I read the doc of upon URL: https://www.zetetic.net/sqlcipher/sqlcipher-api/#rekey, and found these:

_Example 2: Decrypt a SQLCipher database to a Plaintext Database
$ ./sqlcipher encrypted.db
sqlite> PRAGMA key = 'testkey';
sqlite> ATTACH DATABASE 'plaintext.db' AS plaintext KEY '';  -- empty key will disable encryption
sqlite> SELECT sqlcipher_export('plaintext');
sqlite> DETACH DATABASE plaintext;_

I derive a class from class WCDB::Statement, so that I can config these sentences. Then use this method of WCTDatabase:
_- (BOOL)exec:(const WCDB::Statement &)statement_
But it executed unsuccessfully. I don't know why.

**Comment by RingoD** [comment]
Then what's the error?

**Comment by mustlogin** [comment]
> Then what's the error?

No any errors occur, but the encrypted db file should be opened with cipher key still.

**Comment by RingoD** [comment]
Well, I don't understand what this issue is about.

**Comment by RingoD** [comment]
no reply.

**Comment by triste24** [comment]
when using PRAGMA，use "sqlite3_prepare_v2" instead of "sqlite3_exec",or just call "sqlite3_key" before "ATTACH"
