### ISSUE TITLE
How to change the empty field ranked when sorting data?

### ISSUE THREAD

**Issue by ssuperdreamer** [Tencent/wcdb#522]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Objective-C

### The version of WCDB

> e.g. v1.0.5

1.0.7.5

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

Sorting data when a field is empty, it will be ranked first.
I googled and found that this question can be solved like this 
`select * from xxxx order by xxx.a desc nulls last/first` in oracle or 'use case when' in sqlite to change the ranked.
So I saw the source code and found 'case', but I don't know how to use it.
Please give me some advice thx : )

**Comment by RingoD** [comment]
My suggestion is to retrieve all needed rows and sort by code instead of SQL.

**Comment by RingoD** [comment]
No reply.
