### ISSUE TITLE
update to the lastest version at cocoapods 

### ISSUE THREAD

**Issue by zhenian** [Tencent/wcdb#523]
### The language of WCDB

 Objective-C

### The version of WCDB

 1.0.7.5 => 1.0.8.2

### The platform of WCDB

iOS, macOS

### The installation of WCDB

Cocoapods

### What's the issue?

library is outdated at cocoapods.

**Comment by RingoD** [comment]
So what's the question?

**Comment by zhenian** [comment]
@github is v1.0.8.2
@cocoapods is v1.0.7.5  [^](https://cocoapods.org/pods/WCDB)

**Comment by RingoD** [comment]
For ObjC version, v1.0.7.5 is same as v1.0.8.2.
