### ISSUE TITLE
Cannot convert value of type 'Sample.Properties' (aka 'Sample.CodingKeys') to expected argument type '[PropertyConvertible]?'

### ISSUE THREAD

**Issue by JyyJDast1** [Tencent/wcdb#524]
### The language of WCDB
>  Swift 

### The version of WCDB
>  v1.0.8.2

### The platform of WCDB
> iOS

### The installation of WCDB
> Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
<img width="895" alt="屏幕快照 2019-05-31 上午9 53 03" src="https://user-images.githubusercontent.com/12796736/58678277-ae57d880-8391-11e9-90d9-a598a719cf3b.png">
<img width="855" alt="屏幕快照 2019-05-31 上午9 54 47" src="https://user-images.githubusercontent.com/12796736/58678278-aef06f00-8391-11e9-9222-b863ccc7d7a3.png">

> Explain what you want by example or code **in English**.

How can I  solve the error:Cannot convert value of type 'Sample.Properties' (aka 'Sample.CodingKeys') to expected argument type '[PropertyConvertible]?'
Thanks!

**Comment by Dast1990** [comment]
solved，use：
 try? gDataBase.insert(objects: lM1, on: [Sample.Properties.weight], intoTable: TABLE_NAME)
the document on wiki need to be updated!

**Comment by RingoD** [comment]
In some case, it's ok. 

But in your case, it failed to compile since the compiler can't deduce the type. So sometimes, you should reduce the complexity of the expression to avoid compiler complaints.
