### ISSUE TITLE
It seems to dead lock when close DB

### ISSUE THREAD

**Issue by mustlogin** [Tencent/wcdb#525]
### The language of WCDB

Objective-C

### The version of WCDB

pod from master, v1.0.7.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

I create a sub class who is derived from **"WCDB::Statement"**, and use it to config a SQL sentence such as,
```
Printing description of sc:
(WCDB::Statement) WCDB::Statement = {
  WCDB::Describable = (m_description = "UPDATE work SET title=?, content=? WHERE proid=4010")
}
```

Then call  the method:
  `- (WCTStatement *)prepare:(const WCDB::Statement &)statement`
such as:
```
1.   WCTStatement* st = [database prepare:sc];
2.   int x = [st getColumnCount];
3.   BOOL b = [st bindValue:@"CCCCC" byColumnName:@"title"];
4.   b = [st bindValue:@"DDDDDDDDDDDDD" byColumnName:@"content"];
5.   b = [st step];
6.   [st finalize];
```
There are some question about this code segment:
1. Once line 1 is executed, then execute
`- (void)close`
or
`-(void)close:(WCTCloseBlock)onClosed`
will be blocked at following line each time:
```
void RWLock::lockWrite()
{
    std::unique_lock<decltype(m_mutex)> lock(m_mutex);
    ++m_pending;
    while (m_writer > 0 || m_reader > 0) {
        m_cond.wait(lock);       // <-- BLOCK HRER !!!!!!
    }
    --m_pending;
    ++m_writer;
}
```
But,  check the status  **`b = [database isBlockaded]`**,  the return value is NO, normally.

2. At line 2,  the variable x is 0; at line 3  and 4, b is NO. That is,  bind value unsuccessfully. 
So I have some doubt there maybe some mistakes in this:
`- (WCTStatement *)prepare:(const WCDB::Statement &)statement`

**Comment by RingoD** [comment]
Add a `@autoreleasepool` to confirm those objects `dealloc`ed.

**Comment by mustlogin** [comment]
> Add a `@autoreleasepool` to confirm those objects `dealloc`ed.

This is OK. Once this method:
`- (WCTStatement *)prepare:(const WCDB::Statement &)statement
`
is embed into **@autoreleasepool**, the db will be closed normally!

**Comment by mustlogin** [comment]
> > Add a `@autoreleasepool` to confirm those objects `dealloc`ed.
> 
> This is OK. Once this method:
> `- (WCTStatement *)prepare:(const WCDB::Statement &)statement `
> is embed into **@autoreleasepool**, the db will be closed normally!

But even if this, it can't bind value yet. 
```
int x = [st getColumnCount];
3.   BOOL b = [st bindValue:@"CCCCC" byColumnName:@"title"];
4.   b = [st bindValue:@"DDDDDDDDDDDDD" byColumnName:@"content"];
```
This is a fatal problem.

**Comment by RingoD** [comment]
Call `getColumnCount` after `step:`.

I think you should check the tutorial first.

**Comment by mustlogin** [comment]
> Call `getColumnCount` after `step:`.
OK. Call `getColumnCount` before `step` IS my fault, but this line code is insignificant indeed.
The next two line are crucial:
```
3.   BOOL b = [st bindValue:@"CCCCC" byColumnName:@"title"];
4.   b = [st bindValue:@"DDDDDDDDDDDDD" byColumnName:@"content"];
```
I tried again. It can't bind value yet and the return value **`b`** is `NO` always!

**Comment by RingoD** [comment]
If this issue still exists, please submit a sample project for us. Thanks.
