### ISSUE TITLE
Create Table Crash

### ISSUE THREAD

**Issue by Charming04** [Tencent/wcdb#526]
The version of 1.0.6 WCDB，iOS platform， install by Cocoapods

Thread SIGBUS EXC_BAD_ACCESS

#std::__1::__function::__func<-[WCTInterface(Table) createTableAndIndexesOfName:withClass:andError:]::$_0, std::__1::allocator<-[WCTInterface(Table) createTableAndIndexesOfName:withClass:andError:]::$_0>, bool (WCDB::Error&)>::operator()(WCDB::Error&)
#std::__1::__function::__func<-[WCTInterface(Table) createTableAndIndexesOfName:withClass:andError:]::$_0, std::__1::allocator<-[WCTInterface(Table) createTableAndIndexesOfName:withClass:andError:]::$_0>, bool (WCDB::Error&)>::operator()(WCDB::Error&)
#WCDB::CoreBase::runTransaction(std::__1::function<bool (WCDB::Error&)>, std::__1::function<void (WCDB::CoreBase::TransactionEventType)>, WCDB::Error&)
#WCDB::Database::runEmbeddedTransaction(std::__1::function<bool (WCDB::Error&)>, WCDB::Error&)
#-[WCTInterface(Table) createTableAndIndexesOfName:withClass:andError:]
#-[WCTDatabase(Table) createTableAndIndexesOfName:withClass:]

**Comment by RingoD** [comment]
Please provide the whole crash stacks or a project that can reproduce this issue.

**Comment by RingoD** [comment]
No reply.
