### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by azureplus** [Tencent/wcdb#529]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
Swift

### The version of WCDB

> e.g. v1.0.8

### The platform of WCDB

> e.g. iOS, macOS or Android
iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Carthage

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

/usr/bin/xcrun xcodebuild -workspace /app/Carthage/Checkouts/wcdb-swift/WCDB.xcworkspace -scheme WCDB.swift -configuration Release -derivedDataPath /app Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/wcdb-swift/d78747605422caca65694e32a899ad7e3125be7a -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/6y/_wpm7cpn22g4ycnnkct0f0tw0000gn/T/wcdb-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /app/Carthage/Checkouts/wcdb-swift)

**Comment by RingoD** [comment]
I didn't see the error.

**Comment by RingoD** [comment]
No reply.
