### ISSUE TITLE
使用WCDBSwift怎么实现类继承的模型绑定？

### ISSUE THREAD

**Issue by hzm2014** [Tencent/wcdb#530]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
I don't understand your question. Is there a sample?

**Comment by hzm2014** [comment]
import WCDBSwift

//*****************BaseUser*********************

class VEBaseUser: TableCodable {
    
    var userId: String? = "0" //user ID, 不能为空
    var nickname: String? = ""
    var address: String? = ""
    var age: Int = 0
    var phone: String? = ""
    var gender: String?
    var avatarUrl: String? = ""
    
    enum CodingKeys: String, CodingTableKey {
        typealias Root = VEBaseUser
        static let objectRelationalMapping = TableBinding(CodingKeys.self)
        case userId
        case nickname
        case address
        case age
        case phone
        case gender
        case avatarUrl
        
        static var columnConstraintBindings: [CodingKeys: ColumnConstraintBinding]? {
            return [
                userId: ColumnConstraintBinding(isPrimary: true),
            ]
        }
    }
}

//*****************VEUser*********************
class VEUser: VEBaseUser {
    var password: String? = ""
    var token: String? = ""
}

The VEUser inherit "VEBaseUser" ,then how does the "VEBaseUser" conform to protocol 'TableDecodable'?

**Comment by RingoD** [comment]
No. Inheritance is not supported now.
