### ISSUE TITLE
SQLiteRepairKit failed to parse unchanged/uncorrupted B-tree 

### ISSUE THREAD

**Issue by GuanshanLiu** [Tencent/wcdb#532]
### The language of WCDB

Swift

### The version of WCDB

SQLiteRepairKit (1.2.2)
WCDB.swift (1.0.8.2)

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

I am trying to use SQLiteRepairKit to backup/recover our CoreData SQLite Database.

Here is the demo:
https://www.icloud.com/iclouddrive/0RGAIU-PQ6zihJ_gooro6SnwQ#WCDBDemo

Steps:
1. Create a SQLite-backed Core Data database.
2. Backup
3. Recovery

Result:
[SQLITERK_DAMAGED] Failed to parse page 2.
[SQLITERK_DAMAGED] Failed to parse B-tree with root page 2.

It prints out that it failed to parse page, saying it is damaged.

Expected:

Successfully parse all the b-tree.
In my production code, because of this issue, it will fails to recover the data even though nothing changes in the database and it is not corrupted at all.

Using WCDB api to backup and recover CoreData SQLite database will print out the same messages.

**Comment by RingoD** [comment]
Could you please provide the database file generated in your machine?

**Comment by GuanshanLiu** [comment]
Thank you for your reply. 

Here is an updated demo with database files generated on my machine. 
https://www.icloud.com/iclouddrive/0TCXY4Sixbfp7f4RYR_H9q0cg#WCDB-2

This is the persistent store options we are using:
```swift
[
    NSMigratePersistentStoresAutomaticallyOption: true,
    NSInferMappingModelAutomaticallyOption: true,
    NSSQLitePragmasOption: ["secure_delete": true]
 ]
```

**Comment by GuanshanLiu** [comment]
Hi, is there any update on the issue? I added another demo. https://github.com/GuanshanLiu/WCDB-Bug

Even with the WCDB APIs, it will have the same output when trying recover from an uncorrupted database.

```
[SQLITERK_OK] Begin parsing sqlite_master...
[SQLITERK_OK] Parsing B-tree -> [root: 1, name: sqlite_master, type: sqlite_master]
[SQLITERK_OK] Parsed sqlite_master. [table/index: 4]
[SQLITERK_OK] >>> CREATE TABLE ZSAMPLE ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZNAME VARCHAR )
[SQLITERK_OK] [ZSAMPLE] -> pgno: 3
[SQLITERK_OK] Parsing B-tree -> [root: 3, name: ZSAMPLE, type: table]
[SQLITERK_DAMAGED] Failed to parse page 3.
[SQLITERK_DAMAGED] Failed to parse B-tree with root page 3.
[SQLITERK_OK] >>> CREATE TABLE Z_METADATA (Z_VERSION INTEGER PRIMARY KEY, Z_UUID VARCHAR(255), Z_PLIST BLOB)
[SQLITERK_OK] [Z_METADATA] -> pgno: 5
[SQLITERK_OK] Parsing B-tree -> [root: 5, name: Z_METADATA, type: table]
[SQLITERK_OK] >>> CREATE TABLE Z_MODELCACHE (Z_CONTENT BLOB)
[SQLITERK_OK] [Z_MODELCACHE] -> pgno: 6
[SQLITERK_OK] Parsing B-tree -> [root: 6, name: Z_MODELCACHE, type: table]
[SQLITERK_OK] >>> CREATE TABLE Z_PRIMARYKEY (Z_ENT INTEGER PRIMARY KEY, Z_NAME VARCHAR, Z_SUPER INTEGER, Z_MAX INTEGER)
[SQLITERK_OK] [Z_PRIMARYKEY] -> pgno: 4
[SQLITERK_OK] Parsing B-tree -> [root: 4, name: Z_PRIMARYKEY, type: table]
[SQLITERK_OK] Recovery output finished. [succeeded: 7, failed: 0]
```

**Comment by RingoD** [comment]
It's ongoing.

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
