### ISSUE TITLE
mmicu英文分词不支持部分匹配

### ISSUE THREAD

**Issue by risechen** [Tencent/wcdb#534]
### The language of WCDB

> Java 

### The version of WCDB

> v1.0.8

### The platform of WCDB

>  Android

### The installation of WCDB

> AAR

### What's the issue?

mmicu英文分词不支持部分匹配，比如索引库内容是“Android developer”，使用match 'an'无法命中“Android developer”，只有输入'android'才能命中。而且电话号码也是不支持部分匹配，需要输入完整的手机号才能命中

**Comment by John-He-928** [comment]
请使用前缀匹配：https://www.sqlite.org/fts3.html#full_text_index_queries

> Token or token prefix queries. An FTS table may be queried for all documents that contain a specified term (the simple case described above), or for all documents that contain a term with a specified prefix. As we have seen, the query expression for a specific term is simply the term itself. The query expression used to search for a term prefix is the prefix itself with a '*' character appended to it. For example:
> ```
> -- Virtual table declaration
> CREATE VIRTUAL TABLE docs USING fts3(title, body);
>
> -- Query for all documents containing the term "linux":
> SELECT * FROM docs WHERE docs MATCH 'linux';
> 
> -- Query for all documents containing a term with the prefix "lin". This will match
> -- all documents that contain "linux", but also those that contain terms "linear",
> --"linker", "linguistic" and so on.
> SELECT * FROM docs WHERE docs MATCH 'lin*';
> ```
