### ISSUE TITLE
类似 UIEdgeInsets 这种结构体怎么做存储？

### ISSUE THREAD

**Issue by LatteCat** [Tencent/wcdb#535]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.7.5

### The platform of WCDB

> iOS

不做任何转换的话编译会报错，因为 UIEdgeInsets 不是基本数据类型，而且它也没有映射类型

**Comment by ungacy** [comment]
属性改为`NSValue`是否可行?
`
[NSValue valueWithUIEdgeInsets:<#(UIEdgeInsets)#>]
`

**Comment by RingoD** [comment]
Yes, it would be better to store it as `NSObject` class.
