### ISSUE TITLE
WCDB.swift 如何与 FMDB/SQLCipher 共存？

### ISSUE THREAD

**Issue by niuxinhuai** [Tencent/wcdb#536]
### The language of WCDB

>  Swift 4.2

### The version of WCDB

>  v1.0.8.2

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

WCDB.swift has been used in the project for database operations. Now, a flutter embedded in the project needs to use sqflite for database operations. Flutter needs to use FMDB/SQLCipher for database decryption to operate. When I try to join them through pod, the pod reports incorrectly. The prompt is error: [!] The 'Pods-FmdbDemo' target has frameworks with conflicting names: sqlcipher, how should I operate, thank you

**Comment by waylon-edmodo** [comment]
兄弟如何解决的。

**Comment by niuxinhuai** [comment]
我出现的情况是1.我在swift项目中使用的是wcdb.swift
2.现在需求内嵌flutter项目，但是flutter项目操作数据库是通过sqflite(sqflite内嵌的是FMDB)，
3.解决冲突就是我把sqflite中的FMDB给删除掉了，替换为wcdb.swift




------------------ 原始邮件 ------------------
发件人: "waylon"<notifications@github.com>; 
发送时间: 2019年8月1日(星期四) 上午10:19
收件人: "Tencent/wcdb"<wcdb@noreply.github.com>; 
抄送: "灯红酒绿映不出的落寞ゝ"<1242537720@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [Tencent/wcdb] WCDB.swift 如何与 FMDB/SQLCipher 共存？ (#536)




兄弟如何解决的。

**Comment by waylon-edmodo** [comment]
谢谢回复，回复好快。
难道只能把fmdb的sqlcipber指向到wcdb的sqlcipher中。我们希望能够不改fmdb这种第三方库本身的依赖，因为万一以后还有其他第三方库也引入了sqlcipher，还得改，有点麻烦。

**Comment by niuxinhuai** [comment]
是的，存在的一个问题是wcdb中使用的sqlcipher是内嵌的，相当于他们重写了一套，你说的这种指向，不知道可行性为多少，我没有尝试过，祝你好运哇



------------------ 原始邮件 ------------------
发件人: "waylon"<notifications@github.com>; 
发送时间: 2019年8月1日(星期四) 上午10:32
收件人: "Tencent/wcdb"<wcdb@noreply.github.com>; 
抄送: "灯红酒绿映不出的落寞ゝ"<1242537720@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [Tencent/wcdb] WCDB.swift 如何与 FMDB/SQLCipher 共存？ (#536)




谢谢回复，回复好快。
 难道只能把fmdb的sqlcipber指向到wcdb的sqlcipher中。我们希望能够不改fmdb这种第三方库本身的依赖，因为万一以后还有其他第三方库也引入了sqlcipher，还得改，有点麻烦。

**Comment by waylon-edmodo** [comment]
嗯。他们已经把wcdb的sqlciper拆出来了，目前可以单独pod引入。

**Comment by niuxinhuai** [comment]
嗯嗯，加油



------------------ 原始邮件 ------------------
发件人: "waylon"<notifications@github.com>; 
发送时间: 2019年8月1日(星期四) 上午10:48
收件人: "Tencent/wcdb"<wcdb@noreply.github.com>; 
抄送: "灯红酒绿映不出的落寞ゝ"<1242537720@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [Tencent/wcdb] WCDB.swift 如何与 FMDB/SQLCipher 共存？ (#536)




嗯。他们已经把wcdb的sqlciper拆出来了，目前可以单独pod引入。
