### ISSUE TITLE
how to do `insert or ignore` function

### ISSUE THREAD

**Issue by dourgulf** [Tencent/wcdb#537]
### The language of WCDB
Objective-C

### The version of WCDB
WCDB (1.0.7.4)

### The platform of WCDB
iOS

### The installation of WCDB
CocoaPods

### What's the issue?

My table(message) have an auto increase field (msgid) and a unique index field(seq)， every time insert a new message, I will get the msgid from `lastInsertedRowID` property. I wan to insert or ignore if seq is duplicated. 

What I have try:
1. use insertOrReplace interface, it is really what I want, I don't want to replace, I want ignore it.
2. use WCDB::StatementInsert and exec interface, but I can't got `lastInsertedRowID` as the correct msgid any more.

=====中文说明我的问题=====
我有一个叫message的表，有一个叫msgid的字段，是自增主键；还有一个唯一索引字段seq。
每次插入新消息的时候，通过lastInsertedRowID得知插入的自增msgid的值。同时，我希望如果seq重复的情况，不要插入（不要替换）
我尝试了一些办法：
1. 使用insertOrReplaceObject接口，这个接口在主键重复的时候会替换记录，这不是我期望的
2. 使用StatementInsert自己执行insert or ignore是可以的，但是，这个方法无法得到`lastInsertedRowID`了。

**Comment by dourgulf** [comment]
根据QQ群上的一些建议使用：

**Comment by dourgulf** [comment]
看起来WCDB_MULTI_UNIQUE_CONFLICT应该是正确的用法，只可惜WCDB依赖的SQLCipher使用的sqlite版本太低。并不能正确的支持这个扩展。而且这个依赖看起来是一个强依赖。。。

**Comment by RingoD** [comment]
In the current version of WCDB, you can do this through "core interface" by calling `execute:` with your own statement.

**Comment by dourgulf** [comment]
@RingoD  Yes,  I can use core interface to construct an "insert or ignore" statement, but the sqlite version which WCDB using is  "3.15.2"("2016-11-28 19:13:37 bbd85d235f7037c6a033a9690534391ffeacecc8"). But, "insert or ignore" statement require sqlite version "3.24.0 (2018-06-04)" (https://sqlite.org/lang_conflict.html). So, current WCDB execute "insert or ignore" will return error (not ignore and return success). And, return error will cause much performance overhead than "ignore".

中文翻译（以免我的英文写的不准）：是的，我可以用core interface 自己构造“insert or ignore”语句。但是，WCDB自带的sqlite版本是3.15.2，而sqlite的“insert or ignore”功能是在3.24.0版本之后才支持的。所以，就算我可以构造insert or ignore的查询语句，执行的时候sqlite还是返回了错误状态而不是ignore并且成功。返回错误状态的性能开销是比ignore要大一些的。

**Comment by dourgulf** [comment]
@RingoD Can I upgrade the sqlite source by myself? Is WCDB do much modify on original sqlite ?

**Comment by RingoD** [comment]
Using custom SQLite is not tested. Developers should be very careful to do so.

SQLite will be upgraded in the next release.

Currently, I think you can use the raw `insert` and ignoring the error message.

**Comment by dourgulf** [comment]
OK, thanks for your help. Very except for the next release:)
