### ISSUE TITLE
cocoapods 安装 WCDB 后编译不通过

### ISSUE THREAD

**Issue by gongchen94** [Tencent/wcdb#539]
### The language of WCDB

Objective-C

### The version of WCDB

1.0.7.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

Failed building target SQLiteRepairKit
fatal error: module map file '.../Pods/Headers/Public/sqlcipher/WCDBOptimizedSQLCipher.modulemap' not found

**Comment by RingoD** [comment]
I don't think it should be a WCDB issue since v1.0.7.5 is released for a long time.

I think you should first upgrade to the latest version and find why it failed.

**Comment by RingoD** [comment]
no reply.
