### ISSUE TITLE
SQLCipher升级到WCDB关于方法getWritableDatabase的问题

### ISSUE THREAD

**Issue by watchforjz** [Tencent/wcdb#54]
SQLCipher原来有一个函数getWritableDatabase(password)，WCDB文档中显示只保留了无参数的getWritableDatabase。是不是WCDB只支持使用openOrCreateDatabase的方式创建访问加密数据库了？SQLiteOpenHelper仅仅用于不加密的数据库创建和打开？

**Comment by John-He-928** [comment]
`SQLiteOpenHelper` 提供了带密钥版本的构造函数。

[API 文档](https://tencent.github.io/wcdb/references/android/reference/com/tencent/wcdb/database/SQLiteOpenHelper.html)

**Comment by watchforjz** [comment]
刚才详细读了一下文档，应该是方式变了，确实可以通过构造函数传密码使用SQLiteOpenHelper的，谢谢。
