### ISSUE TITLE
Carthage build fail with exit code 65

### ISSUE THREAD

**Issue by LarrySue** [Tencent/wcdb#541]
### The language of WCDB
Swift

### The version of WCDB
v1.0.4/1.0.6/1.0.7/1.0.8

### The platform of WCDB
iOS

### The installation of WCDB
Carthage

### What's the issue?

Always fail when I try to build with Carthage, error code 65

I tried the following build environment

swift 5.1 (Xcode 11.0 Beta2 11M337n)
swift 5.0.1 (Xcode 10.2.1 10E1001)
swift 4.2 (toolchain ID:org.swift.42201809120a)
swift 4.2.4 (toolchain ID:org.swift.42420190329a)

I tried the following command

% carthage update
% carthage update --platform iOS
% carthage update --platform iOS --no-use-binaries
% carthage update --platform iOS --no-use-binaries --toolchain <swift toolchain id> 

and tried the following WCDB version

v1.0.4
v1.0.6
v1.0.7
v1.0.8

**Comment by RingoD** [comment]
So where is the error message?

**Comment by LarrySue** [comment]
carthage update --platform iOS --no-use-binaries --toolchain org.swift.42201809120a

*** Fetching WCDB
*** Checking out WCDB at "v1.0.8"
*** xcodebuild output can be found in /var/folders/hh/y9ttl0_x2h369kj4t2drks740000gn/T/carthage-xcodebuild.5QV84i.log
*** Building scheme "WCDB.swift" in WCDB.xcworkspace

Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/iBreezearrow/Desktop/Carthage/Carthage/Checkouts/WCDB/WCDB.xcworkspace -scheme WCDB.swift -configuration Release -derivedDataPath /Users/iBreezearrow/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11M337n/WCDB/v1.0.8 -sdk iphoneos -toolchain org.swift.42201809120a ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/hh/y9ttl0_x2h369kj4t2drks740000gn/T/WCDB SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/iBreezearrow/Desktop/Carthage/Carthage/Checkouts/WCDB)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/hh/y9ttl0_x2h369kj4t2drks740000gn/T/carthage-xcodebuild.5QV84i.log

**End of the logfile as below:**

ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **


The following build commands failed:
	Ld /Users/iBreezearrow/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11M337n/WCDB/v1.0.8/Build/Intermediates.noindex/ArchiveIntermediates/WCDB.swift/IntermediateBuildFilesPath/WCDB.swift.build/Release-iphoneos/WCDB.swift.build/Objects-normal/arm64/Binary/WCDBSwift normal arm64
(1 failure)

**Comment by RingoD** [comment]
Change the toolchain and check if it still fail.

**Comment by LarrySue** [comment]
I tried the following toolchain versions

4.2 org.swift.42201809120a
4.2.1 org.swift.42120181030a
4.2.2 org.swift.42220190204a
4.2.3 org.swift.42320190228a
4.2.4 org.swift.42420190329a

get the same error

**Comment by RingoD** [comment]
Why not use the original toolchain within Xcode stable version?
