### ISSUE TITLE
can't open encrypted db via static framework package

### ISSUE THREAD

**Issue by amiliry** [Tencent/wcdb#542]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.7.5

### The platform of WCDB

> iOS

### The installation of WCDB

> static framework, and I use private pod spec to manage the framework

### What's the issue?

> 1, I checkouted the WCDB project via tag '1.0.8.2'
> 2, open this project :
![屏幕快照 2019-06-24 下午3 28 52](https://user-images.githubusercontent.com/15916738/60061192-ae47c000-9726-11e9-8470-657ed6ac729b.png)
> 3, I builded it, got two framework packages in Release-iphoneos and Release-iphonesimulator, then I merged them, and put them into local private pod spec project
![屏幕快照 2019-06-24 下午3 29 17](https://user-images.githubusercontent.com/15916738/60061402-9de41500-9727-11e9-8b0b-3c24d7caa255.png)
![Screen Shot 2019-06-24 at 3 25 37 PM](https://user-images.githubusercontent.com/15916738/60061420-b3f1d580-9727-11e9-8481-66c23a5b7c49.png)
> 4, and there is the problem: When I introducing the WCDB via private spec, run my main project, while run succeed, I can't got the data of encrypted database, the error logs are as follow: 
![Screen Shot 2019-06-14 at 4 14 51 PM](https://user-images.githubusercontent.com/15916738/60061590-4f834600-9728-11e9-9c8e-6137bb2a5337.png)
it seems like something error on cipher, the encrypted database cannot be parsed? 
Could you help me to find what's wrong in the process above?
Thank you.

**Comment by amiliry** [comment]
I tried the other two ways: cocoaPod and static .a package, all run succeed and can got right data

**Comment by cntrump** [comment]
```c
#ifdef WCDB_BUILTIN_SQLCIPHER
#include <sqlcipher/sqlite3.h>
#else  //WCDB_BUILTIN_SQLCIPHER
#include <sqlite3.h>
#endif //WCDB_BUILTIN_SQLCIPHER
```

by default, `WCDB_BUILTIN_SQLCIPHER ` is not defined.

**Comment by RingoD** [comment]
So I think it may not be a WCDB issue. Maybe you should find out what you did wrong while merging two static frameworks.

**Comment by RingoD** [comment]
no reply.
