### ISSUE TITLE
前缀匹配过度命中，比如“你你*”可以match到“你好”

### ISSUE THREAD

**Issue by risechen** [Tencent/wcdb#543]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
Java

### The version of WCDB

> e.g. v1.0.5
v1.0.8

### The platform of WCDB

> e.g. iOS, macOS or Android

Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
AAR

### What's the issue?
使用了前缀匹配后会出现过度命中，比如文档内容是“你好啊”，输入“你你”也能命中

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
