### ISSUE TITLE
virtual table insert crash

### ISSUE THREAD

**Issue by batmanbiu** [Tencent/wcdb#548]
### The language of WCDB

 Java 

### The version of WCDB

v1.0.8

### The platform of WCDB

 Android

### The installation of WCDB

Maven

### What's the issue?

Insert into virtual table causes crash,

com_tencent_wcdb_database_SQLiteConnection.cpp:301: void wcdb::emitUpdateNotifications(JNIEnv *, wcdb::SQLiteConnection *): assertion "op >= 0 && op < 3" failed

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
