### ISSUE TITLE
Always got error: no such table test but it exists

### ISSUE THREAD

**Issue by qhhonx** [Tencent/wcdb#551]
### The language of WCDB

> Kotlin/Native -> C++ -> libWCDBOptimizedSQLCipher.a

### The version of WCDB

> WCDBOptimizedSQLCipher v1.2.1

### The platform of WCDB

> macOS

### The installation of WCDB

> direct to link libWCDBOptimizedSQLCipher.a which generated by Xcode build tooling

### What's the issue?

> I wrote a program that direct to link libWCDBOptimizedSQLCipher consisting of all native archs which generated by Xcode build tooling.

> After created a table 'test' in program, when execute a statement like `select * from test` it got error: no such table test. However, the test table exists by using other tool. Actually, whatever a statement such as `select` or `insert` executed, it always go above error message. I am ensure that each time before executing `select` or `insert` the test table existed.

> The program wrote by C++ and calling by Kotlin/Native that direct to invoke sqlite3 APIs. I mean it is not Kotlin/Native fault. If the program direct to link system sqlite library such as `-lsqlite` or user installed official sqlicipher library such as `-lsqlcipher`, all above errors disappeared. BTW, my colleague run his correct rust program to test by linking libWCDBOptimizedSQLCipher.a library, he also got above error except for linking `-lsqlite` or `-lsqlcipher`.

> The program is very simple that has no setup key and create a table test each time before execute a `select/insert` statement. I knew that libWCDBOptimizedSQLCipher.a is just much optimized sqlcipher library that is compatible with sqlite APIs. 

> So, whether if I missing some configuration for  libWCDBOptimizedSQLCipher.a that be linked directly by the program?

Chinese
> 今天使用测试程序直接调用sqlite3提供的API操作，成功创建test表后执行select * from test;后报错: no such table test，但通过工具查看该数据库其实是有test表。实际上，在创建test表成功后，无论执行select还是insert操作，报错都是no such table test。

> 测试程序是通过Kotlin/Native调C++ API，而C++里直接调用sqlite3 API，可以理解成直接使用C++调sqlite3出现了上述问题。
测试程序直接链接了libWCDBOptimizedSQLCipher.a库，该库是通过XCode工具链build而成。

> 但是，如果我直接链接系统-lsqlite库或官方-lsqlcipher库，测试程序就不会出现上述问题，且能正常运行。

> 所以，我的问题是链接了libWCDBOptimizedSQLCipher.a库后，是否需要有一些额外的配置，才能正常运行？

**Comment by RingoD** [comment]
It's not the recommended usage of WCDB. So there is no promise that it will be run correctly.

Could you please provide the sample code or the demo project?

**Comment by qhhonx** [comment]
> It's not the recommended usage of WCDB. So there is no promise that it will be run correctly.
> 
> Could you please provide the sample code or the demo project?

We want to integrate WCDB optimized sqlcipher directly, because WCDB high abstraction is useless for us in terms of our development that depends on [SQLiteConnection.cpp](https://github.com/qhhonx/SQLiter/blob/adopt-sqlcipher/KotlinCpp/knarch/src/main/cpp/SQLiteConnection.cpp) which direct to interact sqlite3 API. We knew that WCDB optimized sqlcipher keeps the same API with official sqlite3 that replacing `-lsqlite3` with `-lWCDBOptimizedSQLCipher` is feasible.

### Update
I forked [qhhonx/sqlcipher](https://github.com/qhhonx/sqlcipher/tree/make-wcdb) from [Tencent/sqlcipher](https://github.com/Tencent/sqlcipher/tree/wcdb) and built sqlcipher library in Xcode project or Makefile directly. After linking the produced library `libsqlcipher.a`, all above issues disappeared. 

Unfortunately, there is another problem that the built `libsqlcipher.a` not supported multiple connections for `file:dbname?mode=memory&cache=shared`. It means that created a table `test` through opening A connection and then inserted a record into table `test` through opening B connection, however, the later operation is failed with message: **no such table test**. Both A and B connection are opened by `file:dbname?mode=memory&cache=shared` that they should share the same memory database according to https://www.sqlite.org/inmemorydb.html.

My sample project is simple but setting up environment is complex that needs to setup Kotlin/Native development environment. The sample code is in [sample-test-for-sqlcipher](https://github.com/qhhonx/SQLiter/commits/sample-test-for-sqlcipher), you can clone it and just execute `./runtest.sh` to see some missing environments.

**Comment by RingoD** [comment]
It's not recommended to enable shared memory mode in iOS/macOS according to the past SQLite mail list.
It will result in poor performance due to too many mutexes.

As for the issue of multiple connection pools, I think you forget to set up the `SQLITE_THREADSAFE` config.

**Comment by qhhonx** [comment]
> It's not recommended to enable shared memory mode in iOS/macOS according to the past SQLite mail list.
> It will result in poor performance due to too many mutexes.

Thanks for your advice and we have not considered that using shared memory mode in production. It is just unit test case for one situation in [DatabaseConnectionTest.kt#L242](https://github.com/qhhonx/SQLiter/blob/e967e709feff971bdbfedb2b7e4c45e64b8e3b81/SQLiter/src/nativeCommonTest/kotlin/co/touchlab/sqliter/DatabaseConnectionTest.kt#L242).

> As for the issue of multiple connection pools, I think you forget to set up the `SQLITE_THREADSAFE` config.

No, we enabled it in [our configure](https://raw.githubusercontent.com/qhhonx/sqlcipher/make-wcdb/configure_wcdb) as below.
```bash
#! /bin/sh

./configure \
--enable-tempstore=yes \
--enable-threadsafe="multi" \
--with-crypto-lib=commoncrypto \
LDFLAGS="-framework Security -framework Foundation" \
CFLAGS="-DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_API_ARMOR -DSQLITE_OMIT_BUILTIN_TEST -DSQLITE_OMIT_AUTORESET -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_LOCKING_STYLE=1 -DSQLITE_SYSTEM_MALLOC -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_CORE -DSQLITE_THREADSAFE=2 -DSQLITE_DEFAULT_CACHE_SIZE=250 -DSQLITE_DEFAULT_CKPTFULLFSYNC=1 -DSQLITE_DEFAULT_PAGE_SIZE=4096 -DSQLITE_OMIT_SHARED_CACHE -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_CC -DUSE_PREAD=1 -DSQLITE_TEMP_STORE=2 -DSQLCIPHER_PREPROCESSED -DHAVE_USLEEP -DSQLITE_MALLOC_SOFT_LIMIT=0 -DSQLITE_WCDB_SIGNAL_RETRY=1 -DSQLITE_DEFAULT_MEMSTATUS=0 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1 -DSQLITE_LIKE_DOESNT_MATCH_BLOBS -DSQLITE_MAX_EXPR_DEPTH=0 -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_PROGRESS_CALLBACK -DSQLITE_OMIT_SHARED_CACHE -DOMIT_CONSTTIME_MEM -DOMIT_MEMLOCK -DSQLITE_ENABLE_FTS3_TOKENIZER -DSQLITE_WCDB_CHECKPOINT_HANDLER -DSQLITE_MMAP_READWRITE -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_FTS5"
```

**Comment by RingoD** [comment]
`./configure` is only for processing. Did you build with `-DSQLITE_THREADSAFE=2`?

**Comment by qhhonx** [comment]
> `./configure` is only for pre-processing. Did you build with `-DSQLITE_THREADSAFE=2`?

I knew the purpose of `./configure`. I mean the above parameters used to configure for generating Makefile. As the parameters show that `-DSQLITE_THREADSAFE=2` is provided.

```
gcc -DSQLITE_SYSTEM_MALLOC -DSQLITE_CORE -DSQLITE_THREADSAFE=2 -DSQLITE_DEFAULT_CACHE_SIZE=250 -DSQLITE_DEFAULT_CKPTFULLFSYNC=1 -DSQLITE_DEFAULT_PAGE_SIZE=4096 -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_CC -DUSE_PREAD=1 -DSQLITE_TEMP_STORE=2 -DSQLCIPHER_PREPROCESSED -DHAVE_USLEEP -DSQLITE_MALLOC_SOFT_LIMIT=0 -DSQLITE_WCDB_SIGNAL_RETRY=1 -DSQLITE_DEFAULT_MEMSTATUS=0 -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1 -DSQLITE_LIKE_DOESNT_MATCH_BLOBS -DSQLITE_MAX_EXPR_DEPTH=0 -DOMIT_CONSTTIME_MEM -DOMIT_MEMLOCK -DSQLITE_WCDB_CHECKPOINT_HANDLER -DSQLITE_MMAP_READWRITE -DSQLCIPHER_CRYPTO_CC -DSQLITE_OS_UNIX=1 -I. -I/Users/hongqinghua/Workbench.local/Github/sqlcipher_wcdb/src -I/Users/hongqinghua/Workbench.local/Github/sqlcipher_wcdb/ext/rtree -I/Users/hongqinghua/Workbench.local/Github/sqlcipher_wcdb/ext/icu -I/Users/hongqinghua/Workbench.local/Github/sqlcipher_wcdb/ext/fts3 -I/Users/hongqinghua/Workbench.local/Github/sqlcipher_wcdb/ext/async -I/Users/hongqinghua/Workbench.local/Github/sqlcipher_wcdb/ext/session -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -DSQLITE_THREADSAFE=2 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_API_ARMOR -DSQLITE_OMIT_BUILTIN_TEST -DSQLITE_OMIT_AUTORESET -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_LOCKING_STYLE=1 -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_OMIT_SHARED_CACHE -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_PROGRESS_CALLBACK -DSQLITE_OMIT_SHARED_CACHE -DSQLITE_ENABLE_FTS3_TOKENIZER -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_FTS5 -DSQLITE_TEMP_STORE=2 -c sqlite3.c  -fno-common -DPIC -o .libs/sqlite3.o
```

**Comment by RingoD** [comment]
Then, it's ok.

If not, you should check the tutorial of SQLite. Or if you think it's a bug, complain to the SQLite staffs.
