### ISSUE TITLE
update set max + 1

### ISSUE THREAD

**Issue by luobin23628** [Tencent/wcdb#552]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.7.5

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
表中的某一列想更新成最大值+1，sql可以做到我想要的效果，但是wcdb不知道该如何实现
`UPDATE notice_conversation SET topIndex = ((SELECT selected_value FROM (SELECT MAX(topIndex) AS selected_value FROM notice_conversation) AS sub_selected_value) + 1) WHERE id = 248`

尝试下面的代码发现不行
`        WCDB::UpdateValueList updateValueList;
        updateValueList.push_back({TXINoticeConversation.topIndex, WCTExpr(TXINoticeConversation.topIndex.max()) + 1});
        WCDB::StatementUpdate statementUpdate = WCDB::StatementUpdate().update(TXI_TABLE_NOTICE_CONVERSATION.UTF8String).set(updateValueList).where(TXINoticeConversation.conversationId == conversation.conversationId);
        WCTStatement *wcStatement = [self.database prepare:statementUpdate];
`

**Comment by luobin23628** [comment]
找到一种实现方式，有没有更好的方式呢，或者可以直接写纯sql？
        WCDB::UpdateValueList updateValueList;
        updateValueList.push_back({TXINoticeConversation.topIndex, WCTExpr("(SELECT selected_value FROM (SELECT MAX(topIndex) AS selected_value FROM notice_conversation) AS sub_selected_value)") + 1});
        WCDB::StatementUpdate statementUpdate = WCDB::StatementUpdate().update(TXI_TABLE_NOTICE_CONVERSATION.UTF8String).set(updateValueList).where(TXINoticeConversation.conversationId == conversation.conversationId);
        WCTStatement *wcStatement = [self.database prepare:statementUpdate];

**Comment by RingoD** [comment]
Pure SQL is not supported here. 

Well, I think your WINQ expression is correct.

**Comment by luobin23628** [comment]
UPDATE notice_conversation SET topIndex=('(SELECT max FROM (SELECT MAX(topIndex) AS max FROM notice_conversation))'+1) WHERE (id=2)
生成的sql多了一个单引号，有办法解决吗

**Comment by luobin23628** [comment]
查看WCDB源代码发现可以通过StatementSelect初始化WCTExpr，但是
        `WCDB::StatementSelect statementSelect = WCDB::StatementSelect().select({TXINoticeConversation.topIndex.max() + 1}).from(TXI_TABLE_NOTICE_CONVERSATION.UTF8String);
        
        WCDB::UpdateValueList updateValueList;
        updateValueList.push_back({TXINoticeConversation.topIndex, WCTExpr(statementSelect)});
        WCDB::StatementUpdate statementUpdate = WCDB::StatementUpdate().update(TXI_TABLE_NOTICE_CONVERSATION.UTF8String).set(updateValueList).where(TXINoticeConversation.conversationId == conversationId);
        WCTStatement *wcStatement = [self.database prepare:statementUpdate];`
但是生成的sql缺少了括号，也没有找到任何可以添加括号的api
UPDATE notice_conversation SET topIndex=SELECT (MAX(topIndex)+1) FROM notice_conversation WHERE (id=3)

**Comment by RingoD** [comment]
Well, That's a bug. We will fix it.

**Comment by Qiuwen-chen** [comment]
Please try the latest version.

**Comment by Kingtous** [comment]
想问下C++怎么做呢？C++貌似没有UpdateValueList
