### ISSUE TITLE
查询String类型字段的最大值

### ISSUE THREAD

**Issue by Archer353** [Tencent/wcdb#555]
### The language of WCDB

> Swift

### The version of WCDB

> 最新版

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

有一个字段为String类型的，但内容是1-100的数，我想查询数据表里，这个字段最大是多少？应该怎么做？

**Comment by RingoD** [comment]
Did you see the sample code in the test case?

**Comment by RingoD** [comment]
no reply.
