### ISSUE TITLE
Android打开数据库的时候报java.lang.NoSuchMethodError: no non-static method "Lcom/tencent/wcdb/database/SQLiteDatabaseCorruptException;.<init>

### ISSUE THREAD

**Issue by risechen** [Tencent/wcdb#556]
07-10 17:39:08.649 10084 10084 E AndroidRuntime: Process: com.g42.im, PID: 10084
07-10 17:39:08.649 10084 10084 E AndroidRuntime: java.lang.RuntimeException: java.lang.NoSuchMethodError: no non-static method "Lcom/tencent/wcdb/database/SQLiteDatabaseCorruptException;.<init>(Ljava/lang/String;)V"
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.yeecall.library.thread.ShowExceptionRunnable$1.run(ShowExceptionRunnable.java:51)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at android.os.Handler.handleCallback(Handler.java:739)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:95)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:171)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at android.app.ActivityThread.main(ActivityThread.java:5728)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at java.lang.reflect.Method.invoke(Native Method)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
07-10 17:39:08.649 10084 10084 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: no non-static method "Lcom/tencent/wcdb/database/SQLiteDatabaseCorruptException;.<init>(Ljava/lang/String;)V"
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.tencent.wcdb.database.SQLiteConnection.nativePrepareStatement(Native Method)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.tencent.wcdb.database.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:996)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.tencent.wcdb.database.SQLiteConnection.executeForString(SQLiteConnection.java:775)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.tencent.wcdb.database.SQLiteConnection.setJournalMode(SQLiteConnection.java:393)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.tencent.wcdb.database.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:383)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:273)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java:238)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.tencent.wcdb.database.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:502)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:216)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java:208)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.tencent.wcdb.database.SQLiteDatabase.openInner(SQLiteDatabase.java:997)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.tencent.wcdb.database.SQLiteDatabase.open(SQLiteDatabase.java:978)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.tencent.wcdb.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:707)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.tencent.wcdb.support.Context.openOrCreateDatabase(Context.java:151)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.tencent.wcdb.database.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:296)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.tencent.wcdb.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:232)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.zayhu.fts.manager.FtsDBDao.getWritableDatabase(FtsDBDao.java:206)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.zayhu.fts.manager.FtsDBDao.clearConvNameIndex(FtsDBDao.java:616)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.zayhu.fts.manager.FtsDBManager.clearConvNameMetaAndIndex(FtsDBManager.java:1079)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.zayhu.fts.manager.FtsBusManager.resetConvNameMetaAndIndex(FtsBusManager.java:544)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.zayhu.fts.manager.FtsBusManager.resetRalationMetaAndIndex(FtsBusManager.java:893)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.zayhu.fts.manager.FtsEventManger$8.runSafe(FtsEventManger.java:337)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.zayhu.base.SafeRunnable.run(SafeRunnable.java:49)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at com.yeecall.library.thread.ShowExceptionRunnable.run(ShowExceptionRunnable.java:40)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at android.os.Handler.handleCallback(Handler.java:739)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:95)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:171)
07-10 17:39:08.649 10084 10084 E AndroidRuntime:  at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Liveinadream** [comment]
同样遇到了这个问题，有没有什么解决方案呐？

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
