### ISSUE TITLE
Is it possible to not use .wal file?

### ISSUE THREAD

**Issue by LakrAream** [Tencent/wcdb#557]
### The language of WCDB
Swift
### The version of WCDB
1.0.8.2
### The platform of WCDB
iOS
### The installation of WCDB
Cocoapods
### What's the issue?
-> When I trying to do a lot of operations in a short time, .wal file grows big and even riches 2GB just in a minute. Can I disable .wal file? If it is not going to happen, how to avoid it becomes such a big guy? I want it to lose weight.

.wal file I meant is someDB.db-wal

**Comment by RingoD** [comment]
Well, I think you should learn about what WAL is and other related things. Then we will talk about disabling WAL.

**Comment by RingoD** [comment]
In WCDB, WAL will be truncate checkpointed when it's idle.

**Comment by LakrAream** [comment]
So I can just leave it there and it will automatically reduce the size of its self right?

**Comment by RingoD** [comment]
Yes.

**Comment by LakrAream** [comment]
So I can just leave it there and it will automatically reduce the size of its self right?
