### ISSUE TITLE
同时使用系统的sqlite3和wcdb是不是会有冲突？

### ISSUE THREAD

**Issue by SuiFeng** [Tencent/wcdb#558]
### The language of WCDB

Objective-C

### The version of WCDB

1.0.7.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

目前线上我们大量遇到 https://github.com/Tencent/wcdb/issues/451 一样的问题，因为我们工程里面同时使用了sqlite3和wcdb，是不是由于函数名字相同的问题，导致了这些crash？

**Comment by RingoD** [comment]
It's obvious that using the same C library within one mach-o.

But I have no idea about whether it's related to #451.

**Comment by SuiFeng** [comment]
因为我们的crash堆栈和 #451 是一样的。

另外，我们既然重构了sqlite，为什么不把相关的函数名字也进行重新命名呢？

**Comment by RingoD** [comment]
We didn't refactor SQLite. We just do some optimization.

It's the responsibility of developers not to link duplicated symbols. Not only when using WCDB, but also using all libraries. As for WCDB, it's introduced at the first line of documentation that it's a SQLite based library.

To avoid duplicated symbols, there's a lot of solutions - dynamic libraries, hidden symbols and so on. Also, it's developer's choice.

**Comment by stupidchou** [comment]
NSString sql = [NSString stringWithFormat：@“SELECT tmsDistributeList。，tmsInterceptList.interceptType，tmsInterceptList.remarkInfo FROM tmsDistributeList LEFT JOIN tmsInterceptList ON tmsDistributeList.mailNo = tmsInterceptList.mailNo WHERE status = 0 AND loginAccount ='％@'AND commonAddress ='％@ 'ORDER BY distributeTime DESC“，[WGUser sharedUser] .mobile，obj]; 
我这样的sql想用wcdb左表关联的方式实现，怎么写呢，我用这样写，发现没办法去从表中取数据的时候做排序NSArray *arr =  [[WGOrderManagement sharedOrderManager] resultMultiObjectsOnResults:{WGDistributeListModel.commonAddress.inTable(tmsDistributeListTable),WGInterceptModel.interceptType.inTable(tmsInterceptListTable),WGInterceptModel.remarkInfo.inTable(tmsInterceptListTable)} fromTables:@[tmsDistributeListTable,tmsInterceptListTable] where:WGDistributeListModel.mailNo == WGInterceptModel.mailNo&& WGDistributeListModel.status == 0&&WGDistributeListModel.loginAccount == [WGUser sharedUser].mobile];你知道有没有好的方案呢

**Comment by RingoD** [comment]
You can print the sql string and check if it's correct.

**Comment by RingoD** [comment]
no reply.
