### ISSUE TITLE
有没有计划把RepairKit独立出来？

### ISSUE THREAD

**Issue by eggInBlack** [Tencent/wcdb#559]
### The language of WCDB

> Objective-C

### The version of WCDB

>  v1.0.5

### The platform of WCDB

> iOS

### The installation of WCDB

>  Cocoapods

### What's the issue?

有没有计划把RepairKit独立出来？

**Comment by RingoD** [comment]
What do you mean about 'separate RepairKit'?

**Comment by eggInBlack** [comment]
It means that we want to use backup and recovery only。F.E, FMDB+RepairKit

**Comment by RingoD** [comment]
The source code is lying at the root folder of the repo. You can use it freely.

**Comment by RingoD** [comment]
no reply.
