### ISSUE TITLE
iOS中复合主键，单字段自增的问题

### ISSUE THREAD

**Issue by LongTimeNoSeee** [Tencent/wcdb#56]
只有一个主键的时候，看到自增的方法：WCDB_PRIMARY_AUTO_INCREMENT，请问复合主键中，单个字段自增应该怎么设置呢

**Comment by RingoD** [comment]
请参考：https://github.com/Tencent/wcdb/wiki/ORM使用教程#表约束

**Comment by LongTimeNoSeee** [comment]
回复很快！你好，请问WCDB_MULTI_PRIMARY_ASC和WCDB_MULTI_PRIMARY_DESC这两个方法的作用是什么呢，是用于数据库排序？和数据库某一主键自增没有关系吧，我在API中只看到了单主键自增的接口，没有看到复合主键中某一主键自增的API。

**Comment by RingoD** [comment]
不好意思，看错了，我以为是复合主键排序。

按照SQLite的语法，复合主键应该是不支持单字段自增的。参考：http://www.sqlite.org/lang_createtable.html

能否给一些你所说的SQL？

**Comment by LongTimeNoSeee** [comment]
你好，之前用的数据库设计工具设计的数据库，复制出sql，在SQLite下确实执行报错，看来这种情况可能并不支持。
