### ISSUE TITLE
WCDB_CHECK限制怎么写？

### ISSUE THREAD

**Issue by willing8310** [Tencent/wcdb#561]
### The language of WCDB

>  Objective-C 

### The version of WCDB

>  v1.0.7.5

### The platform of WCDB

> iOS

### The installation of WCDB

>  Cocoapods

### What's the issue?

请问WCDB_CHECK这个宏第三个参数应该应该怎么写，我想限制表格中uid（int类型）不能存储小于0的值，谢谢。

**Comment by RingoD** [comment]
Just write it and show the error if it fails.

**Comment by RingoD** [comment]
no reply.
