### ISSUE TITLE
(Objective-C)有没有"更新除了主键外所有字段"的便捷写法?类似AllProperties这种

### ISSUE THREAD

**Issue by JsonKit** [Tencent/wcdb#563]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
`WCTProperties` is basically a `std::list` class in C++ STL. Developers can operate it freely.

Considering that most of the iOS developers is unfamiliar to C++, we will add some convenient interfaces in the next release.

**Comment by RingoD** [comment]
no reply.
