### ISSUE TITLE
WCDB关于表的关联

### ISSUE THREAD

**Issue by stupidchou** [Tencent/wcdb#566]
NSString sql = [NSString stringWithFormat：@“SELECT tmsDistributeList。，tmsInterceptList.interceptType，tmsInterceptList.remarkInfo FROM tmsDistributeList LEFT JOIN tmsInterceptList ON tmsDistributeList.mailNo = tmsInterceptList.mailNo WHERE status = 0 AND loginAccount ='％@'AND commonAddress ='％@ 'ORDER BY distributeTime DESC“，[WGUser sharedUser] .mobile，obj]; 
我这样的sql想用wcdb左表关联的方式实现，使用你们的多表联查是不是不能满足呢，我发现你们的api里面没有关于多表联查还带排序的功能。能帮帮我吗？

**Comment by stupidchou** [comment]
有没有知道的呢

**Comment by stupidchou** [comment]
提问题没有用？没人回复？

**Comment by RingoD** [comment]
I think the wiki shows the way that how to write a WINQ.

**Comment by RingoD** [comment]
no reply.
