### ISSUE TITLE
WCDB 集成问题

### ISSUE THREAD

**Issue by Tonigt** [Tencent/wcdb#568]
platform Xcode 10.3，swift version 4.2 ，ios 10  ，WCDB 1.0.7.5
error message ：

1、Value of optional type 'UnsafePointer<Int8>?' must be unwrapped to a value of type 'UnsafePointer<Int8>'

2、Redundant conformance of 'Array<Element>' to protocol 'ColumnCodableBase'
3、Redundant conformance of 'Dictionary<Key, Value>' to protocol 'ColumnCodableBase'
4、Redundant conformance of 'Set<Element>' to protocol 'ColumnCodableBase'

**Comment by RingoD** [comment]
Check the release note and upgrade to the newest version.
