### ISSUE TITLE
Problem with highlighting errors/ warnings in jetbrains AppCode source editor for WCDB_IMPLEMENTATION WCDB_SYNTHESIZE 

### ISSUE THREAD

**Issue by zhenian** [Tencent/wcdb#569]
### The language of WCDB

> Objective-C

### The version of WCDB

> pod 'WCDB', '~> 1.0.7.5'

### The platform of WCDB
> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

![image](https://user-images.githubusercontent.com/18303646/62287988-ef519380-b48d-11e9-9523-09881ef1665f.png)

> like image

**Comment by RingoD** [comment]
Will Xcode produce the same errors?

**Comment by zhenian** [comment]
> Will Xcode produce the same errors?

NO. 

emm... that's a bug of AppCode
