### ISSUE TITLE
iOS 属性默认值的设置

### ISSUE THREAD

**Issue by LongTimeNoSeee** [Tencent/wcdb#57]
iOS中 WCDB_SYNTHESIZE_DEFAULT(className, propertyName, defaultValue)  方法可以设置默认值的，请问如果defaultValue为一个方法呢？比如时间戳：CURRENT_TIMESTAMP

**Comment by RingoD** [comment]
`CURRENT_TIMESTAMP`, `CURRENT_TIME`, `CURRENT_DATE`暂不支持。其实可以在插入时用`[NSDate date]`代替。

我稍后加上这三种默认值。是否还存在其他默认需要添加的？

**Comment by LongTimeNoSeee** [comment]
暂未发现，多谢解答。

**Comment by LongTimeNoSeee** [comment]
你好，这个默认值的话是可以用Object-C方法直接设置的，是吧？

**Comment by RingoD** [comment]
已添加，请参考：https://github.com/Tencent/wcdb/blob/2974a18b7be30a41d1f5838aa3b457f89afe9b30/apple/sample/orm/WCTSampleORM.mm

**Comment by LongTimeNoSeee** [comment]
多谢解答

**Comment by iOkay** [comment]
2.1.13版本如何设置默认时间
