### ISSUE TITLE
getTableOfName:withClass: performance

### ISSUE THREAD

**Issue by ElfSundae** [Tencent/wcdb#570]
## WCDB
v1.0.7.5 , iOS , ObjC 

我刚开始用 WCDB 。
我注意到 `getTableOfName` 方法内部调用了 `isTableExists` 方法：

```objc
- (WCTTable *)getTableOfName:(NSString *)tableName withClass:(Class<WCTTableCoding>)cls
{
    WCDB::Error innerError;
    if ([self isTableExists:tableName withError:innerError]) {
        return [[WCTTable alloc] initWithCore:_core andTableName:tableName andClass:cls];
    }
    return nil;
}
```

而 `isTableExists` 执行了 SQL `SELECT 1 FROM table LIMIT 0` , 想请教下这样是不是有性能问题？个人觉得如果没有特殊原因的话，判断表存在性 应该交由调用方处理。

使用 getTableOfName 主要是为了省略 `ofClass:` `fromTable:` ，更方便（简短）的写 CRUD，如果代价是多一次查询表存在性的话，我觉得还不如直接用 WCTDatabase 的 CRUD 方法。

**Comment by RingoD** [comment]
You are right. We remove the `tableExists` method from the `getTable` method in our new code(in branch `pre_v1.1.0`.

Currently, you can get `WCTTable` and reuse it, without calling `getTable` duplicately.

**Comment by ElfSundae** [comment]
Great! 👍 I currently swizzled the `getTableOfName:withClass:` method:

```objc
- (WCTTable *)rim_getTableOfName:(NSString *)tableName withClass:(Class<WCTTableCoding>)cls
{
    return [[WCTTable alloc] initWithCore:_core andTableName:tableName andClass:cls];
}
```

BTW, if I hold the returned table instance, will the database instance be implicitly retained?

**Comment by RingoD** [comment]
>  if I hold the returned table instance, will the database instance be implicitly retained?

Yes, it will, though it makes nothing bad.

**Comment by ElfSundae** [comment]
OK, thanks.
