### ISSUE TITLE
Android libwcdb native crash

### ISSUE THREAD

**Issue by twlkyao** [Tencent/wcdb#571]
### The language of WCDB

>Java

### The version of WCDB

>v1.0.8

### The platform of WCDB

>Android

### The installation of WCDB

> AAR Package

### What's the issue?

> Post the outputs or screenshots for errors.
>  signal 4(SIGILL), code 1(ILL_ILLOPC)
/data/app/com.mm.android.live/lib/arm/libwcdb.so 0x868a8
/data/app/com.mm.android.live/lib/arm/libwcdb.so 0x12125
/system/lib/libc.so 0x19b9c
/data/app/com.mm.android.live/lib/arm/libwcdb.so 0x89e0d
/system/lib/libc.so 0x7e8c1 je_realloc 0x5f4 0x1b14
/data/app/com.mm.android.live/lib/arm/libwcdb.so 0x186bd
/data/app/com.mm.android.live/lib/arm/libwcdb.so 0xc79a2
/data/app/com.mm.android.live/lib/arm/libwcdb.so 0x11f15
/system/bin/linker 0xaa7c2
/data/app/com.mm.android.live/lib/arm/libwcdb.so 0x11f2d
/system/bin/linker 0x188fd __dl__ZL10call_arrayIPFviPPcS1_EEvPKcPT_jbS5_ 0xbc 0x168
/system/bin/linker 0x87079 __dl__Z18bionic_trace_beginPKc 0xf0 0x414
/system/bin/linker 0x18b21 __dl__ZN6soinfo17call_constructorsEv 0x178 0x244
/system/bin/linker 0xa971 __dl__Z9do_dlopenPKciPK17android_dlextinfoPKv 0x400 0x730
/data/app/com.mm.android.live/lib/arm/libwcdb.so 0x2115
/system/lib/libandroid_runtime.so 0x12eaf8 __gnu_ldivmod_helper 0x14 0x3c
/system/lib/libandroid_runtime.so 0x12e9d8
/system/lib/libc.so 0x263d1 _Z6StrToIIxLxn9223372036854775808ELx9223372036854775807EET_PKcPPci 0xe2 0x1c2
/system/lib/libcutils.so 0x9353 property_get_int32 0x8a 0xdc
/system/lib/libart.so 0x2e42a7 _ZN3art14DexFile_HotfixEPKc 0x36 0x1cc
/system/framework/arm/boot-framework.oat 0x5a5e69

**Comment by twlkyao** [comment]
load libwcdb时crash

**Comment by twlkyao** [comment]
请问有进展么

**Comment by OPHsysbilla** [comment]
遇到了同样的问题

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
