### ISSUE TITLE
com.tencent.wcdb.database.SQLiteException: Failed to register SQLite functions

### ISSUE THREAD

**Issue by xieningtao** [Tencent/wcdb#572]
FATAL EXCEPTION: ThreadHelp #1 Process: com.netease.huatian, PID: 32136 com.tencent.wcdb.database.SQLiteException: Failed to register SQLite functions: not an error, ErrCode: 1 (code 1, errno -1): Database connection initializer failed. at com.tencent.wcdb.database.SQLiteConnection.nativeOpen(Native Method) at com.tencent.wcdb.database.SQLiteConnection.open(SourceFile:254) at com.tencent.wcdb.database.SQLiteConnection.open(SourceFile:238) at com.tencent.wcdb.database.SQLiteConnectionPool.openConnectionLocked(SourceFile:502) at com.tencent.wcdb.database.SQLiteConnectionPool.open(SourceFile:216) at com.tencent.wcdb.database.SQLiteConnectionPool.open(SourceFile:208) at com.tencent.wcdb.database.SQLiteDatabase.openInner(SourceFile:997) at com.tencent.wcdb.database.SQLiteDatabase.open(SourceFile:978) at com.tencent.wcdb.database.SQLiteDatabase.openDatabase(SourceFile:707) at com.tencent.wcdb.support.Context.openOrCreateDatabase(SourceFile:151) at com.tencent.wcdb.database.SQLiteOpenHelper.getDatabaseLocked(SourceFile:296) at com.tencent.wcdb.database.SQLiteOpenHelper.getWritableDatabase(SourceFile:232) at com.netease.huatian.provider.BaseContentProvider.update(SourceFile:153) at android.content.ContentProvider$Transport.update(ContentProvider.java:432) at android.content.ContentResolver.update(ContentResolver.java:2017) at com.netease.huatian.module.conversation.MessageHelper.b(SourceFile:415) at com.netease.huatian.module.welcome.WelcomeActivity$4.run(SourceFile:271) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:919)

**Comment by xieningtao** [comment]
does someone handle this problem?

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
