### ISSUE TITLE
iOS 在锁屏状态下操作数据库闪退

### ISSUE THREAD

**Issue by MerlinOnline** [Tencent/wcdb#575]
【BUG】iOS 在锁屏状态下操作数据库闪退
** was compiled with optimization - stepping may behave oddly; variables may not be available.

**Comment by RingoD** [comment]
So where is the crash info and stack dump?

**Comment by MerlinOnline** [comment]
![image](https://user-images.githubusercontent.com/12826444/62701779-b712fd80-ba17-11e9-9657-69a9b33b474c.png)
这个是我的闪退截图

**Comment by RingoD** [comment]
Try setting file protection to none for your `-shm` file.

**Comment by MerlinOnline** [comment]
我已经将-shm的NSFileProtectionKey设置为NSFileProtectionNone，但是还是会闪退哦。

**Comment by RingoD** [comment]
Then I think we need a full crash stack(including crash analysis) to go on.

**Comment by yaomars** [comment]
@MerlinOnline 这个问题，你这边解决了吗？我也同样遇到了。

**Comment by chengssir** [comment]
为什么关闭了这个问题？很明显还没有解决问题呢？
