### ISSUE TITLE
Question: Is it safe to keep database opening during the whole app lifecycle?

### ISSUE THREAD

**Issue by ElfSundae** [Tencent/wcdb#576]
> WCDB v1.0.7.5, ObjC, iOS

I use WCDB in an IM app, for performance purpose, I hold the WCTDatabase instance in a singleton manager, and the database will never be closed since I did not release the shared database instance during the whole life cycle of my app. I'm not sure is it safe for my data.

Every time when I opening the database, an error has occurred since the database was not properly closed previously:
```
Code:283, Type:SQLiteGlobal, Msg:recovered 20 frames from WAL file /var/.../IM.db-wal
```
According to the SQLite doc:
```
(283) SQLITE_NOTICE_RECOVER_WAL
The SQLITE_NOTICE_RECOVER_WAL result code is passed to the callback of sqlite3_log() when a WAL mode database file is recovered.
```

I am not familiar with SQLite, should I do something or just ignore this error?

**Comment by ElfSundae** [comment]
Is there any method to detect whether the database status is _idle_, ie. no current or pending operations?

**Comment by RingoD** [comment]
Yes, you can ignore it and we will remove this hint in the next release.

Or you can simply google it to learn more technical infos about it.

**Comment by ElfSundae** [comment]
@RingoD Thank you, I googled and it seems okay, can't wait for v1.1 😄
