### ISSUE TITLE
如何将OC字符串表示的字段名转成WCTProperty?

### ISSUE THREAD

**Issue by JsonKit** [Tencent/wcdb#577]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

+ (BOOL)updateProperties:(NSArray<NSString *> *)properties withProject:(JGJWCTProject *)project
{
    WCTPropertyList propertyList;

    for (NSString *propertyStr in properties) {

        SEL selector = NSSelectorFromString(propertyStr);
        IMP imp = [self methodForSelector:selector];
        id (*func)(id, SEL) = (id (*)(id, SEL))imp;
        
        WCTProperty property = func(self, selector);// 执行到这一行就会崩溃???????

        propertyList.push_back(property);
    }
    return [self.table updateRowsOnProperties:propertyList withObject:project where:(JGJWCTProject.userId == project.userId && JGJWCTProject.proId == project.proId)];
}

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
ORM `property` is a class method. Was it wrong here?

**Comment by RingoD** [comment]
no reply.
