### ISSUE TITLE
Android RecoverKit 不支援 AUTOINCREMENT ?

### ISSUE THREAD

**Issue by JacksonHuangTW1229** [Tencent/wcdb#579]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Java

### The version of WCDB

> e.g. v1.0.5

wcdb-20190125-master

### The platform of WCDB

> e.g. iOS, macOS or Android

Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

AAR

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

If I has a table use  @PrimaryKey(autoGenerate = true)
And use BackupKit to backup
It would fail when call RecoverKit.run()

The error log is "SQL execution failed. [tag: SQL_ONESHOT, err: object name reserved for internal use: sqlite_sequence, sql: CREATE TABLE sqlite_sequence(name,seq)]"

How do I use AUTOINCREMENT in my table and backup/restore ?

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
