### ISSUE TITLE
一个问题,如果只要引入wcdb文件,后缀名就要是.mm,后期基本文件都是.mm,你们是怎么处理这个问题的

### ISSUE THREAD

**Issue by haotiankeji** [Tencent/wcdb#58]

**Comment by RingoD** [comment]
我们的工程几乎所有文件都为Objective-C++代码。使用Objective-C++编译不会对你的其他代码产生什么影响。

项目大了之后，很难脱离C++，特别是要依赖各种底层库。

WCDB主要对C++的依赖是WINQ，这部分不太可能剥离。

我也在思考更好的方式优化这个问题，例如提供脚本一键修改所有文件名后缀等。

如果有什么好建议，欢迎提出。

**Comment by haotiankeji** [comment]
将业务操作跟底层数据库分离,可以解决这个问题

**Comment by 312362115** [comment]
WINQ能否用swift实现?

**Comment by RingoD** [comment]
有在考虑 #5
