### ISSUE TITLE
复合主键 表之前建立了2个复合主键，后面在增加第3个复合主键没有效？

### ISSUE THREAD

**Issue by GavinOY** [Tencent/wcdb#582]
### The language of WCDB

> Objective-C

### The version of WCDB

>  v1.0.5

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?
表之前建立了2个主键后面在增加第3个主键没有效？
WCDB_MULTI_PRIMARY(Model,"PRIMARY", PRIMARY1)
WCDB_MULTI_PRIMARY(Model,"PRIMARY", PRIMARY2)
表建立后再增加第三个主键
WCDB_MULTI_PRIMARY(Model,"PRIMARY", PRIMARY3)

**Comment by 0xBowen** [comment]
@GavinOY 请问大佬有解决吗？
