### ISSUE TITLE
Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

### ISSUE THREAD

**Issue by xtxh** [Tencent/wcdb#583]
### The language of WCDB

 Swift 

### The version of WCDB

v1.0.8

### The platform of WCDB

 iOS

### The installation of WCDB

 Cocoapods

### What's the issue?
每次执行到 
 try databaseFTS.insert(objects: ftsDataArray, intoTable: tableNameFTS)
时会调到WCDBTokenize.swift 165行报错，Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

string.enumerateLinguisticTags(in: string.startIndex..<string.endIndex,
                                       scheme: NSLinguisticTagScheme.lemma.rawValue,
                                       options: NSLinguisticTagger.Options.omitWhitespace,
                                       orthography: WCDBCursorInfo.orthography,
                                       invoking: { (tag, _, _, stop) in
                                        optionalLemma = tag.lowercased()
                                        stop = true
        })

并且在控制台输入bt获取线程信息时，会断开调试

**Comment by RingoD** [comment]
Upgrade both WCDB version and Swift version to the newest.

**Comment by wjh0917** [comment]
你好，我也遇到了这个问题，请问你解决了吗？

**Comment by wjh0917** [comment]
你好，我也遇到了这个问题，请问你解决了吗？
