### ISSUE TITLE
database corruption is iOS 13

### ISSUE THREAD

**Issue by Merena** [Tencent/wcdb#587]
### What's the issue?

Before iOS 13, there is no problem. 

Recently I upgrade to iOS 13 beta. When debuging using iOS simulator(haven't try device), sometimes wcdb is corrupted, especially when the document directory is cleared(db file is deleted) and restart. 
I tested, every time the error occurs, it must after "recovered frames from WAL file". But not every recover cause this error.

Among corruption msg "at line XXX of [bbd85d235f]", bbd85d235f is fixed every time, but line no is not.
And I tried close db before delete it and restart, not working, still easily got error.

**Can you check if this is a iOS 13 compatible issue?**

> Post the outputs or screenshots for errors.
> [WCDB][DEBUG]Code:283, Type:SQLiteGlobal, Msg:recovered 2 frames from WAL file /Users/mhm/Library/Developer/CoreSimulator/Devices/D3FEB6F8-C215-4957-AB3A-202E9BEBE6DD/data/Containers/Data/Application/78CEE28B-8F90-4184-84A1-B0F64CDDD66C/Documents/RSDBServ
[WCDB][DEBUG]Code:11, Type:SQLiteGlobal, Msg:database corruption at line 2948 of [bbd85d235f]
[WCDB][DEBUG]Code:11, Type:SQLiteGlobal, Msg:database disk image is malformed
[WCDB][ERROR]Code:11, Type:SQLite, Tag:0, Op:4, ExtCode:11, Msg:database disk image is malformed, SQL:PRAGMA synchronous='NORMAL', Path:/Users/mhm/Library/Developer/CoreSimulator/Devices/D3FEB6F8-C215-4957-AB3A-202E9BEBE6DD/data/Containers/Data/Application/78CEE28B-8F90-4184-84A1-B0F64CDDD66C/Documents/RSDBService.sqlite
2019-08-22 09:19:11.371216+0800 WenHua[12871:67938] RSDBService.sqlite canOpen fail

> Explain what you want by example or code :

**Comment by RingoD** [comment]
I don't think it's related to the iOS version. Have you try to run your code(without any modification) in iOS 12?

**Comment by RingoD** [comment]
no reply.
