### ISSUE TITLE
iOS WCDB操作数据库异常奔溃

### ISSUE THREAD

**Issue by MerlinOnline** [Tencent/wcdb#588]
iOS object-c WCDB操作数据库异常奔溃。
奔溃堆栈：
GIGChat	walIndexTryHdr (wal.c:2033)
1 GIGChat	walIndexReadHdr (wal.c:2092)
2 GIGChat	walIndexReadHdr (wal.c:2092)
3 GIGChat	walTryBeginRead (wal.c:2227)
4 GIGChat	sqlite3WalBeginReadTransaction (wal.c:2423)
5 GIGChat	sqlite3PagerSharedLock (pager.c:5238 [Inline: pagerBeginReadTransaction])
6 GIGChat	sqlite3BtreeBeginTrans (btree.c:3204 [Inline: lockBtree])
7 GIGChat	sqlite3VdbeExec (vdbe.c:3178)
8 GIGChat	sqlite3_step (vdbeapi.c:602)
9 GIGChat	WCDB::StatementHandle::step() (handle_statement.cpp:47)
10 GIGChat	-[WCTSelectBase next] (WCTSelectBase.mm:124)
11 GIGChat	-[WCTSelect allObjects] (WCTSelect.mm:116)
12 GIGChat	-[WCTInterface(Convenient) getObjectsOfClass:fromTable:where:] (WCTInterface+Convenient.mm:0)

**Comment by RingoD** [comment]
Was the device locked when the crash happens?

**Comment by MerlinOnline** [comment]
是的，设备处于锁屏状态下崩溃的。

**Comment by RingoD** [comment]
Try to set the file protection to none for the `database-shm` file.

**Comment by RingoD** [comment]
no reply.

**Comment by lifenglin123** [comment]
数据库设置NSFileProtectionCompleteUntilFirstUserAuthentication这个策略，后台可读写数据即可
