### ISSUE TITLE
Feature: FTS接口

### ISSUE THREAD

**Issue by cxjwin** [Tencent/wcdb#59]
fts 是直接编译进去就可以使用的了么? 有没有相关的文档.

**Comment by RingoD** [comment]
你可以利用WCDB现有接口接入你的FTS，但WCDB暂未提供直接的FTS接口。

FTS在我们的开发计划中。关键点在于如何设计一个易用、通用的FTS接口和功能。如果你有好的想法或实现，欢迎提PR。

**Comment by RingoD** [comment]
https://github.com/Tencent/wcdb/wiki/全文搜索使用教程
