### ISSUE TITLE
firebase  have a conflict with WCDB about Sqlite  For ios 12

### ISSUE THREAD

**Issue by kule123** [Tencent/wcdb#591]
Error Domain=com.google.gmp.measurement.ErrorDomain Code=3 "Database operation "prepare statement" failed with sqlite code 0 and error message "not an error"" UserInfo={NSLocalizedDescription=Database operation "prepare statement" failed with sqlite code 0 and error message "not an error", APMMonitorContext=prepare statement,0,A,4}

**Comment by RingoD** [comment]
Well, I didn't see any errors from WCDB. Maybe you should ask Firebase staff for help.

**Comment by RingoD** [comment]
no reply.
