### ISSUE TITLE
cocoapods导入问题

### ISSUE THREAD

**Issue by wdq123550** [Tencent/wcdb#592]
### The language of WCDB
objc

### The version of WCDB

> e.g. v1.0.7.5

### The platform of WCDB

ios

### The installation of WCDB

cocoapods

### What's the issue?
Analyzing dependencies
Downloading dependencies
Using AFNetworking (3.2.1)
Installing SQLiteRepairKit (1.2.2)

[!] Error installing SQLiteRepairKit
[!] /usr/bin/git clone https://github.com/Tencent/wcdb.git /var/folders/pz/kb0qzscs25l6_qnx262fgtw40000gn/T/d20190829-31516-mdj9du --template= --single-branch --depth 1 --branch v1.0.8.2

Cloning into '/var/folders/pz/kb0qzscs25l6_qnx262fgtw40000gn/T/d20190829-31516-mdj9du'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by wdq123550** [comment]
wazc-03230@wangangongzuodiannaodeMacBook-Air:~$ cd /Users/wazc-03230/Documents/个人文件/AlienHelper
wazc-03230@wangangongzuodiannaodeMacBook-Air:~/Documents/个人文件/AlienHelper$ carthage update --configuration WithoutBitcode --platform ios
*** Fetching WCDB
*** Checking out WCDB at "v1.0.8"
A shell task (/usr/bin/env git clone --quiet https://github.com/Tencent/sqlcipher.git /Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/sqlcipher) failed with exit code 128:
fatal: unable to open /Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/sqlcipher/.git/objects/pack/tmp_pack_eUHn4a: No such file or directory
fatal: index-pack failed

**Comment by wdq123550** [comment]
carthage 也不行

**Comment by wdq123550** [comment]
carthage编译问题
wazc-03230@wangangongzuodiannaodeMacBook-Air:~/Documents/个人文件/AlienHelper$ carthage update
*** Fetching WCDB
*** Checking out WCDB at "v1.0.8"
*** xcodebuild output can be found in /var/folders/pz/kb0qzscs25l6_qnx262fgtw40000gn/T/carthage-xcodebuild.115YUu.log
*** Downloading WCDB.framework binary at "WCDB 1.0.8"
*** Building scheme "WCDB" in WCDB.xcworkspace
*** Building scheme "WCDB.swift" in WCDB.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/WCDB.xcworkspace -scheme WCDB.swift -configuration Release -derivedDataPath /Users/wazc-03230/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/WCDB/v1.0.8 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/pz/kb0qzscs25l6_qnx262fgtw40000gn/T/WCDB SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/pz/kb0qzscs25l6_qnx262fgtw40000gn/T/carthage-xcodebuild.115YUu.log

**Comment by RingoD** [comment]
Since you didn't provide the error log, here are some advice for fixing these kinds of issues:
1. Use a pure English path without any spaces, instead of the folders with Chinese.
2. `index-pack failed` errors usually indicate the network issue. Maybe you should use a better network to connect to Cocoapods spec server and Github.

**Comment by wdq123550** [comment]
https://yun.baidu.com/disk/home?errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0&traceid=#/all?path=%2F&vmode=list   
这样看更直观一点

**Comment by wdq123550** [comment]
你好，你看最后一条信息，我成功下载wcdb了之后它提示wcdb.swift编译错误。

**Comment by RingoD** [comment]
Yes, but you didn't show the error log here.

**Comment by wdq123550** [comment]
http://imgsrc.baidu.com/forum/w%3D580/sign=d9013fce73d98d1076d40c39113eb807/22a2828ba61ea8d30ac3dd36980a304e241f58f3.jpg

这个是下载不了的错误

**Comment by wdq123550** [comment]
链接: https://pan.baidu.com/s/1t_dGfBLnwJYhiiTT30a1_Q 提取码: 251h 

error log文件我不知道该怎么给你看，足足有8M的文件大小。我上传到百度云了，你可以下载来看。

**Comment by RingoD** [comment]
You can compress it. Or post those lines of errors only.

**Comment by wdq123550** [comment]
我试着把error log文件上传到我自己的仓库， https://github.com/wdq123550/WCDBTest  。里面那个carthage-xcodebuild.115YUu.log就是错误文件。麻烦你查看一下。

**Comment by wdq123550** [comment]
我本意是想通过carthage构建framewo库，这样编译会快一点。但是我尝试carthage update十次，有九次都是说下面这些信息。
Cloning into '/var/folders/pz/kb0qzscs25l6_qnx262fgtw40000gn/T/d20190829-31516-mdj9du'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

然后我尝试挂SS全局代理，然后就到wcdb.swift编译错误了。

**Comment by wdq123550** [comment]
现在完全不行了。。。挂SS也不行了。能不能发布一个carthage 编译好的framework？
http://tieba.baidu.com/photo/p?kw=c%E8%AF%AD%E8%A8%80&ie=utf-8&flux=1&tid=6240304043&pic_id=13507bf40ad162d992e0f12e1edfa9ec8a13cd4a&pn=1&fp=2&see_lz=1

**Comment by wdq123550** [comment]
还有就是为啥cocoapods里面执行pod search wcdb 出来的最新结果是1.0.7.5版本的，但是用carthage下载的确是1.0.8版本的？

**Comment by RingoD** [comment]
I don't think we don't have anything to do for your network status.

**Comment by RingoD** [comment]
In v1.0.8.x, we only fix some minor issues for Swift version, which is irrelated with ObjC version.

**Comment by wdq123550** [comment]
好的，那carthage编译不过怎么办？我用的是oc，可以不让它编译wcdb.swift吗？就是wcdb.swift报错.

**Comment by RingoD** [comment]
Again, I didn't see the error logs.

**Comment by wdq123550** [comment]
我不知道是不是这里，我截取的是最后的一些，你可以去
 https://github.com/wdq123550/WCDBTest
里面那个carthage-xcodebuild.115YUu.log就是完整的错误文件
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:38:5: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    internal func joined(separateBy separator: String = ", ") -> String {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:52:5: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    internal func joined(separateBy separator: String = ", ") -> String {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:58:5: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    internal func joined(separateBy separator: String = ", ") -> String {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:64:5: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    internal func joined(separateBy separator: String = ", ") -> String {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:70:5: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    internal func joined(separateBy separator: String = ", ") -> String {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:76:5: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    internal func joined(separateBy separator: String = ", ") -> String {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:82:5: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    internal func joined(separateBy separator: String = ", ") -> String {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:88:5: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    internal func joined(separateBy separator: String = ", ") -> String {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:24:5: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    internal func joined(_ map: (Element) -> String, separateBy separator: String = ", ") -> String {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:98:5: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    internal func asCodingTableKeys() -> [CodingTableKeyBase] {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:92:5: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    internal func asIndexes() -> [ColumnIndex] {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/core/codable/ColumnCodable.swift:32:5: warning: 'public' modifier is redundant for instance method declared in a public extension
    public func asLiteralValue() -> LiteralValue {
    ^~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/builtin/CodableType.swift:244:33: error: redundant conformance of 'Array<Element>' to protocol 'ColumnCodableBase'
extension Array: ColumnCodable, ColumnCodableBase where Element: Codable {
                                ^
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/builtin/CodableType.swift:244:1: note: 'Array<Element>' declares conformance to protocol 'ColumnCodableBase' here
extension Array: ColumnCodable, ColumnCodableBase where Element: Codable {
^
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/builtin/CodableType.swift:262:38: error: redundant conformance of 'Dictionary<Key, Value>' to protocol 'ColumnCodableBase'
extension Dictionary: ColumnCodable, ColumnCodableBase where Key: Codable, Value: Codable {
                                     ^
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/builtin/CodableType.swift:262:1: note: 'Dictionary<Key, Value>' declares conformance to protocol 'ColumnCodableBase' here
extension Dictionary: ColumnCodable, ColumnCodableBase where Key: Codable, Value: Codable {
^
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/builtin/CodableType.swift:280:31: error: redundant conformance of 'Set<Element>' to protocol 'ColumnCodableBase'
extension Set: ColumnCodable, ColumnCodableBase where Element: Codable {
                              ^
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/builtin/CodableType.swift:280:1: note: 'Set<Element>' declares conformance to protocol 'ColumnCodableBase' here
extension Set: ColumnCodable, ColumnCodableBase where Element: Codable {
^
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:187:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toInt8() -> Int8 {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:172:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toInt32() -> Int32 {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:190:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toInt16() -> Int16 {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:178:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toInt32() -> Int32 {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:205:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toInt() -> Int {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:166:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toInt64() -> Int64 {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:193:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toUInt8() -> UInt8 {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:223:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toInt32() -> Int32 {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:196:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toUInt16() -> UInt16 {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:229:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toInt32() -> Int32 {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:199:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toUInt32() -> UInt32 {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:235:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toInt32() -> Int32 {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:211:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toUInt64() -> UInt64 {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:241:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toInt64() -> Int64 {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:208:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toUInt() -> UInt {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:217:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toInt64() -> Int64 {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:184:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toBool() -> Bool {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:160:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toInt32() -> Int32 {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:253:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toFloat() -> Float {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:247:23: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    @inline(__always) internal func toDouble() -> Double {
                      ^~~~~~~~~
                      
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/abstract/Tokenize.swift:111:34: error: value of optional type 'UnsafePointer<Int8>?' must be unwrapped to a value of type 'UnsafePointer<Int8>'
            bytes = Int32(strlen(pInput))
                                 ^
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/abstract/Tokenize.swift:111:34: note: coalesce using '??' to provide a default when the optional value contains 'nil'
            bytes = Int32(strlen(pInput))
                                 ^
                                        ?? <#default value#>
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/abstract/Tokenize.swift:111:34: note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
            bytes = Int32(strlen(pInput))
                                 ^
                                       !
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:120:5: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    internal func joined(_ map: (Key, Value) -> String, separateBy separator: String = "," ) -> String {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:106:5: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    internal mutating func expand(toNewSize newSize: Int, fillWith value: Iterator.Element) {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:114:5: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    internal mutating func expand(toNewSize newSize: Int) {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:134:5: warning: 'internal' modifier is redundant for property declared in an internal extension
    internal var lastPathComponent: String {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:138:5: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    internal func stringByAppending(pathComponent: String) -> String {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:142:5: warning: 'internal' modifier is redundant for property declared in an internal extension
    internal var cString: UnsafePointer<Int8>? {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:146:5: warning: 'internal' modifier is redundant for initializer declared in an internal extension
    internal init?(bytes: UnsafeRawPointer, count: Int, encoding: String.Encoding) {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:150:5: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    internal func range(from begin: Int, to end: Int) -> Range<String.Index> {
    ^~~~~~~~~
    
/Users/wazc-03230/Documents/个人文件/AlienHelper/Carthage/Checkouts/WCDB/swift/source/util/Convenience.swift:154:5: warning: 'internal' modifier is redundant for instance method declared in an internal extension
    internal func range(location: Int, length: Int) -> Range<String.Index> {
    ^~~~~~~~~


** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal armv7
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(4 failures)

**Comment by RingoD** [comment]
Is your Xcode version the newest?

**Comment by wdq123550** [comment]
不是的，xcode是10.2.1，不是最新的

**Comment by RingoD** [comment]
Then try the newest version with Swift 5.

**Comment by willing8310** [comment]
我的Xcode是最新的10.3版本，也遇到同样的问题

**Comment by RingoD** [comment]
@willing8310  Then why not show the error logs?

**Comment by willing8310** [comment]
> @willing8310 Then why not show the error logs?

不好意思，我的可以了，上周应该是网络问题，谢谢。

**Comment by wdq123550** [comment]
我不需要wcdb.swift 我直接把编译好的wcdb.framework直接用也没事把？

**Comment by RingoD** [comment]
@wdq123550 Of course.
