### ISSUE TITLE
Always got error:no such table xx but it exists

### ISSUE THREAD

**Issue by ct-countersoft** [Tencent/wcdb#593]
### The language of WCDB

> Objective-C, iOS,v1.0.5

### What's the issue?

> Post the outputs or screenshots for errors.
> [WCDB]Code:1, Type:SQLite, Tag:0, Op:3, ExtCode:1, Msg:no such table: table_messages_100074, SQL:SELECT rowId FROM table

Chinese:
使用wcdb库接近一年，期间一直正常，在28号左右开始出现数据库异常：逐个db里表出现no such table，最后所有表都报no such table。
wc相关报错打印：Code:1, Type:SQLite, Tag:0, Op:3, ExtCode:1, Msg:no such table: table_messages_100074, SQL:SELECT rowId FROM table

![WechatIMG7](https://user-images.githubusercontent.com/517226/63996160-76496880-cb2d-11e9-92d5-4fe08105c9f9.jpeg)

**Comment by RingoD** [comment]
Please provide a demo project that can reproduce this issue.

**Comment by ct-countersoft** [comment]
Ok, issue is easy; could you tell me when and what could make Wcdb rebuild App DB, and how many percent cause db error or damage db

**Comment by RingoD** [comment]
What do you mean about "rebuild app db"?

**Comment by ct-countersoft** [comment]
3.db
 fileAttributes:{
    NSFileCreationDate = "2019-08-28 11:10:17 +0000";
    NSFileExtensionHidden = 0;
    NSFileGroupOwnerAccountID = 501;
    NSFileGroupOwnerAccountName = mobile;
    NSFileModificationDate = "2019-09-02 03:42:44 +0000";
    NSFileOwnerAccountID = 501;
    NSFileOwnerAccountName = mobile;
    NSFilePosixPermissions = 420;
    NSFileProtectionKey = NSFileProtectionNone;
    NSFileReferenceCount = 1;
    NSFileSize = 606208;
    NSFileSystemFileNumber = 41449527;
    NSFileSystemNumber = 16777220;
    NSFileType = NSFileTypeRegular;
}

For above info desc，this db file【 3.db】should be created in 2018.6 according user first login, but we could find that db create time is 2019-08-28 11:10:17, why?
We are not remove any db file in app, but this db file createtime shows the issue, please tell me wcdb maybe remove db and create the new db file, thx.

Chinese:
我们打印了用户3.db的数据库相关信息，从上面可以看到这个db文件是在数据库出现no such table时被重建了，这个db的创建时间是 2019-08-28 11:10，而我们实际记录到他在使用db有一年多时间，这个3.db创建应该是2018年，而非2019年；

App没有执行db文件删除操作，用户也没有操作db文件，那可能性：wcdb或者iOS系统；
所以我想知道wcdb有没有可能在异常时执行db文件删除操作，重新创建db文件，谢谢！

**Comment by ct-countersoft** [comment]
wcdb在什么异常情况时会删除db文件，重新创建db文件，谢谢！

**Comment by RingoD** [comment]
WCDB never remove/create the database files unless you call it.

**Comment by ct-countersoft** [comment]
ok, thx!

**Comment by antonyyeh** [comment]
我有遇到類似的問題一開始使用都很正常有時會突然發生會出現訊息：[WCDB][ERROR] Code:sqlite(1), Type:SQLite, Message:no such table:（通常要運行一段時間後才會發生） 此時只能刪除ＡＰＰ再重裝才能解決～請問這個問題有解嗎？

**Comment by ct-countersoft** [comment]
检查下所有table的删除语句，no such table就是数据库表被删除了



在 2023-08-28 11:44:14，"antonyyeh" ***@***.***> 写道：

我有遇到類似的問題一開始使用都很正常有時會突然發生會出現訊息：[WCDB][ERROR] Code:sqlite(1), Type:SQLite, Message:no such table:（通常要運行一段時間後才會發生） 此時只能刪除ＡＰＰ再重裝才能解決～請問這個問題有解嗎？
