### ISSUE TITLE
sqlite不兼容的问题这个怎么解决啊 没法用firebase了

### ISSUE THREAD

**Issue by kule123** [Tencent/wcdb#594]
![image](https://user-images.githubusercontent.com/11805288/64060188-e32b3400-cbfb-11e9-8750-0a49cbde5182.png)
 firbase

**Comment by ChengminZhang** [comment]
问题链接：https://github.com/firebase/firebase-ios-sdk/issues/3601

**Comment by kule123** [comment]
哈哈 这就难受了 没人能够解决这些问题

**Comment by Liulinzhe17** [comment]
手动@一下wcdb作者

**Comment by RingoD** [comment]
I think it should be a problem caused by sharing SQLite.
A good way to solve it should be using WCDB as a dynamic library.

**Comment by yanghuabiao** [comment]
同问

**Comment by yanghuabiao** [comment]
> I think it should be a problem caused by sharing SQLite.
> A good way to solve it should be using WCDB as a dynamic library.

同问

**Comment by yanghuabiao** [comment]
@RingoD ，我们也提了issue，在firebase，firebase的作者回复说最好是wcdb的作者删除或者更新sqlite3到3.29

**Comment by RingoD** [comment]
We will upgrade sqlcipher to the newest when the next version is released.

**Comment by kule123** [comment]
Use WCDB as a dynamic library  
its work fine
thanks

**Comment by yanghuabiao** [comment]
你好，我想问问什么时候会发布新的版本 @RingoD

**Comment by Liulinzhe17** [comment]
> I think it should be a problem caused by sharing SQLite.
> A good way to solve it should be using WCDB as a dynamic library.

I got WCDB as a dynamic library. Need to dependence sqlcipher?

**Comment by LanceXZH** [comment]
使用动态库也解决不了这个问题啊，什么时候发布新版本，更新sqlite3到3.29啊？ @RingoD

**Comment by ChengminZhang** [comment]
> 使用动态库也解决不了这个问题啊，什么时候发布新版本，更新sqlite3到3.29啊？ @RingoD

使用动态库可以解决，我目前已经兼容firebase，就是更新比较麻烦了。

按照官方文档的动态库安装是无法正确安装使用的，你需要观察wcdb.podspec文件的依赖库，其中有一个库指向了另一个库的某一次提交，把它们组装正确后就可以动态库安装成功。

**Comment by LanceXZH** [comment]
> > 使用动态库也解决不了这个问题啊，什么时候发布新版本，更新sqlite3到3.29啊？ @RingoD
> 
> 使用动态库可以解决，我目前已经兼容firebase，就是更新比较麻烦了。
> 
> 按照官方文档的动态库安装是无法正确安装使用的，你需要观察wcdb.podspec文件的依赖库，其中有一个库指向了另一个库的某一次提交，把它们组装正确后就可以动态库安装成功。

您好，是repairKit还是SQLCipher啊，怎么正确组装啊？能详细说一下嘛，感谢！ @ChengminZhang

**Comment by ChengminZhang** [comment]
> > > 使用动态库也解决不了这个问题啊，什么时候发布新版本，更新sqlite3到3.29啊？ @RingoD
> > 
> > 
> > 使用动态库可以解决，我目前已经兼容firebase，就是更新比较麻烦了。
> > 按照官方文档的动态库安装是无法正确安装使用的，你需要观察wcdb.podspec文件的依赖库，其中有一个库指向了另一个库的某一次提交，把它们组装正确后就可以动态库安装成功。
> 
> 您好，是repairKit还是SQLCipher啊，怎么正确组装啊？能详细说一下嘛，感谢！ @ChengminZhang


我用的是OC，对比Pod和手动安装，发现手动安装动态老是失败，按照教程安装拉下来都是最新的代码，怀疑是两个库版本对不上，所以找到目前线上可以正确安装的版本，把代码拉下拉。Pod使用的是WCDB v1.0.7.5，依赖的sqlcipher版本是1.2.0，所以把版本回退一下。

git clone https://github.com/Tencent/wcdb.git
cd wcdb
git submodule update —init sqlcipher

然后把wcdb库回退到tag 1.0.7.5
把sqlcipher库回退到commit  7413f8517e305f4edf106dec0682515767f4fc4a（podspec显示，sqlcipher的1.2.0版本是通过commit来指定的，很奇怪）

再将 wcdb/objc/WCDB.xcodeproj添加到你的工程中，把他们都编译一下。
继续按照wiki的教程安装就好了。

希望对你有帮助

**Comment by LanceXZH** [comment]
> > > > 使用动态库也解决不了这个问题啊，什么时候发布新版本，更新sqlite3到3.29啊？ @RingoD
> > > 
> > > 
> > > 使用动态库可以解决，我目前已经兼容firebase，就是更新比较麻烦了。
> > > 按照官方文档的动态库安装是无法正确安装使用的，你需要观察wcdb.podspec文件的依赖库，其中有一个库指向了另一个库的某一次提交，把它们组装正确后就可以动态库安装成功。
> > 
> > 
> > 您好，是repairKit还是SQLCipher啊，怎么正确组装啊？能详细说一下嘛，感谢！ @ChengminZhang
> 
> 我用的是OC，对比Pod和手动安装，发现手动安装动态老是失败，按照教程安装拉下来都是最新的代码，怀疑是两个库版本对不上，所以找到目前线上可以正确安装的版本，把代码拉下拉。Pod使用的是WCDB v1.0.7.5，依赖的sqlcipher版本是1.2.0，所以把版本回退一下。
> 
> git clone https://github.com/Tencent/wcdb.git
> cd wcdb
> git submodule update —init sqlcipher
> 
> 然后把wcdb库回退到tag 1.0.7.5
> 把sqlcipher库回退到commit 7413f8517e305f4edf106dec0682515767f4fc4a（podspec显示，sqlcipher的1.2.0版本是通过commit来指定的，很奇怪）
> 
> 再将 wcdb/objc/WCDB.xcodeproj添加到你的工程中，把他们都编译一下。
> 继续按照wiki的教程安装就好了。
> 
> 希望对你有帮助

亲测可用，不过我这边直接从1.0.7.5拉一个branch出来，不回退sqlcipher就可以用了，回退了反而不行！
