### ISSUE TITLE
How to creates triggers with wcdb?

### ISSUE THREAD

**Issue by ct-countersoft** [Tencent/wcdb#595]
### The language of WCDB

>Objective-C

### The version of WCDB

> v1.0.5

### The platform of WCDB

> iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?
我们想使用wcdb创建触发器，但是搜遍API没找到触发器创建的。
> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
WCDB v1.0.x does not support the trigger. It will be supported in the next release.
Currently, maybe you could rewrite the source code.

**Comment by ct-countersoft** [comment]
oo

**Comment by ct-countersoft** [comment]
ok, try it. Thx.

**Comment by stupidchou** [comment]
Are triggers supported now?
