### ISSUE TITLE
Android数据库修复后如何重新替换数据库？

### ISSUE THREAD

**Issue by huopochuan** [Tencent/wcdb#596]
直接文件替换不会立即生效，需要重启才生效。微信修复数据库后需要重启APP吗

**Comment by John-He-928** [comment]
You should close and reopen the result database file to make it work.

**Comment by huopochuan** [comment]
如果正在执行增删改查的时候，执行了close and reopen应该会报错的，这种情况怎么避免的？

**Comment by huopochuan** [comment]
i should speak English?
