### ISSUE TITLE
About WCDB SQLCipher 

### ISSUE THREAD

**Issue by zhangqushun** [Tencent/wcdb#597]
### The language of WCDB

 Objective-C

### The version of WCDB

WCDB (1.0.7.5)
WCDBOptimizedSQLCipher (1.2.1)

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

I'm install WCDB with Cocoapods. In my test, it seems that the SQLCipher version used is 3.2.  The SQLCipher version installed using other methods is 4.1. How can I update the version of the SQLCipher? Or when will you update? Also, what I want to ask is why the WCDB not provide the Interface to custom hmac and kdf algorithms？

**Comment by RingoD** [comment]
It will be updated in the next release.

**Comment by RingoD** [comment]
Could you please tell me why you would like to modify the hmac and the kdf ?
