### ISSUE TITLE
How to make the primary key restart from 1

### ISSUE THREAD

**Issue by rakuyoMo** [Tencent/wcdb#598]
### The language of WCDB

Swift

### The version of WCDB

v1.0.8.2

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

I have a auto increment primary key called `id`

When I delete all the data in the table, I want the content of the `id` to start from 1 and re-increment

I have reviewed this [issue 507 ](https://github.com/Tencent/wcdb/issues/507)

Then I found the `WCTSequence` class, but I didn't find the corresponding Swift class.

So how do I operate to solve this problem?

**Comment by RingoD** [comment]
You can implement your own `WCTSequence` class in Swift.

**Comment by rakuyoMo** [comment]
> You can implement your own `WCTSequence` class in Swift.

So the official did not provide a similar class right?

Do you have plans to launch an official `WCTSequence`?

If you plan to provide it in `1.1.0`, I think I can wait until

**Comment by RingoD** [comment]
No, I think, since it's not necessary and can be implemented by the developers easily.

**Comment by rakuyoMo** [comment]
Ok, I will try to build this class myself.
