### ISSUE TITLE
#import <WCDB/WCDB.h>  报错Could not build module 'WCDB'

### ISSUE THREAD

**Issue by DeveInfo** [Tencent/wcdb#60]
引入#import <WCDB/WCDB.h>时报错 Could not build module 'WCDB'，该类.m已改成.mm,但是在.mm中引用不报错，在.h 中引用报上述错误

**Comment by RingoD** [comment]
其他引用这个.h的源文件也需要改

**Comment by xilin** [comment]
我在制作一个pod库时，dependency里有wcdb和另一个swift库，开启了modular_header，编译时也出了这个提示。已确保pod库内部引用.h源文件的所有实现都已经是.mm了。是因为umbrella里把这个h文件暴露出去所以出这个提示吗？
