### ISSUE TITLE
How to batch update?

### ISSUE THREAD

**Issue by ElfSundae** [Tencent/wcdb#603]
ObjC WCDB (1.0.7.5)

I want to batch update rows with ORM objects using one SQL statement, instead of for-loop.
I don't know how to use `WCDB::Expr::Case` with updating methods, it seems the `WCTUpdate` does not support CASE expression yet.

**Comment by RingoD** [comment]
Sorry for this. `case` expression is not fully supported in the current version.

**Comment by VincentSit** [comment]
How do I do this in the Swift version? No sample code was found in Wiki or testcase.

**Comment by ElfSundae** [comment]
Thanks, waiting for it.

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
