### ISSUE TITLE
swift 5.1

### ISSUE THREAD

**Issue by 937447974** [Tencent/wcdb#604]
你好，能麻烦百忙之中升级到swift5.1吗

**Comment by RingoD** [comment]
I find that WCDB swift can be compiled in Swift 5.1.

What problem have you encountered?

**Comment by 937447974** [comment]
> I find that WCDB swift can be compiled in Swift 5.1.
> 
> What problem have you encountered?

不能将 wcdb 打包为 framework 供 swift 项目使用，只能源码导入使用。

**Comment by RingoD** [comment]
Then what's the error shown?

**Comment by 937447974** [comment]
> Then what's the error shown?

不能引入低于swift 5 的 framewofk

**Comment by RingoD** [comment]
Could you please provide the original errors or a screen shot?

**Comment by RingoD** [comment]
What's the Swift version of your project? And what's it when building WCDBSwift?

**Comment by 937447974** [comment]
刚刚试了一下，可以 framework 导入，是我的 podspec 没配对。
