### ISSUE TITLE
Install WCDB via CocoaPods, but build failed with xcode 11.0

### ISSUE THREAD

**Issue by JasonZengJ** [Tencent/wcdb#605]
### The language of WCDB

Objective-C

### The version of WCDB

v1.0.7.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

build failed with xcode 11.0(11A420a)

![image](https://user-images.githubusercontent.com/5507202/65411836-7bde5980-de20-11e9-84a1-4ac76936f7f3.png)

**Comment by RingoD** [comment]
Did you build with C++11?

**Comment by RingoD** [comment]
no reply.
