### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by huary** [Tencent/wcdb#607]
<img width="840" alt="WeChat8cebafe0ae7c574fbdd0d21477ac48c7" src="https://user-images.githubusercontent.com/20548093/65656226-ab27dd00-e051-11e9-84ed-c45cc1a5a638.png">
![1569468927601](https://user-images.githubusercontent.com/20548093/65656245-c397f780-e051-11e9-97ca-dca6710bb603.jpg)

### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
Please provide the basic information.
