### ISSUE TITLE
'sqliterk/SQLiteRepairKit.h' file not found

### ISSUE THREAD

**Issue by zicjin** [Tencent/wcdb#608]
### The language of WCDB
Swift

### The version of WCDB
github "Tencent/WCDB" "v1.0.8.2"

### The platform of WCDB
iOS

### The installation of WCDB
Carthage

### What's the issue?
WCDB-Bridging.h:
![image](https://user-images.githubusercontent.com/199482/65846514-8e044e80-e370-11e9-8d73-4b65629b2456.png)

compile fail

**Comment by RingoD** [comment]
What's the Swift version?

**Comment by st2340596** [comment]
Same .  Xcode 11.2  Swift 5

**Comment by st2340596** [comment]
> Same . Xcode 11.2 Swift 5

wcdb / pre 1.1.0

**Comment by RingoD** [comment]
`pre_v1.1.0` is prepared for Swift. You might use v1.0.8.2 for Swift 5.x.

**Comment by njuxjy** [comment]
I'm facing the same issue:

## The language of WCDB
Swift 4.2, Xcode 11.3.1

## The version of WCDB
github "Tencent/WCDB" "v1.0.8.2"

## The platform of WCDB
iOS

## The installation of WCDB
Carthage

**Comment by danleechina** [comment]
I am facing the same issue. Any updates? Using Swift5.1 in Xcode 11. WCDB version v1.0.8.2 installated by carthage

**Comment by danleechina** [comment]
I comment out the following line and compiled successfully.

```
//#import <sqliterk/SQLiteRepairKit.h>
```
