### ISSUE TITLE
A very obvious BUG in WCTUpdate.mm (Line:72)

### ISSUE THREAD

**Issue by mustlogin** [Tencent/wcdb#611]
### The language of WCDB
OBJC

### The version of WCDB
master, last version

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?

There is an obvious BUG in this file (line 72):  [WCTUpdate.mm](https://github.com/Tencent/wcdb/blob/master/objc/WCDB/interface/chaincall/WCTUpdate.mm)

I add comment in the code block, such as 
```
for (const WCTProperty &property : propertyList) {
            const std::shared_ptr<WCTColumnBinding> &columnBinding = property.getColumnBinding();
            if (columnBinding) {
                updateValueList.push_back({property, WCTExpr::BindParameter});
            } else {   //<-- in this branch, 'columnBinding' is NULL.
                WCDB::Error::ReportInterface(_core->getTag(),
                                             _core->getPath(),
                                             WCDB::Error::InterfaceOperation::Update,
                                             WCDB::Error::InterfaceCode::ORM,
                                             [NSString stringWithFormat:@"Updating [%@] with an unknown column [%s]", 
tableName, 
columnBinding->columnName.c_str()].UTF8String,  //<-- BUT NULL pointer is used to access property, the progress Crash!
&_error);
            }
        }
```

**Comment by RingoD** [comment]
Could you provide the sample code?

A null `column binding` usually indicates the wrong definitions of ORM.

**Comment by RingoD** [comment]
no reply.

**Comment by mustlogin** [comment]
You close this issue not because of the analysis result of the code, but because I did not provide sample code. I think, this is irresponsible。
This is BUG is very obvious.  in the code block, just only 8 lines of code,  there are 2 comments I had written with "//". I had described clearly.

**Comment by mustlogin** [comment]
You close this issue not because of the analysis result of the code, but because I did not provide sample code. I think, this is irresponsible。
This is BUG is very obvious.  in the code block, just only 8 lines of code,  there are 2 comments I had written with "//". I had described clearly.
