### ISSUE TITLE
iOS WCDB crash

### ISSUE THREAD

**Issue by ww1234** [Tencent/wcdb#613]
### The language of WCDB

>Objective-C

### The version of WCDB

> v1.0.6.2

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> 异常信息
> 
![image](https://user-images.githubusercontent.com/7813081/66984292-0303b200-f0ed-11e9-8925-52e8a05d8f21.png)
> crash堆栈
> 
![image](https://user-images.githubusercontent.com/7813081/66984363-275f8e80-f0ed-11e9-98e5-b133e53b6735.png)
>符号化后

> 0x000000010805b8cc
void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, WCDB::Database::$_3::operator()(std::__1::shared_ptr<WCDB::Handle>&, WCDB::Error&) const::'lambda'(WCDB::Handle*, int, void*)::operator()(WCDB::Handle*, int, void*) const::'lambda'()> >(void*) (in WCDB) + 152
0x000000010805b960
WCDB::TimedQueue<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::waitUntilExpired(std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)> const&, bool) (in WCDB) + 104

**Comment by RingoD** [comment]
It seems a system error. Could you provide the sample code?

Or will it still crash in the newest version?

**Comment by RingoD** [comment]
no reply.
