### ISSUE TITLE
app多用户多数据库之间如何进行切换

### ISSUE THREAD

**Issue by wh3mi0v** [Tencent/wcdb#614]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
Object-C

### The version of WCDB

> e.g. v1.0.5

v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android
ios

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

想请教一下，如果想实现同一个app能够进行多个用户的切换，每个用户的数据单独保存到一个独立到数据库，比如用户a登陆后的数据库采用a.sqlite 保存，a退出后，b在同一个手机上进行登陆，建立b.sqlite用于存放b的相关数据。 

这种场景，可以通过什么方式进行database的切换吗？ 目前database采用的单例，是需要重新走一次databse初始化操作么？

谢谢指教。有这方面经验的朋友也欢迎分享。再次谢过了

**Comment by RingoD** [comment]
I don't think it's a WCDB issue.

Maybe you could try not to use a singleton.
