### ISSUE TITLE
什么时候更新？

### ISSUE THREAD

**Issue by yanghuabiao** [Tencent/wcdb#616]
跪问大神什么时候更新？解决sqlite3和fireBase冲突的问题？项目急需解决这个问题！！！

**Comment by Liulinzhe17** [comment]
+1

**Comment by freezy7** [comment]
按照文档先自己编译个动态库吧，我也搞了一天

**Comment by freezy7** [comment]
打包好的动态库，有需要的可以直接下载用
[https://github.com/freezy7/WCDB_Framework](https://github.com/freezy7/WCDB_Framework)

**Comment by RingoD** [comment]
Sorry for this. We are preparing for the update. You can see that ObjC version is stable now in the `pre_v1.1.0` branch. But we have some tough questions to be solved.

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
