### ISSUE TITLE
查询耗时

### ISSUE THREAD

**Issue by Charming04** [Tencent/wcdb#617]
### The language of WCDB
Objective-C 

### The version of WCDB
v1.0.5

### The platform of WCDB
iOS

### The installation of WCDB
- (id /* WCTObject* */)getOneObjectOfClass:(Class)cls
                                 fromTable:(NSString *)tableName
                                   orderBy:(const WCTOrderByList &)orderList;
这个方法有时会耗时，大概3，5s才能返回

**Comment by RingoD** [comment]
It depends on how you create your table and indexes. 

Learn some basics of the database may help you~

**Comment by RingoD** [comment]
no reply.
