### ISSUE TITLE
开启cocoapods的generate_multiple_pod_projects后，link失败

### ISSUE THREAD

**Issue by atomsongxiangwu** [Tencent/wcdb#618]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.7.5

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

>Undefined symbols for architecture arm64:
  "vtable for WCTConstraintPrimaryKeyBinding", referenced from:
      WCTConstraintPrimaryKeyBinding::~WCTConstraintPrimaryKeyBinding() in libIMSDK-Pods-Demo.a(PropertyORM.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "WCTConstraintPrimaryKeyBinding::WCTConstraintPrimaryKeyBinding(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      std::__1::enable_if<std::is_base_of<WCTConstraintBindingBase, WCTConstraintPrimaryKeyBinding>::value, WCTConstraintPrimaryKeyBinding*>::type WCTBinding::getOrCreateConstraintBinding<WCTConstraintPrimaryKeyBinding>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libIMSDK-Pods-Demo.a(PropertyORM.o)
  "WCTConstraintPrimaryKeyBinding::addPrimaryKey(WCDB::ColumnIndex const&)", referenced from:
      $_11::operator()(WCTBinding*) const in libIMSDK-Pods-Demo.a(PropertyORM.o)
      $_12::operator()(WCTBinding*) const in libIMSDK-Pods-Demo.a(PropertyORM.o)
      $_13::operator()(WCTBinding*) const in libIMSDK-Pods-Demo.a(PropertyORM.o)
      $_14::operator()(WCTBinding*) const in libIMSDK-Pods-Demo.a(PropertyORM.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> 开启了cocoapods的:generate_multiple_pod_projects => true后，出现link不过的情况，必须手动再把wcdb的framework添加进去
![image](https://user-images.githubusercontent.com/10009089/67660989-0293d280-f99b-11e9-90ea-3c242b26660f.png)。依赖关系如下：主项目通过pod引入了IMSDK，IMSDK的podspec中依赖了WCDB

**Comment by RingoD** [comment]
Well, I don't think we have `v1.1.1`.

**Comment by atomsongxiangwu** [comment]
> Well, I don't think we have `v1.1.1`.

sorry, my mistake, It's v1.0.7.5

**Comment by RingoD** [comment]
`generate_multiple_pod_projects` is not tested.

**Comment by atomsongxiangwu** [comment]
I have solved the problem. thx!

**Comment by kingslay** [comment]
> I have solved the problem. thx!

How did you solve this
