### ISSUE TITLE
内置的RepairKit能用于Android sqlite数据库的修复吗？如果可以，是否考虑将其独立出来？

### ISSUE THREAD

**Issue by paozhuanyinyu** [Tencent/wcdb#624]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
`RepairKit` is supported on Android.

**Comment by paozhuanyinyu** [comment]
> `RepairKit` is supported on Android.

我意思是是否支持普通的未加密的sqlite

**Comment by John-He-928** [comment]
RepairKit supports encrypted **and** plain-text databases on Android as well as iOS platform.
