### ISSUE TITLE
swift 编译错误

### ISSUE THREAD

**Issue by 121372288** [Tencent/wcdb#625]
### The language of WCDB

 Swift 

### The version of WCDB

 v1.8.0.2

### The platform of WCDB

 iOS

### The installation of WCDB

 Cocoapods

### What's the issue?

安装后无法编译  
Conditional conformance of type 'Array<Element>' to protocol 'ColumnDecodable' does not imply conformance to inherited protocol 'ColumnCodableBase'

Dictionary<Key, Value>以及 Set<Element>  都出现同样的错误

**Comment by RingoD** [comment]
Did you upgrade to the latest version of Xcode with Swift 5.1?

**Comment by 121372288** [comment]
我使用的是 Xcode10.1    swift4.2    编译时报的这个错误

**Comment by RingoD** [comment]
Then use v1.0.8 for Swift 4.2 or use v1.0.8 for Swift 5.x.
