### ISSUE TITLE
My project sometimes compile failed with this error : "fatal error: 'WCDB/config.hpp' file not found".

### ISSUE THREAD

**Issue by CroPort** [Tencent/wcdb#626]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.5

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

My project sometimes compile failed with error below:

```
CompileC /path/to/arm64/SomeModel.o path/to/SomeModel.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (1 failure)

In file /path/to/SomeModel.mm:10: In file included from /path/to/Pods/Headers/Public/WCDB/WCDB/WCDB.h:44: /path/to/Pods/Headers/Public/WCDB/WCDB/WCTDatabase+Core.h:23:9: fatal error: 'WCDB/config.hpp' file not found #import <WCDB/config.hpp> ^~~~~~~~~~~~~~~~~ 1 error generated.
```

It's not always failed, so I was confused about that, any idea?

**Comment by RingoD** [comment]
It's strange about compile failed randomly. Maybe it's an issue about `target dependencies`?
