### ISSUE TITLE
Android ANR (com.tencent.wcdb.database.SQLiteDatabaseLockedException)

### ISSUE THREAD

**Issue by Winstonokk** [Tencent/wcdb#628]
### The language of WCDB

>  Java 

### The version of WCDB

> v1.0.6.2

### The platform of WCDB

>  Android

### The installation of WCDB

> Maven

### What's the issue?
This bug happens by chance, but it will lead to ANR every time it appears.

![image](https://user-images.githubusercontent.com/16253450/68934200-32cbd580-07d1-11ea-8310-9b652a199858.png)
![image](https://user-images.githubusercontent.com/16253450/68934244-470fd280-07d1-11ea-8f5b-cff65acc1dd8.png)

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
