### ISSUE TITLE
crash WCDBSwift 

### ISSUE THREAD

**Issue by 937447974** [Tencent/wcdb#629]
0	WCDBSwift
$s9WCDBSwift10TimedQueueC02reC04withyx_tFSS_Tg5Tf4xn_n + 992
1	WCDBSwift
$s9WCDBSwift10TimedQueueC02reC04withyx_tFSS_Tg5Tf4xn_n + 356
2	WCDBSwift
$s9WCDBSwift8DatabaseC14defaultConfigs33_61483DD555A1004C392E92126BE4A25CLLAA0D0VvpZfiyAA6HandleCKcfU2_yAI_SiytSgtcfU_ + 452
3	WCDBSwift
$s9WCDBSwift6HandleC8register11onCommittedyyAC_SiytSgtc_tFs5Int32VSvSg_s13OpaquePointerVSgSPys4Int8VGSgAHtcfU_To + 88
4	sqlcipher
sqlite3_step + 572
5	WCDBSwift
$s9WCDBSwift15HandleStatementC4stepSbyKF + 44
6	WCDBSwift
$s9WCDBSwift6DeleteC7executeyyKF + 220
7	WCDBSwift
$s9WCDBSwift15DeleteInterfacePA2A4CoreCRbzrlE6delete9fromTable5where7orderBy5limit6offsetySS_AA21ExpressionConvertible_pSgSayAA05OrderN0_pGSgA2MtKFTf4xnnnnn_nAA11TransactionC_Tg5 + 488
8	WCDBSwift
$s9WCDBSwift8DatabaseCAA15DeleteInterfaceA2aDP6delete9fromTable5where7orderBy5limit6offsetySS_AA21ExpressionConvertible_pSgSayAA05OrderN0_pGSgA2MtKFTW + 12
9	BLCocoa
$s9WCDBSwift15DeleteInterfaceP7BLCocoaE6delete6objectyqd___tKAD16BLTableEncodableRd__lF + 260
10	BLSocket
$s8BLSocket13SocketServiceV12socketActionyyFZyyKcfU_ + 996
11	BLSocket
$s8BLSocket13SocketServiceV12socketActionyyFZyyKcfU_TA + 16
12	coswift
$s7coswift9CoroutineC7co_exec33_BE573CF296F1FD75CFFA582F2226558ALLyySvSgXCvpfiyAFcfU_ + 84
13	cocore
coroutine_main + 32

**Comment by RingoD** [comment]
Can it be reproduce?

**Comment by 937447974** [comment]
| 是否越狱 | 否
可用内存大小 | 48.55 MB ( 2.42% ) | 可用存储空间 | 10.08 GB ( 8.46% )
Bugly SDK版本号 | 2.5.0


0 WCDBSwift | $s9WCDBSwift10TimedQueueC02reC04withyx_tFSS_Tg5Tf4xn_n + 992
-- | --
1 WCDBSwift | $s9WCDBSwift10TimedQueueC02reC04withyx_tFSS_Tg5Tf4xn_n + 356
2 WCDBSwift | $s9WCDBSwift8DatabaseC14defaultConfigs33_61483DD555A1004C392E92126BE4A25CLLAA0D0VvpZfiyAA6HandleCKcfU2_yAI_SiytSgtcfU_ + 452
3 WCDBSwift | $s9WCDBSwift6HandleC8register11onCommittedyyAC_SiytSgtc_tFs5Int32VSvSg_s13OpaquePointerVSgSPys4Int8VGSgAHtcfU_To + 88
4 sqlcipher | sqlite3_step + 572
5 WCDBSwift | $s9WCDBSwift6InsertC7execute4withySayxG_tKAA14TableEncodableRzlF02doB6ObjectL_yyKAaGRzlF + 1144
6 WCDBSwift | $s9WCDBSwift6InsertC7execute4withySayxG_tKAA14TableEncodableRzlF + 196
7 WCDBSwift | $s9WCDBSwift15InsertInterfacePA2A4CoreCRbzrlE6insert7objects2on9intoTableySayqd__G_SayAA19PropertyConvertible_pGSgSStKAA0I9EncodableRd__lFTf4nnxn_nTm + 212
8 WCDBSwift | $s9WCDBSwift11TransactionCAA15InsertInterfaceA2aDP15insertOrReplace7objects2on9intoTableySayqd__G_SayAA19PropertyConvertible_pGSgSStKAA0K9EncodableRd__lFTWTm + 48
9 WCDBSwift | $s9WCDBSwift11TransactionCAA15InsertInterfaceA2aDP15insertOrReplace7objects2on9intoTableySayqd__G_SayAA19PropertyConvertible_pGSgSStKAA0K9EncodableRd__lFTW + 24
10 WCDBSwift | $s9WCDBSwift8DatabaseCAA15InsertInterfaceA2aDP15insertOrReplace7objects2on9intoTableySayqd__G_SayAA19PropertyConvertible_pGSgSStKAA0K9EncodableRd__lFTW + 12
11 BLCocoa | $s9WCDBSwift15InsertInterfaceP7BLCocoaE15insertOrReplace7objects2onySayqd__G_SayAA19PropertyConvertible_pGtKAA14TableEncodableRd__lF + 240
12 BLCocoa | $s9WCDBSwift15InsertInterfaceP7BLCocoaE15insertOrReplace7objects2onyqd__d_SayAA19PropertyConvertible_pGtKAA14TableEncodableRd__lF + 12
13 BLKanbanModule | $s14BLKanbanModule20KanbanViewControllerC13routerCanOpen4withSbSDySSypG_tF+ 860
14 BLKanbanModule | $s14BLKanbanModule20KanbanViewControllerC13routerCanOpen4withSbSDySSypG_tFTo + 96
15 YJCocoa | $s7YJCocoa11YJURLRouterC10openRouter33_B95230245CDFC516E174747E85593ECDLL8register7options10completionyAA16YJRouterRegisterAELLC_SDySSypGyAKcSgtF + 432
16 YJCocoa | $s7YJCocoa11YJURLRouterC14registerRouter33_B95230245CDFC516E174747E85593ECDLL0C0yAA16YJRouterRegisterAELLC_tFyypSg_yAIcSgtcfU_ + 276
17 YJCocoa | $s7YJCocoa11YJSchedulerC7publish5topic4data6serial10completionySS_ypSgSbyAIcSgtFyACcfU_yycfU_TA + 64
18 YJCocoa | $sIeg_IeyB_TR + 28
19 libdispatch.dylib | __dispatch_call_block_and_release + 24
20 libdispatch.dylib | __dispatch_client_callout + 16
21 libdispatch.dylib | __dispatch_main_queue_callback_4CF$VARIANT$mp + 1068
22 CoreFoundation | 0x000000019cee6000 + 697132
23 CoreFoundation | 0x000000019cee6000 + 676452
24 CoreFoundation | CFRunLoopRunSpecific + 436
25 GraphicsServices | GSEventRunModal + 104
26 UIKitCore | UIApplicationMain + 212
27 KBiPhone_Distribution | main (AppDelegate.swift:16)
28 libdyld.dylib | _start + 4

**Comment by CoderXO** [comment]
解决了吗？？？

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
