### ISSUE TITLE
unknown tokenizer: WCDB

### ISSUE THREAD

**Issue by xiongxiongjiang** [Tencent/wcdb#632]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Swift

### The version of WCDB

> e.g. v1.0.5

1.0.8.2

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

When I try to create virtual table, it reports "Message:unknown tokenizer: WCDB".

I copy this code from document:

```
        static var virtualTableBinding: VirtualTableBinding? {
            return VirtualTableBinding(with: .fts3, and: ModuleArgument(with: .WCDB))
        }
```

**Comment by damozhang** [comment]
@xiongxiongjiang 
Hi, I got a same issue. 
Did you find a solution? Hope you can share your experience.

Thanks

**Comment by lessSource** [comment]
@xiongxiongjiang
Hi, I got a same issue.
Did you find a solution? Hope you can share your experience.

Thanks

**Comment by eyuxin** [comment]
I resolve this issue by add "dataBase?.setTokenizes(.WCDB)" before create virtualTable.
