### ISSUE TITLE
SQLCipher upgraded to version 4?

### ISSUE THREAD

**Issue by JaminZhou** [Tencent/wcdb#634]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.8

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

Is SQLCipher upgraded to version 4? When will it be finished?
I saw someone asking in March.

**Comment by RingoD** [comment]
It's upgraded in `pre_v1.1.0` branch, but we haven't merge them into `master` now.

**Comment by yangbin911213** [comment]
when you merge them into master？

**Comment by RingoD** [comment]
It's ongoing.

**Comment by makehapi** [comment]
> It's ongoing.

请问什么时候能支持SQLCipher 4.2.0版本的，因为之前使用的是FMDB/SQLCipher（里面的SQLCipher就是4.2.0）创建的加密数据库，现在想迁移到WCDB上，但是却打不开原先的加密数据库

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
