### ISSUE TITLE
请问如何打开WCDB加密数据库

### ISSUE THREAD

**Issue by JayneVong** [Tencent/wcdb#635]
### The language of WCDB

> Java

### The version of WCDB

> 1.0.6.2

### The platform of WCDB

> Android

### The installation of WCDB

> api 'com.tencent.wcdb:wcdb-android:1.0.6.2'

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
SQLiteCipherSpec cipher = new SQLiteCipherSpec()
                    .setPageSize(1024)  
                    .setSQLCipherVersion(3);
使用以上方式创建的数据库，在Mac终端中如何打开呢？

GeorgeKingMac:databases king$ ls
encrypted_db.db
GeorgeKingMac:databases king$ sqlcipher encrypted_db.db
SQLCipher version 3.25.2 2018-09-25 19:08:10
Enter ".help" for usage hints.
sqlite> PRAGMA key = 'super-secret';
sqlite> PRAGMA kdf_iter = 64000;
sqlite> PRAGMA cipher_page_size = 1024;
sqlite> .table
Error: file is not a database
sqlite> .dbinfo
unable to read database header
sqlite>

**Comment by sumous** [comment]
sqlcipher version 3.4.1

`SQLCipher version 3.15.2 2016-11-28 19:13:37
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite>  PRAGMA key = 'xxxxx';
sqlite>  PRAGMA cipher_page_size = 4096;
sqlite> .table`

It works fine!

**Comment by huapeng222** [comment]
> ### The language of WCDB
> > Java
> 
> ### The version of WCDB
> > 1.0.6.2
> 
> ### The platform of WCDB
> > Android
> 
> ### The installation of WCDB
> > api 'com.tencent.wcdb:wcdb-android:1.0.6.2'
> 
> ### What's the issue?
> > Post the outputs or screenshots for errors.
> > Explain what you want by example or code **in English**.
> > SQLiteCipherSpec cipher = new SQLiteCipherSpec()
> > .setPageSize(1024)
> > .setSQLCipherVersion(3);
> > 使用以上方式创建的数据库，在Mac终端中如何打开呢？
> 
> GeorgeKingMac:databases king$ ls
> encrypted_db.db
> GeorgeKingMac:databases king$ sqlcipher encrypted_db.db
> SQLCipher version 3.25.2 2018-09-25 19:08:10
> Enter ".help" for usage hints.
> sqlite> PRAGMA key = 'super-secret';
> sqlite> PRAGMA kdf_iter = 64000;
> sqlite> PRAGMA cipher_page_size = 1024;
> sqlite> .table
> Error: file is not a database
> sqlite> .dbinfo
> unable to read database header
> sqlite>

mac 下可以使用DB Browser for SQLite,还有 Datum - Lite 
这两个都是免费的

**Comment by LZhenHong** [comment]
![image](https://user-images.githubusercontent.com/9366368/104127455-1a3b5900-539d-11eb-8d8c-778c6580c284.png)
这样配置然后输入密码就行了
