### ISSUE TITLE
兼容Androidx

### ISSUE THREAD

**Issue by kebeyDing** [Tencent/wcdb#637]
### The language of WCDB

>Java 

### The version of WCDB

> wcdb.room版本：1.0.8

### The platform of WCDB

>Android

### The installation of WCDB

> Git clone

### What's the issue?

目前没有兼容androidx，后面是否有考虑兼容？

**Comment by lixiaoshaxing** [comment]
同求

**Comment by wirteEable** [comment]
同求

**Comment by urtheone** [comment]
现在是不是依然不兼容Androidx?

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
