### ISSUE TITLE
WCDB是否支持sqlite3的case when语法

### ISSUE THREAD

**Issue by JsonKit** [Tencent/wcdb#639]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.7

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> WCDB是否支持sqlite3的case when语法,如果支持,怎么使用?
> WCDB怎么执行原生SQL语句?

**Comment by RingoD** [comment]
Well, before v1.1.0, it's not fully supported. You can check `expr.hpp` to see the interface.

But we already redesign it in `pre_v1.1.0` branch.
