### ISSUE TITLE
carthage update failed

### ISSUE THREAD

**Issue by atuooo** [Tencent/wcdb#640]
### The language of WCDB

> Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)
Target: x86_64-apple-darwin19.0.0

### The version of WCDB

> v1.0.8

### The platform of WCDB

> iOS

### The installation of WCDB

> Carthage

### What's the issue?

> carthage update
*** Fetching WCDB
*** Checking out WCDB at "v1.0.8"
*** xcodebuild output can be found in /var/folders/jd/hw80w8b136j27n300kgmwrjw0000gn/T/carthage-xcodebuild.WimWfm.log
*** Downloading WCDB.framework binary at "WCDB 1.0.8"
*** Building scheme "WCDB.swift" in WCDB.xcworkspace
Build Failed
	Task failed with exit code 65:
This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/jd/hw80w8b136j27n300kgmwrjw0000gn/T/carthage-xcodebuild.WimWfm.log

Log:

> Carthage/Checkouts/WCDB/swift/source/builtin/CodableType.swift:244:33: error: redundant conformance of 'Array<Element>' to protocol 'ColumnCodableBase'
extension Array: ColumnCodable, ColumnCodableBase where Element: Codable {

**Comment by RingoD** [comment]
Use v1.0.8.2.

**Comment by atuooo** [comment]
After using v1.0.8.2, Carthage build succeed. But occur the swift compiler error:

`Module 'WCDBSwift' was created for incompatible target x86_64-apple-macos10.9: /Users/ooatuoo/Desktop/Jike-Resource/Podcast-iOS/Carthage/Build/Mac/WCDBSwift.framework/Modules/WCDBSwift.swiftmodule/x86_64.swiftmodule`

**Comment by atuooo** [comment]
After using v1.0.8.2, carthage build succeed, but occur swift compile error:
`Module 'WCDBSwift' was created for incompatible target x86_64-apple-macos10.9: /Users/**/Carthage/Build/Mac/WCDBSwift.framework/Modules/WCDBSwift.swiftmodule/x86_64.swiftmodule`

**Comment by qyhongfan** [comment]
same

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
