### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by kindvoon** [Tencent/wcdb#643]
The language of WCDB
Swift
The version of WCDB
v1.0.8.2
The platform of WCDB
iOS
The installation of WCDB
Cocoapods
What's the issue?
WCDB.Swift必须使用 use_framework! 吗？
目前项目中没使用，所以集成时候也未添加use_framework!，会报WCDBOptimizedSQLCiper下sqlite3.h中宏找不到、sqlite3_tokenizer访问不到等相关错误

**Comment by RingoD** [comment]
Currently, yes.
