### ISSUE TITLE
通过WCTPropertyNamed获取对应类的WCTProperty不成功

### ISSUE THREAD

**Issue by BraveheartStone** [Tencent/wcdb#644]
### The language of WCDB

>  Objective-C

### The version of WCDB

> v1.0.7.5

### The platform of WCDB

>  iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> I want to use WCTPropertyNamed and get the corresponding properties of a class through a string.How should I use it.

**Comment by RingoD** [comment]
I think you should describe your issue more clearly. What's the problem while you using `WCTPropertyNamed `.
