### ISSUE TITLE
How to redirect

### ISSUE THREAD

**Issue by ygfygf** [Tencent/wcdb#645]
### The language of WCDB

> e.g. Objective-C

### The version of WCDB

> e.g. v1.0.7.5

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

//Full-Text-Search by `match`
    NSArray<WCTSampleFTSData *> *ftsDataArray = [databaseFTS getObjectsOfClass:WCTSampleFTSData.class fromTable:tableNameFTS where:WCTSampleFTSData.PropertyNamed(tableNameFTS).match("Eng*")];
    for (WCTSampleFTSData *ftsData in ftsDataArray) {
        NSLog(@"Match name:%@ content:%@", ftsData.name, ftsData.content);
    }

    //Full-Text-Search info by `match`
    //See http://www.sqlite.org/fts3.html#snippet for further information
    WCTOneRow *row = [databaseFTS getOneRowOnResults:{WCTSampleFTSData.PropertyNamed(tableNameFTS).snippet(), WCTSampleFTSData.PropertyNamed(tableNameFTS).offsets()} fromTable:tableNameFTS where:WCTSampleFTSData.PropertyNamed(tableNameFTS).match("12*")];
    NSLog(@"Snippet: %@ Offsets: %@", row[0], row[1]);

How is offset related to class? Can only be called twice？

**Comment by RingoD** [comment]
Well, I don't really understand what your problem is. Could you tell us what you expect?
