### ISSUE TITLE
The Crash on iOS associated with 'WCDB::Ticker:: secondsFromElapse' 

### ISSUE THREAD

**Issue by hxming2919** [Tencent/wcdb#646]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Objective-C

### The version of WCDB

> e.g. v1.0.5

1.0.6

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 

libobjc.A.dylib | objc_msgSend + 16
-- | --
1 MyAppXXX | void std::__1::__call_once_proxy<std::__1::tuple<WCDB::Ticker::secondsFromElapse(unsigned long long const&)::'lambda'()&&> >(void*) + 1269348
2 MyAppXXX | void std::__1::__call_once_proxy<std::__1::tuple<WCDB::Ticker::secondsFromElapse(unsigned long long const&)::'lambda'()&&> >(void*) + 601724
3 MyAppXXX | void std::__1::__call_once_proxy<std::__1::tuple<WCDB::Ticker::secondsFromElapse(unsigned long long const&)::'lambda'()&&> >(void*) + 768476
4 Foundation | ___NSThreadPerformPerform + 336
5 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
6 CoreFoundation | ___CFRunLoopDoSource0 + 88
7 CoreFoundation | ___CFRunLoopDoSources0 + 176
8 CoreFoundation | ___CFRunLoopRun + 1004
9 CoreFoundation | CFRunLoopRunSpecific + 436
10 Foundation | -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 300
11 MyAppXXX | void std::__1::__call_once_proxy<std::__1::tuple<WCDB::Ticker::secondsFromElapse(unsigned long long const&)::'lambda'()&&> >(void*) + 768192
12 Foundation | ___NSThread__start__ + 984
13 libsystem_pthread.dylib | __pthread_body + 128
14 libsystem_pthread.dylib | _pthread_start + 44

> Explain what you want by example or code **in English**.

This Crash will happen randomly ,Wanna get some help to find out what's happened?

**Comment by RingoD** [comment]
I notice your another issue: https://github.com/Tencent/wcdb/issues/647
Such randomly, unexpected crash, I think it may lead to some project issues. 
Could you reproduce this issue? Or try to rebuild a clean project with WCDB and non-other framework.

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
