### ISSUE TITLE
crash on [WCTSelectBase(NoARC) extractPropertyToObject:atIndex:withColumnBinding:] 

### ISSUE THREAD

**Issue by hxming2919** [Tencent/wcdb#647]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Objective-C,

### The version of WCDB

> e.g. v1.0.5

v1.0.6

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 0	libsystem_kernel.dylib
__pthread_kill + 8
1	libsystem_pthread.dylib
pthread_kill + 112
2	libsystem_c.dylib
abort + 140
3	libsystem_malloc.dylib
__nano_vet_and_size_of_live
4	libsystem_malloc.dylib
_nano_free + 220
5	CoreFoundation
__CFRelease + 1264
6	MyProXXX
-[WCTSelectBase(NoARC) extractPropertyToObject:atIndex:withColumnBinding:] (WCTSelectBase+NoARC.mm:196)
7	MyProXXX
-[WCTSelect allObjects] (WCTSelect.mm:0)
8	MyProXXX
-[WCTInterface(Convenient) getObjectsOfClass:fromTable:where:] (WCTInterface+Convenient.mm:0)
9	MyProXXX
+[MyProXXXBaseReportLogModel allDataType:reportedState:] (MyProXXX BaseReportLogModel.mm:0)
10	MyProXXX
__70-[MyProXXXBaseReporterCacheManager _reportDataWithDataArray:type:maxCount:]_block_invoke (MyProXXX BaseReporterCacheManager.m:0)
11	libdispatch.dylib
__dispatch_call_block_and_release + 24
12	libdispatch.dylib
__dispatch_client_callout + 16
13	libdispatch.dylib
__dispatch_queue_serial_drain + 928
14	libdispatch.dylib
__dispatch_queue_invoke + 652
15	libdispatch.dylib
__dispatch_root_queue_drain + 572
16	libdispatch.dylib
__dispatch_worker_thread3 + 124
17	libsystem_pthread.dylib
_pthread_wqthread + 1288
> Explain what you want by example or code **in English**.

my app crash randomly  on  [WCTSelectBase(NoARC) extractPropertyToObject:atIndex:withColumnBinding:] ,Wanna get some help to find out what's happened?

**Comment by RingoD** [comment]
Can it be reproduced?

**Comment by NBXXF** [comment]
这个解决了么？我也遇到了

**Comment by NBXXF** [comment]
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/14288893/211735249-8250a9ed-b756-423c-a27d-364888cce460.png">

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
