### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by xiongxiongjiang** [Tencent/wcdb#648]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Swift

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

在[文档](https://github.com/Tencent/wcdb/wiki/Swift-%e5%a2%9e%e5%88%a0%e6%9f%a5%e6%94%b9#%E6%8F%92%E5%85%A5%E6%93%8D%E4%BD%9C)中，对” insertOrReplace“的解释是“在主键一致时，新数据会覆盖旧数据”，我觉得这样的解释有点歧义。事实上在联合唯一约束一致时，新数据也会更新旧数据。

**Comment by RingoD** [comment]
You are right. It's updated now. Thanks.
