### ISSUE TITLE
按照静态库的引入步骤操作完成后，编译报错

### ISSUE THREAD

**Issue by jizhengzhu** [Tencent/wcdb#649]
### The language of WCDB

> Objective-C

### The version of WCDB

>  v1.1

### The platform of WCDB

> iOS

### The installation of WCDB

> Git clone

### What's the issue?

![20200103_104731](https://user-images.githubusercontent.com/17465139/71704676-a6c04c80-2e16-11ea-9e5a-02cfe52c2260.png)

Create a new project and follow the steps above. It will fail to compile.

**Comment by jizhengzhu** [comment]
iOS用静态库或动态库的引入步骤操作后，都会编译报错

**Comment by RingoD** [comment]
The language? commit hash or tag you cloned?
