### ISSUE TITLE
WCDB如何与FMDB共存啊？

### ISSUE THREAD

**Issue by LanceXZH** [Tencent/wcdb#650]
WCDB如何与FMDB共存啊？还是说，要使用WCDB，必须把FMDB从工程中移除？

**Comment by RingoD** [comment]
What's your problem while using WCDB and FMDB together?

**Comment by huapeng222** [comment]
> What's your problem while using WCDB and FMDB together?

使用 FMDB/SQLCipher 会crash,有什么办法,可以让fmdb 使用wcdb库里边的 sqlcipher

**Comment by huapeng222** [comment]
> > What's your problem while using WCDB and FMDB together?
> 
> 使用 FMDB/SQLCipher 会crash,有什么办法,可以让fmdb 使用wcdb库里边的 sqlcipher

已经找到解决方案,header patch 导入 "${PODS_ROOT}/Headers/Public/WCDBOptimizedSQLCipher"

FMDatabase.m 中引入 #import <WCDBOptimizedSQLCipher/sqlcipher/sqlite3.h>

**Comment by renmoqiqi** [comment]
> > > What's your problem while using WCDB and FMDB together?
> > 
> > 
> > 使用 FMDB/SQLCipher 会crash,有什么办法,可以让fmdb 使用wcdb库里边的 sqlcipher
> 
> 已经找到解决方案,header patch 导入 "${PODS_ROOT}/Headers/Public/WCDBOptimizedSQLCipher"
> 
> FMDatabase.m 中引入 #import <WCDBOptimizedSQLCipher/sqlcipher/sqlite3.h>

是低版本crash吗

**Comment by huapeng222** [comment]
> > > > What's your problem while using WCDB and FMDB together?
> > > 
> > > 
> > > 使用 FMDB/SQLCipher 会crash,有什么办法,可以让fmdb 使用wcdb库里边的 sqlcipher
> > 
> > 
> > 已经找到解决方案,header patch 导入 "${PODS_ROOT}/Headers/Public/WCDBOptimizedSQLCipher"
> > FMDatabase.m 中引入 #import <WCDBOptimizedSQLCipher/sqlcipher/sqlite3.h>
> 
> 是低版本crash吗

不是版本问题,wcdb里边已经集成了SQLCipher, 再使用pod 集成FMDB/SQLCipher,两边就会冲突,我的办法就是直接用wcdb里边的SQLCipher,只集成FMDB

**Comment by renmoqiqi** [comment]
> > > > > What's your problem while using WCDB and FMDB together?
> > > > 
> > > > 
> > > > 使用 FMDB/SQLCipher 会crash,有什么办法,可以让fmdb 使用wcdb库里边的 sqlcipher
> > > 
> > > 
> > > 已经找到解决方案,header patch 导入 "${PODS_ROOT}/Headers/Public/WCDBOptimizedSQLCipher"
> > > FMDatabase.m 中引入 #import <WCDBOptimizedSQLCipher/sqlcipher/sqlite3.h>
> > 
> > 
> > 是低版本crash吗
> 
> 不是版本问题,wcdb里边已经集成了SQLCipher, 再使用pod 集成FMDB/SQLCipher,两边就会冲突,我的办法就是直接用wcdb里边的SQLCipher,只集成FMDB

我使用FMDB/SQLCipher dyld: lazy symbol binding failed: Symbol not found: _sqlite3_key

**Comment by huapeng222** [comment]
可以参考我的,设置header path 引用wcdb 里边的SQLCipher,一样能加密的,不过,只能用1024位加密 @renmoqiqi

**Comment by makehapi** [comment]
FMDB/SQLCipher创建的加密数据库怎么迁移到WCDB上

**Comment by makehapi** [comment]
看了其他评论说，FMDB/SQLCipher (2.7.5)版本的SQLCipher是4.2.0的版本，而WCDB还不支持打开4.2.0版本的加密数据库

**Comment by makehapi** [comment]
希望微信团队尽快处理啊

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
