### ISSUE TITLE
WCDBOptimizedSQLCipher分支问题

### ISSUE THREAD

**Issue by jinean** [Tencent/wcdb#651]
### The language of WCDB
Objective-C

### The version of WCDB

WCDB (1.0.8.2)
WCDBOptimizedSQLCipher (1.2.1)

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?
我想把WCDBOptimizedSQLCipher 通过,:path =>的形式引入 ,
请问 我需要下https://github.com/Tencent/sqlcipher下的哪个归档 可以保证和目前pod上的1.2.1一致

**Comment by RingoD** [comment]
Well, you can clone the specified tag of the Github repo, then you would find the commit hash of sqlcipher there.
