### ISSUE TITLE
如何关闭 DEBUG 信息

### ISSUE THREAD

**Issue by gee1k** [Tencent/wcdb#652]
### The language of WCDB

> Swift

### The version of WCDB

> v1.0.8

### The platform of WCDB

> macOS

### The installation of WCDB

> Cocoapods

### What's the issue?
如何关闭下图所示的 DEBUG 信息，因为我的程序需要在命令行运行。每次运行时都提示这个。体验不是很好！望告知，谢谢 🤓

![image](https://user-images.githubusercontent.com/12059800/71509499-80eef100-28c6-11ea-85c7-cb473aca9922.png)

**Comment by RingoD** [comment]
It's already described in the tutorial. Check `globalTrace`.

**Comment by gee1k** [comment]
OK，thx！
