### ISSUE TITLE
com.tencent.wcdb.CursorWindowAllocationException

### ISSUE THREAD

**Issue by JinChangSheng** [Tencent/wcdb#654]
The language of WCDB
Java

The version of WCDB
WCDB.swift (1.0.6)

The platform of WCDB
Android

The installation of WCDB
Android pad

What's the issue?
I encountered this problem, the program temporary memory is relatively high, the cursor is closed.
com.tencent.wcdb.CursorWindowAllocationException
Cursor window allocation of 2048 kb failed.

**Comment by kekegdsz** [comment]
遇到了同样的问题+1

**Comment by dongliang0201** [comment]
+1

**Comment by BINBINXIAO** [comment]
+1

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
