### ISSUE TITLE
数据库损坏

### ISSUE THREAD

**Issue by lightai** [Tencent/wcdb#66]
使用Stetho查看数据库：chrome的开发者工具上查看数据库，chrome://inspect/#devices，很容易发生数据库损坏。数据库没有启用加密。
![wcdb](https://user-images.githubusercontent.com/995199/27425604-84c7621e-576b-11e7-9117-086de2f22925.PNG)

**Comment by lightai** [comment]
chrome查看数据库的同时，读取db，发生com.tencent.wcdb.database.SQLiteDatabaseCorruptException: database disk image is malformed (code 11, errno 0):

**Comment by John-He-928** [comment]
从log看，错误是 **从DB Header里读出来的 Page Count，和实际文件大小不符**。
出错位置在 sqlite3.c 的 64971 行：

```c
    if( (pBt->db->flags & SQLITE_RecoveryMode)==0 && nPage>nPageFile ){
      rc = SQLITE_CORRUPT_BKPT;
      goto page1_init_failed;
    }
```

这个应该是 SQLite 底层的问题，SQLite 官方不建议使用版本不一样的两个不同 SQLite 库同时访问同一个 DB，Stetho 应该是使用系统的 SQLite 库。 [SQLite 相关文档](https://sqlite.org/howtocorrupt.html#multiple_copies_of_sqlite_linked_into_the_same_applicationhttps://sqlite.org/howtocorrupt.html#multiple_copies_of_sqlite_linked_into_the_same_application)

如果需要同时使用Stetho，GitHub 上有适配 WCDB 的修改版本，支持加密
https://github.com/viviwen123/stetho
