### ISSUE TITLE
SQLiteConnection.nativeOpen 报native异常 signal 6 (SIGABRT)

### ISSUE THREAD

**Issue by weizhenguo321** [Tencent/wcdb#660]
### The language of WCDB

> Java 

### The version of WCDB

> 1.0.8

### The platform of WCDB

> Android

### The installation of WCDB

> Maven

### What's the issue?

signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'stack corruption detected (-fstack-protector)'
    r0  00000000  r1  00006fa0  r2  00000006  r3  00000008
    r4  00006939  r5  00006fa0  r6  a92ff60c  r7  0000010c
    r8  00000000  r9  b034cb10  sl  a6a8cbad  fp  00000006
    ip  a92ff648  sp  a92ff5f8  lr  e9bece6f  pc  e9be6528  cpsr  200d0030

backtrace:
    #00 pc 0001a528  /system/lib/libc.so (abort+63)
    #01 pc 00049c7d  /system/lib/libc.so (__stack_chk_fail+8)
    #02 pc 00065207  /lib/arm/libwcdb.so (sqlcipher_codec_pragma+1134)
    #03 pc 00000a32  /dev/ashmem/dalvik-LinearAlloc_26937_26985 (deleted)

build id:
    /system/lib/libc.so (BuildId: e8a95d2a73171dc45000479abefe26f8)
    /lib/arm/libwcdb.so (BuildId: 4a447821d940a657620c2a944011cc5761e5ac7a)
    /dev/ashmem/dalvik-LinearAlloc_26937_26985 (deleted) (BuildId: unknown)

stack:
         a92ff5b8  ffffffdf
         a92ff5bc  00000000
         a92ff5c0  7cc65d34
         a92ff5c4  7cc65d34
         a92ff5c8  00006939
         a92ff5cc  ed24884f  /system/bin/app_process32 (sigprocmask+182)
         a92ff5d0  16086800  /dev/ashmem/dalvik-main space (region space)_2699_2699 (deleted)
         a92ff5d4  00000049
         a92ff5d8  ffffffdf
         a92ff5dc  7cc65d34
         a92ff5e0  00006939
         a92ff5e4  00006fa0
         a92ff5e8  a92ff60c
         a92ff5ec  a92ff648
         a92ff5f0  00000000
         a92ff5f4  e9be651d  /system/lib/libc.so (abort+52)
    #00  a92ff5f8  e9c64218  [anon:.bss]
         a92ff5fc  a92ff648
         a92ff600  a6a8cbdb  /lib/arm/libwcdb.so
         a92ff604  e9c1ca6d  /system/lib/libc.so (async_safe_fatal_no_abort+36)
         a92ff608  00000049
         a92ff60c  ffffffdf
         a92ff610  adc44680  [anon:libc_malloc]
         a92ff614  00000000
         a92ff618  e9c64218  [anon:.bss]
         a92ff61c  a92ff648
         a92ff620  a6a8cbdb  /lib/arm/libwcdb.so
         a92ff624  e9c15c81  /system/lib/libc.so (__stack_chk_fail+12)
    #01  a92ff628  a92ff648
         a92ff62c  a6a2620b  /lib/arm/libwcdb.so (sqlcipher_codec_pragma+1138)
    #02  a92ff630  00000000
         a92ff634  00000000
         a92ff638  00000000
         a92ff63c  a92ff6a0
         a92ff640  a9204000
         a92ff644  a92ff6b0
         a92ff648  00000051
         a92ff64c  00000049
         a92ff650  b034cb60  [anon:libc_malloc]
         a92ff654  7cc65d34
         a92ff658  7cc65d34
         a92ff65c  ba50da34  /dev/ashmem/dalvik-LinearAlloc_26937_26985 (deleted)
    #03  a92ff660  00000004
         a92ff664  00000000
         a92ff668  a92ff9b0
         a92ff66c  00000001
         a92ff670  bf11ee00  [anon:libc_malloc]
         a92ff674  a92ff7a0
         a92ff678  a92ff72c
         a92ff67c  c852fdbf  /oat/arm/base.odex (deleted)
         a92ff680  00000000
         a92ff684  cfffffff  /dev/ashmem/dalvik-jit-code-cache_26937_26937 (deleted)
         a92ff688  7cc65d34
         a92ff68c  bf11ee00  [anon:libc_malloc]
         a92ff690  ba50da34  /dev/ashmem/dalvik-LinearAlloc_26937_26985 (deleted)
         a92ff694  00000000
         a92ff698  00000003
         a92ff69c  16087b28  /dev/ashmem/dalvik-main space (region space)_2699_2699 (deleted)

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
