### ISSUE TITLE
wcdb-room transitive dependency fails on gradle 5.1 and above

### ISSUE THREAD

**Issue by em020** [Tencent/wcdb#661]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

java

### The version of WCDB

> e.g. v1.0.5

1.0.8

### The platform of WCDB

> e.g. iOS, macOS or Android

Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

on gradle 5.1 and above,  if only claim dependency of wcdb-room, wcdb-android will not be downloaded.

**Comment by em020** [comment]
implementation "com.tencent.wcdb:room:${WCDB_VERSION}"

only above will not transitively downlaod wcdb-android, which is against your document.

**Comment by lixiaoshaxing** [comment]
How did it work？ thanks

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
