### ISSUE TITLE
如何迁移数据库文件？

### ISSUE THREAD

**Issue by SuiFeng** [Tencent/wcdb#663]
### The language of WCDB

Objective-C

### The version of WCDB

1.0.7.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

我们需要将数据库文件从cache目录迁移至document目录，如何做呢？

**Comment by RingoD** [comment]
close the database and move all related files.

**Comment by Qiuwen-chen** [comment]
You can use moveFiles method now.
