### ISSUE TITLE
COLLATE NOCASE in where clause

### ISSUE THREAD

**Issue by leonylcatwork** [Tencent/wcdb#665]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Objective-C

### The version of WCDB

> e.g. v1.0.5

1.0.7.5

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

How to implement the following please?
```
SELECT id, spelling FROM table WHERE spelling COLLATE NOCASE IN ('a', 'b')
```

**Comment by RingoD** [comment]
Try `pre_v1.1.0` branch.

**Comment by Qiuwen-chen** [comment]
Please try the latest version.
