### ISSUE TITLE
create table WITHOUT ROWID

### ISSUE THREAD

**Issue by leonylcatwork** [Tencent/wcdb#666]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Objective-C

### The version of WCDB

> e.g. v1.0.5

V1.0.7.5

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

**Question: how to create a table without rowid?**

```
CREATE TABLE BK_VOC_TB (
    id            TEXT    PRIMARY KEY DEFAULT NULL,
    count         INTEGER DEFAULT 0,
    flag          INTEGER DEFAULT 0,
    status        TEXT
)
WITHOUT ROWID;
```

**Comment by RingoD** [comment]
We disable `without rowid` feature since it may not be a good practice. 

Could you tell us why would you like to use it?

**Comment by leonylcatwork** [comment]
We are porting from FMDB and the original design of the table is without rowid. This table has huge number of rows and dedicated pk. Without rowid can save considerable amount of space, in a mobile device.

**Comment by RingoD** [comment]
SQLite takes up space at most 9 bytes per int, less in practice. It will not take more than 9MB for 1 million rows. In conclusion, I don't really believe that WITHOUT ROWID can save space. Maybe you should have a full test case.

Since historical data are already in this kind of structure, it's a reasonable demand. However, we have no plan for supporting this recently. Modifying the source code and it will not be hard.

**Comment by leonylcatwork** [comment]
Well we do have experiment on it. The reality is that the difference is significant. 
Our db is 201MB in total with "WITHOUT ROWID" and this table has 1.5 million rows. If we remove "WITHOUT ROWID" and rebuild the database all over again without changing anything else, it goes up to 258MB, 28.8% increase.

**Comment by leonylcatwork** [comment]
I have also created a test [https://github.com/leonylcatwork/WCDBTests](url)
WCDBTestsTests.mm -> -testWithoutRowid
1.5M rows in a table makes 41MB (19.7% ) difference.

**Comment by RingoD** [comment]
I notice that `getFilesWithError:` is called for getting the database size.
It's an interface to get the size of all database related files. However, what we considering is the size of the database file itself.
As a result, the real size should be used is the database size itself after running truncated checkpoint.

**Comment by leonylcatwork** [comment]
Well that is the actual size it takes on disk. When you do `[db close]` there aren't any other files besides xxx.db. And it really makes no difference if you check size with NSFileManager.

I run both with sqlite3_analyzer:

WITHOUT ROWID:
```
Page size in bytes................................ 4096      
Pages in the whole file (measured)................ 28618     
Pages in the whole file (calculated).............. 28618     
Pages that store data............................. 28618      100.0% 
Pages on the freelist (per header)................ 0            0.0% 
Pages on the freelist (calculated)................ 0            0.0% 
Pages of auto-vacuum overhead..................... 0            0.0% 
Number of tables in the database.................. 2         
Number of indices................................. 0         
Number of defined indices......................... 0         
Number of implied indices......................... 0         
Size of the file in bytes......................... 117219328 
Bytes of user payload stored...................... 100998542   86.2% 
```
 
WITH ROWID:
```
Page size in bytes................................ 4096      
Pages in the whole file (measured)................ 35643     
Pages in the whole file (calculated).............. 35643     
Pages that store data............................. 35643      100.0% 
Pages on the freelist (per header)................ 0            0.0% 
Pages on the freelist (calculated)................ 0            0.0% 
Pages of auto-vacuum overhead..................... 0            0.0% 
Number of tables in the database.................. 2         
Number of indices................................. 1         
Number of defined indices......................... 0         
Number of implied indices......................... 1         
Size of the file in bytes......................... 145993728 
Bytes of user payload stored...................... 100998542   69.2% 

```

Notice that, "Bytes of user payload stored" are the same. Meaning extra space is consumed by other stuff when enabling rowid. There are `1 index` and `1 implied index` with rowid. And there is really no other difference between the two database.

**Comment by RingoD** [comment]
Could your please upload your database file here?

**Comment by leonylcatwork** [comment]
This test repo has it: https://github.com/leonylcatwork/WCDBTests

**Comment by Qiuwen-chen** [comment]
You can use WCDB_WITHOUT_ROWID to config without rowid table since v2.0.0.
