### ISSUE TITLE
有计划支持 Mac Catalyst 么？

### ISSUE THREAD

**Issue by 94haox** [Tencent/wcdb#667]
Swift

是否有计划支持 Mac Catalyst ？

**Comment by RayJiang16** [comment]
想知道+1

**Comment by strangeliu** [comment]
在 Mac Catalyst 下使用没有任何问题

**Comment by RingoD** [comment]
What's the problem you met?

**Comment by 94haox** [comment]
In WCDBOptimizedSQLCipher/os_nix.c 
'gethostuuid' is unavailable: not available on macCatalyst

**Comment by 94haox** [comment]
[sqlcipher](https://github.com/sqlcipher/sqlcipher/pull/342)

this commit fixed the error of **sqlcipher** on macCatalyst.
can push the same change on WCDBOptimizedSQLCipher?

**Comment by TravelC** [comment]
Hi, wanted to check if there's any update on this, still getting the error with version 2.0.4.

**Comment by Qiuwen-chen** [comment]
Fixed in the latest version.
