### ISSUE TITLE
Xcode创建文件时找不到WCDB分类

### ISSUE THREAD

**Issue by githubhuxian** [Tencent/wcdb#670]
### The language of WCDB

> e.g. Objective-C

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

之前创建文件有这样的可以选择，现在没有了，这是为什么？
https://upload-images.jianshu.io/upload_images/2510972-8db851d3b7837fda.png?imageMogr2/auto-orient/strip|imageView2/2/w/1200/format/webp

**Comment by RingoD** [comment]
The image is broken. Could you please explain you issue more clearly?
