### ISSUE TITLE
cocoapods 导入问题

### ISSUE THREAD

**Issue by Dacilia** [Tencent/wcdb#671]
[!] Error installing WCDBOptimizedSQLCipher
[!] /usr/bin/git clone https://github.com/Tencent/sqlcipher.git /var/folders/b0/xstfp_qn4wn03qj5sqll6cw40000gn/T/d20200208-65426-1m5b4p8 --template=

Cloning into '/var/folders/b0/xstfp_qn4wn03qj5sqll6cw40000gn/T/d20200208-65426-1m5b4p8'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by RingoD** [comment]
This message usually indicates a connect error. Maybe you should find a better wifi or try google this message.

**Comment by wanglang** [comment]
Installing SDWebImage (3.8.3)
Installing SQLiteRepairKit (1.2.2)

[!] Error installing SQLiteRepairKit
[!] /usr/bin/git clone https://github.com/Tencent/wcdb.git /var/folders/st/n6yzlrhx1k9ft2t092pnv8c40000gn/T/d20200312-15023-kkgt61 --template= --single-branch --depth 1 --branch v1.0.8.2

Cloning into '/var/folders/st/n6yzlrhx1k9ft2t092pnv8c40000gn/T/d20200312-15023-kkgt61'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by wanglang** [comment]
我也遇到cocoapods集成的问题了，换了多个网络都不好使。

**Comment by ZhangD123** [comment]
您好，我也遇到这个问题，请问怎么解决的

**Comment by YangYueFan** [comment]
+1

**Comment by Nsobject11** [comment]
这个有解决方案吗？

**Comment by jinean** [comment]
"source": {
    "git": "https://github.com/Tencent/sqlcipher.git",
    "commit": "e2cca10d20773398468b915254c546f9fa5b1909"
  },
自己下载放本地吧
