### ISSUE TITLE
Incomplete definition of type 'struct sqlite3_value'

### ISSUE THREAD

**Issue by NicolasKim** [Tencent/wcdb#672]
主工程为swift iOS工程

依赖
'WCDB.swift', '1.0.8.2'
'私有pod'

私有pod中加入了sqlcipher  （sqlite.h,sqlite.c），除了sqlcipher提供的这两个文件，没有任何数据库相关的三方库。

编译期报错
`Incomplete definition of type 'struct sqlite3_value'`

这个问题该如何解决？

**Comment by RingoD** [comment]
It seems ok in my side. Could you provide more information about this?

**Comment by lizuba** [comment]
我这边也碰到同样的问题 在私有库中引用了sqlcipher ，然后提示redefinition of 'sqlite3_pcache_methods'。
错误如下：
xxx/sqlcipher.framework/Headers/sqlite3.h:7287:8: error: redefinition of 'sqlite3_pcache_methods'
struct sqlite3_pcache_methods {
       ^
/Applications/Xcode 10.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/usr/include/sqlite3.h:7749:8: note: previous definition is here
struct sqlite3_pcache_methods {

**Comment by foolzzz** [comment]
pod 'WCDB'

![image](https://user-images.githubusercontent.com/5143340/82974907-a450d000-a00d-11ea-8e16-a17c1a7ab4c8.png)

**Comment by foolzzz** [comment]
need help

platform :osx, '10.12'

**Comment by 1137155216** [comment]
想问下解决了么？同样的问题

**Comment by Qiuwen-chen** [comment]
Please try new version.
