### ISSUE TITLE
Any API for sqlite3_interrupt()?

### ISSUE THREAD

**Issue by leonylcatwork** [Tencent/wcdb#674]
### The language of WCDB
Objective
### The version of WCDB
v1.0.7.5
### The platform of WCDB
iOS
### The installation of WCDB
Cocoapods

### What's the issue?

We have some long running db task that we want to be able to interrupt if needed. When FMDB we have access to sqlite3_interrupt(). I cannot find that for WCDB. Please advise.

**Comment by RingoD** [comment]
No, there is no public interface for `sqlite_interrupt`.

**Comment by leonylcatwork** [comment]
Will we be getting one in future release?

**Comment by RingoD** [comment]
No, I think.

Here's the bad case. `sqlite_interrupt ` is something about multi-tasking. 
If the long running task thread happen to begin at the time after `sqlite_interrupt` but before the transaction of your new task, then `sqlite_interrupt` can not achieve your purpose. 
This is a low probability event. However, if something may happen, then it will happen.

**Comment by Qiuwen-chen** [comment]
You can use WCTCancellationSignal since v2.0.4.
