### ISSUE TITLE
通过静态库安装后,编译报错

### ISSUE THREAD

**Issue by JuneJuneCute** [Tencent/wcdb#675]
### The language of WCDB

Objective-C

### The version of WCDB

1.0.7

### The platform of WCDB

 iOS

### The installation of WCDB

Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
 1、Conflicting types for 'sqlite3Vacuum'
2、Use of undeclared identifier 'SQLITE_PREPARE_NO_VTAB'

**Comment by RingoD** [comment]
Was there another SQLite library in your project?
