### ISSUE TITLE
SIGSEGV(SEGV_MAPERR) sqlite3_register_mm_cipher+62

### ISSUE THREAD

**Issue by lizhangqu** [Tencent/wcdb#677]
### The language of WCDB

> Java 

### The version of WCDB

> v1.0.3

### The platform of WCDB

> Android

### The installation of WCDB

> Maven

### What's the issue?

>SIGSEGV(SEGV_MAPERR)
>1 #00 lr 0001d95f /data/data/**/lib/libwcdb.so (sqlite3_register_mm_cipher+62) [armeabi-v7a::a6536cb8339bd5360cb13d7f60d3106f]

Even if you fix it in [Workaround some Android devices failed to load ICU functions.](https://github.com/Tencent/wcdb/commit/9beffc64b184b968cc3853ac594662b637d3848f) it still happens.

### Devices
小米 MI 8, 小米 MI 8 SE, 小米 MI 9, 小米 MI 9 SE, 华为ELE AL00
 
### OS 
Android 10, Android 9, Android 8.1, Android 8.0, Android 7.1.1

**Comment by Qiuwen-chen** [comment]
Please try v2.1.0.
