### ISSUE TITLE
安装WCDB 失败

### ISSUE THREAD

**Issue by limeidong** [Tencent/wcdb#68]
我是通过静态库的方式安装的，我把下载下来的源文件中  apple 文件夹中的 WCDB.xcodeproj,拖到自己的项目中，然后 按照教程 配置 的Build Phases，这些都没有问题，就是最后引入头文件的时候，死活找不到这个 #import <WCDB/WCDB.h>  头文件。

**Comment by RingoD** [comment]
对比教程 https://github.com/Tencent/wcdb/wiki#安装 的按静态库安装，每一步对一下看是否有没有做错。
特别是`在你的项目工程配置的Build Phases->Linked Binary and Libraries中添加WCDB.framework。这里有两个WCDB.framework，需要添加WCDB iOS Static的target下的WCDB.framework。`这里是否有选错framework

**Comment by limeidong** [comment]
好的，问题已经解决，我用cocopods安装的。

**Comment by limeidong** [comment]
好的，问题已经解决，我用cocopods安装的。

**Comment by ui03** [comment]
cocopods 安装Installing WCDB (1.0.1)卡着不动了，你的也这样吗？

**Comment by RingoD** [comment]
@ui03 通常是网络问题，cocoapods的服务器不太好

**Comment by limeidong** [comment]
@ui03  我的现在也出现这个问题了，卡着不动，也不知道是不是网络问题，也看不到加载进度，愁人。

**Comment by RingoD** [comment]
网络问题
https://github.com/Tencent/wcdb/wiki/常见问题

**Comment by YL1989** [comment]
通过静态库安装，死活编译不过，从新安装几十次都不行，安装步骤对了一遍又一遍。
WCDB，从安装到放弃！
第一次用这么难搞的开源。

**Comment by RingoD** [comment]
@YL1989 请提供你的编译错误信息，或加入我们的QQ群详细讨论。光是吐槽解决不了任何问题，这里有更多的人正常安装并使用很久了。

**Comment by YL1989** [comment]
@RingoD  QQ群多少哦，哥哥。

**Comment by RingoD** [comment]
@YL1989  wiki第一句就是

**Comment by tigerZhang86** [comment]
@YL1989  请问你通过静态库方式最终安装成功了吗？

**Comment by ui03** [comment]
@tigerZhang86 静态库没有成功 我用的cocopods成功了

**Comment by karosLi** [comment]
静态库安装 other link flags 还需要加上 -l"c++"
