### ISSUE TITLE
求助 这个语句 怎么转换，使用WCDB

### ISSUE THREAD

**Issue by comlog** [Tencent/wcdb#680]
### The language of WCDB
> Objective-C

### The version of WCDB
>v1.0.5

### The platform of WCDB
> iOS

### The installation of WCDB
> Cocoapods

### What's the issue?

select l._max_seq, l._uid,l._name,l._display_name,l._portrait,l._gender,l._mobile,l._email,l._address,l._company,l._social,l._extra,l._type,l._update_dt,m._alias,r._alias from t_user as l left join t_friend as m on l._uid=m._friend_uid left join (select _mid, _alias from t_group_member where _gid = ? and _cur_target = ?) as r  on l._uid=r._mid where l._uid = ? limit 1

这个语句 怎么转换，使用WCDB

**Comment by RingoD** [comment]
I don't see where the difficulty is. Maybe you can try first and post more specified issue.
