### ISSUE TITLE
OC/Swift mixed project issue

### ISSUE THREAD

**Issue by NicolasKim** [Tencent/wcdb#681]
My project is OC/Swift mixed one.  I'm trying to use WCDB in both programing languages, but I don't wanna use both versions of WCDB which is WCDB and WCDB.swift,  I found that the swift version(WCDB.swift) is not just interface of WCDB, it's reprogramed by swift language.

**Comment by RingoD** [comment]
and what's your issue?

**Comment by Qiuwen-chen** [comment]
Now you can use one WCDB to support multi languages since v2.0.0.
