### ISSUE TITLE
#Thread (MMT2 #3) (crashed) libwcdb.so Caused by:libwcdb.so Fatal Exception:SIGILL / ILL_ILLOPC 0xd482a3e8

### ISSUE THREAD

**Issue by laipi007** [Tencent/wcdb#682]
### The language of WCDB

>Java 
java.lang.Runtime.nativeLoad(Runtime.java)
2
java.lang.Runtime.doLoad(Runtime.java:1072)
3
java.lang.Runtime.loadLibrary0(Runtime.java:987)
4
java.lang.System.loadLibrary(System.java:1530)
5
com.tencent.wcdb.database.SQLiteGlobal.<clinit>(SQLiteGlobal.java:69)
6
com.tencent.wcdb.database.SQLiteGlobal.loadLib(SQLiteGlobal.java)
7
com.tencent.wcdb.database.SQLiteOpenHelper.<clinit>(SQLiteOpenHelper.java:49)

### The version of WCDB

> v1.0.0

### The platform of WCDB

>  Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
Please try v2.1.0.
