### ISSUE TITLE
iOS cocopods添加的wcdb  一引用#import <WCDB/WCDB.h>编译就报错 

### ISSUE THREAD

**Issue by guoshengboy** [Tencent/wcdb#683]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Objective-C

### The version of WCDB
> e.g. v1.0.5
1.0.7.5

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
用pods安装好wcdb之后 如果不引用wcdb可以编译运行，一旦引用wcdb就编译报错
![image](https://user-images.githubusercontent.com/9675660/76292843-ed389880-62ea-11ea-94bf-83cde163df06.png)
![image](https://user-images.githubusercontent.com/9675660/76292877-fde90e80-62ea-11ea-9425-88b9bd1690b9.png)
![image](https://user-images.githubusercontent.com/9675660/76292903-0b9e9400-62eb-11ea-8f05-22440402d927.png)

> Explain what you want by example or code **in English**.

**Comment by RingoD** [comment]
Could you provide the full error log?

**Comment by heyehao2008** [comment]
#import <WCDB/WCDB.h>的.m文件必须改为.mm

**Comment by ke112** [comment]
点赞  我也遇到了这个问题   改成.mm,就好了.
