### ISSUE TITLE
事务插入10条数据，其中 1 条违反唯一约束，想让剩下9 条能正常插入。

### ISSUE THREAD

**Issue by tlin2011** [Tencent/wcdb#690]
### The language of WCDB

> e.g.  Swift

### The version of WCDB

> e.g. v1.0.8.2

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

 try AppsDatabaseManager.defaultManager.database.run(controllableTransaction: {
                do {
                    
                    // try AppsDatabaseManager.defaultManager.database.insert(objects: sport,sport2, intoTable: "sport")
                    try AppsDatabaseManager.defaultManager.database.insert(objects: sport, intoTable: "sport")
                    try AppsDatabaseManager.defaultManager.database.insert(objects: sport2, intoTable: "sport")
                    
                } catch let error as WCDBSwift.Error {
                    print("insert sport data rollback: \(error.type) \(error.code)")
                    if error.type == .sqlite && error.code.value == 19 {
                        print("continue")
                    }else {
                        return false
                    }
                }
                return true
            })

**Comment by tlin2011** [comment]
try AppsDatabaseManager.defaultManager.database.run(controllableTransaction: {
         do {

                // try AppsDatabaseManager.defaultManager.database.insert(objects: sport,sport2, intoTable: "sport")
                try AppsDatabaseManager.defaultManager.database.insert(objects: sport, intoTable: "sport")
                try AppsDatabaseManager.defaultManager.database.insert(objects: sport2, intoTable: "sport")
                
            } catch let error as WCDBSwift.Error {
                print("insert sport data rollback: \(error.type) \(error.code)")
                if error.type == .sqlite && error.code.value == 19 {
                    print("continue")
                }else {
                    return false
                }
            }
            return true
        })

**Comment by tlin2011** [comment]
catch 到 违反唯一约束，剩下数据仍然想继续提交！

**Comment by Jonwei** [comment]
那就不是事务操作了吧？可以不用不事务操作，直接for循环就可以了吧？

**Comment by Qiuwen-chen** [comment]
You can use insertOrIgnoreObjects method.
