### ISSUE TITLE
sqcipher 4.1.3迁移 

### ISSUE THREAD

**Issue by lqt30817** [Tencent/wcdb#691]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
Java

### The version of WCDB

> e.g. v1.0.5
1.0.8

### The platform of WCDB

> e.g. iOS, macOS or Android
Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

之前使用sqlcipher 4.1.3的，可以用原文件迁移过去吗？

**Comment by Qiuwen-chen** [comment]
Yes
