### ISSUE TITLE
数据库删除的问题

### ISSUE THREAD

**Issue by qz-wzf** [Tencent/wcdb#693]
### The language of WCDB

> e.g. Objective-C

### The version of WCDB

> e.g. v1.0.7.5

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

分月份创建多个数据库，怎么获取月份较早的数据库并进行删除数据库的操作

**Comment by Qiuwen-chen** [comment]
You can use -[WCTDatabase removeFilesWithError:].
