### ISSUE TITLE
wcdb在swift中使用是已经不支持类似于这种的where: KPerson.Properties.age < 0查询条件了吗

### ISSUE THREAD

**Issue by luluaidota** [Tencent/wcdb#694]
### The language of WCDB

> e.g.Swift

### The version of WCDB

> e.g. v1.0.8

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

let persons: [KPerson]? = KDBManager.share.getObjects(on: KPerson.Properties.all, fromTable: TB_Person, where: KPerson.Properties.age < 0)

类似于这种写法，报错 Binary operator '<' cannot be applied to operands of type 'KPerson.Properties' (aka 'KPerson.CodingKeys') and 'Int'

**Comment by ZClee128** [comment]
我也是，为什么要关闭

**Comment by zhuimengFIRE** [comment]
请问该怎么写呢
