### ISSUE TITLE
how to create dynamic where params?

### ISSUE THREAD

**Issue by lyly51** [Tencent/wcdb#697]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

swift

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

ios

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
pod

### What's the issue?

how to create dynamic params in where ?
I have array ids = [1,2,3,4,....] need to create select * from table where tagid = 1 and tagid =2 and ...

**Comment by Qiuwen-chen** [comment]
Use tag.in(ids)
