### ISSUE TITLE
当FundamentalValue的包含值为null时，调用FundamentalValue的int64Value，stringValue等value方法时，会返回一个默认值而不是nil

### ISSUE THREAD

**Issue by karlcool** [Tencent/wcdb#698]
### The language of WCDB

> Swift

### The version of WCDB

> v1.0.8.2

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

当FundamentalValue的包含值为null时（例如这个column不存在时），调用FundamentalValue的int64Value，stringValue等value方法时，会返回一个默认值而不是nil。尤其当使用int值的时候，会严重误导开发者。

**Comment by Qiuwen-chen** [comment]
Fixed in WCDB 2.0
