### ISSUE TITLE
增加android的 x86_64 支持

### ISSUE THREAD

**Issue by kirozhao** [Tencent/wcdb#7]
加速模拟器调试

**Comment by John-He-928** [comment]
这个只需要编译过x86_64的OpenSSL即可支持，之前是因为没有设备测就没有特别支持，如果有需求的话，近期即可加上

**Comment by silencezwm** [comment]
微信居然还会出现没有设备测试，666

**Comment by John-He-928** [comment]
已提交x86_64支持
Commit: [1f5b1d7](https://github.com/Tencent/wcdb/commit/1f5b1d72e8b4ddc7f45d35c497829e06018bfa4f)

后续合入master
