### ISSUE TITLE
使用WCDB_SYNTHESIZE运行奔溃

### ISSUE THREAD

**Issue by ui03** [Tencent/wcdb#70]
您好，我按文档使用静态库安装运行没有问题，@property(retain) NSString *content; 
WCDB_SYNTHESIZE(Message, content) 数据表字段为字符串类型运行奔溃

**# Message.h文件**

#import <Foundation/Foundation.h>
#import <WCDB/WCDB.h>
@interface Message : NSObject<WCTTableCoding>

@property int localID;
@property(retain) NSString *content;
@property(retain) NSDate *createTime;
@property(retain) NSDate *modifiedTime;
@property(assign) int unused;

//WCDB_PROPERTY宏在头文件声明需要绑定到数据库表的字段
WCDB_PROPERTY(localID)
WCDB_PROPERTY(content)
WCDB_PROPERTY(createTime)
WCDB_PROPERTY(modifiedTime)

 @end

# **Message.m文件**
#import "Message.h"

@implementation Message
WCDB_IMPLEMENTATION(Message)
WCDB_SYNTHESIZE(Message, localID)
WCDB_SYNTHESIZE(Message, content)
WCDB_SYNTHESIZE(Message, createTime)
WCDB_SYNTHESIZE(Message, modifiedTime)

@end

# **运行奔溃**

在最后一行代码处奔溃
![Uploading 屏幕快照 2017-06-23 上午9.51.11.png…]()

WCTColumnType WCTRuntimeObjCAccessor::GetColumnType(Class instanceClass, const std::string &propertyName)
{
    static const SEL ColumnTypeSelector = NSSelectorFromString(@"columnTypeForWCDB");
    Class propertyClass = GetPropertyClass(instanceClass, propertyName);
    IMP implementation = GetClassMethodImplementation(propertyClass, ColumnTypeSelector);
    using GetColumnTyper = WCTColumnType (*)(Class, SEL);
    return ((GetColumnTyper) implementation)(propertyClass, ColumnTypeSelector);
}

2017-06-23 09:51:09.307 MyDb[712:15875] +[NSString columnTypeForWCDB]: unrecognized selector sent to class 0x10d0d7c40
2017-06-23 09:51:09.318 MyDb[712:15875] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSString columnTypeForWCDB]: unrecognized selector sent to class 0x10d0d7c40'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010d8bfd4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010d27621e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d92fe44 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010d845005 ___forwarding___ + 1013
	4   CoreFoundation                      0x000000010d844b88 _CF_forwarding_prep_0 + 120
	5   MyDb                                0x000000010cbfd218 _ZN22WCTRuntimeObjCAccessor13GetColumnTypeEP10objc_classRKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE + 152
	6   MyDb                                0x000000010cbfcbc1 _ZN22WCTRuntimeObjCAccessorC2EP10objc_classRKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE + 257
	7   MyDb                                0x000000010cbfd265 _ZN22WCTRuntimeObjCAccessorC1EP10objc_classRKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE + 37
	8   MyDb                                0x000000010cbdc55b _ZN16WCTColumnBindingC2IU8__strongP8NSStringEEP10objc_classRKNSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEESE_PT_PNS6_9enable_ifIXsr16ColumnIsObjCTypeISF_EE5valueEvE4typeE + 123
	9   MyDb                                0x000000010cbdc4cd _ZN16WCTColumnBindingC1IU8__strongP8NSStringEEP10objc_classRKNSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEESE_PT_PNS6_9enable_ifIXsr16ColumnIsObjCTypeISF_EE5valueEvE4typeE + 61
	10  MyDb                                0x000000010cbd388b _ZN10WCTBinding16addColumnBindingIU8__strongP8NSStringEENSt3__110shared_ptrI16WCTColumnBindingEERKNS4_12basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEESF_ + 123
	11  MyDb                                0x000000010cbd36ed +[Message content] + 429
	12  MyDb                                0x000000010cbd3951 _ZNK3$_1clERNSt3__14listIK11WCTPropertyNS0_9allocatorIS3_EEEE + 49
	13  MyDb                                0x000000010cbdd558 __cxx_global_var_init.5 + 24
	14  MyDb                                0x000000010cbdd5f5 _GLOBAL__sub_I_Message.mm + 37
	15  ???                                 0x000000010ccb922b 0x0 + 4509635115
	16  ???                                 0x000000010ccb942e 0x0 + 4509635630
	17  ???                                 0x000000010ccb50bc 0x0 + 4509618364
	18  ???                                 0x000000010ccb423a 0x0 + 4509614650
	19  ???                                 0x000000010ccb42cf 0x0 + 4509614799
	20  ???                                 0x000000010ccaa066 0x0 + 4509573222
	21  ???                                 0x000000010ccad706 0x0 + 4509587206
	22  ???                                 0x000000010cca9249 0x0 + 4509569609
	23  ???                                 0x000000011bc33510 0x0 + 4760745232
	24  ???                                 0x000000011bc31a39 0x0 + 4760738361
	25  ???                                 0x000000011bc2d249 0x0 + 4760719945
	26  ???                                 0x000000011bc2d036 0x0 + 4760719414
	27  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by RingoD** [comment]
在`Build Setting`的`Other Linker Flags`中加上`-all_load`试试

**Comment by ui03** [comment]
@RingoD 不行，加上后报63个错
![Uploading 屏幕快照 2017-06-23 上午11.00.34.png…]()

**Comment by ui03** [comment]
@RingoD 


Undefined symbols for architecture x86_64:
  "_sqlite3_column_table_name", referenced from:
      WCDB::StatementHandle::getColumnTableName(int) in WCDB(handle_statement.o)
  "_sqlite3_column_name", referenced from:
      WCDB::StatementHandle::getColumnName(int) in WCDB(handle_statement.o)
  "_sqlite3_column_count", referenced from:
      WCDB::StatementHandle::getColumnCount() in WCDB(handle_statement.o)
  "_sqlite3_bind_int", referenced from:
      WCDB::StatementHandle::bindInteger32(int const&, int) in WCDB(handle_statement.o)
  "_sqlite3_db_handle", referenced from:
      WCDB::StatementHandle::resetBinding() in WCDB(handle_statement.o)
      WCDB::StatementHandle::step() in WCDB(handle_statement.o)
      WCDB::StatementHandle::finalize() in WCDB(handle_statement.o)
      WCDB::StatementHandle::getLastInsertedRowID() in WCDB(handle_statement.o)
  "_sqlcipher_codec_ctx_get_data", referenced from:
      _sqliterkCryptoDecode in WCDB(sqliterk_crypto.o)
  "_sqlite3_initialize", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
  "_sqlite3_column_double", referenced from:
      WCDB::StatementHandle::getDouble(int) in WCDB(handle_statement.o)
  "_sqlcipher_activate", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
  "_deflateEnd", referenced from:
      _sqliterk_save_master in WCDB(sqliterk_output.o)
  "_sqlcipher_codec_ctx_set_pagesize", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
  "_sqlcipher_codec_ctx_set_use_hmac", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
  "_sqlite3_column_type", referenced from:
      WCDB::StatementHandle::getType(int) in WCDB(handle_statement.o)
  "_sqlcipher_codec_ctx_get_pagesize", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
      _sqliterkCryptoDecode in WCDB(sqliterk_crypto.o)
  "_sqlite3_errstr", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
      _sqliterkCryptoDecode in WCDB(sqliterk_crypto.o)
  "_sqlite3_exec", referenced from:
      WCDB::Handle::exec(WCDB::Statement const&) in WCDB(handle.o)
      _sqliterk_output in WCDB(sqliterk_output.o)
      table_onParseColumn(sqliterk*, sqliterk_table*, sqliterk_column*) in WCDB(sqliterk_output.o)
  "_sqlite3_finalize", referenced from:
      fini_insert(sqliterk_output_ctx*) in WCDB(sqliterk_output.o)
      _sqliterk_save_master in WCDB(sqliterk_output.o)
      init_insert(sqliterk_output_ctx*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in WCDB(sqliterk_output.o)
      WCDB::StatementHandle::finalize() in WCDB(handle_statement.o)
  "_sqlcipher_deactivate", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
      _sqliterkCryptoFreeCodec in WCDB(sqliterk_crypto.o)
  "_sqlite3_key", referenced from:
      WCDB::Handle::setCipherKey(void const*, int) in WCDB(handle.o)
  "_sqlite3_value_dup", referenced from:
      init_insert(sqliterk_output_ctx*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in WCDB(sqliterk_output.o)
  "_sqlite3_open", referenced from:
      WCDB::Handle::open() in WCDB(handle.o)
  "_inflate", referenced from:
      inflate_read(__sFILE*, z_stream_s*, void*, unsigned int, CipherContext*) in WCDB(sqliterk_output.o)
  "_inflateEnd", referenced from:
      _sqliterk_load_master in WCDB(sqliterk_output.o)
  "_sqlcipher_codec_key_derive", referenced from:
      _sqliterkCryptoDecode in WCDB(sqliterk_crypto.o)
  "_sqlite3_wal_hook", referenced from:
      WCDB::Handle::registerCommitedHook(std::__1::function<void (WCDB::Handle*, int, void*)> const&, void*) in WCDB(handle.o)
  "_sqlcipher_codec_ctx_free", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
      _sqliterkCryptoFreeCodec in WCDB(sqliterk_crypto.o)
  "_sqlite3_column_int", referenced from:
      _sqliterk_save_master in WCDB(sqliterk_output.o)
      WCDB::StatementHandle::getInteger32(int) in WCDB(handle_statement.o)
  "_deflateInit_", referenced from:
      _sqliterk_save_master in WCDB(sqliterk_output.o)
  "_sqlite3_free", referenced from:
      _sqliterk_output in WCDB(sqliterk_output.o)
      table_onParseColumn(sqliterk*, sqliterk_table*, sqliterk_column*) in WCDB(sqliterk_output.o)
  "_sqlite3_bind_null", referenced from:
      table_onParseColumn(sqliterk*, sqliterk_table*, sqliterk_column*) in WCDB(sqliterk_output.o)
      WCDB::StatementHandle::bindNull(int) in WCDB(handle_statement.o)
  "_sqlite3_column_bytes", referenced from:
      _sqliterk_save_master in WCDB(sqliterk_output.o)
      WCDB::StatementHandle::getBLOB(int, int&) in WCDB(handle_statement.o)
  "_sqlite3_extended_errcode", referenced from:
      WCDB::Handle::close() in WCDB(handle.o)
      WCDB::Handle::isTableExists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in WCDB(handle.o)
      WCDB::Handle::prepare(WCDB::Statement const&) in WCDB(handle.o)
      WCDB::Handle::exec(WCDB::Statement const&) in WCDB(handle.o)
      WCDB::Handle::setCipherKey(void const*, int) in WCDB(handle.o)
      WCDB::StatementHandle::resetBinding() in WCDB(handle_statement.o)
      WCDB::StatementHandle::step() in WCDB(handle_statement.o)
      ...
  "_sqlite3_file_control", referenced from:
      _sqliterk_save_master in WCDB(sqliterk_output.o)
  "_sqlite3_column_int64", referenced from:
      WCDB::StatementHandle::getInteger64(int) in WCDB(handle_statement.o)
  "_sqlite3_column_text", referenced from:
      _sqliterk_save_master in WCDB(sqliterk_output.o)
      WCDB::StatementHandle::getText(int) in WCDB(handle_statement.o)
  "_sqlite3_value_free", referenced from:
      fini_insert(sqliterk_output_ctx*) in WCDB(sqliterk_output.o)
  "_sqlcipher_codec_ctx_init", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
  "_sqlcipher_codec_ctx_set_cipher", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
  "_sqlite3_bind_blob", referenced from:
      table_onParseColumn(sqliterk*, sqliterk_table*, sqliterk_column*) in WCDB(sqliterk_output.o)
      WCDB::StatementHandle::bindBLOB(void const* const&, int, int) in WCDB(handle_statement.o)
  "_sqlite3_bind_text", referenced from:
      table_onParseColumn(sqliterk*, sqliterk_table*, sqliterk_column*) in WCDB(sqliterk_output.o)
      WCDB::StatementHandle::bindText(char const* const&, int) in WCDB(handle_statement.o)
  "_sqlite3_column_blob", referenced from:
      WCDB::StatementHandle::getBLOB(int, int&) in WCDB(handle_statement.o)
  "_deflate", referenced from:
      _sqliterk_save_master in WCDB(sqliterk_output.o)
  "_sqlite3_step", referenced from:
      table_onParseColumn(sqliterk*, sqliterk_table*, sqliterk_column*) in WCDB(sqliterk_output.o)
      _sqliterk_save_master in WCDB(sqliterk_output.o)
      init_insert(sqliterk_output_ctx*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in WCDB(sqliterk_output.o)
      WCDB::StatementHandle::step() in WCDB(handle_statement.o)
  "_sqlite3_db_config", referenced from:
      WCDB::Handle::setConfig(WCDB::Handle::Config, bool) in WCDB(handle.o)
  "_sqlite3_db_filename", referenced from:
      _sqliterk_output in WCDB(sqliterk_output.o)
  "_sqlite3_sql", referenced from:
      WCDB::Handle::setTrace(std::__1::function<void (int, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned int, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, unsigned int> > > const&, long long const&)> const&)::$_1::operator()(unsigned int, void*, void*, void*) const in WCDB(handle.o)
      table_onParseColumn(sqliterk*, sqliterk_table*, sqliterk_column*) in WCDB(sqliterk_output.o)
      WCDB::StatementHandle::step() in WCDB(handle_statement.o)
  "_sqlite3_close", referenced from:
      WCDB::Handle::close() in WCDB(handle.o)
  "_sqlite3_bind_value", referenced from:
      table_onParseColumn(sqliterk*, sqliterk_table*, sqliterk_column*) in WCDB(sqliterk_output.o)
  "_inflateInit_", referenced from:
      _sqliterk_load_master in WCDB(sqliterk_output.o)
  "_sqlite3_bind_int64", referenced from:
      table_onParseColumn(sqliterk*, sqliterk_table*, sqliterk_column*) in WCDB(sqliterk_output.o)
      WCDB::StatementHandle::bindInteger64(long long const&, int) in WCDB(handle_statement.o)
  "_sqlite3_last_insert_rowid", referenced from:
      WCDB::Handle::getLastInsertedRowID() in WCDB(handle.o)
      WCDB::StatementHandle::getLastInsertedRowID() in WCDB(handle_statement.o)
  "_sqlite3_bind_double", referenced from:
      table_onParseColumn(sqliterk*, sqliterk_table*, sqliterk_column*) in WCDB(sqliterk_output.o)
      WCDB::StatementHandle::bindDouble(double const&, int) in WCDB(handle_statement.o)
  "_sqlite3_trace_v2", referenced from:
      WCDB::Handle::setTrace(std::__1::function<void (int, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned int, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, unsigned int> > > const&, long long const&)> const&) in WCDB(handle.o)
  "_sqlite3_table_column_metadata", referenced from:
      WCDB::Handle::isTableExists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in WCDB(handle.o)
  "_sqlcipher_codec_ctx_get_reservesize", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
  "_sqlite3_column_value", referenced from:
      init_insert(sqliterk_output_ctx*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in WCDB(sqliterk_output.o)
  "_sqlite3_reset", referenced from:
      table_onParseColumn(sqliterk*, sqliterk_table*, sqliterk_column*) in WCDB(sqliterk_output.o)
      WCDB::StatementHandle::resetBinding() in WCDB(handle_statement.o)
  "_sqlite3_prepare_v2", referenced from:
      WCDB::Handle::prepare(WCDB::Statement const&) in WCDB(handle.o)
      _sqliterk_save_master in WCDB(sqliterk_output.o)
      init_insert(sqliterk_output_ctx*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in WCDB(sqliterk_output.o)
  "_sqlcipher_codec_ctx_set_kdf_iter", referenced from:
      _sqliterkCryptoSetCipher in WCDB(sqliterk_crypto.o)
  "_sqlcipher_page_cipher", referenced from:
      _sqliterkCryptoDecode in WCDB(sqliterk_crypto.o)
  "_sqlite3_errmsg", referenced from:
      WCDB::Handle::close() in WCDB(handle.o)
      WCDB::Handle::open() in WCDB(handle.o)
      WCDB::Handle::isTableExists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in WCDB(handle.o)
      WCDB::Handle::prepare(WCDB::Statement const&) in WCDB(handle.o)
      WCDB::Handle::exec(WCDB::Statement const&) in WCDB(handle.o)
      WCDB::Handle::setCipherKey(void const*, int) in WCDB(handle.o)
      table_onParseColumn(sqliterk*, sqliterk_table*, sqliterk_column*) in WCDB(sqliterk_output.o)
      ...
  "_sqlite3_config", referenced from:
      WCDB::$_0::operator()() const in WCDB(handle.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by RingoD** [comment]
NSString的column coding是以category的形式在WCDB内的，静态库连接的时候可能没有将其链接进去，导致crash。

在`Other Linker Flags`中加上`-all_load`和`-ObjC`通常能解决。

**Comment by RingoD** [comment]
`Linked Binary and Libraries`中有添加正确的WCDB吗？

`在你的项目工程配置的Build Phases->Linked Binary and Libraries中添加WCDB.framework。这里有两个WCDB.framework，需要添加WCDB iOS Static的target下的WCDB.framework。`

**Comment by ui03** [comment]
@RingoD WCDB添加的是iOS Static的target下的WCDB.framework

我搭建好框架运行没问题，只添加WCDB_SYNTHESIZE(Message, localID)也没问题，表字段是字符串类型奔溃，使用WCTDatabase *database = [[WCTDatabase alloc] initWithPath:path];创建表的时候会报那63个错。现在加上-all_load一直运行不起来，是不是我搭建环境有问题啊？

**Comment by RingoD** [comment]
我有重现你的crash，并且在加上-all_load后解决了

**Comment by ui03** [comment]
@RingoD 那应该是我搭建环境有问题，我换个方式试试

**Comment by RingoD** [comment]
已在安装文档中注明`-all_load`和`-ObjC`

**Comment by ui03** [comment]
使用cocopods已解决，谢谢
