### ISSUE TITLE
wcdb  崩溃

### ISSUE THREAD

**Issue by zs58zs107** [Tencent/wcdb#701]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

OC

### The version of WCDB

> e.g. v1.0.5
1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS 

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

wcdb崩溃 

以下是堆栈信息

0 libobjc.A.dylib | objc_retain + 16
-- | --
1 libobjc.A.dylib | objc_storeStrong + 44
2 ZSEstae | std::__1::__list_imp<WCDB::Order const, std::__1::allocator<WCDB::Order const> >::clear() + 13883740
3 CoreFoundation | ___NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__ + 16
4 CoreFoundation | -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 208
5 ZSEstae | std::__1::__list_imp<WCDB::Order const, std::__1::allocator<WCDB::Order const> >::clear() + 13883468
6 Foundation | ___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
7 Foundation | -[NSBlockOperation main] + 100
8 Foundation | ___NSOPERATION_IS_INVOKING_MAIN__ + 20
9 Foundation | -[NSOperation start] + 732
10 Foundation | ___NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 20
11 Foundation | ___NSOQSchedule_f + 180
12 libdispatch.dylib | __dispatch_block_async_invoke2 + 104
13 libdispatch.dylib | __dispatch_client_callout + 16
14 libdispatch.dylib | __dispatch_continuation_pop$VARIANT$mp + 412
15 libdispatch.dylib | __dispatch_async_redirect_invoke + 788
16 libdispatch.dylib | __dispatch_root_queue_drain + 376
17 libdispatch.dylib | __dispatch_worker_thread2 + 128
18 libsystem_pthread.dylib | _pthread_wqthread + 212

[崩溃信息.docx](https://github.com/Tencent/wcdb/files/4453858/default.docx)

**Comment by Qiuwen-chen** [comment]
Please try WCDB 2.0 to see if this problem still exists
