### ISSUE TITLE
RecoverKit修复，数据丢失

### ISSUE THREAD

**Issue by geolo123** [Tencent/wcdb#703]
### The language of WCDB

> java

### The version of WCDB

>  v1.0.8

### The platform of WCDB

> Android

### The installation of WCDB

> Maven,

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

恢复,耗时:369225ms, failureCount:90097, successCount:801639
使用，RecoverKit修复，数据丢失了；失败了9万多；所以，折算恢复成功率只有80%左右；
被恢复的目标db文件是加密库；

**Comment by geolo123** [comment]
是不是我使用上有问题？还是说被神话了？

**Comment by huangzongwang** [comment]
恢复经常卡住有啥办法？

**Comment by Qiuwen-chen** [comment]
Please try v2.1.0. Data backup and recovery capabilities have been significantly improved.
