### ISSUE TITLE
Full text search for lettor or digit is incomplete

### ISSUE THREAD

**Issue by jeff201903** [Tencent/wcdb#704]
### The language of WCDB

> e.g. Objective-C

### The version of WCDB

> e.g. v1.0.7.5

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

sence:  
I have there message content like:  "you"  "out"  "yu".  when I first tapped "o" to search, there are only "out" can be search, the expected result is "you" "out".

but there message like: "你好" "好的" "来了，好的".  when I first tapped "好" to search, the expected result is right.

this is implement：

```
- (NSArray *)searchFTSLike:(NSString *)rex {
    const char *rexStr = [[NSString stringWithFormat:@"*%@*",rex] UTF8String];
    NSArray *ftsDatas = [self.ftsDB getObjectsOfClass:Message.class fromTable:kftsTable where:Message.msg.match(rexStr)];

    return ftsDatas;
}

```

So why full text search for lettor the result is incomplete?  and how to modify because I can't find the solution。thank you!

**Comment by Qiuwen-chen** [comment]
English words only support prefix search.
