### ISSUE TITLE
工程使用的FMDB/SQLCipher4.2.0迁移至WCDB后无法解密

### ISSUE THREAD

**Issue by flsv** [Tencent/wcdb#705]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Objective-C

### The version of WCDB

> e.g. v1.0.7.5

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

旧工程想从FMDB迁移到WCDB， 在工程中pod 'FMDB/SQLCipher'，导入了SQLCipher 4.2.0，迁移至WCDB后，无法解密数据库

**Comment by Leonw2229** [comment]
他们还没适配SQLCipher 4，我android线上用的就是4.x；还在等着呢

**Comment by flsv** [comment]
@Leonw2229  但是我看他们不是说升级到4.1.0了吗
 sqlcipher @ 7acb2ea   Upgrade SQLCipher to 4.1.0

**Comment by Leonw2229** [comment]
> @Leonw2229 但是我看他们不是说升级到4.1.0了吗
> sqlcipher @ 7acb2ea Upgrade SQLCipher to 4.1.0

emmm,他们应该是升级了没合并到正式版上吧

**Comment by makehapi** [comment]
打不开是因为SQLCipher4.2.0的原因吗，我这里也很尴尬，原先FMDB/SQLCipher 2.7.5   SQLCipher为4.2.0的版本创建的加密数据库，转成FMDB+WCDB就打不开了，希望尽快升级啊

**Comment by Qiuwen-chen** [comment]
WCDB 2.0 is published, please try.
