### ISSUE TITLE
创建数据库的时候报错

### ISSUE THREAD

**Issue by DargonLee** [Tencent/wcdb#707]
### The language of WCDB

> e.g. Objective-C, v1.0.7.5 iOS Cocoapods

创建数据库的时候报错

[WCDB][ERROR]Code:14, Type:SQLite, Tag:0, Op:1, Msg:unable to open database file,

**Comment by GitHubzhangbo** [comment]
同样的问题 有什么解决方法吗？

**Comment by Qiuwen-chen** [comment]
This problem may be due to the temporary failure of the system IO, you can try to restart the phone or upgrade the system.
