### ISSUE TITLE
线上偶现用户初始化数据库时，连接数据库异常。

### ISSUE THREAD

**Issue by chenshaolin520** [Tencent/wcdb#708]
### The language of WCDB

>java

### The version of WCDB

> e.g. v1.0.8

### The platform of WCDB

> e.g. Android

### The installation of WCDB

> e.g. AAR Package

### What's the issue?

> Caused by:com.tencent.wcdb.database.SQLiteException:not an error(code 0, errno 0): Could not open the datebase in read/write mode.
1 com.tencent.wcdb.database.SQLiteConnection.nativeOpen(Native Method)
2 com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java)
3 com.tencent.wcdb.database.SQLiteConnection.open(SQLiteConnection.java)
4 com.tencent.wcdb.database.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java)
5 com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java)
6 com.tencent.wcdb.database.SQLiteConnectionPool.open(SQLiteConnectionPool.java)
7 com.tencent.wcdb.database.SQLiteDataBase.openInner(SQLiteDateBase.java)
8 com.tencent.wcdb.database.SQLiteDataBase.open(SQLiteDateBase.java)
9 com.tencent.wcdb.database.SQLiteDateBase.openDateBase(SQLiteDateBase.java)

> 

Above is the error stack information, can you help analyze the reason？
Thank you ~

**Comment by Qiuwen-chen** [comment]
Please try v2.1.0.
