### ISSUE TITLE
archive problem

### ISSUE THREAD

**Issue by skyxian** [Tencent/wcdb#709]
The language of WCDB

Swift5.1.2

The version of WCDB

v1.0.8.2

The platform of WCDB

iOS

The installation of WCDB

Carthage 和 手动导入

What's the issue?

precondition：cocoapods is use use_modular_headers！（项目组件化有很多子组件）

Carthage问题：在demo中使用Carthage生成WCDBSwift.framework，然后将WCDBSwift.framework单独引入工程，配置路径：可以build，也可以打包成功，但是upload to appstore , 会报以下错误：
The bundle at 'xx.app/Frameworks/WCDBSwift.framework' contains disallowed file 'Frameworks'.</string>

手动导入（按照wcdb文档）问题：build正常，打包release也正常，但是archive adHoc环境的时候会报以下错误：
No such module 'WCDBSwift'(在 import WCDB.Swift 的地方)

**Comment by Qiuwen-chen** [comment]
It is not a WCDB related Problem.
