### ISSUE TITLE
Feature: 重新加密数据库

### ISSUE THREAD

**Issue by vsignsoft** [Tencent/wcdb#71]
1、前提条件：
已经存在一个sqlite数据库文件（用sqlite工具创建的），且存在数据库表；
无论表里是否有数据；
2、在macOS 上使用WCDB，加密该数据库，插入、读取数据库表，均失败；
给出错误信息：
[WCDB]Code:26, Type:SQLiteGlobal, Msg:file is encrypted or is not a database
[WCDB]Code:26, Type:SQLite, Tag:0, Op:3, ExtCode:26, Msg:file is encrypted or is not a database, SQL:PRAGMA journal_mode, Path:/Users/xxx/Library/Developer/Xcode/DerivedData/WCDB-efjqwwcdtedcwhbdbmttflouwhzg/Build/Products/Debug/SampleDB/WCTSampleAdvance.SQLite
3、如果使用 WCDB 不加密该数据库，插入、读取数据库表，都会成功；
4、用各种sqlite工具，均可打开该数据库；

总结：
只要是外界创建好的sqlite数据库，用WCDB来加密，随后的数据库操作都会失败！
均报上面的错误；

---- 以下为加密、操作代码 ----
NSString *className = NSStringFromClass(WCTSampleAdvance.class);
NSString *path = [[baseDirectory stringByAppendingPathComponent:className] stringByAppendingString:@".SQLite"];
NSString *tableName = className;
WCTDatabase *database = [[WCTDatabase alloc] initWithPath:path];
    
// cipher
NSData *key = [@"password" dataUsingEncoding:NSUTF8StringEncoding];
[database setCipherKey:key];

// operation
WCTSampleAdvance *obj = [[WCTSampleAdvance alloc] init];
obj.intValue = 110;
BOOL ret = [database insertObject:obj into:tableName];

ret 返回NO;
报出错误：
[WCDB]Code:26, Type:SQLiteGlobal, Msg:file is encrypted or is not a database
[WCDB]Code:26, Type:SQLite, Tag:0, Op:3, ExtCode:26, Msg:file is encrypted or is not a database, SQL:PRAGMA journal_mode, Path:/Users/xxx/Library/Developer/Xcode/DerivedData/WCDB-efjqwwcdtedcwhbdbmttflouwhzg/Build/Products/Debug/SampleDB/WCTSampleAdvance.SQLite

**Comment by RingoD** [comment]
`setCipherKey:`是设置密钥，对于一个未加密的数据库，设置密钥尝试解密，自然不成功的。

**Comment by vsignsoft** [comment]
我的需求是这样的：
期望利用WCDB 对未加密的数据库，进行加密；

请问，WCDB 是否提供这样的接口？

P.S. 
我用WCDB 创建数据库，再利用 [database setCipherKey:key] 对数据库加密是可以的；

**Comment by RingoD** [comment]
后续考虑加上对未加密数据库加密的接口，但并不建议这么做，因为重新加密是很耗性能的。

用WCDB可以是因为此时SQLite数据库还未创建。

**Comment by vsignsoft** [comment]
@RingoD 非常感谢！

**Comment by RingoD** [comment]
等待开发

**Comment by RingoD** [comment]
添加了attach statement和detach statement

你可以根据使用sqlcipher_export进行重新加密，请参考https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export

**Comment by tigerZhang86** [comment]
@vsignsoft 请问你使用 attach statement 进行重新加密了吗？

**Comment by dulingkang** [comment]
@RingoD  这一句在WCDB中如何调用， ``` SELECT sqlcipher_export('encrypted'); ```

**Comment by RingoD** [comment]
请参考核心层接口：https://github.com/Tencent/wcdb/wiki/基础类、CRUD与Transaction#核心层接口

**Comment by tigerZhang86** [comment]
@dulingkang 你好，请问 SELECT sqlcipher_export('encrypted') 这个你写出来吗？

**Comment by huchpi0226** [comment]
@RingoD，SELECT sqlcipher_export('encrypted');，你说参考核心层接口写，还是没写出来，请贴下代码呗，谢谢。

**Comment by RingoD** [comment]
@huchpi0226 大致的代码为：`Statement().select(Expr::Function("sqlcipher_export", "encrypted"))`，可自己再微调下。
这里近期我们会重构文档，提供更多例子。

**Comment by dslcoding** [comment]
你好，我也是有这个需求。能不能把相关的代码贴出来吗？我现在有一个现成的数库文件。想用wcdb加密之后，再访问，数据。
