### ISSUE TITLE
访问数据时数据库报错

### ISSUE THREAD

**Issue by Wang-Meng** [Tencent/wcdb#711]
### The language of WCDB

Java 

### The version of WCDB

1.0.8

### The platform of WCDB

Android

### The installation of WCDB

Maven

### What's the issue?

error when query：
Caused by: java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
AndroidRuntime: 	at com.tencent.wcdb.CursorWindow.nativeGetLong(Native Method)
AndroidRuntime: 	at com.tencent.wcdb.CursorWindow.e(Unknown Source:8)
AndroidRuntime: 	at com.tencent.wcdb.CursorWindow.d(Unknown Source:0)

I found the resolution recently：https://github.com/Tencent/wcdb/commit/54be7f223be0cef1bae4362d2ddf8a862d7780d5
But，Android release version is not update. Waiting for update！

**Comment by Qiuwen-chen** [comment]
Please try v2.1.0.
