### ISSUE TITLE
添加Package.swift文件支持

### ISSUE THREAD

**Issue by mrsunx** [Tencent/wcdb#712]
### The language of WCDB
Swift

### The version of WCDB
1.0.8.2

### The platform of WCDB
ios

### The installation of WCDB
Cocoapods

### What's the issue?
可以支持Swift Package Manager么。

**Comment by Qiuwen-chen** [comment]
Please try v2.1.0.

**Comment by mrsunx** [comment]
好像会报错 

The package product 'WCDBSwift' cannot be used as a dependency of this target because it uses unsafe build flags.

**Comment by Qiuwen-chen** [comment]
Indeed, SwiftPM's requirements are very strict. For now, you can add the wcdb package by branch instead of version number, which can temporarily avoid this problem.

This problem will be fixed in the next version.

**Comment by Qiuwen-chen** [comment]
> 好像会报错
> 
> The package product 'WCDBSwift' cannot be used as a dependency of this target because it uses unsafe build flags.

Fixed in the latest version.
