### ISSUE TITLE
wcdb有计划升级所支持的sqlcipher到更高或者最新版本？

### ISSUE THREAD

**Issue by baidusoso** [Tencent/wcdb#713]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
Java

### The version of WCDB

> e.g. v1.0.5
v1.1

### The platform of WCDB

> e.g. iOS, macOS or Android
Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
Git clone

### What's the issue?

目前wcdb支持的sqlcipher最新版本是v4.1.0，对应sqlite v3.27.2；而sqlcipher已经升级到v4.4.0,对应的sqlite v3.31.0。sqlite这些升级修复好几个critical的bug。

wcdb有计划升级所支持的sqlcipher到更高或者最新版本？

thx

**Comment by Qiuwen-chen** [comment]
No plans yet
