### ISSUE TITLE
JUST REOPEN ISSUES:#611

### ISSUE THREAD

**Issue by mustlogin** [Tencent/wcdb#715]
### The language of WCDB

Objective-C

### The version of WCDB

master, last version

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

###  What's the issue?

I reopen the issue [#611](https://github.com/Tencent/wcdb/issues/611#issue-505587423).
Please look : [my reply](https://github.com/Tencent/wcdb/issues/611#issuecomment-631938356)

**Comment by Qiuwen-chen** [comment]
WCDB 2.0 rewrites the logic of OC ORM.
