### ISSUE TITLE
cocoapods macOS 集成 缺少库

### ISSUE THREAD

**Issue by foolzzz** [Tencent/wcdb#720]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Objective-C

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

macOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

缺少 sqlcipher.framework
缺少 sqliterk.framework

**Comment by comlog** [comment]
请问 你解决了吗？

**Comment by Qiuwen-chen** [comment]
Please try WCDB 2.0 to see if this problem still exists.
