### ISSUE TITLE
WCDBSwift 与 邮件发送冲突

### ISSUE THREAD

**Issue by tpian928** [Tencent/wcdb#722]
### The language of WCDB
Swift

### The version of WCDB
v1.0.8.2

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?
与MessageUI 中的邮件发送冲突，如果在UIViewContoller中
```
import WCDBSwift
```
则发送邮件后的回调方法不可用
```
    func mailComposeController(_ controller: MFMailComposeViewController, didFinishWith result: MFMailComposeResult, error: Error?) {
        controller.dismiss(animated: true, completion: nil)
    }
```

**Comment by ioser-wzp** [comment]
继承以后，所有包含Error的回掉都不会执行了，系统和第三方的回调都是如此

**Comment by Qiuwen-chen** [comment]
Fixed in WCDB 2.0
