### ISSUE TITLE
大厂的开源为啥不能长久更新下去呢？？？

### ISSUE THREAD

**Issue by sunlight2728** [Tencent/wcdb#724]
大哥们
优化优化
更新更新
为啥国内的代码坚持不了几天
不能长久的做下去呢
这一年多没更新了
这样会对微信的开源工具 失去信心的

腾讯是，微信也是，阿里也是，各种厂子都差不多

慢慢的
慢慢的
大厂开源的
再也不敢用下去了

AFNetworking  最远的一个文件都六年了

国内程序员之悲哀

呜呼哀哉

**Comment by luluuyu** [comment]
同问，什么时候才会更新呢

**Comment by 378804441** [comment]
KPI项目呗。当时开源团队人员估计都换了n茬了。谁愿意去维护一个开源项目

**Comment by liujixi1992** [comment]
主要国内开源项目只是为了开源。。

**Comment by sunlight2728** [comment]
开来大厂的开源没法子用了

**Comment by tigerzhang08** [comment]
开源项目本身就存在时间久了无人维护的情况，只不过在国内开源项目大都和 KPI 相关联，业务和部门变动都可能导致后续项目无人维护（毕竟没有时间和金钱支持），如果有能力就自己 fork 一份改改，否则只能另辟蹊径。

**Comment by HuangSenhui** [comment]
出现新Bug了吗？为什么一定要有更新才踏实？

**Comment by Jinxiansen** [comment]
。

**Comment by Qiuwen-chen** [comment]
New version of WCDB will be release soon, please wait.
