### ISSUE TITLE
新增字段默认值为空, 想设置默认值, 没找到相关内容,希望回复

### ISSUE THREAD

**Issue by yuangaopeng** [Tencent/wcdb#725]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by BartSimpsons** [comment]
WCDB_SYNTHESIZE_DEFAULT(xxxxxxxx, xxx, @"")
