### ISSUE TITLE
不支持cocoapods 静态导入吗

### ISSUE THREAD

**Issue by chunxige** [Tencent/wcdb#726]
### The language of WCDB

>  Swift

### The installation of WCDB

Cocoapods

**Comment by xuzhongping** [comment]
同问，使用静态链接后，虽然能编译成功，但是在数据库操作时一直失败，很好奇这个库必须要动态链接的原因是啥

**Comment by cntrump** [comment]
> 同问，使用静态链接后，虽然能编译成功，但是在数据库操作时一直失败，很好奇这个库必须要动态链接的原因是啥

因为编译需要依赖 sqlcipher 而不是系统的 sqlite，动态编译坑可能会少一点。也可以自己改成静态的，需要去掉项目里链接的 sqlite，如果有的话。
