### ISSUE TITLE
建表时userId变成了accountId 结果报错

### ISSUE THREAD

**Issue by icofans** [Tencent/wcdb#73]
#import <Foundation/Foundation.h>
#import <WCDB.h>

@interface Account : NSObject <WCTTableCoding>

@property(nonatomic,copy) NSString *userId;

@property(nonatomic,copy) NSString *mobile;

@property(nonatomic,copy) NSString *clientId;

@property(nonatomic,copy) NSString *realName;

@property(nonatomic,assign) NSInteger accountType;

@property(nonatomic,copy) NSString *tenantName;

@property(nonatomic,copy) NSString *tenantShortName;

@property(nonatomic,copy) NSString *address;

@property(nonatomic,copy) NSString *headImage;

@property(nonatomic,copy) NSString *menuTree;

WCDB_PROPERTY(userId)
WCDB_PROPERTY(mobile)
WCDB_PROPERTY(clientId)
WCDB_PROPERTY(realName)
WCDB_PROPERTY(accountType)
WCDB_PROPERTY(address)
WCDB_PROPERTY(headImage)
WCDB_PROPERTY(menuTree)
WCDB_PROPERTY(tenantName)
WCDB_PROPERTY(tenantShortName)
@end

使用上面对象建表时 为什么userId变成了accountId 结果报错

[WCDB]Code:1, Type:Warning, Msg:Skip column named [id] for table [account]
[WCDB]Code:1, Type:Warning, Msg:Skip column named [accountId] for table [account]
[WCDB]Code:1, Type:Warning, Msg:Skip column named [mobile] for table [account]
[WCDB]Code:1, Type:Warning, Msg:Skip column named [realName] for table [account]
[WCDB]Code:1, Type:Warning, Msg:Skip column named [accountType] for table [account]
[WCDB]Code:1, Type:Warning, Msg:Skip column named [headImage] for table [account]
[WCDB]Code:1, Type:Warning, Msg:Skip column named [clientId] for table [account]
[WCDB]Code:1, Type:Warning, Msg:Skip column named [orgName] for table [account]
[WCDB]Code:1, Type:Warning, Msg:Skip column named [orgShortName] for table [account]
[WCDB]Code:1, Type:Warning, Msg:Skip column named [address] for table [account]
[WCDB]Code:1, Type:Warning, Msg:Skip column named [menuTree] for table [account]
[WCDB]Code:1, Type:SQLiteGlobal, Msg:Cannot add a PRIMARY KEY column
[WCDB]Code:1, Type:SQLite, Tag:0, Op:4, ExtCode:1, Msg:Cannot add a PRIMARY KEY column, SQL:ALTER TABLE account ADD COLUMN userId TEXT PRIMARY KEY, Path:/var/mobile/Containers/Data/Application/2F17F302-0338-4E05-827A-8F2039BADC85/Library/Caches/accountInfo/account.db

**Comment by RingoD** [comment]
应该是你的表内原来已经有一个accountId的字段，然后你将其重新命名为了userId。
请参考：https://github.com/Tencent/wcdb/wiki/ORM使用教程#修改字段
