### ISSUE TITLE
使用字段宏（WCDB_SYNTHESIZE）会编译生成c++全局对象初始化方法，影响冷启动时间，有优化方法吗

### ISSUE THREAD

**Issue by Litt1er** [Tencent/wcdb#735]
![image](https://user-images.githubusercontent.com/16396128/86228904-902a6080-bbc1-11ea-9836-5291e9f18d3e.png)

**Comment by Charming04** [comment]
这个有办法优化么

**Comment by Qiuwen-chen** [comment]
We will optimize this problem in the next version soon, please wait.
