### ISSUE TITLE
需求：如何实现不确定查询条件数量的复杂查询？

### ISSUE THREAD

**Issue by onTheWa** [Tencent/wcdb#736]
### The language of WCDB

> e.g. Objective-C

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

    我现在有个需求：比如数据有status、name、size、weight等字段，
查询条件是用户控制的，我无法确定用户选择那些字段进行查询，
这种需求的查询如何实现呢？查询条件的WCTCondition类是否有提供这样的接口可以让我组装查询条件？

**Comment by onTheWa** [comment]
![截屏2020-07-02下午7 19 50](https://user-images.githubusercontent.com/20084586/86352929-27aeb280-bc99-11ea-9ca1-baea8b6cbe13.png)
类似这样的需求，查询条件的数量取决于用户的操作，我如何把这些条件组合起来查询出用户需要的数据呢？

**Comment by ZhangXueFei** [comment]
自定义 WCTCondition,每个条件都生成一个查询语句，最后根据需求拼接出一个完整的查询条件。demo中有这样例子
