### ISSUE TITLE
Crash  in probability when app enter background mode

### ISSUE THREAD

**Issue by SeraZheng** [Tencent/wcdb#737]
### The language of WCDB
OC
### The version of WCDB

1.0.7.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 1
WCDB WCDB::TimedQueue<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::waitUntilExpired(std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)> const&, bool) [__mutex_base : 130 + 0x4]
WCDB WCDB::Database::$_3::operator()(std::__1::shared_ptr<WCDB::Handle>&, WCDB::Error&) const::'lambda'(WCDB::Handle*, int, void*)::operator()(WCDB::Handle*, int, void*) const::'lambda'()::operator()() const [database_config.cpp : 214 + 0xc]

> 2
WCDB std::__1::__function::__func<WCDB::Database::$_3::operator()(std::__1::shared_ptr<WCDB::Handle>&, WCDB::Error&) const::'lambda'(WCDB::Handle*, int, void*)::operator()(WCDB::Handle*, int, void*) const::'lambda'()::operator()() const::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), std::__1::allocator<WCDB::Database::$_3::operator()(std::__1::shared_ptr<WCDB::Handle>&, WCDB::Error&) const::'lambda'(WCDB::Handle*, int, void*)::operator()(WCDB::Handle*, int, void*) const::'lambda'()::operator()() const::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) [recyclable.hpp : 71 + 0x0]
WCDB WCDB::TimedQueue<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::waitUntilExpired(std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)> const&, bool) [functional : 1860 + 0xc]
WCDB WCDB::Database::$_3::operator()(std::__1::shared_ptr<WCDB::Handle>&, WCDB::Error&) const::'lambda'(WCDB::Handle*, int, void*)::operator()(WCDB::Handle*, int, void*) const::'lambda'()::operator()() const [database_config.cpp : 214 + 0xc]

**Comment by Millionaryearl** [comment]
any progress

**Comment by Qiuwen-chen** [comment]
We will optimize this problem in the next version soon, please wait.
