### ISSUE TITLE
【建议】增加判断某个字段是否已经存在的接口

### ISSUE THREAD

**Issue by vsignsoft** [Tencent/wcdb#74]
有时，动态增加表字段；
需要判断该字段是否已经存在，否则，该字段已经存在的话，调用 addColumn 会失败；

所以，需要一个判断该字段是否已经存在的接口方便调用；
建议增加这样的接口，谢谢！

**Comment by RingoD** [comment]
如果只是需要加字段，可以直接用ORM，参考：https://github.com/Tencent/wcdb/wiki/ORM使用教程#增加字段

如果是希望通过代码加字段，可以用addColumn接口。目前没有提供直接获取字段名的方法，可以通过`PRAGMA table_info`来获取所有字段名，并判断是否字段已经存在。
请参考：
1. table_info：http://www.sqlite.org/pragma.html 
2. WCDB中利用table_info自动添加字段的代码： https://github.com/Tencent/wcdb/blob/master/apple/WCDB/interface/table/WCTInterface%2BTable.mm
