### ISSUE TITLE
Create Table Crash

### ISSUE THREAD

**Issue by nothot** [Tencent/wcdb#741]
### The language of WCDB

> Objective-C

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> iOS

### What's the issue?

We found WCDB has crash when creating table sometimes，the crash stack as follow:
SIGSEGV 0x0000000000000002
0
WCDB
WCTBinding::generateCreateTableStatement(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const + 148
1
WCDB
std::__1::__function::__func<-[WCTInterface(Table) createTableAndIndexesOfName:withClass:andError:]::$_0, std::__1::allocator<-[WCTInterface(Table) createTableAndIndexesOfName:withClass:andError:]::$_0>, bool (WCDB::Error&)>::operator()(WCDB::Error&) + 496
2
WCDB
WCDB::CoreBase::runTransaction(std::__1::function<bool (WCDB::Error&)>, std::__1::function<void (WCDB::CoreBase::TransactionEventType)>, WCDB::Error&) + 84
3
WCDB
WCDB::Database::runEmbeddedTransaction(std::__1::function<bool (WCDB::Error&)>, WCDB::Error&) + 192
4
WCDB
-[WCTInterface(Table) createTableAndIndexesOfName:withClass:andError:] + 192
5
WCDB
-[WCTDatabase(Table) createTableAndIndexesOfName:withClass:] + 80

**Comment by wangpeiyan** [comment]
Encountered same problem

**Comment by Qiuwen-chen** [comment]
Please try WCDB 2.0 to see if this problem still exists.
