### ISSUE TITLE
iOS 插入或更新的问题

### ISSUE THREAD

**Issue by LongTimeNoSeee** [Tencent/wcdb#75]
请问iOS中`insertOrReplaceObject`方法实现的是：如果数据库中不存在这个主键，插入;如果数据库中存在这个主键，全量覆盖？

**Comment by RingoD** [comment]
是的，请参考:http://www.sqlite.org/lang_insert.html

**Comment by LongTimeNoSeee** [comment]
嗯，好的，但是没有`insertOrUpdate`这样的功能吗，比如：如果数据存在，则更新，可能只是更新部分字段;不存在，插入。

**Comment by RingoD** [comment]
可以使用`insertOrReplaceObject:onProperties:`。
我稍后也完善下这部分的教程内容。

**Comment by RingoD** [comment]
https://github.com/Tencent/wcdb/wiki/基础类、CRUD与Transaction#便捷接口
已更新便捷接口的文档
