### ISSUE TITLE
How to migrate unencrypted datebase to encrypted database

### ISSUE THREAD

**Issue by panfeng200866** [Tencent/wcdb#751]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.1.1

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> How to migrate unencrypted datebase to encrypted database, I tried the sqlcipher_export API, but It seems not work. Here are my code:
 
const char *sql = [[NSString stringWithFormat:@"ATTACH DATABASE '%@' AS encrypted KEY '%@';", dbPath, password] UTF8String];
const char *exportSql = [[NSString stringWithFormat:@"SELECT sqlcipher_export('encrypted');"] UTF8String];
const char *detachSql = [[NSString stringWithFormat:@"DETACH DATABASE encrypted;"] UTF8String];

rc = sqlite3_exec(unencrypted_DB, sql,NULL,NULL, &errmsg);
rc = sqlite3_exec(unencrypted_DB, exportSql,NULL,NULL, &errmsg);
rc = sqlite3_exec(unencrypted_DB, detachSql,NULL,NULL, &errmsg);

The first line value of rc is 26, and errmsg printed 'file is encrypted or is not a database'. I find another API void sqlcipher_exportFunc(sqlite3_context *context, int argc, sqlite3_value **argv)，should I try this way？Could you give me some guides or instructions? Thanks a lot.

**Comment by Qiuwen-chen** [comment]
Please use data migration feature in v2.1.0.
