### ISSUE TITLE
为什么数据库插入数据之后，可视化工具就打不开数据了啊，这个调试的时候不好看数据啊？

### ISSUE THREAD

**Issue by luolong123** [Tencent/wcdb#753]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
It is not a WCDB related problem.
