### ISSUE TITLE
lastInsertedRowID无法获取到

### ISSUE THREAD

**Issue by cxz137131304** [Tencent/wcdb#754]
问题简要描述：lastInsertedRowID在getObject的时候无法获取到正确的值

背景：
我用swift版本的model，用的oc版本的wcdb
@objc var isAutoIncrement: Bool = true
@objc var lastInsertedRowID: Int = 0
WCDB_PROPERTY(lastInsertedRowID);
WCDB_SYNTHESIZE(ChatMessage, lastInsertedRowID);
遇到的问题：
1.我在进行insert的时候，lastInsertedRowID的数据是正常递增获取到了。
2.当进行getObject的时候，lastInsertedRowID一直都为0
3.当使用该字段进行排序的时候，OrderBy:ChatMessage.lastInsertedRowID.order(WCTOrderedDescending)，或者使用WCTOrderedAscending，结果都是一样的。

是否是我操作问题，导致lastInsertedRowID在数据库中没有真正的数据，麻烦解答下，谢谢

**Comment by ToForgive** [comment]
可以看下是不是用了 insertOrReplace方法 改成 insert方法就好了，至少我的好了。

**Comment by cxz137131304** [comment]
谢谢

**Comment by Qiuwen-chen** [comment]
lastInsertedRowID is only useful when inserting new data.

**Comment by cxz137131304** [comment]
> lastInsertedRowID is only useful when inserting new data.

这个字段的数据 无法被获取到是吗？不是真实存在数据库？

**Comment by Qiuwen-chen** [comment]
> > lastInsertedRowID is only useful when inserting new data.
> 
> 这个字段的数据 无法被获取到是吗？不是真实存在数据库？

Yes
