### ISSUE TITLE
How to update and append data into specify column?

### ISSUE THREAD

**Issue by xungui** [Tencent/wcdb#755]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

For WCDB.Swift database update api

How to update and append data into specify column?

CREATE TABLE "Demo" (
	"id"	INTEGER,
	"name"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);

INSERT INTO 'Demo' ('name') VALUES ('test')

###Target
UPDATE Demo SET name = name || ' Appended ' WHERE id = 1

**Comment by Qiuwen-chen** [comment]
Here is wiki: https://github.com/Tencent/wcdb/wiki/Swift-%e5%a2%9e%e5%88%a0%e6%9f%a5%e6%94%b9

**Comment by xungui** [comment]
邮件已收到！谢谢！
