### ISSUE TITLE
WAL文件过大，很快就到几百MB了，请问这个wal文件是自动回收吗

### ISSUE THREAD

**Issue by knightSaber** [Tencent/wcdb#756]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by azureplus** [comment]
journalSizeLimit

**Comment by holybin** [comment]
> journalSizeLimit

1、configure journal_size_limit
2、trigger checkpoint and sqlite will truncate wal file size to your limit size
