### ISSUE TITLE
"walIndexTryHdr" crash happened

### ISSUE THREAD

**Issue by tigerandy163com** [Tencent/wcdb#758]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.7.5

### The platform of WCDB

>  iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

![Lark20200824-152643](https://user-images.githubusercontent.com/3240001/91016088-c95dda80-e61e-11ea-93b3-d9c5547c5883.png)

hi, A large number of these crash statistics have been discovered recently. Is there a solution? It doesn't happen when the screen is locked

**Comment by lifenglin123** [comment]
果然和文件保护策略有关，数据库设置NSFileProtectionCompleteUntilFirstUserAuthentication这个策略，后台可读写数据即可
