### ISSUE TITLE
打开已加密的数据库文件

### ISSUE THREAD

**Issue by xiejunyuan** [Tencent/wcdb#762]
### The language of WCDB

> e.g. Objective-C

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

如何打开之前使用FMDB/SQLCipher加密过的数据库文件呢，有例子代码可以参考吗？我查阅了很多资料都没有对应的处理。

**Comment by makehapi** [comment]
同问

**Comment by Qiuwen-chen** [comment]
You can use -[WCTDatabase setCipherKey:] to configure cipherKey for encrypted database.
