### ISSUE TITLE
ORM使用教程文档 手动安装文件模版网页链接失效

### ISSUE THREAD

**Issue by Ash-Oswin** [Tencent/wcdb#763]
# ORM使用教程文档 WCTColumnCoding手动安装文件模版处网页链接失效

### WCTColumnCoding文件模版
......
1.首先需要安装文件模版。
....未获取 WCDB 的 Github 仓库的开发者.....
已获取 WCDB 的 Github 仓库的开发者，可以手动运行 cd path-to-your-wcdb-dir/tools/templates; sh install.sh; 手动安装 文件模版(https://github.com/Tencent/wcdb/blob/master/objc/xctemplate/Makefile) 此链接已失效

**Comment by Qiuwen-chen** [comment]
Got it.
