### ISSUE TITLE
使用androidx的room强制转换不了db

### ISSUE THREAD

**Issue by lixiangkai1987** [Tencent/wcdb#764]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

SQLiteDatabase sqlite = ((WCDBDatabase) db.getOpenHelper().getWritableDatabase()).getInnerDatabase();

**Comment by Qiuwen-chen** [comment]
Please try v2.1.0
