### ISSUE TITLE
Backup Crash, can anyone help?

### ISSUE THREAD

**Issue by openproject** [Tencent/wcdb#765]
### The language of WCDB

Java

### The version of WCDB

v1.0.8

### The platform of WCDB

Android

### The installation of WCDB

AAR

### What's the issue?

BackupKit crash on mm_backup_statistics+4

LineageOS Version: '16.0-20200407-NIGHTLY-mido'
Build fingerprint: 'xiaomi/mido/mido:7.0/NRD90M/V9.6.1.0.NCFMIFD:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 20994, tid: 21156, name: db-read-thread-  >>> com.xxx.app <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xffffffffc38869d8
    x0  ffffffffc3886840  x1  00000074ab62c0e4  x2  a7baecd1c0a4bdb8  x3  00000074afdcb000
    x4  00000074ab62c540  x5  00000074b36c2b5f  x6  607560694b23ff3a  x7  0000000000000000
    x8  a7baecd1c0a4bdb8  x9  a7baecd1c0a4bdb8  x10 0000000000430000  x11 00000074cd498adc
    x12 00000074cd498b30  x13 00000074cd498b84  x14 00000074cd498be4  x15 0000000000000000
    x16 00000074ab62c0f0  x17 0000000000000000  x18 0000000000000001  x19 000000754f47a9f0
    x20 00000074aa64ee74  x21 00000074afdcb000  x22 00000074ab62c3a0  x23 00000074b36c2b5f
    x24 0000000000000008  x25 00000074ab62e588  x26 00000074afdcb0a0  x27 0000000000000002
    x28 0000000000000005  x29 00000074ab62c0c0
    sp  00000074ab62c0c0  lr  00000074aa64ee9c  pc  00000074aa65aabc

backtrace:
    #00 pc 000000000003eabc  /data/app/com.xxx.app-oA4j_ODYkBNqVKVI9pQUQQ==/lib/arm64/libwcdb.so (mm_backup_statistics+4)
    #01 pc 0000000000032e98  /data/app/com.xxx.app-oA4j_ODYkBNqVKVI9pQUQQ==/lib/arm64/libwcdb.so
    #02 pc 000000000022b338  /data/app/com.xxx.app-oA4j_ODYkBNqVKVI9pQUQQ==/oat/arm64/base.odex (offset 0x1f6000) (com.tencent.wcdb.repair.BackupKit.nativeStatementCount+152)
    #03 pc 0000000000554c4c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    #04 pc 00000000000cf6e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    #05 pc 000000000027f2f8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
    #06 pc 0000000000279300  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
    #07 pc 0000000000525c98  /system/lib64/libart.so (MterpInvokeStatic+204)
    #08 pc 0000000000547214  /system/lib64/libart.so (ExecuteMterpImpl+14612)
    #09 pc 00000000010dc6be  /data/app/com.xxx.app-oA4j_ODYkBNqVKVI9pQUQQ==/oat/arm64/base.vdex (com.tencent.wcdb.repair.BackupKit.run+66)
    #10 pc 0000000000253004  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3326130167+488)
    #11 pc 0000000000258af8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #12 pc 00000000002792e4  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #13 pc 0000000000524794  /system/lib64/libart.so (MterpInvokeVirtual+588)
    #14 pc 0000000000547094  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #15 pc 0000000001b53ebe  /data/app/com.xxx.app-oA4j_ODYkBNqVKVI9pQUQQ==/oat/arm64/base.vdex (com.xxx.imsdk.db.BackupService$BackupRunnable.run+52)
    #16 pc 0000000000253004  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3326130167+488)
    #17 pc 0000000000258af8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #18 pc 00000000002792e4  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #19 pc 0000000000525710  /system/lib64/libart.so (MterpInvokeInterface+1392)
    #20 pc 0000000000547294  /system/lib64/libart.so (ExecuteMterpImpl+14740)
    #21 pc 0000000001b908ba  /data/app/com.xxx.app-oA4j_ODYkBNqVKVI9pQUQQ==/oat/arm64/base.vdex (com.xxx.imsdk.task.DbReadTask$Companion$execute$2.onRun+4)
    #22 pc 0000000000253004  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3326130167+488)
    #23 pc 0000000000258af8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #24 pc 00000000002792e4  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #25 pc 0000000000524794  /system/lib64/libart.so (MterpInvokeVirtual+588)
    #26 pc 0000000000547094  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #27 pc 0000000001b90896  /data/app/com.xxx.app-oA4j_ODYkBNqVKVI9pQUQQ==/oat/arm64/base.vdex (com.xxx.imsdk.task.DbReadTask$Companion$execute$2.onRun)
    #28 pc 0000000000253004  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3326130167+488)
    #29 pc 0000000000258af8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #30 pc 00000000002792e4  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #31 pc 0000000000525710  /system/lib64/libart.so (MterpInvokeInterface+1392)
    #32 pc 0000000000547294  /system/lib64/libart.so (ExecuteMterpImpl+14740)
    #33 pc 0000000001b5556c  /data/app/com.xxx.app-oA4j_ODYkBNqVKVI9pQUQQ==/oat/arm64/base.vdex (com.xxx.imsdk.task.DbTask.run+8)
    #34 pc 0000000000253004  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3326130167+488)
    #35 pc 0000000000258af8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #36 pc 00000000002792e4  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #37 pc 0000000000525710  /system/lib64/libart.so (MterpInvokeInterface+1392)
    #38 pc 0000000000547294  /system/lib64/libart.so (ExecuteMterpImpl+14740)
    #39 pc 000000000010fcaa  /system/framework/boot.vdex (java.util.concurrent.ThreadPoolExecutor.runWorker+160)
    #40 pc 0000000000253004  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3326130167+488)
    #41 pc 0000000000258af8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #42 pc 00000000002792e4  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #43 pc 0000000000524794  /system/lib64/libart.so (MterpInvokeVirtual+588)
    #44 pc 0000000000547094  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #45 pc 000000000010efbe  /system/framework/boot.vdex (java.util.concurrent.ThreadPoolExecutor$Worker.run+4)
    #46 pc 0000000000253004  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3326130167+488)
    #47 pc 0000000000258af8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #48 pc 00000000002792e4  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #49 pc 0000000000525710  /system/lib64/libart.so (MterpInvokeInterface+1392)
    #50 pc 0000000000547294  /system/lib64/libart.so (ExecuteMterpImpl+14740)
    #51 pc 00000000000c4afa  /system/framework/boot.vdex (java.lang.Thread.run+12)
    #52 pc 0000000000253004  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3326130167+488)
    #53 pc 0000000000515028  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
    #54 pc 000000000055dafc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    #55 pc 0000000000554988  /system/lib64/libart.so (art_quick_invoke_stub+584)
    #56 pc 00000000000cf6c8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    #57 pc 000000000045c884  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
    #58 pc 000000000045d940  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+424)
    #59 pc 000000000048881c  /system/lib64/libart.so (art::Thread::CreateCallback(void*)+1120)
    #60 pc 0000000000082bbc  /system/lib64/libc.so (__pthread_start(void*)+36)
    #61 pc 00000000000234fc  /system/lib64/libc.so (__start_thread+68)

More info below:
[wcdb_tombstone.txt](https://github.com/Tencent/wcdb/files/5297335/wcdb_tombstone.txt)

**Comment by liuyuan5358** [comment]
I have the same problem.
you can use the new version.
It has been solved.

**Comment by Qiuwen-chen** [comment]
Please try v2.1.0
