### ISSUE TITLE
自定义嵌套属性时候， 存入是嵌套属性的子类，取出时候为空

### ISSUE THREAD

**Issue by xiaoyao20084321** [Tencent/wcdb#766]
![image](https://user-images.githubusercontent.com/10344550/95668890-54356d00-0bac-11eb-9a0a-7f24431829f7.png)
![image](https://user-images.githubusercontent.com/10344550/95668903-80e98480-0bac-11eb-8b96-654556ab74fa.png)

如题，怎么解决

**Comment by Qiuwen-chen** [comment]
WCDB has no way of knowing what type of subclass you store.
