### ISSUE TITLE
直接调用C++类的问题

### ISSUE THREAD

**Issue by crazyevent** [Tencent/wcdb#77]
// 直接new一个WCDB::Database对象
```
m_database = std::shared_ptr<WCDB::Database>(new WCDB::Database(db_path));
printf("%s can open=%d", db_path.c_str(), m_database->canOpen());// can open=0
```
// 创建表
```
StatementCreateTable state;
ColumnDefList colList = table->TableStruct();// table是一个管理表结构的对象
state.create(table->GetTableName(), colList);
m_database->exec(state, err);/* 此处没有报错，查看目标文件存在，但是没有创建表，文件只有4KB */
```
请问是怎么回事呢？是我用法有问题嘛？

**Comment by RingoD** [comment]
没有重现这个问题。
你使用的WCDB哪个版本？用最新的commit是否还存在同样问题？如果还有问题，麻烦提供下完整代码。

另外，为什么要直接使用`WCDB::Database`，而不用ObjC？

**Comment by crazyevent** [comment]
1、确定我的调用流程没问题的？
2、版本是最新的，没有使用ObjC的代码；
3、直接用WCDB是因为需要一个跨平台的解决方案，包括win在内，所以ORM之类的只能放弃使用。

**Comment by RingoD** [comment]
这点代码没发现问题，能否给个完整的sample？

**Comment by crazyevent** [comment]
can open=0这地方有问题否？

**Comment by RingoD** [comment]
返回0肯定是不正确的，但没有代码我无法判断问题

**Comment by crazyevent** [comment]
找到了，是handle_pool::fill_one函数返回出错，这个在新版本里已经解决的。

**Comment by crazyevent** [comment]
另外还有个问题，数据库操作默认是不是马上写入文件的？我看到创建表的语句执行了，表也出现了，但是表没有任何字段，并且存储目录下出现了同名的.db-shm和.db-wal文件

**Comment by RingoD** [comment]
是立即写入。
SQLite的WAL模式是先写入wal文件，再checkpoint写回db。但这种情况下是能读到数据的
