### ISSUE TITLE
Model中有与数据库关键字重名的属性时，创建表失败，比如 order 属性

### ISSUE THREAD

**Issue by leiguang** [Tencent/wcdb#770]
### The language of WCDB

Swift

### The version of WCDB

v1.0.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

>  Code:sqliteGlobal(1), Type:SQLiteGlobal, Message:near \"order\": syntax error"
> Code:sqlite(1), Type:SQLite, Path:/Users/leiguang/Library/Developer/CoreSimulator/Devices/5B769E6F-B652-4311-8C91-326675F02DB3/data/Containers/Data/Application/C1328B18-E95E-4514-8F45-8F6986BC313A/Documents/GeneratedProvisionDefaultDBs/provision_home_default.db,SQL:CREATE TABLE IF NOT EXISTS home_page(name TEXT, widgetType TEXT, theme TEXT, padding BLOB, margin BLOB, parent TEXT, content BLOB, order INTEGER, componentOrder TEXT, template TEXT, displayGroup TEXT, customField BLOB),ExtendedCode:1,Message:near "order": syntax error,Operation:4

在其他软件中 给 order 两侧加上 `` 后，是可以正常执行此sql语句的。
除了给数据库字段命别名，WCDB有方法处理这种关键字吗？

**Comment by Qiuwen-chen** [comment]
No
