### ISSUE TITLE
WCDB-Swift fuzzy search

### ISSUE THREAD

**Issue by wkmeow** [Tencent/wcdb#771]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Swift

### The version of WCDB
WCDB-Swift
> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android
iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

can wcdb-swift fuzzy search the string  contain Chinese , English or numbers???? . And how?

**Comment by wkmeow** [comment]
let tableColumn = Column(named: "type")
 let objects : [Model] = try db.getObjects( fromTable: tableName, where: tableColumn.like("产品"))

以上代码，type为string字段，使用like，方法，也无法实现模糊搜索，只有在string和key完全相同时，才能有返回内容。

**Comment by Qiuwen-chen** [comment]
You need to use wildcards in the query, such as  tableColumn.like("%产品%").
