### ISSUE TITLE
Backup database file to icloud

### ISSUE THREAD

**Issue by xchenLee** [Tencent/wcdb#773]
### The language of WCDB

> Objective-C

### I want to backup the db file to iCloud or the server, it seems that no API supported

>what should I do, if I want to backup the database datas  to  cloud like iCloud or the server, and then recover it back.  
>in my demo project, I copy the database file from the app container, and  read it with pathForResource, the database cannot be opened

>(我想把数据库文件备份到云端，然后再读取下来，尝试了从app container 里的数据库路径获取到的文件，放到工程里，再尝试initWithPath来读取，发现读取失败)，目前有API支持吗

**Comment by yi821661664** [comment]
[WCDB][ERROR] Code:sqlite(26), Type:SQLite, ExtendedCode:26,SQL:PRAGMA synchronous='NORMAL',Message:file is encrypted or is not a databas类似于这种报错吗？

**Comment by Qiuwen-chen** [comment]
Please give more detail about this error.
