### ISSUE TITLE
WCDB.swift不支持Swift 5

### ISSUE THREAD

**Issue by devchena** [Tencent/wcdb#774]

**Comment by SUWW** [comment]
请问你是怎么解决？我pod不下来。

**Comment by devchena** [comment]
可以pod下来，但是版本还是Swift 4.2

**Comment by zhxin183** [comment]
pod 'WCDBSwift'

**Comment by wujianguo** [comment]
这边建了个 repo，把 swift 版本的 WCDB 单独拿出来了，去掉了之前的历史记录与其他代码，加快下载集成速度，已经支持 swift5，可以直接使用。https://github.com/codesanatorium/WCDB.swift

**Comment by Qiuwen-chen** [comment]
WCDB will support Swift 5 soon.
