### ISSUE TITLE
unknown tokenizer: WCDB"

### ISSUE THREAD

**Issue by lessSource** [Tencent/wcdb#775]
####  e.g. Objective-C, Swift or Java
Swift

####  The version of WCDB

e.g. v1.0.5
1.0.8.2

####  e.g. iOS, macOS or Android
iOS

####  e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
Cocoapods

####  Explain what you want by example or code in English.
  When I try to create virtual table, it reports "Message:unknown tokenizer: WCDB".

 I copy this code from document:

        static var virtualTableBinding: VirtualTableBinding? {
            return VirtualTableBinding(with: .fts3, and: ModuleArgument(with: .WCDB))
        }

**Comment by eyuxin** [comment]
I resolve this issue by add "dataBase?.setTokenizes(.WCDB)" before create virtualTable.
