### ISSUE TITLE
when create table, column attribute include  "ON CONFLICT IGNORE" cause  syntax error

### ISSUE THREAD

**Issue by SSETong** [Tencent/wcdb#776]
### The language of WCDB
Swift

### The version of WCDB
1.0.8.2

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?
![image](https://user-images.githubusercontent.com/38234750/98786509-248eb480-2439-11eb-8829-672fcb635ec7.png)

When created table, there was a syntax problem in the conflict attribute of the column setting
Wrong syntax sql query
CREATE TABLE IF NOT EXISTS "TableName" (
   id INTEGER PRIMARY KEY ASC AUTOINCREMENT ON CONFLICT IGNORE NOT NULL,
   nodeUUID TEXT NOT NULL UNIQUE
)

Correct syntax sql query, the "ON CONFLICT IGNORE" mush be set on the suffix
CREATE TABLE IF NOT EXISTS "TableName" (
   id INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL  ON CONFLICT IGNORE ,
   nodeUUID TEXT NOT NULL UNIQUE
)

**Comment by ToForgive** [comment]
同样的问题，有人可以解决下嘛～

**Comment by Qiuwen-chen** [comment]
Fix in WCDB 2.0
