### ISSUE TITLE
查询语句条件过多swift编译不通过

### ISSUE THREAD

**Issue by skyxian** [Tencent/wcdb#777]
The language of WCDB

e.g. Swift
The version of WCDB

e.g. v1.0.8
The platform of WCDB

e.g. iOS
The installation of WCDB

e.g. Cocoapods
What's the issue?

您好，我使用WCDBSwift 中的Condition类来拼接查询语句（查询语句条件过多的时候Swift编译不让通过）

let condition: Condition? = WCDBConversation.Properties.firstLevel == true && WCDBConversation.Properties.conversationType != "someone_nearby" && WCDBConversation.Properties.conversationType != "someone_nearby_old" && WCDBConversation.Properties.conversationType != "ouyu" && WCDBConversation.Properties.conversationType != "Unknown"（添加最后这个"Unknown"条件后就报错了）

let results = WCDBManage.shared.qureyFromDb(fromTable: WCDBManage.shared.K_Conversation_Table(), cls: WCDBConversation.self, where: condition, orderBy: [WCDBConversation.Properties.rank.asOrder(by: .descending), WCDBConversation.Properties.createdAt.asOrder(by: .descending)], limit: nil, offset: nil)

swift编译不让通过
The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

查了半天没找到使用Array来实现的办法，请问我应该怎么处理呐？不胜感激

**Comment by skyxian** [comment]
@RingoD 求教， swift5.之后不让拼接语句过多（项目中查询条件过多）

let condition: Condition? = WCDBConversation.Properties.firstLevel == true && WCDBConversation.Properties.conversationType != "someone_nearby" && WCDBConversation.Properties.conversationType != "someone_nearby_old" && WCDBConversation.Properties.conversationType != "ouyu" && WCDBConversation.Properties.conversationType != "Unknown"（添加最后这个"Unknown"条件后就报错了）

swift编译不让通过
The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

这个问题对我们挺重要的，希望能解答一下，谢啦

**Comment by AllenYL** [comment]
请问怎么解决这个条件过长的问题啊？
