### ISSUE TITLE
无法找到"libwcdb.so"

### ISSUE THREAD

**Issue by wangtonggen** [Tencent/wcdb#778]
### The language of WCDB

> Java 

### The version of WCDB

> e.g. v1.0.8

### The platform of WCDB

> Android

### The installation of WCDB

> Maven,

### What's the issue?

说是无法找到libwcdb动态库
/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64, /preas/lib64]]] couldn't find "libwcdb.so"

**Comment by wangtonggen** [comment]
我查看app/build/outputs 目录下的APK 里面是有这个动态库的，奇怪的是并不是每次都会出现。出现的时候关闭APP进程，重新打开就好了。我很奇怪为什么会出现这个问题

**Comment by Muchenyao** [comment]
我也是同样的问题，升级的AS 3.1 和gradle到最新出现

**Comment by wangtonggen** [comment]
> 我也是同样的问题，升级的AS 3.1 和gradle到最新出现

这个我这边不是必现的，而且关闭进程后重新打开有可以了。

**Comment by ceneax** [comment]
一样   模拟器会出现。真机目前没遇到，  尚不清楚是什么问题

**Comment by Qiuwen-chen** [comment]
Please try v2.1.0
