### ISSUE TITLE
sql语句 SELECT * FROM UploadList WHERE uploadStatus != 2 ORDER BY curr_index ASC  在WCDB应该是怎么写的

### ISSUE THREAD

**Issue by HuRKun** [Tencent/wcdb#779]
### The language of WCDB

> e.g. Objective-C

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by ZhangXueFei** [comment]
//降序排列，字符串匹配
    NSString *likeStr = [NSString stringWithFormat:@"%@%@%@",@"%",searchText,@"%"];
    return [database getObjectsOfClass:CheatlistModel.class fromTable:TABLE_WCDB_Cheatlist where:{CheatlistModel.deleteState==0 and CheatlistModel.taskName.like(likeStr)} orderBy:{CheatlistModel.starFlag.order(WCTOrderedDescending),CheatlistModel.startTime.order(WCTOrderedDescending)}];
