### ISSUE TITLE
iOS连表查询，两个表里有相同字段，WCTResultList要怎么设置

### ISSUE THREAD

**Issue by will0321** [Tencent/wcdb#782]
连表查询代码如下：     
   WCDB::JoinClause join = WCDB::JoinClause("User").join("Group",WCDB::JoinClause::Type::Left).on(User.uid == Group.groupId);
        
        WCTResultList resultList = WCTResultList({User.uid,User.dscription,Group.name});
        
        WCDB::StatementSelect select = WCDB::StatementSelect().select(resultList).from(join).where(wctCondition).limit(limit);
        WCTStatement *statement = [self.database prepare:select];
        while (statement && [statement step]) {
            NSLog(@"satetement:%@",statement);
            
        }
其中dscription这个字段，两个表里都有。但是查询的时候生成的语句没有加表名。直接是dscription。所以查询保错。WCTResultList要怎么设置生成的select才会有加表名。

**Comment by will0321** [comment]
知道了，这样写就可以了
WCDB::ColumnResultList list = {WCDB::ColumnResult("User.uid"),WCDB::ColumnResult("User.dscription"),WCDB::ColumnResult("Group.name")};

WCDB::StatementSelect select = WCDB::StatementSelect().select(resultList).from(join).where(wctCondition).limit(limit);

**Comment by will0321** [comment]
上面那样写还是不行。直接生成了这个 “User.dscription”而不是User.dscription

**Comment by Qiuwen-chen** [comment]
You should use WCTResultList({User.uid,User.dscription.inTable(xxx),Group.name})
