### ISSUE TITLE
FMDB/SQLCipher创建的加密数据库怎么迁移到WCDB上

### ISSUE THREAD

**Issue by makehapi** [Tencent/wcdb#783]
FMDB/SQLCipher不能与WCDB共存，只能用FMDB+WCDB了，这时候原先用FMDB/SQLCipher创建的加密数据库怎么迁移到WCDB上，FMDB引用WCDB的SQLCipher但是不能打开原先FMDB/SQLCipher创建的加密数据库

**Comment by Qiuwen-chen** [comment]
WCDB 2.0 supports to open databases created by different versions of sqlcipher, please try.
