### ISSUE TITLE
弱弱的问一句，Tencent这个库还维护吗？pre1.1.0 14个月了，还没发布，SQLCipher也还是老的

### ISSUE THREAD

**Issue by Lee-Wang-Jing** [Tencent/wcdb#784]
弱弱的问一句，Tencent这个库还维护吗？pre1.1.0 14个月了，还没发布
SQLCipher也还是老的
最新的FMDB 加密数据库SQLCipher迁移都无法打开。
issues也没人理了。

😔，KPI完成了就不了了之了。。

**Comment by wujianguo** [comment]
Hey, guys, I create a repo for wcdb.swift, wish to maintain it together. https://github.com/codesanatorium/WCDB.swift

**Comment by yanyin1986** [comment]
@wujianguo Great!
