### ISSUE TITLE
wcdb 1.0.8

### ISSUE THREAD

**Issue by cpcxy** [Tencent/wcdb#786]
wcdb 1.0.8 高于 gradle-5.4.1 时 会出现 引用不到  com.tencent.wcdb.database.SQLiteCipherSpec的问题

**Comment by lucky-tom** [comment]
implementation 'com.tencent.wcdb:room:1.0.8'  
implementation 'com.tencent.wcdb:wcdb-android:1.0.8'//把这个引用下

我的gradle版本，gradle-6.5
android studio 版本4.1.1
可以引用到。
