### ISSUE TITLE
数据库修复失败

### ISSUE THREAD

**Issue by vsignsoft** [Tencent/wcdb#79]
在研究数据库修复样例时，发现一个问题：
1、如果原数据库未加密过，备份，恢复都正常（也就是样例）(pageSize 4096)；
2、如果原数据库经过加密的，备份成功，恢复后，表创建了，但是数据没有导过来 (pageSize 1024)；
3、两种情况所获取的pageSize不一样，一个是 4096，一个是1024;

测试环境：
在 macOS 上，跑测试实例 sample_repair_main.mm 

不成功情况，代码修改处：
1、给原始数据库设置密码；
2、恢复时，参数 databaseCipher 传入原始数据库设置的密码；
（- recoverFromPath:(NSString *)corruptedDBPath withPageSize:(const int)pageSize backupCipher:(NSData *)backupCipher databaseCipher:(NSData *)databaseCipher）

日志打印报错：
2017-06-27 11:04:25.316668+0800 Sample[1038:52855] Base Directory: /Users/xxx/Library/Developer/Xcode/DerivedData/WCDB-efjqwwcdtedcwhbdbmttflouwhzg/Build/Products/Debug/SampleDB
2017-06-27 11:04:25.316886+0800 Sample[1038:52855] Sample-repair Begin
2017-06-27 11:04:33.397352+0800 Sample[1038:52855] The count of objects before: 10
[SQLITERK_OK] Saved master info with 1 entries.
[WCDB]Code:26, Type:SQLiteGlobal, Msg:file is encrypted or is not a database
[WCDB]Code:26, Type:SQLite, Tag:0, Op:3, ExtCode:26, Msg:file is encrypted or is not a database, SQL:PRAGMA journal_mode, Path:/Users/xxx/Library/Developer/Xcode/DerivedData/WCDB-efjqwwcdtedcwhbdbmttflouwhzg/Build/Products/Debug/SampleDB/WCTSampleRepair.sqlite
2017-06-27 11:04:36.827410+0800 Sample[1038:52855] The count of objects corrupted: 0
[SQLITERK_OK] Loaded master info with 1 valid entries.
[SQLITERK_DAMAGED] Invalid page size: 1024 expected, 26659 returned.
[SQLITERK_DAMAGED] Reserved bytes field doesn't match. 16 expected, 40 returned.
[SQLITERK_DAMAGED] The [free page count] field is corrupted. 0 is used
[SQLITERK_DAMAGED] Header cannot be decoded correctly. Trying to apply recovery data.
[SQLITERK_DAMAGED] Invalid page size: 1024 expected, 26659 returned.
[SQLITERK_DAMAGED] Reserved bytes field doesn't match. 16 expected, 40 returned.
[SQLITERK_DAMAGED] The [free page count] field is corrupted. 0 is used
[SQLITERK_DAMAGED] Header corrupted.
[SQLITERK_OK] RepairKit on '/Users/wfeng/Library/Developer/Xcode/DerivedData/WCDB-efjqwwcdtedcwhbdbmttflouwhzg/Build/Products/Debug/SampleDB/WCTSampleRepair.sqlite' opened, encrypted.
[SQLITERK_OK] Output recovered data to '/Users/wfeng/Library/Developer/Xcode/DerivedData/WCDB-efjqwwcdtedcwhbdbmttflouwhzg/Build/Products/Debug/SampleDB/WCTSampleRepair_recover.sqlite', flags 0x0002
[SQLITERK_OK] Begin parsing sqlite_master...
[SQLITERK_OK] Parsing B-tree -> [root: 1, name: sqlite_master, type: sqlite_master]
[SQLITERK_DAMAGED] Page 1 has invalid type
[SQLITERK_DAMAGED] Failed to parse page 1.
[SQLITERK_DAMAGED] Failed to parse sqlite_master.
[SQLITERK_OK] >>> CREATE TABLE WCTSampleRepair(identifier INTEGER,content TEXT)
[SQLITERK_OK] [WCTSampleRepair] -> pgno: 2
[SQLITERK_DAMAGED] Failed to parse B-tree with root page 2.
[SQLITERK_OK] Recovery output finished. [succeeded: 1, failed: 0]
2017-06-27 11:04:40.761825+0800 Sample[1038:52950] The count of objects repaired: 0

不成功情况，代码如下：
`void sample_repair_main(NSString *baseDirectory)
{
    NSLog(@"Sample-repair Begin");
    NSString *className = NSStringFromClass(WCTSampleRepair.class);
    NSString *base = [baseDirectory stringByAppendingPathComponent:className];
    NSString *path = [base stringByAppendingString:@".sqlite"];
    NSString *recoverPath = [[base stringByAppendingString:@"_recover"] stringByAppendingString:@".sqlite"];
    NSString *tableName = className;
    __block WCTDatabase *database = [[WCTDatabase alloc] initWithPath:path];
    [database close:^{
        [database removeFilesWithError:nil];
    }];
    
    NSData *cipher_key = [@"test123" dataUsingEncoding:NSUTF8StringEncoding];
   [database setCipherKey:cipher_key];

    WCTDatabase *recover = [[WCTDatabase alloc] initWithPath:recoverPath];
    [recover close:^{
        [recover removeFilesWithError:nil];
    }];
    
    //prepare
    {
        [database createTableAndIndexesOfName:tableName
                                    withClass:WCTSampleRepair.class];
        for (int i = 0; i < 10; ++i)
        {
            WCTSampleRepair *object = [[WCTSampleRepair alloc] init];
            object.identifier = i;
            object.content = [NSString stringWithFormat:@"%d", i];
            [database insertObject:object
                              into:tableName];
        }
        NSLog(@"The count of objects before: %lu", [database getAllObjectsOfClass:WCTSampleRepair.class fromTable:tableName].count);
    }
    
    NSString *password = @"backup123";
    NSData *cipher = [password dataUsingEncoding:NSUTF8StringEncoding];
    
    //backup
    {
        BOOL ret = [database backupWithCipher:cipher];
    }
    
    //get page size
    int pageSize;
    //get page size from origin database.
    //Since page size never change unless you can call "PRAGMA page_size=NewPageSize" to set it. You have no need to get the page size like this. Instead, you can hardcode it.
    {
        @autoreleasepool {
            WCTStatement *statement = [database prepare:WCDB::StatementPragma().pragma(WCDB::Pragma::PageSize)];
            [statement step];
            NSNumber *value = (NSNumber *) [statement getValueAtIndex:0];
            pageSize = value.intValue;
            statement = nil;
        }
    }
    
    //do something
    //corrupt
    {
        [database close:^{  
            FILE *file = fopen(path.UTF8String, "rb+");
            unsigned char *zeroPage = new unsigned char[100];
            memset(zeroPage, 0, 100);
            fwrite(zeroPage, 100, 1, file);
            fclose(file);
        }];
        
        NSLog(@"The count of objects corrupted: %lu", [database getAllObjectsOfClass:WCTSampleRepair.class fromTable:tableName].count);
    }
    
    //repair
    {
        //Since recovering is a long time operation, you'd better call it in sub-thread.
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
        
            WCTDatabase *recover = [[WCTDatabase alloc] initWithPath:recoverPath];
            
            [database close:^{
                BOOL ret = [recover recoverFromPath:path withPageSize:pageSize backupCipher:cipher databaseCipher:cipher_key];
            }];
            NSLog(@"The count of objects repaired: %lu", [recover getAllObjectsOfClass:WCTSampleRepair.class fromTable:tableName].count);
        });
    }
    
    while (1) {
        ;
    }

    NSLog(@"Sample-repair End");
}
`

**Comment by vsignsoft** [comment]
另外，WCDB QQ讨论群 190485752 根本加不进去；
加入，就被秒拒了；
回答问题 b = 6 也被拒绝；

**Comment by RingoD** [comment]
我重现了，可能是bug。

**Comment by RingoD** [comment]
QQ群一直有人成功加进来，要不你再试试吧

**Comment by vsignsoft** [comment]
加进群了，原来验证时，直接输入 
6
就行了；

不是输入 b = 6;

**Comment by jackytianhappy** [comment]
请问题在最新版本修复了吗？刚使用了最新版也复现了，原先加密过的数据库，用WCDB进行备份，sqlite_master备份成功，恢复的时候，page_size都保持一致1024，但是数据没恢复过来，表结构是恢复了，数据丢失。
以下是恢复时的log：
[SQLITERK_OK] Loaded master info with 1 valid entries.
[SQLITERK_DAMAGED] Invalid page size: 1024 expected, -4743 returned.
[SQLITERK_DAMAGED] Reserved bytes field doesn't match. 16 expected, -19 returned.
[SQLITERK_DAMAGED] Header cannot be decoded correctly. Trying to apply recovery data.
[SQLITERK_DAMAGED] Invalid page size: 1024 expected, -4743 returned.
[SQLITERK_DAMAGED] Reserved bytes field doesn't match. 16 expected, -19 returned.
[SQLITERK_DAMAGED] Header corrupted.
[SQLITERK_OK] RepairKit on '/Users/tiannan01/Library/Developer/CoreSimulator/Devices/5A3996E7-A6CA-4298-911F-16321E32BF33/data/Containers/Data/Application/ECF3F05F-29C9-485D-B1DC-9A9C731CF7FB/tmp/Encrypt-tmpDB' opened, encrypted.
[SQLITERK_OK] Output recovered data to '/Users/tiannan01/Library/Developer/CoreSimulator/Devices/5A3996E7-A6CA-4298-911F-16321E32BF33/data/Containers/Data/Application/ECF3F05F-29C9-485D-B1DC-9A9C731CF7FB/tmp/tmpDB_recover', flags 0x0002
[SQLITERK_OK] Begin parsing sqlite_master...
[SQLITERK_OK] Parsing B-tree -> [root: 1, name: sqlite_master, type: sqlite_master]
[SQLITERK_OK] Parsed sqlite_master. [table/index: 1]
[SQLITERK_OK] >>> CREATE TABLE 'person' ('id' INTEGER PRIMARY KEY AUTOINCREMENT  NOT NULL ,'person_id' VARCHAR(255),'person_name' VARCHAR(255),'person_age' INTEGER,'person_number'VARCHAR(255))
[SQLITERK_OK] [person] -> pgno: 2
[SQLITERK_DAMAGED] Failed to parse B-tree with root page 2.
[SQLITERK_OK] Recovery output finished. [succeeded: 1, failed: 0]
page2解析失败

**Comment by RingoD** [comment]
@jackytianhappy 正在修复

**Comment by RingoD** [comment]
该问题已修复：https://github.com/Tencent/wcdb/commit/c76e65c62153563bebfdd14853a7aac11705f416
