### ISSUE TITLE
Xcode 12.3 无法pod WCDB 文件  报错 。

### ISSUE THREAD

**Issue by SUWW** [Tencent/wcdb#790]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by SUWW** [comment]
[!] Error installing WCDB
[!] /usr/bin/git clone https://github.com/Tencent/wcdb.git /var/folders/ht/qzl4hvns781b1xzmynfx_h4m0000gn/T/d20210115-21170-mv7g05 --template= --single-branch --depth 1 --branch v1.0.7.5

Cloning into '/var/folders/ht/qzl4hvns781b1xzmynfx_h4m0000gn/T/d20210115-21170-mv7g05'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by tamarous** [comment]
This seemed not a problem related to WCDB, but a network connection problem.

**Comment by Nsobject11** [comment]
[!] Error installing SQLiteRepairKit
[!] /usr/bin/git clone https://github.com/Tencent/wcdb.git /var/folders/hf/b_sbs_8569565lrdldtr9y4r0000gn/T/d20210309-27576-cu449n --template= --single-branch --depth 1 --branch v1.0.8.2

Cloning into '/var/folders/hf/b_sbs_8569565lrdldtr9y4r0000gn/T/d20210309-27576-cu449n'...
fatal: unable to access 'https://github.com/Tencent/wcdb.git/': Failed to connect to github.com port 443: Operation timed out 
换了几个网络，翻墙都不好使

**Comment by wujianguo** [comment]
这边建了个 repo，把 swift 版本的 WCDB 单独拿出来了，去掉了之前的历史记录与其他代码，加快下载集成速度，已经支持 swift5，可以直接使用。https://github.com/codesanatorium/WCDB.swift
