### ISSUE TITLE
Android 报找不到静态方法

### ISSUE THREAD

**Issue by deqvhygah1113** [Tencent/wcdb#791]
### The language of WCDB

 Java 

### The version of WCDB

 v1.0.8

### The platform of WCDB

 Android

### The installation of WCDB

Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
![image](https://user-images.githubusercontent.com/37454117/106147995-7ed72000-61b3-11eb-9537-34ce4452ddbb.png)

> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
Please try v2.1.0
