### ISSUE TITLE
iOS 已有数据库文件的读取（解密）

### ISSUE THREAD

**Issue by yi821661664** [Tencent/wcdb#793]
问题描述：当前我从后端下载了已有数据库，并想打开并使用，但是直接报下面的错误，那么这种情况应该怎么处理呢？（注：后端的数据库并没有进行加密，使用了wcdb的默认加密方式）
[WCDB][ERROR] Code:sqlite(26), Type:SQLite, ExtendedCode:26,SQL:PRAGMA synchronous='NORMAL',Message:file is encrypted or is not a databas

**Comment by captain-black** [comment]
老哥，解决了吗？怎么解决的？我也遇到这样问题
