### ISSUE TITLE
Redefinition of multi-files about sqlite3_xx

### ISSUE THREAD

**Issue by GrayLand119** [Tencent/wcdb#799]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Swift , Version 12.4 (12D4e), MacOS Big Sur 11.2.2

### The version of WCDB

> e.g. v1.0.5

1.0.8

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

Redefinition of multi-files about sqlite3.

Swift Compiler Error Group
../Pods/WCDBOptimizedSQLCipher/sqlite3.h:650:8: Redefinition of 'sqlite3_file'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3.h:693:8: Previous definition is here
/<module-includes>:2:9: In file included from <module-includes>:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:
../Pods/WCDBOptimizedSQLCipher/sqlite3.h:745:8: Redefinition of 'sqlite3_io_methods'
../Pods/WCDBOptimizedSQLCipher/sqlite3.h:1226:8: Redefinition of 'sqlite3_vfs'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3.h:1378:8: Previous definition is here
/<module-includes>:2:9: In file included from <module-includes>:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:
../Pods/WCDBOptimizedSQLCipher/sqlite3.h:1523:8: Redefinition of 'sqlite3_mem_methods'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3.h:1675:8: Previous definition is here
/<module-includes>:2:9: In file included from <module-includes>:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:
../Pods/WCDBOptimizedSQLCipher/sqlite3.h:3662:20: Typedef redefinition with different types ('struct Mem' vs 'struct sqlite3_value')
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3.h:4242:30: Previous definition is here
/<module-includes>:2:9: In file included from <module-includes>:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:
../Pods/WCDBOptimizedSQLCipher/sqlite3.h:5798:8: Redefinition of 'sqlite3_module'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3.h:6608:8: Previous definition is here
/<module-includes>:2:9: In file included from <module-includes>:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:
../Pods/WCDBOptimizedSQLCipher/sqlite3.h:5929:8: Redefinition of 'sqlite3_index_info'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3.h:6748:8: Previous definition is here
/<module-includes>:2:9: In file included from <module-includes>:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:
../Pods/WCDBOptimizedSQLCipher/sqlite3.h:5932:10: Redefinition of 'sqlite3_index_constraint'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3.h:6751:10: Previous definition is here
/<module-includes>:2:9: In file included from <module-includes>:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:
../Pods/WCDBOptimizedSQLCipher/sqlite3.h:5939:10: Redefinition of 'sqlite3_index_orderby'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3.h:6758:10: Previous definition is here
/<module-includes>:2:9: In file included from <module-includes>:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:
../Pods/WCDBOptimizedSQLCipher/sqlite3.h:5944:10: Redefinition of 'sqlite3_index_constraint_usage'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3.h:6763:10: Previous definition is here
/<module-includes>:2:9: In file included from <module-includes>:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:
../Pods/WCDBOptimizedSQLCipher/sqlite3.h:6042:8: Redefinition of 'sqlite3_vtab'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3.h:6894:8: Previous definition is here
/<module-includes>:2:9: In file included from <module-includes>:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:
../Pods/WCDBOptimizedSQLCipher/sqlite3.h:6066:8: Redefinition of 'sqlite3_vtab_cursor'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3.h:6918:8: Previous definition is here
/<module-includes>:2:9: In file included from <module-includes>:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:
../Pods/WCDBOptimizedSQLCipher/sqlite3.h:6561:8: Redefinition of 'sqlite3_mutex_methods'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3.h:7422:8: Previous definition is here
/<module-includes>:2:9: In file included from <module-includes>:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:
../Pods/WCDBOptimizedSQLCipher/sqlite3.h:7099:8: Redefinition of 'sqlite3_pcache_page'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3.h:8161:8: Previous definition is here
/<module-includes>:2:9: In file included from <module-includes>:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:
../Pods/WCDBOptimizedSQLCipher/sqlite3.h:7264:8: Redefinition of 'sqlite3_pcache_methods2'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3.h:8326:8: Previous definition is here
/<module-includes>:2:9: In file included from <module-includes>:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3ext.h:20:
../Pods/WCDBOptimizedSQLCipher/sqlite3.h:7287:8: Redefinition of 'sqlite3_pcache_methods'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/sqlite3.h:8349:8: Previous definition is here
Could not build Objective-C module 'SQLite3'

**Comment by GrayLand119** [comment]
I had created another new project for checking Carthage if work fine, here is out put:
>>> carthage update
*** Fetching WCDB
*** Checking out WCDB at "v1.0.8"
*** xcodebuild output can be found in /var/folders/ly/634vz3bx5wn1swqc3j94_dc80000gn/T/carthage-xcodebuild.g09fVt.log
*** Downloading WCDB.framework binary at "WCDB 1.0.8"
I cancelled building after Downloaded. 

And then, I didn't do any other thing, just open the previous project which I encounter with the Redefinition Error above, and rebuild it. The amazing thing was happened, the Error was gone.

**Comment by mason-hz** [comment]
**Same problem here**

<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "sqlite3ext.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:
#include <sqlite3.h>
         ^
/Users/fanmao/Library/Developer/Xcode/DerivedData/AelfApp-fttcwrdjedclzphfsfjjppdlyyud/Build/Products/Debug-iphonesimulator/WCDBOptimizedSQLCipher/sqlcipher.framework/Headers/sqlite3.h:650:8: error: redefinition of 'sqlite3_file'
struct sqlite3_file {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3.h:693:8: note: previous definition is here
struct sqlite3_file {
       ^
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "sqlite3ext.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:
#include <sqlite3.h>
         ^
/Users/fanmao/Library/Developer/Xcode/DerivedData/AelfApp-fttcwrdjedclzphfsfjjppdlyyud/Build/Products/Debug-iphonesimulator/WCDBOptimizedSQLCipher/sqlcipher.framework/Headers/sqlite3.h:745:8: error: redefinition of 'sqlite3_io_methods'
struct sqlite3_io_methods {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3.h:792:8: note: previous definition is here
struct sqlite3_io_methods {
       ^
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "sqlite3ext.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:
#include <sqlite3.h>
         ^
/Users/fanmao/Library/Developer/Xcode/DerivedData/AelfApp-fttcwrdjedclzphfsfjjppdlyyud/Build/Products/Debug-iphonesimulator/WCDBOptimizedSQLCipher/sqlcipher.framework/Headers/sqlite3.h:1226:8: error: redefinition of 'sqlite3_vfs'
struct sqlite3_vfs {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3.h:1378:8: note: previous definition is here
struct sqlite3_vfs {
       ^
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "sqlite3ext.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:
#include <sqlite3.h>
         ^
/Users/fanmao/Library/Developer/Xcode/DerivedData/AelfApp-fttcwrdjedclzphfsfjjppdlyyud/Build/Products/Debug-iphonesimulator/WCDBOptimizedSQLCipher/sqlcipher.framework/Headers/sqlite3.h:1523:8: error: redefinition of 'sqlite3_mem_methods'
struct sqlite3_mem_methods {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3.h:1675:8: note: previous definition is here
struct sqlite3_mem_methods {
       ^
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "sqlite3ext.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:
#include <sqlite3.h>
         ^
/Users/fanmao/Library/Developer/Xcode/DerivedData/AelfApp-fttcwrdjedclzphfsfjjppdlyyud/Build/Products/Debug-iphonesimulator/WCDBOptimizedSQLCipher/sqlcipher.framework/Headers/sqlite3.h:3662:20: error: typedef redefinition with different types ('struct Mem' vs 'struct sqlite3_value')
typedef struct Mem sqlite3_value;
                   ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3.h:4242:30: note: previous definition is here
typedef struct sqlite3_value sqlite3_value;
                             ^
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "sqlite3ext.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:
#include <sqlite3.h>
         ^
/Users/fanmao/Library/Developer/Xcode/DerivedData/AelfApp-fttcwrdjedclzphfsfjjppdlyyud/Build/Products/Debug-iphonesimulator/WCDBOptimizedSQLCipher/sqlcipher.framework/Headers/sqlite3.h:5798:8: error: redefinition of 'sqlite3_module'
struct sqlite3_module {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3.h:6608:8: note: previous definition is here
struct sqlite3_module {
       ^
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "sqlite3ext.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:
#include <sqlite3.h>
         ^
/Users/fanmao/Library/Developer/Xcode/DerivedData/AelfApp-fttcwrdjedclzphfsfjjppdlyyud/Build/Products/Debug-iphonesimulator/WCDBOptimizedSQLCipher/sqlcipher.framework/Headers/sqlite3.h:5929:8: error: redefinition of 'sqlite3_index_info'
struct sqlite3_index_info {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3.h:6748:8: note: previous definition is here
struct sqlite3_index_info {
       ^
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "sqlite3ext.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:
#include <sqlite3.h>
         ^
/Users/fanmao/Library/Developer/Xcode/DerivedData/AelfApp-fttcwrdjedclzphfsfjjppdlyyud/Build/Products/Debug-iphonesimulator/WCDBOptimizedSQLCipher/sqlcipher.framework/Headers/sqlite3.h:5932:10: error: redefinition of 'sqlite3_index_constraint'
  struct sqlite3_index_constraint {
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3.h:6751:10: note: previous definition is here
  struct sqlite3_index_constraint {
         ^
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "sqlite3ext.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:
#include <sqlite3.h>
         ^
/Users/fanmao/Library/Developer/Xcode/DerivedData/AelfApp-fttcwrdjedclzphfsfjjppdlyyud/Build/Products/Debug-iphonesimulator/WCDBOptimizedSQLCipher/sqlcipher.framework/Headers/sqlite3.h:5939:10: error: redefinition of 'sqlite3_index_orderby'
  struct sqlite3_index_orderby {
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3.h:6758:10: note: previous definition is here
  struct sqlite3_index_orderby {
         ^
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "sqlite3ext.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:
#include <sqlite3.h>
         ^
/Users/fanmao/Library/Developer/Xcode/DerivedData/AelfApp-fttcwrdjedclzphfsfjjppdlyyud/Build/Products/Debug-iphonesimulator/WCDBOptimizedSQLCipher/sqlcipher.framework/Headers/sqlite3.h:5944:10: error: redefinition of 'sqlite3_index_constraint_usage'
  struct sqlite3_index_constraint_usage {
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3.h:6763:10: note: previous definition is here
  struct sqlite3_index_constraint_usage {
         ^
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "sqlite3ext.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:
#include <sqlite3.h>
         ^
/Users/fanmao/Library/Developer/Xcode/DerivedData/AelfApp-fttcwrdjedclzphfsfjjppdlyyud/Build/Products/Debug-iphonesimulator/WCDBOptimizedSQLCipher/sqlcipher.framework/Headers/sqlite3.h:6042:8: error: redefinition of 'sqlite3_vtab'
struct sqlite3_vtab {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3.h:6894:8: note: previous definition is here
struct sqlite3_vtab {
       ^
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "sqlite3ext.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:
#include <sqlite3.h>
         ^
/Users/fanmao/Library/Developer/Xcode/DerivedData/AelfApp-fttcwrdjedclzphfsfjjppdlyyud/Build/Products/Debug-iphonesimulator/WCDBOptimizedSQLCipher/sqlcipher.framework/Headers/sqlite3.h:6066:8: error: redefinition of 'sqlite3_vtab_cursor'
struct sqlite3_vtab_cursor {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3.h:6918:8: note: previous definition is here
struct sqlite3_vtab_cursor {
       ^
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "sqlite3ext.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:
#include <sqlite3.h>
         ^
/Users/fanmao/Library/Developer/Xcode/DerivedData/AelfApp-fttcwrdjedclzphfsfjjppdlyyud/Build/Products/Debug-iphonesimulator/WCDBOptimizedSQLCipher/sqlcipher.framework/Headers/sqlite3.h:6561:8: error: redefinition of 'sqlite3_mutex_methods'
struct sqlite3_mutex_methods {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3.h:7422:8: note: previous definition is here
struct sqlite3_mutex_methods {
       ^
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "sqlite3ext.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:
#include <sqlite3.h>
         ^
/Users/fanmao/Library/Developer/Xcode/DerivedData/AelfApp-fttcwrdjedclzphfsfjjppdlyyud/Build/Products/Debug-iphonesimulator/WCDBOptimizedSQLCipher/sqlcipher.framework/Headers/sqlite3.h:7099:8: error: redefinition of 'sqlite3_pcache_page'
struct sqlite3_pcache_page {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3.h:8161:8: note: previous definition is here
struct sqlite3_pcache_page {
       ^
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "sqlite3ext.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:
#include <sqlite3.h>
         ^
/Users/fanmao/Library/Developer/Xcode/DerivedData/AelfApp-fttcwrdjedclzphfsfjjppdlyyud/Build/Products/Debug-iphonesimulator/WCDBOptimizedSQLCipher/sqlcipher.framework/Headers/sqlite3.h:7264:8: error: redefinition of 'sqlite3_pcache_methods2'
struct sqlite3_pcache_methods2 {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3.h:8326:8: note: previous definition is here
struct sqlite3_pcache_methods2 {
       ^
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "sqlite3ext.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:
#include <sqlite3.h>
         ^
/Users/fanmao/Library/Developer/Xcode/DerivedData/AelfApp-fttcwrdjedclzphfsfjjppdlyyud/Build/Products/Debug-iphonesimulator/WCDBOptimizedSQLCipher/sqlcipher.framework/Headers/sqlite3.h:7287:8: error: redefinition of 'sqlite3_pcache_methods'
struct sqlite3_pcache_methods {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3.h:8349:8: note: previous definition is here
struct sqlite3_pcache_methods {
       ^
<unknown>:0: error: could not build Objective-C module 'SQLite3'

**Comment by mukesh-mt** [comment]
I'm having same issue. Any workaround for this?

**Comment by celinahiyasjavier** [comment]
Also encountering this issue. Is it possible for the redefined sqlite files be contained in this library only to avoid conflict with other libraries?
