### ISSUE TITLE
如何按照多个条件排序查询结果

### ISSUE THREAD

**Issue by haotiankeji** [Tencent/wcdb#80]

**Comment by RingoD** [comment]
如果你的指的是order by的话，可以看下sample：https://github.com/Tencent/wcdb/blob/master/apple/sample/convenient/sample_convenient_main.mm

```
    //Select Objects with condition/order/offset/limit
    {
        NSArray<WCTSampleConvenient *> *objects = [database getObjectsOfClass:WCTSampleConvenient.class
                                                                    fromTable:tableName
                                                                      orderBy:WCTSampleConvenient.intValue.order(WCTOrderedAscending)
                                                                        limit:1
                                                                       offset:2];
    }
```

如果不是，麻烦给一下详细的描述和示例

**Comment by summerHearts** [comment]
比如 order by age , create_time 这样的， 怎么解决呢

**Comment by suifens** [comment]
https://github.com/Tencent/wcdb/wiki/%E4%BB%8EFMDB%E8%BF%81%E7%A7%BB%E5%88%B0WCDB中的WINQ和字段映射表有说明

**Comment by suifens** [comment]
https://github.com/Tencent/wcdb/wiki/%E4%BB%8EFMDB%E8%BF%81%E7%A7%BB%E5%88%B0WCDB 中的 [WINQ和字段映射](https://github.com/Tencent/wcdb/wiki/%E4%BB%8EFMDB%E8%BF%81%E7%A7%BB%E5%88%B0WCDB#winq%E5%92%8C%E5%AD%97%E6%AE%B5%E6%98%A0%E5%B0%84) 表中有说明
