### ISSUE TITLE
关于WCDB集成的坑。

### ISSUE THREAD

**Issue by 295060456** [Tencent/wcdb#800]
内联函数、mm文件里面创建对象只能用alloc init，不能用new

此外，还需要在xcode里面进行如下配置：
![添加如下字段](https://user-images.githubusercontent.com/13795605/112753439-df42dc00-9001-11eb-8c89-7fca8dda6160.png)

**Comment by makehapi** [comment]
放弃吧，都不维护了，研究了半天，白费功夫，数据库都是用的老的版本

**Comment by a714857512** [comment]
swift都很久不更新了，这些国内大厂都是这样，kpi一没有，就不维护了，少用点这些国内大厂的东西。

**Comment by wujianguo** [comment]
这边建了个 repo，把 swift 版本的 WCDB 单独拿出来了，去掉了之前的历史记录与其他代码，加快下载集成速度，已经支持 swift5，可以直接使用。https://github.com/codesanatorium/WCDB.swift

**Comment by muken88** [comment]
> 放弃吧，都不维护了，研究了半天，白费功夫，数据库都是用的老的版本

又维护了
