### ISSUE TITLE
WCTDatabase 对象如何获取db的所有表名称

### ISSUE THREAD

**Issue by nchkdxlq** [Tencent/wcdb#804]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.7

### The platform of WCDB

> iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

在一个db中，动态的计算表名称再创建表，现在需要对表结构升级添加一列。由于不知道表的名称，就不能很方便的给表结果添加列，如何通过WCTDatabase对象获取db的所有表名称呢？

**Comment by gdutxzy** [comment]
WCTMaster.TableName 查询这张表就好了
