### ISSUE TITLE
Doubt for CoreStatement's method definition

### ISSUE THREAD

**Issue by slkai** [Tencent/wcdb#805]
### The language of WCDB
Swift

### The version of WCDB
v1.0.8.2

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?

It seems that methodA could be replaced by methodB in CoreStatement, any reason to define methodA?
For less type inference?

methodA: 
```
public func value(atIndex index: Int, of type: ColumnDecodable.Type) -> ColumnDecodable?
```

methodB: 
```
public func value<ColumnDecodableType: ColumnDecodable>(
        atIndex index: Int,
        of type: ColumnDecodableType.Type = ColumnDecodableType.self) -> ColumnDecodableType?
```

**Comment by Qiuwen-chen** [comment]
CoreStatement is remove in WCDB  2.0
