### ISSUE TITLE
include wcdb.h in example's .mm file!

### ISSUE THREAD

**Issue by Godlowd** [Tencent/wcdb#808]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

You should include the file <WCDB/wcdb.h> in your example's .mm file, which is confusing for novice, the Xcode is always noticing me that I have not written the code correctly until I create the template. It would be better to include it in your example

**Comment by Qiuwen-chen** [comment]
Got it.
