### ISSUE TITLE
跨数据库联表查询如何实现 swift

### ISSUE THREAD

**Issue by JasonEVA** [Tencent/wcdb#809]
### The language of WCDB

> Swift 

### The version of WCDB

> v1.0.8

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

你好，我使用WCDB创建了两个数据库，A数据库中的A1表是用于储存题库的（A数据库可能会被整体替换）。B数据库中的B1表用于储存用户答题信息，两张表使用的主键都是题目的id。我现在需要跨数据库联表查询数据，查询出每一道题，并且包括用户对于这题的操作情况，请问如何实现？我在文档中只找到了，同一数据库中的联表查询，现在想知道跨数据库联表查询如何实现。

**Comment by Qiuwen-chen** [comment]
You should use StatementAttach to attach database B to database A firstly.

**Comment by lisiqiang** [comment]
你好 我这边通过sql语句 将aaa数据库附加到 bbb数据库，访问时，报找不到数据库（aaa）中的表，WCDB 不知道支持不支持跨数据库联表查询啊，我是将sqlite迁移到WCDB,遇到这个问题
ATTACH DATABASE /data/user/0/xxxx/databases/aaa.db AS mydb KEY 'aaaa';

**Comment by Qiuwen-chen** [comment]
You can use StatementAttach to attach the aaa, and then use StatementInsert/StatementUpdate/StatementDelete/StatementSelect to read or write the data in aaa. Some tutorial of statement can be found here: https://github.com/Tencent/wcdb/wiki/Swift-%e9%ab%98%e7%ba%a7%e6%8e%a5%e5%8f%a3
