### ISSUE TITLE
ColumnResult::Any()的问题

### ISSUE THREAD

**Issue by crazyevent** [Tencent/wcdb#81]
用这个构造查询的话，变成select '*' 了。

**Comment by crazyevent** [comment]
ColumnResultList retList;
retList.push_back(ColumnResult::Any());

**Comment by RingoD** [comment]
是的，有什么问题

**Comment by crazyevent** [comment]
select '*' from table会报错吧。

**Comment by RingoD** [comment]
确认是bug，这个在ORM层没有使用，所有没意识到问题。
你可以先用`ColumnResult(Column::Any)`
