### ISSUE TITLE
dyld: Library not loaded: @rpath/WCDBSwift.framework/WCDBSwift

### ISSUE THREAD

**Issue by iosyangxiaodong** [Tencent/wcdb#812]
dyld: Library not loaded: @rpath/WCDBSwift.framework/WCDBSwift
  Referenced from: /private/var/containers/Bundle/Application/C484DFDD-BFC6-4943-8E74-017A0503C878/driver.app/Frameworks/db.framework/db
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/usr/lib/libMTLCapture.dylib
为什么找不到库

**Comment by iosyangxiaodong** [comment]
有人知道什么原因吗

**Comment by TyrantDante** [comment]
LD_RUNPATH_SEARCH_PATHS = @executable_path/Frameworks

**Comment by Qiuwen-chen** [comment]
You need to check your project configuration.
