### ISSUE TITLE
添加联合主键后，插入失败

### ISSUE THREAD

**Issue by 0xBa0** [Tencent/wcdb#815]
### The language of WCDB
>  Objective-C

### The version of WCDB
> 1.0.7.5

### The platform of WCDB
> iOS

### The installation of WCDB
>Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

Firstly, I setup a muti-primary key as 'name', then insert to db, success.
![image](https://user-images.githubusercontent.com/39689377/124557215-d2891c00-de6b-11eb-872f-3eb9085228d0.png)

Next, I add a muti-primary key as 'userId', then  use 'createTableAndIndexesOfName: ' to update columns. I have some errors when inserting an object with the same 'name' but different 'userId'.
![image](https://user-images.githubusercontent.com/39689377/124556549-f8fa8780-de6a-11eb-859d-8a0535f50f30.png)

```Objective-C
// .h
@interface DBPerson (WCTTableCoding)<WCTTableCoding>
WCDB_PROPERTY(name)
//WCDB_PROPERTY(userId)
@end

// .mm
@implementation DBPerson
WCDB_IMPLEMENTATION(DBPerson);

WCDB_SYNTHESIZE(DBPerson, name)
//WCDB_SYNTHESIZE_DEFAULT(DBPerson, userId, -1)

WCDB_MULTI_PRIMARY(DBPerson,  "PrimaryConstraint", name)
//WCDB_MULTI_PRIMARY(DBPerson,  "PrimaryConstraint", userId)
@end
```

Errors: 

[WCDB][DEBUG]Code:1555, Type:SQLiteGlobal, Msg:abort at 11 in [INSERT INTO DBPerson(name,userId) VALUES(?,?)]: UNIQUE constraint failed: DBPerson.name
[WCDB][ERROR]Code:19, Type:SQLite, Tag:0, Op:5, ExtCode:1555, Msg:UNIQUE constraint failed: DBPerson.name, SQL:INSERT INTO DBPerson(name,userId) VALUES(?,?), Path:/Users/xxx/Library/Developer/CoreSimulator/Devices/B1F7BA1B-9122-4344-A277-70C159C0BA5E/data/Containers/Data/Application/75306CE3-5F45-4D19-88FC-4735CBB0CE12/Documents/DATABASE_NAME
[WCDB][ERROR]Code:19, Type:SQLite, Tag:0, Op:6, ExtCode:1555, Msg:UNIQUE constraint failed: DBPerson.name, Path:/Users/xxx/Library/Developer/CoreSimulator/Devices/B1F7BA1B-9122-4344-A277-70C159C0BA5E/data/Containers/Data/Application/75306CE3-5F45-4D19-88FC-4735CBB0CE12/Documents/DATABASE_NAME

**Comment by hapiii** [comment]
我也遇到这个问题了。请问您有什么好的解决方案吗？

**Comment by Qiuwen-chen** [comment]
You cannot modify the constraints of an already created table. In fact, the multi primary key was not configured successfully.
