### ISSUE TITLE
WCDB.swift 使用默认setCipher(key: "")加密数据库，导出到mac后无法用终端解密

### ISSUE THREAD

**Issue by lileitodev** [Tencent/wcdb#816]
### The language of WCDB
> Swift
### The version of WCDB
> 1.0.8.2
### The platform of WCDB
> iOS
### The installation of WCDB
> Cocoapods

### 问题描述
在iOS端app，使用默认加密方法`setCipher(key: "")` 加密了数据库，app可以正常读取数据库数据。
导出到mac想要查看数据，无法解密。
同样，使用`wcdb/swift/sample `项目中生成的数据库文件也是无法解密

### 使用sample生成的数据库文件解密步骤
```
./sqlcipher SampleRepair
PRAGMA key='databaseCipher';
PRAGMA cipher_page_size=4096;
```
### sample 中加密代码部分
![image](https://user-images.githubusercontent.com/37165325/126078326-cdc9e577-d8d3-4e0e-a609-6ddb14266803.png)

### 终端操作截屏
![image](https://user-images.githubusercontent.com/37165325/126078507-bac21de3-a811-43ff-8d1f-24a3d2426d5d.png)

### 其他
自己使用sqlcipher自己创建加密和解密数据库是可以正常操作成功的。所以不知道少了什么步骤导致了无法成功解密。

**Comment by lileitodev** [comment]
忽然灵光一闪，使用了sqlcipher3 的默认参数来解密，竟然操作成功了。。。
```
./sqlcipher sqlcipher3.sqlite
PRAGMA key = 'MIwkB*+}R(0gS7@t';
PRAGMA cipher_page_size = 4096;
PRAGMA kdf_iter = 64000;
PRAGMA cipher_hmac_algorithm = HMAC_SHA1;
PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA1;
ATTACH DATABASE 'sqlcipher-4.db' AS sqlcipher4 KEY '';
SELECT sqlcipher_export('sqlcipher4');
DETACH DATABASE sqlcipher4;
```
我之前没有成功，原因是终端sqlcipher程序默认使用的是sqlcipher4的参数来解密，但是wcdb使用的是sqlcipher3 所以解密失败.
希望对后来者有所帮助。

**Comment by MrPans** [comment]
@lileitodev 和你使用相同的 wcdb 版本，在 swift 中使用 wcdb 创建加密的 sqllite 文件，使用终端无法解密。 终端中尝试使用了 sqlcipher3 的默认参数依然无效，想问问是不是有其他可能的原因？

创建 db 文件：
```swift
database = Database(withPath: DatabaseManager.dbPath)
let password = "MIwkB*+}R(0gS7@t".data(using: .ascii)
 self.database.setCipher(key: password)
```

终端解密：
```bash
sqlite> PRAGMA key = 'MIwkB*+}R(0gS7@t';
ok
sqlite> PRAGMA cipher_page_size = 4096;
sqlite> PRAGMA kdf_iter = 64000;
sqlite> PRAGMA cipher_hmac_algorithm = HMAC_SHA1;
sqlite> PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA1;
sqlite> ATTACH DATABASE 'aaa.db' AS sqlcipher4 KEY '';
Runtime error: file is not a database (26)
```

**Comment by lileitodev** [comment]
> @lileitodev 和你使用相同的 wcdb 版本，在 swift 中使用 wcdb 创建加密的 sqllite 文件，使用终端无法解密。 终端中尝试使用了 sqlcipher3 的默认参数依然无效，想问问是不是有其他可能的原因？
> 
> 创建 db 文件：
> 
> ```swift
> database = Database(withPath: DatabaseManager.dbPath)
> let password = "MIwkB*+}R(0gS7@t".data(using: .ascii)
>  self.database.setCipher(key: password)
> ```
> 
> 终端解密：
> 
> ```shell
> sqlite> PRAGMA key = 'MIwkB*+}R(0gS7@t';
> ok
> sqlite> PRAGMA cipher_page_size = 4096;
> sqlite> PRAGMA kdf_iter = 64000;
> sqlite> PRAGMA cipher_hmac_algorithm = HMAC_SHA1;
> sqlite> PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA1;
> sqlite> ATTACH DATABASE 'aaa.db' AS sqlcipher4 KEY '';
> Runtime error: file is not a database (26)
> ```

首先，你需要用sqlciper 的终端应用打开才行。
`./sqlcipher sqlcipher3.sqlite`
这一句就是用sqlcipher 打开数据库的。 @MrPans
