### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by WangKunKun** [Tencent/wcdb#819]
### The language of WCDB

Swift 

### The version of WCDB

1.0.8.2

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

7   WCDBSwift                           0x0000000107093e28 $s9WCDBSwift6HandleC7prepareyAA0B9StatementCAA0D0_pKF + [Handle.swift : 90] 
8   WCDBSwift                           0x0000000107083fbc $s9WCDBSwift8DatabaseC7prepareyAA25RecyclableHandleStatementCAA0F0_pKF + [Core.swift : 47] 
9   WCDBSwift                           0x00000001070b1874 $s9WCDBSwift6SelectC10allObjects2ofSayxGxm_tKAA14TableDecodableRzlF + [<compiler-generated> : 0] 
10  WCDBSwift                           0x000000010709d0b4 $s9WCDBSwift15SelectInterfacePA2A4CoreCRbzrlE10getObjects2on9fromTable5where7orderBy5limit6offsetSayqd__GSayAA19PropertyConvertible_pG_SSAA010ExpressionP0_pSgSayAA05OrderP0_pGSgA2QtKAA0I9DecodableRd__lF + [Interface.swift : 713] 
11  WCDBSwift                           0x000000010709fb94 $s9WCDBSwift11TransactionCAA15SelectInterfaceA2aDP10getObjects2on9fromTable5where7orderBy5limit6offsetSayqd__GSayAA19PropertyConvertible_pG_SSAA010ExpressionP0_pSgSayAA05OrderP0_pGSgA2QtKAA0I9DecodableRd__lFTW + [<compiler-generated> : 0] 
12  WCDBSwift                           0x00000001070a0354 $s9WCDBSwift8DatabaseCAA15SelectInterfaceA2aDP10getObjects2on9fromTable5where7orderBy5limit6offsetSayqd__GSayAA19PropertyConvertible_pG_SSAA010ExpressionP0_pSgSayAA05OrderP0_pGSgA2QtKAA0I9DecodableRd__lFTW
13  WCDBSwift                           0x000000010709d204 $s9WCDBSwift15SelectInterfacePA2A4CoreCRbzrlE10getObjects2on9fromTable5where7orderBy5limit6offsetSayqd__GAA19PropertyConvertible_pd_SSAA010ExpressionP0_pSgSayAA05OrderP0_pGSgA2PtKAA0I9DecodableRd__lF + [Interface.swift : 723] 

现在app中大部分的crash 来自于贵sdk·· 麻烦更新一下吧··

**Comment by Qiuwen-chen** [comment]
Please present more detail about this crash. We will update WCDB  soon.

**Comment by Qiuwen-chen** [comment]
Please use WCDB 2.0 and see if there is still this problem.
