### ISSUE TITLE
创建数据库失败

### ISSUE THREAD

**Issue by cxz137131304** [Tencent/wcdb#821]
当前版本1.0.7，一直使用正常的测试机，iphone 6s ,13.5.1的系统，突然掉用数据库爆以下这个错误。
create WCDB Table failure at Document  Code:21, Type:SQLite, Msg:[sqlite3_key] is not supported for current config, Tag:0, ExtCode:21, Path:/var/mobile/Containers/Data/Application/94F09C30-610D-469F-B7D1-687BEFBFCE00/Documents/chatDB.db, Op:7

**Comment by Qiuwen-chen** [comment]
You should build sqlcipher with SQLITE_HAS_CODEC.
