### ISSUE TITLE
SQLite version 3.15.2  有很多漏洞，官网已经更新了，咱们什么时候更新呀

### ISSUE THREAD

**Issue by QiuYeHong90** [Tencent/wcdb#823]
`#define SQLITE_VERSION        "3.15.2"
#define SQLITE_VERSION_NUMBER 3015002
#define SQLITE_SOURCE_ID      "2016-11-28 19:13:37 bbd85d235f7037c6a033a9690534391ffeacecc8"`

**Comment by Qiuwen-chen** [comment]
We will upgrade sqlite soon.
