### ISSUE TITLE
crash:  sqlcipher sqlite3DbMallocRawNN + 64

### ISSUE THREAD

**Issue by yixianxueqi** [Tencent/wcdb#824]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

swift

### The version of WCDB

> e.g. v1.0.5

1.0.8.2

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

firebase捕获：
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/12805642/131111790-4c112e7c-5822-4ca5-a3cd-faffc70881da.png">

源码：
> 数据库相关

```
    func insertOrUpdateWebStorage(dict: [String: String]?, appID: String?) -> Bool {
        guard let dict = dict, let appId = appID, dict.count >= 2, appId.count > 0 else { return false }        
        let model = KDWebStorageModel(dict: dict, appId: appId)
        
        do {
            try database.insertOrReplace(objects: [model], intoTable: tableName(type: XTTableType.webStorage))
        } catch  {
            return false
        }
        
        return true
    }

```

> 模型映射

```
import Foundation
import WCDBSwift

class KDWebStorageModel:KDJSONModel,TableCodable {
    var key: String?
    var value: String?
    var appId: String?
    
    public enum CodingKeys: String, CodingTableKey {
        public typealias Root = KDWebStorageModel
        public static let objectRelationalMapping = TableBinding(CodingKeys.self)
        
        //字段约束
        static var columnConstraintBindings: [CodingKeys: ColumnConstraintBinding]? {
            return [
                key: ColumnConstraintBinding(isPrimary: true),
            ]
        }
        
        case key
        case value
        case appId
    }
    
    
    init(dict: [String: String], appId: String) {
        super.init()  
        if let key = dict["key"], let value = dict["value"] {
            self.key = appId + key
            self.value = value
            self.appId = appId
        }
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    required init(data: Data!) throws {
        fatalError("init(data:) has not been implemented")
    }
    
    required init(dictionary dict: [AnyHashable : Any]!) throws {
        fatalError("init(dictionary:) has not been implemented")
    }
}
```

遇到很多崩溃在此处(其它表也是同样的)：sqlcipher sqlite3DbMallocRawNN + 64，想知道如何解决？以及什么时候可以更新版本出来，2年多没升级了。。。

**Comment by QiuYeHong90** [comment]
sqlite 不打算升级了么

**Comment by winwys** [comment]
同样的问题+1

**Comment by yixianxueqi** [comment]
在社区群得到的处理方案：

目前大部分崩溃在 void *sqlite3DbMallocRawNN 函数，此函数通过宏SQLITE_OMIT_LOOKASIDE（禁止后备内存分配）来实现2套逻辑，目前走了后备内存分配的方案。

解决方案：

```ruby
#在Podfile中添加
post_install do |pi|
    pi.pods_project.targets.each do |t|
      if t.name == 'WCDBOptimizedSQLCipher'
        t.build_configurations.each do |config|
          if config.name == 'Release' || config.name == 'Debug'
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)','SQLITE_OMIT_LOOKASIDE']
          end
        end
      end
    end
end
```

目的是在WCDB引用的WCDBOptimizedSQLCipher库中，配置添加宏SQLITE_OMIT_LOOKASIDE，让sqlite3DbMallocRawNN方法走另一套非后备内存分配的方案。

**Comment by cqwicqw** [comment]
What is the probability of this crash? In WeChat, only one person per million people encounters this crash every day, so we don't consider dealing with this problem. The possible cause of this problem is heap memory corruption or multi-threaded use of sqlite3_stmt.

**Comment by yixianxueqi** [comment]
> What is the probability of this crash? In WeChat, only one person per million people encounters this crash every day, so we don't consider dealing with this problem. The possible cause of this problem is heap memory corruption or multi-threaded use of sqlite3_stmt.

较早的数据已经没有了，平常万次会话崩溃率在0.07%，而这个问题导致崩溃率上升了0.04%；按照社区给的方案做了处理。

**Comment by Leon-OS** [comment]
> 

按照社区的方法根解了吗？

**Comment by yixianxueqi** [comment]
> 按照社区的方法根解了吗？

根解了；

**Comment by Qiuwen-chen** [comment]
Please use WCDB 2.0 and see if there is still this problem.
