### ISSUE TITLE
子查询

### ISSUE THREAD

**Issue by JHCarpediem** [Tencent/wcdb#826]
SELECT datetime(msg_time/1000, 'unixepoch', 'localtime') FROM (SELECT * FROM im_msg ORDER BY msg_time DESC) GROUP BY (STRFTIME('%Y-%m-%d', DATETIME(msg_time/1000, 'unixepoch', 'localtime')))

请问以上子查询在wcdb怎么使用

**Comment by hznge** [comment]
SubqueryList

**Comment by cqwicqw** [comment]
You can use code like this:
WCTStatement *statement = [database prepare:WCDB::StatementSelect()select(xxx).from(WCDB::StatementSelect().select(xxxx).from(xxx).where(xxx))];
         if (statement && [statement step]) {
             NSLog(@"Cache size %@", [statement getValueAtIndex:0]);
         }
