### ISSUE TITLE
Could not build Objective-C module 'SQLite3'

### ISSUE THREAD

**Issue by Five0314** [Tencent/wcdb#829]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

I created a new swift project and imported wcdb using cocoapods, and ...
the following errors occurred :
<img width="2293" alt="WX20210918-180540@2x" src="https://user-images.githubusercontent.com/4555607/133885166-d205dc48-07f8-4f5f-b9b8-be644187cbba.png">

Could not build Objective-C module 'SQLite3'

 In file included from /Users/**/Downloads/Xcode_12.5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sqlite3ext.h:20:

**Comment by ZTKevin** [comment]
same question，wcdb1.0.8.2, swift 5，-xcode14.2，iOS，Cocoapods
issue：Could not build Objective-C module 'SQLite3'

**Comment by Qiuwen-chen** [comment]
Please try WCDB 2.0 to see if this problem still exists.
