### ISSUE TITLE
可以不上传安卓的prebuild文件吗, 文件太大, clone失败好多次

### ISSUE THREAD

**Issue by c344081** [Tencent/wcdb#83]
我只是想看下iOS的demo, 一整天过去了, 竟然还没clone完😂, 放在里面cocoapods集成的时候也会先下载这些文件...

**Comment by crazyevent** [comment]
这个，git翻个墙吧。

**Comment by John-He-928** [comment]
后续试着将prebuilt放到submodule

**Comment by c344081** [comment]
我翻墙拖了一遍...最慢的是openssl😅. 另外cocoapods集成的时候, 安卓prebuilt里的文件iOS本来是不需要的,但是也会下载, 感觉挺浪费的..另外podspec加了:submodules => true的时候, 所有的submodule应该都会被clone, 所以放submodule还是会被下载的😅

**Comment by John-He-928** [comment]
Android的依赖项编译起来非常麻烦，所以才放的预编译库。这个clone过一次后面基本不会改了
