### ISSUE TITLE
WCTTokenizerNameWCDB分词搜索无效果，只匹配一条数据

### ISSUE THREAD

**Issue by x1340939306** [Tencent/wcdb#832]
//prepare
    {
        //English
        GZIMFTSBase *object = [[GZIMFTSBase alloc] init];
        object.name = @"English";
        object.content = @"!树！";
        object.isAutoIncrement = YES;
        [databaseOrigin insertObject:object into:tableNameOrigin];
    }
    {
        //Number
        GZIMFTSBase *object = [[GZIMFTSBase alloc] init];
        object.name = @"Number Eng";
        object.content = @"￥果树123$";
        object.isAutoIncrement = YES;
        [databaseOrigin insertObject:object into:tableNameOrigin];
    }
    {
        //Chinese
        GZIMFTSBase *object = [[GZIMFTSBase alloc] init];
        object.name = @"Chinese";
        object.content = @"#苹果#";
        object.isAutoIncrement = YES;
        [databaseOrigin insertObject:object into:tableNameOrigin];
    }
    {
        //Chinese
        GZIMFTSBase *object = [[GZIMFTSBase alloc] init];
        object.name = @"Chinese2";
        object.content = @"$这是一颗苹果树$";
        object.isAutoIncrement = YES;
        [databaseOrigin insertObject:object into:tableNameOrigin];
    }

 [databaseFTS setTokenizer:WCTTokenizerNameWCDB];

    [databaseFTS createVirtualTableOfName:tableNameFTS withClass:GZIMFTSData.class];

NSArray<GZIMFTSData *> *ftsDataArray = [databaseFTS getObjectsOfClass:GZIMFTSData.class fromTable:tableNameFTS where:GZIMFTSData.PropertyNamed(tableNameFTS).match("*苹果树*")];

Match name:Chinese2 content:$这是一颗苹果树$

**Comment by cqwicqw** [comment]
This result is correct.
