### ISSUE TITLE
偶现的在调用isTableExists方法时，崩溃。

### ISSUE THREAD

**Issue by JabberYQ** [Tencent/wcdb#833]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Objective-C

### The version of WCDB

> e.g. v1.0.5

1.0.8.6

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

偶现的在调用isTableExists方法时，崩溃。

![WechatIMG57786](https://user-images.githubusercontent.com/15389684/139213970-e63480e7-9f33-48a2-8ff1-8bc5a2d7a947.png)

**Comment by Qiuwen-chen** [comment]
Please use WCDB 2.0 and see if there is still this problem.
