### ISSUE TITLE
How to implement recursive statements？

### ISSUE THREAD

**Issue by ygf-git** [Tencent/wcdb#835]
How to implement recursive statements？

**Comment by cqwicqw** [comment]
You can use code like this:
WCTStatement *statement = [database prepare:WCDB::StatementSelect().select(xxx).from(WCDB::StatementSelect().select(xxxx).from(xxx).where(xxx))];
if (statement && [statement step]) {
       NSLog(@"value %@", [statement getValueAtIndex:0]);
}
