### ISSUE TITLE
WCDB删除有一个cash

### ISSUE THREAD

**Issue by CoderXO** [Tencent/wcdb#836]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

0
WCDBSwift
reQueue (<compiler-generated>:0)
1
WCDBSwift
reQueue (<compiler-generated>:0)
2
WCDBSwift
_$s9WCDBSwift8DatabaseC14defaultConfigs33_61483DD555A1004C392E92126BE4A25CLLAA0D0VvpZfiyAA6HandleCKcfU2_yAI_SiytSgtcfU_ (<compiler-generated>:0)
3
WCDBSwift
_$s9WCDBSwift6HandleC8register11onCommittedyyAC_SiytSgtc_tFs5Int32VSvSg_s13OpaquePointerVSgSPys4Int8VGSgAHtcfU_To (<compiler-generated>:0)
4
sqlcipher
sqlite3_step (vdbeapi.c:663 [Inline: sqlite3Step])
5
WCDBSwift
step (HandleStatement.swift:46)
6
WCDBSwift
execute (Delete.swift:113)
7
WCDBSwift
delete (Interface.swift:330)

**Comment by CoderXO** [comment]
删除应用程序崩溃

**Comment by cqwicqw** [comment]
Please give more detail
