### ISSUE TITLE
ios15.1 杀后台, app进入后台会被系统很快干掉 Message from debugger: Terminated due to signal 9,有什么解决办法吗

### ISSUE THREAD

**Issue by yuangaopeng** [Tencent/wcdb#838]
### The language of WCDB

> e.g. swift 

### The version of WCDB

> e.g. v1.0.8.2

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by cntrump** [comment]
同一个问题？https://github.com/Tencent/wcdb/issues/847

**Comment by Qiuwen-chen** [comment]
Here might be the reason for that crash: https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_plaintext_header_size

You can config cipher_plaintext_header_size with StatementPragma through Database.setConfig(named:with:orderBy:).
