### ISSUE TITLE
A Warning, Implicit import of bridging header 'WCDB-Bridging.h' via module 'WCDBSwift' is deprecated and will be removed in a later version of Swift

### ISSUE THREAD

**Issue by LionWY** [Tencent/wcdb#839]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Swift

### The version of WCDB

> e.g. v1.0.5

1.0.8.2

### The platform of WCDB

> e.g. iOS, macOS or Android

iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Framework
[PodDemo.zip](https://github.com/Tencent/wcdb/files/7587181/PodDemo.zip)

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

as the Title
can you resolve the warning?
Here is the demo

**Comment by wfs498121294** [comment]
+1

**Comment by cqwicqw** [comment]
Got it. It will be fixed in future version.

**Comment by Qiuwen-chen** [comment]
Fixed in WCDB  2.0
