### ISSUE TITLE
请问 WCTSelectBase+WCTExpr 这个分类是私密的吗？

### ISSUE THREAD

**Issue by zhuangyz** [Tencent/wcdb#84]
我在使用 in(const WCDB::StatementSelectList &statementSelectList) 表达式时需要用到 select 的 statement ，但是发现单单 import <WCDB/WCDB.h> 并不能找到这个 statement ，还需要另外 import <WCDB/WCTSelectBase+WCTExpr.h> 。

**Comment by RingoD** [comment]
`in({selectBase})`

**Comment by zhuangyz** [comment]
好的，谢谢
