### ISSUE TITLE
build 失败

### ISSUE THREAD

**Issue by AIllsMyLee** [Tencent/wcdb#841]
### The language of WCDB

 swift

### The version of WCDB

v1.0.7.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?
<img width="658" alt="QQ20211207-132257@2x" src="https://user-images.githubusercontent.com/37650182/144971430-c7f2a8e5-42a9-4918-81d5-52302c8aafc7.png">

Undefined symbol: _sqlite3_column_type

**Comment by wujianguo** [comment]
Hey, guys, I create a repo for wcdb.swift, wish to maintain it together. https://github.com/codesanatorium/WCDB.swift

**Comment by cqwicqw** [comment]
Please confirm that sqlcipher is compiled together
