### ISSUE TITLE
SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by czbill** [Tencent/wcdb#843]
### The language of WCDB

> Java 

### The version of WCDB

> v1.0.8

### The platform of WCDB

> Android

### The installation of WCDB

>  Maven

### What's the issue?

1
#00 pc 0004e30a /data/app/com.ringleai.ai--RqUwvQ0Hu7RkuJoMH2Tgg==/lib/arm/libwcdb.so [armeabi-v7a::d940a657620c2a944011cc5761e5ac7a]
2
#01 pc 000551e3 /data/app/com.ringleai.ai--RqUwvQ0Hu7RkuJoMH2Tgg==/lib/arm/libwcdb.so (sqlite3_rekey_v2+202) [armeabi-v7a::d940a657620c2a944011cc5761e5ac7a]
3
#02 pc 00066d73 /data/app/com.ringleai.ai--RqUwvQ0Hu7RkuJoMH2Tgg==/lib/arm/libwcdb.so [armeabi-v7a::d940a657620c2a944011cc5761e5ac7a]
4
#03 pc 000691cb /data/app/com.ringleai.ai--RqUwvQ0Hu7RkuJoMH2Tgg==/lib/arm/libwcdb.so [armeabi-v7a::d940a657620c2a944011cc5761e5ac7a]
5
#04 pc 0006a6f9 /data/app/com.ringleai.ai--RqUwvQ0Hu7RkuJoMH2Tgg==/lib/arm/libwcdb.so [armeabi-v7a::d940a657620c2a944011cc5761e5ac7a]
6
#05 pc 0006a917 /data/app/com.ringleai.ai--RqUwvQ0Hu7RkuJoMH2Tgg==/lib/arm/libwcdb.so [armeabi-v7a::d940a657620c2a944011cc5761e5ac7a]
7
#06 pc 000833af /data/app/com.ringleai.ai--RqUwvQ0Hu7RkuJoMH2Tgg==/lib/arm/libwcdb.so [armeabi-v7a::d940a657620c2a944011cc5761e5ac7a]
8
#07 pc 00083443 /data/app/com.ringleai.ai--RqUwvQ0Hu7RkuJoMH2Tgg==/lib/arm/libwcdb.so (sqlite3_prepare16_v2+10) [armeabi-v7a::d940a657620c2a944011cc5761e5ac7a]
9
#08 pc 00015351 /data/app/com.ringleai.ai--RqUwvQ0Hu7RkuJoMH2Tgg==/lib/arm/libwcdb.so [armeabi-v7a::d940a657620c2a944011cc5761e5ac7a]
10
#09 pc 003e5d29 /system/lib/libart.so (art_quick_generic_jni_trampoline+40) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
11
#10 pc 003e1fe1 /system/lib/libart.so (art_quick_invoke_stub_internal+64) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
12
#11 pc 003e665b /system/lib/libart.so (art_quick_invoke_static_stub+226) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
13
#12 pc 000ace47 /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+182) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
14
#13 pc 001f2e53 /system/lib/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+238) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
15
#14 pc 001ee403 /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+574) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
16
#15 pc 003ccf71 /system/lib/libart.so (MterpInvokeStatic+324) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
17
#16 pc 003d4414 /system/lib/libart.so (ExecuteMterpImpl+14612) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
18
#17 pc 001d5985 /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+340) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
19
#18 pc 001dad07 /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+142) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
20
#19 pc 001ee3ed /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+552) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
21
#20 pc 003cbebf /system/lib/libart.so (MterpInvokeVirtual+446) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
22
#21 pc 003d4294 /system/lib/libart.so (ExecuteMterpImpl+14228) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
23
#22 pc 001d5985 /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+340) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
24
#23 pc 001dad07 /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+142) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
25
#24 pc 001ee3ed /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+552) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
26
#25 pc 003cbebf /system/lib/libart.so (MterpInvokeVirtual+446) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
27
#26 pc 003d4294 /system/lib/libart.so (ExecuteMterpImpl+14228) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
28
#27 pc 001d5985 /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+340) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
29
#28 pc 001dad07 /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+142) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
30
#29 pc 001ee3ed /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+552) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
31
#30 pc 003cbebf /system/lib/libart.so (MterpInvokeVirtual+446) [armeabi-v7a::d2078ba50169919802b98e67fdc80c58]
32
java:
33
[Failed to get Java stack]

**Comment by Qiuwen-chen** [comment]
Please try v2.1.0.
