### ISSUE TITLE
WCDB's FTS function errors

### ISSUE THREAD

**Issue by MrBugDou** [Tencent/wcdb#845]
### The language of WCDB

Objective-C

### The version of WCDB

Installing SQLiteRepairKit (1.2.2)
Installing WCDB (1.0.7.5)
Installing WCDBOptimizedSQLCipher (1.2.1)

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
Console output：

[WCDB][DEBUG]Code:1, Type:SQLiteGlobal, Msg:statement aborts at 1: [SELECT fts3_tokenizer(?,?)] @\232\372\201
[WCDB][ERROR]Code:1, Type:SQLite, Tag:0, Op:5, ExtCode:1, Msg:@\232\372\201, SQL:SELECT fts3_tokenizer(?,?), Path:/var/mobile/Containers/Data/Application/E2D19868-7263-48C4-BEA5-B8D744B4610E/Documents/com.geiim.app/10055823/Database/geim_fts.db

Data definition：
![image](https://user-images.githubusercontent.com/12947653/149315664-3ea99b26-00d0-449d-bf97-98dc308ab284.png)

Database init
![image](https://user-images.githubusercontent.com/12947653/149315937-d3a09c35-e9a7-451a-a927-840c3b143d8e.png)

Data preview
![image](https://user-images.githubusercontent.com/12947653/149317397-e9d586cd-da60-436d-984b-7fcb1c32cd62.png)

> Explain what you want by example or code **in English**.

When I use WCDB's FTS function, the console keeps sending out errors

Execute the following code：

![image](https://user-images.githubusercontent.com/12947653/149318676-f505cf99-bc41-4c44-9a14-2ac72a313aa0.png)

The results is empty, but I expect a match

**Comment by yhcflyy** [comment]
我这边设置了分词之后也在报错误：[WCDB][ERROR]Code:1, Type:SQLite, Tag:0, Op:5, ExtCode:1, Msg:@\232\372\201�, SQL:SELECT fts3_tokenizer(?,?),
我发现在调用[database setTokenizer:WCTTokenizerNameWCDB];后必须延迟一点时间就不会报错了

**Comment by MrBugDou** [comment]
> 我设置了分词之后的后续报错：[WCDB][ERROR]Code:1,Type:SQLite, Tag:0, Op:5, ExtCode:1, Msg:@\232\372\201�, SQL :SELECT fts3_tokenizer(?,?), 我发现在调用[database setTokenizer:WCTTokenizerNameWCDB];之后必须一点时间就不会报错了

谢谢，我试试
