### ISSUE TITLE
insertObjects:into

### ISSUE THREAD

**Issue by chengssir** [Tencent/wcdb#849]
Crashed: read_queue
0  xxxxxxxx                        0xb2644c WCDB::Error::report() const + 1885 (functional:1885)
1  xxxxxxxx                        0xb26960 WCDB::Error::Report(WCDB::Error::Type, int, std::__1::map<WCDB::Error::Key, WCDB::ErrorValue, std::__1::less<WCDB::Error::Key>, std::__1::allocator<std::__1::pair<WCDB::Error::Key const, WCDB::ErrorValue> > > const&, WCDB::Error*) + 232 (error.cpp:232)
2  xxxxxxxx                        0xb27c08 WCDB::Error::ReportSQLiteGlobal(int, char const*, WCDB::Error*) + 1079 (__tree:1079)
3  xxxxxxxx                        0xbf1c84 sqlite3_log + 1046 (printf.c:1046)
4  xxxxxxxx                        0xc0a480 sqlite3VdbeExec + 998 (vdbe.c:998)
5  xxxxxxxx                        0xc0b1d4 sqlite3_step + 602 (vdbeapi.c:602)
6  xxxxxxxx                        0xb35230 WCDB::StatementHandle::step() + 47 (handle_statement.cpp:47)
7  xxxxxxxx                        0xb4a250 -[WCTInsert doInsertObjects:withError:] + 126 (WCTInsert.mm:126)
8  xxxxxxxx                        0xb4a59c -[WCTInsert executeWithObjects:] + 154 (WCTInsert.mm:154)
9  xxxxxxxx                        0xb575b8 -[WCTInterface(Convenient) insertObjects:into:] + 1028 (WCTInterface+Convenient.mm:1028)

**Comment by Qiuwen-chen** [comment]
Please use WCDB 2.0 and see if there is still this problem.
