### ISSUE TITLE
drop trigger failed 删除触发器失败 

### ISSUE THREAD

**Issue by JasonLinkinBright** [Tencent/wcdb#850]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

java

### The version of WCDB

> e.g. v1.0.5

v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
fisrt，I have a plain db whit a trigger named like “CREATE TRIGGER IF NOT EXISTS groups_cleanup_test DELETE ON " + NAME1 + " " + "BEGIN "
                    + "DELETE FROM " + NAME2 + " WHERE group_id = old._id;"
                    + "SELECT _DELETE_FILE(old.group_icon);" + "END"”,
and I migrate the plain db to encrypted db，
I want to drop trigger by execSql(drop Trigger trigger_name) in encrypted database using wcdb.
but after that,I find that the trigger is not be deleted, it still exist right there.
I know that the trigger contains error function  _DELETE_FILE,how can I drop the trigger
数据库迁移后，调用drop trigger 语句，发现没有生效，trigger 仍然存在

**Comment by Qiuwen-chen** [comment]
Please try v2.1.0.
