### ISSUE TITLE
iOS15.x app进入后台30秒左右，被系统干掉了，有什么解决方式吗？

### ISSUE THREAD

**Issue by SMYdamao** [Tencent/wcdb#853]
### The language of WCDB

> e.g. Objective-C,

### The version of WCDB

> e.g. v1.0.7.5

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

**Comment by shywoody** [comment]
issue第六个有个同学fork并进行了解决你试试看可不可行，可行记得回来回复下

**Comment by SMYdamao** [comment]
> issue第六个有个同学fork并进行了解决你试试看可不可行，可行记得回来回复下

这个我试了，还是不能解决

**Comment by cqwicqw** [comment]
Please provide more details, maybe this is not caused by WCDB.
