### ISSUE TITLE
WCDB_PRIMARY 唯一主键丢失了

### ISSUE THREAD

**Issue by wxwlcp** [Tencent/wcdb#854]
### The language of WCDB

> e.g. Objective-C
WCDB_PRIMARY 唯一主键丢失了。ORM里面设置了WCDB_PRIMARY，但是不知道为啥数据库里面这个字段不是唯一主键了

**Comment by cqwicqw** [comment]
May be this table has been created before. SQLite does not support changing column constraints for existing tables.
