### ISSUE TITLE
静态库集成  报错  Use of undeclared identifier 'SQLITE_PREPARE_NO_VTAB'    

### ISSUE THREAD

**Issue by liude233** [Tencent/wcdb#859]
### The language of WCDB

 Objective-C

### The version of WCDB

> e.g. v1.0.7

### The platform of WCDB

iOS,

### The installation of WCDB

  Git clone

#
### What's the issue?

[> Post the outputs or screenshots for errors.

Use of undeclared identifier 'SQLITE_PREPARE_NO_VTAB'

> Explain what you want by example or code **in English**.

Use of undeclared identifier 'SQLITE_PREPARE_NO_VTAB'

**Comment by cqwicqw** [comment]
Got it.

**Comment by cqwicqw** [comment]
You can rollback the code to this commit firstly 1f6540b093eb0eba82b277fdda989f6a8da00b5d.
