### ISSUE TITLE
Feature: WINQ可变参数

### ISSUE THREAD

**Issue by mdjwanghong** [Tencent/wcdb#86]
使用wink如何实现？

**Comment by RingoD** [comment]
`[database getObjectsOfClass:WCTSampleORM.class fromTable:@"myTable" where:WCTSampleORM.identifier.in({1, 2, 3, 4, 5})];`

**Comment by RingoD** [comment]
我后续再提供一个可变参数的方式

**Comment by mdjwanghong** [comment]
NSArray *array=[[NSArray alloc] initWithObjects:@1,@2,@3,@4,nil];

    [database getObjectsOfClass:WCTSampleORM.class fromTable:@"myTable" where:WCTSampleORM.identifier.in(array)];

这种方式也可以吧？

**Comment by RingoD** [comment]
可以的

**Comment by mdjwanghong** [comment]
回复的太快了，谢谢！

**Comment by RingoD** [comment]
可变参数无法实现易用的接口
