### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by 937447974** [Tencent/wcdb#860]
### The language of WCDB

> Objective-C

### The version of WCDB

>最新

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

4360   WCDB                                0x000000010afda038 WCDB::Error::report() const + [functional : 1913] 
4371   WCDB                                0x000000010afd9fec WCDB::Error::report() const + [error.cpp : 106] 
4382   WCDB                                0x000000010afda564 WCDB::Error::Report(WCDB::Error::Type, int, std::__1::map<WCDB::Error::Key, WCDB::ErrorValue, std::__1::less<WCDB::Error::Key>, std::__1::allocator<std::__1::pair<WCDB::Error::Key const, WCDB::ErrorValue> > > const&, WCDB::Error*) + [error.cpp : 228] 
4393   WCDB                                0x000000010afdb3c4 WCDB::Error::ReportInterface(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, WCDB::Error::InterfaceOperation, WCDB::Error::InterfaceCode, char const*, WCDB::Error*) + [__tree : 1076] 
4404   WCDB                                0x000000010b02205c -[WCTSelect initWithCore:andResults:fromTable:] + [WCTSelect.mm : 43] 
4415   WCDB                                0x000000010b008bd8 -[WCTInterface(Convenient) getObjectsOfClass:fromTable:where:] + [WCTInterface+Convenient.mm : 0] 
4426   QTCoreData                          0x0000000107c341b4 __63-[QTMessageDBContext resetAllSendingFileMessageStateExceptIds:]_block_invoke_2 + [QTMessageDBContext.mm : 0] 
4437   WCDB                                0x000000010aff88f4 std::__1::__function::__func<-[WCTDatabase(Transaction) runTransaction:event:]::$_1, std::__1::allocator<-[WCTDatabase(Transaction) runTransaction:event:]::$_1>, bool (WCDB::Error&)>::operator()(WCDB::Error&) + [WCTDatabase+Transaction.mm : 49] 
4448   WCDB                                0x000000010afd0c78 WCDB::CoreBase::runTransaction(std::__1::function<bool (WCDB::Error&)>, std::__1::function<void (WCDB::CoreBase::TransactionEventType)>, WCDB::Error&) + [core_base.cpp : 103] 
4459   WCDB                                0x000000010aff81b4 -[WCTDatabase(Transaction) runTransaction:event:] + [WCTDatabase+Transaction.mm : 0] 
44610  WCDB                                0x000000010aff80b8 -[WCTDatabase(Transaction) runTransaction:] + [WCTDatabase+Transaction.mm : 36]

**Comment by cqwicqw** [comment]
Please give more detail of crash report.

**Comment by lin-it** [comment]
me too

**Comment by Qiuwen-chen** [comment]
Please use WCDB 2.0 and see if there is still this problem.
