### ISSUE TITLE
Library evolution报错

### ISSUE THREAD

**Issue by tomatobin** [Tencent/wcdb#861]
### The language of WCDB

Swift 

### The version of WCDB

> v1.0.8.2

### The platform of WCDB

> iOS

### The installation of WCDB

> Pods

### What's the issue?
开启BUILD_LIBRARY_FOR_DISTRIBUTION = YES，低版本Xcode（eg.Xcode13.2.1) 编译成二进制Framework后，在高版本Xcode（eg. Xcode13.3.1）集成，编译报错。

```
Conditional conformance of type 'Array<Element>' to protocol 'ColumnEncodable' does not imply conformance to inherited protocol 'ColumnCodableBase'
```

### Solution

Array、Dictionary、Set的ColumnCodable扩展修改为ColumnCodableBase,ColumnEncodable,ColumnDecodable，eg：
```
extension Array: ColumnCodableBase,ColumnEncodable,ColumnDecodable
```

**Comment by cqwicqw** [comment]
This problem will be fixed in the new version
