### ISSUE TITLE
propertyName:[String : Any]提示does not conform to protocol 'Decodable'

### ISSUE THREAD

**Issue by luyanisme** [Tencent/wcdb#863]
class NodeInfoEntity: ColumnJSONCodable, HandyJSON{
    
    var type: NodeInfoType?;
    var elementValues: [String : Any]?;
    
    required init() {
        
    }
}
会报错Type 'NodeInfoEntity' does not conform to protocol 'Decodable'
请问下这个Any怎么处理，我的业务里面需要动态的增加字段，而且每个字段里的类型有可能是不一样的

**Comment by yuanliangYL** [comment]
> 
我也遇到同样的问题，请问一下你这边有处理方案了吗？

**Comment by cqwicqw** [comment]
Custom types must implement the ColumnCodable protocol.
