### ISSUE TITLE
 WCTExpr每次二元操作之后都会自动加个括号，怎么搞？

### ISSUE THREAD

**Issue by CodeSlaveZhang** [Tencent/wcdb#864]
### The language of WCDB

Objective-C

### The version of WCDB

v1.0.5

### The platform of WCDB

iOS, macOS

### The installation of WCDB

 Git clone

### What's the issue?

 WCTExpr每次二元操作之后都会自动加个括号，怎么搞？

`
WCTCondition condition = KIMMessageDBObj.msg_client_id.isNotNull();

    if (option.fromMessage) {

        condition = condition && KIMMessageDBObj.convo_seq_id<option.fromMessage.seqInSession;

    }

    if (option.toMessage) {

        condition = condition && KIMMessageDBObj.convo_seq_id>option.toMessage.seqInSession;

    }

    if (option.atType!=KIMMessageAtTypeUnknown) {

        condition = condition && KIMMessageDBObj.at_type==option.atType;

    }

    if (option.messageTypes.count) {

        condition = condition &&KIMMessageDBObj.msg_type.in(option.messageTypes);

    }
`

这样每次二元操作都会自动带个括号

**Comment by cqwicqw** [comment]
The new version of WCDB will simplify the use of brackets, please wait.
