### ISSUE TITLE
swift 模糊查询 查不到数据

### ISSUE THREAD

**Issue by Xiaxiangjing** [Tencent/wcdb#866]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
加上这个like条件后：SYTagSQLTable.Properties.name.like(text)
却无法查询到数据，是哪里出了问题？

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by AllenYL** [comment]
不要写 like(keywords)， 要模仿sqlite语句写成: like("%keywords%")就可以了
