### ISSUE TITLE
VirtualTable set primary key invalid 虚拟表设置主键

### ISSUE THREAD

**Issue by AllenYL** [Tencent/wcdb#867]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
swift

### The version of WCDB

> e.g. v1.0.8.2

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

The virtual table (XXXXTableName) data model I created tried to set "mid" as the primary key constraint, but it was invalid，I want to use "mid" as the primary key so that the inserted data does not duplicate, how do I set it?

I see that the table inside DB(XXXXTableName_content) actually uses the private property "docid" as the primary key.

![截屏2022-08-03 17 21 17](https://user-images.githubusercontent.com/16030436/182573188-ad6885c1-9a17-46ba-ac6c-45c6977a7f20.png)

<img width="728" alt="截屏2022-08-03 17 13 48" src="https://user-images.githubusercontent.com/16030436/182571870-e2981b24-fcf0-4d86-80a6-07571a9e86d5.png">

<img width="752" alt="截屏2022-08-03 17 13 27" src="https://user-images.githubusercontent.com/16030436/182571832-49e66829-e189-4349-938c-e7e89d664fa4.png">

**Comment by cqwicqw** [comment]
SQLite does not support adding column constraints to the columns of the fts table. Please see https://www.sqlite.org/draft/fts3.html.
