### ISSUE TITLE
微信删了好友后保留数据库怎么用这个库恢复聊天记录

### ISSUE THREAD

**Issue by xygituser** [Tencent/wcdb#870]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

据说删除的信息会保留在FTS5IndexMicroMsg_encrypt.db和FTS5IndexMicroMsg_encrypt.db-journal这里，FTS5IndexMicroMsg_encrypt.db解密后没看懂里面的数据，也没找到想要的，怀疑是不是在这个FTS5IndexMicroMsg_encrypt.db-journal里面，但不知道怎么解密，看了微信的java层大概是调用这个库的，求解

**Comment by cqwicqw** [comment]
The fts database does not have complete information to restore chat records
