### ISSUE TITLE
wcdb 不支持直接执行sql，如何实现很复杂的计算sql？

### ISSUE THREAD

**Issue by ijeffery3** [Tencent/wcdb#875]
例如这种sql ：

SELECT a.*FROM(SELECT S1.inspectTemplateType AS inspectTemplateType,count(DISTINCT S2.questionOrderId)AS questionNum,S1.busCheckItemId AS busCheckItemId,S1.busCheckItemName AS busCheckItemName,S1.deservedScoreFlag AS deservedScoreFlag,S1.parentCheckItemId AS parentCheckItemId,S1.itemDirectoryFlag AS itemDirectoryFlag,S1.itemSort,S3.itemInvolveFlag AS itemInvolveFlag,CASE WHEN S5.busCheckItemId IS NOT NULL THEN 1 ELSE 0 END AS checkQualifiedFlag,S5.excellenceFlag AS excellenceFlag,CASE WHEN S3.busCheckItemId IS NOT NULL OR S5.busCheckItemId IS NOT NULL OR S2.busCheckItemId IS NOT NULL THEN 1 ELSE 0 END AS checkFlag,CASE WHEN S3.itemInvolveFlag=1 THEN NULL WHEN S1.deservedScoreFlag=1 AND S5.busCheckItemId IS NULL AND S2.busCheckItemId IS NULL THEN NULL WHEN S1.deservedScoreFlag=1 AND S2.busCheckItemId IS NOT NULL THEN S1.itemDeservedScore WHEN S1.deservedScoreFlag=0 THEN S1.itemDeservedScore ELSE NULL END AS itemDeservedScore,CASE WHEN CASE WHEN S5.busCheckItemId IS NOT NULL THEN 0 WHEN S1.checkType=1246531 THEN(SELECT S13.levelScore FROM HGCJTXJInspectScoreLevelTable S13 WHERE S13.groupInspectTemplateId=S1.groupInspectTemplateId AND((S1.levelScoreSource=2 AND S13.busCheckItemId=S1.busCheckItemId)or(S1.levelScoreSource=1 AND S13.busCheckItemId==\"\"))AND S13.levelMinNum<(SELECT count(1)FROM HGCJTXJQuestionTable S11 WHERE S11.busCheckItemId=S1.busCheckItemId AND S11.busProjectId=S1.busProjectId AND S11.orderProgressCode!=1037535)ORDER BY S13.levelMinNum DESC LIMIT 1)WHEN S1.checkType=1246532 THEN(SELECT S13.levelScore FROM HGCJTXJInspectScoreLevelTable S13 WHERE S13.groupInspectTemplateId=S1.groupInspectTemplateId AND S13.busProjectId=S1.busProjectId AND((S1.levelScoreSource=2 AND S13.busCheckItemId=S1.busCheckItemId)or(S1.levelScoreSource=1 AND S13.busCheckItemId==\"\"))AND S13.levelMinNum<(SELECT sum(S11.questionNum)FROM HGCJTXJQuestionTable S11 WHERE S11.busCheckItemId=S1.busCheckItemId AND S11.busProjectId=S1.busProjectId AND S11.orderProgressCode!=1037535)ORDER BY S13.levelMinNum DESC LIMIT 1)WHEN S1.checkType=1246533 THEN(SELECT sum(S13.levelScore)FROM HGCJTXJQuestionTable S11 LEFT JOIN HGCJTXJInspectScoreLevelTable S13 ON S11.groupInspectScoreLevelId=S13.inspectScoreLevelId AND S11.busProjectId=S13.busProjectId WHERE S11.busCheckItemId=S1.busCheckItemId AND S11.busProjectId=S1.busProjectId AND S11.orderProgressCode!=1037535)ELSE NULL END>itemDeservedScore THEN itemDeservedScore ELSE CASE WHEN S5.busCheckItemId IS NOT NULL THEN 0 WHEN S1.checkType=1246531 THEN(SELECT S13.levelScore FROM HGCJTXJInspectScoreLevelTable S13 WHERE S13.groupInspectTemplateId=S1.groupInspectTemplateId AND((S1.levelScoreSource=2 AND S13.busCheckItemId=S1.busCheckItemId)or(S1.levelScoreSource=1 AND S13.busCheckItemId==\"\"))AND S13.levelMinNum<(SELECT count(1)FROM HGCJTXJQuestionTable S11 WHERE S11.busCheckItemId=S1.busCheckItemId AND S11.busProjectId=S1.busProjectId AND S11.orderProgressCode!=1037535)ORDER BY S13.levelMinNum DESC LIMIT 1)WHEN S1.checkType=1246532 THEN(SELECT S13.levelScore FROM HGCJTXJInspectScoreLevelTable S13 WHERE S13.groupInspectTemplateId=S1.groupInspectTemplateId AND S13.busProjectId=S1.busProjectId AND((S1.levelScoreSource=2 AND S13.busCheckItemId=S1.busCheckItemId)or(S1.levelScoreSource=1 AND S13.busCheckItemId==\"\"))AND S13.levelMinNum<(SELECT sum(S11.questionNum)FROM HGCJTXJQuestionTable S11 WHERE S11.busCheckItemId=S1.busCheckItemId AND S11.busProjectId=S1.busProjectId AND S11.orderProgressCode!=1037535)ORDER BY S13.levelMinNum DESC LIMIT 1)WHEN S1.checkType=1246533 THEN(SELECT sum(S13.levelScore)FROM HGCJTXJQuestionTable S11 LEFT JOIN HGCJTXJInspectScoreLevelTable S13 ON S11.groupInspectScoreLevelId=S13.inspectScoreLevelId AND S11.busProjectId=S13.busProjectId WHERE S11.busCheckItemId=S1.busCheckItemId AND S11.busProjectId=S1.busProjectId AND S11.orderProgressCode!=1037535)ELSE NULL END END AS deductionScore,0.0 AS directoryScoringRate FROM HGCJTXJCheckItemTable S1 LEFT JOIN HGCJTXJQuestionTable S2 ON S1.busCheckItemId=S2.busCheckItemId AND S2.busProjectId=S1.busProjectId AND S2.orderProgressCode!=1037535 LEFT JOIN HGCJTXJCheckItemResultTable S3 ON S1.busCheckItemId=S3.busCheckItemId AND S1.busProjectId=S3.busProjectId LEFT JOIN HGCJTXJCheckQualifiedTable S5 ON S1.busCheckItemId=S5.busCheckItemId AND S5.busProjectId=S1.busProjectId WHERE S1.groupInspectTemplateId=%@ AND S1.itemDirectoryFlag=0 AND S1.busProjectId=%@ GROUP BY S1.busCheckItemId UNION ALL SELECT NULL AS inspectTemplateType,NULL AS questionNum,S21.busCheckItemId AS busCheckItemId,S21.busCheckItemName AS busCheckItemName,0 AS deservedScoreFlag,NULL AS parentCheckItemId,1 AS itemDirectoryFlag,NULL AS itemSort,S24.itemInvolveFlag AS itemInvolveFlag,0 AS checkQualifiedFlag,0 AS excellenceFlag,0 AS checkFlag,NULL AS deductionScore,NULL AS itemDeservedScore,(1-sum((SELECT CASE WHEN CASE WHEN S5.busCheckItemId IS NOT NULL THEN 0 WHEN S3.busCheckItemId IS NOT NULL AND S3.questionNum=0 THEN 0 WHEN S1.checkType=1246531 THEN(SELECT S13.levelScore FROM HGCJTXJInspectScoreLevelTable S13 WHERE S13.groupInspectTemplateId=S1.groupInspectTemplateId AND S13.busProjectId=S1.busProjectId AND((S1.levelScoreSource=2 AND S13.busCheckItemId=S1.busCheckItemId)or(S1.levelScoreSource=1 AND S13.busCheckItemId==\"\"))AND S13.levelMinNum<(SELECT count(1)FROM HGCJTXJQuestionTable S11 WHERE S11.busCheckItemId=S1.busCheckItemId AND S11.busProjectId=S21.busProjectId AND S11.orderProgressCode!=1037535)ORDER BY S13.levelMinNum DESC LIMIT 1)WHEN S1.checkType=1246532 THEN(SELECT S13.levelScore FROM HGCJTXJInspectScoreLevelTable S13 WHERE S13.groupInspectTemplateId=S1.groupInspectTemplateId AND((S1.levelScoreSource=2 AND S13.busCheckItemId=S1.busCheckItemId)or(S1.levelScoreSource=1 AND S13.busCheckItemId==\"\"))AND S13.levelMinNum<(SELECT sum(S11.questionNum)FROM HGCJTXJQuestionTable S11 WHERE S11.busCheckItemId=S1.busCheckItemId AND S11.busProjectId=S21.busProjectId AND S11.orderProgressCode!=1037535)ORDER BY S13.levelMinNum DESC LIMIT 1)WHEN S1.checkType=1246533 THEN(SELECT sum(S13.levelScore)FROM HGCJTXJQuestionTable S11 LEFT JOIN HGCJTXJInspectScoreLevelTable S13 ON S11.groupInspectScoreLevelId=S13.inspectScoreLevelId AND S11.busProjectId=S13.busProjectId WHERE S11.busCheckItemId=S1.busCheckItemId AND S11.busProjectId=S21.busProjectId AND S11.orderProgressCode!=1037535)ELSE NULL END>CASE WHEN S3.itemInvolveFlag=1 THEN NULL WHEN S1.deservedScoreFlag=1 AND S5.busCheckItemId IS NULL AND S2.busCheckItemId IS NULL THEN NULL WHEN S1.deservedScoreFlag=1 AND S2.busCheckItemId IS NOT NULL THEN S1.itemDeservedScore WHEN S1.deservedScoreFlag=0 THEN S1.itemDeservedScore ELSE NULL END THEN CASE WHEN S3.itemInvolveFlag=1 THEN NULL WHEN S1.deservedScoreFlag=1 AND S5.busCheckItemId IS NULL AND S2.busCheckItemId IS NULL THEN NULL WHEN S1.deservedScoreFlag=1 AND S2.busCheckItemId IS NOT NULL THEN S1.itemDeservedScore WHEN S1.deservedScoreFlag=0 THEN S1.itemDeservedScore ELSE NULL END ELSE CASE WHEN S5.busCheckItemId IS NOT NULL THEN 0 WHEN S3.busCheckItemId IS NOT NULL AND S3.questionNum=0 THEN 0 WHEN S1.checkType=1246531 THEN(SELECT S13.levelScore FROM HGCJTXJInspectScoreLevelTable S13 WHERE S13.groupInspectTemplateId=S1.groupInspectTemplateId AND S13.busProjectId=S1.busProjectId ......

**Comment by cqwicqw** [comment]
All SQL statements supported by sqlite can be translated into WCDB Winq statements and executed with -[WCTInterface exec:] or -[WCTInterface prepare:]

**Comment by wulw1990** [comment]
@Qiuwen-chen 可以给帮忙看个具体的例子吗，我用的swift，需要执行这样的SQL，如何用statements实现呢：
//                    CREATE TEMPORARY VIEW UniqueSample AS
//                    SELECT \"from\", \"to\", episode_start, document
//                    FROM (
//                      SELECT \"from\", \"to\", episode_start, document,
//                             ROW_NUMBER() OVER (PARTITION BY episode_start) as rn
//                      FROM \(intervalTableName)
//                    )
//                    ORDER BY episode_start DESC
//                    WHERE rn = 1;

**Comment by ijeffery3** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Qiuwen-chen** [comment]
> 

This wiki might help you https://github.com/Tencent/wcdb/wiki/Swift-%e8%af%ad%e8%a8%80%e9%9b%86%e6%88%90%e6%9f%a5%e8%af%a2
