### ISSUE TITLE
怎样消除这个警告？

### ISSUE THREAD

**Issue by ygf-git** [Tencent/wcdb#877]
### The language of WCDB

> e.g. Swift

### The version of WCDB

> e.g. WCDBSwift (1.0.2)

### The platform of WCDB

> e.g. iOS, macOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

Non-final class ' ' cannot safely conform to protocol 'TableDecodable', which requires that 'Self.CodingKeys.Root' is exactly equal to 'Self'; this is an error in Swift 6

怎样消除这个警告？

**Comment by tomatobin** [comment]
final class xxxx {
}
