### ISSUE TITLE
引入自己编译的sqlite会有影响么

### ISSUE THREAD

**Issue by Hoikiiz** [Tencent/wcdb#879]
### The language of WCDB
Objective-C

### The platform of WCDB
iOS

### What's the issue?
咨询一下，如果我在工程中引入了自己编译的 sqlite3，WCDB会自动使用么，如果是的话，我需要追加哪些编译参数来避免异常呢

**Comment by devSC** [comment]
Swift 下会报错

**Comment by cqwicqw** [comment]
The sqlite used by WCDB has modified the source code, so the public version of sqlite cannot be used.
