### ISSUE TITLE
Android 1.0.2 onSQLExecuted打出的time都是负数

### ISSUE THREAD

**Issue by edongyu** [Tencent/wcdb#88]
database使用setTraceCallback设置回调， onSQLExecuted 回调的参数中time都是负数， 而且执行一条语句会回调两次， 是需要两次相减自己算调用时间么！

```
07-07 10:45:43.165 I/DBTrace (  466):  (466) [onSQLExecuted:44]onSQLExecuted : select count(*) from m where readType=?, time : -1499395543164
07-07 10:45:43.168 I/DBTrace (  466):  (466) [onSQLExecuted:44]onSQLExecuted : select count(*) from m where readType=?, time : -1499395543166
```

**Comment by John-He-928** [comment]
time就是耗时本身，不需要减，我看看是不是bug

**Comment by John-He-928** [comment]
负数是修改出来的问题，重构将回调函数放出synchronized block避免死锁时引入，没有取到结束时间，所以负数是 0 - 开始时间。

两次回调，前一次是prepare，后一次是执行，如果是之前执行过一样的SQL，在缓存里有的话就不会prepare，回调的时候不加区分好像是不太好，这边顺便改一改。

**Comment by edongyu** [comment]
感谢详细的回复！

**Comment by John-He-928** [comment]
负数和重复调用问题已经修正，在最新master分支
