### ISSUE TITLE
WCDB 使用非 option 的值会 Crash，would not be decoded, please make it optional.

### ISSUE THREAD

**Issue by chensifang** [Tencent/wcdb#880]
### The language of WCDB

> Swift

### The version of WCDB

> e.g. v1.0.8.2

### The platform of WCDB

> e.g. macOS 

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?
Model 中使用非 option 值，在 getObjects 的时候会 Crash

> Post the outputs or screenshots for errors.
> 
这是我的代码
![image](https://user-images.githubusercontent.com/10810457/199242365-5dbd8673-0239-480f-8d41-dfb796fe0b3e.png)
这是 Crash 的地方
![image](https://user-images.githubusercontent.com/10810457/199242447-3995cd46-fc94-4b61-9c0f-ba55c40f36a0.png)

> Explain what you want by example or code **in English**.

@RingoD  能帮忙解答一下吗，非常感谢~

**Comment by aioser** [comment]
another program for kpi。 换 realm 吧

**Comment by Chouee** [comment]
遇到相同的问题。iOS12系统，其他系统正常。改成option后，虽然不会报错了，但是enum会decode失败。是不是我忽略了些什么？

**Comment by Qiuwen-chen** [comment]
Since the iOS 12 simulator is not available for download in xcode, I cannot reproduce this issue. Please use the new system, or use the optional value.
