### ISSUE TITLE
新增字段 查询失败 

### ISSUE THREAD

**Issue by sleepwalkercode** [Tencent/wcdb#881]
### The language of WCDB

Objective-C

### The version of WCDB

 WCDB (1.0.7.5)

### The platform of WCDB

macOS

### The installation of WCDB

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

新增了四个字段 目前已经有19个字段了 但是新增的字段没有加上 查看了生成的sqllite文件 字段有两个加进去了 有两个没有加上 不知道什么原因。但是createTableAndIndexesOfName执行反馈为YES
**
/// CPDataItem.h
@property (nonatomic,copy) NSString *categoryId;
@property (nonatomic,copy) NSNumber *imageType;
@property (nonatomic,copy) NSString *imageMd5;
@property (nonatomic,copy) NSString *applicationIconMd5;

/// CPDataItem.m
WCDB_SYNTHESIZE(CPDataItem, applicationIconMd5)
WCDB_SYNTHESIZE(CPDataItem, imageType)
WCDB_SYNTHESIZE(CPDataItem, imageMd5)
WCDB_SYNTHESIZE(CPDataItem, categoryId)

/// CPDataItem+WCTTableCoding
WCDB_PROPERTY(imageType)
WCDB_PROPERTY(imageMd5)
WCDB_PROPERTY(categoryId)
WCDB_PROPERTY(applicationIconMd5)

///database
- (BOOL)creatCategoryDataWithName
{
    return [self.database createTableAndIndexesOfName:PasboardCategoryTableName withClass:CPCategoryItem.class];
    // 数据库加密
    if ([self.database canOpen]) {
        // 先判断表是不是已经存在
        return [self.database createTableAndIndexesOfName:PasboardCategoryTableName withClass:CPCategoryItem.class];
//        if ([self.database isOpened]) {
//
//            if ([self.database isTableExists:PasboardCategoryTableName]) {
//                NSLog(@"分类表已经存在");
//                return NO;
//            }else
//                NSLog(@"分类表不存在");
//                return [self.database createTableAndIndexesOfName:PasboardCategoryTableName withClass:CPCategoryItem.class];
//        }
    }
    return NO;
}
/// 创建表
- (BOOL)creatDataBaseWithName:(NSString *)tableName
{
    return [self.database createTableAndIndexesOfName:tableName withClass:CPDataItem.class];
    // 数据库加密
    if ([self.database canOpen]) {
        // 先判断表是不是已经存在
        return [self.database createTableAndIndexesOfName
![截屏2022-11-18 11 36 52](https://user-images.githubusercontent.com/116727055/202611371-4c5218f1-67db-46e5-b854-0d80f89f519b.png)
:tableName withClass:CPDataItem.class];
//        if ([self.database isOpened]) {
//
//            if ([self.database isTableExists:tableName]) {
//                return NO;
//            }else
//                return [self.database createTableAndIndexesOfName:tableName withClass:CPDataItem.class];
//        }
    }
    return NO;
}
**
创建成功 然后执行查询报错
[WCDB][ERROR]Code:11, Type:SQLite, Tag:0, Op:5, ExtCode:11, Msg:database disk image is malformed, SQL:SELECT COUNT(*) FROM PastedDataTable LIMIT 1, Path:/Users/****/***.sqlite

**Comment by sleepwalkercode** [comment]
请问这是什么原因造成的？

**Comment by cqwicqw** [comment]
As the error message says, the database is corrupted and it can not update data or add new columns. You need to repair the database or delete the database.
