### ISSUE TITLE
请问QQ群都满了，怎么加入技术交流群呢？

### ISSUE THREAD

**Issue by camoufleur** [Tencent/wcdb#883]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by yjtacx** [comment]
同问呀，我反馈的一个问题，快3周了，没人回复，😌

**Comment by Qiuwen-chen** [comment]
You can post your problems here.
