### ISSUE TITLE
Thread 52: EXC_BAD_ACCESS (code=1, address=0xae2a1b980)

### ISSUE THREAD

**Issue by JW-chenjingwei** [Tencent/wcdb#886]
### The language of WCDB

> Objective-C

### The version of WCDB

> "1.0.7.5"

### The platform of WCDB

 iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

I had a similar error in debugging：
![image](https://user-images.githubusercontent.com/19601566/211238504-5559dfcb-7ff6-4a86-bfbd-2d008fdadad8.png)

**Comment by Qiuwen-chen** [comment]
This problem will be fixed in the next version, please wait.
