### ISSUE TITLE
"use_modular_headers!"方式同时引入WCDB,WCDB.swift，出现报错

### ISSUE THREAD

**Issue by NicChui** [Tencent/wcdb#888]
### The language of WCDB

> Objective-C, Swift 

### The version of WCDB

> v1.1.0

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?
<img width="1044" alt="Xnip2023-01-12_10-44-54" src="https://user-images.githubusercontent.com/9591634/211963603-309ca361-13cd-4e60-80cb-6bdda6bc44ec.png">
> 
> 
> podfile 使用 "use_modular_headers!"方式同时引入WCDB,WCDB.swift，出现报错

**Comment by Qiuwen-chen** [comment]
We will provide a better way to integrate WCDB and WCDB.Swift into one project in the next version.
