### ISSUE TITLE
子线程创建虚拟表崩溃

### ISSUE THREAD

**Issue by AllenYL** [Tencent/wcdb#889]
### The language of WCDB
Swift

### The version of WCDB
1.0.8.2

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?
子线程创建虚拟表的时候偶现崩溃。

<img width="842" alt="截屏2023-01-30 12 13 53" src="https://user-images.githubusercontent.com/16030436/215386492-e5cb6692-ce59-4cc5-8499-6c8ebc76b96b.png">

<img width="1137" alt="截屏2023-01-30 11 59 54" src="https://user-images.githubusercontent.com/16030436/215386520-e4471956-5732-492b-93a3-4da1725e8fbb.png">

<img width="935" alt="截屏2023-01-30 12 00 14" src="https://user-images.githubusercontent.com/16030436/215386527-7054b3f7-b8e2-4de1-921d-989a06d3089c.png">

**Comment by Qiuwen-chen** [comment]
We will use a better implementation in the next version.
