### ISSUE TITLE
只要一切换窗口的根控制器，数据库就损坏！

### ISSUE THREAD

**Issue by mdjwanghong** [Tencent/wcdb#89]
我的代码如下：

` WCTDatabase *db = [[WCTDatabase alloc] initWithPath:[WCDBHelper getDBPathDefault]];
    [db close:^{
        [db removeFilesWithError:nil]; }];
    
    BOOL ret1 = [db createTableAndIndexesOfName:NSStringFromClass(Login_user.class) withClass:Login_user.class];
    
    [db insertOrReplaceObjects:login.user
                          into:NSStringFromClass(Login_user.class)];
    
    BOOL ret2 = [db createTableAndIndexesOfName:NSStringFromClass(User_to_dep.class) withClass:User_to_dep.class];
    
    [db insertOrReplaceObjects:login.utd
                          into:NSStringFromClass(User_to_dep.class)];
    
    BOOL ret3 = [db createTableAndIndexesOfName:NSStringFromClass(Department.class) withClass:Department.class];
    
    [db insertOrReplaceObjects:login.dep
                          into:NSStringFromClass(Department.class)];
    
    BOOL ret4 = [db createTableAndIndexesOfName:NSStringFromClass(User_device.class) withClass:User_device.class];
    
    [db insertOrReplaceObjects:login.user_device
                          into:NSStringFromClass(User_device.class)];

   // 切换窗口的根控制器
//    UIWindow *window = [UIApplication sharedApplication].keyWindow;
//    [window switchRootViewController];

`

上述代码运行没有问题，数据存储都很正常，但是只要一切换窗口的要控制器

 `   // 切换窗口的根控制器
  UIWindow *window = [UIApplication sharedApplication].keyWindow;
 [window switchRootViewController];`

# 数据库中的表就全部消失，数据全无，请问是什么原因？

**Comment by RingoD** [comment]
你的代码第一句就删了数据库呀-removeFilesWithError:

**Comment by mdjwanghong** [comment]
[db close:^{[db removeFilesWithError:nil]; }];

这段代码删除，也是不行，只要写入数据库后再切换窗口，则数据库里面的表及数据全部消失！

**Comment by RingoD** [comment]
debug一下传入的路径，并看一下创建的文件？

**Comment by mdjwanghong** [comment]
解决了，谢谢！
