### ISSUE TITLE
near "OFFSET": syntax error

### ISSUE THREAD

**Issue by jozdee** [Tencent/wcdb#890]
### The language of WCDB

Objective-C

### The version of WCDB

 最新版本

### The platform of WCDB

 iOS

### The installation of WCDB

Cocoapods

### What's the issue?

执行：[_db deleteObjectsFromTable:tableName offset:offset];

报错：Code:1, Type:SQLite, Msg:near "OFFSET": syntax error, Tag:0, ExtCode:1, SQL:DELETE FROM search1 OFFSET 1000,

执行：[_db updateRowsInTable:tableName onProperty:property withValue:value offset:offset];
报错：Code:1, Type:SQLite, Msg:near "OFFSET": syntax error, Tag:0, ExtCode:1, SQL:UPDATE search0 SET name=? OFFSET 999,

应该是用一个原因造成的，查了相关历史issue，只找到一个也没看如何解决，有看到到回答下呀？

**Comment by Qiuwen-chen** [comment]
Got it. We will fix it in the next version.
