### ISSUE TITLE
数据备份与恢复测试遇到问题

### ISSUE THREAD

**Issue by jozdee** [Tencent/wcdb#891]
### The language of WCDB

Objective-C

### The version of WCDB

最新

### The platform of WCDB

iOS

### The installation of WCDB

 Cocoapods

### What's the issue?
调用- (BOOL)recoverFromPath:(NSString *)corruptedDBPath withPageSize:(const int)pageSize backupCipher:(NSData *)backupCipher databaseCipher:(NSData *)databaseCipher;
出现如下错误，是否一定需要表被损坏才能正常恢复数据呢，测试的时候如何模拟场景进行测试呢？

[SQLITERK_OK] Begin parsing sqlite_master...
[SQLITERK_OK] Parsing B-tree -> [root: 1, name: sqlite_master, type: sqlite_master]
[SQLITERK_DAMAGED] Failed to parse page 1.
[SQLITERK_DAMAGED] Failed to parse sqlite_master.
[SQLITERK_OK] >>> CREATE TABLE test(name TEXT,avatarUrl TEXT,content TEXT,age INTEGER,msgId TEXT PRIMARY KEY)
2023-02-06 18:32:11.595739+0800 NNSIMTest[16074:450406] [WCDB错误信息]：Code:1, Type:SQLiteGlobal, Msg:table test already exists
[SQLITERK_CANTOPEN] EXEC FAILED: table test already exists [SQL: CREATE TABLE test(name TEXT,avatarUrl TEXT,content TEXT,age INTEGER,msgId TEXT PRIMARY KEY)]
[SQLITERK_OK] [test] -> pgno: 2
[SQLITERK_DAMAGED] No rows can be successfully output. [failed: 1]
2023-02-06 18:32:11.596034+0800 NNSIMTest[16074:450406] [WCDB错误信息]：Code:6, Type:Repair, Op:2,

**Comment by DSPerson** [comment]
me to...

**Comment by Qiuwen-chen** [comment]
You need to backup the database first, then randomly corrupt one or two data page of the database, and then run database recovery. After that, you can check whether the data is completely restored. If the data is completely restored, these error messages can be ignored, and we will provide a better data backup and repair method in the next version.
