### ISSUE TITLE
The storage path cannot read data normally under the AppGroup

### ISSUE THREAD

**Issue by strangerBen** [Tencent/wcdb#893]
### The language of WCDB
Objective-C

### The version of WCDB
v1.0.8.2

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?
After uninstalling and reinstalling the app, start it for the first time and set the database storage path in AppGroup. After storing the data, it is found that it cannot be read normally in the Siri Extension. After killing the app, it can be read normally in Siri Extension after starting the app again.

**Comment by Qiuwen-chen** [comment]
Please upgrade to the latest version of WCDB and try again.
