### ISSUE TITLE
com.tencent.wcdb.database.SQLiteDiskIOException

### ISSUE THREAD

**Issue by yjtacx** [Tencent/wcdb#894]
### The language of WCDB

> Java 

### The version of WCDB

> v1.0.8

### The platform of WCDB

> Android

### The installation of WCDB

> AAR Package

### What's the issue?
WCDB.AsyncCheckpointer
com.tencent.wcdb.database.SQLiteDiskIOException
disk I/O error (code 778, errno 29): Cannot checkpoint the WAL database
com.tencent.wcdb.database.SQLiteConnection.nativeWalCheckpoint(Native Method)
com.tencent.wcdb.database.SQLiteConnection.walCheckpoint(SQLiteConnection.java:976)
com.tencent.wcdb.database.SQLiteSession.walCheckpoint(SQLiteSession.java:802)
com.tencent.wcdb.database.SQLiteDatabase.walCheckpoint(SQLiteDatabase.java:1925)
com.tencent.wcdb.database.SQLiteAsyncCheckpointer.handleMessage(SQLiteAsyncCheckpointer.java:118)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loop(Looper.java:219)
android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by yjtacx** [comment]
@LiLejia @hzlzh @qiaohaijun 哪位大佬回复下呀！

**Comment by Qiuwen-chen** [comment]
As said in the log, it is caused by disk IO error, not WCDB logic problem

**Comment by yjtacx** [comment]
这个发生在wcdb的框架代码内，是不是wcdb做个容错处理呀

**Comment by Qiuwen-chen** [comment]
Unhandleable
