### ISSUE TITLE
更新数据时，只要已操作数据就卡死不论读和写，什么原因

### ISSUE THREAD

**Issue by myprogramminglife** [Tencent/wcdb#896]
更新数据时，只要已操作数据就卡死不论读和写，什么原因

**Comment by viihua** [comment]
哈哈 那应该跟我是一个问题 [https://github.com/Tencent/wcdb/issues/887](url)

**Comment by viihua** [comment]
https://github.com/Tencent/wcdb/issues/887

**Comment by viihua** [comment]
应该是一个问题，但人说他那没什么问题。回退吧。 https://github.com/Tencent/wcdb/issues/887

**Comment by Qiuwen-chen** [comment]
Please upgrade to the latest version of WCDB, this problem is solved.
