### ISSUE TITLE
WCDB的多线程操作应该怎么设计？

### ISSUE THREAD

**Issue by qq20539350** [Tencent/wcdb#90]
Transaction 事务款线程的例子打不开

**Comment by RingoD** [comment]
WCDB绝大部分接口都支持多线程同时调用。不需要特别设计

**Comment by qq20539350** [comment]
文档不是说只有 Transaction 是线程安全的吗？ WCTDatabase 不是线程安全的

**Comment by RingoD** [comment]
所有便捷接口都是线程安全的。在每个类的声明处也有注释指明thread-safe或not thread-safe。

> WCTDatabase 不是线程安全的

这个在哪个文档里说的？

**Comment by qq20539350** [comment]
WCTDatabase不支持跨线程事务。事务内的操作必须在同一个线程运行完。可以通过两种方式运行事务：  记错了

**Comment by RingoD** [comment]
不支持跨线程事务和线程不安全是两回事噢。

跨线程事务是指，一个事务在A线程开始，在B线程操作，在C线程完成。这种类似的操作。

线程安全是指接口可以在任意线程调用。绝大部分接口都是可以在任意线程调用的。
