### ISSUE TITLE
[WCDB] Error Occur: Code:1, Type:SQLiteGlobal, Msg:no such function: json_extract

### ISSUE THREAD

**Issue by lin-it** [Tencent/wcdb#902]
什么情况？

sqllte3不是支持的吗 ？

    WCTExprList exprList = {xxx.xxx, "$.xxx"};
    WCTExpr substrExpr = WCTExpr::Function(@"json_extract", exprList);

**Comment by Qiuwen-chen** [comment]
Please update to the latest version of WCDB and try again.
