### ISSUE TITLE
引入WCDB后，原有sqlite3数据库执行报错 SQLITE_MISUSE

### ISSUE THREAD

**Issue by TommyChangz** [Tencent/wcdb#905]
### The language of WCDB
 Objective-C

### The version of WCDB
 v1.1.0

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods,

### What's the issue?

1. 由于项目里有使用基于系统sqlite3封装的数据库，在引入WCDB后，原有的数据库执行sql时报错【sqlite3_exec()函数】报错，错误code为SQLITE_MISUSE  21   /* Library used incorrectly */。
2. 不知道是不是因为WCDB改写的sqlite源码影响到了系统的sqlite3？但项目是可以正常编译运行的。

**Comment by Qiuwen-chen** [comment]
WCDB is configured with SQLITE_ENABLE_API_ARMOR. It will activate extra code that attempts to detect misuse of the SQLite API

**Comment by jozdee** [comment]
YYKit中的YYKVStorage，崩溃在sqlite3_exec调用上，请问如何解决？

- (BOOL)_dbExecute:(NSString *)sql {
    if (sql.length == 0) return NO;
    if (![self _dbCheck]) return NO;
    
    char *error = NULL;
    int result = sqlite3_exec(_db, sql.UTF8String, NULL, NULL, &error);
    if (error) {
        if (_errorLogsEnabled) NSLog(@"%s line:%d sqlite exec error (%d): %s", __FUNCTION__, __LINE__, result, error);
        sqlite3_free(error);
    }
    
    return result == SQLITE_OK;
}
