### ISSUE TITLE
UI线程卡死，出现死锁，貌似和YYCache冲突了，也是挺偶现的，但是一直操作也一定能复现出来

### ISSUE THREAD

**Issue by BIBiBI12** [Tencent/wcdb#906]
### The language of WCDB

Objective-C

### The version of WCDB

 - WCDB (1.1.0):
    - SQLiteRepairKit (~> 1.3.0)
    - WCDBOptimizedSQLCipher (~> 1.3.0)
  - WCDBOptimizedSQLCipher (1.3.0)

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

![截屏2023-03-27 10 26 59](https://user-images.githubusercontent.com/20101580/227826027-54fc6b8f-7daa-4f8f-8bfe-27ac8acd8a5a.png)

貌似YYCache调用系统的sqlite3Step(),但是进入了SQLiteRepairKit的同名方法里（只是我猜测），仅供佬做参考

**Comment by Qiuwen-chen** [comment]
Please upgrade to WCDB 2.0.0. The new version doesn't have this problem.
