### ISSUE TITLE
insert not success

### ISSUE THREAD

**Issue by wdq123550** [Tencent/wcdb#907]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
oc

### The version of WCDB

> e.g. v1.0.5

2.0.0

### The platform of WCDB

> e.g. iOS, macOS or Android
ios

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

i update wcdb from 1.1.0 to 2.0.0.
And ,the insertObject:intoTable: function return NO.

but in v1.1.0, it's YES.

what happen?

the console does not log any about "wcdb" info.

**Comment by Qiuwen-chen** [comment]
You can find details about error handling here: https://github.com/Tencent/wcdb/wiki/Objc-%e7%9b%91%e6%8e%a7%e4%b8%8e%e9%94%99%e8%af%af%e5%a4%84%e7%90%86

**Comment by wdq123550** [comment]
3Q~
