### ISSUE TITLE
Some problem in WCDB_SYNTHESIZE_COLUMN

### ISSUE THREAD

**Issue by wdq123550** [Tencent/wcdb#909]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
oc

### The version of WCDB

> e.g. v1.0.5
v2.0.0

### The platform of WCDB

> e.g. iOS, macOS or Android
ios

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

cocoapods

### What's the issue?

if i have the property "content" in class at app version 1.0.0
and in app version 2.0.0, the property "content" was update to "title", in wcdb, use WCDB_SYNTHESIZE_COLUMN to change db.
but if in app version 3.0.0. the property "title" update to "subTitle", and one of user update app to 3.0.0 from 1.0.0.
WCDB_SYNTHESIZE_COLUMN can fix it ?

**Comment by Qiuwen-chen** [comment]
In app 2.0, you should configure WCDB_SYNTHESIZE_COLUMN(title, "content") . 

In app 3.0, you should configure WCDB_SYNTHESIZE_COLUMN(subTitle, "content"). 

This will not actually change the content of the database, so there will be no compatibility issues

**Comment by wdq123550** [comment]
Great~
