### ISSUE TITLE
是否支持C/C++的native 接口

### ISSUE THREAD

**Issue by MuYu-zhi** [Tencent/wcdb#910]
如题，希望在native中访问数据库，是否有相关接口可用，或者自行封装的话工作量预计如何

**Comment by Qiuwen-chen** [comment]
You can use WCDB C++：https://github.com/Tencent/wcdb/wiki/C++-%e5%ae%89%e8%a3%85%e4%b8%8e%e5%85%bc%e5%ae%b9%e6%80%a7

**Comment by MuYu-zhi** [comment]
C++接口是只有2.0.0版本才支持的吗，之前的1.0.8没有看到相关信息

**Comment by Qiuwen-chen** [comment]
Yes, WCDB C++ is released starting from 2.0.0
