### ISSUE TITLE
新版 创建数据库崩溃

### ISSUE THREAD

**Issue by X230** [Tencent/wcdb#912]
### The language of WCDB

swift

### The version of WCDB

v2.0.0

### The platform of WCDB

macOS

### The installation of WCDB

Cocoapods

### What's the issue?
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/14076410/229994254-8c79648a-0e6a-4a57-9e3c-659516855f1d.png">

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/14076410/229994352-73ecc203-77d1-4634-be44-a618d81ae58d.png">

**Comment by Qiuwen-chen** [comment]
Is it easy to repeat? You can give me a sample code so that I can reproduce this problem.

**Comment by Qiuwen-chen** [comment]
Does it only appear on the i386 architecture？

**Comment by X230** [comment]
> Is it easy to repeat? You can give me a sample code so that I can reproduce this problem.
使用文档里的例子就会出现  intel  arm64都有

class Sample: TableCodable {
    var identifier: Int? = nil
    var description: String? = nil
        
    enum CodingKeys: String, CodingTableKey {
        typealias Root = Sample
        case identifier
        case description
        static let objectRelationalMapping = TableBinding(CodingKeys.self) {
            BindColumnConstraint(identifier, isPrimary: true)
            BindColumnConstraint(description, isNotNull: true, defaultTo: "defaultDescription")
        }
    }

    var isAutoIncrement: Bool = false // 用于定义是否使用自增的方式插入
    var lastInsertedRowID: Int64 = 0 // 用于获取自增插入后的主键值
}

**Comment by Qiuwen-chen** [comment]
Show me the crash stack on arm64 architecture.

**Comment by socoolby** [comment]
**The language of WCDB**
swift

**The version of WCDB**
v2.0.0

**The platform of WCDB**
iOS

**The installation of WCDB**
Cocoapods

**The develop platform**
MacBook with Intel

The same problem. It is easy to repeat,
Working on device(iPhone), but not working on simulator(The sample code at [Tutorials for swift](https://github.com/Tencent/wcdb/wiki/Swift-%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8) will crash every time when create table).

**Comment by Qiuwen-chen** [comment]
> **The language of WCDB** swift
> 
> **The version of WCDB** v2.0.0
> 
> **The platform of WCDB** iOS
> 
> **The installation of WCDB** Cocoapods
> 
> **The develop platform** MacBook with Intel
> 
> The same problem. It is easy to repeat, Working on device(iPhone), but not working on simulator(The sample code at [Tutorials for swift](https://github.com/Tencent/wcdb/wiki/Swift-%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8) will crash every time when create table).

Got it.

**Comment by Qiuwen-chen** [comment]
The cause of the crash has been confirmed. This problem will not cause an error on the real device, and we will fix this problem in the next version. Before this, compiling the simulator with DEBUG configuration can also avoid this problem.

**Comment by Qiuwen-chen** [comment]
It is fixed in WCDB 2.0.1.
