### ISSUE TITLE
Incomplete type 'WCDB::Error' named in nested name specifier

### ISSUE THREAD

**Issue by vanemu** [Tencent/wcdb#913]
### The language of WCDB

> Objective-C

### The version of WCDB

> v2.0.0

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

Is there any documentation for major version upgrades? I'm having trouble compiling after upgrading to 2.0.0.

**Comment by Qiuwen-chen** [comment]
You can import WCDB.h or WCDBObjc.h. Here is the wiki of 2.0.0: https://github.com/Tencent/wcdb/wiki/Objc-%e5%bf%ab%e9%80%9f%e5%85%a5%e9%97%a8

**Comment by fypyxz** [comment]
> You can import WCDB.h or WCDBObjc.h. Here is the wiki of 2.0.0: https://github.com/Tencent/wcdb/wiki/Objc-%e5%bf%ab%e9%80%9f%e5%85%a5%e9%97%a8

我现在的情况是：已经使用pod 'WCDB.objc','2.0.1'了，单独项目应用没有问题，我在包含有RN的项目中也出现了这个问题

**Comment by Qiuwen-chen** [comment]
> > You can import WCDB.h or WCDBObjc.h. Here is the wiki of 2.0.0: https://github.com/Tencent/wcdb/wiki/Objc-%e5%bf%ab%e9%80%9f%e5%85%a5%e9%97%a8
> 
> 我现在的情况是：已经使用pod 'WCDB.objc','2.0.1'了，单独项目应用没有问题，我在包含有RN的项目中也出现了这个问题

I don't know, you can analyze it further.

**Comment by fypyxz** [comment]
好的

**Comment by vanemu** [comment]
> 好的

请问你这边解决了吗？我这边的旧项目还是无法通过编译。
