### ISSUE TITLE
能提升一下插入性能,插入性能比查询性能差太多

### ISSUE THREAD

**Issue by NBXXF** [Tencent/wcdb#914]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
iOS  or Android?

**Comment by NBXXF** [comment]
ios
