### ISSUE TITLE
连表查询并分组无结果返回

### ISSUE THREAD

**Issue by muken88** [Tencent/wcdb#916]
### The language of WCDB
 Objective-C
### The version of WCDB
 v2.0.0
### The platform of WCDB
iOS
### The installation of WCDB
Cocoapods

#### 情况1:连表查询(正常)
    WCDB::StatementSelect select1 = WCDB::StatementSelect();
    WCDB::TablesOrSubqueries table = select1.select(Model.allProperties).from(table1).unionAll().select(Model.allProperties).from(table2);
    WCDB::StatementSelect select2 = WCDB::StatementSelect();
    WCDB::Statement &statement = select2.select({Model.allProperties}).from(table).where(Model.text.match("qwer"));

#### 情况2:单表查询并分组(正常)
    WCDB::StatementSelect select1 = WCDB::StatementSelect();
    WCDB::TablesOrSubqueries table = select1.select(Model.allProperties).from(table1);
    WCDB::StatementSelect select2 = WCDB::StatementSelect();
    WCDB::Statement &statement = select2.select({Model.typeId,Model.typeId.count()}).from(table).where(Model.text.match("qwer")).group(Model.typeId);

#### 情况3:连表查询并分组(无结果返回)
    WCDB::StatementSelect select1 = WCDB::StatementSelect();
    WCDB::TablesOrSubqueries table = select1.select(Model.allProperties).from(table1).unionAll().select(Model.allProperties).from(table2);
    WCDB::StatementSelect select2 = WCDB::StatementSelect();
    WCDB::Statement &statement = select2.select({Model.typeId,Model.typeId.count()}).from(table).where(Model.text.match("qwer")).group(Model.typeId);

**Comment by muken88** [comment]
unable to use function MATCH in the requested context

**Comment by Qiuwen-chen** [comment]
NSLog(@"%s", statement.getDescription().data());

It can print the sql string of statement, and you can check the sql.

**Comment by muken88** [comment]
> 

我打印看过  然后我通过globalTraceError检测到了unable to use function MATCH in the requested context   但是我奇怪的是为什么连表之后使用match也是有结果的 但是再加个分组就会报上面这个错

**Comment by muken88** [comment]
> NSLog(@"%s", statement.getDescription().data());
> 
> It can print the sql string of statement, and you can check the sql.



> NSLog(@"%s", statement.getDescription().data());
> 
> It can print the sql string of statement, and you can check the sql.

我打印看过 然后我通过globalTraceError检测到了unable to use function MATCH in the requested context 但是我奇怪的是为什么连表之后使用match也是有结果的 但是再加个分组就会报上面这个错

**Comment by Qiuwen-chen** [comment]
It is a limitation of SQLite. Match function does not work like other functions.

**Comment by muken88** [comment]
> It is a limitation of SQLite. Match function does not work like other functions.

那如果说需要在连表的情况下再根据Match的结果去分组应该怎么做呢？

**Comment by Qiuwen-chen** [comment]
I have no idea for now, you can try other ways, such as splitting one query into two queries

**Comment by muken88** [comment]
> I have no idea for now, you can try other ways, such as splitting one query into two queries

好的感谢回复,我再想想其他办法
