### ISSUE TITLE
_ZN10WCTBinding28getOrCreateConstraintBindingI30WCTConstraintPrimaryKeyBindingEENSt3__19enable_ifIXsr3std10is_base_ofI24WCTConstraintBindingBaseT_EE5valueEPS5_E4typeERKNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE

### ISSUE THREAD

**Issue by V5zhou** [Tencent/wcdb#917]
### The language of WCDB

Objective-C

### The version of WCDB

v1.0.7.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
Thread 0 Crashed:
0   libsystem_kernel.dylib              0x000000020d2ff160 __pthread_kill + [ : 8] 
1   libsystem_pthread.dylib             0x000000021da1c1ac pthread_kill + [ : 268] 
2   libsystem_c.dylib                   0x00000001d7004c8c abort + [ : 180] 
3   libsystem_c.dylib                   0x00000001d705b880 err
4   FireCat                             0x0000000107268104 _ZN10WCTBinding28getOrCreateConstraintBindingI30WCTConstraintPrimaryKeyBindingEENSt3__19enable_ifIXsr3std10is_base_ofI24WCTConstraintBindingBaseT_EE5valueEPS5_E4typeERKNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE.cold.1 + [WCTBinding.h : 0] 
5   Fire                            0x0000000104fd69c0 -[GDImageEditorPrepareService reportLogWithEditorType:isPrepareWorkHistory:workRecordId:templateId:contentLength:isCancel:error:] + [GDImageEditorPrepareService.m : 46] 
6   Fire                             0x0000000104fd64e4 -[GDImageEditorPrepareLogger manager:resourceDownloadEnd:] + [GDImageEditorPrepareLogger.m : 0] 
7   CoreFoundation                      0x00000001cf9f86c4 __invoking___ + [ : 148] 
8   CoreFoundation                      0x00000001cf9a4b2c -[NSInvocation invoke] + [ : 428] 
9   CoreFoundation                      0x00000001cf9a4544 -[NSInvocation invokeWithTarget:] + [ : 64] 
10  Fire                            0x0000000105008530 -[GDMultipleProxy forwardInvocation:] + [GDMultipleProxy.m : 49] 
11  CoreFoundation                      0x00000001cf9a3cf8 ___forwarding___ + [ : 976] 
12  CoreFoundation                      0x00000001cfa0c330 __forwarding_prep_0___ + [ : 96] 
13  Fire                             0x0000000104fea7ec __85-[GDImageTemplateManager downloadResourceWithTemplate:isSkipDownloadBackgroundImage:]_block_invoke + [GDImageTemplateManager.m : 0] 

> Explain what you want by example or code **in English**.

It is not clear what caused the wcdb crash, as it appears that we did not call wcdb in GDImageEditorPrepareService.m，And this is a sporadic crash, we cannot reproduce it. The method on line 5 is called via message forwarding by GDMultipleProxy, implemented as follows:

```
//
//  GDMultipleProxy.m
//

#import "GDMultipleProxy.h"

@interface GDMultipleProxy ()

@property (nonatomic, strong) NSPointerArray *proxies;      /// 所有代理。使用NSPointerArray保证调用有序性
@property (nonatomic, strong) NSMutableSet *strongRef;      /// 被强引用的代理

@end

@implementation GDMultipleProxy

// MARK: - public

- (void)addProxy:(id)proxy {
    [self.proxies addPointer:(__bridge void * _Nullable)(proxy)];
    [self.strongRef addObject:proxy];
}

- (void)addWeakProxy:(id)proxy {
    [self.proxies addPointer:(__bridge void * _Nullable)(proxy)];
}

- (void)removeProxy:(id)proxy {
    NSUInteger i = 0;
    while (i < self.proxies.count) {
        id item = [self.proxies pointerAtIndex:i];
        if (item == proxy) {
            [self.proxies removePointerAtIndex:i];
            break;
        }
        i++;
    }
}

// MARK: - 消息转发

- (void)forwardInvocation:(NSInvocation *)invocation {
    for (id proxy in self.proxies) {
        if (proxy && [proxy respondsToSelector:invocation.selector]) {
            [invocation invokeWithTarget:proxy];
        }
    }
}

- (NSMethodSignature *)methodSignatureForSelector:(SEL)sel {
    for (id proxy in self.proxies) {
        if (!proxy) {
            continue;
        }
        NSMethodSignature *signature = [proxy methodSignatureForSelector:sel];
        if (signature) {
            return signature;
        }
    }
    // 未命中的调用
    return [NSMethodSignature signatureWithObjCTypes:"v@:@"];
}

// MARK: - setter & getter

- (NSPointerArray *)proxies {
    if (!_proxies) {
        _proxies = [NSPointerArray weakObjectsPointerArray];
    }
    return _proxies;
}

- (NSMutableSet *)strongRef {
    if (!_strongRef) {
        _strongRef = [NSMutableSet set];
    }
    return _strongRef;
}

@end

```

**Comment by Qiuwen-chen** [comment]
This is not a WCDB related problem, it may be caused by a stack symbol parsing problem.
