### ISSUE TITLE
Is there any plan to remove jetifier?

### ISSUE THREAD

**Issue by zhangzhenxi** [Tencent/wcdb#918]
### The language of WCDB
Java

### The version of WCDB
`1.0.8`

### The platform of WCDB
`Android`

### The installation of WCDB
`gradle`

### What's the issue?

![image](https://user-images.githubusercontent.com/7889171/231085549-daa7de62-591a-49e1-8b70-ee77803b9277.png)

Is there any plan to remove jetifier ??

**Comment by Qiuwen-chen** [comment]
I will consider it when developing WCDB Java.
