### ISSUE TITLE
绑定枚举类型的属性时提示错误

### ISSUE THREAD

**Issue by mongelly** [Tencent/wcdb#92]
`typedef NS_ENUM(int,AppConfigType)
{
    AppConfigTypeLocal,
    AppConfigTypeRemote
};

@interface AppConfigMeta : NSObject<WCTTableCoding>

@property (nonatomic) NSString *key;
@property (nonatomic) NSString *value;
@property AppConfigType type;
@property (nonatomic) NSString *userid;

WCDB_PROPERTY(key)
WCDB_PROPERTY(value)
WCDB_PROPERTY(type)
WCDB_PROPERTY(userid)

@end
`
采用OC新的枚举声明方式以后，绑定type属性时编译会出现以下提示，这个是为什么？

~/Pods/Headers/Public/WCDB/WCTRuntimeCppAccessor.h:60:67: Cannot initialize return object of type 'AppConfigType' with an lvalue of type 'CType' (aka 'int')

**Comment by RingoD** [comment]
这个已经修复了
https://github.com/Tencent/wcdb/commit/3bd0d0d1e2fa67525a9606e1fb20f3f56f98ff8b
