### ISSUE TITLE
Lots of 0xdead10cc crashes after embedding widget

### ISSUE THREAD

**Issue by lileitodev** [Tencent/wcdb#920]
### The language of WCDB
Swift

### The version of WCDB
1.0.8.2

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?
a lot of crash on the App Store crash analysis `Termination Reason: RUNNINGBOARD 0xdead10cc `
[Apple doc said and link:](https://developer.apple.com/documentation/xcode/understanding-the-exception-types-in-a-crash-report) 

> 0xdead10cc (pronounced “dead lock”). The operating system terminated the app because it held on to a file lock or SQLite database lock during suspension. Request additional background execution time on the main thread with [beginBackgroundTask(withName:expirationHandler:)](https://developer.apple.com/documentation/uikit/uiapplication/1623051-beginbackgroundtask). Make this request well before starting to write to the file in order to complete those operations and relinquish the lock before the app suspends. In an app extension, use [beginActivity(options:reason:)](https://developer.apple.com/documentation/foundation/processinfo/1415995-beginactivity) to manage this work.

I need to use the host app database in the [widget](https://developer.apple.com/documentation/widgetkit/).The database works well before I added [widget](https://developer.apple.com/documentation/widgetkit/) to my project.And I moved the database path to App Group path.

When I integrate the widget for the first time, the main application will **crash immediately** after entering the background.
To avoid this problem, [according to this page](https://developer.apple.com/forums/thread/126438), I call `database.close`  in `applicationWillResignActive`. It no longer crashes immediately， but the app will **crash after several seconds**.
To avoid the app crash in background several seconds,I applied for 5s with `beginBackgroundTask` to let the app handle all database operations. It's better now. at least user Insensible. But there is a lot of crashes on App Store. maybe wcdb need to provide support  to avoid the crash.

```
var work: DispatchWorkItem? = nil
func applicationWillResignActive(_ application: UIApplication) {
    work?.cancel()
    work = DispatchWorkItem(block: {
        UserManager.getManager()?.database?.close()
        UIApplication.shared.endBackgroundTask(self.dbOpId)
        self.dbOpId = UIBackgroundTaskIdentifier.invalid
    })
    UIApplication.shared.endBackgroundTask(self.dbOpId)
    self.dbOpId = UIBackgroundTaskIdentifier.invalid
    self.dbOpId = UIApplication.shared.beginBackgroundTask (withName: "DBOP") {
        UserManager.getManager()?.database?.close()
        UIApplication.shared.endBackgroundTask(self.dbOpId)
        self.dbOpId = UIBackgroundTaskIdentifier.invalid
    }
    print("start op: \(self.dbOpId)")
    if let work = self.work {
        //give last 5 seconds to handle works.
        DispatchQueue(label: "alhosn.default", attributes: .concurrent).asyncAfter(deadline: .now() + 5, execute: work)
    }
}    
```

**Comment by Qiuwen-chen** [comment]
Thanks for the feedback, it's a bit complicated, I'll analyze it later when I have time.

**Comment by lileitodev** [comment]
> Thanks for the feedback, it's a bit complicated, I'll analyze it later when I have time.

Thank you for your reply.

I have written a demo on github. [this is the link.](https://github.com/lileitodev/WidgetCrashWithWCDBSwift) which can lead to the crash.
1.  I ignored the pods folder. You need to install pods yourself. This way you can see little code in git history.
2. You need to test it with your app group and the bundle ID of your developer account.
3. you need run this demo on a real device.
4. run the demo and let the app enter background. you will see `Message from debugger: Terminated due to signal 9`. the app crash immediately.

I found that if I remove `database?.setCipher(key: pwdData)` the demo doesn't crash when going into the background.
Widget code is template. All I added to TestWidget is this code:
```
let testInfo = TestInfo()
testInfo.uuid = "widget" + UUID().uuidString
TestManager.manager.saveInfo(info: testInfo)
```
The other code is in the host app's `ViewController.swift` and `TestInfo.swift` files.

Hope this helps you.

**Comment by Qiuwen-chen** [comment]
> > Thanks for the feedback, it's a bit complicated, I'll analyze it later when I have time.
> 
> Thank you for your reply.
> 
> I have written a demo on github. [this is the link.](https://github.com/lileitodev/WidgetCrashWithWCDBSwift) which can lead to the crash.
> 
> 1. I ignored the pods folder. You need to install pods yourself. This way you can see little code in git history.
> 2. You need to test it with your app group and the bundle ID of your developer account.
> 3. you need run this demo on a real device.
> 4. run the demo and let the app enter background. you will see `Message from debugger: Terminated due to signal 9`. the app crash immediately.
> 
> I found that if I remove `database?.setCipher(key: pwdData)` the demo doesn't crash when going into the background. Widget code is template. All I added to TestWidget is this code:
> 
> ```
> let testInfo = TestInfo()
> testInfo.uuid = "widget" + UUID().uuidString
> TestManager.manager.saveInfo(info: testInfo)
> ```
> 
> The other code is in the host app's `ViewController.swift` and `TestInfo.swift` files.
> 
> Hope this helps you.

Got it!

**Comment by Qiuwen-chen** [comment]
Here might be the reason for that crash: https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_plaintext_header_size

**Comment by Qiuwen-chen** [comment]
Here is the reason for that crash: https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_plaintext_header_size

You can config cipher_plaintext_header_size with StatementPragma through Database.setConfig(named:with:orderBy:).

**Comment by lileitodev** [comment]
I didn't find a predefined for `cipher_plaintext_header_size` in struct `Pragma`,and the Pragma `init(named name: String)` is fileprivate.
So  I temporarily changed it to public. Is there any other way to set it?
```
if let pwdData = "$b)PGhvRtpjnQDqc".data(using: .utf8)  {
            database?.setConfig(named: "demo", with: { (handle: Handle) throws in
                try handle.exec(StatementPragma().pragma(Pragma(named: "cipher_plaintext_header_size"), to: 32))
            }, orderBy: 1)
            database?.setCipher(key: pwdData)
 }
```
and the console output:
```
[WCDB][ERROR] Code:sqlite(26), Type:SQLite, Operation:4,Message:file is encrypted or is not a database,ExtendedCode:26,SQL:PRAGMA synchronous='NORMAL',Path:/var/mobile/Containers/Shared/AppGroup/5138E04C-E539-4AFA-808E-50823355F568/DataBase/Test.sqlite
```
I'm not sure what I'm doing wrong.

**Comment by lileitodev** [comment]
> Here is the reason for that crash: https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_plaintext_header_size
> 
> You can config cipher_plaintext_header_size with StatementPragma through Database.setConfig(named:with:orderBy:).
Thank you very much. But I have some problem while configuring this.
 I didn't find a predefined for `cipher_plaintext_header_size` in struct `Pragma`,and the Pragma `init(named name: String)` is fileprivate.
So  I temporarily changed it to public. Is there any other way to set it?
```
if let pwdData = "$b)PGhvRtpjnQDqc".data(using: .utf8)  {
            database?.setConfig(named: "demo", with: { (handle: Handle) throws in
                try handle.exec(StatementPragma().pragma(Pragma(named: "cipher_plaintext_header_size"), to: 32))
            }, orderBy: 1)
            database?.setCipher(key: pwdData)
 }
```
and the console output:
```
[WCDB][ERROR] Code:sqlite(26), Type:SQLite, Operation:4,Message:file is encrypted or is not a database,ExtendedCode:26,SQL:PRAGMA synchronous='NORMAL',Path:/var/mobile/Containers/Shared/AppGroup/5138E04C-E539-4AFA-808E-50823355F568/DataBase/Test.sqlite
```
I'm not sure what I'm doing wrong.

**Comment by Qiuwen-chen** [comment]
This configuration is only valid on new databases. 

Beside cipher_plaintext_header_size, cipher_salt also needs to be configured. You need to read the content in the link completely, and after configuration, you must also confirm that the header of the database will not be encrypted.

**Comment by Qiuwen-chen** [comment]
fileprivate modifier in Pragma will be changed to public in next version

**Comment by Qiuwen-chen** [comment]
> > This configuration is only valid on new databases.
> > Beside cipher_plaintext_header_size, cipher_salt also needs to be configured. You need to read the content in the link completely, and after configuration, you must also confirm that the header of the database will not be encrypted.
> 
> according to [the link](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_plaintext_header_size)
> 
> ```
> sqlite> pragma key = 'test';
> ok
> sqlite> select count(*) from sqlite_master; -- trigger header read, currently it is encrypted
> 1
> sqlite> PRAGMA cipher_salt; -- read current salt and save it for later use
> 5062fa73375626a23af92d3dce504b57
> sqlite> PRAGMA cipher_plaintext_header_size = 32;
> sqlite> PRAGMA user_version = 1; -- force header write
> ```
> 
> I need get the encrypted salt first. how can I get the salt with the wcdb API?

You can use HandleStatement.

**Comment by Qiuwen-chen** [comment]
The wiki of WCDB 2.0 might help you: https://github.com/Tencent/wcdb/wiki/Swift-%e9%ab%98%e7%ba%a7%e6%8e%a5%e5%8f%a3#handle

**Comment by lileitodev** [comment]
I tested this process on the command line tool with my test database.

<img width="961" alt="WechatIMG4" src="https://user-images.githubusercontent.com/37165325/233406537-ded3511f-618a-45ce-8ba4-7d0771715623.png">

I get the salt with my swift code. Same as the salt obtained by Terminal.
```
class func getSalt() -> String? {
        if let dbURL = URL(string: databasePath()) {
            do {
                let saltLength = 16
                let handle = try FileHandle(forReadingFrom:dbURL)
                let first16Bytes: Data? = try handle.read(upToCount: saltLength)
                try handle.close()
                let salt = first16Bytes?.hexEncodedString()
                print(salt)
                if let salt = salt {
                    save(salt: salt)
                }
                return salt
            } catch  {
                print(error)
            }
        }
        return getSavedSalt()
    }
```
The problem is that when the app is installed for the first time, the `setConfig` callback can be executed.
[the sqlciper doc said](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_plaintext_header_size)
> Note that PRAGMA cipher_plaintext_header_size must be called each time the database is opened and keyed. Likewise, the salt must be stored externally to the database by the application and provided for initialization every time the database is opened (with the possible exception of the first time a database is created).
```
database?.setCipher(key: pwdData)
                database?.setConfig(named: "demo", withInvocation: { handle in
                    //The call back only be called when the app is installed for the first time. According to the sqlciper doc. I need this run every open db.
                    if let salt = Self.getSalt(), !salt.isEmpty {
                        let headerSizePragma = Pragma(named: "cipher_plaintext_header_size")
                        try handle.exec(StatementPragma().pragma(headerSizePragma).to(32))
                        let saltPragma = Pragma(named: "cipher_salt")
                        try handle.exec(StatementPragma().pragma(saltPragma).to(salt))
                    }

                }, withPriority: .high)
```
But the second time, restart the application. The `setconfig` callback is not  be called.
So it can't execute the configuration about salt and header_size.
the console show error
`[ERROR] Code:NotADatabase Message:file is not a database`

**Comment by Qiuwen-chen** [comment]
I'll handle it in the next version in a week or two, please wait.

**Comment by Qiuwen-chen** [comment]
You need to save the salt read from the database to a separate file instead of reading directly from the database each time, or you can directly generate a random salt and set it on a new database.

Note that the configuration logic for setting the salt needs to be configured with the highest priority. WCDB 2.0.1 supports adding the highest priority configuration。

**Comment by lileitodev** [comment]
> You need to save the salt read from the database to a separate file instead of reading directly from the database each time, or you can directly generate a random salt and set it on a new database.
> 
> Note that the configuration logic for setting the salt needs to be configured with the highest priority. WCDB 2.0.1 supports adding the highest priority configuration.
Thank you very much.You save my life bro.
Finally. I use the process below to make the cipher plaintext header works.
```
database?.setConfig(named: "demo", withInvocation: { handle in
            do {
                if let salt = Self.getSavedSalt(), !salt.isEmpty {
                    let mark: String = "open plaintext db again:"
                    try handle.exec(StatementPragma().pragma(.key).to("test"))
                    print("\(mark) set key done")
                    try handle.exec(StatementPragma().pragma(.cipherSalt).to("x'\(salt)'"))
                    print("\(mark) read saved salt: set salt done")
                    try handle.exec(StatementPragma().pragma(.cipherPlainTextHeaderSize).to(32))
                    print("\(mark) set cipherPlainTextHeaderSize done")

                } else {
                    let mark: String = "set plain text for db:"
                    try handle.exec(StatementPragma().pragma(.key).to("test"))
                    print("\(mark) set key done")
                    try handle.exec(StatementSelect().select(Column.all).from("sqlite_master"))
                    print("\(mark) fetch sqlite_master done")
                    try handle.exec(StatementPragma().pragma(.cipherSalt))
                    print("\(mark) get salt done")
                    if let salt = Self.getDBSalt() {
                        try handle.exec(StatementPragma().pragma(.cipherSalt).to("x'\(salt)'"))
                        print("\(mark) set salt done")
                        try handle.exec(StatementPragma().pragma(.cipherPlainTextHeaderSize).to(32))
                        print("\(mark) set cipherPlainTextHeaderSize done")
                        //force write cipherPlainTextHeaderSize
                        try handle.exec(StatementPragma().pragma(.userVersion).to(1))
                        print("\(mark) set userVersion done")
                    }
                }
                
            } catch  {
                print(error)
            }
        }, withPriority: .highest)
```
hope this can help somebody. [demo link](https://github.com/lileitodev/WidgetCrashWithWCDBSwift.git)

**Comment by lileitodev** [comment]
in the demo it works fine. but in my project, I have some problem to get cipher salt. 
So I want try other way to get the cipher salt.
I found the c++ method, but I can not translate it to swift. there is no `getText()` in swift version handle. can you provide a swift version for this.

In the demo, it works fine for getting the cipher salt. But in my project, I have some problems.So I want to try other way to get the cipher salt.
I found a c++ method in WCDB source code. but can't convert it to swift. There is no `getText()` in the swift version handle. Can you provide a  swift version for this? Thank you.
```
StringView AbstractHandle::getCipherSalt()
{
    WCTAssert(isOpened());
    HandleStatement handleStatement(this);
    Statement cipherSalt = StatementPragma().pragma(Pragma::cipherSalt());
    StringView salt;
    if (handleStatement.prepare(cipherSalt) && handleStatement.step()
        && !handleStatement.done()) {
        salt = handleStatement.getText();
    }
    handleStatement.finalize();
    return salt;
}
```

**Comment by lileitodev** [comment]
In the demo, getting the cipher salt works fine. But in my project, I have some problems to get it.So I want to try other way to get the cipher salt.
I found a c++ method in WCDB source code. but can't convert it to swift. There is no `getText()` in the swift version handle. Can you provide a  swift version for this? Thank you.
```
StringView AbstractHandle::getCipherSalt()
{
    WCTAssert(isOpened());
    HandleStatement handleStatement(this);
    Statement cipherSalt = StatementPragma().pragma(Pragma::cipherSalt());
    StringView salt;
    if (handleStatement.prepare(cipherSalt) && handleStatement.step()
        && !handleStatement.done()) {
        salt = handleStatement.getText();
    }
    handleStatement.finalize();
    return salt;
}
```

**Comment by Qiuwen-chen** [comment]
> setconfig配置后, 导出数据库, 发现是没有加密的呀, 可以直接用工具打开

You should use setCipher interface to config cipher key.

**Comment by yuangaopeng** [comment]
thank you!
这么设置之后,后台crash减少了, 但还是存在, 是不是配置代码的问题,求解
以下就是配置部分:
self.db?.setCipher(key: key)
 self.db?.setConfig(named: "yisuobao", withInvocation: { handle in
                do {
                    
                    if let salt = self.getSavedSalt(), !salt.isEmpty {
                        try handle.exec(StatementPragma().pragma(.key).to(key!))
                        try handle.exec(StatementPragma().pragma(.cipherPlainTextHeaderSize).to(32))
                        try handle.exec(StatementPragma().pragma(.cipherSalt).to("x'\(salt)'"))

**Comment by Qiuwen-chen** [comment]
> 

No idea. You can do further analyze.
