### ISSUE TITLE
跨数据库联表操作问题

### ISSUE THREAD

**Issue by lisiqiang** [Tencent/wcdb#923]
### The language of WCDB

>Java 

### The version of WCDB

>  v1.0.8

### The platform of WCDB

> Android

### The installation of WCDB

> Maven

### What's the issue?
我这边通过sql语句 将aaa数据库附加到 bbb数据库，访问时，报找不到数据库（aaa）中的表，WCDB 不知道支持不支持跨数据库联表查询啊，我是将sqlite迁移到WCDB,遇到这个问题
ATTACH DATABASE /data/user/0/xxxx/databases/aaa.db AS mydb KEY 'aaaa';

> Post the outputs or screenshots for errors.
> 
![企业微信截图_20230414191303](https://user-images.githubusercontent.com/4235445/232029325-89f4c927-37dc-4602-b749-de7a62a6ad7b.png)

> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
The new version of WCDB Java is under development, and it will support cross-database queries.
