### ISSUE TITLE
在开启事务时，能指定事务类型吗？

### ISSUE THREAD

**Issue by WuKongCoo1** [Tencent/wcdb#924]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
Objective-C

### The version of WCDB

> e.g. v1.0.5
v1.0.7

### The platform of WCDB

> e.g. iOS, macOS or Android
iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
Cocoapods

### What's the issue?
在开启事务时，能指定事务类型吗？如：
1. BEGIN [ DEFERRED] TRANSACTION
2. BEGIN [IMMEDIATE] TRANSACTION
3. BEGIN [EXCLUSIVE] TRANSACTION：

**Comment by Qiuwen-chen** [comment]
You can use StatementBegin to begin a transaction manually.
