### ISSUE TITLE
1.0.7.5加密版本升级到2.0.0，ERROR: 26, file is not a database 

### ISSUE THREAD

**Issue by fypyxz** [Tencent/wcdb#925]
### The language of WCDB

 Objective-C
wcdb2.0.0
iOS
Cocoapods

### What's the issue?
1.0.7.5加密版本升级到2.0.0

运行报错如下：
 [WCDB ERROR][ERROR: 26, file is not a database], SQL: PRAGMA journal_mode, Path: /var/mobile/Containers/Data/Application/********/********.db, Source: SQLite，

升级不了，这个升级过程相当麻烦，修改太多代码了，旧方法的面目全非了，升级代价大

**Comment by Qiuwen-chen** [comment]
We did not change the encryption logic.

**Comment by fypyxz** [comment]
Pod:1.0.7.5版本
  - WCDB (1.0.7.5):
    - SQLiteRepairKit (~> 1.2.0)
    - WCDBOptimizedSQLCipher (~> 1.2.0)
  - WCDBOptimizedSQLCipher (1.2.1)
Pod:2.0.0版本
 - WCDB (2.0.0):
    - WCDB/no-arc (= 2.0.0)
    - WCDBOptimizedSQLCipher (~> 1.4.0)
  - WCDB/no-arc (2.0.0):
    - WCDBOptimizedSQLCipher (~> 1.4.0)
  - WCDBOptimizedSQLCipher (1.4.0)
 1.0.7.5升级到1.1.0版本也是不行的，是不是加密库升级导致的呢？

**Comment by fypyxz** [comment]
[ERROR: 26, file is not a database], SQL: PRAGMA journal_mode, Path:*****

**Comment by Qiuwen-chen** [comment]
Can this problem be repeated with a new database as well?

**Comment by fypyxz** [comment]
> We did not change the encryption logic.

[ERROR: 26, file is not a database], SQL: PRAGMA journal_mode, Path:*****

**Comment by fypyxz** [comment]
> Can this problem be repeated with a new database as well?

如果不是升级就不会有这个问题
，只有从旧版本升级上来的才会有这个问题

**Comment by fypyxz** [comment]
self.database = [[WCTDatabase alloc] initWithPath:dbPathAndName];
[self.database setCipherKey:cipherData andCipherPageSize:4096];

我开始就是这样初始化的，
SQL: PRAGMA journal_mode,这块不知道哪里运行的

**Comment by fypyxz** [comment]
1.0.7.5版本初始化语句：
GlobalSQLTrace SQL: PRAGMA cipher_page_size=4096
GlobalSQLTrace SQL: PRAGMA locking_mode
GlobalSQLTrace SQL: PRAGMA synchronous='NORMAL'
GlobalSQLTrace SQL: PRAGMA journal_mode
GlobalSQLTrace SQL: PRAGMA journal_mode='WAL'
GlobalSQLTrace SQL: PRAGMA fullfsync=1
lobalSQLTrace SQL: PRAGMA synchronous='FULL'


2.0.0版本初始化语句：
GlobalSQLTrace SQL: PRAGMA cipher_page_size = 4096
GlobalSQLTrace SQL: PRAGMA journal_mode
GlobalSQLTrace SQL: PRAGMA temp_store = 1
GlobalSQLTrace SQL: PRAGMA cipher_page_size = 4096（这块怎么跑两次。。。）
GlobalSQLTrace SQL: PRAGMA journal_mode
GlobalSQLTrace SQL: PRAGMA journal_mode = 'WAL'
GlobalSQLTrace SQL: PRAGMA checkpoint_fullfsync = TRUE
GlobalSQLTrace SQL: PRAGMA temp_store = 1


两个初始化流程有点不一样吗？

**Comment by fypyxz** [comment]
1.0.7.5版本初始化语句：
GlobalSQLTrace SQL: PRAGMA cipher_page_size=4096
GlobalSQLTrace SQL: PRAGMA locking_mode
GlobalSQLTrace SQL: PRAGMA synchronous='NORMAL'
GlobalSQLTrace SQL: PRAGMA journal_mode
GlobalSQLTrace SQL: PRAGMA journal_mode='WAL'
GlobalSQLTrace SQL: PRAGMA fullfsync=1
lobalSQLTrace SQL: PRAGMA synchronous='FULL'


2.0.0版本初始化语句：
GlobalSQLTrace SQL: PRAGMA cipher_page_size = 4096
GlobalSQLTrace SQL: PRAGMA journal_mode
GlobalSQLTrace SQL: PRAGMA temp_store = 1
GlobalSQLTrace SQL: PRAGMA cipher_page_size = 4096
GlobalSQLTrace SQL: PRAGMA journal_mode
GlobalSQLTrace SQL: PRAGMA journal_mode = 'WAL'
GlobalSQLTrace SQL: PRAGMA checkpoint_fullfsync = TRUE
GlobalSQLTrace SQL: PRAGMA temp_store = 1

**Comment by fypyxz** [comment]
1.0.7.5升级到2.0.0版本，打开就数据库日志：

GlobalSQLTrace SQL: PRAGMA cipher_page_size = 4096
GlobalSQLTrace SQL: PRAGMA temp_store = 1
GlobalSQLTrace SQL: PRAGMA temp_store = 1
GlobalSQLTrace SQL: PRAGMA cipher_page_size = 4096
[ERROR: 26, file is not a database], SQL: PRAGMA journal_mode, Path:
GlobalSQLTrace SQL: PRAGMA temp_store = 1
GlobalSQLTrace SQL: PRAGMA cipher_page_size = 4096
[ERROR: 26, file is not a database], Source: SQLite, Type: Integrity, SQL: PRAGMA journal_mode, Path:
GlobalSQLTrace SQL: PRAGMA temp_store = 1
GlobalSQLTrace SQL: PRAGMA cipher_page_size = 4096
[ERROR:
GlobalSQLTrace SQL: PRAGMA temp_store = 1,path=Project_2040c20f7997e168ab920afe6430fe4c.db
GlobalSQLTrace SQL: PRAGMA cipher_page_size = 4096,path=Project_2040c20f7997e168ab920afe6430fe4c.db

**Comment by Qiuwen-chen** [comment]
Create a new demo project, use WCDB 1.0.7.5 to create a new encrypted database, and then use WCDB 2.0 to open the database to see if there is any problem.

**Comment by fypyxz** [comment]
> Create a new demo project, use WCDB 1.0.7.5 to create a new encrypted database, and then use WCDB 2.0 to open the database to see if there is any problem.

是的，就是最简单的项目，升级就不行了


@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    //转换到应用程序的Document目录下
    NSArray *searchPaths =    NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    NSString *tDocumentFolderPath=[[NSString alloc] initWithString:[searchPaths objectAtIndex: 0]];
    
    [self registerWCDBTrace];
    WCTDatabase* database = [[WCTDatabase alloc] initWithPath:[NSString stringWithFormat:@"%@/sample.db",tDocumentFolderPath]];
    
    [database setCipherKey:[@"db_password" dataUsingEncoding:NSASCIIStringEncoding] andCipherPageSize:4096];
    
    //1.0.7.5
//    if (![database isTableExists:NSStringFromClass(Sample.class)]) {
//        [database createTableAndIndexesOfName:@"Sample" withClass:Sample.class];
//    }
//    //Prepare data
//    Sample* object = [[Sample alloc] init];
//    object.identifier = 1;
//    object.content = @"sample_insert";
//    //Insert
//    BOOL ret = [database insertObject:object into:@"Sample"];
    
    
    
    //2.0.0
    if (![database tableExists:NSStringFromClass(Sample.class)]) {
        [database createTable:@"Sample" withClass:Sample.class];
    }
    //Prepare data
    Sample* object = [[Sample alloc] init];
    object.identifier = 1;
    object.content = @"sample_insert";
    //Insert
    BOOL ret = [database insertObject:object intoTable:@"Sample"];
    
    [database close:^{
        NSLog(@"关闭数据库。。");
    }];
}

//注册WCDB栈(未确定是否只要注册一次)
- (void)registerWCDBTrace
{
    //错误信息健康1.0.7.5
//    [WCTStatistics SetGlobalErrorReport:^(WCTError *error)
//    {
//        NSLog(@"[WCDB error]%@", error);
//    }];
    
    //2.0.0
    [WCTDatabase globalTraceError:^(WCTError *error)
    {
        NSLog(@"[WCDB error]%@", error);
    }];

}
@end

**Comment by fypyxz** [comment]
1.0.7.5升级到1.1.0版本也是不行的，一样的问题

**Comment by Qiuwen-chen** [comment]
Try cipher_migrate with StatementPragma through -[WCTDatabase setConfig:withUninvocation:forName:withPriority:]

https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_migrate

**Comment by fypyxz** [comment]
> Try cipher_migrate with StatementPragma through -[WCTDatabase setConfig:withUninvocation:forName:withPriority:]
> 
> https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_migrate

能不能给个例子呀，膜拜下

**Comment by fypyxz** [comment]
> Try cipher_migrate with StatementPragma through -[WCTDatabase setConfig:withUninvocation:forName:withPriority:]
> 
> https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_migrate


[database setConfig:^BOOL(WCTHandle * handle) {
        return [handle execute:WCDB::StatementPragma().pragma(WCDB::Pragma::key()).to("db_password")];
    } withUninvocation:nil forName:@"key"];
    [database setConfig:^BOOL(WCTHandle * handle) {
        return [handle execute:WCDB::StatementPragma().pragma(WCDB::Pragma::cipherMigrate())];
    } withUninvocation:nil forName:@"cipher_migrate"];

这块不是很了解，麻烦指点下

**Comment by Qiuwen-chen** [comment]
I'll fix this in the next version in a week or two, please wait.

**Comment by JvanChow** [comment]
Maybe it related to the SQLCipher encryption algorithm, test by DB Browser for  SQLite.
1.0.7.5 page is 4096, KDF iteration  is 64000, HMAC algorithm is SHA1, KDF algorithm is SHA1，it work.
2.0.0 page is 4096, KDF iteration  is 256000, HMAC algorithm is SHA512, KDF algorithm is SHA512，it work.

**Comment by fypyxz** [comment]
> Maybe it related to the SQLCipher encryption algorithm, test by DB Browser for SQLite.
> 1.0.7.5 page is 4096, KDF iteration is 64000, HMAC algorithm is SHA1, KDF algorithm is SHA1，it work.
> 2.0.0 page is 4096, KDF iteration is 256000, HMAC algorithm is SHA512, KDF algorithm is SHA512，it work.

Can you provide the setting version of Object c? Thank you！
能不能提供Object-c的设置版本，谢谢

**Comment by JvanChow** [comment]
> > Maybe it related to the SQLCipher encryption algorithm, test by DB Browser for SQLite.
> > 1.0.7.5 page is 4096, KDF iteration is 64000, HMAC algorithm is SHA1, KDF algorithm is SHA1，it work.
> > 2.0.0 page is 4096, KDF iteration is 256000, HMAC algorithm is SHA512, KDF algorithm is SHA512，it work.
> 
> Can you provide the setting version of Object c? Thank you！ 能不能提供Object-c的设置版本，谢谢

I'm not the author, wait the next version.

**Comment by Qiuwen-chen** [comment]
The new interface -[WCTDatabase setCipherKey:andCipherPageSize:andCipherViersion:] in WCDB 2.0.1 can open the database created by old versions of sqlcipher, please try.

**Comment by fypyxz** [comment]
> The new interface -[WCTDatabase setCipherKey:andCipherPageSize:andCipherViersion:] in WCDB 2.0.1 can open the database created by old versions of sqlcipher, please try.

pod 'WCDB','2.0.1'
error:CocoaPods could not find compatible versions for pod "WCDB":

**Comment by fypyxz** [comment]
> The new interface -[WCTDatabase setCipherKey:andCipherPageSize:andCipherViersion:] in WCDB 2.0.1 can open the database created by old versions of sqlcipher, please try.

测试升级可以了，感谢！

**Comment by lin-it** [comment]
@Qiuwen-chen  大佬这个问题1.1.0就不行了。能修一下吗

**Comment by fypyxz** [comment]
> @Qiuwen-chen 大佬这个问题1.1.0就不行了。能修一下吗

2.0版本和1.1版本，两个写法完全不一样，估计他不想维护这个了
趁早升级，1.0.7.5到1.1版本升级去了两三年
