### ISSUE TITLE
2.0.0 最低系统要求 iOS12.4.0，如果在 iOS11 上集成有什么问题？没找到差异的地方

### ISSUE THREAD

**Issue by JvanChow** [Tencent/wcdb#926]
### The language of WCDB

> e.g. Objective-C

### The version of WCDB

> e.g. v2.0.0

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

系统要求
iOS 12.4 及以上

如果在 iOS11 上集成 2.0.0 有什么问题？没找到差异的 API

**Comment by Qiuwen-chen** [comment]
No problem for now. However, the minimum supported version of WeChat is already iOS13, and we may not be compatible with lower versions in the future.
