### ISSUE TITLE
Data race in walIndexAppend

### ISSUE THREAD

**Issue by DrunkardSworder** [Tencent/wcdb#927]
### The language of WCDB

> Swift

### The version of WCDB

> 2.0.0

### The platform of WCDB

> iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

> ![image](https://user-images.githubusercontent.com/36027902/233826374-575fedf7-185e-4651-9a39-8b6468f2727e.png)
>

**Comment by Qiuwen-chen** [comment]
It's the logic of sqlite and we do not change it.

**Comment by edwin-chief** [comment]
How did you solve this problem? I'm also encountering this crash.
