### ISSUE TITLE
Domain=WCDB Code=11 "(null)" UserInfo={Msg=database disk image is malformed, Tag=523, ExtCode=11, WCTErrorType=1,

### ISSUE THREAD

**Issue by AxlTom** [Tencent/wcdb#928]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.7

### The platform of WCDB

> iOS

### The installation of WCDB

>  Cocoapods

### What's the issue?
DB error is Error Domain=WCDB Code=11 "(null)" UserInfo={Msg=database disk image is malformed, Tag=523, ExtCode=11, WCTErrorType=1,
最近遇到了这种错误，想请教一下怎么解决

**Comment by Qiuwen-chen** [comment]
Upgrade to WCDB 2.0, and here is the wiki for database corruption: https://github.com/Tencent/wcdb/wiki/Objc-%e6%8d%9f%e5%9d%8f%e3%80%81%e5%a4%87%e4%bb%bd%e3%80%81%e4%bf%ae%e5%a4%8d
