### ISSUE TITLE
How do I open an encrypted database？

### ISSUE THREAD

**Issue by BaronWj** [Tencent/wcdb#929]
### The language of WCDB

oc

### The version of WCDB

  - SQLiteRepairKit (1.2.2):
    - WCDBOptimizedSQLCipher (~> 1.2.0)
  - WCDB (1.0.7.5):
    - SQLiteRepairKit (~> 1.2.0)
    - WCDBOptimizedSQLCipher (~> 1.2.0)
  - WCDBOptimizedSQLCipher (1.2.1)

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

![image](https://user-images.githubusercontent.com/4156274/234182978-f964d999-5840-43aa-b90c-5ec09b31ba3c.png)

1、How do I open an encrypted database？

**Comment by Qiuwen-chen** [comment]
WCDB is based on SQLCipher, but we don't use the default configuration of SQLCipher. Thus this app may not support opening encrypted databases created by WCDB.

**Comment by BaronWj** [comment]
WCTDatabase *database = [[WCTDatabase alloc] initWithPath:path];
NSData *password = [@"MyPassword" dataUsingEncoding:NSASCIIStringEncoding];
[database setCipherKey:password];


"MyPassword" is the password to open the database？

**Comment by Qiuwen-chen** [comment]
> WCTDatabase *database = [[WCTDatabase alloc] initWithPath:path]; NSData *password = [@"MyPassword" dataUsingEncoding:NSASCIIStringEncoding]; [database setCipherKey:password];
> 
> "MyPassword" is the password to open the database？

Yes

**Comment by BaronWj** [comment]
![image](https://user-images.githubusercontent.com/4156274/236137652-d765cc41-f3b7-4c92-80b9-2912b6079aef.png)
I tried to open with a password. But it failed.

**Comment by Qiuwen-chen** [comment]
> WCDB is based on SQLCipher, but we don't use the default configuration of SQLCipher. Thus this app may not support opening encrypted databases created by WCDB.

I have explained it here.
