### ISSUE TITLE
Objective-C++编译结果和OC不一样啊  

### ISSUE THREAD

**Issue by GodL** [Tencent/wcdb#93]
把.m改为.mm后本来能编译过的现在无法编译成功.
第一个就是 无法把一个integer赋值给一个枚举
第二个就是实现的一个strongify宏报错

**Comment by GodL** [comment]
自从把.m改成.mm  注释后的代码都给我报错

**Comment by RingoD** [comment]
请提供错误信息

**Comment by GodL** [comment]
<img width="760" alt="qq20170716-0 2x" src="https://user-images.githubusercontent.com/15048055/28244504-5713d7be-6a1f-11e7-9794-8d529d2a3e06.png">
<img width="492" alt="qq20170716-1 2x" src="https://user-images.githubusercontent.com/15048055/28244507-599fe270-6a1f-11e7-96f7-c229e7ced388.png">

**Comment by RingoD** [comment]
直接将整型赋值给enum类型，是不规范的做法。
你可以加一个类型转换一下。或者将`Build Setting`->`Language - C++`->`C++ Language Dialect`改为`GNU++98`
