### ISSUE TITLE
Does the migration not support encryption?

### ISSUE THREAD

**Issue by JvanChow** [Tencent/wcdb#931]
### The language of WCDB
> e.g. Objective-C

### The version of WCDB
> e.g. v2.0.0

### The platform of WCDB
> e.g. iOS

### The installation of WCDB
> e.g. Cocoapods

### What's the issue?
Does the migration not support encryption?
when db setCipherKey，report error code 26 not a database file

**Comment by Qiuwen-chen** [comment]
Supported in the newly released WCDB 2.0.1
