### ISSUE TITLE
Data migrate not support encrypted db.

### ISSUE THREAD

**Issue by JvanChow** [Tencent/wcdb#932]
### The language of WCDB
> e.g. Objective-C

### The version of WCDB
> e.g. v2.0.1

### The platform of WCDB
> e.g. iOS

### The installation of WCDB
> e.g. Cocoapods

### What's the issue?
If source or target db is encrypted, migration not work.

// 1.create source db
NSString *sourceDBPath = [[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0] stringByAppendingPathComponent:@"sourceDB.sqlite"];
WCTDatabase *sourceDatabase = [[WCTDatabase alloc] initWithPath:sourceDBPath];
[sourceDatabase setCipherKey:[@"test" dataUsingEncoding:NSUTF8StringEncoding]]; **// encrypt**
// source db create table
BOOL ret = [sourceDatabase createTable:@"sourceSampleTable" withClass:Sample.class];

// 2.insert data to source db
Sample* oldObject1 = [[Sample alloc] init];
oldObject1.identifier = 1;
oldObject1.content = @"oldContent1";
Sample* oldObject2 = [[Sample alloc] init];
oldObject2.identifier = 2;
oldObject2.content = @"oldContent2";
ret &= [sourceDatabase insertObjects:@[oldObject1, oldObject2] intoTable:@"sourceSampleTable"];

// 3.create target db
NSString *targetDBPath = [[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0] stringByAppendingPathComponent:@"targetDB.sqlite"];
WCTDatabase* targetDatabase = [[WCTDatabase alloc] initWithPath:targetDBPath];
[targetDatabase setCipherKey:[@"test" dataUsingEncoding:NSUTF8StringEncoding]]; **// encrypt**

[targetDatabase filterMigration:^(WCTMigrationUserInfo *info) {
    if([info.table isEqualToString:@"sourceSampleTable"]) {
        info.sourceTable = @"sourceSampleTable";
        info.sourceDatabase = sourceDBPath;
    }
}];

//4.trace error
[targetDatabase traceError:^(WCTError * _Nonnull error) {
    __strong typeof(weakDB) database = weakDB;
    NSLog(@"errorCode %lu", error.code); **// errorCode 26, not a db file**
}];

// 5.target db create table
BOOL ret = [targetDatabase createTable:@"sourceSampleTable" withClass:Sample.class]; **// ret is false, and report error 26**

**Comment by Qiuwen-chen** [comment]
Now only databases with the same encryption key and the same encryption configuration are supported for migration.

**Comment by JvanChow** [comment]
> Now only databases with the same encryption key and the same encryption configuration are supported for migration.

@Qiuwen-chen 
It works when the cipher version is 4. However the cipher version 3 cannot work.
Please see demo for details.

[TestMigration.m.zip](https://github.com/Tencent/wcdb/files/11339599/TestMigration.m.zip)

**Comment by Qiuwen-chen** [comment]
> > Now only databases with the same encryption key and the same encryption configuration are supported for migration.
> 
> @Qiuwen-chen It works when the cipher version is 4. The cipher version 3 cannot work, although they are the same encryption key and the same encryption configuration. Please see demo for details.
> 
> [TestMigration.m.zip](https://github.com/Tencent/wcdb/files/11339599/TestMigration.m.zip)

The wiki below will explain this issue:

https://github.com/Tencent/wcdb/wiki/Objc-%E6%95%B0%E6%8D%AE%E8%BF%81%E7%A7%BB#%E5%8A%A0%E5%AF%86%E6%95%B0%E6%8D%AE%E5%BA%93%E8%B7%A8%E6%95%B0%E6%8D%AE%E5%BA%93%E8%BF%81%E7%A7%BB%E7%9A%84%E9%99%90%E5%88%B6
