### ISSUE TITLE
AutoBackup not work.

### ISSUE THREAD

**Issue by JvanChow** [Tencent/wcdb#933]
### The language of WCDB
> e.g. Objective-C

### The version of WCDB
> e.g. v2.0.1

### The platform of WCDB
> e.g. iOS

### The installation of WCDB
> e.g. Cocoapods

### What's the issue?
Test -[WCTDatabase enableAutoBackup:] not work, but the -[BackupTests test_auto_backup_when_checkpointed] is OK.

// 1.create db
NSString *dbPath = [[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0] stringByAppendingPathComponent:@"testDB.sqlite"];
WCTDatabase *database = [[WCTDatabase alloc] initWithPath:dbPath];

// 2. check backup file is exist
NSString *firstMaterialPath = [self.database.path stringByAppendingString:@"-first.material"];
BOOL ret = [[NSFileManager defaultManager] fileExistsAtPath:firstMaterialPath]; // return false

// 3.config and insert new data
[database enableAutoCheckpoint:NO];
[database enableAutoBackup:YES];
TestCaseObject *object = [TestCaseObject objectWithIdentifier:6 andContent:[NSString stringWithFormat:@"abc_%d", 6]];
[database insertObject:object intoTable:@"TestCaseObject"];

[database passiveCheckpoint];

[NSThread sleepForTimeInterval:12]; // refer to BackupTests: [NSThread sleepForTimeInterval:WCDB::OperationQueueTimeIntervalForBackup + self.delayForTolerance];

// 4. check backup file is exist
ret = [[NSFileManager defaultManager] fileExistsAtPath:firstMaterialPath]; // return false
NSLog(@"ret %d", ret); // ret 0

**Comment by Qiuwen-chen** [comment]
Now only databases with the same key are supported for migration.

**Comment by Qiuwen-chen** [comment]
The backup time interval is ten minutes, and the time interval in the unit test is reduced for quick testing.
