### ISSUE TITLE
WCDB 安卓没有 2.0 版本吗

### ISSUE THREAD

**Issue by HenryWu01** [Tencent/wcdb#938]
### The language of WCDB
Java

### The version of WCDB
2.0.1

### The platform of WCDB
Android

### The installation of WCDB
Maven

### What's the issue?
I want to use WCDB 2.0.1 on Android via Room adapter.

However, wcdb on android only have version 1.0.8, there is no plain to add android support on wcdb 2.0+?

**Comment by Qiuwen-chen** [comment]
WCDB  for Java will come up a few mouthes later. But Room adapter will not be available any more.
