### ISSUE TITLE
数据库崩溃

### ISSUE THREAD

**Issue by fypyxz** [Tencent/wcdb#942]
> e.g. Objective-C
> e.g. v2.0.1
> e.g. iOS
> e.g. Cocoapods

崩溃线程：#29 Thread
SIGSEGV
SEGV_ACCERR
0
sqlcipher
sqlite3LockAndPrepare + 88
1
WCDBObjc
WCDB::HandleStatement::prepare(WCDB::UnsafeStringView const&) + 140
2
WCDBObjc
WCDB::HandleStatement::prepare(WCDB::UnsafeStringView const&) + 140
3
WCDBObjc
WCDB::HandleStatement::prepare(WCDB::Statement const&) + 100
4
WCDBObjc
WCDB::AbstractHandle::getCipherPageSize() + 96
5
WCDBObjc
WCDB::Repair::FullCrawler::work() + 104
6
WCDBObjc
WCDB::Repair::FactoryRetriever::restore(WCDB::UnsafeStringView const&) + 856
7
WCDBObjc
WCDB::Repair::FactoryRetriever::work() + 200
8
WCDBObjc
_ZNSt3__110__function6__funcIZN4WCDB13InnerDatabase8retrieveERKNS_8functionIFvddEEEE3$_3NS_9allocatorIS9_EEFvvEEclEv + 344
9
WCDBObjc
WCDB::HandlePool::drain(std::__1::function<void ()> const&) + 152
10
WCDBObjc
WCDB::InnerDatabase::close(std::__1::function<void ()> const&) + 468
11
WCDBObjc
WCDB::InnerDatabase::retrieve(std::__1::function<void (double, double)> const&) + 108
12
WCDBObjc
-[WCTDatabase(Repair) retrieve:] + 172

关联数据库操作线程1：
#0 Thread
0
libsystem_kernel.dylib
___psynch_cvwait + 8

2
libc++.1.dylib
std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3
WCDBObjc
WCDB::SharedLock::lockShared() + 116
4
WCDBObjc
WCDB::SharedLockGuard::SharedLockGuard(WCDB::SharedLock&) + 28
5
WCDBObjc
WCDB::InnerDatabase::initialize() + 72
6
WCDBObjc
WCDB::InnerDatabase::getHandle() + 372
7
WCDBObjc
WCDB::InnerDatabase::beginTransaction() + 44

关联数据库操作线程2：
#24 com.Tencent.WCDB.Queue.Operation
0
libsystem_kernel.dylib
___psynch_cvwait + 8

2
libc++.1.dylib
std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3
WCDBObjc
WCDB::SharedLock::lockShared() + 116
4
WCDBObjc
WCDB::SharedLockGuard::SharedLockGuard(WCDB::SharedLock&) + 28
5
WCDBObjc
WCDB::InnerDatabase::initialize() + 72
6
WCDBObjc
WCDB::InnerDatabase::checkIntegrity(bool) + 52
7
WCDBObjc
WCDB::Core::integrityShouldBeChecked(WCDB::UnsafeStringView const&) + 68
8
WCDBObjc
WCDB::OperationQueue::onTimed(WCDB::OperationQueue::Operation const&, WCDB::OperationQueue::Parameter const&) + 184
9
WCDBObjc
WCDB::TimedQueue<WCDB::OperationQueue::Operation, WCDB::OperationQueue::Parameter>::loop(std::__1::function<void (WCDB::OperationQueue::Operation const&, WCDB::OperationQueue::Parameter const&)> const&) + 188
10
WCDBObjc
WCDB::OperationQueue::main() + 96
11
WCDBObjc
std::__1::__async_assoc_state<void, std::__1::__async_func<void (WCDB::AsyncQueue::*)(), WCDB::AsyncQueue*> >::__execute() + 48
12
WCDBObjc
_ZNSt3__114__thread_proxyB6v15006INS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEMNS_19__async_assoc_stateIvNS_12__async_funcIMN4WCDB10AsyncQueueEFvvEJPSA_EEEEEFvvEPSF_EEEEEPvSK_ + 72

**Comment by Qiuwen-chen** [comment]
Is it easy to repeat? What is the crash rate?

**Comment by fypyxz** [comment]
不容易复现，Bugly统计崩溃率：0.79%，基本都是这个类型的崩溃

**Comment by Qiuwen-chen** [comment]
If you are a Tencent employee, you can contact me via rtx

**Comment by fypyxz** [comment]
> If you are a Tencent employee, you can contact me via rtx

普通使用者

**Comment by Qiuwen-chen** [comment]
Since no such crash has been found in WeChat, and the retrieve interface is not commonly used, a crash rate of 0.79% is acceptable. We do not intend to continue analyzing this issue. If you have a stable way to reproduce this problem, we can take a look.
