### ISSUE TITLE
iOS上，创建数据库和table都没有问题，插入数据也ok，但是就是查询不到数据，这是为什么呢？如何debug呢。我用的2.0.1版本

### ISSUE THREAD

**Issue by TimmyLee** [Tencent/wcdb#943]
iOS上，创建数据库和table都没有问题，插入数据也ok，但是就是查询不到数据，这是为什么呢？如何debug呢。我用的2.0.1版本

**Comment by TimmyLee** [comment]
复现了，场景是这样的：
1.创建数据库+table
2.insert数据
3.查询数据，能查到数据
4.杀掉app，重启
5.创建数据库+table
6.查询数据
7.查不到数据

**Comment by TimmyLee** [comment]
调用的是getObjectsOfClass:fromTable方法

**Comment by TimmyLee** [comment]
开源东西不会这么烂吧

**Comment by Qiuwen-chen** [comment]
We are not looking at github all the time. 

If you raise an issue, please wait patiently for a reply. 

Here's what you need: https://github.com/Tencent/wcdb/wiki/Objc-%e7%9b%91%e6%8e%a7%e4%b8%8e%e9%94%99%e8%af %af%e5%a4%84%e7%90%86
