### ISSUE TITLE
DBDumpUtil.java open db file fail

### ISSUE THREAD

**Issue by hahaha28** [Tencent/wcdb#944]
### The language of WCDB

java

### The version of WCDB

1.0.8

### The platform of WCDB

android

### The installation of WCDB

maven

### What's the issue?

https://github.com/Tencent/wcdb/blame/8a87b1e28c054c175c3afdd0e72fe1c0dfb43339/android/jni/com_tencent_wcdb_repair_DBDumpUtil.cpp#L330
The DBDumpUtil.cpp line 330, why the key length is 7 ? And open encrypt db file will fail.

**Comment by hahaha28** [comment]
@Qiuwen-chen help🙏

**Comment by Qiuwen-chen** [comment]
No idea. WCDB Android will be deprecated. WCDB Java is developing. Please wait.
