### ISSUE TITLE
Open db fail didn't call errorHandler

### ISSUE THREAD

**Issue by hahaha28** [Tencent/wcdb#945]
### The language of WCDB

> java

### The version of WCDB

> 1.0.8

### The platform of WCDB

> Android

### The installation of WCDB

> Maven

### What's the issue?

> open db fail didn't call errorHandler

> https://github.com/Tencent/wcdb/blob/8a87b1e28c054c175c3afdd0e72fe1c0dfb43339/android/room/src/main/java/com/tencent/wcdb/room/db/WCDBOpenHelper.java#LL82C1-L99C1

WCDBOpenHelper.java line 89, when the db is onCorruption, the dbObj is not null but dbRef[0] is null. Why not call getWrappedDb(SQLiteDatabase sqLiteDatabase)?

**Comment by hahaha28** [comment]
@Qiuwen-chen help

**Comment by Qiuwen-chen** [comment]
No idea. WCDB Android will be deprecated. WCDB Java is developing. Please wait.
