### ISSUE TITLE
The db-wal file grow infinitely. Resulting in poor db read and write performance.

### ISSUE THREAD

**Issue by echoyin** [Tencent/wcdb#946]
### The language of WCDB

> Objective-C

### The version of WCDB

> e.g. v1.0.7.5

### The platform of WCDB

> macOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

> ![pages more than 100](https://github.com/Tencent/wcdb/assets/10231470/896f99df-80fc-41ef-9900-decf7c086a74)
>![wal grow infinitely](https://github.com/Tencent/wcdb/assets/10231470/458a05ca-e5d6-4dfb-865f-59fc46c46b4d)

**Comment by echoyin** [comment]
I tried to do checkpoint manually with the following code, it returned YES. But it didn't take effect, and the wal file is still growing infinitely.
BOOL res = [self.dataBase exec:WCDB::StatementPragma().pragma(WCDB::Pragma::WalCheckpoint)];
How should I prevent the wal file from growing infinitely, or how can I make the manual checkpoint take effect?

**Comment by Qiuwen-chen** [comment]
Please try WCDB 2.0

**Comment by echoyin** [comment]
> Please try WCDB 2.0

Thanks for reply. Upgrade to v2.0.1. It works.
