### ISSUE TITLE
WINQ如何根据多个字段进行排序

### ISSUE THREAD

**Issue by mongelly** [Tencent/wcdb#95]
例如原始的SQL语句是这样的：
select * from table1 order by column1,column2 desc;
用WINQ的语法怎么实现？

**Comment by RingoD** [comment]
WINQ请参考：https://github.com/Tencent/wcdb/wiki/iOS-macOS使用教程#字段组合
CRUD接口请参考：https://github.com/Tencent/wcdb/wiki/基础类、CRUD与Transaction#数据操作
sample代码请参考：https://github.com/Tencent/wcdb/blob/master/apple/sample/convenient/sample_convenient_main.mm

**Comment by mongelly** [comment]
看到sample了，之前没注意到，谢谢。
