### ISSUE TITLE
请问wcdb在并发写的时候性能会急剧劣化吗

### ISSUE THREAD

**Issue by JeremyLiao** [Tencent/wcdb#950]
### The language of WCDB

>  Java 

### The version of WCDB

> v1.0.8

### The platform of WCDB

> Android

### The installation of WCDB

>  AAR Package 

### What's the issue?

请问wcdb在并发写的时候性能会急剧劣化吗

**Comment by Qiuwen-chen** [comment]
No, concurrent writing to the same DB will become serial writing.
