### ISSUE TITLE
 'Types.h' file not found

### ISSUE THREAD

**Issue by zhazhaDan** [Tencent/wcdb#951]
你好，在最新tag '2.0.2'版本中新加的文件 'Types.h'和 libwebp库中文件重名，会导致项目编译失败，请问能否解决，用其他引用方式呢 
<img width="265" alt="image" src="https://github.com/Tencent/wcdb/assets/11848919/7148e391-d980-4f49-b5e0-c1cb3201990c">
<img width="278" alt="image" src="https://github.com/Tencent/wcdb/assets/11848919/165e64ae-686a-4d7b-bc4b-b5cdc6aaf401">

**Comment by Qiuwen-chen** [comment]
Will be handled next week, please wait.

**Comment by Qiuwen-chen** [comment]
Fixed in WCDB 2.0.2.5.
