### ISSUE TITLE
'CaseInsensitiveList.hpp' file not found

### ISSUE THREAD

**Issue by LisonFan** [Tencent/wcdb#952]
### The language of WCDB

> Objective-C

### The version of WCDB

> v2.0.2

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?
![image](https://github.com/Tencent/wcdb/assets/9424775/07b644f9-886f-4a34-8b1b-7adf75bbf6d4)

**Comment by Lincktang** [comment]
有一样的问题，这个有解决么

**Comment by Qiuwen-chen** [comment]
Fixed in WCDB 2.0.2.5.
