### ISSUE TITLE
Manually execute checkpoint and report an error

### ISSUE THREAD

**Issue by echoyin** [Tencent/wcdb#953]
### The language of WCDB

> e.g. Objective-C

### The version of WCDB

> e.g. v2.0.1

### The platform of WCDB

> e.g.macOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

> During the process of reading and writing 17w files, manually execute the checkpoint, and keep reporting errors, as shown in the screenshot below.
> ERROR: 10, disk I/O error
> What's the reason for this error? How to solve this problem?
![checkpoint error](https://github.com/Tencent/wcdb/assets/10231470/5cfa8c13-d758-476b-a5d6-3cebd8a1c845)

**Comment by Qiuwen-chen** [comment]
WCDB performs checkpoint automatically, so you don't need to do it manually. 

If you really want to checkpoint, please use -[WCTDatabase truncateCheckpoint] or -[WCTDatabase passiveCheckpoint].

**Comment by echoyin** [comment]
> WCDB performs checkpoint automatically, so you don't need to do it manually.
> 
> If you really want to checkpoint, please use -[WCTDatabase truncateCheckpoint] or -[WCTDatabase passiveCheckpoint].

I found that #ifdef WCDB_TESTS is used in WCTDatabase+Test.h (the screenshot below), which makes it impossible to use the methods defined in WCTDatabase+Test.h in my project. Can I remove #ifdef WCDB_TESTS? Will this have any effect on my project?
![iShot_2023-06-12_15 19 50](https://github.com/Tencent/wcdb/assets/10231470/3aab1388-5b53-4ce9-b5b6-22b5d4747dff)

**Comment by echoyin** [comment]
> You can remove it, or just define WCDB_TESTS when you compile WCDB.

Ok, thanks for reply.
