### ISSUE TITLE
如何按照指定条件插入数据

### ISSUE THREAD

**Issue by muken88** [Tencent/wcdb#955]
WCDB(2.0.0) Objective-C iOS Cocoapods 
When inserting data [database insertObject: intoTable:table]; Data is inserted later in the table by default. 
Now I have a field time with 10 pieces of data that are 1, 2, 3, 4, 5, 7, 9, 10, 11. How do I insert time=6 in front of 7 so that the result is 1, 2, 3, 4, 5, 6, 7, 9, 10, 11

**Comment by Qiuwen-chen** [comment]
The order of the data in the database does not matter. You can use ORDER BY to specify the order when reading.

**Comment by muken88** [comment]
If there is a large number of data in the table, such as millions of items, will the query speed affect performance if the ORDER BY is specified?

**Comment by muken88** [comment]
If there is a large number of data in the table, such as millions of items, will the query speed affect performance if the ORDER BY is specified?  And the Order by ordering in memory involves a performance penalty

**Comment by muken88** [comment]
Is there a way to insert data based on the size of a field? So when you read it, you read it sequentially and you don't need to sort it

**Comment by Qiuwen-chen** [comment]
No such thing.
