### ISSUE TITLE
WCDBSwift/Insert.swift:84: Assertion failed: Auto-increment inserts do not support conflict action!

### ISSUE THREAD

**Issue by DrunkardSworder** [Tencent/wcdb#956]
### The language of WCDB

> Swift

### The version of WCDB

> v2.0.2.5

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

for var object in objects {
                let isAutoIncrement = object.isAutoIncrement
                encoder.isPrimaryKeyEncoded = !isAutoIncrement
                try object.encode(to: encoder)
                try handle.step()
                assert(!useConfliction || !isAutoIncrement,
                       "Auto-increment inserts do not support conflict action!")
                if !useConfliction && isAutoIncrement {
                    object.lastInsertedRowID = handle.lastInsertedRowID
                }
                handle.reset()
            }
我发现2.0.2之后新添加了 assert(!useConfliction || !isAutoIncrement,
                       "Auto-increment inserts do not support conflict action!")，我们之前项目中有同事有错误的使用情况，但是在之前的版本里似乎是正常运行的，项目中有个bug是有小部分用户的手机会出现主线程卡死，不知道有没有关系呢？
崩溃报错
Thread 1: Assertion failed: Auto-increment inserts do not support conflict action!

**Comment by Qiuwen-chen** [comment]
It can not cause lag. You should analyze the actual all stack of the lag.
