### ISSUE TITLE
TableCodable的属性问题

### ISSUE THREAD

**Issue by Lincktang** [Tencent/wcdb#958]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?
遵循TableCodable协议的类，无法定义[String: Any]的类型，但是实际使用中很多情况是不知道value是何类型的
> Post the outputs or screenshots for errors.
> ![image](https://github.com/Tencent/wcdb/assets/10082241/51a0e8fc-1afb-485c-8418-ca2ce8fec8dc)
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
Here is the wiki  for this:https://github.com/Tencent/wcdb/wiki/Swift-%e8%87%aa%e5%ae%9a%e4%b9%89%e5%ad%97%e6%ae%b5%e6%98%a0%e5%b0%84%e7%b1%bb%e5%9e%8b

**Comment by Lincktang** [comment]
@Qiuwen-chen 这种方式是明确的知道所有的key值是哪些，才能使用，问题是这个属性是一个map，而且key有哪些是不确定的
