### ISSUE TITLE
请问有c++代码直接调用该数据库的代码示例吗

### ISSUE THREAD

**Issue by xionghengheng** [Tencent/wcdb#96]
rt

**Comment by RingoD** [comment]
WCDB主要提供OC接口，一些优化也是在OC层面做的，如果使用C++层的接口，则无法完整获得WCDB的特性。
也因此，暂不提供C++层面接口的调用。但你可以阅读源码了解到用法

**Comment by fantasticfears** [comment]
抱歉，我需要再提一下这个问题。既然现在这是一个开源项目了，那它的 roadmap 是怎么样的呢？
比如它在一段时间会只为了满足微信团队的需要，还或是会继续拓展使用范围，来适用类似这个主题使用 C++ 的需求？

**Comment by RingoD** [comment]
@fantasticfears  请不要在closed issue里讨论问题，麻烦另开一个
