### ISSUE TITLE
use where got error Cannot convert value of type 'UserModel.CodingKeys' to expected argument type 'String'

### ISSUE THREAD

**Issue by tomtao2022** [Tencent/wcdb#960]
model
public class UserModel: TableCodable {
    /// 主键自增id 
    var identifier: Int? = nil

    var uid: String = ""
    
    var name : String = ""

    var introduce : String = ""
    
    var sessionID: String = ""
    
    public enum CodingKeys : String,CodingTableKey {
       public typealias Root = UserModel
        public static let objectRelationalMapping = TableBinding(CodingKeys.self)
        case identifier = "id"
        case uid
        case name
        case introduce
        case sessionID
        
        //Column constraints for primary key, unique, not null, default value and so on. It is optional.
       public static var columnConstraintBindings: [CodingKeys: ColumnConstraintBinding]? {
            return [
                .identifier: ColumnConstraintBinding(isPrimary: true, isAutoIncrement: true)
            ]
        }
    }
}

use in other class
UserModel.Properties.introduce == "1000"

got error 
Cannot convert value of type 'UserModel.CodingKeys' to expected argument type 'String'

**Comment by Qiuwen-chen** [comment]
Please try wcdb 2.0
