### ISSUE TITLE
WCDB.swift和系统的SQLite3冲突，编译报错

### ISSUE THREAD

**Issue by Lincktang** [Tencent/wcdb#961]
### The language of WCDB
Objective-C, Swift 
> e.g. Objective-C, Swift or Java 

### The version of WCDB
v2.0.2 v2.0.2.5
> e.g. v1.0.5

### The platform of WCDB
iOS
> e.g. iOS, macOS or Android

### The installation of WCDB
Cocoapods
> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?
无论是使用2.0.2版本还是2.0.5版本，只要使用了WCDB都无法使用系统的SQLite3
为了验证问题，创建了一个纯净的项目，Podfile只是引入WCDB.swift，创建一个swift文件import对应的组件库，编译后报错
Could not build Objective-C module 'SQLite3'

> Post the outputs or screenshots for errors.
> ![image](https://github.com/Tencent/wcdb/assets/10082241/168fd1ad-8581-4ab7-abc4-9a85be9635ba)
> Explain what you want by example or code **in English**.
Podfile如下：
```
target 'TestWCDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestWCDB
  pod 'WCDB.swift', '2.0.2.5'

  target 'TestWCDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestWCDBUITests' do
    # Pods for testing
  end

end
```
TestWCDBClass.swift如下：
```
import Foundation
import WCDBSwift
import SQLite3
```
编译后直接报错

**Comment by Qiuwen-chen** [comment]
WCDB already contains a SQLite internally. You cannot link two SQLites at the same time.
