### ISSUE TITLE
Compile Failed when pod with OpenCV

### ISSUE THREAD

**Issue by lbininhbl** [Tencent/wcdb#962]
### The language of WCDB

> Swift

### The version of WCDB

> v2.0.2.5

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

Xcode Project compile failed when pod 'OpenCV'. 

![image](https://github.com/Tencent/wcdb/assets/5364138/fddfa089-7f0d-4327-aa11-58b15ee23020)

**Comment by lbininhbl** [comment]
Compile successfully only drag opencv2.framework into project rather than via Cocoapods.

**Comment by Qiuwen-chen** [comment]
Will be fixed in next version.

**Comment by Qiuwen-chen** [comment]
Fixed
