### ISSUE TITLE
WCDB编译SQLite报错问题……

### ISSUE THREAD

**Issue by Lincktang** [Tencent/wcdb#963]
### The language of WCDB
Objective-C, Swift
> e.g. Objective-C, Swift or Java 

### The version of WCDB
v2.0.2.5
> e.g. v1.0.5

### The platform of WCDB
iOS
> e.g. iOS, macOS or Android

### The installation of WCDB
Cocoapods
> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?
使用WCDB时候，依赖的WCDBOptimizedSQLCipher和系统的SQLite3冲突，编译后报错Redefinition of 'sqlite3_file'
> Post the outputs or screenshots for errors.
> ![image](https://github.com/Tencent/wcdb/assets/10082241/e2458393-c63c-4c22-84ec-53a9c4e8b60e)
> Explain what you want by example or code **in English**.

@Qiuwen-chen 使用的是最新版本的WCDB，确实还是编译报错，问题一直存在。
为了做验证我单独使用WCDBOptimizedSQLCipher的1.4.1版本也会和SQLite3冲突，这个问题一直没有解决。
这个是我的Mainifest.lock文件，确实是最新版本
```
PODS:
  - WCDB (2.0.2.5):
    - WCDB/no-arc (= 2.0.2.5)
    - WCDBOptimizedSQLCipher (~> 1.4.1)
  - WCDB/no-arc (2.0.2.5):
    - WCDBOptimizedSQLCipher (~> 1.4.1)
  - WCDBOptimizedSQLCipher (1.4.1)

DEPENDENCIES:
  - WCDB (= 2.0.2.5)

SPEC REPOS:
  trunk:
    - WCDB
    - WCDBOptimizedSQLCipher

SPEC CHECKSUMS:
  WCDB: 09d4197ade5b7eb59661928be087f5f22a677367
  WCDBOptimizedSQLCipher: 880ec8aa6cda6b27e4c72b30bf0cc01771deda6f

PODFILE CHECKSUM: a2a7bb1774e4df3b4961d8b3763b5a8d25fde61c

COCOAPODS: 1.12.1
```

**Comment by Qiuwen-chen** [comment]
之前的回复好像你不理解还是没看到？我再解释下吧。

WCDB内部是包含了一个SQLite的，你同时引入WCDB和SQLite的时候，相当于链接了两个SQLite，必然有符号冲突。所以同一个工程中不能同时使用WCDB和SQLite。如果真要用，请把WCDB编译成动态库。

**Comment by Lincktang** [comment]
@Qiuwen-chen 请教一下，我用cocoapods导入WCDB，如何能够保证他是一个动态库，不和系统的SQLite3冲突呢，有什么特殊的配置可以做到么
