### ISSUE TITLE
No member named 'as' in 'WCTProperty'

### ISSUE THREAD

**Issue by vanemu** [Tencent/wcdb#964]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

Objective-C

### The version of WCDB

> e.g. v1.0.5

v2.0.2.5

### The platform of WCDB

> e.g. iOS, macOS or Android

 iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

WCTResultList resultList = {Sample.AllProperties};
resultList.push_back((Sample.amount_1 + Sample.amount_2).total().as(OERecord.total_spent));

or

SELECT customer_id, SUM(total_amount) AS total_spent
FROM Orders
GROUP BY customer_id
HAVING SUM(total_amount) > 1000;

This was possible in the previous 1.x version, how does it work now in 2.x? No ad keyword found, how do I currently implement a sql query like the one above?

**Comment by Qiuwen-chen** [comment]
You can write a code like this:

**Comment by Qiuwen-chen** [comment]
You can write a code like this:

WCDB::ResultColumns resultColumns = Sample.allProperties;
    WCDB::Expression sum = (Sample.amount_1 + Sample.amount_2).sum();
    resultColumns.push_back(WCDB::ResultColumn(sum).as("total_spent"));
    WCDB::StatementSelect select = WCDB::StatementSelect().select(resultColumns).from("Order").group(Sample.customer_id).having(sum > 1000);
    
    WCTColumnsXRows* rows = [self.database getRowsFromStatement:select];
