### ISSUE TITLE
按照wiki上面调用backupKit.run()后，应用在nantive层崩溃

### ISSUE THREAD

**Issue by cangbing2003** [Tencent/wcdb#966]
引用方式：implementation "com.tencent.wcdb:wcdb-android:$wcdbVersion"
wcdbVersion = "1.0.8"

 RepairKit.MasterInfo.save(db, db.getPath() + "-mbak", getKey().getBytes());
                            Log.e(TAG, "backUpDb success");
                            BackupKit backupKit = new BackupKit(db, db.getPath() + "-backup", getKey().getBytes(),0, null);
                           int result = backupKit.run();
                           Log.e(TAG, "backUpDb data result = " + result);
                           backupKit.release();

崩溃信息：

出错堆栈

1	#00 pc 000000000003eabc /data/app/~~KviQKod1e219XokSVmThdQ==/com.xx.xx-J--VXA6ps6W_yqy9hHMH7w==/lib/arm64/libwcdb.so (mm_backup_statistics+4) [arm64-v8a::5d8c5aaaa7fc79a803f73e5f50d4e51f]
2	#01 pc 0000000000032e98 /data/app/~~KviQKod1e219XokSVmThdQ==/com.xx.xx-J--VXA6ps6W_yqy9hHMH7w==/lib/arm64/libwcdb.so [arm64-v8a::5d8c5aaaa7fc79a803f73e5f50d4e51f]
3	#02 pc 000000000021a354 /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) [arm64-v8a::a5e73a0aec5744ea99a09aa21e5f11f1]
4	#03 pc 0000000000209a9c /apex/com.android.art/lib64/libart.so (nterp_helper+1948) [arm64-v8a::a5e73a0aec5744ea99a09aa21e5f11f1]
5	#04 pc 000000000020a254 /apex/com.android.art/lib64/libart.so (nterp_helper+3924) [arm64-v8a::a5e73a0aec5744ea99a09aa21e5f11f1]
6	#05 pc 000000000020b074 /apex/com.android.art/lib64/libart.so (nterp_helper+7540) [arm64-v8a::a5e73a0aec5744ea99a09aa21e5f11f1]
7	#06 pc 000000000020a254 /apex/com.android.art/lib64/libart.so (nterp_helper+3924) [arm64-v8a::a5e73a0aec5744ea99a09aa21e5f11f1]
8	#07 pc 000000000020b074 /apex/com.android.art/lib64/libart.so (nterp_helper+7540) [arm64-v8a::a5e73a0aec5744ea99a09aa21e5f11f1]
9	#08 pc 000000000021096c /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+556) [arm64-v8a::a5e73a0aec5744ea99a09aa21e5f11f1]
10	#09 pc 000000000027990c /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+184) [arm64-v8a::a5e73a0aec5744ea99a09aa21e5f11f1]
11	#10 pc 000000000060fed0 /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460) [arm64-v8a::a5e73a0aec5744ea99a09aa21e5f11f1]
12	#11 pc 00000000006572f8 /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1288) [arm64-v8a::a5e73a0aec5744ea99a09aa21e5f11f1]
13	#12 pc 00000000000b8b98 /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) [arm64-v8a::25eadd32a5b6753e7e58e01ae8014530]
14	#13 pc 0000000000055794 /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) [arm64-v8a::25eadd32a5b6753e7e58e01ae8014530]
15	java:
16	com.tencent.wcdb.repair.BackupKit.run(BackupKit.java:149)

**Comment by Qiuwen-chen** [comment]
WCDB for Android will be deprecated. WCDB Java is developing. Please wait.

**Comment by cangbing2003** [comment]
> WCDB for Android will be deprecated. WCDB Java is developing. Please wait.

when can we use the new sdk?

**Comment by Qiuwen-chen** [comment]
Two or three months later.
