### ISSUE TITLE
“Objc 数据迁移”教程中，迁移例子的代码写错了

### ISSUE THREAD

**Issue by oqsh** [Tencent/wcdb#967]
### The language of WCDB
Objective-C

### The version of WCDB
newest

### The platform of WCDB
iOS

### The installation of WCDB
Cocoapods

### What's the issue?
1. 图中红框里的 targetPath 应该是 sourcePath？
2. 代码最后一行的 targetSampleTable 创建，应该放在 filterMigration 之前？

<img width="941" alt="image" src="https://github.com/Tencent/wcdb/assets/30433920/b42547d0-a4ed-44c6-956b-819c2e946dd0">

**Comment by Qiuwen-chen** [comment]
The "targetPath" is modified to "sourcePath". The targetSampleTable can be created either before or after filterMigration.

**Comment by oqsh** [comment]
This is an automatic reply, confirming that your email was received.I will reply as soon as possible.Thank you
