### ISSUE TITLE
WCTDatabase分类中的方法无法使用

### ISSUE THREAD

**Issue by sosolittle** [Tencent/wcdb#968]
### The language of WCDB

> e.g. Objective-C

### The version of WCDB

> e.g.  2.0.2.5

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods,

### What's the issue?
WCTDatabase分类中的方法无法使用
![image](https://github.com/Tencent/wcdb/assets/13461109/444ae204-c371-468b-b581-0aa8c619cda3)

**Comment by Qiuwen-chen** [comment]
These methods are for testing only and are not recommended to use.
