### ISSUE TITLE
syntax error, SQL:ALTER TABLE  ADD COLUMN from TEXT

### ISSUE THREAD

**Issue by sosolittle** [Tencent/wcdb#969]
### The language of WCDB

> e.g. Objective-C,

### The version of WCDB

> e.g. v1.1.0

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?
![image](https://github.com/Tencent/wcdb/assets/13461109/e6d9e1cb-103a-40e5-a411-af5f8056f21c)
![image](https://github.com/Tencent/wcdb/assets/13461109/7b25b16e-0ff3-4a42-9a69-d6fe242ef0da)
大佬，请问一下是我不会用吗？

**Comment by sosolittle** [comment]
其他字段都没有问题，就这两个字段就有问题

**Comment by Qiuwen-chen** [comment]
Column name can not be the keywords of sqlite: https://sqlite.org/lang_keywords.html
