### ISSUE TITLE
数据库如何解密?

### ISSUE THREAD

**Issue by h421933728** [Tencent/wcdb#97]
请教一下我用wcdb对数据库进行加密，创建db如下
![image](https://user-images.githubusercontent.com/8063451/28244103-b88fc48c-6a13-11e7-93c9-539f1a2d77cb.png)

由于调查bug的需要，我拿到沙盒的test.db后，我需要打开db，应该如何对test.db进行解密？

我尝试在终端通过如下方式解密，但是一直提示："file is encrypted or is not a database"，是我操作不对吗？
![image](https://user-images.githubusercontent.com/8063451/28244122-228a67d4-6a14-11e7-8f6e-59808922452c.png)

**Comment by jackytianhappy** [comment]
@h421933728 方式不对，加密解密参考这个：http://blog.csdn.net/tianyitianyi1/article/details/51258296

**Comment by RingoD** [comment]
@h421933728 还需要设置cipher_page_size。`PRAGMA cipher_page_size=4096`

**Comment by h421933728** [comment]
@RingoD 加上cipher_page_size可以转换成功，真棒，非常感谢！！！

**Comment by Jasonvvei** [comment]
你好，加了cipher_page_size还是提示："file is encrypted or is not a database"，难道还需要进行什么特别操作？
```
sqlcipher test.db
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> PRAGMA key = '123456';
sqlite> PRAGMA cipher_page_size = 4096;
sqlite> ATTACH DATABASE 'plaintext.db' AS plaintext KEY '';
Error: file is encrypted or is not a database
sqlite>
```
![6bab2454-8fba-4bde-a012-d93f12784fc1](https://user-images.githubusercontent.com/14148888/29963244-bc78ccde-8f38-11e7-813d-ed54c086a046.png)

**Comment by RingoD** [comment]
@Jasonvvei 如果是WCDB创建的数据库，只要设置正确的key和4096 cipher_page_size即可打开。你可以用sample的数据库进行尝试。
对于你的例子，可以尝试去掉attach

**Comment by edongyu** [comment]
@Jasonvvei ，我也遇到了同样的问题， 尝试了几次，分享一下结论：**命令参数顺序很重要！**

项目参数用的跟微信的一样， SQLiteCipherSpec cipher = new SQLiteCipherSpec().setPageSize(1024).setSQLCipherVersion(1);

使用这个参数，在windows上有线程的工具可以直接输入密码打开数据库。

使用sqlcipher命令行，会有一些坑，注意PRAGMA语句的使用顺序

如下代码顺序可以成功打开数据

```
ro@xx:~/code$ sqlcipher 78d7092db4364413.db 
SQLCipher version 3.8.6 2014-08-15 11:46:33
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> PRAGMA cipher_default_kdf_iter = 4000;
sqlite> PRAGMA key = '123456';
sqlite> PRAGMA cipher_use_hmac = OFF;
sqlite> PRAGMA cipher_page_size = 1024;
sqlite> SELECT count(*) FROM sqlite_master;
20
```
测试其他的顺序就会失败，比如：

```
ro@xx:~/code$ sqlcipher 78d7092db4364413.db  
SQLCipher version 3.8.6 2014-08-15 11:46:33
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> PRAGMA cipher_page_size = 1024;
sqlite> PRAGMA cipher_use_hmac = OFF;
sqlite> PRAGMA cipher_default_kdf_iter = 4000;
sqlite> PRAGMA key = '123456';
sqlite> SELECT count(*) FROM sqlite_master;
Error: file is encrypted or is not a database
```

**Comment by candRabbit** [comment]
请问 android 代码中如何 执行上述命令

**Comment by iamcxl369** [comment]
@candRabbit 这些命令的执行步骤是:
1.先把加密的数据库文件从手里里面copy到电脑上;
2.然后在电脑上编译安装sqlcipher;
3.然后通过sqlcipher在终端上执行上面的命令.

**Comment by iamcxl369** [comment]
**我现在碰到的问题:**
我通过Sqlcipher在电脑上解密数据库不成功.

我的操作步骤:
- 0x01. 在手机上创建一个非加密数据库,然后写入一些数据.

- 0x02. 基于第一步的数据,把非加密数据库迁移到wcdb中.

- 0x03. 在手机app中尝试读取0x02步骤迁移后的数据,可以正常读出;

- 0x04. 然后通过代码把wcdb加密后的数据库copy到电脑上通过下面命令操作:

```
➜  sqlcipher-master ./sqlcipher test-wcdb.db
SQLCipher version 3.20.1 2017-08-24 16:21:36
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> PRAGMA key = 'xxxxxx';
sqlite> PRAGMA cipher_page_size=4096;
sqlite> SELECT count(*) FROM sqlite_master;
0
sqlite> .databases
main: /home/iamcxl369/github/sqlcipher-master/test-wcdb.db
```
## 可以看到
数据库并没有通过sqlcipher解密出来. 看到的是空的.

**Comment by edongyu** [comment]
@candRabbit Android代码里面不用执行这些命令， 用wcdb的接口就可以得到解密后数据， 跟使用sqlite一样
