### ISSUE TITLE
Wiki 中有处单词拼写错误

### ISSUE THREAD

**Issue by siren186** [Tencent/wcdb#970]
### The language of WCDB

> C++

### The version of WCDB

> v2.0.2.5

### The platform of WCDB

> PC

### The installation of WCDB

> Git clone

### What's the issue?

> Wiki word spelling mistake

![QQ五笔截图未命名](https://github.com/Tencent/wcdb/assets/7559001/139b80c0-1dcc-4457-9bb1-5aac020b36f5)

**Comment by Qiuwen-chen** [comment]
Updated
