### ISSUE TITLE
Crash on iOS 14 when use XCode 15 beta_5

### ISSUE THREAD

**Issue by leipengiOS** [Tencent/wcdb#971]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.6

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
<img width="1064" alt="image" src="https://github.com/Tencent/wcdb/assets/106293696/23982975-f19e-4f56-83c3-2befdbe998b4">

> 
<img width="852" alt="image" src="https://github.com/Tencent/wcdb/assets/106293696/56343c6d-f297-4984-9ac5-0637a677a116">

> Explain what you want by example or code **in English**.

WCDB add column Crash on iOS 14 when use XCode 15 beta_5

**Comment by Qiuwen-chen** [comment]
Get

**Comment by Qiuwen-chen** [comment]
Upgrade WCDB to 2.0.3 and try again

**Comment by yhcflyy** [comment]
不需要升级最新wcdb，是由于xcode15重写了新的链接器导致，只需要在build setting - other linker flags中添加-Wl,-ld_classic即可，
https://developer.apple.com/forums/thread/736203
