### ISSUE TITLE
Swift project install with code archive compile error: umbrella header 'WCDBBridging.h' not found

### ISSUE THREAD

**Issue by CrashRain** [Tencent/wcdb#972]
### The language of WCDB

> Swift

### The version of WCDB

> v2.0.3

### The platform of WCDB

> iOS

### The installation of WCDB

> source code

### What's the issue?

<img width="1168" alt="image" src="https://github.com/Tencent/wcdb/assets/5134517/1d389877-d66c-41c3-bbe5-0cb10168a6c3">

how to fix it?

**Comment by Qiuwen-chen** [comment]
May be you xcode version is old

**Comment by CrashRain** [comment]
Xcode version is 14.3.1 (14E300c), create a new project, install with source code then archive, will show the error.

**Comment by Qiuwen-chen** [comment]
I also use this version. But I did not encounter this problem. If you can't solve it, you can send me the source code to reproduce the problem.

**Comment by CrashRain** [comment]
[WCDB_Test.zip](https://github.com/Tencent/wcdb/files/12297849/WCDB_Test.zip)
I remove the WCDB source code directory because of size limit, you should first put it into project directory.

**Comment by Qiuwen-chen** [comment]
Still no error. May be you should clean build folder and try again.

**Comment by gpr321** [comment]
编译WCDBSwift 的时候Edit scheme, 把 Build Configuration 改为 Release 再编译就会报这个错误. @Qiuwen-chen

**Comment by Miles-Matheson** [comment]
> [WCDB_Test.zip](https://github.com/Tencent/wcdb/files/12297849/WCDB_Test.zip) 由于大小限制，我删除了WCDB源代码目录，您应该先将其放入项目目录中。

请问兄台这个问题解决没， 我现在也遇到这个问题。 满脑子问号 哈哈哈

**Comment by CrashRain** [comment]
> > [WCDB_Test.zip](https://github.com/Tencent/wcdb/files/12297849/WCDB_Test.zip) 由于大小限制，我删除了WCDB源代码目录，您应该先将其放入项目目录中。
> 
> 请问兄台这个问题解决没， 我现在也遇到这个问题。 满脑子问号 哈哈哈

我直接用CocoaPods集成就好了，之前因为需要自己修改某些地方用的源码，没有找到原因。
