### ISSUE TITLE
WCDB.swift 2.0.3 如何在模型中使用Swift enum

### ISSUE THREAD

**Issue by xboy-im** [Tencent/wcdb#973]
### The language of WCDB

> Swift

### The version of WCDB

> e.g. v2.0.3

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

> 问题如标题所示

**Comment by Qiuwen-chen** [comment]
Enumeration types that implement ColumnCodable can be used in models normally.

**Comment by xboy-im** [comment]
> Enumeration types that implement ColumnCodable can be used in models normally.

`@objc(SVObjcLogMessageType) public enum SVLogMessageType: Int32, ColumnCodable {
    case quic = 1
    case player
    case mobile
    case all
    
    public init?(with value: FundamentalValue) {
        self.init(rawValue: value.int32Value)
    }

    public func archivedValue() -> FundamentalValue {
        FundamentalValue(self.rawValue)
    }

    public static var columnType: WCDBSwift.ColumnType {
        .integer32
    }
}`

我的代码是这样的，insert会报错

**Comment by Qiuwen-chen** [comment]
Update to new version and try again

**Comment by xboy-im** [comment]
> 

I used WCDB.swift 2.0.3

**Comment by Qiuwen-chen** [comment]
What error is it

**Comment by xboy-im** [comment]
> Update to new version and try again
<img width="646" alt="截屏2023-08-09 11 54 15" src="https://github.com/Tencent/wcdb/assets/5466295/786c6776-e6b6-4d5d-bfcd-f249e5c02d95">

**Comment by xboy-im** [comment]
> 

[ERROR] Code:Misuse Message:bad parameter or other API misuse,Path:/var/mobile/Containers/Data/Application/09EF9034-462C-411C-8346-29C8B177A588/Library/SVDB/Common/CommonDB.db,SQL:PRAGMA journal_mode,Source:SQLite

**Comment by Qiuwen-chen** [comment]
There is no FundamentalValue in 2.0.3 any more

**Comment by Qiuwen-chen** [comment]
This error is not caused by enum. You should check other logic of you database

**Comment by Qiuwen-chen** [comment]
This wiki might help you: https://github.com/Tencent/wcdb/wiki/Swift-%e7%9b%91%e6%8e%a7%e4%b8%8e%e9%94%99%e8%af%af%e5%a4%84%e7%90%86

**Comment by xboy-im** [comment]
> This wiki might help you: https://github.com/Tencent/wcdb/wiki/Swift-%e7%9b%91%e6%8e%a7%e4%b8%8e%e9%94%99%e8%af%af%e5%a4%84%e7%90%86

非常感谢，确实跟enum没有关系。我们app之前用的WCDB1.x版本，现在升级成WCDB.swift 2.0.3，模型SVLogMessage之前是OC类，现在将它用Swift重写了类名保持不变，这种情况如何处理？

**Comment by xboy-im** [comment]
> This wiki might help you: https://github.com/Tencent/wcdb/wiki/Swift-%e7%9b%91%e6%8e%a7%e4%b8%8e%e9%94%99%e8%af%af%e5%a4%84%e7%90%86

得到的错误日志是：API call with invalid database connection pointer，已经确认目前升级到了WCDB.swift 2.0.3

**Comment by Qiuwen-chen** [comment]
Analyze it yourself. Unless you confirm that it is a WCDB problem, then raise an issue

**Comment by losedMemory** [comment]
> > 
> 
> [错误]代码：误用消息：参数错误或其他API误用，路径：/var/mobile/Containers/Data/Application/09EF9034-462C-411C-8346-29C8B177A588/Library/SVDB/Common/CommonDB.db， SQL： PRAGMA Journal_mode，来源：SQLite

你解决这个问题了吗，我也是oc混编出现了这个问题
