### ISSUE TITLE
按照wiki进行的操作，发现canOpen=false，验证过数据库路径是正确的

### ISSUE THREAD

**Issue by xboy-im** [Tencent/wcdb#974]
### The language of WCDB

> Swift

### The version of WCDB

> WCDB.swift 2.0.3

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods
> Podfile 中添加 use_frameworks! :linkage => :static

### What's the issue?

> 创建表报错：API call with invalid database connection pointer

**Comment by Qiuwen-chen** [comment]
Send me the code to reproduce this problem

**Comment by xboy-im** [comment]
> Send me the code to reproduce this problem

<img width="894" alt="截屏2023-08-09 17 46 54" src="https://github.com/Tencent/wcdb/assets/5466295/d720d178-8d97-4f50-9189-3cb7e3e45aa5">

**Comment by Qiuwen-chen** [comment]
It must be some special case. I need a demo project to reproduce it, not just some code snippet.

**Comment by xboy-im** [comment]
> It must be some special case. I need a demo project to reproduce it, not just some code snippet.

我重新创建了一个Demo工程，用跟原工程同样的WCDB版本，同样的集成方式，同样的代码测试的是正常的，但是原工程里面一直不可用，也请同事帮忙检查了，都没有发现问题，这种情况还有什么排查方法吗？非常感谢

**Comment by xboy-im** [comment]
> No idea. Note that "API call with invalid database connection pointer" is not a error message from WCDB.

解决了，在Other linker flags里面增加-all_load，就可以了😭
