### ISSUE TITLE
ios启动崩溃

### ISSUE THREAD

**Issue by wqforever** [Tencent/wcdb#975]
### The language of WCDB

Objective-C,

### The version of WCDB

1.0.7.5

### The platform of WCDB

iOS

### The installation of WCDB

Cocoapods

### What's the issue?

启动崩溃
<img width="1767" alt="image" src="https://github.com/Tencent/wcdb/assets/15868474/69b8fe1b-8aa0-41ca-8428-34e59345f8ab">

**Comment by Qiuwen-chen** [comment]
Upgrade WCDB  to 2.0.3

**Comment by wqforever** [comment]
我们最低支持iOS10，升级不到2.0.3

**Comment by Qiuwen-chen** [comment]
You can compile with source code and configure wcdb to be compatible with lower versions.

**Comment by wqforever** [comment]
升级到2.0.3之后，还是有崩溃
![61692001705_ pic](https://github.com/Tencent/wcdb/assets/15868474/abb20927-7abe-4bd2-a167-0d713ce29fca)

**Comment by Qiuwen-chen** [comment]
It is an project configuration problem, not caused by WCDB.

**Comment by wqforever** [comment]
请问下是哪里的配置问题？能告知一下吗，谢谢

**Comment by ningcol** [comment]
升级到xcode15，启动的时候，WCDB_SYNTHESIZE崩溃了，14都没有问题
