### ISSUE TITLE
中文或UTF-8路径不支持

### ISSUE THREAD

**Issue by siren186** [Tencent/wcdb#977]
### The language of WCDB

> C++

### The version of WCDB

> v2.0.3

### The platform of WCDB

> Windows

### The installation of WCDB

> Git clone

### What's the issue?

> 中文路径不支持，含有 `UTF-8` 字符的路径也不支持。如：`C:\❄MyDoc\`
> 问题出在了：
> 1、如果我向 WCDB::Database( `path` ) 传参用 `UTF-8` 路径，WCDB 调用的 WinAPI 无法正确处理 UTF-8 路径，导致失败！
> 2、如果我向 WCDB::Database( `path` ) 传参用 `GBK` 路径，WCDB 调用的 WinAPI 成功，但底层 sqlite3_open( `path` ) 用的是 UTF-8 编码，导致失败！
>
> Windows 平台下，WCDB 处理字符串编码，没能和SQLite API 保持一致。

**Comment by Qiuwen-chen** [comment]
OK，I will fix it this week.

**Comment by Qiuwen-chen** [comment]
Fixed in WCDB 2.0.4
