### ISSUE TITLE
因为一些原因历史版本中有加密的也有不加密的，2.0之后的WCDB如何判断不加密的时候是否成功了？

### ISSUE THREAD

**Issue by JXUnx1** [Tencent/wcdb#978]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
You can user canOpen method to check it.

**Comment by huiyumiao** [comment]
2.0 版本已经没有 canOpen 方法了
Version 2.0 has no canOpen method to call

**Comment by huiyumiao** [comment]
> You need to import WCTDatabase+Test.h

这个分类中的确有这个方法，但是 import WCTDatabase+Test.h 之后还是报错说找不到 canOpen 这个方法，难道还需要其他什么操作吗？[抱拳]
