### ISSUE TITLE
Assertion.hpp file not found

### ISSUE THREAD

**Issue by wqforever** [Tencent/wcdb#979]
### The language of WCDB

> e.g. Objective-C, Swift or Java 
Objective-C

### The version of WCDB

> e.g. v1.0.5
2.0.3

### The platform of WCDB

> e.g. iOS, macOS or Android
iOS

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
<img width="1306" alt="image" src="https://github.com/Tencent/wcdb/assets/15868474/14f63129-0057-4693-8d1a-2a855007cbf8">

> Explain what you want by example or code **in English**.

**Comment by Qiuwen-chen** [comment]
Cocoapod has verified that WCDB can be compiled successfully when uploading Cocoapod, it should be a problem in your project.

**Comment by tigerzhang08** [comment]
> ### The language of WCDB
> > e.g. Objective-C, Swift or Java
> > Objective-C
> 
> ### The version of WCDB
> > e.g. v1.0.5
> > 2.0.3
> 
> ### The platform of WCDB
> > e.g. iOS, macOS or Android
> > iOS
> 
> ### The installation of WCDB
> > e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
> > Cocoapods
> 
> ### What's the issue?
> > Post the outputs or screenshots for errors.
> 
> <img alt="image" width="1306" src="https://private-user-images.githubusercontent.com/15868474/261485439-14f63129-0057-4693-8d1a-2a855007cbf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjQ1NDksIm5iZiI6MTcxNDM2NDI0OSwicGF0aCI6Ii8xNTg2ODQ3NC8yNjE0ODU0MzktMTRmNjMxMjktMDA1Ny00NjkzLThkMWEtMmE4NTUwMDdjYmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA0MTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2YjUxZmEyMTU3ZjljYmFkZjUyMGEzZTFjNjUyN2FiM2I3Y2QxNTk2MTIwNTU0NDNmOThmYjU0NmQ4MWUxYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.84vxdCRxs_f3tl5AuOV3jkyszrCAkGr3D8SimWT_OHs">
> > Explain what you want by example or code **in English**.

遇到了同样的问题，请问有解决方案吗？

**Comment by Qiuwen-chen** [comment]
> > ### The language of WCDB
> > > e.g. Objective-C, Swift or Java
> > > Objective-C
> > 
> > 
> > ### The version of WCDB
> > > e.g. v1.0.5
> > > 2.0.3
> > 
> > 
> > ### The platform of WCDB
> > > e.g. iOS, macOS or Android
> > > iOS
> > 
> > 
> > ### The installation of WCDB
> > > e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
> > > Cocoapods
> > 
> > 
> > ### What's the issue?
> > > Post the outputs or screenshots for errors.
> > 
> > 
> > <img alt="image" width="1306" src="https://private-user-images.githubusercontent.com/15868474/261485439-14f63129-0057-4693-8d1a-2a855007cbf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjQ1NDksIm5iZiI6MTcxNDM2NDI0OSwicGF0aCI6Ii8xNTg2ODQ3NC8yNjE0ODU0MzktMTRmNjMxMjktMDA1Ny00NjkzLThkMWEtMmE4NTUwMDdjYmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA0MTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2YjUxZmEyMTU3ZjljYmFkZjUyMGEzZTFjNjUyN2FiM2I3Y2QxNTk2MTIwNTU0NDNmOThmYjU0NmQ4MWUxYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.84vxdCRxs_f3tl5AuOV3jkyszrCAkGr3D8SimWT_OHs">
> > > Explain what you want by example or code **in English**.
> 
> 遇到了同样的问题，请问有解决方案吗？

There may exist another Assertion.hpp in your project. Find it and rename it will solve the problem.

**Comment by Kam-To** [comment]
Perhaps `-fcxx-modules` was added to your `Other C++ Flags`, remove it should works.

@Qiuwen-chen  and maybe those 'Not Found' files should be mark as public in WCDB target's build phase tab.
