### ISSUE TITLE
WAL模式下调试程序

### ISSUE THREAD

**Issue by mongelly** [Tencent/wcdb#98]
WCDB默认是采用WAL模式操作数据库的，但是在调试程序或者程序发生错误的时候经常需要查看sqlite中的原始数据，能否在api中增加一个方法可以临时性关闭wal模式或者手动进行checkpoint。

**Comment by alexlee002** [comment]
@RingoD WCDB对sqlite进行了修改， 不支持多进程打开， 那么如果你一边调试， 一边通过其他工具查看数据库数据的话， 我认为是会有问题的。

**Comment by mongelly** [comment]
@alexlee002 谢谢你的描述，我遇到的就是这个问题。如果在调试过程中APP发生崩溃或者意外中断，外部的查看工具是无法打开数据库文件的。

**Comment by RingoD** [comment]
@alexlee002 WCDB的文档没有指出不支持多进程打开。
@mongelly 数据库关闭时也会自动checkpoint。所以麻烦定位一下你的问题具体产生的原因，然后我们再想办法如何解决

**Comment by mongelly** [comment]
@RingoD  问题已解决，之前应该是外部的Sqlite工具对WAL的支持有问题导致数据库无法打开。谢谢
