### ISSUE TITLE
How to sort Chinese characters by PinYin

### ISSUE THREAD

**Issue by siren186** [Tencent/wcdb#980]
### The language of WCDB

> C++

### The version of WCDB

> v2.0.3

### The platform of WCDB

> Windows

### The installation of WCDB

> Git clone

### What's the issue?

> Two Questions:
> 1、I wanna call `sqlite3_create_collation(db, "PINYIN", SQLITE_UTF8, nullptr, &MyPinYinCompare);`
> to registry my custom collation `PINYIN`, for sorting Chinese characters by **拼音**
> 
> 2、I wanna call `sqlite3_create_function(db, "REGEXP", 2, SQLITE_UTF8, 0, &MyRegExp, 0, 0);`
> to registry my custom function `REGEXP`, for supporting **regular expressions** for sqlite3
> 
> So that I can use the query like this:
> ```
> SELECT name FROM table ORDER BY name COLLATE PINYIN WHERE name REGEXP '[0-9a-A]{0,3}'
> ```
>
> BUT I cannot find the way to do it by WCDB, I want to know how to implement my requirements by WCDB.

**Comment by Qiuwen-chen** [comment]
These are not supported yet. You can modify the source code of WCDB, or sort after reading the results from WCDB, which will not make much difference in performance.
