### ISSUE TITLE
编译的windows版本的dll，没有导出函数、类，要怎么调用？

### ISSUE THREAD

**Issue by 593607226** [Tencent/wcdb#983]
### The language of WCDB

c++

### The version of WCDB

v 2.0.3

### The platform of WCDB

windows10

### The installation of WCDB

Git clone

### What's the issue?
编译出来的wcdb.dll，是没有导出函数列表的，没有lib文件，我要动态链接进工程，要怎么做？直接使用报下面错误

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "protected: bool __cdecl WCDB::HandleORMOperation::createTable(class WCDB::UnsafeStringView const &,class WCDB::Binding const &)" (?createTable@HandleORMOperation@WCDB@@IEAA_NAEBVUnsafeStringView@2@AEBVBinding@2@@Z)，函数 "public: bool __cdecl WCDB::HandleORMOperation::createTable<class Config>(class WCDB::UnsafeStringView const &)" (??$createTable@VConfig@@@HandleORMOperation@WCDB@@QEAA_NAEBVUnsafeStringView@1@@Z) 中引用了该符号	myservice	E:\Code\agent\build\src\service\DlpService.obj	1	
错误	LNK2019	无法解析的外部符号 "protected: class WCDB::BaseAccessor const * __cdecl WCDB::Field::getAccessor(void)const " (?getAccessor@Field@WCDB@@IEBAPEBVBaseAccessor@2@XZ)，函数 "public: void __cdecl WCDB::StatementOperation::bindObject<class Config>(class Config const &,class WCDB::Field const &,int)" (??$bindObject@VConfig@@@StatementOperation@WCDB@@QEAAXAEBVConfig@@AEBVField@1@H@Z) 中引用了该符号	service	E:\Code\agent\build\src\service\DlpService.obj	1

**Comment by Qiuwen-chen** [comment]
Fixed in WCDB 2.0.4. Now only static libraries can be compiled, dll is not supported yet.
