### ISSUE TITLE
关于编译WCDB.DLL动态库的两个建议

### ISSUE THREAD

**Issue by siren186** [Tencent/wcdb#985]
### The language of WCDB

> C++

### The version of WCDB

> v2.0.4

### The platform of WCDB

> Windows

### The installation of WCDB

> Git clone

### What's the issue?

> 上一版本 `v2.0.3` 编译DLL是没有问题的。
> 造成 `v2.0.4` 编译不出的DLL的原因在于新加的宏 `WCDB_API` 。
> 这个宏在有 `cpp` 文件的类名前加没有问题，可以正确的导出这个类。
> 但对于**没有cpp文件的类**（模板类、简单类），或者类前置声明。是**无需添加该宏**来指定的。
> 没有cpp文件的类，其它模块通过 `#include *.hpp` 文件即可正常使用。指定了 `WCDB_API` 后反而会造成模板类编译不过。
> ## 所以，关于编译 DLL 动态库的两个建议：
> 1、恢复成原来没有 `WCDB_API` 前缀的形式，是可以通过CMake宏`CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`来正常导出的。
> 2、保持最新版现状，在**没有cpp文件的类**前去掉 `WCDB_API`。会有很多编译警告（C4251）忽略即可。
>
> 以上两种方式，都是可以编译出 WCDB.DLL 文件的
> WCDB.DLL 还是非常实用的，尤其很多模块共享同一数据库的时候。使用静态库太难受了，望采纳。

**Comment by Qiuwen-chen** [comment]
感谢建议。

**Comment by Qiuwen-chen** [comment]
Thanks for the suggestion! It helps a lot.

Exporting all symbols will cause the dll to be larger, so we tried to use WCDB_API to configure the export symbols in 2.0.4.

But after the configuration, some unresolveable compile errors come out(Even if some redundant WCDB_API is deleted).

Now `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` is set to export all symbols to compile the dll, please update to the latest code in the master branch.
