### ISSUE TITLE
windows下无法编译动态链接库

### ISSUE THREAD

**Issue by 593607226** [Tencent/wcdb#986]
### The language of WCDB

> C++

### The version of WCDB

> v2.0.4

### The platform of WCDB

> windows10

### The installation of WCDB

> Git clone

### What's the issue?

看CmakeLists.txt中，设置编译动态链接库的是下面几行，看起来不支持windows编译动态链接库
if (NOT DEFINED BUILD_SHARED_LIBS AND NOT DEFINED WIN32)
    set(BUILD_SHARED_LIBS ON)
endif ()

我将其修改为
if (NOT DEFINED BUILD_SHARED_LIBS AND DEFINED WIN32)
    set(BUILD_SHARED_LIBS ON)
endif ()

按动态链接库编译，可是报错，错误输出如下：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C3889	对类类型“std::equal_to<void>”的对象的调用: 未找到匹配的调用运算符	WCDB	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\list	1698	
错误	C3889	对类类型“std::equal_to<void>”的对象的调用: 未找到匹配的调用运算符	WCDB	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\list	1698	
错误	C3889	对类类型“std::equal_to<void>”的对象的调用: 未找到匹配的调用运算符	WCDB	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\list	1698	
错误	C3889	对类类型“std::equal_to<void>”的对象的调用: 未找到匹配的调用运算符	WCDB	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\list	1698	
错误	C3889	对类类型“std::equal_to<void>”的对象的调用: 未找到匹配的调用运算符	WCDB	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\list	1698	
错误	C3889	对类类型“std::equal_to<void>”的对象的调用: 未找到匹配的调用运算符	WCDB	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\list	1698	
错误	C3889	对类类型“std::equal_to<void>”的对象的调用: 未找到匹配的调用运算符	WCDB	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\list	1698	
错误	C3889	对类类型“std::equal_to<void>”的对象的调用: 未找到匹配的调用运算符	WCDB	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\list	1698	
错误	C3889	对类类型“std::equal_to<void>”的对象的调用: 未找到匹配的调用运算符	WCDB	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\list	1698	
错误	C3889	对类类型“std::equal_to<void>”的对象的调用: 未找到匹配的调用运算符	WCDB	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\list	1698	
错误	C3889	对类类型“std::equal_to<void>”的对象的调用: 未找到匹配的调用运算符	WCDB	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\list	1698	
错误	C3889	对类类型“std::equal_to<void>”的对象的调用: 未找到匹配的调用运算符	WCDB	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\list	1698	
错误	C3889	对类类型“std::equal_to<void>”的对象的调用: 未找到匹配的调用运算符	WCDB	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\list	1698	
错误	C3889	对类类型“std::equal_to<void>”的对象的调用: 未找到匹配的调用运算符	WCDB	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\list	1698	
错误	C2451	类型为“WCDB::Expression”的条件表达式无效	WCDB	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\list	1698	
错误	C3889	对类类型“std::equal_to<void>”的对象的调用: 未找到匹配的调用运算符	WCDB	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\list	1698	
错误	C2451	类型为“WCDB::Expression”的条件表达式无效	WCDB	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\list	1698

**Comment by Qiuwen-chen** [comment]
Please update to the latest code in the master branch.
