### ISSUE TITLE
windows平台c++使用wcdb.dll动态库崩溃

### ISSUE THREAD

**Issue by 593607226** [Tencent/wcdb#990]
### The language of WCDB

> C++

### The version of WCDB

> v2.0.4

### The platform of WCDB

> Windows10

### The installation of WCDB

> Git clone

### What's the issue?

执行查询崩溃，代码如下，最后一行崩了

std::unique_ptr<WCDB::Database> _database = nullptr;
	//wcdb数据库初始化
	_database = std::make_unique<WCDB::Database>("user.db");

	//wcdb全局错误监控
	WCDB::Database::globalTraceError([](const WCDB::Error& error) {
		assert(error.level != WCDB::Error::Level::Fatal);
		//LOG_ERROR() << error.getDescription().data();
		});

	if (!_database->tableExists("configTable").value())
	{
		_database->createTable<Config>("configTable");
	}
	if (!_database->tableExists("ruleTable").value())
	{
		_database->createTable<Config>("ruleTable");
	}
	WCDB::Optional<Config> object = _database->getFirstObject<Config>("configTable");

崩溃堆栈如下：
  	WCDB.dll!free_dbg_nolock(void * const block, const int block_use) 行 996	C++
 	WCDB.dll!_free_dbg(void * block, int block_use) 行 1030	C++
 	[外部代码]	
 	WCDB.dll!WCDB::Syntax::TableOrSubquery::~TableOrSubquery() 行 32	C++
 	WCDB.dll!WCDB::SpecifiedSyntax<WCDB::Syntax::TableOrSubquery,WCDB::SQL>::~SpecifiedSyntax<WCDB::Syntax::TableOrSubquery,WCDB::SQL>() 行 109	C++
 	WCDB.dll!WCDB::TableOrSubquery::~TableOrSubquery() 行 37	C++
 	[外部代码]	
 	ConsoleApplication1.exe!WCDB::_SyntaxList<WCDB::TableOrSubquery>::~_SyntaxList<WCDB::TableOrSubquery>() 行 127	C++
 	ConsoleApplication1.exe!WCDB::SyntaxList<WCDB::TableOrSubquery>::~SyntaxList<WCDB::TableOrSubquery>() 行 180	C++
 	ConsoleApplication1.exe!WCDB::Select<Config>::fromTable(const WCDB::UnsafeStringView & tableName) 行 94	C++
 	ConsoleApplication1.exe!WCDB::HandleORMOperation::getFirstObject<Config>(const WCDB::UnsafeStringView & table, const WCDB::Expression & where, const WCDB::SyntaxList<WCDB::OrderingTerm> & orders, const WCDB::Expression & offset) 行 222	C++
>	ConsoleApplication1.exe!main() 行 55	C++
 	[外部代码]	

析构崩溃了，可能是有些用到的类没有导出

**Comment by Qiuwen-chen** [comment]
https://stackoverflow.com/questions/35310117/debug-assertion-failed-expression-acrt-first-block-header
