### ISSUE TITLE
Change WCDB From Objective-C to Swift

### ISSUE THREAD

**Issue by NNlml** [Tencent/wcdb#993]
### The language of WCDB

> Objective-C and Swift 

### The version of WCDB

> OC is 1.0.7 Swift is 2.0.4

### The platform of WCDB

> iOS

### The installation of WCDB

>  Cocoapods

### What's the issue?

Our previous project used the OC version of WCDB, and when storing arrays and custom classes, there was already BLOB type data in the database. Now we want to replace it with the Swift version of WCDB. How can I read these data from the original database? And when writing, the Swift version of WCDB stores String-type arrays as Json. How can we store them directly in the original database?

**Comment by Qiuwen-chen** [comment]
The interfaces of Objc and Swift are equivalent and very close. The logic that Objc can implement can be implemented equally by Swift.

**Comment by NNlml** [comment]
您好




依守流莺
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/wcdb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月30日(星期三) 晚上7:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/wcdb] Change WCDB From Objective-C to Swift (Issue #993)





 
Closed #993 as completed.

**Comment by NNlml** [comment]
您好
可能用翻译出来的英文表述的不清楚. 我重新说明一下这个问题.
我们项目是准备把OC代码全面换成Swift代码, OC代码已经生成过数据库, 并且保存过二进制类型. 举例 一个NSArray数组.&nbsp;
NSArray数组在使用OC的WCDB的时候, 会被保存成BLOB类型. 假定字段名是str


这时候我把OC代码全面替换成Swift时, Swift定义这个字段类型 是 [String] , 但是在读取原来数据库str字段是读不出来报错的. 因为原str保存方式是BLOB, 按照swiftwcdb文档, swift的[String] 会被保存成Json.&nbsp;


这个可以上升到自定义类, 自定义类 class A , 有n个属性, 然后保存成数组, OC也是BLOB, 把数据库和Class A同时改写成Swift时 Swift定义肯定是[A] , 那么默认读取的时候是一定读不出来的. Swift里面会把A遵循 ColumnJsonCodable 协议, 保存是json形式.&nbsp;


目前已经通过重写&nbsp;public init(from decoder: Decoder) throws { 方法, 对这些单独的字段, 按照Data类型读出, 并且进行NSKeyedUnarchiver解档 得到了对应的数据. 这个问题已经解决了. 但是wcdbswift 并没有对这种情况进行demo说明. 希望未来能完善一下这块的说明, 或者希望能默认兼容一下.


谢谢




依守流莺
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Tencent/wcdb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月30日(星期三) 晚上7:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/wcdb] Change WCDB From Objective-C to Swift (Issue #993)





 
Closed #993 as completed.

**Comment by Qiuwen-chen** [comment]
OK
