### ISSUE TITLE
How to modify json type in SQL

### ISSUE THREAD

**Issue by PJYGit** [Tencent/wcdb#995]
### The language of WCDB

> Java 

### The version of WCDB

> v1.0.8

### The platform of WCDB

> Android

### The installation of WCDB

> Maven

### What's the issue?

> I got a column named "a" whose type is json, how do i modify the params in the json using sql, can i get an example?

**Comment by PJYGit** [comment]
https://www.sqlite.org/json1.html

**Comment by chancelee** [comment]
> ### The language of WCDB
> > Java
> 
> ### The version of WCDB
> > v1.0.8
> 
> ### The platform of WCDB
> > Android
> 
> ### The installation of WCDB
> > Maven
> 
> ### What's the issue?
> > I got a column named "a" whose type is json, how do i modify the params in the json using sql, can i get an example?

I suggest storing the JSON content in another table.

**Comment by Qiuwen-chen** [comment]
Json is not supported yet.
