### ISSUE TITLE
When to support json functions

### ISSUE THREAD

**Issue by PJYGit** [Tencent/wcdb#996]
### The language of WCDB

> Java 

### The version of WCDB

> v1.0.8

### The platform of WCDB

> Android

### The installation of WCDB

> Maven

### What's the issue?
<img width="1487" alt="WeChatWorkScreenshot_c566f858-3ba9-4907-beef-a78a0215b44c" src="https://github.com/Tencent/wcdb/assets/48624220/27a8dd04-0676-46a2-a583-e28403b72428">

no json function support

SQL: 
UPDATE 
	message
SET
	ref_content = json_replace(ref_content, '$.revoked', true)
WHERE
	uuid='123456'

Is this related to the wcdb version or android version or the DB impl of different phone brands?
Default SQLite supports it!

**Comment by chancelee** [comment]
This issue is not related to WCDB. It is because the SQLite version does not support it

**Comment by chancelee** [comment]
> ### The language of WCDB
> > Java
> 
> ### The version of WCDB
> > v1.0.8
> 
> ### The platform of WCDB
> > Android
> 
> ### The installation of WCDB
> > Maven
> 
> ### What's the issue?
> <img alt="WeChatWorkScreenshot_c566f858-3ba9-4907-beef-a78a0215b44c" width="1487" src="https://user-images.githubusercontent.com/48624220/264988660-27a8dd04-0676-46a2-a583-e28403b72428.png">
> no json function support
> 
> SQL: UPDATE message SET ref_content = json_replace(ref_content, '$.revoked', true) WHERE uuid='123456'
> 
> Is this related to the wcdb version or android version or the DB impl of different phone brands? Default SQLite supports it!

**This issue is not related to WCDB. It is because the SQLite version does not support it**

**Comment by Qiuwen-chen** [comment]
It‘s not in our road map yet.
