### ISSUE TITLE
联合体未初始化导致的崩溃问题

### ISSUE THREAD

**Issue by 593607226** [Tencent/wcdb#997]
### The language of WCDB

> C++

### The version of WCDB

> v2.0.4

### The platform of WCDB

> Windows10

### The installation of WCDB

> Git clone

### What's the issue?

使用visual studio2022调试代码，执行查询数据库操作，x64平台，在debug配置下正常运行，在release配置下崩溃。
代码如下：
std::unique_ptr<WCDB::Database> _database = std::make_unique<WCDB::Database>("user.db");
WCDB::Optional<Config1> wcdbConfig = _database->getFirstObject<Config>("messageTable", WCDB_FIELD(Config::LuaPassword) == "MyConfig");

崩溃堆栈如下：
WCDB.dll!WCDB::UnsafeStringView::operator=(const WCDB::UnsafeStringView & other) 行 60	C++
WCDB.dll!WCDB::Field::configWithBinding(const WCDB::Binding & binding, void * memberPointer) 行 55	C++
DLPPlugin.dll!WCDB::Field::Field<Message,std::string>(std::string * memberPointer) 行 54	C++
DLPPlugin.dll!DLPPlugin::UpdateDriverSwitcherFromDatebase() 行 394	C++
DLPPlugin.dll!DLPPlugin::DLPPlugin() 行 39	C++

![image](https://github.com/Tencent/wcdb/assets/28924232/11a7cf06-aee4-4ce4-bfb2-011aa9cb7786)

原因分析：
在Binding.cpp的getColumnName函数，在map中通过key找不到对应值，迭代器是m_fieldMap.end()，可是还是把迭代器中的值返回，导致写入非法内存。
![image](https://github.com/Tencent/wcdb/assets/28924232/638bb296-a02e-4ff8-be96-ae573a0b190c)
这里有WCTAssert断言，可是只在Debug生效，而问题只发生在Release配置。
具体原因是key不正确导致，key通过MemberPointer.cpp的castMemberPointer函数，将指向类成员变量的指针转为void*指针。可是指向类成员变量的指针T O::*memberPointer占四个字节，而void*指针占八个字节。而void*没有初始化操作，将四个字节拷贝到八个字节，有四个字节内存未可知，导致每次调用这个castMemberPointer获得的key内容不一致。Debug有对这个未初始化的内存默认赋值，而Release没有，就导致出现崩溃。
<img width="553" alt="1694141816287" src="https://github.com/Tencent/wcdb/assets/28924232/02fff045-2339-4d96-8bfb-c9928beb3de6">

将void*赋初值nullptr可修复此问题，测试正常。作者看看怎么改比较好。

![image](https://github.com/Tencent/wcdb/assets/28924232/08eb73cd-7fac-4e46-92df-9ad3f4ef17f2)

**Comment by 593607226** [comment]
测试代码：
![image](https://github.com/Tencent/wcdb/assets/28924232/2e771e02-5582-4347-8ea2-bb7976e9fc63)

**Comment by Qiuwen-chen** [comment]
Thanks a lot. We will fix it next week.

**Comment by Qiuwen-chen** [comment]
Fixed in the master branch.
