### ISSUE TITLE
从1.1.0升级到2.0.4 数据保存出现问题

### ISSUE THREAD

**Issue by cd-chen** [Tencent/wcdb#998]
从1.1.0升级到2.0.4之后，保存数据库出现错误
![WX20230908-172007@2x](https://github.com/Tencent/wcdb/assets/19301659/25d10b15-9709-4363-9d4f-c99dcd776710)
![WX20230908-172025@2x](https://github.com/Tencent/wcdb/assets/19301659/cb62cbfb-0467-424a-a4eb-c7c8d821ab71)
在1.1.0时这样配置没有问题

![WX20230908-172055@2x](https://github.com/Tencent/wcdb/assets/19301659/64d71c65-937e-4c16-8905-d0a3d3091830)
升级到2.0.4之后崩溃在ColumnIsBLOBType<NSData*>::asUnderlyingType(NSData* data)位置，data数据是deviceModel的内容

**Comment by Qiuwen-chen** [comment]
The WCTColumnCoding has changed.

**Comment by cd-chen** [comment]
@Qiuwen-chen 更新了WCTColumnCoding之后崩溃不崩溃了，但是之前1.1.0保存的数据读取不出来了，保存新的也保存失败了

```
2.0.4保存数据库的代码
+ (BOOL)updateWalletModel:(CLColdlarWalletModel *)walletModel {
    
    WCTDatabase *database = [CLDatabaseManager database];
    NSString *tableName = NSStringFromClass([CLColdlarWalletModel class]);
    // 建表
    [database createTable:tableName withClass:CLColdlarWalletModel.class];
    
    WCTTable *table = [database getTable:tableName withClass:CLColdlarWalletModel.class];
    
    return [database runTransaction:^BOOL(WCTHandle * _Nonnull) {
        [table deleteObjectsWhere:CLColdlarWalletModel.wallet_id == walletModel.wallet_id];
        BOOL result = [table insertOrReplaceObject:walletModel];
        CLLog(@"%@",result?@"更新成功":@"更新失败");
        return YES;
    }];
}
```

```
这个1.1.0保存数据库的代码
+ (BOOL)updateWalletModel:(CLColdlarWalletModel *)walletModel {
    
    WCTDatabase *database = [CLDatabaseManager database];
    NSString *tableName = NSStringFromClass([CLColdlarWalletModel class]);
    // 建表
    [database createTableAndIndexesOfName:tableName withClass:CLColdlarWalletModel.class];
    
    WCTTable *table = [database getTableOfName:tableName withClass:CLColdlarWalletModel.class];
    
    return [database runTransaction:^BOOL{
        [table deleteObjectsWhere:CLColdlarWalletModel.wallet_id == walletModel.wallet_id];
        BOOL result = [table insertOrReplaceObject:walletModel];
        CLLog(@"%@",result?@"更新成功":@"更新失败");
        return YES;
    }];
}
```
文档WCTTable获取方式为WCTTable* table = [database createTable:@"sampleTable" withClass:Sample.class]，实际2.0.4版本中createTable是获取不到WCTTable的，返回的是BOOL类型的

**Comment by Qiuwen-chen** [comment]
You should use getTable:withClass:, doc is updated.

**Comment by Qiuwen-chen** [comment]
This wiki might help you: https://github.com/Tencent/wcdb/wiki/Objc-%e7%9b%91%e6%8e%a7%e4%b8%8e%e9%94%99%e8%af%af%e5%a4%84%e7%90%86

**Comment by cd-chen** [comment]
@Qiuwen-chen 全局监控错误信息之后，保存数据库还是保存不成功
